Repository ARMmbed/mbed-os, pull requests merged in 2018-03, with the labels that each got.

#5548 Tests for SysTimer (the idle loop timer for tickless mode)
  TESTS/mbedmicro-rtos-mbed/systimer/main.cpp
  rtos/TARGET_CORTEX/SysTimer.cpp
  rtos/TARGET_CORTEX/SysTimer.h
  rtos/TARGET_CORTEX/mbed_rtx_idle.cpp
Labels: ready for merge, release-version: 5.8.0-rc1

#6240 Improve invalid configuration error messages
  tools/config/__init__.py
Labels: ready for merge, release-version: 5.8.0-rc1

#6231 pull request: add required info
  .github/pull_request_template.md
Labels: ready for merge, release-version: 5.7.7

#5993 Work around Arm Compiler 6 stdvector perfomance cliff
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge, release-version: 5.7.7

#5950 Reserve and Render header in managed BL mode
  tools/build_api.py
  tools/config/__init__.py
  tools/utils.py
Labels: ready for merge, release-version: 5.8.0-rc1

#6230 Add system_reset call
  TESTS/host_tests/system_reset.py
  TESTS/mbed_platform/system_reset/main.cpp
  drivers/CAN.cpp
  drivers/I2C.cpp
  drivers/PwmOut.h
  drivers/SPI.cpp
  drivers/SerialBase.cpp
  drivers/Ticker.h
  drivers/Timeout.h
  drivers/Timer.h
  features/nanostack/FEATURE_NANOSTACK/targets/TARGET_SL_RAIL/NanostackRfPhyEfr32.cpp
  hal/mbed_sleep_manager.c
  mbed.h
  platform/DeepSleepLock.h
  platform/mbed_interface.c
  platform/mbed_power_mgmt.h
  platform/mbed_sleep.h
  platform/mbed_wait_api_rtos.cpp
  platform/sleep.h
  rtos/TARGET_CORTEX/mbed_rtx_idle.cpp
  targets/TARGET_Atmel/TARGET_SAM_CortexM0P/drivers/system/reset/TARGET_SAMD21/reset.h
  targets/TARGET_Atmel/TARGET_SAM_CortexM0P/drivers/system/reset/TARGET_SAML21/reset.h
  targets/TARGET_Atmel/TARGET_SAM_CortexM0P/drivers/system/reset/TARGET_SAMR21/reset.h
  targets/TARGET_Atmel/TARGET_SAM_CortexM4/drivers/pmc/sleep.c
  targets/TARGET_NUVOTON/nu_timer.h
  targets/TARGET_ONSEMI/TARGET_NCS36510/sleep.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/i2c_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/pwmout_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/serial_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/spi_api.c
Labels: needs: review, release-version: 5.8.0-rc1

#6179 littlefs: Update to version 1.3
  .travis.yml
  features/filesystem/littlefs/TESTS/filesystem/dirs/main.cpp
  features/filesystem/littlefs/TESTS/filesystem_retarget/dirs/main.cpp
  features/filesystem/littlefs/littlefs/.gitignore
  features/filesystem/littlefs/littlefs/.travis.yml
  features/filesystem/littlefs/littlefs/DESIGN.md
  features/filesystem/littlefs/littlefs/Makefile
  features/filesystem/littlefs/littlefs/README.md
  features/filesystem/littlefs/littlefs/SPEC.md
  features/filesystem/littlefs/littlefs/emubd/lfs_emubd.c
  features/filesystem/littlefs/littlefs/lfs.c
  features/filesystem/littlefs/littlefs/lfs.h
  features/filesystem/littlefs/littlefs/lfs_util.h
  features/filesystem/littlefs/littlefs/tests/template.fmt
  features/filesystem/littlefs/littlefs/tests/test.py
  features/filesystem/littlefs/littlefs/tests/test_dirs.sh
  features/filesystem/littlefs/littlefs/tests/test_truncate.sh
  features/filesystem/littlefs/mbed_lib.json
Labels: needs: work, release-version: 5.8.0-rc1

#5900 Add NVStore (A.K.A SOTP) feature
  features/nvstore/README.md
  features/nvstore/TESTS/nvstore/functionality/main.cpp
  features/nvstore/mbed_lib.json
  features/nvstore/source/nvstore.cpp
  features/nvstore/source/nvstore.h
Labels: needs: review, release-version: 5.8.0-rc1

#6142 Add optional tracing to sleep manager lock/unlock
  hal/mbed_sleep_manager.c
  platform/mbed_power_mgmt.h
  platform/mbed_sleep.h
Labels: release-version: 5.8.0-rc1

#6251 Fixed Thread Commissioning issue in CoAP service
  features/nanostack/FEATURE_NANOSTACK/coap-service/source/coap_connection_handler.c
  features/nanostack/FEATURE_NANOSTACK/coap-service/source/coap_message_handler.c
  features/nanostack/FEATURE_NANOSTACK/coap-service/source/coap_service_api.c
  features/nanostack/FEATURE_NANOSTACK/coap-service/source/include/coap_connection_handler.h
  features/nanostack/FEATURE_NANOSTACK/coap-service/source/include/coap_message_handler.h
  features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/coap_message_handler/test_coap_message_handler.c
  features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/coap_service_api/coap_service_apitest.cpp
  features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/coap_service_api/test_coap_service_api.c
  features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/coap_service_api/test_coap_service_api.h
  features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/stub/coap_connection_handler_stub.c
  features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/stub/coap_connection_handler_stub.h
  features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/stub/coap_message_handler_stub.c
  features/nanostack/FEATURE_NANOSTACK/coap-service/test/coap-service/unittest/stub/coap_message_handler_stub.h
Labels: needs: CI

#6249 [feature-nrf528xx] Fix ISR stack size inconsistencies on NRF52 series
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_GCC_ARM/NRF52832.ld
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_IAR/nRF52832.icf
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_IAR/nRF52840.icf
Labels: ready for merge

#6246 C030 platform I2C initialisation fix
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/min_battery_voltage.c
Labels: needs: CI

#6234 [feature-nrf528xx] Extended PeripheralPins and pinmap for NRF52 series
  targets/TARGET_NORDIC/TARGET_NRF5x/PeripheralPinsDefault.c
  targets/TARGET_NORDIC/TARGET_NRF5x/object_owners.c
  targets/TARGET_NORDIC/TARGET_NRF5x/object_owners.h
  targets/TARGET_NORDIC/TARGET_NRF5x/pinmap_ex.c
  targets/TARGET_NORDIC/TARGET_NRF5x/pinmap_ex.h
Labels: needs: CI

#6228 Nuvoton: Rework us_ticker/lp_ticker with one H/W timer
  targets/TARGET_NUVOTON/TARGET_M451/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M451/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_M480/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M480/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_NANO100/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_NANO100/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_NUC472/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_NUC472/us_ticker.c
Labels: needs: CI

#6215 USBDevice HAL specification
  TESTS/host_tests/pyusb_basic.py
  TESTS/usb_device/basic/USBTester.cpp
  TESTS/usb_device/basic/USBTester.h
  TESTS/usb_device/basic/main.cpp
  hal/mbed_usb_phy.cpp
  hal/usb_phy_api.h
  platform/USBPhy.h
  targets/TARGET_NXP/TARGET_LPC176X/usb/USBEndpoints_LPC17_LPC23.h
  targets/TARGET_NXP/TARGET_LPC176X/usb/USBHAL_LPC17.cpp
  targets/TARGET_NXP/TARGET_LPC176X/usb/USBPhyHw.h
  targets/targets.json
  tools/build_travis.py
  usb/device/USBDevice/EndpointResolver.cpp
  usb/device/USBDevice/EndpointResolver.h
  usb/device/USBDevice/USBDescriptor.h
  usb/device/USBDevice/USBDevice.cpp
  usb/device/USBDevice/USBDevice.h
  usb/device/USBDevice/USBDevice_Types.h
Labels: needs: review

#6143 Correct mbed export with multiple --source params
  tools/project.py
Labels: release-version: 5.7.7

#6275 NRF52: Customize STDIO pins from config system
  targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/PeripheralNames.h
  targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52840/PeripheralNames.h
Labels: ready for merge, release-version: 5.7.7

#6146 Correct gcc m33 floating point handling
  tools/toolchains/__init__.py
  tools/toolchains/gcc.py
Labels: ready for merge, release-version: 5.7.7

#6173 Modifies error text reported from RTX from 'underflow' to 'overflow'
  rtos/TARGET_CORTEX/mbed_rtx_handlers.c
Labels: ready for merge

#6268 Unittests fixed
  features/cellular/UNITTESTS/at/at_cellularstack/test_at_cellularstack.cpp
Labels: release-version: 5.7.7

#6202 Fix max32625mbed
  targets/TARGET_Maxim/TARGET_MAX32625/PeripheralPins.c
  targets/TARGET_Maxim/TARGET_MAX32625/TARGET_MAX32625MBED/PinNames.h
  targets/TARGET_Maxim/TARGET_MAX32625/TARGET_MAX32625NEXPAQ/PinNames.h
  targets/TARGET_Maxim/TARGET_MAX32625/analogin_api.c
  targets/TARGET_Maxim/TARGET_MAX32625/i2c_api.c
  targets/TARGET_Maxim/TARGET_MAX32625/serial_api.c
  targets/TARGET_Maxim/TARGET_MAX32625/spi_api.c
  targets/TARGET_Maxim/TARGET_MAX32625/us_ticker.c
Labels: ready for merge, release-version: 5.7.7

#6102 Add support for STEVAL-3DP001V1 board
  features/unsupported/USBDevice/targets/TARGET_STM/USBHAL_IP_OTGFSHS.h
  features/unsupported/USBDevice/targets/TARGET_STM/USBHAL_STM32.h
  features/unsupported/USBHost/targets/TARGET_STM/USBHALHost_STM.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_STEVAL_3DP001V1/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_STEVAL_3DP001V1/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_STEVAL_3DP001V1/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_STEVAL_3DP001V1/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_gpio_ex.h
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
  tools/build_travis.py
Labels: Scope: new-target, ready for merge, release-version: 5.7.7

#6235 mcu_lpc546xx: move "release_versions" to children and fix clock
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/TARGET_LPCXpresso/mbed_overrides.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/mbed_overrides.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_LPCXpresso/mbed_overrides.c
  targets/targets.json
Labels: ready for merge, release-version: 5.7.7

#6263 Clarify intention between comparison to zero and the shift operation
  events/equeue/equeue.c
Labels: ready for merge, release-version: 5.7.7

#6285 Improve json schema and schema errors
  tools/config/__init__.py
  tools/config/definitions.json
Labels: ready for merge, release-version: 5.8.0-rc2

#5751 Add tests for Watchdog HAL API
  TESTS/host_tests/sync_on_reset.py
  TESTS/host_tests/watchdog_reset.py
  TESTS/mbed_drivers/watchdog/Watchdog_tests.h
  TESTS/mbed_drivers/watchdog/main.cpp
  TESTS/mbed_drivers/watchdog_reset/Watchdog_reset_tests.h
  TESTS/mbed_drivers/watchdog_reset/main.cpp
  TESTS/mbed_hal/watchdog/main.cpp
  TESTS/mbed_hal/watchdog/watchdog_api_tests.h
  TESTS/mbed_hal/watchdog_reset/main.cpp
  TESTS/mbed_hal/watchdog_reset/watchdog_reset_tests.h
  TESTS/mbed_hal/watchdog_timing/main.cpp
  TESTS/mbed_hal/watchdog_timing/watchdog_timing_tests.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/watchdog_api.c
  targets/TARGET_STM/TARGET_STM32F4/watchdog_api.c
Labels: ready for merge

#6286 Small typo fixes in readme.md files
  events/README.md
  features/FEATURE_BLE/targets/TARGET_CORDIO/README.md
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_MCU_NRF51822/sdk/README.md
  features/mbedtls/README.md
  features/nvstore/README.md
Labels: ready for merge

#6280 NVStore: Enclose header file with DOXYGEN_ONLY option as well.
  features/nvstore/source/nvstore.h
Labels: ready for merge, release-version: 5.8.1

#6271 Allow build profiles to omit language entries
  tools/build_api.py
Labels: ready for merge, release-version: 5.7.7, release-version: 5.8.1

#6226 rtl8195am: fix ARM section error
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/analogin_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/TOOLCHAIN_ARM_STD/rtl8195a.sct
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/rtl8195a_init.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/log_uart_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/pwmout_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/serial_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/spi_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/trng_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/api/platform/platform_stdlib.h
Labels: ready for merge, release-version: 5.7.7, release-version: 5.8.1

#6171 Update mbed-coap to version 4.3.0
  features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md
  features/FEATURE_COMMON_PAL/mbed-coap/mbed-coap/sn_coap_protocol.h
  features/FEATURE_COMMON_PAL/mbed-coap/module.json
  features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.9.0-rc1

#6164 Adding Laird BL652 as new target
  targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_MTB_LAIRD_BL652/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/TARGET_MTB_LAIRD_BL652/device.h
  targets/targets.json
Labels: Scope: new-target, ready for merge, release-version: 5.7.7, release-version: 5.8.1

#6257 Fix for Crash dump formatting issues and adding more info to crash dump
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_ARM/except.S
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.S
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_IAR/except.S
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.c
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.h
Labels: ready for merge

#6266 Corrected STM+K64F eth driver flagging, memory allocation and thread init
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/TARGET_K64F/hardware_init_MK64F12.c
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/TARGET_K66F/hardware_init_MK66F18.c
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/k64f_emac.cpp
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/k64f_emac.h
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/k64f_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/stm32f2_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F2/stm32f2_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_ARCH_MAX/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_ARCH_MAX/stm32f4_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MBED_CONNECT_ODIN/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MBED_CONNECT_ODIN/stm32f4_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MTB_UBLOX_ODIN_W2/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MTB_UBLOX_ODIN_W2/stm32f4_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_NUCLEO_F429ZI/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_NUCLEO_F429ZI/stm32f4_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_NUCLEO_F439ZI/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_NUCLEO_F439ZI/stm32f4_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_UBLOX_C030/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_UBLOX_C030/stm32f4_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_UBLOX_EVK_ODIN_W2/stm32f4_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F7/TARGET_DISCO_F746NG/stm32f7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F7/TARGET_DISCO_F769NI/stm32f7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F7/TARGET_NUCLEO_F746ZG/stm32f7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F7/TARGET_NUCLEO_F756ZG/stm32f7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F7/TARGET_NUCLEO_F767ZI/stm32f7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F7/stm32f7_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac.cpp
  features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac.h
  features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac_config.h
  targets/targets.json
Labels: needs: CI

#6241 Corrected STM eth driver flagging, memory allocation and thread init
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
Labels: needs: preceding PR, needs: work

#6297 [feature-nrf528xx] NRF52 series PWM reimplementation for SDK 14.2
  targets/TARGET_NORDIC/TARGET_NRF5x/PeripheralPinsDefault.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/objects.h
  targets/TARGET_NORDIC/TARGET_NRF5x/pinmap_ex.c
  targets/TARGET_NORDIC/TARGET_NRF5x/pinmap_ex.h
  targets/TARGET_NORDIC/TARGET_NRF5x/pwmout_api.c
Labels: ready for merge

#6323 fatfs: Revert "Update error code mapping"
  features/filesystem/fat/FATFileSystem.cpp
Labels: BREAKING-CHANGE, ready for merge, release-version: 5.8.0-rc2

#6301 Cellular tests: fixed cellular greentea tests by adding timeout as it…
  features/cellular/TESTS/cellular/cellular_all/network.cpp
Labels: ready for merge, release-version: 5.8.0-rc2

#6327 cellular doxygen updates
  features/cellular/easy_cellular/CellularConnectionFSM.h
  features/cellular/easy_cellular/EasyCellularConnection.h
Labels: release-version: 5.8.0-rc2

#6328 MIMXRT: define PullUp default value
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PinNames.h
Labels: release-version: 5.8.0-rc2

#6290 Cellular tests: fix power mgmt stub
  features/cellular/UNITTESTS/target_h/platform/mbed_power_mgmt.h
Labels: ready for merge, release-version: 5.8.1

#6341 Add lorawan and nvstore examples for testing.
  tools/test/examples/examples.json
Labels: needs: CI, release-version: 5.8.0-rc2

#6352 Release candidate for mbed-os-5.8.0-rc2
  features/cellular/TESTS/cellular/cellular_all/network.cpp
  features/cellular/easy_cellular/CellularConnectionFSM.h
  features/cellular/easy_cellular/EasyCellularConnection.h
  features/filesystem/fat/FATFileSystem.cpp
  features/nvstore/source/nvstore.h
  mbed.h
  targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/PeripheralNames.h
  targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52840/PeripheralNames.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PinNames.h
  tools/config/__init__.py
  tools/config/definitions.json
  tools/test/examples/examples.json
Labels: needs: CI

#6287 MCUXpresso_MCUS: Apply K64F us_ticker fix across all MCU's
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/us_ticker.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/us_ticker.c
Labels: ready for merge, release-version: 5.7.7, release-version: 5.8.1

#6322 Add ATECC508A connection details in README.md
  features/atcryptoauth/ATCRYPTOAUTH-XPRO-B-K64F2.jpg
  features/atcryptoauth/ATCRYPTOAUTH-XPRO-B-Shield.jpg
  features/atcryptoauth/README.md
Labels: ready for merge

#6315 EFM32: make gpio interrupts faster by offloading expected pin state check to user
  targets/TARGET_Silicon_Labs/TARGET_EFM32/gpio_irq_api.c
Labels: ready for merge, release-version: 5.8.1

#6314 Cellular: ATHandler write improvements.
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
Labels: ready for merge, release-version: 5.8.1

#6311 mts_mdot_f411re: Fix for Multi-Tech mDot IAR linker script
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/device/TOOLCHAIN_IAR/stm32f411xe.icf
Labels: ready for merge, release-version: 5.8.1

#6310 MCUXpresso: Fix test failures seen with ci-test shield
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/peripheral_clock_defines.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/i2c_api.c
Labels: ready for merge, release-version: 5.8.1

#6303 [ATCmdParser]: Align `process_oob()` to `vrecv()`'s newline handling
  platform/ATCmdParser.cpp
Labels: ready for merge, release-version: 5.8.1

#6300 Fixes to LoRa PHY
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHYAS923.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN779.cpp
  features/lorawan/lorastack/phy/LoRaPHYEU433.cpp
  features/lorawan/lorastack/phy/LoRaPHYEU868.cpp
  features/lorawan/lorastack/phy/LoRaPHYIN865.cpp
  features/lorawan/lorastack/phy/LoRaPHYKR920.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.cpp
Labels: ready for merge, release-version: 5.8.1

#6288 Fix macro definition of iodefine_typedef for RZ_A1H
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/inc/iodefines/iodefine_typedef.h
Labels: ready for merge, release-version: 5.8.1

#6274 events: Added note about immediate firing of periodic events
  events/EventQueue.h
Labels: Scope: refactor, ready for merge, release-version: 5.8.1

#6198 Flash support: Add flash support for LPC54114 & LPC546XX
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/flash_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/objects.h
  targets/targets.json
Labels: ready for merge, release-version: 5.8.1

#5106 Timeout & LowPowerTimeout tests
  TESTS/mbed_drivers/lp_timeout/main.cpp
  TESTS/mbed_drivers/timeout/main.cpp
  TESTS/mbed_drivers/timeout/timeout_tests.h
Labels: ready for merge, release-version: 5.8.1

#6092 mbed-mesh-api: add JSON help
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed_lib.json
Labels: ready for merge, release-version: 5.8.1

#6292 rtl8195am - improve credentials handling
  targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.cpp
Labels: ready for merge

#6345 Cellular: Fixed sms unit tests.
  features/cellular/UNITTESTS/at/at_cellularsms/test_at_cellularsms.cpp
Labels: ready for merge, release-version: 5.8.1

#6238 Remove windup behavior from break_dispatch
  events/equeue/equeue.c
  events/equeue/equeue.h
  events/equeue/tests/tests.c
Labels: BREAKING-CHANGE, ready for merge, release-version: 5.9.0-rc1

#6329 Cellular: add callback API
  features/cellular/framework/API/CellularNetwork.h
Labels: ready for merge, release-version: 5.8.1

#6270 Add parameter in tools settings to show error/warning as Link
  tools/default_settings.py
  tools/settings.py
  tools/toolchains/__init__.py
Labels: needs: review, release-version: 5.9.0-rc1

#6361 Convert option list to unicode
  tools/utils.py
Labels: ready for merge, release-version: 5.8.1

#6359 NVStore: add comments in header file for Doxygen formatting sake.
  features/nvstore/source/nvstore.h
Labels: ready for merge, release-version: 5.8.1

#6346 Fix for #6252
  targets/targets.json
Labels: ready for merge, release-version: 5.8.1

#6353 STM32 RTC init
  targets/TARGET_STM/rtc_api.c
Labels: ready for merge, release-version: 5.8.1

#6354 Enable iar export option for MTB_ADV_WISE_1510
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.8.1

#6114 Remove mbed 2 builds from Travis
  .travis.yml
Labels: ready for merge, release-version: 5.8.1

#6326 rtl8195am : fix gpio toggle slow
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/TOOLCHAIN_ARM_STD/rtl8195a.sct
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/TOOLCHAIN_GCC_ARM/rtl8195a.ld
Labels: needs: CI

#6264 Deprecated warnings for feature/netsocket/cellular
  features/cellular/easy_cellular/APN_db.h
  features/cellular/framework/API/CellularNetwork.h
  features/netsocket/CellularInterface.h
  features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.cpp
  features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.h
  features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.cpp
  features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.h
  features/netsocket/cellular/generic_modem_driver/UARTCellularInterface.cpp
  features/netsocket/cellular/generic_modem_driver/UARTCellularInterface.h
  features/netsocket/nsapi.h
Labels: needs: CI

#6337 Add Kinetis USB Phy
  TESTS/usb_device/basic/USBTester.cpp
  targets/TARGET_Freescale/usb/USBEndpoints_Kinetis.h
  targets/TARGET_Freescale/usb/USBPhyHw.h
  targets/TARGET_Freescale/usb/USBPhy_Kinetis.cpp
  targets/targets.json
  usb/device/USBDevice/USBDevice.cpp
  usb/device/USBDevice/USBDevice.h
Labels: ready for merge

#6375 Fix watchdog timing accuracy test for UBLOX_EVK_ODIN_W2
  TESTS/mbed_hal/watchdog_timing/main.cpp
Labels: ready for merge

#6379 DISCO_L496AG: Add new platform
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/system_clock.c
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
Labels: Scope: new-target, ready for merge, release-version: 5.8.1

#6372 Fix doxygen for ITM HAL
  doxyfile_options
  doxygen_options.json
  hal/itm_api.h
Labels: ready for merge, release-version: 5.8.1

#6367 ADI: Fix on chip flash minimal programmable unit size
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/api/flash_api.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/api/flash_api.c
Labels: ready for merge, release-version: 5.8.1

#6216 Correct Realtek post-build script to work in the online compiler
  tools/targets/REALTEK_RTL8195AM.py
Labels: ready for merge, release-version: 5.8.1

#6192 Correct syntax for mbed export in Py3
  tools/export/cmake/__init__.py
  tools/export/gnuarmeclipse/__init__.py
  tools/export/iar/__init__.py
  tools/export/makefile/__init__.py
  tools/export/mcuxpresso/__init__.py
  tools/export/nb/__init__.py
  tools/export/sw4stm32/__init__.py
  tools/export/uvision/__init__.py
  tools/export/vscode/__init__.py
  tools/project.py
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.8.1

#6387 USB updates and enhancements
  TESTS/usb_device/basic/USBTester.cpp
  TESTS/usb_device/basic/USBTester.h
  platform/USBPhy.h
  targets/TARGET_Freescale/usb/USBPhyHw.h
  targets/TARGET_Freescale/usb/USBPhy_Kinetis.cpp
  targets/TARGET_NXP/TARGET_LPC176X/usb/USBHAL_LPC17.cpp
  targets/TARGET_NXP/TARGET_LPC176X/usb/USBPhyHw.h
  usb/device/USBDevice/USBDevice.cpp
  usb/device/USBDevice/USBDevice.h
Labels: needs: review

#6371 Add RESET_REASON and WATCHDOG to doxygen options
  doxyfile_options
  doxygen_options.json
  hal/reset_reason_api.h
  targets/targets.json
Labels: ready for merge

#6269 Add tests for Reset Reason API
  TESTS/host_tests/reset_reason.py
  TESTS/mbed_drivers/reset_reason/ResetReason_tests.h
  TESTS/mbed_drivers/reset_reason/main.cpp
  TESTS/mbed_hal/reset_reason/main.cpp
  TESTS/mbed_hal/reset_reason/reset_reason_api_tests.h
  targets/TARGET_STM/reset_reason.c
Labels: ready for merge

#6356 Add include search path when preprocessing assembly files for uvision and make_armc5 exports
  tools/export/makefile/__init__.py
  tools/export/uvision/uvision.tmpl
Labels: needs: CI

#6340 Disables flash clock and cache test
  TESTS/mbed_hal/flash/functional_tests/main.cpp
Labels: ready for merge, release-version: 5.8.1

#6370 STM32 LPTICKER : optimize RTC wake up timer init
  targets/TARGET_STM/rtc_api.c
Labels: ready for merge, release-version: 5.8.1

#6363 dir seek fixed - dptr was not updated before checking
  features/filesystem/fat/FATFileSystem.cpp
Labels: ready for merge

#6350 Cellular: update attach test
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: ready for merge

#6338 littlefs: Fix issue updating dir struct when extended dir chain
  features/filesystem/littlefs/littlefs/lfs.c
  features/filesystem/littlefs/littlefs/tests/test_dirs.sh
  features/filesystem/littlefs/littlefs/tests/test_files.sh
Labels: Scope: bug-fix, ready for merge

#6333 Corrected lwip adaptation TCP flagging
  features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Labels: ready for merge, release-version: 5.8.1

#6330 NUCLEO_L433RC_P: fix pins definitions
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/TARGET_NUCLEO_L433RC_P/PinNames.h
Labels: ready for merge, release-version: 5.8.1

#6357 Update mbed-coap to version 4.4.0
  features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md
  features/FEATURE_COMMON_PAL/mbed-coap/mbed-coap/sn_coap_protocol.h
  features/FEATURE_COMMON_PAL/mbed-coap/mbed-coap/sn_config.h
  features/FEATURE_COMMON_PAL/mbed-coap/module.json
  features/FEATURE_COMMON_PAL/mbed-coap/source/include/sn_coap_protocol_internal.h
  features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.8.1

#6279 LoRa refactoring
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMacChannelPlan.cpp
  features/lorawan/lorastack/mac/LoRaMacChannelPlan.h
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.h
  features/lorawan/lorastack/mac/LoRaMacMcps.cpp
  features/lorawan/lorastack/mac/LoRaMacMcps.h
  features/lorawan/lorastack/mac/LoRaMacMib.cpp
  features/lorawan/lorastack/mac/LoRaMacMib.h
  features/lorawan/lorastack/mac/LoRaMacMlme.cpp
  features/lorawan/lorastack/mac/LoRaMacMlme.h
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.cpp
  features/lorawan/lorastack/phy/lora_phy_ds.h
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6392 Nuvoton: Remove unnecessary UART INT in UART DMA transfer
  targets/TARGET_NUVOTON/TARGET_M451/serial_api.c
  targets/TARGET_NUVOTON/TARGET_M480/serial_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/serial_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/serial_api.c
Labels: ready for merge, release-version: 5.8.1

#6344 armcc - remove fromelf output before regenerating one
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.8.1

#6168 CM3DS Maintenance Pull Request: Memory changes (2/4)
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/README.md
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/TOOLCHAIN_ARM_STD/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/cmsis_nvic.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/memory_zones.h
  targets/TARGET_ARM_SSG/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, release-version: 5.8.1

#6368 Sort out volatiles in the atomic functions
  platform/mbed_critical.c
  platform/mbed_critical.h
Labels: ready for merge

#6348 Fix PR template
  .github/pull_request_template.md
Labels: release-version: 5.8.1

#6404 Update USBCDC and USBSerial
  .travis.yml
  usb/device/USBSerial/USBCDC.cpp
  usb/device/USBSerial/USBCDC.h
  usb/device/USBSerial/USBSerial.cpp
  usb/device/USBSerial/USBSerial.h
  usb/device/utilities/AsyncOp.cpp
  usb/device/utilities/AsyncOp.h
  usb/device/utilities/LinkEntry.h
  usb/device/utilities/LinkedList.h
  usb/device/utilities/LinkedListBase.cpp
  usb/device/utilities/LinkedListBase.h
Labels: needs: review

#6412 STM32L4 ADC correct internal channel management
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_adc.c
Labels: ready for merge, release-version: 5.8.1

#6309 Peek API to view data of buffer without popping
  TESTS/mbedmicro-rtos-mbed/CircularBuffer/main.cpp
  platform/CircularBuffer.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6406 USB generic tests
  TESTS/host_tests/pyusb_basic.py
  TESTS/usb_device/basic/USBTester.cpp
  TESTS/usb_device/basic/USBTester.h
  TESTS/usb_device/basic/main.cpp
Labels: ready for merge

#6431 Fix Address.Size and AlternateByes.Size by shifting them
  targets/TARGET_STM/qspi_api.c
Labels: ready for merge

#6432 QSPI: Fix Instruction with no data command
  targets/TARGET_STM/qspi_api.c
Labels: ready for merge

#6343 Add EMAC driver README.md with porting guide
  features/netsocket/emac-drivers/README.md
Labels: ready for merge

#6425 Changed STM emac driver to loop RX frame reading
  features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac.cpp
  features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac.h
Labels: ready for merge

#6415 rtl8195am: fix LogUART Tx interrupt crash
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/log_uart_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/serial_api.c
Labels: ready for merge, release-version: 5.8.1

#6377 Replace runtime strip_path function with compiler intrinsic equivalents
  hal/mbed_sleep_manager.c
  platform/mbed_power_mgmt.h
  platform/mbed_toolchain.h
Labels: ready for merge, release-version: 5.8.1

#6419 Correct get_config imports
  tools/get_config.py
Labels: ready for merge, release-version: 5.8.1

#6427 Added SerialWireOutput to mbed namespace
  drivers/SerialWireOutput.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6388 NVStore: key management enhancements
  features/nvstore/README.md
  features/nvstore/TESTS/nvstore/functionality/main.cpp
  features/nvstore/source/nvstore.cpp
  features/nvstore/source/nvstore.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6239 Interrupt in pin mode
  drivers/InterruptIn.cpp
  drivers/InterruptIn.h
Labels: Scope: feature, ready for merge, release-version: 5.9.0-rc1

#6437 Nuvoton: Fix NVSTORE test failed
  targets/TARGET_NUVOTON/TARGET_M451/flash_api.c
  targets/TARGET_NUVOTON/TARGET_M480/flash_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/flash_api.c
Labels: ready for merge, release-version: 5.8.1

#6443 Rename lp_us tests to common and hf to microsecond
  TESTS/mbed_hal/common_tickers/main.cpp
  TESTS/mbed_hal/common_tickers/ticker_api_tests.h
  TESTS/mbed_hal/common_tickers_freq/main.cpp
  TESTS/mbed_hal/common_tickers_freq/ticker_api_test_freq.h
  hal/lp_ticker_api.h
  hal/us_ticker_api.h
Labels: ready for merge

#6393 Move USBPhy and related files to USB directory
  usb/device/USBPhy/USBPhy.h
  usb/device/USBPhy/USBPhyEvents.h
  usb/device/USBPhy/USBPhyTypes.h
  usb/device/hal/mbed_usb_phy.cpp
  usb/device/hal/usb_phy_api.h
  usb/device/targets/TARGET_Freescale/USBEndpoints_Kinetis.h
  usb/device/targets/TARGET_Freescale/USBPhyHw.h
  usb/device/targets/TARGET_Freescale/USBPhy_Kinetis.cpp
  usb/device/targets/TARGET_NXP/USBEndpoints_LPC17_LPC23.h
  usb/device/targets/TARGET_NXP/USBHAL_LPC17.cpp
  usb/device/targets/TARGET_NXP/USBPhyHw.h
Labels: ready for merge

#6446 Add USBPhy template
  usb/device/targets/TARGET_Template/USBPhyHw.h
  usb/device/targets/TARGET_Template/USBPhy_template.cpp
Labels: ready for merge

#6445 Add pyusb to requirements
  requirements.txt
Labels: ready for merge

#6435 [feature-nrf528xx] Serial re-implementation for the NRF52 series
  targets/TARGET_NORDIC/TARGET_NRF5x/PeripheralPinsDefault.c
  targets/TARGET_NORDIC/TARGET_NRF5x/README.md
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/PeripheralNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_DELTA_DFBM_NQ620/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_MTB_UBLOX_NINA_B1/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_NRF52_DK/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_RBLAB_BLENANO2/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_UBLOX_EVA_NINA/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_UBLOX_EVK_NINA_B1/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_VBLUNO52/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/PeripheralNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_NRF52840_DK/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/objects.h
  targets/TARGET_NORDIC/TARGET_NRF5x/pinmap_ex.c
  targets/TARGET_NORDIC/TARGET_NRF5x/pinmap_ex.h
  targets/TARGET_NORDIC/TARGET_NRF5x/serial_api.c
Labels: ready for merge

#6450 Realtek: serial - line ending fix
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/serial_api.c
Labels: needs: CI, release-version: 5.8.2

#6440 Remove supertarget
  targets/targets.json
Labels: ready for merge, release-version: 5.9.0-rc1

#6428 Avoid incorrect config errors on export with many --source
  tools/export/__init__.py
Labels: ready for merge, release-version: 5.8.2

#6424 Nuvoton: Support M487 v3.0 pin map
  targets/TARGET_NUVOTON/TARGET_M480/TARGET_NUMAKER_PFM_M487/PinNames.h
Labels: ready for merge, release-version: 5.8.2

#6416 lwIP: fix some IPv6 errors, eg TCP keepalive
  features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Labels: ready for merge, release-version: 5.8.2

#6313 Add missing Doxygen descriptions for Nanostack
  doxyfile_options
  doxygen_options.json
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/LoWPANNDInterface.h
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/ThreadInterface.h
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h
  features/nanostack/FEATURE_NANOSTACK/nanostack-interface/NanostackEthernetPhy.h
  features/nanostack/FEATURE_NANOSTACK/nanostack-interface/NanostackInterface.h
  features/nanostack/FEATURE_NANOSTACK/nanostack-interface/NanostackPhy.h
  features/nanostack/FEATURE_NANOSTACK/nanostack-interface/NanostackRfPhy.h
Labels: ready for merge, release-version: 5.8.2

#6452 Revert "BLE: Gatt client unit tests"
  .travis.yml
  features/FEATURE_BLE/tests/CMakeLists.txt
  features/FEATURE_BLE/tests/CMakeLists.txt.in
  features/FEATURE_BLE/tests/README.md
  features/FEATURE_BLE/tests/generic/GattClient/TestCharacteristicDesctiptorDiscovery.cpp
  features/FEATURE_BLE/tests/generic/GattClient/TestDiscoverAllServices.cpp
  features/FEATURE_BLE/tests/generic/GattClient/TestNoCb.cpp
  features/FEATURE_BLE/tests/generic/GattClient/TestRead.cpp
  features/FEATURE_BLE/tests/generic/GattClient/TestServerEvent.cpp
  features/FEATURE_BLE/tests/generic/GattClient/TestWrite.cpp
  features/FEATURE_BLE/tests/generic/GattClient/mock/MockCallbacks.cpp
  features/FEATURE_BLE/tests/generic/GattClient/mock/MockCallbacks.h
  features/FEATURE_BLE/tests/generic/GattClient/mock/MockPalGattClient.cpp
  features/FEATURE_BLE/tests/generic/GattClient/mock/MockPalGattClient.h
  features/FEATURE_BLE/tests/generic/GattClient/util/CharacteristicDescription.h
  features/FEATURE_BLE/tests/generic/GattClient/util/Equality.cpp
  features/FEATURE_BLE/tests/generic/GattClient/util/Equality.h
  features/FEATURE_BLE/tests/generic/GattClient/util/Log.h
  features/FEATURE_BLE/tests/generic/GattClient/util/PrettyPrinter.h
  features/FEATURE_BLE/tests/generic/GattClient/util/ServerDescription.h
  features/FEATURE_BLE/tests/generic/GattClient/util/ServiceDescription.h
  features/FEATURE_BLE/tests/mbed_os_stub/mbed_assert.c
Labels: ready for merge

#6439 Update USBTester product name
  TESTS/usb_device/basic/USBTester.cpp
Labels: needs: CI

#6487 Minimize the size of uvision include paths
  tools/export/exporters.py
  tools/export/gnuarmeclipse/__init__.py
  tools/export/uvision/__init__.py
Labels: ready for merge, release-version: 5.8.2

#6472 Provide fixes for HAL ticker test
  TESTS/mbed_hal/common_tickers/main.cpp
Labels: ready for merge

#6477 Add Watchdog and ResetReason headers to mbed.h
  mbed.h
Labels: ready for merge

#6373 flash: add docs for user defined data
  hal/TARGET_FLASH_CMSIS_ALGO/flash_data.h
Labels: ready for merge, release-version: 5.8.2

#6467 KL82Z: Update the clock selection method for LPUART module
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/TARGET_USENSE/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/peripheral_clock_defines.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/serial_api.c
Labels: ready for merge, release-version: 5.8.2

#6488 Fix initial SP for new Silicon Labs targets on ARMCC
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32PG12/device/TOOLCHAIN_ARM_STD/startup_efm32pg12b.S
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG1/device/TOOLCHAIN_ARM_STD/startup_efr32mg1p.S
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/device/TOOLCHAIN_ARM_STD/startup_efr32mg12p.S
Labels: release-version: 5.8.2

#6413 LPC176X: Fix flash program size
  targets/TARGET_NXP/TARGET_LPC176X/device/flash_api.c
Labels: needs: CI

#6471 Re-implement us_ticker and lp_ticker for Silicon Labs targets
  targets/TARGET_Silicon_Labs/TARGET_EFM32/burtc.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/common/clocking.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/common/mbed_overrides.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/lp_ticker.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/rtc_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/rtc_api_HAL.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/rtcc.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/us_ticker.c
  targets/targets.json
Labels: needs: CI

#6500 Added watchdog implementation for NCS36510.
  targets/TARGET_ONSEMI/TARGET_NCS36510/watchdog_api.c
  targets/targets.json
Labels: needs: CI

#6491 [feature-nrf528xx] NRF52 serial bug fix and serial_free implementation
  targets/TARGET_NORDIC/TARGET_NRF5x/serial_api.c
Labels: needs: review

#6394 Nuvoton: Fix us_ticker/lp_ticker
  targets/TARGET_NUVOTON/TARGET_M451/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M451/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_M480/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M480/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_NANO100/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_NANO100/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_NUC472/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_NUC472/us_ticker.c
Labels: ready for merge

#6408 Add overloaded get_erase_size API with address parameter to BlockDevice
  features/TESTS/filesystem/util_block_device/main.cpp
  features/filesystem/bd/BlockDevice.h
  features/filesystem/bd/ChainingBlockDevice.cpp
  features/filesystem/bd/ChainingBlockDevice.h
  features/filesystem/bd/ExhaustibleBlockDevice.cpp
  features/filesystem/bd/ExhaustibleBlockDevice.h
  features/filesystem/bd/HeapBlockDevice.cpp
  features/filesystem/bd/HeapBlockDevice.h
  features/filesystem/bd/MBRBlockDevice.cpp
  features/filesystem/bd/MBRBlockDevice.h
  features/filesystem/bd/ObservingBlockDevice.cpp
  features/filesystem/bd/ObservingBlockDevice.h
  features/filesystem/bd/ProfilingBlockDevice.cpp
  features/filesystem/bd/ProfilingBlockDevice.h
  features/filesystem/bd/ReadOnlyBlockDevice.cpp
  features/filesystem/bd/ReadOnlyBlockDevice.h
  features/filesystem/bd/SlicingBlockDevice.cpp
  features/filesystem/bd/SlicingBlockDevice.h
Labels: Scope: feature, ready for merge, release-version: 5.9.0-rc1

#6475 Enable tickless mode on Silicon Labs targets
  targets/targets.json
Labels: ready for merge, release-version: 5.8.2

#6479 Fix USB tests
  TESTS/host_tests/pyusb_basic.py
Labels: ready for merge, release-version: 5.8.2

#6494 [BLE] Fixed inconsistent casing issue for SecurityDb
  features/FEATURE_BLE/ble/pal/MemorySecurityDb.h
  features/FEATURE_BLE/ble/pal/SecurityDb.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioBLE.h
Labels: ready for merge, release-version: 5.8.2
