Repository ARMmbed/mbed-os, pull requests merged in 2018-07, with the labels that each got.

#7369 Fix race condition in serial_api.c for NRF52 series
  targets/TARGET_NORDIC/TARGET_NRF5x/README.md
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
Labels: ready for merge, release-version: 5.9.3

#7348 LoRaWAN: Correcting doxygen
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.h
Labels: ready for merge, release-version: 5.9.3

#7389 Update nsdynmemlib in frameworks/nanostack-libservice
  features/frameworks/nanostack-libservice/mbed-client-libservice/ip4string.h
  features/frameworks/nanostack-libservice/mbed-client-libservice/nsdynmemLIB.h
  features/frameworks/nanostack-libservice/source/libip4string/ip4tos.c
  features/frameworks/nanostack-libservice/source/libip4string/stoip4.c
  features/frameworks/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c
  features/frameworks/nanostack-libservice/test/libService/unittest/nsdynmem/dynmemtest.cpp
  features/frameworks/nanostack-libservice/test/libService/unittest/stubs/ns_list_stub.c
  features/frameworks/nanostack-libservice/test/libService/unittest/stubs/nsdynmemLIB_stub.c
  features/frameworks/nanostack-libservice/test/libService/unittest/stubs/nsdynmemLIB_stub.h
  features/frameworks/nanostack-libservice/test/libService/unittest/stubs/platform_nvm_stub.c
Labels: ready for merge, release-version: 5.10.0-rc1

#7367 Tools: Detect Arm Compiler version using Component
  tools/test/toolchains/api_test.py
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.9.3

#7331 Improve the process for Cortex-A9 in mbed_application
  platform/mbed_application.c
Labels: ready for merge, release-version: 5.9.3

#7384 Fix memory leakage with MBR on exiting error path
  features/filesystem/bd/MBRBlockDevice.cpp
Labels: ready for merge, release-version: 5.9.3

#7403 LPC546XX: Fix UART mux setting in the LPCXpresso board
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_LPCXpresso/PeripheralPins.c
Labels: ready for merge, release-version: 5.9.3

#7277 Tools: Persist config errors until validation occurs
  tools/build_api.py
  tools/config/__init__.py
Labels: ready for merge, release-version: 5.9.3

#7342 Add kernel ticker test
  TESTS/mbedmicro-rtos-mbed/kernel_tick_count/main.cpp
Labels: ready for merge, release-version: 5.9.3

#7376 DISCO_L496AG: change LED1 and LED2 pins
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/PinNames.h
Labels: ready for merge, release-version: 5.9.3

#7377 Tools: Summarize stats when depth is 0
  tools/memap.py
Labels: ready for merge, release-version: 5.9.3

#7386 Make clock source changeable over mbed_app.json for EFM32-Targets
  targets/TARGET_Silicon_Labs/TARGET_EFM32/common/mbed_overrides.c
Labels: ready for merge, release-version: 5.9.3

#7390 DISCO STM32L4 : Add TWO_RAM_REGIONS macro
  targets/targets.json
Labels: ready for merge, release-version: 5.9.3

#7399 Bug fix for receive windows
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/phy/LoRaPHY.cpp
Labels: ready for merge, release-version: 5.9.3

#7401 Fix interrupt initialization for NRF52 series
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
Labels: ready for merge, release-version: 5.9.3

#7405 Fix target definition for NRF52 series
  targets/targets.json
Labels: ready for merge, release-version: 5.9.3

#7411 Fix wrong config binding
  platform/mbed_error.c
Labels: ready for merge, release-version: 5.9.3

#7413 Modified Wiced drivers EMAC instance get
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/TARGET_WICED/wiced_interface/WicedInterface.h
Labels: ready for merge, release-version: 5.9.3

#7414 Added json options for nanostack heap statictics
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/mesh_system.c
Labels: ready for merge, release-version: 5.10.0-rc1

#7371 Improve efficiency and formatting of ITM output
  drivers/SerialWireOutput.h
  hal/itm_api.h
  hal/mbed_itm_api.c
Labels: needs: CI, release-version: 5.9.3

#7420 MIMXRT1050_EVK: Fix the GPIO IRQ number assignements
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/gpio_irq_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/MIMXRT1052.h
Labels: needs: CI, release-version: 5.9.3

#7364 Fix storage rtos types - remove including internal header file
  TESTS/mbed_hal/common_tickers/main.cpp
  TESTS/mbed_hal/lp_ticker/main.cpp
  TESTS/mbedmicro-rtos-mbed/heap_and_stack/main.cpp
  features/device_key/source/DeviceKey.cpp
  features/lwipstack/LWIPStack.h
  features/lwipstack/lwip-sys/arch/sys_arch.h
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/kinetis_emac.cpp
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/kinetis_emac.h
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/numaker_emac.cpp
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/numaker_emac.h
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_LPC546XX/lpc546xx_emac.cpp
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_LPC546XX/lpc546xx_emac.h
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_LPCTarget/lpc17_emac.cpp
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_LPCTarget/lpc17_emac.h
  features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac.cpp
  features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac.h
  rtos/TARGET_CORTEX/mbed_rtos_storage.h
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
  rtos/Thread.cpp
Labels: needs: review, release-version: 5.10.0-rc1

#7421 MIMXRT1050_EVK: Move clock enable after check of pin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/gpio_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/gpio_irq_api.c
Labels: ready for merge

#7406 NANO130: Change PLL clock source to HIRC instead of HXT
  targets/TARGET_NUVOTON/TARGET_NANO100/TARGET_NUMAKER_PFM_NANO130/mbed_overrides.c
  targets/targets.json
Labels: ready for merge, release-version: 5.9.3

#7429 MXRT1050: Ensure the pins are in input mode for analogin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/analogin_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PeripheralPins.c
Labels: ready for merge, release-version: 5.9.3

#7412 apply FatFs 0.13b hotfix - fix readdir() never terminates when dir is full
  features/filesystem/fat/ChaN/ff.cpp
Labels: ready for merge, release-version: 5.9.3

#7352 STM32: Fix RTC test issue on targets using a 16-bit timer for us_ticker
  targets/TARGET_STM/hal_tick_16b.c
  targets/TARGET_STM/hal_tick_common.c
  targets/TARGET_STM/mbed_overrides.c
  targets/TARGET_STM/sleep.c
  targets/TARGET_STM/us_ticker.c
Labels: needs: CI, release-version: 5.9.3

#7437 Recognize ".cc" and ".hh" source file extensions
  tools/toolchains/__init__.py
Labels: ready for merge, release-version: 5.9.3

#7410 Tools: Move exporter alias handling to CLI
  tools/export/__init__.py
  tools/project.py
  tools/test/examples/examples_lib.py
Labels: needs: CI, release-version: 5.9.3

#7333 Cellular: More unit tests for ATHandler's read routines
  features/cellular/UNITTESTS/at/athandler/Makefile
  features/cellular/UNITTESTS/at/athandler/athandlertest.cpp
  features/cellular/UNITTESTS/at/athandler/test_athandler.cpp
  features/cellular/UNITTESTS/at/athandler/test_athandler.h
  features/cellular/UNITTESTS/stubs/FileHandle_stub.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
Labels: needs: CI, release-version: 5.9.3

#7430 Lora: Add support for runtime PHY selection
  features/lorawan/LoRaWANInterface.cpp
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYAS923.cpp
  features/lorawan/lorastack/phy/LoRaPHYAS923.h
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.h
  features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN470.h
  features/lorawan/lorastack/phy/LoRaPHYCN779.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN779.h
  features/lorawan/lorastack/phy/LoRaPHYEU433.cpp
  features/lorawan/lorastack/phy/LoRaPHYEU433.h
  features/lorawan/lorastack/phy/LoRaPHYEU868.cpp
  features/lorawan/lorastack/phy/LoRaPHYEU868.h
  features/lorawan/lorastack/phy/LoRaPHYIN865.cpp
  features/lorawan/lorastack/phy/LoRaPHYIN865.h
  features/lorawan/lorastack/phy/LoRaPHYKR920.cpp
  features/lorawan/lorastack/phy/LoRaPHYKR920.h
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.h
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7466 Tools: py3 compatible version checks
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
Labels: ready for merge, release-version: 5.9.3

#7127 NVStore tests: Tune memory consumption; stop threads greafully
  features/nvstore/TESTS/nvstore/functionality/main.cpp
Labels: ready for merge, release-version: 5.9.3

#7446 Disable LSE for MTB_USI_WM_BN_BM_22
  targets/targets.json
Labels: needs: CI, release-version: 5.9.3

#7404 Do not print error reports in release builds
  platform/mbed_error.c
Labels: ready for merge, release-version: 5.9.3

#7453 Fix SWI conflict in SoftDevice for NRF52 series
  targets/TARGET_NORDIC/TARGET_NRF5x/README.md
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_S132_FULL/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_S132_OTA/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_S140_FULL/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_S140_OTA/mbed_lib.json
Labels: ready for merge, release-version: 5.9.3

#7474 Replace build profile changes with config
  rtos/mbed_lib.json
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge, release-version: 5.9.3

#7365 STM32 RTC : bypass shadow registers
  targets/TARGET_STM/rtc_api.c
  targets/TARGET_STM/sleep.c
Labels: ready for merge

#7487 Allow STDIO pins to be NC in NRF52 series
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
Labels: ready for merge, release-version: 5.9.3

#7486 Fix linker script for NRF52840/IAR
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_IAR/nRF52832.icf
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_IAR/nRF52840.icf
Labels: needs: CI

#7501 Tools: Make directories before gen file uses them
  tools/export/exporters.py
Labels: ready for merge, release-version: 5.9.3

#7489 Cellular: HSI set to be source clock for WISE_1570
  targets/targets.json
Labels: ready for merge, release-version: 5.9.3

#7471 tests-mbed_drivers-lp_timer: change delay method
  TESTS/mbed_drivers/lp_timer/main.cpp
Labels: ready for merge, release-version: 5.9.3

#7459 LoRaWAN: FRMPayload size validity
  features/lorawan/LoRaRadio.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
Labels: ready for merge, release-version: 5.9.3

#7318 Cellular: Remove max_packet_size
  features/cellular/UNITTESTS/at/at_cellularstack/test_at_cellularstack.cpp
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.h
Labels: ready for merge, release-version: 5.9.3

#7434 Separate version header file in Mbed OS
  mbed.h
  platform/mbed_version.h
Labels: ready for merge, release-version: 5.9.3

#7461 Raytac: target removal
  targets/targets.json
Labels: release-version: 5.9.3

#7445 LoRaWAN: Remedy for issue #7230
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorawan_types.h
Labels: needs: CI, release-version: 5.9.3

#7505 Fix linker script for NRF52840/ARM
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_ARM_STD/nRF52832.sct
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_ARM_STD/nRF52840.sct
Labels: needs: CI, release-version: 5.9.3

#7494 tests-mbed_hal-lp_ticker: change implementation of the delay before deep-sleep.
  TESTS/mbed_hal/lp_ticker/main.cpp
Labels: needs: CI, release-version: 5.9.3

#7481 Tools: Fix py3 bug with mbed export -S
  tools/project.py
Labels: needs: CI, release-version: 5.9.3

#7500 Tools: Correct cmse lib creating with make_gcc_arm exporter
  tools/toolchains/gcc.py
Labels: needs: CI, release-version: 5.9.3

#7503 Tools: Drop quotes from makefiles
  tools/export/makefile/__init__.py
Labels: needs: CI, release-version: 5.9.3

#7475 Tools: py3 compatible mbed-os version lowercasing
  tools/build_api.py
Labels: needs: CI, release-version: 5.9.3

#7436 Update stats to fetch Mbed OS version info
  TESTS/mbed_platform/stats_sys/main.cpp
  platform/mbed_stats.c
  platform/mbed_stats.h
Labels: needs: CI, release-version: 5.9.3

#7507 STM32 LPTICKER with LPTIM minor update
  targets/TARGET_STM/lp_ticker.c
Labels: needs: CI, release-version: 5.9.3

#7477 Tools: Skip target lookup in test builds.
  tools/test_api.py
Labels: needs: CI, release-version: 5.9.3

#7498 STM32: enable HSI/LSE clocks for LPUART
  targets/TARGET_STM/serial_api.c
Labels: needs: CI, release-version: 5.9.3

#7448 Unity: Add macros for test skipping.
  features/frameworks/unity/source/unity.c
  features/frameworks/unity/unity/unity.h
  features/frameworks/unity/unity/unity_internals.h
  features/frameworks/utest/TESTS/unit_tests/test_skip/main.cpp
Labels: needs: review, release-version: 5.9.4

#7183 Tools: Extract resources object and implement incremental scan
  TESTS/storage_abstraction/.mbedignore
  TESTS/storage_abstraction/basicAPI/basicAPI.cpp
  tools/build_api.py
  tools/build_release.py
  tools/config/__init__.py
  tools/export/__init__.py
  tools/export/atmelstudio/__init__.py
  tools/export/cces/__init__.py
  tools/export/cmake/__init__.py
  tools/export/cmsis/__init__.py
  tools/export/codeblocks/__init__.py
  tools/export/coide/__init__.py
  tools/export/ds5_5/__init__.py
  tools/export/embitz/__init__.py
  tools/export/exporters.py
  tools/export/gnuarmeclipse/__init__.py
  tools/export/iar/__init__.py
  tools/export/kds/__init__.py
  tools/export/lpcxpresso/__init__.py
  tools/export/makefile/__init__.py
  tools/export/mcuxpresso/__init__.py
  tools/export/nb/__init__.py
  tools/export/simplicity/__init__.py
  tools/export/sw4stm32/__init__.py
  tools/export/uvision/__init__.py
  tools/get_config.py
  tools/git_hooks/find_duplicates.py
  tools/project.py
  tools/resources/__init__.py
  tools/test/build_api/build_api_test.py
  tools/test/test_api/test_api_test.py
  tools/test/toolchains/api_test.py
  tools/test_api.py
  tools/toolchains/__init__.py
  tools/toolchains/arm.py
Labels: component: tools, ready for merge, release-version: 5.9.4

#7325 hal-qspi test
  TESTS/mbed_hal/qspi/flash_configs/MX25R6435F_config.h
  TESTS/mbed_hal/qspi/flash_configs/NORDIC/NRF52840_DK/flash_config.h
  TESTS/mbed_hal/qspi/flash_configs/STM/DISCO_L475VG_IOT01A/flash_config.h
  TESTS/mbed_hal/qspi/flash_configs/flash_configs.h
  TESTS/mbed_hal/qspi/main.cpp
  TESTS/mbed_hal/qspi/qspi_test.h
  TESTS/mbed_hal/qspi/qspi_test_utils.cpp
  TESTS/mbed_hal/qspi/qspi_test_utils.h
  targets/TARGET_NORDIC/TARGET_NRF5x/qspi_api.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PinNames.h
  targets/TARGET_STM/qspi_api.c
  targets/targets.json
Labels: ready for merge

#4846 Integrate mbed OS RTC with mbed TLS
  features/mbedtls/platform/inc/platform_mbed.h
Labels: component: tls, ready for merge, tracking

#7396 Tools: Show Mbed-2-only targets in mbed compile -S
  tools/make.py
Labels: ready for merge, release-version: 5.9.4

#7468 Remove LoRaWAN license from top-level directory
  LICENSE-BSD-3-Clause
Labels: needs: CI, release-version: 5.9.4

#7533 Fix linker script for NRF52832/IAR
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_IAR/nRF52832.icf
Labels: ready for merge

#7504 Feature itm fix
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/system_nrf52.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/system_nrf52840.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/itm_api.c
Labels: ready for merge

#7544 Remove extra ARMc6 instance in unique mapping
  tools/build_api.py
Labels: needs: CI, release-version: 5.9.4

#7479 Silicon Labs: Add support for hardware CRC
  targets/TARGET_Silicon_Labs/TARGET_EFM32/crc_api.c
  targets/targets.json
Labels: needs: CI, release-version: 5.9.4

#7520 LoRaWAN: Wrong return code for JoinRequest retry
  features/lorawan/lorastack/mac/LoRaMac.cpp
Labels: ready for merge, release-version: 5.9.4

#7548 Fix some targets fail to pass ticker overflow test
  TESTS/mbed_hal/common_tickers/main.cpp
Labels: ready for merge, release-version: 5.9.4

#7539 STM32F2/F4/F7 : LL API is now available for IRQ
  targets/TARGET_STM/TARGET_STM32F2/gpio_irq_device.h
  targets/TARGET_STM/TARGET_STM32F4/gpio_irq_device.h
  targets/TARGET_STM/TARGET_STM32F7/gpio_irq_device.h
Labels: ready for merge, release-version: 5.9.4

#7491 EFM32: fix weak PeripheralPins configuration
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG/PeripheralPins.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG11/PeripheralPins.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32HG/PeripheralPins.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32LG/PeripheralPins.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32PG/PeripheralPins.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32PG12/PeripheralPins.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32WG/PeripheralPins.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32ZG/PeripheralPins.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG1/PeripheralPins.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/PeripheralPins.c
Labels: needs: CI, release-version: 5.9.4

#7556 Fix spelling in error message in fault handler
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.c
Labels: ready for merge, release-version: 5.9.4

#7061 Tools: Include configuration in ASM
  tools/export/iar/__init__.py
  tools/export/iar/ewp.tmpl
  tools/export/makefile/__init__.py
  tools/test/toolchains/api_test.py
  tools/toolchains/__init__.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
Labels: ready for merge

#7480 Add MTS Dragonfly bootloader back after accidental removal from pr #7131
  tools/bootloaders/MTS_DRAGONFLY_F411RE/bootloader.bin
Labels: ready for merge, release-version: 5.9.4

#7510 STM32: Improve GPIO IRQ edge detection when waking from deepsleep
  targets/TARGET_STM/gpio_irq_api.c
Labels: ready for merge

#7519 Wiznet: fix us_ticker & gpio bug
  targets/TARGET_WIZNET/TARGET_W7500x/W7500x_Peripheral_Library/W7500x_gpio.c
  targets/TARGET_WIZNET/TARGET_W7500x/W7500x_Peripheral_Library/W7500x_gpio.h
  targets/TARGET_WIZNET/TARGET_W7500x/mbed_overrides.c
  targets/TARGET_WIZNET/TARGET_W7500x/us_ticker.c
Labels: ready for merge, release-version: 5.9.4

#7530 RTOS SYSTIMER test error in TICKLESS mode
  TESTS/mbedmicro-rtos-mbed/systimer/main.cpp
Labels: ready for merge, release-version: 5.9.4

#7553 STM32L496: fix RAM size in ARM scatter file
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/device/TOOLCHAIN_ARM_MICRO/stm32l496xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/device/TOOLCHAIN_ARM_STD/stm32l496xx.sct
Labels: ready for merge, release-version: 5.9.4

#7562 STM32 : add all QSPI pins in available targets
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_NUCLEO_F412ZG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_NUCLEO_F412ZG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_NUCLEO_F413ZH/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_NUCLEO_F413ZH/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446ZE/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446ZE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_DISCO_F469NI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/TARGET_NUCLEO_F756ZG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/TARGET_NUCLEO_F756ZG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/TARGET_DISCO_F769NI/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/TARGET_DISCO_F769NI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/TARGET_NUCLEO_L432KC/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/TARGET_NUCLEO_L432KC/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/TARGET_NUCLEO_L433RC_P/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/TARGET_NUCLEO_L433RC_P/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_DISCO_L476VG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/TARGET_NUCLEO_L486RG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/TARGET_NUCLEO_L486RG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_NUCLEO_L496ZG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_NUCLEO_L496ZG/PeripheralPins.c
  tools/targets/STM32_gen_PeripheralPins.py
Labels: needs: CI

#7580 hal-qspi_test: remove STM workaround
  TESTS/mbed_hal/qspi/flash_configs/STM/DISCO_L475VG_IOT01A/flash_config.h
  TESTS/mbed_hal/qspi/main.cpp
Labels: needs: CI

#7581 Implement qspi_free function
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/objects.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/objects.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/objects.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/objects.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/objects.h
  targets/TARGET_STM/qspi_api.c
Labels: ready for merge

#7586 Add reset internal state before call to HAL_QspiInit function
  targets/TARGET_STM/qspi_api.c
Labels: needs: CI

#7554 Enable HAL Flash API on Fast Models MPS2 targets
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/flash_api.c
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/memory_zones.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/objects.h
  targets/targets.json
Labels: ready for merge, release-version: 5.9.4

#7549 Revise heap and stack size for Ethernet of GR-PEACH
  features/lwipstack/mbed_lib.json
Labels: ready for merge, release-version: 5.9.4

#7551 realtek rtl8195am remove DEVICE_EMAC
  targets/TARGET_Realtek/TARGET_AMEBA/rtw_emac.cpp
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/api/wifi/wifi_conf.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/drivers/wlan/realtek/src/osdep/lwip_intf.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/drivers/wlan/realtek/src/osdep/lwip_intf.h
  targets/targets.json
Labels: ready for merge, release-version: 5.9.4

#7587 Allow legacy TCPServer::accept() to override inherited Socket::accept()
  features/netsocket/TCPServer.h
Labels: ready for merge, release-version: 5.9.4

#7528 SPM: upstream changes
  TESTS/spm/client_tests/client_ipc_tests.cpp
  TESTS/spm/client_tests/part1_psa.json
  TESTS/spm/client_tests/server.c
  TESTS/spm/neg_client_tests/neg_ipc_tests.cpp
  TESTS/spm/neg_client_tests/part1_psa.json
  TESTS/spm/neg_client_tests/server1.c
  TESTS/spm/neg_dual_partition/neg_dual_tests.cpp
  TESTS/spm/neg_dual_partition/part1_psa.json
  TESTS/spm/neg_dual_partition/part2_psa.json
  TESTS/spm/neg_dual_partition/server1.c
  TESTS/spm/neg_dual_partition/server2.c
  TESTS/spm/neg_server_tests/neg_ipc_tests.cpp
  TESTS/spm/neg_server_tests/part1_psa.json
  TESTS/spm/neg_server_tests/part2_psa.json
  TESTS/spm/neg_server_tests/server1.c
  TESTS/spm/neg_server_tests/server2.c
  TESTS/spm/server/main.cpp
  TESTS/spm/server/partition.c
  TESTS/spm/server/partition2.c
  TESTS/spm/server/server_tests.h
  TESTS/spm/server/tests.c
  TESTS/spm/smoke/main.cpp
  TESTS/spm/smoke/part1_psa.json
  TESTS/spm/smoke/partition1.c
  spm/handles_manager.c
  spm/mbed_lib.json
  spm/psa_defs.h
  spm/spm_client.c
  spm/spm_client.h
  spm/spm_common.c
  spm/spm_hal_sw.c
  spm/spm_init.c
  spm/spm_internal.h
  spm/spm_server.c
  spm/spm_server.h
  tools/spm/generate_partition_code.py
  tools/spm/partition_description_schema.json
  tools/spm/templates/psa_NAME_partition.c.tpl
  tools/spm/templates/psa_NAME_partition.h.tpl
  tools/spm/templates/psa_common.c.tpl
  tools/test/spm/test_data.py
  tools/test/spm/test_generate_partition_code.py
Labels: needs: review

#7578 Makes Greentea TCP test cases to timeout less in connection errors
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest_burst.cpp
  TESTS/netsocket/tcp/tcpsocket_endpoint_close.cpp
  TESTS/netsocket/tcp/tcpsocket_recv_100k.cpp
  TESTS/netsocket/tcp/tcpsocket_recv_timeout.cpp
  TESTS/netsocket/tcp/tcpsocket_send_repeat.cpp
  TESTS/netsocket/tcp/tcpsocket_send_timeout.cpp
  TESTS/netsocket/tcp/tcpsocket_thread_per_socket_safety.cpp
Labels: needs: CI, release-version: 5.9.4

#7567 Tools: Generate update images with managed bl mode
  tools/build_api.py
  tools/make.py
  tools/test_api.py
Labels: ready for merge, release-version: 5.10.0-rc1

#7603 Nuvoton: Replace __wrap__sbrk with overriding _sbrk
  platform/mbed_retarget.cpp
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_GCC_ARM/m2351_retarget.c
  targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_GCC_ARM/m451_retarget.c
  targets/TARGET_NUVOTON/TARGET_M480/device/TOOLCHAIN_GCC_ARM/m480_retarget.c
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_GCC_ARM/nano100_retarget.c
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_GCC_ARM/nuc472_retarget.c
  targets/TARGET_NUVOTON/mbed_rtx.h
Labels: needs: CI, release-version: 5.9.4

#7608 Tools: Correct `win_to_unix` path handling
  tools/resources/__init__.py
Labels: needs: CI, release-version: 5.9.4

#7609 Make location meaningful in print_error_report
  platform/mbed_error.c
Labels: needs: CI, release-version: 5.9.4

#6985 Fix heap base/limit error with ARM_LIB_STACK/ARM_LIB_HEAP in RTOS-less
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_ARM_MICRO/sys.cpp
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_ARM_STD/sys.cpp
  targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_ARM_MICRO/sys.cpp
  targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_ARM_STD/sys.cpp
  targets/TARGET_NUVOTON/TARGET_M480/device/TOOLCHAIN_ARM_MICRO/sys.cpp
  targets/TARGET_NUVOTON/TARGET_M480/device/TOOLCHAIN_ARM_STD/sys.cpp
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_ARM_MICRO/sys.cpp
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_ARM_STD/sys.cpp
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_ARM_MICRO/sys.cpp
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_ARM_STD/sys.cpp
  targets/TARGET_NUVOTON/TOOLCHAIN_ARM/sys.cpp
Labels: ready for merge, release-version: 5.9.5

#7289 On STM32F439xI IAR linker file decreased stack size and increased heap
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/device/TOOLCHAIN_IAR/stm32f439xx_flash.icf
Labels: ready for merge

#7545 Fix for Thread::max_stack not returning right value when OS_STACK_WATERMARK is enabled
  rtos/Thread.cpp
Labels: ready for merge, release-version: 5.9.5

#7622 MPS2 platform: Enable interrupt on rx for UART
  targets/TARGET_ARM_SSG/TARGET_MPS2/serial_api.c
Labels: ready for merge, release-version: 5.9.5

#7628 Optimize the configuration for RTX evr events
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
Labels: ready for merge, release-version: 5.9.5

#7632 Remove debug print
  features/filesystem/fat/FATFileSystem.cpp
Labels: ready for merge, release-version: 5.9.5

#7641 LoRaWAN: Fixing incorrect NetID causing ABP Failures
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorawan_types.h
Labels: ready for merge, release-version: 5.9.5

#7653 Update mbed-coap version to 4.5.1
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/module.json
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge

#7565 Nuvoton: Fix NUC472 SD-Host HW IP reset definition
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/numaker_emac.cpp
  targets/TARGET_NUVOTON/TARGET_NUC472/device/NUC472_442.h
Labels: ready for merge, release-version: 5.9.5
