Repository ARMmbed/mbed-os, pull requests merged in 2018-09, with the labels that each got.

#7561 Design process and template for Mbed-OS
  docs/design-documents/README.md
  docs/design-documents/design_template.md
  docs/design-documents/diagram_examples/flow_chart_example.jpg
  docs/design-documents/diagram_examples/flow_chart_example.xml
  docs/design-documents/diagram_examples/sequence_diagram_example.jpg
  docs/design-documents/diagram_examples/sequence_diagram_example.xml
  docs/design-documents/diagram_examples/system_arch_example.jpg
  docs/design-documents/diagram_examples/system_arch_example.xml
  docs/design-documents/drivers/README.md
  docs/design-documents/example_feature_design/diagrams/app_hook.jpg
  docs/design-documents/example_feature_design/diagrams/app_hook.xml
  docs/design-documents/example_feature_design/diagrams/error_handling_arch.jpg
  docs/design-documents/example_feature_design/diagrams/error_handling_arch.xml
  docs/design-documents/example_feature_design/diagrams/error_log.jpg
  docs/design-documents/example_feature_design/diagrams/error_log.xml
  docs/design-documents/example_feature_design/diagrams/error_status.jpg
  docs/design-documents/example_feature_design/diagrams/error_status.xml
  docs/design-documents/example_feature_design/diagrams/fault_handler.jpg
  docs/design-documents/example_feature_design/diagrams/fault_handler.xml
  docs/design-documents/example_feature_design/example_feature_design.md
  docs/design-documents/features/connectivity/README.md
  docs/design-documents/features/filesystem/README.md
  docs/design-documents/features/security/README.md
  docs/design-documents/features/storage/README.md
  docs/design-documents/hal/README.md
  docs/design-documents/platform/README.md
  docs/design-documents/rtos/README.md
  docs/design-documents/tools/README.md
Labels: G, ready for merge, release-version: 5.10.0-rc1

#7814 Connectivity drivers
  .travis.yml
  components/802.15.4_RF/atmel-rf-driver/LICENSE
  components/802.15.4_RF/atmel-rf-driver/README.md
  components/802.15.4_RF/atmel-rf-driver/apache-2.0.txt
  components/802.15.4_RF/atmel-rf-driver/atmel-rf-driver/NanostackRfPhyAtmel.h
  components/802.15.4_RF/atmel-rf-driver/mbed_lib.json
  components/802.15.4_RF/atmel-rf-driver/source/AT86RFReg.h
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.cpp
  components/802.15.4_RF/atmel-rf-driver/source/at24mac.cpp
  components/802.15.4_RF/atmel-rf-driver/source/at24mac.h
  components/802.15.4_RF/mcr20a-rf-driver/LICENSE
  components/802.15.4_RF/mcr20a-rf-driver/README.md
  components/802.15.4_RF/mcr20a-rf-driver/apache-2.0.txt
  components/802.15.4_RF/mcr20a-rf-driver/mbed_lib.json
  components/802.15.4_RF/mcr20a-rf-driver/mcr20a-rf-driver/NanostackRfPhyMcr20a.h
  components/802.15.4_RF/mcr20a-rf-driver/source/MCR20Drv.c
  components/802.15.4_RF/mcr20a-rf-driver/source/MCR20Drv.h
  components/802.15.4_RF/mcr20a-rf-driver/source/MCR20Overwrites.h
  components/802.15.4_RF/mcr20a-rf-driver/source/MCR20Reg.h
  components/802.15.4_RF/mcr20a-rf-driver/source/NanostackRfPhyMcr20a.cpp
  components/802.15.4_RF/mcr20a-rf-driver/source/XcvrSpi.h
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
  components/wifi/esp8266-driver/README.md
  components/wifi/esp8266-driver/mbed_lib.json
  doxyfile_options
  doxygen_options.json
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/sal-stack-nanostack/mbed_lib.json
  features/netsocket/mbed_lib.json
  targets/targets.json
  tools/test/examples/examples.json
  tools/test_configs/config_paths.json
  tools/test_configs/no_network.json
  tools/test_configs/target_configs.json
Labels: G, needs: CI, release-version: 5.10.0-rc1

#7806 LoRaWAN: Fixing Hard fault in CN470 PHY layer
  features/lorawan/FSB_Usage.txt
  features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN470.h
  features/lorawan/mbed_lib.json
Labels: ready for merge, release-version: 5.10.0-rc1

#7426 NFC APIs Design Specification
  docs/design-documents/nfc/interop_test_rig.png
  docs/design-documents/nfc/nfc_design.md
  docs/design-documents/nfc/phase_1_architecture.png
  docs/design-documents/nfc/phase_2_architecture.png
  docs/design-documents/nfc/uml_diagram_controller.png
  docs/design-documents/nfc/uml_diagram_controller.txt
  docs/design-documents/nfc/uml_diagram_endpoints.png
  docs/design-documents/nfc/uml_diagram_endpoints.txt
  docs/design-documents/nfc/uml_diagram_ndef_common_parsers.png
  docs/design-documents/nfc/uml_diagram_ndef_common_parsers.txt
  docs/design-documents/nfc/uml_diagram_ndef_message_builder_diagram.png
  docs/design-documents/nfc/uml_diagram_ndef_message_builder_diagram.txt
  docs/design-documents/nfc/uml_diagram_ndef_message_parser.png
  docs/design-documents/nfc/uml_diagram_ndef_message_parser.txt
  docs/design-documents/nfc/uml_diagram_ndef_record_parser.png
  docs/design-documents/nfc/uml_diagram_ndef_record_parser.txt
  docs/design-documents/nfc/uml_diagram_ndef_simple_parser.png
  docs/design-documents/nfc/uml_diagram_ndef_simple_parser.txt
Labels: G, ready for merge, release-version: 5.10.0-rc1

#7683 Renesas : Improve LWIP speed
  features/lwipstack/lwipopts.h
  features/lwipstack/mbed_lib.json
Labels: ready for merge, release-version: 5.10.0-rc1

#7907 Update mbed-coap to version 4.6.2
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/module.json
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: needs: CI, release-version: 5.10.0-rc1

#7099 Add reference counter for platform context
  features/cryptocell/FEATURE_CRYPTOCELL310/Readme.md
  features/cryptocell/FEATURE_CRYPTOCELL310/TARGET_MCU_NRF52840/crypto_platform.c
  features/cryptocell/FEATURE_CRYPTOCELL310/TARGET_MCU_NRF52840/crypto_platform.h
  features/cryptocell/FEATURE_CRYPTOCELL310/trng.c
  features/mbedtls/platform/inc/platform_alt.h
  features/mbedtls/platform/inc/platform_mbed.h
  features/mbedtls/platform/src/platform_alt.c
Labels: needs: review, release-version: 5.10.0-rc1

#7726 Update BLE error calls to use new error codes and mbed_error
  features/FEATURE_BLE/ble/services/EddystoneService.h
  features/FEATURE_BLE/source/BLE.cpp
  platform/mbed_error.h
Labels: needs: CI, release-version: 5.10.0-rc1

#7423 Fix issue #6872 - Mutex lock has possibility to fail at runtime (returning status flag)
  TESTS/mbedmicro-rtos-mbed/mutex/main.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  rtos/Mutex.cpp
  rtos/Mutex.h
Labels: needs: CI, release-version: 5.10.0-rc1

#7952 Prevent sector-unaligned erase
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.h
  components/storage/blockdevice/COMPONENT_SPIF/TESTS/block_device/spif/main.cpp
Labels: needs: CI, release-version: 5.10.0-rc1

#7895 Lora: Remove duplicate LinkCheckReq MAC command
  features/lorawan/LoRaWANStack.cpp
Labels: needs: CI, release-version: 5.10.0-rc1

#7893 Lora: Improve description of callback methods
  features/lorawan/lorawan_types.h
Labels: needs: CI, release-version: 5.10.0-rc2

#7964 NFC: fix reading from NFC EEPROM
  features/nfc/source/nfc/NFCEEPROM.cpp
Labels: ready for merge, release-version: 5.10.0-rc2

#7824 Use MbedCRC for LittleFS
  drivers/MbedCRC.cpp
  drivers/MbedCRC.h
  drivers/TableCRC.cpp
  drivers/TableCRC.h
  features/storage/filesystem/littlefs/LittleFileSystem.cpp
  features/storage/filesystem/littlefs/littlefs/lfs_util.c
  hal/crc_api.h
Labels: ready for merge, release-version: 5.10.0-rc2

#7904 MIMXRT1050_EVK: Update SPI HAL driver
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/spi_api.c
Labels: ready for merge, release-version: 5.10.1, release-version: 5.9.7

#6293 Reduce .text footprint of the network stack
  features/cellular/UNITTESTS/stubs/SocketAddress_stub.cpp
  features/netsocket/SocketAddress.cpp
Labels: ready for merge, release-version: 5.10.1, release-version: 5.9.7

#7924 Add special handling for "/default" filesystem
  features/storage/TESTS/filesystem/general_filesystem/main.cpp
  features/storage/system_storage/SystemStorage.cpp
  platform/FileBase.cpp
  platform/FileBase.h
Labels: ready for merge, release-version: 5.10.0-rc2

#7779 Fix for nrf52 pwm issues
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/pwmout_api.c
Labels: needs: CI, release-version: 5.9.7

#7988 Unittesting: Update mutex stub
  UNITTESTS/stubs/Mutex_stub.cpp
Labels: ready for merge, release-version: 5.10.0-rc2

#8012 IOTCORE-389 - bring back legacy alignment for Arm C6
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge, release-version: 5.10.0-rc2

#7985 Unittesting: Update Mbed CLI subcommand in Readme
  UNITTESTS/README.md
Labels: ready for merge, release-version: 5.10.0-rc2

#8020 Update mbed-coap to version 4.6.3
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/module.json
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: needs: CI, release-version: 5.10.0-rc2

#8015 QSPI driver: API parameters fix
  drivers/QSPI.cpp
  drivers/QSPI.h
Labels: needs: CI, release-version: 5.10.0-rc2

#7720 python scripts : table print with github policy
  tools/build_api.py
  tools/memap.py
  tools/test_api.py
Labels: needs: CI, release-version: 5.10.0-rc2

#8022 Update Mbed TLS version to 2.13.1
  features/mbedtls/VERSION.txt
  features/mbedtls/importer/Makefile
  features/mbedtls/inc/mbedtls/config.h
  features/mbedtls/inc/mbedtls/platform_util.h
  features/mbedtls/inc/mbedtls/threading.h
  features/mbedtls/inc/mbedtls/version.h
  features/mbedtls/src/platform_util.c
  features/mbedtls/src/threading.c
  features/mbedtls/src/x509.c
Labels: ready for merge, release-version: 5.10.0-rc2

#7990 DISCO_L475VG_IOT01A remove old QSPI pins
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PinNames.h
Labels: ready for merge, release-version: 5.10.0-rc2

#7991 fix example code in QSPI.h
  drivers/QSPI.h
Labels: ready for merge, release-version: 5.10.0-rc2

#8016 [OOB 5.10] Fix typo
  TEST_APPS/readme.md
Labels: needs: CI, release-version: 5.10.0-rc2

#7971 Fix memory reservation for Softdevice in NRF52_DK
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_ARM_STD/nRF52832.sct
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_GCC_ARM/NRF52832.ld
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_IAR/nRF52832.icf
  tools/toolchains/__init__.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
Labels: needs: CI, release-version: 5.10.0-rc2

#7950 Fix memory allocation on STM32L4 devices
  targets/TARGET_STM/TARGET_STM32L4/l4_retarget.c
Labels: needs: CI, release-version: 5.10.0-rc2

#7803 Add Socket test plan
  TESTS/netsocket/README.md
  TESTS/netsocket/eth_environment.png
  TESTS/netsocket/wifi_environment.png
Labels: needs: CI, release-version: 5.10.0-rc2

#8079 BUGFIX: Remove account management API calls from DM
  tools/device_management.py
Labels: needs: CI, release-version: 5.10.0-rc3

#8092 Fix quotes around gcovr install command for Windows
  UNITTESTS/README.md
Labels: needs: CI, release-version: 5.10.0-rc3

#8031 Fix TCPServer::accept()
  features/netsocket/TCPServer.cpp
Labels: ready for merge, release-version: 5.10.0-rc3

#8066 Move unittest paths to hyphens
  UNITTESTS/README.md
  UNITTESTS/features/cellular/framework/AT/AT_CellularBase/unittest.cmake
  UNITTESTS/features/cellular/framework/common/util/unittest.cmake
  UNITTESTS/features/netsocket/InternetSocket/unittest.cmake
  UNITTESTS/features/netsocket/NetworkInterface/unittest.cmake
  UNITTESTS/features/netsocket/TCPSocket/unittest.cmake
  UNITTESTS/features/netsocket/UDPSocket/unittest.cmake
  UNITTESTS/platform/CircularBuffer/unittest.cmake
Labels: needs: CI, release-version: 5.10.0-rc3

#8086 Fix SocketAddress unittests
  UNITTESTS/CMakeLists.txt
  UNITTESTS/features/netsocket/InternetSocket/unittest.cmake
  UNITTESTS/features/netsocket/TCPSocket/unittest.cmake
  UNITTESTS/features/netsocket/UDPSocket/unittest.cmake
Labels: ready for merge, release-version: 5.10.0-rc3

#8075 Syncronize mbed-ls minimum version with icetea requirements
  requirements.txt
Labels: G, release-version: 5.10.0-rc3

#7992 Fix TCPSocket::accept()
  features/netsocket/TCPSocket.cpp
Labels: ready for merge, release-version: 5.10.1

#7945 Move SYNCHRONOUS_DNS_CACHE test to extended set
  TESTS/netsocket/dns/main.cpp
Labels: G, needs: CI, release-version: 5.10.0-rc3

#8063 `mbed dm`: Accept api key and host on the command line
  tools/device_management.py
Labels: G, needs: CI, release-version: 5.10.0-rc3

#8140 requiremnts: Bump IceTea
  requirements.txt
Labels: G, needs: CI, release-version: 5.10.0-rc3

#8123 Unit tests: fix coverage exclude paths on Windows
  UNITTESTS/unit_test/test.py
Labels: G, needs: CI, release-version: 5.10.0-rc3

#8100 Allow storage doxy to build
  doxyfile_options
  doxygen_options.json
Labels: G, needs: CI, release-version: 5.10.0-rc3

#7901 Compiler Warning fixes
  hal/mbed_ticker_api.c
  rtos/TARGET_CORTEX/mbed_rtx_handlers.c
Labels: ready for merge, release-version: 5.10.1

#7960 Change mbedtls_platform_context parameter to NULL
  TESTS/mbedtls/multi/main.cpp
  TESTS/mbedtls/selftest/main.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xCrypto.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xCrypto.h
Labels: ready for merge, release-version: 5.10.1

#7982 LoRaWAN: Memory overrun correction
  features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
Labels: ready for merge, release-version: 5.10.1

#8010 NXP: Update serial driver's parity handling
  targets/TARGET_NXP/TARGET_LPC11U6X/serial_api.c
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/serial_api.c
  targets/TARGET_NXP/TARGET_LPC13XX/serial_api.c
  targets/TARGET_NXP/TARGET_LPC15XX/serial_api.c
  targets/TARGET_NXP/TARGET_LPC176X/serial_api.c
  targets/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088/serial_api.c
  targets/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088_DM/serial_api.c
  targets/TARGET_NXP/TARGET_LPC43XX/serial_api.c
  targets/TARGET_NXP/TARGET_LPC81X/serial_api.c
Labels: ready for merge, release-version: 5.10.1

#8052 FileBase: Fix unsetting of default when destroyed
  platform/FileBase.cpp
Labels: ready for merge, release-version: 5.10.1

#8067 Spelling fixes and general readability improvements for TEST_APPS documentation
  TEST_APPS/readme.md
Labels: ready for merge, release-version: 5.10.1

#7969 Cellular: CellularDevice:get_default_instance() implemented
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
  features/cellular/easy_cellular/CellularConnectionFSM.h
  features/cellular/easy_cellular/EasyCellularConnection.cpp
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.h
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.h
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96.cpp
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96.h
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.h
  features/cellular/framework/targets/UBLOX/PPP/UBLOX_PPP.cpp
  features/cellular/framework/targets/UBLOX/PPP/UBLOX_PPP.h
Labels: ready for merge, release-version: 5.11.0-rc1

#8137 Icetea hw restriction
  tools/run_icetea.py
  tools/test/run_icetea/run_icetea_unit_test.py
Labels: A, needs: review, ready for merge, release-version: 5.10.0-rc3

#7856 Realtek: fix gpio is connected
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/gpio_api.c
Labels: ready for merge, release-version: 5.10.1

#7981 BLE: fix missing updates sent callback in GattServer using Cordio stack
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
Labels: ready for merge, release-version: 5.10.1

#7700 STM32: Correct device_has_add flags for bluepill_f103c8 target, fixes #7654
  targets/TARGET_STM/TARGET_STM32F1/TARGET_BLUEPILL_F103C8/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F1/TARGET_BLUEPILL_F103C8/PinNames.h
  targets/targets.json
Labels: ready for merge, release-version: 5.10.1

#7883 netsocket: Fix compiler warning
  features/netsocket/InternetSocket.cpp
Labels: needs: CI, release-version: 5.10.1

#8136 STM: Fix us_ticker timestamp after deep sleep
  targets/TARGET_STM/sleep.c
Labels: ready for merge, release-version: 5.10.1

#7903 Clean up include paths.
  drivers/FlashIAP.cpp
  drivers/Serial.h
  drivers/SerialBase.h
  drivers/UARTSerial.h
  hal/mbed_sleep_manager.c
  hal/mbed_ticker_api.c
  platform/mbed_poll.cpp
  platform/mbed_power_mgmt.h
Labels: ready for merge, release-version: 5.10.1

#8029 Fix issues with LowPowerTickerWrapper
  hal/LowPowerTickerWrapper.cpp
Labels: ready for merge, release-version: 5.10.1

#8025 Align to CMSIS defines for Non-Secure
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_ARM_MICRO/M2351.sct
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_ARM_STD/M2351.sct
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_GCC_ARM/M2351.ld
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_IAR/M2351.icf
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
Labels: ready for merge, release-version: 5.10.1

#7920 Resolve duplicate ADuCM3029 system return code
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TARGET_EV_COG_AD3029LZ/device/system_ADuCM3029.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/bsp/system_ADuCM3029.h
Labels: ready for merge, release-version: 5.10.1

#7882 Add greentea tests for network interface status and connect/disconnect
  TESTS/network/interface/main.cpp
  TESTS/network/interface/networkinterface_conn_disc_repeat.cpp
  TESTS/network/interface/networkinterface_status.cpp
  TESTS/network/interface/networkinterface_tests.h
Labels: ready for merge, release-version: 5.10.1

#8054 Lora: Fix ADRAckReq
  features/lorawan/lorastack/mac/LoRaMac.cpp
Labels: ready for merge, release-version: 5.10.1

#8145 Add bootloader image for Nucleo F207ZG
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/LICENCE
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/mbed-bootloader-nucleo_f207zg-block_device-sotp-v3.4.0-3-gdbbb.bin
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/mbed_lib.json
Labels: ready for merge, release-version: 5.10.1

#8153 Unit tests: automatic unit test suite naming
  UNITTESTS/CMakeLists.txt
  UNITTESTS/README.md
  UNITTESTS/features/cellular/framework/AT/at_cellularbase/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularinformation/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularpower/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularsim/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/athandler/unittest.cmake
  UNITTESTS/features/cellular/framework/common/util/unittest.cmake
  UNITTESTS/features/netsocket/InternetSocket/unittest.cmake
  UNITTESTS/features/netsocket/NetworkInterface/unittest.cmake
  UNITTESTS/features/netsocket/TCPSocket/unittest.cmake
  UNITTESTS/features/netsocket/UDPSocket/unittest.cmake
  UNITTESTS/platform/CircularBuffer/unittest.cmake
  UNITTESTS/template/unittest.cmake.template
  UNITTESTS/unit_test/new.py
Labels: ready for merge, release-version: 5.10.1

#8074 LoRaWAN: Refactoring compliance test code
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorawan_types.h
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.10.1

#7921 Fix Bug : IAR heap memory problem
  targets/TARGET_WIZNET/TARGET_W7500x/TARGET_WIZwiki_W7500/device/TOOLCHAIN_IAR/W7500_Flash.icf
  targets/TARGET_WIZNET/TARGET_W7500x/TARGET_WIZwiki_W7500ECO/device/TOOLCHAIN_IAR/W7500_Flash.icf
  targets/TARGET_WIZNET/TARGET_W7500x/TARGET_WIZwiki_W7500P/device/TOOLCHAIN_IAR/W7500_Flash.icf
Labels: ready for merge, release-version: 5.10.1

#8176 CellularDevice_stub added
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/unittest.cmake
  UNITTESTS/stubs/CellularDevice_stub.cpp
Labels: ready for merge, release-version: 5.10.1

#8160 Update mbed-cloud-sdk in requirements.txt
  requirements.txt
Labels: ready for merge, release-version: 5.10.1

#7935 LoRa: Stop processing MAC commands if command id is unknown
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
Labels: needs: CI, release-version: 5.10.1

#7671 [RFC] SPI HAL Specification
  docs/design-documents/hal/0000-spi-overhaul.md
  docs/design-documents/hal/spi_irq_flow.png
Labels: ready for merge, release-version: feature branch

#7987 M2351: Update to NuMaker-PFM-M2351 V1.3 board
  targets/TARGET_NUVOTON/TARGET_M2351/PinNames.h
Labels: needs: CI, release-version: 5.10.1

#7993 Fix EFM32 pwmout hal function pwmout_period
  targets/TARGET_Silicon_Labs/TARGET_EFM32/pwmout_api.c
Labels: needs: CI, release-version: 5.10.1

#8171 Skip the unstable SYNCHRONOUS_DNS_CACHE testcase
  TESTS/netsocket/dns/main.cpp
Labels: needs: CI, release-version: 5.10.1

#8181 Py3 support
  tools/build_api.py
  tools/run_icetea.py
Labels: needs: CI, release-version: 5.10.1

#7925 Qspi hal test refactoring/update
  TESTS/mbed_hal/qspi/flash_configs/MX25R3235F_config.h
  TESTS/mbed_hal/qspi/flash_configs/MX25RXX35F_config.h
  TESTS/mbed_hal/qspi/flash_configs/N25Q128A_config.h
  TESTS/mbed_hal/qspi/flash_configs/NORDIC/NRF52840_DK/flash_config.h
  TESTS/mbed_hal/qspi/flash_configs/STM/DISCO_L475VG_IOT01A/flash_config.h
  TESTS/mbed_hal/qspi/flash_configs/SiliconLabs/EFM32GG11_STK3701/flash_config.h
  TESTS/mbed_hal/qspi/main.cpp
  TESTS/mbed_hal/qspi/qspi_test_utils.cpp
  TESTS/mbed_hal/qspi/qspi_test_utils.h
  targets/TARGET_NORDIC/TARGET_NRF5x/qspi_api.c
Labels: ready for merge, release-version: 5.10.1

#8060 Clarify test configuration in Socket/Networking test document
  TESTS/netsocket/README.md
Labels: ready for merge, release-version: 5.10.1

#8096 Lora: Fix sticky MAC command retransmissions
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.h
Labels: ready for merge, release-version: 5.10.1

#8112 specify mbed-cli version requirement
  UNITTESTS/README.md
Labels: ready for merge, release-version: 5.10.1

#8187 STM32: fix wrong LSE config in serial_baud function
  targets/TARGET_STM/serial_api.c
Labels: ready for merge, release-version: 5.10.1

#8030 Nuvoton: Fix Greentea test common_tickers failed
  TESTS/mbed_hal/common_tickers/main.cpp
  targets/TARGET_NUVOTON/TARGET_M2351/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M2351/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_M451/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M451/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_M480/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M480/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_NANO100/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_NANO100/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_NUC472/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_NUC472/us_ticker.c
Labels: ready for merge, release-version: 5.10.1

#8023 Hotfix for PR #7778 on Silicon Labs targets
  features/nanostack/sal-stack-nanostack/mbed_lib.json
  features/nanostack/targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/NanostackRfPhyEfr32.cpp
  features/netsocket/mbed_lib.json
  targets/targets.json
  tools/test_configs/target_configs.json
  tools/toolchains/iar.py
Labels: needs: CI, release-version: 5.10.1

#8182 Unit tests: fix cellular athandler unit tests and wait() declaration conflict
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  UNITTESTS/target_h/platform/mbed_retarget.h
  UNITTESTS/target_h/platform/mbed_wait_api.h
Labels: needs: CI, release-version: 5.10.1

#8164 Support Nuvoton's new target NUMAKER_IOT_M487
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/mbedtls_device.h
  targets/TARGET_NUVOTON/TARGET_M480/PinNames.h
  targets/targets.json
Labels: needs: CI, release-version: 5.10.1

#8073 Add documentation about icetea testcases
  TEST_APPS/testcases/README.md
  TEST_APPS/testcases/example/README.md
  TEST_APPS/testcases/netsocket/README.md
Labels: needs: CI, release-version: 5.10.1

#8106 Replace macros with config options
  platform/mbed_lib.json
  rtos/TARGET_CORTEX/mbed_rtos_rtx.c
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
  rtos/mbed_lib.json
Labels: needs: CI, release-version: 5.10.1

#8212 Unit tests: update README.md
  UNITTESTS/README.md
Labels: ready for merge, release-version: 5.10.1

#8019 Cellular: fixed crash when closing CellularNetwork via CellularDevice.
  features/cellular/framework/AT/AT_CellularBase.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
Labels: ready for merge, release-version: 5.10.1

#7989 M2351: Fix STDIO_UART error
  targets/TARGET_NUVOTON/TARGET_M2351/PeripheralNames.h
Labels: ready for merge, release-version: 5.10.1

#8005 BLE: fix whitelist generation (set correct address type)
  features/FEATURE_BLE/ble/generic/SecurityDb.h
Labels: ready for merge, release-version: 5.10.1

#8165 Fix for issue #8155 (NRF52832: time stops after 35 minutes)
  platform/mbed_rtc_time.cpp
Labels: ready for merge, release-version: 5.10.1

#8009 LPC1768: Enable RTC
  targets/targets.json
Labels: ready for merge, release-version: 5.10.1

#7955 Add SPI_FREQ parameter to DATAFLASH block device configuration
  components/storage/blockdevice/COMPONENT_DATAFLASH/DataFlashBlockDevice.h
  components/storage/blockdevice/COMPONENT_DATAFLASH/mbed_lib.json
Labels: ready for merge, release-version: 5.11.0-rc1

#8037 STM32: Fix disabling of IRQs shared by multiple events
  targets/TARGET_STM/gpio_irq_api.c
Labels: ready for merge, release-version: 5.10.1

#8229 Fix network and util ut
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  UNITTESTS/features/cellular/framework/common/util/utiltest.cpp
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: needs: CI, release-version: 5.10.1

#7941 Nuvoton: Fix GPIO mode mapping
  targets/TARGET_NUVOTON/TARGET_M2351/PinNames.h
  targets/TARGET_NUVOTON/TARGET_M2351/gpio_api.c
  targets/TARGET_NUVOTON/TARGET_M2351/gpio_object.h
  targets/TARGET_NUVOTON/TARGET_M2351/pinmap.c
  targets/TARGET_NUVOTON/TARGET_M451/PinNames.h
  targets/TARGET_NUVOTON/TARGET_M451/gpio_api.c
  targets/TARGET_NUVOTON/TARGET_M451/gpio_object.h
  targets/TARGET_NUVOTON/TARGET_M451/pinmap.c
  targets/TARGET_NUVOTON/TARGET_M480/PinNames.h
  targets/TARGET_NUVOTON/TARGET_M480/gpio_api.c
  targets/TARGET_NUVOTON/TARGET_M480/gpio_object.h
  targets/TARGET_NUVOTON/TARGET_M480/pinmap.c
  targets/TARGET_NUVOTON/TARGET_NANO100/PinNames.h
  targets/TARGET_NUVOTON/TARGET_NANO100/gpio_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/gpio_object.h
  targets/TARGET_NUVOTON/TARGET_NANO100/pinmap.c
  targets/TARGET_NUVOTON/TARGET_NUC472/PinNames.h
  targets/TARGET_NUVOTON/TARGET_NUC472/gpio_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/gpio_object.h
  targets/TARGET_NUVOTON/TARGET_NUC472/pinmap.c
Labels: needs: CI, release-version: 5.10.1

#8154 Unit tests: add code coverage filtering
  UNITTESTS/mbed_unittest.py
  UNITTESTS/unit_test/coverage.py
  UNITTESTS/unit_test/options.py
  UNITTESTS/unit_test/settings.py
  UNITTESTS/unit_test/test.py
Labels: ready for merge, release-version: 5.10.1

#7057 Add TRNG API test
  TESTS/host_tests/trng_reset.py
  TESTS/mbed_hal/trng/base64b/base64b.cpp
  TESTS/mbed_hal/trng/base64b/base64b.h
  TESTS/mbed_hal/trng/main.cpp
  TESTS/mbed_hal/trng/pithy/pithy.c
  TESTS/mbed_hal/trng/pithy/pithy.h
Labels: component: tls, ready for merge, release-version: 5.10.1, tracking

#7911 travis: add license check for gnu library license
  .travis.yml
Labels: ready for merge, release-version: 5.10.1

#7696 skip the flashsim test if not enough memory cannot be allocated for it.
  features/storage/TESTS/blockdevice/flashsim_block_device/main.cpp
Labels: ready for merge, release-version: 5.10.1

#8099 MIMXRT1050_EVK: Fix the PWM Hal driver
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/pwmout_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PeripheralNames.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PeripheralPins.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/mbed_overrides.c
Labels: ready for merge, release-version: 5.10.1

#8247 Update Manifest tool version
  requirements.txt
Labels: ready for merge, release-version: 5.10.1

#7890 Circular buffer should use conditional statement instead of modulo
  TESTS/mbed_platform/CircularBuffer/main.cpp
  platform/CircularBuffer.h
Labels: ready for merge

#7926 Increase the timeout for rtostimer test to 10s
  TESTS/mbedmicro-rtos-mbed/rtostimer/main.cpp
Labels: ready for merge

#7934 corrected a typo in AT_CellularPower::opt_power_save_mode
  features/cellular/framework/AT/AT_CellularPower.cpp
Labels: ready for merge

#7953 Fix is_valid_erase function to use get_erase_size with address
  features/storage/blockdevice/BlockDevice.h
Labels: ready for merge

#8132 gt netsocket tcp - increases threads' stack size
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tcp/tcpsocket_thread_per_socket_safety.cpp
Labels: needs: CI, release-version: 5.10.1

#8246 Add back examples updated for mbed-os-5.10
  tools/test/examples/examples.json
Labels: needs: CI, release-version: 5.10.1
