Repository ARMmbed/mbed-os, pull requests merged in 2018-05, with the labels that each got.

#6765 Cellular: Fix AT Handler compile warning
  features/cellular/framework/AT/ATHandler.cpp
Labels: ready for merge, release-version: 5.8.4

#6778 Add support for open drain leds
  targets/TARGET_Maxim/TARGET_MAX32625/gpio_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.8.4

#6774 littlefs: Fix issue with trailing dots in file paths
  features/filesystem/littlefs/littlefs/lfs.c
  features/filesystem/littlefs/littlefs/tests/test_paths.sh
Labels: ready for merge, release-version: 5.8.4, scope: bug-fix

#6762 Fix compile error with MBED_MEM_TRACING_ENABLED and ARMC6
  platform/mbed_retarget.cpp
Labels: ready for merge, release-version: 5.8.4

#6740 Lora: Fix max tx power check
  features/lorawan/lorastack/phy/LoRaPHY.cpp
Labels: ready for merge, release-version: 5.8.4

#6729 Add bootloader support for NUCLEO_F411RE target
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/TOOLCHAIN_ARM_STD/stm32f411re.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/TOOLCHAIN_GCC_ARM/STM32F411XE.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/TOOLCHAIN_IAR/stm32f411xe.icf
  targets/targets.json
Labels: ready for merge, release-version: 5.8.4

#6713 Drop include paths for ARM assembler
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/TOOLCHAIN_ARM_STD/startup_MPS2.S
  tools/export/uvision/uvision.tmpl
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.8.4

#6675 Add SAI/SAITransmitter/SAIReceiver class tests.
  TESTS/mbed_drivers/sai/main.cpp
Labels: ready for merge

#6761 Updated non-blocking connect changes to EMAC greentea test network stack
  TESTS/network/emac/emac_TestNetworkStack.cpp
  TESTS/network/emac/emac_TestNetworkStack.h
Labels: ready for merge

#6798 Fix bug in MBR for NRF52 series
  targets/TARGET_NORDIC/TARGET_NRF5x/reloc_vector_table.c
Labels: ready for merge, release-version: 5.8.5

#6796 Fix us_ticker for NRF52 series
  targets/TARGET_NORDIC/TARGET_NRF5x/us_ticker.c
Labels: ready for merge, release-version: 5.8.5

#6819 Remove example update scripting from tools
  tools/test/examples/examples.json
  tools/test/examples/pr.tmpl
  tools/test/examples/update.py
Labels: ready for merge, release-version: 5.9.0-rc1

#6797 Fix compile error with DirectSerial in serial-less build
  platform/mbed_retarget.cpp
Labels: ready for merge, release-version: 5.8.5

#6793 tools: Pass app-config to get_config
  tools/build_api.py
  tools/get_config.py
  tools/test/test_api/test_api_test.py
  tools/test_api.py
Labels: ready for merge, release-version: 5.8.5

#6792 Cellular: Add dynamic alloc and destruction to easycellular
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
  features/cellular/easy_cellular/CellularConnectionFSM.h
  features/cellular/easy_cellular/EasyCellularConnection.cpp
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: ready for merge, release-version: 5.9.0-rc1

#6788 mbed_ticker_api remove specific case for 32768 in favor of all frequencies divisible by 2
  hal/mbed_ticker_api.c
  hal/ticker_api.h
Labels: ready for merge

#6768 Nano 100: Lower HEAP size for IAR
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_IAR/NANO130.icf
Labels: ready for merge, release-version: 5.8.5

#6769 Move subtract basepath into the resources class
  tools/export/__init__.py
  tools/toolchains/__init__.py
Labels: ready for merge, release-version: 5.8.5

#6771 Fix UART initialization for NRF52
  targets/TARGET_NORDIC/TARGET_NRF5x/serial_api.c
Labels: ready for merge, release-version: 5.9.0-rc1

#6773 Enlarge timer thread stack size for Cortex-M23/M33
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
Labels: ready for merge, release-version: 5.8.5

#6728 Fix issue template - simplified version
  .github/issue_template.md
Labels: ready for merge, release-version: 5.8.5

#6657 add ncs36510 fib and trim generation
  targets/TARGET_ONSEMI/TARGET_NCS36510/device/TOOLCHAIN_GCC_ARM/NCS36510.ld
  tools/export/codeblocks/__init__.py
  tools/export/codeblocks/cbp.tmpl
  tools/export/codeblocks/ncs36510fib.c
  tools/export/codeblocks/ncs36510trim.c
Labels: ready for merge, release-version: 5.9.0-rc1

#6654 Add missing carriage returns to fault handler
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.c
Labels: ready for merge, release-version: 5.9.0-rc1

#6781 tools: Refactor notification API
  tools/build.py
  tools/build_api.py
  tools/colorize.py
  tools/export/__init__.py
  tools/make.py
  tools/notifier/__init__.py
  tools/notifier/mock.py
  tools/notifier/term.py
  tools/project.py
  tools/settings.py
  tools/targets/__init__.py
  tools/test.py
  tools/test/build_api/build_api_test.py
  tools/test/toolchains/api_test.py
  tools/test_api.py
  tools/toolchains/__init__.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
Labels: needs: CI, release-version: 5.9.0-rc1

#6610 Stm32 eth remove tx rx locking interrupt perforation
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_eth.c
Labels: needs: CI, release-version: 5.8.5

#6805 tools: Reorder test configuration priority
  tools/test.py
Labels: ready for merge, release-version: 5.8.5

#6800 Lora: Fix LoRaMacCrypto asserts
  features/lorawan/lorastack/mac/LoRaMacCrypto.cpp
Labels: needs: CI, release-version: 5.8.5

#6814 GenericGattClient: Fix discovery termination.
  features/FEATURE_BLE/source/generic/GenericGattClient.cpp
Labels: ready for merge, release-version: 5.8.5

#6743 BLE: Conditional compilation of H4 driver
  features/FEATURE_BLE/targets/TARGET_CORDIO/doc/PortingGuide.md
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/H4TransportDriver.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/H4TransportDriver.h
Labels: ready for merge, release-version: 5.8.5

#6742 BLE: Update cordio porting guide
  features/FEATURE_BLE/targets/TARGET_CORDIO/doc/PortingGuide.md
Labels: ready for merge, release-version: 5.8.5

#6808 LoRa: State machine work
  features/lorawan/LoRaRadio.h
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.cpp
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMacChannelPlan.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.h
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYAS923.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.h
  features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN470.h
  features/lorawan/lorastack/phy/LoRaPHYCN779.cpp
  features/lorawan/lorastack/phy/LoRaPHYEU433.cpp
  features/lorawan/lorastack/phy/LoRaPHYEU868.cpp
  features/lorawan/lorastack/phy/LoRaPHYIN865.cpp
  features/lorawan/lorastack/phy/LoRaPHYKR920.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.h
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.h
  features/lorawan/lorastack/phy/lora_phy_ds.h
  features/lorawan/lorawan_types.h
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6809 Mbed Stats: Assert if NULL pointer passed as arg
  platform/mbed_stats.c
Labels: ready for merge, release-version: 5.8.5

#6849 Add missing semicolon to NRF51 critical_section implementation
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_MCU_NRF51822/hal_patch/critical_section_api.c
Labels: ready for merge, release-version: 5.8.5

#6817 GenericSecurityManager: Fix crypto_toolbox_f4 signature.
  features/FEATURE_BLE/ble/generic/GenericSecurityManager.h
Labels: ready for merge, release-version: 5.8.5

#6845 Remove obsolete OS_IDLE_THREAD_STACK_SIZE from NRF52
  targets/TARGET_NORDIC/mbed_rtx.h
Labels: ready for merge, release-version: 5.8.5

#6784 Add common define MBED_ALL_STATS_ENABLED to enable all statistics
  mbed.h
  platform/mbed_stats.c
  platform/mbed_stats.h
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6852 Fix for issue #5308 - RTC set/get time issue on NCS36510
  TESTS/mbed_drivers/rtc/main.cpp
  targets/TARGET_ONSEMI/TARGET_NCS36510/rtc_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.8.5

#6879 Build mbed-os-example-lora only for lora targets
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.8.5

#6864 FlashIAP: Fix problem of programming source buffer not aligned to 4
  TESTS/mbed_drivers/flashiap/main.cpp
  drivers/FlashIAP.cpp
Labels: ready for merge, release-version: 5.8.5

#6882 lwIP: Enable TCP out-of-order processing
  features/FEATURE_LWIP/lwip-interface/lwipopts.h
Labels: ready for merge

#6838 export: Fix invalid config header path in Sw4STM32
  tools/export/sw4stm32/__init__.py
  tools/export/sw4stm32/cproject_common.tmpl
Labels: ready for merge, release-version: 5.8.5

#6833 mbed test: add argument `--ignore` to allow passing in mbedignore patterns
  tools/build.py
  tools/build_api.py
  tools/export/__init__.py
  tools/make.py
  tools/project.py
  tools/test.py
  tools/test_api.py
Labels: ready for merge, release-version: 5.9.0-rc1

#6883 Update mbed-coap to version 4.4.3
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_coap_header.h
  features/frameworks/mbed-coap/module.json
  features/frameworks/mbed-coap/source/include/sn_coap_protocol_internal.h
  features/frameworks/mbed-coap/source/sn_coap_parser.c
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: release-version: 5.8.5

#6875 Lora: Fix battery_level callback
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.h
  features/lorawan/lorawan_types.h
Labels: release-version: 5.8.5

#6839 Lora: fix AU915 build
  features/lorawan/lorastack/phy/loraphy_target.h
Labels: release-version: 5.9.0-rc1

#6885 BL mode: Prevent jump address conflicts
  tools/build_api.py
Labels: release-version: 5.8.5

#6892 LoRaWAN: Wrong type of message check
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
Labels: release-version: 5.9.0-rc1

#6795 Thread stats API
  TESTS/mbed_platform/stats_thread/main.cpp
  platform/mbed_stats.c
  platform/mbed_stats.h
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6886 Corrected iteritems py2/3 compatability in test_api.py
  requirements.txt
  tools/test_api.py
Labels: ready for merge, release-version: 5.9.0-rc1

#6881 USB basic test update
  TESTS/host_tests/pyusb_basic.py
  TESTS/usb_device/basic/main.cpp
Labels: ready for merge

#6865 fix greentea-client, require a character input between K-V pairs
  features/frameworks/greentea-client/source/greentea_test_env.cpp
Labels: ready for merge, release-version: 5.8.5

#6917 Travis: Quick name-fix for warnings reported by Astyle
  .travis.yml
Labels: ready for merge, release-version: 5.8.5

#6919 tools: Add explicit target for NVStore example
  tools/test/examples/examples.json
Labels: needs: CI, release-version: 5.8.5

#6937 Add memory manager set to add_ethernet_interface() of test stack
  TESTS/network/emac/emac_TestNetworkStack.cpp
  TESTS/network/emac/emac_test_initialize.cpp
  features/netsocket/OnboardNetworkStack.h
Labels: needs: CI

#6559 Implement FlashSimBlockDevice - flash simulated block device over RAM
  features/TESTS/filesystem/flashsim_block_device/main.cpp
  features/filesystem/bd/FlashSimBlockDevice.cpp
  features/filesystem/bd/FlashSimBlockDevice.h
Labels: needs: review, release-version: 5.9.0-rc1

#6940 NVStore - remove Thread.h include
  features/nvstore/source/nvstore.cpp
Labels: ready for merge, release-version: 5.8.5

#6926 Corrected lwip netif flags to be set before power up
  features/FEATURE_LWIP/lwip-interface/LWIPInterfaceEMAC.cpp
Labels: ready for merge

#6904 add-rtl8195am-feature-emac
  TESTS/network/emac/template_mbed_app.txt
  targets/TARGET_Realtek/TARGET_AMEBA/.mbedignore
  targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.cpp
  targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.h
  targets/TARGET_Realtek/TARGET_AMEBA/rtw_emac.cpp
  targets/TARGET_Realtek/TARGET_AMEBA/rtw_emac.h
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/drivers/wlan/realtek/src/osdep/lwip_intf.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/drivers/wlan/realtek/src/osdep/lwip_intf.h
  targets/targets.json
  tools/test_configs/RealtekInterface.json
Labels: needs: CI, release-version: 5.9.0-rc1

#6953 Updated ublox odin greentea test configuration file connect statement
  tools/test_configs/OdinInterface.json
Labels: ready for merge

#6855 Add NetworkInterface::get_default_instance()
  features/nanostack/mbed-mesh-api/source/LoWPANNDInterface.cpp
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/ThreadInterface.cpp
  features/nanostack/nanostack-interface/NanostackRfPhy.h
  features/netsocket/CellularBase.h
  features/netsocket/EthInterface.h
  features/netsocket/EthernetInterface.cpp
  features/netsocket/MeshInterface.h
  features/netsocket/NetworkInterface.h
  features/netsocket/NetworkInterfaceDefaults.cpp
  features/netsocket/WiFiInterface.h
  features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.cpp
  features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.h
  features/netsocket/mbed_lib.json
  targets/targets.json
Labels: ready for merge

#6939 NOT_SUPPORTED error was not supported any more in test_api.py script
  tools/test_api.py
Labels: ready for merge, release-version: 5.9.0-rc1

#6905 Lora: Remove obsolete FEATURE_COMMON_PAL flags
  .travis.yml
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
Labels: ready for merge, release-version: 5.9.0-rc1

#6901 events: Introduce API to query how much time is left for delayed event
  TESTS/events/queue/main.cpp
  events/EventQueue.cpp
  events/EventQueue.h
  events/equeue/equeue.c
  events/equeue/equeue.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6823 tools: Remove long-deprecated build_everything.py
  tools/build_everything.py
Labels: ready for merge, release-version: 5.9.0-rc1

#6821 System stats - API addition
  TESTS/mbed_platform/stats_sys/main.cpp
  platform/mbed_stats.c
  platform/mbed_stats.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6951 STM32 SPI: fix NSS pin configuration
  targets/TARGET_STM/stm_spi_api.c
Labels: ready for merge, release-version: 5.8.6

#6866 fatfs: Add erase disk to format
  features/filesystem/fat/FATFileSystem.cpp
Labels: needs: review, release-version: 5.9.0-rc1

#6791 Add POSIX fcntl flag support
  drivers/UARTSerial.h
  platform/FileHandle.h
  platform/mbed_retarget.cpp
  platform/mbed_retarget.h
Labels: release-version: 5.9.0-rc1

#6480 NVStore: add the allocate_key API (instead of set_alloc_key)
  features/nvstore/TESTS/nvstore/functionality/main.cpp
  features/nvstore/source/nvstore.cpp
  features/nvstore/source/nvstore.h
Labels: BREAKING-CHANGE, needs: review, release-version: 5.9.0-rc1

#6757 Implement BufferedBlockDevice
  features/TESTS/filesystem/buffered_block_device/main.cpp
  features/filesystem/bd/BufferedBlockDevice.cpp
  features/filesystem/bd/BufferedBlockDevice.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6336 fatfs: Update error code mapping
  features/filesystem/fat/FATFileSystem.cpp
  platform/mbed_retarget.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 5.9.0-rc1

#6857 CPU Statistics
  TESTS/mbed_platform/stats_cpu/main.cpp
  hal/mbed_sleep_manager.c
  platform/mbed_power_mgmt.h
  platform/mbed_stats.c
  platform/mbed_stats.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6878 Add low power timer fallback for platforms without RTC
  platform/mbed_rtc_time.cpp
Labels: ready for merge, release-version: 5.9.0-rc1

#6959 Remove unused ITM implementation from NRF51 series
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF51/itm_api.c
Labels: ready for merge, release-version: 5.9.0-rc1

#6896 Export folder needs to not ignore .mbed files.
  tools/export/.gitignore
Labels: ready for merge, release-version: 5.8.6

#6709 Update watchdog tests -- allow shorter timeouts
  TESTS/mbed_drivers/watchdog/main.cpp
  TESTS/mbed_drivers/watchdog_reset/main.cpp
  TESTS/mbed_hal/watchdog/main.cpp
  TESTS/mbed_hal/watchdog_reset/main.cpp
Labels: ready for merge

#6772 littlefs: Map LFS_ERR_CORRUPT to EILSEQ
  features/filesystem/littlefs/LittleFileSystem.cpp
Labels: BREAKING-CHANGE, ready for merge, release-version: 5.9.0-rc1

#6968 Test build: Reduce include command length
  tools/test.py
Labels: ready for merge, release-version: 5.8.6

#6989 KW41Z: Enable SLEEP feature
  targets/targets.json
Labels: needs: CI

#6964 Adding Sleep and usticker to MTB_ODIN_W2
  targets/targets.json
Labels: needs: work

#6912 Enable RTC on MCUXpresso devices
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/rtc_api.c
  targets/targets.json
Labels: needs: work

#6993 CPU Stats test - Increased wait time to allow device to sleep
  TESTS/mbed_platform/stats_cpu/main.cpp
Labels: ready for merge, release-version: 5.9.0-rc1

#6642 Device key implementation
  features/device_key/README.md
  features/device_key/TESTS/device_key/functionality/main.cpp
  features/device_key/mbed_lib.json
  features/device_key/source/DeviceKey.cpp
  features/device_key/source/DeviceKey.h
  features/mbedtls/inc/mbedtls/config-no-entropy.h
  features/mbedtls/inc/mbedtls/config.h
  features/nvstore/source/nvstore.h
Labels: component: tls, mirrored, ready for merge, release-version: 5.9.0-rc1, tracking

#6927 Cellular: AT debugging improved
  features/cellular/README.md
  features/cellular/TESTS/socket/udp/main.cpp
  features/cellular/TESTS/socket/udp/template_mbed_app.json.txt
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularSIM.cpp
  features/cellular/framework/common/CellularLog.cpp
  features/cellular/framework/common/CellularLog.h
  features/cellular/mbed_lib.json
Labels: release-version: 5.9.0-rc1

#6433 Enabl-able Python 3 tools testing in Travis CI
  .travis.yml
Labels: needs: CI, release-version: 5.9.0-rc1

#7003 Add devicekey example to examples list
  tools/test/examples/examples.json
Labels: G, ready for merge, release-version: 5.9.0-rc1

#7015 Fix build for MBT_ODIN_W2 and MBED_CONNECT_ODIN when using WiFi
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MBED_CONNECT_ODIN/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MBED_CONNECT_ODIN/stm32f4_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MODULE_UBLOX_ODIN_W2/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MODULE_UBLOX_ODIN_W2/stm32f4_eth_init.cpp
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MODULE_UBLOX_ODIN_W2/wifi_emac/wifi_emac.cpp
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MODULE_UBLOX_ODIN_W2/wifi_emac/wifi_emac.h
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MTB_UBLOX_ODIN_W2/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MTB_UBLOX_ODIN_W2/stm32f4_eth_init.c
Labels: A, ready for merge, release-version: 5.9.0-rc1

#6708 Add Hardware CRC HAL API specification
  doxyfile_options
  doxygen_options.json
  drivers/MbedCRC.h
  hal/crc_api.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/mbed_crc_api.c
  targets/TARGET_STM/mbed_crc_api.c
  targets/targets.json
Labels: A, ready for merge, release-version: 5.9.0-rc1

#6910 LoRaWAN: Adding acquisition of metadata, backoff and a cancel_send() API
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.cpp
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorawan_types.h
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.9.0-rc1

#7019 Made lwip memory configuration more specific for NXP targets
  features/FEATURE_LWIP/lwip-interface/mbed_lib.json
Labels: release-version: 5.9.0-rc1

#6981 Remove ns_event_loop_thread_start() from NDInterface and ThreadInterface connect()
  features/nanostack/mbed-mesh-api/source/nd_tasklet.c
  features/nanostack/mbed-mesh-api/source/thread_tasklet.c
Labels: A, needs: CI, release-version: 5.9.0-rc1

#7023 Add new examples to example list for CI.
  tools/test/examples/examples.json
Labels: release-version: 5.9.0-rc1

#7030 Fix lwIP PPP glue
  features/FEATURE_LWIP/lwip-interface/LWIPInterface.cpp
  features/FEATURE_LWIP/lwip-interface/LWIPStack.h
  features/FEATURE_LWIP/lwip-interface/ppp_lwip.cpp
Labels: ready for merge, release-version: 5.9.0-rc1

#7021 Update watchdog timing test
  TESTS/mbed_hal/watchdog_timing/main.cpp
Labels: ready for merge

#6928 Cellular: Fixed con-disc sequence can now be called multiple times.
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
  features/cellular/easy_cellular/CellularConnectionFSM.h
  features/cellular/easy_cellular/EasyCellularConnection.cpp
  features/cellular/easy_cellular/EasyCellularConnection.h
  features/cellular/framework/API/CellularPower.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularPower.cpp
  features/cellular/framework/AT/AT_CellularPower.h
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#6970 Fixes to EFM32 port
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/PeripheralPins.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/TARGET_TB_SENSE_12/PinNames.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/flash_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#6984 EFM32 IRQ handling fix
  targets/TARGET_Silicon_Labs/TARGET_EFM32/gpio_irq_api.c
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#6991 EFM32: make mbed_rtx.h depend of families instead of targets
  targets/TARGET_Silicon_Labs/mbed_rtx.h
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#7014 Add check for _interface
  features/netsocket/EMACInterface.cpp
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#7020 Add STM32L433RC to IAR exporter definitions
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#7022 Fix array overflow in gpio configuration code for NRF5x
  targets/TARGET_NORDIC/TARGET_NRF5x/gpio_api.c
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#7034 Fix redeclaration of type name "bool_t" for Renesas
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/common/r_typedefs.h
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#7035 tests-mbed_hal-common_tickers: Fix increment test case implementation
  TESTS/mbed_hal/common_tickers/main.cpp
Labels: ready for merge, release-version: 5.9.0-rc2

#7016 Corrected asynchronous DNS functionality
  features/FEATURE_LWIP/lwip-interface/LWIPStack.cpp
  features/netsocket/NetworkStack.cpp
  features/netsocket/nsapi_dns.cpp
  features/netsocket/nsapi_types.h
Labels: ready for merge, release-version: 5.9.1

#7054 gethostbyname must reject empty name
  TESTS/netsocket/udp/main.cpp
  features/netsocket/NetworkStack.cpp
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#7005 Lora: Add greentea tests for LoRaRadio API
  TESTS/lorawan/loraradio/README.md
  TESTS/lorawan/loraradio/main.cpp
  TESTS/lorawan/loraradio/template_mbed_app.txt
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#7031 Nuvoton: Adhere to reworked RTC spec to release with Mbed OS 5.9
  targets/TARGET_NUVOTON/TARGET_M451/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_M480/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/device/StdDriver/nano100_rtc.h
  targets/TARGET_NUVOTON/TARGET_NANO100/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/device/StdDriver/nuc472_rtc.h
  targets/TARGET_NUVOTON/TARGET_NUC472/rtc_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.9.1

#7053 Fix RTOS-less build failed with cmsis/RTE_Components.h
  cmsis/RTE_Components.h
Labels: release-version: 5.9.1

#7039 FPGAIO: Add MISC IO initialization support
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/arm_mps2_io_drv.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/arm_mps2_io_drv.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/gpio_api.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/objects.h
Labels: needs: CI, release-version: 5.9.1

#7027 Fix possible bug with SysTimer
  rtos/TARGET_CORTEX/SysTimer.cpp
Labels: needs: review, release-version: 5.8.6, release-version: 5.9.1

#7059 OS version not update in mbed_stats
  TESTS/mbed_platform/stats_sys/main.cpp
  platform/mbed_stats.c
Labels: needs: CI, release-version: 5.9.0-rc2
