Repository ARMmbed/mbed-os, pull requests merged in 2018-12, with the labels that each got.

#8844 STM32 : Remove html release notes files
  targets/TARGET_STM/README.md
  targets/TARGET_STM/TARGET_STM32F1/device/Release_Notes_stm32cubef1.html
  targets/TARGET_STM/TARGET_STM32F1/device/Release_Notes_stm32f1xx_hal.html
  targets/TARGET_STM/TARGET_STM32F2/device/Release_Notes_stm32f2xx_hal.html
  targets/TARGET_STM/TARGET_STM32F3/device/Release_Notes_stm32f3xx_hal.html
  targets/TARGET_STM/TARGET_STM32F7/device/Release_Notes_stm32f7xx_hal.html
  targets/TARGET_STM/TARGET_STM32L0/device/Release_Notes_stm32l0xx_hal.html
  targets/TARGET_STM/TARGET_STM32L1/device/Release_Notes_stm32l1xx_hal.html
Labels: needs: CI, release-version: 5.11.1

#8828 Nuvoton: Support DAC HAL
  targets/TARGET_NUVOTON/TARGET_M2351/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_M2351/PeripheralPins.c
  targets/TARGET_NUVOTON/TARGET_M2351/PeripheralPins.h
  targets/TARGET_NUVOTON/TARGET_M2351/analogout_api.c
  targets/TARGET_NUVOTON/TARGET_M2351/objects.h
  targets/TARGET_NUVOTON/TARGET_M451/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_M451/PeripheralPins.c
  targets/TARGET_NUVOTON/TARGET_M451/PeripheralPins.h
  targets/TARGET_NUVOTON/TARGET_M451/analogout_api.c
  targets/TARGET_NUVOTON/TARGET_M451/objects.h
  targets/TARGET_NUVOTON/TARGET_M480/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_M480/PeripheralPins.c
  targets/TARGET_NUVOTON/TARGET_M480/PeripheralPins.h
  targets/TARGET_NUVOTON/TARGET_M480/analogout_api.c
  targets/TARGET_NUVOTON/TARGET_M480/objects.h
  targets/TARGET_NUVOTON/TARGET_NANO100/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_NANO100/PeripheralPins.c
  targets/TARGET_NUVOTON/TARGET_NANO100/PeripheralPins.h
  targets/TARGET_NUVOTON/TARGET_NANO100/analogout_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/objects.h
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1

#8841 Bugfix restrict send size; namespace fixes; ATCmdParser::read return value fix
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 5.11.1

#8843 Fix C++11 build with Arm Compiler 6
  components/802.15.4_RF/stm-s2lp-rf-driver/source/s2lpReg.h
  features/frameworks/nanostack-libservice/mbed-client-libservice/ns_types.h
Labels: ready for merge, release-version: 5.11.1

#8854 SMCC FOTA: bin name change
  tools/targets/REALTEK_RTL8195AM.py
Labels: ready for merge, release-version: 5.11.1

#8855 Fix compilation warnings (apart from nanostack)
  components/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.c
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
  features/cellular/framework/AT/ATHandler.cpp
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
  platform/mbed_board.c
Labels: ready for merge, release-version: 5.11.1

#8861 Bugfix-tests-network-wifi drop the assumption about more than one SSID
  TESTS/network/wifi/main.cpp
  TESTS/network/wifi/wifi_scan.cpp
  TESTS/network/wifi/wifi_scan_null.cpp
Labels: ready for merge, release-version: 5.11.1

#8883 LPC546XX: Fix build failure due to incorrect merge
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/TARGET_LPCXpresso/qspi_device.h
Labels: ready for merge, release-version: 5.11.1

#8884 BLE: Fix iteration on connections in CordioGattServer.
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
Labels: ready for merge, release-version: 5.11.1

#8888 Align comment block in sys stats struct
  platform/mbed_stats.h
Labels: ready for merge, release-version: 5.11.1

#8890 ESP8266 disconnect returns ERROR_NO_CONNECTION
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 5.11.1

#8911 Fix ESP8266 recv_udp timeout with flow control
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
Labels: ready for merge, release-version: 5.11.1

#8872 MCUXpresso: Ensure the RTC OSC is running at bootup on Kinetis platforms
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/TARGET_UBRIDGE/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/TARGET_USENSE/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/TARGET_MCU_K22F512/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/TARGET_RO359B/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_HEXIWEAR/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_MTS_GAMBIT/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_RAPIDIOT/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/lp_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/rtc_api.c
Labels: ready for merge, release-version: 5.11.1

#8882 Update mbed-coap to version 4.7.3
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/module.json
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.11.1

#8944 Travis fix: rabbitmq key update (travis msg broker)
  .travis.yml
Labels: ready for merge, release-version: 5.11.0-rc2

#8951 Remove NVSTORE enabled from NUCLEO_F410RB
  features/storage/nvstore/mbed_lib.json
Labels: ready for merge, release-version: 5.11.1

#8949 TARGET_WICED updated.
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
Labels: ready for merge, release-version: 5.11.1

#8946 STM32L4: before calling HAL_CRYP_DeInit initialize the Instance member
  features/mbedtls/targets/TARGET_STM/aes_alt.c
Labels: ready for merge, release-version: 5.11.0-rc2

#8932 Fix target handling in build.py
  tools/build.py
Labels: ready for merge, release-version: 5.11.0-rc2

#8922 MTB_ADV_WISE_1570: disable MPU code until target properly supported
  targets/targets.json
Labels: ready for merge, release-version: 5.11.0-rc2

#8920 MODULE_UBLOX_ODIN_W2: disable MPU code until target properly supported
  targets/targets.json
Labels: ready for merge, release-version: 5.11.0-rc2

#8926 mbedtls: Update Mbed TLS to 2.15.1
  features/mbedtls/VERSION.txt
  features/mbedtls/importer/Makefile
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto.c
Labels: ready for merge, release-version: 5.11.0-rc2

#8904 Ble extended advertising fixes
  features/FEATURE_BLE/ble/gap/AdvertisingDataParser.h
  features/FEATURE_BLE/ble/gap/AdvertisingParameters.h
  features/FEATURE_BLE/ble/gap/ConnectionParameters.h
  features/FEATURE_BLE/ble/gap/Events.h
  features/FEATURE_BLE/ble/gap/Gap.h
  features/FEATURE_BLE/ble/gap/ScanParameters.h
  features/FEATURE_BLE/ble/gap/Types.h
  features/FEATURE_BLE/ble/generic/GenericGap.h
  features/FEATURE_BLE/source/BLE.cpp
  features/FEATURE_BLE/source/gap/ConnectionParameters.cpp
  features/FEATURE_BLE/source/gap/Gap.cpp
  features/FEATURE_BLE/source/generic/GenericGap.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalGap.cpp
Labels: ready for merge, release-version: 5.11.0-rc2

#8952 Turn off MPU for PSOC 6
  targets/targets.json
Labels: ready for merge, release-version: 5.11.0-rc2

#8953 Update FEATURE_BLE README
  features/FEATURE_BLE/README.md
Labels: ready for merge, release-version: 5.11.0-rc2

#8925 Fix PSA storage typo
  components/TARGET_PSA/services/psa_prot_internal_storage/COMPONENT_PSA_SRV_IMPL/pits_impl.cpp
  components/TARGET_PSA/services/psa_prot_internal_storage/psa_prot_internal_storage.h
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto.c
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto_storage_its.c
Labels: ready for merge, release-version: 5.11.0-rc2

#8873 PSA-SPM documentation follow-up
  components/TARGET_PSA/spm/COMPONENT_SPE/handles_manager.h
  components/TARGET_PSA/spm/COMPONENT_SPE/spm_internal.h
  components/TARGET_PSA/spm/COMPONENT_SPE/spm_server.h
  components/TARGET_PSA/spm/doc/INTRO.md
  components/TARGET_PSA/spm/doc/README.md
  components/TARGET_PSA/spm/doc/png/PSA-standardized-Interfaces-diagram.png
  doxyfile_options
  doxygen_options.json
  hal/spm_api.h
Labels: ready for merge, release-version: 5.11.0-rc2

#8908 Fix PSA internal storage configuration
  components/TARGET_PSA/services/psa_prot_internal_storage/COMPONENT_PSA_SRV_IMPL/pits_impl.cpp
  components/TARGET_PSA/services/psa_prot_internal_storage/COMPONENT_PSA_SRV_IMPL/pits_impl.h
Labels: ready for merge, release-version: 5.11.0-rc2

#8900 Nuvoton: Refine UART init/deinit
  targets/TARGET_NUVOTON/TARGET_M2351/objects.h
  targets/TARGET_NUVOTON/TARGET_M2351/serial_api.c
  targets/TARGET_NUVOTON/TARGET_M451/objects.h
  targets/TARGET_NUVOTON/TARGET_M451/serial_api.c
  targets/TARGET_NUVOTON/TARGET_M480/objects.h
  targets/TARGET_NUVOTON/TARGET_M480/serial_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/objects.h
  targets/TARGET_NUVOTON/TARGET_NANO100/serial_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/objects.h
  targets/TARGET_NUVOTON/TARGET_NUC472/serial_api.c
Labels: ready for merge, release-version: 5.11.1

#8879 Ble extended advertising doc fixes
  features/FEATURE_BLE/ble/common/Duration.h
  features/FEATURE_BLE/ble/gap/ScanParameters.h
Labels: ready for merge, release-version: 5.11.1

#8860 Add the port for the ACONNO ACN52832 module on MTB's form factor
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_MTB_ACONNO_ACN52832/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_MTB_ACONNO_ACN52832/device.h
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1, scope: new-target

#8936 Reduce default MBEDTLS_MPI_MAX_SIZE
  features/mbedtls/importer/adjust-config.sh
Labels: ready for merge, release-version: 5.11.1

#8097 Add support for nrf52_dk bootloader
  tools/build_api.py
  tools/config/__init__.py
Labels: ready for merge, release-version: 5.11.1

#8965 Coverity fixes.
  features/nanostack/mbed-mesh-api/source/ethernet_tasklet.c
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: needs: CI, release-version: 5.11.1

#8853 Reports NSAPI_STATUS_CONNECTING when trying to reconnect
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
Labels: ready for merge, release-version: 5.11.1

#8956 Update Ticker wrapper to handle early interrupts
  hal/LowPowerTickerWrapper.cpp
Labels: ready for merge, release-version: 5.11.1

#8933 Fixing Doxygen descriptions
  features/device_key/source/DeviceKey.h
  features/storage/kvstore/KVStore.h
  features/storage/kvstore/conf/kv_config.h
  features/storage/kvstore/filesystemstore/FileSystemStore.h
  features/storage/kvstore/global_api/kvstore_global_api.h
  features/storage/kvstore/kv_map/KVMap.h
  features/storage/kvstore/securestore/SecureStore.h
  features/storage/kvstore/tdbstore/TDBStore.h
Labels: ready for merge, release-version: 5.11.1

#8910 Fix rare NRF52 serial TX lockup
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
Labels: ready for merge, release-version: 5.11.1

#8974 Release candidate for mbed-os-5.11.0-rc2
  .travis.yml
  components/TARGET_PSA/services/psa_prot_internal_storage/COMPONENT_PSA_SRV_IMPL/pits_impl.cpp
  components/TARGET_PSA/services/psa_prot_internal_storage/COMPONENT_PSA_SRV_IMPL/pits_impl.h
  components/TARGET_PSA/services/psa_prot_internal_storage/psa_prot_internal_storage.h
  components/TARGET_PSA/spm/COMPONENT_SPE/handles_manager.h
  components/TARGET_PSA/spm/COMPONENT_SPE/spm_internal.h
  components/TARGET_PSA/spm/COMPONENT_SPE/spm_server.h
  components/TARGET_PSA/spm/doc/INTRO.md
  components/TARGET_PSA/spm/doc/README.md
  components/TARGET_PSA/spm/doc/png/PSA-standardized-Interfaces-diagram.png
  doxyfile_options
  doxygen_options.json
  features/FEATURE_BLE/README.md
  features/FEATURE_BLE/ble/gap/AdvertisingDataParser.h
  features/FEATURE_BLE/ble/gap/AdvertisingParameters.h
  features/FEATURE_BLE/ble/gap/ConnectionParameters.h
  features/FEATURE_BLE/ble/gap/Events.h
  features/FEATURE_BLE/ble/gap/Gap.h
  features/FEATURE_BLE/ble/gap/ScanParameters.h
  features/FEATURE_BLE/ble/gap/Types.h
  features/FEATURE_BLE/ble/generic/GenericGap.h
  features/FEATURE_BLE/source/BLE.cpp
  features/FEATURE_BLE/source/gap/ConnectionParameters.cpp
  features/FEATURE_BLE/source/gap/Gap.cpp
  features/FEATURE_BLE/source/generic/GenericGap.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalGap.cpp
  features/mbedtls/VERSION.txt
  features/mbedtls/importer/Makefile
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto.c
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto_storage_its.c
  features/mbedtls/targets/TARGET_STM/aes_alt.c
  hal/spm_api.h
  targets/targets.json
  tools/build.py
Labels: needs: CI

#8891 Cellular: Remove sim interface
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/at_cellulardevicetest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularinformation/at_cellularinformationtest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularsim/at_cellularsimtest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularsim/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellulardevice/cellulardevicetest.cpp
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  UNITTESTS/stubs/AT_CellularInformation_stub.cpp
  UNITTESTS/stubs/AT_CellularSIM_stub.cpp
  UNITTESTS/stubs/CellularDevice_stub.cpp
  UNITTESTS/target_h/myCellularDevice.h
  features/cellular/TESTS/api/cellular_device/main.cpp
  features/cellular/TESTS/api/cellular_information/main.cpp
  features/cellular/TESTS/api/cellular_sim/main.cpp
  features/cellular/TESTS/socket/udp/template_mbed_app.json.txt
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/API/CellularInformation.h
  features/cellular/framework/API/CellularSIM.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/AT/AT_CellularInformation.cpp
  features/cellular/framework/AT/AT_CellularInformation.h
  features/cellular/framework/AT/AT_CellularSIM.cpp
  features/cellular/framework/AT/AT_CellularSIM.h
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.h
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularInformation.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularInformation.h
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularSIM.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularInformation.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularInformation.h
Labels: BREAKING-CHANGE, needs: CI, release-version: feature branch

#8935 Fix PSA crypto partition and tests
  TESTS/mbed-crypto/sanity/main.cpp
  TESTS/psa/crypto_init/COMPONENT_SPE/psa_setup.c
  TESTS/psa/crypto_init/main.cpp
  TESTS/psa/entropy_inject/COMPONENT_SPE/psa_setup.c
  TESTS/psa/entropy_inject/main.cpp
  TESTS/psa/prot_internal_storage/COMPONENT_SPE/psa_setup.c
  TESTS/psa/spm_client/COMPONENT_SPE/psa_setup.c
  TESTS/psa/spm_server/COMPONENT_SPE/psa_setup.c
  TESTS/psa/spm_smoke/COMPONENT_SPE/psa_setup.c
  components/TARGET_PSA/services/crypto/COMPONENT_PSA_SRV_IPC/psa_crypto_spm.c
  components/TARGET_PSA/services/crypto/COMPONENT_SPE/psa_crypto_partition.c
  components/TARGET_PSA/services/crypto/COMPONENT_SPE/psa_crypto_srv_partition.c
  components/TARGET_PSA/services/crypto/COMPONENT_SPE/psa_crypto_srv_partition.h
  components/TARGET_PSA/services/crypto/crypto_partition_psa.json
  components/TARGET_PSA/services/crypto/psa_crypto_srv_ifs.h
  components/TARGET_PSA/spm/COMPONENT_SPE/psa_setup.c
Labels: ready for merge, release-version: 5.11.0-rc3

#8745 Add new target future sequana PSA
  TESTS/mbed_hal/spm/main.cpp
  TESTS/mbed_hal/trng/main.cpp
  TESTS/mbedmicro-rtos-mbed/mail/main.cpp
  TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
  TESTS/mbedmicro-rtos-mbed/threads/main.cpp
  TESTS/mbedtls/selftest/main.cpp
  TESTS/psa/crypto_init/TARGET_FUTURE_SEQUANA_PSA/crypto_init.hex
  TESTS/psa/entropy_inject/TARGET_FUTURE_SEQUANA_PSA/entropy_inject.hex
  TESTS/psa/prot_internal_storage/TARGET_FUTURE_SEQUANA_PSA/prot_internal_storage.hex
  TESTS/psa/spm_client/TARGET_FUTURE_SEQUANA_PSA/spm_client.hex
  TESTS/psa/spm_server/TARGET_FUTURE_SEQUANA_PSA/spm_server.hex
  TESTS/psa/spm_smoke/TARGET_FUTURE_SEQUANA_PSA/spm_smoke.hex
  features/storage/kvstore/conf/mbed_lib.json
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
  features/storage/nvstore/mbed_lib.json
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M0/device/TOOLCHAIN_ARM_STD/cy8c6xx7_cm0plus.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M0/device/TOOLCHAIN_GCC_ARM/cy8c6xx7_cm0plus.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M0/device/TOOLCHAIN_IAR/cy8c6xx7_cm0plus.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M0/system_psoc63_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/device/TOOLCHAIN_ARM_STD/cy8c6xx7_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/device/TOOLCHAIN_GCC_ARM/cy8c6xx7_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/device/TOOLCHAIN_IAR/cy8c6xx7_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/system_psoc63_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_FUTURE_SEQUANA_M0_PSA/cyprotection.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_FUTURE_SEQUANA_M0_PSA/cyprotection.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_FUTURE_SEQUANA_M0_PSA/cyprotection_config.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_FUTURE_SEQUANA_M0_PSA/spm_hal_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_FUTURE_SEQUANA_M0_PSA/spm_init_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_FUTURE_SEQUANA_PSA/prebuilt/LICENSE-permissive-binary-license-1.0.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_FUTURE_SEQUANA_PSA/prebuilt/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_FUTURE_SEQUANA_PSA/prebuilt/psa_debug_1.0.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_FUTURE_SEQUANA_PSA/prebuilt/psa_release_1.0.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_FUTURE_SEQUANA_PSA/spm_init_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/flash_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/mbed_rtx.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6_utils.c
  targets/targets.json
  tools/build_api.py
  tools/targets/PSOC6.py
Labels: needs: CI, release-version: 5.11.0-rc3, scope: new-target

#8994 Turn off MPU on targets failing OOB
  targets/targets.json
Labels: needs: CI, release-version: 5.11.0-rc3

#8960 STM32: avoid STM32 family name check
  targets/TARGET_STM/TARGET_STM32F0/device/stm32f0xx_hal_rtc.h
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_rtc.h
  targets/TARGET_STM/TARGET_STM32F3/device/stm32f3xx_hal_rtc.h
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc.h
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_rtc.h
  targets/TARGET_STM/TARGET_STM32L0/device/stm32l0xx_hal_rtc.h
  targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_rtc.h
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_rtc.h
  targets/TARGET_STM/lp_ticker.c
  targets/TARGET_STM/mbed_overrides.c
  targets/TARGET_STM/rtc_api.c
  targets/TARGET_STM/sleep.c
Labels: ready for merge, release-version: 5.11.1

#8852 Cellular: update doxygen and add attach CellularDevice.
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/device/CellularDevice.cpp
Labels: ready for merge, release-version: 5.11.1

#9005 Mbed TLS: Fix ECC hardware double initialization
  features/mbedtls/src/ecp.c
Labels: ready for merge, release-version: 5.11.0-rc3

#8996 Fix uninitialized handler pointer in FastModels ethernet driver
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/drivers/lan91c111.c
Labels: ready for merge, release-version: 5.11.0-rc3

#9009 [PSOC6]: Fix for static resource manager.
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/psoc6_static_srm.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6_utils.c
Labels: needs: CI, release-version: 5.11.1

#9001 Missing socket greentea tests implementation
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tcp/tcpsocket_bind_address.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_invalid.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_null.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_port_fail.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_unopened.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_wrong_type.cpp
  TESTS/netsocket/tcp/tcpsocket_open_destruct.cpp
  TESTS/netsocket/tcp/tcpsocket_open_twice.cpp
  TESTS/netsocket/tcp/tcpsocket_setsockopt_keepalive_valid.cpp
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udp_tests.h
  TESTS/netsocket/udp/udpsocket_bind_address.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_invalid.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_null.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_port.cpp
  TESTS/netsocket/udp/udpsocket_bind_port.cpp
  TESTS/netsocket/udp/udpsocket_bind_port_fail.cpp
  TESTS/netsocket/udp/udpsocket_bind_unopened.cpp
  TESTS/netsocket/udp/udpsocket_bind_wrong_type.cpp
  TESTS/netsocket/udp/udpsocket_open_destruct.cpp
  TESTS/netsocket/udp/udpsocket_open_twice.cpp
Labels: needs: CI, release-version: 5.11.1

#9003 Revert "Merge pull request #8922 from juhoeskeli/wise_1570_mpu_disable"
  targets/targets.json
Labels: ready for merge, release-version: 5.11.0-rc3

#8986 Fix a few bugs in TDBStore and KV config
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/kvstore/kv_map/KVMap.cpp
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: ready for merge, release-version: 5.11.0-rc3

#8905 SPI and deep sleep fixes for FUTURE_SEQUANA target.
  targets/TARGET_Cypress/TARGET_PSOC6/i2c_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/objects.h
  targets/TARGET_Cypress/TARGET_PSOC6/pwmout_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/serial_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/spi_api.c
Labels: needs: CI, release-version: 5.11.0-rc3

#8993 Apply GitHub style to exporter matrix
  tools/export/__init__.py
Labels: needs: CI, release-version: 5.11.1

#9030 Reduce ROM impact of MPU code
  TESTS/mbed_hal/mpu/main.cpp
  hal/mpu/mbed_mpu_v8m.c
  hal/mpu_api.h
  platform/mbed_mpu_mgmt.c
  platform/mbed_mpu_mgmt.h
  rtos/TARGET_CORTEX/mbed_boot.c
Labels: needs: CI, release-version: 5.11.0-rc3

#9033 Fix Stream for IAR toolchain
  TESTS/mbed_platform/Stream/main.cpp
  platform/Stream.cpp
Labels: ready for merge, release-version: 5.11.1

#8875 Add dependency checks to components
  components/802.15.4_RF/atmel-rf-driver/atmel-rf-driver/NanostackRfPhyAtmel.h
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.cpp
  components/802.15.4_RF/mcr20a-rf-driver/mcr20a-rf-driver/NanostackRfPhyMcr20a.h
  components/802.15.4_RF/mcr20a-rf-driver/source/NanostackRfPhyMcr20a.cpp
  components/802.15.4_RF/stm-s2lp-rf-driver/source/NanostackRfPhys2lp.cpp
  components/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.c
  components/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.h
  components/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver/NanostackRfPhys2lp.h
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
Labels: ready for merge, release-version: 5.11.1

#8822 LoRaWAN: Mitigating reception issues at lower data rates & FCnt increment after retry exhaustion
  UNITTESTS/features/lorawan/loraphy/unittest.cmake
  UNITTESTS/stubs/LoRaPHY_stub.cpp
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/mbed_lib.json
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.11.1

#8987 Fix a few SecureStore issues (following preliminary security review)
  docs/design-documents/features/storage/KVStore/KVStore_design.md
  docs/design-documents/features/storage/SecureStore/SecureStore_design.md
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/securestore_whitebox/main.cpp
  features/storage/kvstore/KVStore.h
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/kvstore/global_api/kvstore_global_api.h
  features/storage/kvstore/securestore/SecureStore.cpp
  features/storage/kvstore/securestore/SecureStore.h
Labels: ready for merge, release-version: 5.11.0-rc3

#9043 Removed rabbitmq fix from travis.yml
  .travis.yml
Labels: ready for merge, release-version: 5.11.1

#8959 [ESP8266] Adds support for controlling HW reset of the modem from the…
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
  components/wifi/esp8266-driver/mbed_lib.json
Labels: ready for merge, release-version: 5.11.0-rc3

#9025 Mbed os 5.11.0 oob: fix fault exception issue
  features/cellular/framework/AT/AT_CellularStack.cpp
Labels: ready for merge, release-version: 5.11.0-rc3

#9020 Revert "Turn off MPU on targets failing OOB"
  targets/targets.json
Labels: needs: CI, release-version: 5.11.0-rc3

#9051 ESP8266 send returns WOULD_BLOCK error when busy
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: needs: CI, release-version: 5.11.0-rc3

#8728 Fix issues in Cryptocell 310 shax_alt discovered by On Target Testing
  features/cryptocell/FEATURE_CRYPTOCELL310/sha1_alt.c
  features/cryptocell/FEATURE_CRYPTOCELL310/sha1_alt.h
  features/cryptocell/FEATURE_CRYPTOCELL310/sha256_alt.c
  features/cryptocell/FEATURE_CRYPTOCELL310/sha256_alt.h
Labels: ready for merge, release-version: 5.11.1

#8995 Add core option for Cortex-M33 with DSP enabled
  tools/targets/__init__.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
Labels: ready for merge, release-version: 5.11.1

#9008 Add NUCLEO_L4R5ZI_P target
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1

#9035 STM32L4: correct RNG clock source
  targets/TARGET_STM/trng_api.c
Labels: ready for merge, release-version: 5.11.1

#9037 BLE: Update toolchain.h with mbed_toolchain.h
  features/FEATURE_BLE/source/BLE.cpp
Labels: ready for merge, release-version: 5.11.1

#9047 travis: add license
  .travis.yml
Labels: ready for merge, release-version: 5.11.1

#9055 travis: use https for fetching astyle package
  .travis.yml
Labels: ready for merge, release-version: 5.11.1

#8901 Cell refactor power api
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/at_cellulardevicetest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularpower/at_cellularpowertest.cpp
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  UNITTESTS/features/cellular/framework/device/cellulardevice/cellulardevicetest.cpp
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  UNITTESTS/stubs/AT_CellularNetwork_stub.cpp
  UNITTESTS/stubs/AT_CellularPower_stub.cpp
  UNITTESTS/stubs/CellularDevice_stub.cpp
  UNITTESTS/target_h/myCellularDevice.h
  features/cellular/TESTS/api/cellular_device/main.cpp
  features/cellular/TESTS/api/cellular_power/main.cpp
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/API/CellularPower.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/AT/AT_CellularPower.cpp
  features/cellular/framework/AT/AT_CellularPower.h
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.h
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.h
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularPower.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularPower.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularPower.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularPower.h
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.h
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910_CellularPower.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910_CellularPower.h
Labels: BREAKING-CHANGE, ready for merge, release-version: feature branch

#9050 Cellular: changed support features to CellularProperty array.
  UNITTESTS/features/cellular/framework/AT/at_cellularbase/at_cellularbasetest.cpp
  UNITTESTS/stubs/AT_CellularBase_stub.cpp
  UNITTESTS/stubs/AT_CellularBase_stub.h
  features/cellular/framework/AT/AT_CellularBase.cpp
  features/cellular/framework/AT/AT_CellularBase.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularInformation.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_Module.cpp
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/PPP/UBLOX_PPP.cpp
Labels: ready for merge, release-version: feature branch

#9036 Disable MPU on RT1050 due to memory map
  targets/targets.json
Labels: ready for merge, release-version: 5.11.0-rc4

#9063 mbed_fault_handler: fix build warning
  cmsis/TARGET_CORTEX_M/mbed_fault_handler.c
Labels: ready for merge, release-version: 5.11.1

#9060 Fix duplicate 'overrides' keys in targets.json config file
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1

#9049 Fix test-netsocket-tcp greentea test build fails.
  TESTS/netsocket/tcp/main.cpp
Labels: ready for merge, release-version: 5.11.1

#9034 Change enet_tasklet declarations to match code
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  features/nanostack/mbed-mesh-api/source/ethernet_tasklet.c
  features/nanostack/mbed-mesh-api/source/include/enet_tasklet.h
Labels: ready for merge, release-version: 5.11.1

#8831 [Seeed Arch MAX] Add Mbed OS 5 support
  targets/targets.json
Labels: needs: CI, release-version: 5.11.1, scope: new-target

#9073 W7500x target ADC 6 and 7 not implemented
  targets/TARGET_WIZNET/TARGET_W7500x/analogin_api.c
Labels: needs: CI, release-version: 5.11.1

#9072 Enable stats reporting with a flag in targets.json
  targets/targets.json
  tools/toolchains/__init__.py
Labels: ready for merge, release-version: 5.11.0-rc4

#9090 Cellular: Removed unnecessary checks after new
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/at_cellulardevicetest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/at_cellularsmstest.cpp
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  UNITTESTS/target_h/myCellularDevice.h
  features/cellular/TESTS/api/cellular_power/main.cpp
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/AT/AT_CellularSMS.cpp
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/common/CellularList.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.h
Labels: ready for merge, release-version: feature branch

#9087 kvstore tests: reduce reset
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_2/main.cpp
  features/storage/TESTS/kvstore/static_tests/main.cpp
Labels: ready for merge, release-version: 5.11.1

#9085 U-blox C030 PinNames Updated
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/PinNames.h
Labels: ready for merge, release-version: 5.11.1

#9057 Prefer QSPI Bus mode 1-4-4 as highest priority for QSPIFBlockDevice
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/TESTS/block_device/qspif/main.cpp
Labels: ready for merge, release-version: 5.11.1

#9054 Fix max_keys reset limitation
  features/storage/nvstore/TESTS/nvstore/functionality/main.cpp
  features/storage/nvstore/source/nvstore.cpp
  features/storage/nvstore/source/nvstore.h
Labels: ready for merge, release-version: 5.11.1

#9052 Cellular: Rewrite AT handler consume to tag
  features/cellular/framework/AT/ATHandler.cpp
Labels: ready for merge, release-version: 5.11.1

#8978 fixed wrong __StackTop calculation
  targets/TARGET_NXP/TARGET_LPC15XX/device/TOOLCHAIN_GCC_ARM/LPC1549.ld
Labels: ready for merge, release-version: 5.11.1

#8866 Cellular: Refactored GEMALTO_CINTERION_Module to GEMALTO_CINTERION
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.h
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularContext.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularNetwork.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_Module.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_Module.h
Labels: ready for merge, release-version: 5.11.1

#8819 Improve the unit testing documentation
  UNITTESTS/README.md
Labels: ready for merge, release-version: 5.11.1

#8802 Fix long writes/reads stack overflowing
  TESTS/nfc/eeprom/main.cpp
  features/nfc/nfc/NFCEEPROM.h
  features/nfc/source/nfc/NFCEEPROM.cpp
Labels: ready for merge, release-version: 5.11.1

#9101 Cellular: Fix to use PPP stack in PPP mode
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularContext.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularContext.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularContext.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularContext.h
Labels: ready for merge, release-version: 5.11.1

#9089 STM32 QSPI update
  TESTS/mbed_hal/qspi/flash_configs/MX25L51245G_config.h
  TESTS/mbed_hal/qspi/flash_configs/STM/DISCO_F413ZH/flash_config.h
  TESTS/mbed_hal/qspi/flash_configs/STM/DISCO_L475VG_IOT01A/flash_config.h
  TESTS/mbed_hal/qspi/flash_configs/flash_configs.h
  components/storage/blockdevice/COMPONENT_QSPIF/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_NUCLEO_F412ZG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_NUCLEO_F412ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_NUCLEO_F413ZH/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_NUCLEO_F413ZH/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446ZE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446ZE/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_DISCO_F469NI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/TARGET_NUCLEO_F756ZG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/TARGET_NUCLEO_F756ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/TARGET_DISCO_F769NI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/objects.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/TARGET_NUCLEO_L432KC/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/TARGET_NUCLEO_L433RC_P/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_DISCO_L476VG/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/TARGET_NUCLEO_L486RG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_NUCLEO_L496ZG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_NUCLEO_L496ZG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_NUCLEO_L496ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/objects.h
  targets/TARGET_STM/qspi_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1

#8961 ThisThread get_name()
  rtos/ThisThread.cpp
  rtos/ThisThread.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9109 Rework fseek/ftell tests
  TESTS/mbed_platform/FileHandle/main.cpp
Labels: ready for merge, release-version: 5.11.1

#9107 Fixing execution of OS2 tests
  tools/test_api.py
Labels: ready for merge, release-version: 5.11.1

#9105 Add some rounding to determine the pulse value for PWM for the STM target
  targets/TARGET_STM/pwmout_api.c
Labels: ready for merge, release-version: 5.11.1

#9100 Align prototype & implementation of enet_tasklet_disconnect & friends
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  features/nanostack/mbed-mesh-api/source/ethernet_tasklet.c
  features/nanostack/mbed-mesh-api/source/include/enet_tasklet.h
Labels: ready for merge, release-version: 5.11.1

#9097 Update to add support for Cortex-M33FD
  tools/toolchains/__init__.py
Labels: ready for merge, release-version: 5.11.1

#8990 Adjust FAT FS tests to low memory boards
  features/storage/TESTS/filesystem/fat_filesystem/main.cpp
  features/storage/TESTS/filesystem/multipart_fat_filesystem/main.cpp
Labels: ready for merge, release-version: 5.11.1

#8655 Disable write buffer in debug builds (M3/M4)
  cmsis/TARGET_CORTEX_M/core_cm3.h
  platform/mbed_application.c
Labels: ready for merge, release-version: 5.11.1

#8972 Merge feature-posix branch (FileHandle::truncate)
  TESTS/mbed_platform/FileHandle/TestFile.h
  TESTS/mbed_platform/FileHandle/main.cpp
  features/storage/filesystem/File.cpp
  features/storage/filesystem/File.h
  features/storage/filesystem/FileSystem.cpp
  features/storage/filesystem/FileSystem.h
  features/storage/filesystem/fat/FATFileSystem.cpp
  features/storage/filesystem/fat/FATFileSystem.h
  features/storage/filesystem/littlefs/LittleFileSystem.cpp
  features/storage/filesystem/littlefs/LittleFileSystem.h
  platform/FileHandle.h
  platform/mbed_retarget.cpp
  platform/mbed_retarget.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9131 Add versioning limits to `intervaltree` module
  requirements.txt
Labels: ready for merge, release-version: 5.11.1

#9120 Cellular: Add generic cellular modem
  features/cellular/framework/AT/AT_CellularBase.h
  features/cellular/framework/targets/GENERIC/GENERIC_AT3GPP/GENERIC_AT3GPP.cpp
  features/cellular/framework/targets/GENERIC/GENERIC_AT3GPP/GENERIC_AT3GPP.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
Labels: ready for merge, release-version: feature branch

#9053 Rapid-IoT: Add support for the KW41Z side of the platform
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_RAPIDIOT/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_RAPIDIOT/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_RAPIDIOT/PinNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_RAPIDIOT/device.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_RAPIDIOT/fsl_clock_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_RAPIDIOT/fsl_clock_config.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_RAPIDIOT/mbed_overrides.c
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1, scope: new-target

#9079 Add socket stat logging state change update
  features/netsocket/TCPSocket.cpp
Labels: ready for merge, release-version: 5.11.1

#9126 Fix multiple definitions of '__aeabi_atexit'
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U68/startup_LPC11U68.cpp
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U68/LPC11U68.ld
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U68/aeabi_romdiv_patch.S
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U68/mtb.c
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U68/startup_LPC11U68.cpp
Labels: ready for merge, release-version: 5.11.1

#9084 Realtek-rtl8195am-Network_Socket_Updates
  features/lwipstack/mbed_lib.json
  targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.cpp
  targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.h
Labels: ready for merge, release-version: 5.11.1

#9045 Fix wrong PIN config for RTL8195AM platform
  components/storage/blockdevice/COMPONENT_SD/config/mbed_lib.json
Labels: ready for merge, release-version: 5.11.1

#8975 Initialize the interface at the construction
  features/nanostack/mbed-mesh-api/source/LoWPANNDInterface.cpp
  features/nanostack/mbed-mesh-api/source/ThreadInterface.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-version: 5.11.1

#8971 Cellular: added setting of data carrier support for UART.
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/unittest.cmake
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  UNITTESTS/target_h/myCellularDevice.h
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/device/CellularContext.cpp
  features/cellular/framework/device/CellularDevice.cpp
Labels: ready for merge, release-version: feature branch

#8966 spi-overhaul: add limitation for spi async API
  docs/design-documents/hal/0000-spi-overhaul.md
Labels: ready for merge, release-version: feature branch

#9061 More MPU work
  hal/mpu/mbed_mpu_v7m.c
  hal/mpu/mbed_mpu_v8m.c
  platform/mbed_application.c
  platform/mbed_mpu_mgmt.h
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1

#9081 Nuvoton: Fix crypto AC management
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/aes/aes_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/des/des_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/ecp/ecp_internal_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha1_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha256_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha512_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/aes/aes_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/des/des_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/sha/sha1_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/sha/sha256_alt.c
  targets/TARGET_NUVOTON/TARGET_M480/crypto/crypto-misc.cpp
  targets/TARGET_NUVOTON/TARGET_M480/crypto/crypto-misc.h
  targets/TARGET_NUVOTON/TARGET_NUC472/crypto/crypto-misc.cpp
  targets/TARGET_NUVOTON/TARGET_NUC472/crypto/crypto-misc.h
Labels: ready for merge, release-version: 5.11.1

#9155 PSOC6: Fixing merge issue for pull request #9009
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6_utils.c
Labels: ready for merge, release-version: 5.11.1

#9157 PSOC6: Updated default M0 image to not modify UDB configuration when…
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/hex/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/hex/psoc63_m0_default_1.01.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/hex/psoc63_m0_default_1.02.hex
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1

#7799 Removing feature names from the "allowed feature" config list.
  TEST_APPS/device/socket_app/mbed_app.json
  tools/config/__init__.py
Labels: ready for merge, release-version: 5.12.0-rc1

#9151 github: add reviewers to the PR template
  .github/pull_request_template.md
Labels: ready for merge, release-version: 5.11.1

#8832 nRF52840_DK: "qspi_api.c" check read/write WORD alignment, set clock frequency divider
  targets/TARGET_NORDIC/TARGET_NRF5x/qspi_api.c
Labels: ready for merge, release-version: 5.11.1

#9150 Check correct ARMC6 predefine for FP codegen
  cmsis/TARGET_CORTEX_A/core_ca.h
  cmsis/TARGET_CORTEX_M/core_armv8mbl.h
  cmsis/TARGET_CORTEX_M/core_armv8mml.h
  cmsis/TARGET_CORTEX_M/core_cm0.h
  cmsis/TARGET_CORTEX_M/core_cm0plus.h
  cmsis/TARGET_CORTEX_M/core_cm1.h
  cmsis/TARGET_CORTEX_M/core_cm23.h
  cmsis/TARGET_CORTEX_M/core_cm3.h
  cmsis/TARGET_CORTEX_M/core_cm33.h
  cmsis/TARGET_CORTEX_M/core_cm4.h
  cmsis/TARGET_CORTEX_M/core_cm7.h
  cmsis/TARGET_CORTEX_M/core_sc000.h
  cmsis/TARGET_CORTEX_M/core_sc300.h
Labels: ready for merge, release-version: 5.11.1

#9148 Fix FLASHIAP_ROM_END macro for GCC_ARM & IAR toolchains
  TESTS/mbed_drivers/flashiap/main.cpp
  drivers/FlashIAP.h
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/nvstore/TESTS/nvstore/functionality/main.cpp
  features/storage/system_storage/SystemStorage.cpp
Labels: ready for merge, release-version: 5.11.1

#9143 Fix BLE long write execution failure
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF51/source/nRF5xGattServer.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xGattServer.cpp
Labels: ready for merge, release-version: 5.11.1

#9158 Fix LTO build failures due to duplicate local types
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.cpp
  components/802.15.4_RF/mcr20a-rf-driver/source/NanostackRfPhyMcr20a.cpp
  features/storage/kvstore/filesystemstore/FileSystemStore.cpp
  features/storage/kvstore/securestore/SecureStore.cpp
  features/storage/kvstore/tdbstore/TDBStore.cpp
  features/storage/nvstore/source/nvstore.cpp
Labels: ready for merge, release-version: 5.11.1

#9134 STM32: enable TICKLESS
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1

#8749 Cellular: AT handler API
  UNITTESTS/features/cellular/framework/AT/at_cellularbase/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/at_cellulardevicetest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  UNITTESTS/features/cellular/framework/AT/athandler/unittest.cmake
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/AT_CellularBase_stub.cpp
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  UNITTESTS/target_h/myCellularDevice.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/ATHandler_factory.cpp
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
Labels: ready for merge, release-version: 5.12.0-rc1

#8916 STM32F429/STM32F439 alignment
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/LICENSE
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/mbed-bootloader-nucleo_f439zi-block_device-sotp-v3_4_0.bin
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_DISCO_F429ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_ARM_STD/startup_stm32f429xx.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_ARM_STD/stm32f429xx.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_GCC_ARM/STM32F429xI.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_GCC_ARM/startup_stm32f429xx.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_IAR/startup_stm32f429xx.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_IAR/stm32f429xx_flash.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/device/TOOLCHAIN_ARM_STD/stm32f439xx.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/device/TOOLCHAIN_GCC_ARM/STM32F439ZI.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/device/TOOLCHAIN_GCC_ARM/startup_stm32f439xx.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/device/flash_data.h
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal.c
  targets/TARGET_STM/TARGET_STM32F4/hal_init_pre.c
  targets/targets.json
Labels: needs: CI, release-version: 5.11.1

#8885 Docs: Watchdog: Update code comments in tests
  TESTS/mbed_drivers/reset_reason/ResetReason_tests.h
  TESTS/mbed_drivers/watchdog/Watchdog_tests.h
  TESTS/mbed_drivers/watchdog/main.cpp
  TESTS/mbed_drivers/watchdog_reset/Watchdog_reset_tests.h
  TESTS/mbed_drivers/watchdog_reset/main.cpp
  TESTS/mbed_hal/reset_reason/main.cpp
  TESTS/mbed_hal/reset_reason/reset_reason_api_tests.h
  TESTS/mbed_hal/watchdog/main.cpp
  TESTS/mbed_hal/watchdog/watchdog_api_tests.h
  TESTS/mbed_hal/watchdog_reset/main.cpp
  TESTS/mbed_hal/watchdog_reset/watchdog_reset_tests.h
  TESTS/mbed_hal/watchdog_timing/main.cpp
  TESTS/mbed_hal/watchdog_timing/watchdog_timing_tests.h
Labels: ready for merge, release-version: feature branch

#9144 EventQueue: Old pointers of sibling were not cleared
  events/equeue/equeue.c
  events/equeue/tests/tests.c
Labels: ready for merge, release-version: 5.11.1

#9164 Disable printf in crash reporting for release builds
  platform/mbed_error.c
Labels: ready for merge, release-version: 5.11.1

#9174 MTB_ODIN_v2_fixes
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_MTB_UBLOX_ODIN_W2/PinNames.h
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1

#9168 Fix to unit test losing process output due to timing issue
  UNITTESTS/unit_test/utils.py
Labels: ready for merge, release-version: 5.11.1

#9180 Revert "STM32 RTC : skip rtc_write if possible"
  targets/TARGET_STM/rtc_api.c
Labels: ready for merge, release-version: 5.11.1

#8955 Bug fix for UART issue on LPC54608 - issue #7398
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/serial_api.c
Labels: ready for merge, release-version: 5.11.1

#9171 Nuvoton: Fix NUC472 hard fault in SMCC tests
  targets/TARGET_NUVOTON/TARGET_NUC472/device/StdDriver/nuc472_clk.c
Labels: ready for merge, release-version: 5.11.1

#8815 Add platform TT_M3HQ
  targets/TARGET_TT/TARGET_TT_M3HQ/PeripheralNames.h
  targets/TARGET_TT/TARGET_TT_M3HQ/PinNames.h
  targets/TARGET_TT/TARGET_TT_M3HQ/PortNames.h
  targets/TARGET_TT/TARGET_TT_M3HQ/analogin_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/analogout_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/device.h
  targets/TARGET_TT/TARGET_TT_M3HQ/device/TMPM3HQ.h
  targets/TARGET_TT/TARGET_TT_M3HQ/device/TOOLCHAIN_ARM_STD/startup_TMPM3HQ.S
  targets/TARGET_TT/TARGET_TT_M3HQ/device/TOOLCHAIN_ARM_STD/tmpm3hqfdfg.sct
  targets/TARGET_TT/TARGET_TT_M3HQ/device/TOOLCHAIN_GCC_ARM/startup_TMPM3HQ.S
  targets/TARGET_TT/TARGET_TT_M3HQ/device/TOOLCHAIN_GCC_ARM/tmpm3hqfdfg.ld
  targets/TARGET_TT/TARGET_TT_M3HQ/device/TOOLCHAIN_IAR/startup_TMPM3HQ.S
  targets/TARGET_TT/TARGET_TT_M3HQ/device/TOOLCHAIN_IAR/tmpm3hqfdfg.icf
  targets/TARGET_TT/TARGET_TT_M3HQ/device/cmsis.h
  targets/TARGET_TT/TARGET_TT_M3HQ/device/cmsis_nvic.h
  targets/TARGET_TT/TARGET_TT_M3HQ/device/system_TMPM3HQ.c
  targets/TARGET_TT/TARGET_TT_M3HQ/device/system_TMPM3HQ.h
  targets/TARGET_TT/TARGET_TT_M3HQ/gpio_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/gpio_include.h
  targets/TARGET_TT/TARGET_TT_M3HQ/gpio_irq_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/gpio_object.h
  targets/TARGET_TT/TARGET_TT_M3HQ/i2c_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/objects.h
  targets/TARGET_TT/TARGET_TT_M3HQ/pinmap.c
  targets/TARGET_TT/TARGET_TT_M3HQ/port_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/pwmout_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/serial_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/sleep.c
  targets/TARGET_TT/TARGET_TT_M3HQ/spi_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/us_ticker.c
  targets/TARGET_TT/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1, scope: new-target
