Repository ARMmbed/mbed-os, pull requests merged in 2018-02, with the labels that each got.

#6050 lwip: enable EMAC IPv6 support
  features/FEATURE_LWIP/lwip-interface/emac_lwip.c
Labels: ready for merge, release-version: 5.7.6

#6047 Fix NVIC Wrapper include for Renesas
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/inc/RZ_A1LU.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/inc/RZ_A1H.h
Labels: ready for merge, release-version: 5.7.6

#6042 DISCO_F303VC : STDIO pins correction and alignment with STM32 family
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/TARGET_DISCO_F303VC/PinNames.h
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/TARGET_DISCO_F303VC/system_clock.c
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/device/TOOLCHAIN_IAR/startup_stm32f303xc.S
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/device/TOOLCHAIN_IAR/stm32f303xc.icf
  targets/targets.json
Labels: ready for merge, release-version: 5.7.6

#6035 Fix serial pins and a typo for ODIN MTB
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_MTB_UBLOX_ODIN_W2/PinNames.h
Labels: ready for merge, release-version: 5.7.6

#6018 fix compiler warning
  features/filesystem/fat/FATFileSystem.cpp
Labels: ready for merge, release-version: 5.7.6

#5941 STM32L0/4 Enable use of LPUART in stop mode
  targets/TARGET_STM/serial_api.c
Labels: ready for merge, release-version: 5.7.6

#6058 Ble: fix size function in advertising_data_t and address_t.
  features/FEATURE_BLE/ble/pal/GapTypes.h
Labels: needs: CI, release-version: 5.7.6

#6051 add few files to gitignore list
  .gitignore
Labels: release-version: 5.7.6

#5847 Unify fault handling and add script to show faults
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_ARM/except.S
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.S
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/TOOLCHAIN_IAR/except.S
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.c
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.h
  targets/TARGET_ONSEMI/TARGET_NCS36510/exceptions.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTB_MTS_DRAGONFLY/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/device/system_clock.c
  targets/targets.json
  tools/debug_tools/crash_log_parser/README.md
  tools/debug_tools/crash_log_parser/crash_log_parser.py
Labels: needs: work

#6070 remove magic calibration value for HSI in ST's targets
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTB_MTS_DRAGONFLY/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xC/TARGET_DISCO_F401VC/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_ARCH_MAX/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_DISCO_F407VG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F410xB/TARGET_NUCLEO_F410RB/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_ELMO_F411RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_SAKURAIO_EVB_01/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_MTB_MXCHIP_EMW3166/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_NUCLEO_F412ZG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_NUCLEO_F413ZH/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_DISCO_F429ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_B96B_F446VE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446ZE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_DISCO_F469NI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/TARGET_NUCLEO_F756ZG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/TARGET_DISCO_F769NI/system_clock.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L053x8/TARGET_DISCO_L053C8/system_clock.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L053x8/TARGET_NUCLEO_L053R8/system_clock.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/TARGET_MTB_MURATA_ABZ/system_clock.c
Labels: needs: CI

#6059 Enabling LoRaWAN technology in Mbed-OS 5.8
  features/lorawan/LoRaRadio.h
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.cpp
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMacChannelPlan.cpp
  features/lorawan/lorastack/mac/LoRaMacChannelPlan.h
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.h
  features/lorawan/lorastack/mac/LoRaMacCrypto.cpp
  features/lorawan/lorastack/mac/LoRaMacCrypto.h
  features/lorawan/lorastack/mac/LoRaMacMcps.cpp
  features/lorawan/lorastack/mac/LoRaMacMcps.h
  features/lorawan/lorastack/mac/LoRaMacMib.cpp
  features/lorawan/lorastack/mac/LoRaMacMib.h
  features/lorawan/lorastack/mac/LoRaMacMlme.cpp
  features/lorawan/lorastack/mac/LoRaMacMlme.h
  features/lorawan/lorastack/mac/LoRaMacTest.h
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYAS923.cpp
  features/lorawan/lorastack/phy/LoRaPHYAS923.h
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.h
  features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN470.h
  features/lorawan/lorastack/phy/LoRaPHYCN779.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN779.h
  features/lorawan/lorastack/phy/LoRaPHYEU433.cpp
  features/lorawan/lorastack/phy/LoRaPHYEU433.h
  features/lorawan/lorastack/phy/LoRaPHYEU868.cpp
  features/lorawan/lorastack/phy/LoRaPHYEU868.h
  features/lorawan/lorastack/phy/LoRaPHYIN865.cpp
  features/lorawan/lorastack/phy/LoRaPHYIN865.h
  features/lorawan/lorastack/phy/LoRaPHYKR920.cpp
  features/lorawan/lorastack/phy/LoRaPHYKR920.h
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.h
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.h
  features/lorawan/lorastack/phy/lora_phy_ds.h
  features/lorawan/mbed_lib.json
  features/lorawan/system/LoRaWANTimer.cpp
  features/lorawan/system/LoRaWANTimer.h
  features/lorawan/system/lorawan_data_structures.h
Labels: needs: work

#6074 fatfs: Remove extra MBR block
  features/TESTS/filesystem/multipart_fat_filesystem/main.cpp
  features/filesystem/bd/MBRBlockDevice.cpp
  features/filesystem/fat/FATFileSystem.cpp
Labels: ready for merge

#6083 tools: build: fix handing of "--stats-depth"
  tools/build_api.py
Labels: ready for merge

#5973 Update Mbed TLS HW acceleration partner code to new hashing API
  TESTS/mbedtls/multi/main.cpp
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha1_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha1_alt.h
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha256_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha256_alt.h
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha512_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha512_alt.h
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/sha/sha1_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/sha/sha1_alt.h
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/sha/sha256_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/sha/sha256_alt.h
  features/mbedtls/targets/TARGET_STM/md5_alt.c
  features/mbedtls/targets/TARGET_STM/md5_alt.h
  features/mbedtls/targets/TARGET_STM/sha1_alt.c
  features/mbedtls/targets/TARGET_STM/sha1_alt.h
  features/mbedtls/targets/TARGET_STM/sha256_alt.c
  features/mbedtls/targets/TARGET_STM/sha256_alt.h
  features/mbedtls/targets/TARGET_Silicon_Labs/crypto_sha.c
  features/mbedtls/targets/TARGET_Silicon_Labs/sha1_alt.h
  features/mbedtls/targets/TARGET_Silicon_Labs/sha256_alt.h
  features/mbedtls/targets/hash_wrappers.c
Labels: component: tls, mirrored, needs: work, tracking

#6009 fix for issue "serial example callback not working"
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/serial_api.c
Labels: ready for merge

#5666 Add exporter for Analog Devices' CrossCore Embedded Studio
  tools/export/__init__.py
  tools/export/cces/README.md.tmpl
  tools/export/cces/__init__.py
  tools/export/cces/cces.json.tmpl
Labels: needs: review

#6095 mbr: Add note about limitations
  features/filesystem/bd/MBRBlockDevice.h
Labels: release-version: 5.7.6

#5892 add OSHChip as an mbed target
  targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_OSHCHIP/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF51822_UNIFIED/TARGET_OSHCHIP/device.h
  targets/targets.json
Labels: Scope: new-target, ready for merge

#6064 Chages that will enable TARGET_MTB_MXCHIP_EMW3166 and minor changes t…
  targets/TARGET_STM/TARGET_STM32F4/TARGET_Advantech_F412RE/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_Advantech_F412RE/PinNames.h
  targets/TARGET_WICED/.mbedignore
  targets/TARGET_WICED/WICED.md
  targets/TARGET_WICED/wiced_interface/WicedInterface.cpp
  targets/TARGET_WICED/wiced_interface/WicedInterface.h
  targets/TARGET_WICED/wiced_interface/wiced_emac.c
  targets/TARGET_WICED/wiced_interface/wiced_test_config.json
  targets/TARGET_WICED/wiced_port/platforms/TARGET_MTB_MXCHIP_EMW3166/w_platform.c
  targets/TARGET_WICED/wiced_port/platforms/TARGET_MTB_MXCHIP_EMW3166/w_platform.h
  targets/TARGET_WICED/wiced_port/platforms/TARGET_MTB_MXCHIP_EMW3166/w_platform_config.h
  targets/TARGET_WICED/wiced_port/platforms/TARGET_MTB_MXCHIP_EMW3166/w_wifi_nvram_image.h
  targets/targets.json
Labels: needs: review

#6000 Prevent detect_targets.py tool script from crashing on known targets
  tools/detect_targets.py
Labels: release-version: 5.7.6

#6068 Fix for issue #6054 - interrupts scheduled in the past.
  hal/mbed_ticker_api.c
Labels: needs: CI, release-version: 5.7.6

#6096 Generate/Link secure object file
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
Labels: ready for merge, release-version: 5.7.6

#6049 Nuvoton: Rework RTC
  targets/TARGET_NUVOTON/TARGET_M451/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_M480/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/rtc_api.c
Labels: ready for merge

#6099 gnuarmeclipse exporter uses mBed instead of proper casing
  tools/export/gnuarmeclipse/makefile.targets.tmpl
Labels: needs: CI

#6045 RTX changes pulled in from d20b8aa
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
  rtos/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.h
  rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.c
Labels: ready for merge

#6029 RTX5: Pre-processor defines used for assembly
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_ARM/TARGET_M23/irq_armv8mbl.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_ARM/TARGET_M23/irq_armv8mbl_ns.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_ARM/TARGET_M33/irq_armv8mml.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_ARM/TARGET_M33/irq_armv8mml_ns.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M23/irq_armv8mbl.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M23/irq_armv8mbl_ns.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M33/irq_armv8mml.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M33/irq_armv8mml_fp.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M33/irq_armv8mml_fp_ns.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M33/irq_armv8mml_ns.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_M23/irq_armv8mbl.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_M23/irq_armv8mbl_common.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_M23/irq_armv8mbl_ns.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_M33/irq_armv8mml.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_M33/irq_armv8mml_ns.S
  tools/importer/cmsis_importer.json
  tools/toolchains/gcc.py
Labels: ready for merge

#6087 Integrating Mbed LoRaWAN Stack in Mbed-OS 5.8
  LICENSE-BSD-3-Clause
  features/lorawan/LICENSE
  features/lorawan/LoRaRadio.h
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.cpp
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMacChannelPlan.cpp
  features/lorawan/lorastack/mac/LoRaMacChannelPlan.h
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.h
  features/lorawan/lorastack/mac/LoRaMacCrypto.cpp
  features/lorawan/lorastack/mac/LoRaMacCrypto.h
  features/lorawan/lorastack/mac/LoRaMacMcps.cpp
  features/lorawan/lorastack/mac/LoRaMacMcps.h
  features/lorawan/lorastack/mac/LoRaMacMib.cpp
  features/lorawan/lorastack/mac/LoRaMacMib.h
  features/lorawan/lorastack/mac/LoRaMacMlme.cpp
  features/lorawan/lorastack/mac/LoRaMacMlme.h
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYAS923.cpp
  features/lorawan/lorastack/phy/LoRaPHYAS923.h
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.h
  features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN470.h
  features/lorawan/lorastack/phy/LoRaPHYCN779.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN779.h
  features/lorawan/lorastack/phy/LoRaPHYEU433.cpp
  features/lorawan/lorastack/phy/LoRaPHYEU433.h
  features/lorawan/lorastack/phy/LoRaPHYEU868.cpp
  features/lorawan/lorastack/phy/LoRaPHYEU868.h
  features/lorawan/lorastack/phy/LoRaPHYIN865.cpp
  features/lorawan/lorastack/phy/LoRaPHYIN865.h
  features/lorawan/lorastack/phy/LoRaPHYKR920.cpp
  features/lorawan/lorastack/phy/LoRaPHYKR920.h
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.h
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.h
  features/lorawan/lorastack/phy/lora_phy_ds.h
  features/lorawan/mbed_lib.json
  features/lorawan/system/LoRaWANTimer.cpp
  features/lorawan/system/LoRaWANTimer.h
  features/lorawan/system/lorawan_data_structures.h
Labels: needs: review, release-version: 5.8.0-rc1

#6088 STM32F429ZI add SERIAL_ASYNCH
  targets/targets.json
Labels: ready for merge

#6113 remove unused variable / resolve compiler warning
  rtos/Semaphore.cpp
Labels: needs: CI

#6048 Nuvoton: Rework us_ticker and lp_ticker
  targets/TARGET_NUVOTON/TARGET_M451/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M451/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_M480/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M480/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_NANO100/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_NANO100/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_NUC472/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_NUC472/us_ticker.c
Labels: ready for merge

#5956 [feature-hal-itm] Instrumented Trace Macrocell HAL API for SWO debug output
  drivers/SerialWireOutput.h
  hal/itm_api.h
  hal/mbed_itm_api.c
  targets/TARGET_NORDIC/TARGET_NRF5/itm_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/itm_api.c
  targets/targets.json
Labels: needs: CI

#6110 equeue: Removed RTOS dependencies with RTOS not present
  .travis.yml
  events/equeue/equeue_platform.h
Labels: needs: CI, release-version: 5.7.6

#5978 Feature watchdog: Add definition of reset reason and watchdog doxy groups
  hal/reset_reason_api.h
  hal/watchdog_api.h
Labels: release-version: 5.7.6

#6118 equeue: Add note about using global event queues in irq
  events/mbed_shared_queues.h
Labels: release-version: 5.7.6

#6135 tests-events-timing - print debug info only in case of failure.
  TESTS/events/timing/main.cpp
Labels: ready for merge, release-version: 5.7.6

#6117 UBLOX C030: I2C avoid any RTOS waits
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/battery_charger_i2c.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/battery_charger_i2c.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/min_battery_voltage.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/min_battery_voltage.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/min_battery_voltage.h
Labels: ready for merge, release-version: 5.7.6

#6115 NRF5x: Fix `error_t` conflict with gcc std>=gnu++11
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF5/source/nRF5XPalGattClient.cpp
Labels: ready for merge, release-version: 5.7.6

#5915 Simplify and Improve error/warning parser for gcc_arm
  tools/toolchains/gcc.py
Labels: release-version: 5.7.6

#6106 QSPI feature: add STM32L4 support
  drivers/QSPI.cpp
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/objects.h
  targets/TARGET_STM/qspi_api.c
  targets/targets.json
Labels: ready for merge

#6121 Avoid blowing away .mbedignore files in exporters
  tools/export/e2studio/__init__.py
  tools/export/exporters.py
  tools/export/gnuarmeclipse/__init__.py
  tools/export/mcuxpresso/__init__.py
  tools/export/nb/__init__.py
Labels: ready for merge

#6123 Correct sector scraping in arm-pack-manager
  tools/arm_pack_manager/__init__.py
  tools/arm_pack_manager/aliases.json
  tools/arm_pack_manager/index.json
  tools/project.py
Labels: ready for merge

#6126 Modified 'apt-get update' to loop until successful
  .travis.yml
Labels: ready for merge

#5812 M487: Support ECP H/W accelerator
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/TARGET_NUMAKER_PFM_M487/mbedtls_device.h
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/ecp/ecp_internal_alt.c
  targets/TARGET_NUVOTON/TARGET_M480/crypto/crypto-misc.c
  targets/TARGET_NUVOTON/TARGET_M480/crypto/crypto-misc.h
  targets/TARGET_NUVOTON/TARGET_NUC472/crypto/crypto-misc.c
Labels: component: tls, mirrored, needs: CI, tracking

#6041 STM32 STDIO pin redefinition
  targets/targets.json
Labels: ready for merge

#6055 K64F lp ticker driver - calculation bug fix.
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/lp_ticker.c
Labels: ready for merge, release-version: 5.7.6

#6046 littlefs: Fix incorrect lookahead population before ack
  features/filesystem/littlefs/littlefs/lfs.c
  features/filesystem/littlefs/littlefs/lfs.h
  features/filesystem/littlefs/littlefs/tests/test_alloc.sh
Labels: ready for merge

#6076 Remove ticker interface initialization while Ticker creation.
  drivers/Ticker.h
Labels: ready for merge, release-version: 5.8.0-rc1

#6093 NETSOCKET MBED_EXTENDED_TESTS json configuration
  TESTS/netsocket/tcp_echo/main.cpp
  TESTS/netsocket/tcp_echo_parallel/main.cpp
  TESTS/netsocket/tcp_packet_pressure/main.cpp
  TESTS/netsocket/tcp_packet_pressure_parallel/main.cpp
  TESTS/netsocket/udp_echo_parallel/main.cpp
  TESTS/netsocket/udp_packet_pressure/main.cpp
  TESTS/netsocket/udp_packet_pressure_parallel/main.cpp
Labels: ready for merge

#6124 Make NRF52 flash work with SoftDevice
  targets/TARGET_NORDIC/TARGET_NRF5/flash_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.7.6

#6109 Feature QSPI: add address to command transfer
  drivers/QSPI.cpp
  drivers/QSPI.h
Labels: ready for merge

#6125 Add quotes around MBED_BOT parameter
  .travis.yml
Labels: ready for merge, release-version: 5.7.6

#6139 LWIP PBUF_POOL_BUFSIZE increased to fit also IPv6 header
  TESTS/network/wifi/wifi_connect_params_channel_fail.cpp
  features/FEATURE_LWIP/lwip-interface/lwipopts.h
Labels: ready for merge, release-version: 5.7.6

#6128 [feature-nrf528xx] Fix TRNG for NRF52
  targets/TARGET_NORDIC/TARGET_NRF5x/trng_api.c
  targets/targets.json
Labels: needs: review

#6078 Pull request template update
  .github/pull_request_template.md
Labels: ready for merge, release-version: 5.7.6

#6163 Revert "Update Mbed TLS HW acceleration partner code to new hashing API"
  TESTS/mbedtls/multi/main.cpp
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha1_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha1_alt.h
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha256_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha256_alt.h
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha512_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/sha/sha512_alt.h
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/sha/sha1_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/sha/sha1_alt.h
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/sha/sha256_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/sha/sha256_alt.h
  features/mbedtls/targets/TARGET_STM/md5_alt.c
  features/mbedtls/targets/TARGET_STM/md5_alt.h
  features/mbedtls/targets/TARGET_STM/sha1_alt.c
  features/mbedtls/targets/TARGET_STM/sha1_alt.h
  features/mbedtls/targets/TARGET_STM/sha256_alt.c
  features/mbedtls/targets/TARGET_STM/sha256_alt.h
  features/mbedtls/targets/TARGET_Silicon_Labs/crypto_sha.c
  features/mbedtls/targets/TARGET_Silicon_Labs/sha1_alt.h
  features/mbedtls/targets/TARGET_Silicon_Labs/sha256_alt.h
  features/mbedtls/targets/hash_wrappers.c
Labels: release-version: 5.8.0-rc1

#6154 tools: Let unicode error messages through
  tools/make.py
Labels: ready for merge, release-version: 5.7.6

#6145 Correct single file excludes for some exporters
  tools/toolchains/__init__.py
Labels: ready for merge, release-version: 5.7.6

#6156 retarget: Fix path behaviour without leading slash
  platform/FilePath.cpp
Labels: release-version: 5.7.6

#6147 LPC546XX: Add support for 220MHz core speed available on LPC54628
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/clock_config.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/clock_config.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/mbed_overrides.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_LPCXpresso/clock_config.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_LPCXpresso/clock_config.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_LPCXpresso/mbed_overrides.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/LPC54618_features.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/LPC54628.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/LPC54628_features.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/TOOLCHAIN_ARM_STD/LPC54628J512.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/TOOLCHAIN_ARM_STD/lib_power.ar
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/TOOLCHAIN_ARM_STD/startup_LPC54628.S
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/TOOLCHAIN_GCC_ARM/LPC54628J512.ld
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/TOOLCHAIN_GCC_ARM/libpower.a
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/TOOLCHAIN_GCC_ARM/startup_LPC54628.S
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/TOOLCHAIN_IAR/LPC54628J512.icf
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/TOOLCHAIN_IAR/lib_power.a
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/TOOLCHAIN_IAR/startup_LPC54628.S
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/fsl_device_registers.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/system_LPC54628.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/system_LPC54628.h
  targets/targets.json
  tools/export/iar/iar_definitions.json
  tools/export/mcuxpresso/LPC546XX_cproject.tmpl
Labels: ready for merge

#6162 sleep_manager_racecondition test fix for devices with low CPU clock
  TESTS/mbed_hal/sleep_manager_racecondition/main.cpp
Labels: release-version: 5.7.6

#6160 fix issue 6150
  features/FEATURE_LWIP/lwip-interface/lwip_stack.c
  features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.cpp
Labels: needs: CI

#6140 FlashIAP driver modifications
  TESTS/mbed_drivers/flashiap/main.cpp
  drivers/FlashIAP.cpp
  drivers/FlashIAP.h
Labels: ready for merge, release-version: 5.8.0-rc1

#6116 Add TRNG for NRF52832
  targets/TARGET_NORDIC/TARGET_NRF5/TARGET_MCU_NRF52832/sdk/nrf_drv_config.h
  targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/hal/nrf_rng.h
  targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/rng/nrf_drv_rng.c
  targets/TARGET_NORDIC/TARGET_NRF5/TARGET_SDK11/drivers_nrf/rng/nrf_drv_rng.h
  targets/TARGET_NORDIC/TARGET_NRF5/trng_api.c
  targets/targets.json
Labels: component: tls, mirrored, ready for merge, tracking

#6197 Revert "Added pretty bar printing for compile output"
  tools/build_api.py
  tools/make.py
  tools/memap.py
Labels: ready for merge, release-version: 5.7.7

#6182 platform: FileHandle test - remove optimization for stdlib diversity
  TESTS/mbed_platform/FileHandle/main.cpp
Labels: ready for merge, release-version: 5.7.7

#6177 littlefs: Fix handling of root as target for create operations
  features/filesystem/littlefs/littlefs/lfs.c
  features/filesystem/littlefs/littlefs/tests/test_paths.sh
Labels: ready for merge, release-version: 5.7.7

#6153 Correct exporter clean behavior
  tools/export/atmelstudio/__init__.py
  tools/export/cces/__init__.py
  tools/export/cdt/__init__.py
  tools/export/cmake/__init__.py
  tools/export/cmsis/__init__.py
  tools/export/coide/__init__.py
  tools/export/e2studio/__init__.py
  tools/export/embitz/__init__.py
  tools/export/exporters.py
  tools/export/gnuarmeclipse/__init__.py
  tools/export/iar/__init__.py
  tools/export/kds/__init__.py
  tools/export/makefile/__init__.py
  tools/export/mcuxpresso/__init__.py
  tools/export/nb/__init__.py
  tools/export/qtcreator/__init__.py
  tools/export/simplicity/__init__.py
  tools/export/sw4stm32/__init__.py
  tools/export/uvision/__init__.py
  tools/export/vscode/__init__.py
  tools/project.py
Labels: ready for merge, release-version: 5.7.7

#6151 BLE: Fix generic gap connect
  features/FEATURE_BLE/source/generic/GenericGap.cpp
Labels: Scope: bug-fix, component: ble, ready for merge, release-version: 5.7.7

#6120 fatfs: Update error code mapping
  features/filesystem/fat/FATFileSystem.cpp
Labels: ready for merge

#5957 C030 R410M Target Added
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/onboard_modem_api.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/ublox_low_level_api.c
  targets/targets.json
Labels: Scope: new-target, ready for merge

#5046 TimerEvent tests
  TESTS/mbed_drivers/timerevent/main.cpp
  drivers/TimerEvent.h
  targets/TARGET_ARM_SSG/TARGET_BEETLE/us_ticker.c
  targets/TARGET_Freescale/TARGET_KLXX/us_ticker.c
  targets/TARGET_Maxim/TARGET_MAX32600/us_ticker.c
  targets/TARGET_Maxim/TARGET_MAX32610/us_ticker.c
  targets/TARGET_Maxim/TARGET_MAX32620/us_ticker.c
  targets/TARGET_Maxim/TARGET_MAX32625/us_ticker.c
  targets/TARGET_Maxim/TARGET_MAX32630/us_ticker.c
  targets/TARGET_NORDIC/TARGET_MCU_NRF51822/us_ticker.c
  targets/TARGET_NORDIC/TARGET_NRF5/common_rtc.h
  targets/TARGET_NORDIC/TARGET_NRF5/lp_ticker.c
  targets/TARGET_NORDIC/TARGET_NRF5/us_ticker.c
Labels: ready for merge, release-version: 5.7.7

#6193 ODIN MTB LEDs Fix
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_MTB_UBLOX_ODIN_W2/PinNames.h
Labels: ready for merge

#6052 us/lp ticker - port K64F platform to new HAL api
  TESTS/mbed_drivers/rtc/main.cpp
  TESTS/mbed_hal/lp_ticker/lp_ticker_api_tests.h
  TESTS/mbed_hal/lp_ticker/main.cpp
  TESTS/mbed_hal/lp_us_tickers/main.cpp
  hal/lp_ticker_api.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/lp_ticker.c
  targets/targets.json
Labels: needs: review

#6186 Eventloop in main thread to master
  features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/mbed_lib.json
  features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.c
  features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.h
  features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_hal_init.c
Labels: ready for merge

#6185 nanostack-hal: add alternative critical section implementation
  features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_interrupt.c
  features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/mbed_lib.json
Labels: ready for merge

#5828 Feature: PSA Secure Partition Manager Null implementation
  TESTS/spm/client_tests/client_ipc_tests.cpp
  TESTS/spm/client_tests/part1_psa.json
  TESTS/spm/client_tests/server.c
  TESTS/spm/neg_tests/neg_ipc_tests.cpp
  TESTS/spm/neg_tests/neg_tests.h
  TESTS/spm/neg_tests/part1_psa.json
  TESTS/spm/neg_tests/part2_psa.json
  TESTS/spm/neg_tests/server1.c
  TESTS/spm/neg_tests/server2.c
  TESTS/spm/neg_tests/spm_reboot.c
  TESTS/spm/server/main.cpp
  TESTS/spm/server/part1_psa.json
  TESTS/spm/server/part2_psa.json
  TESTS/spm/server/partition.c
  TESTS/spm/server/partition2.c
  TESTS/spm/server/server_tests.h
  TESTS/spm/server/tests.c
  TESTS/spm/smoke/main.cpp
  TESTS/spm/smoke/part1_psa.json
  TESTS/spm/smoke/partition1.c
  requirements.txt
  rtos/TARGET_CORTEX/mbed_boot.c
  spm/handles_manager.c
  spm/handles_manager.h
  spm/mbed_lib.json
  spm/psa_defs.h
  spm/spm_client.c
  spm/spm_client.h
  spm/spm_common.c
  spm/spm_init.c
  spm/spm_internal.h
  spm/spm_panic.h
  spm/spm_server.c
  spm/spm_server.h
  tools/build_api.py
  tools/export/__init__.py
  tools/spm/__init__.py
  tools/spm/generate_partition_code.py
  tools/spm/partition_description_schema.json
  tools/spm/templates/psa_NAME_partition.c.tpl
  tools/spm/templates/psa_NAME_partition.h.tpl
  tools/spm/templates/psa_client_common.h.tpl
  tools/spm/templates/psa_common.c.tpl
  tools/test/spm/__init__.py
  tools/test/spm/test_data.py
  tools/test/spm/test_generate_partition_code.py
  tools/toolchains/__init__.py
Labels: ready for merge

#6166 Make APN lookup the default behaviour for PPPCellularInterface
  features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.cpp
  features/netsocket/cellular/generic_modem_driver/mbed_lib.json
Labels: ready for merge, release-version: 5.7.7

#6167 CM3DS Maintenance Pull Request: Bug fixes (1/4)
  features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_CM3DS_MPS2/lwipopts_conf.h
  features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_CM3DS_MPS2/mps2_emac.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/SDK/smsc9220_eth.c
Labels: ready for merge

#6172 Use SRAM2 32Kbytes on STM32L475 / L476 and L486 devices
  platform/mbed_retarget.cpp
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_GCC_ARM/STM32L475XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_GCC_ARM/STM32L476XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_GCC_ARM/STM32L486XX.ld
  targets/TARGET_STM/TARGET_STM32L4/l4_retarget.c
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
Labels: ready for merge

#6217 STM32 RTC : update free function
  targets/TARGET_STM/rtc_api.c
Labels: needs: CI, release-version: 5.7.7

#6218 Travis: Tear out python3 testing to get CI working again
  .travis.yml
  tools/test/config/invalid_key/test_data.json
  tools/test/config/invalid_key_lib/test_data.json
  tools/test/toolchains/api_test.py
  tools/toolchains/arm.py
Labels: release-version: 5.7.7

#6229 Fix a bug using ELF as output extension
  tools/toolchains/__init__.py
Labels: ready for merge

#6209 Platform: Improve mbed_sleep.h
  platform/mbed_sleep.h
Labels: ready for merge, release-version: 5.7.7

#6214 Build issue for M33 core
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M33/irq_armv8mml.S
Labels: ready for merge, release-version: 5.7.7

#6227 Nuvoton: Add I2C & Serial Pin Name
  targets/TARGET_NUVOTON/TARGET_M451/TARGET_NUMAKER_PFM_M453/PinNames.h
  targets/TARGET_NUVOTON/TARGET_M480/TARGET_NUMAKER_PFM_M487/PinNames.h
  targets/TARGET_NUVOTON/TARGET_NANO100/TARGET_NUMAKER_PFM_NANO130/PinNames.h
  targets/TARGET_NUVOTON/TARGET_NUC472/TARGET_NUMAKER_PFM_NUC472/PinNames.h
Labels: ready for merge, release-version: 5.7.7

#6225 Flash test: fix the time over a longer range
  TESTS/mbed_hal/flash/functional_tests/main.cpp
Labels: ready for merge, release-version: 5.7.7

#5911 CRC class implementation
  drivers/MbedCRC.cpp
  drivers/MbedCRC.h
  drivers/TableCRC.cpp
  drivers/TableCRC.h
  mbed.h
Labels: needs: review
