Repository ARMmbed/mbed-os, pull requests merged in 2018-10, with the labels that each got.

#7896 Fix pin names of MIMXRT1050 I2C pins
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PinNames.h
Labels: ready for merge, release-version: 5.10.2

#7914 Remove references to "mBed"
  tools/export/gnuarmeclipse/.project.tmpl
  tools/export/mcuxpresso/.project.tmpl
  tools/export/mcuxpresso/makefile.targets.tmpl
Labels: ready for merge, release-version: 5.10.2

#7957 nRF5x: pass ram linker start/length from config system
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_ARM_STD/nRF52832.sct
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_GCC_ARM/NRF52832.ld
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_IAR/nRF52832.icf
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_ARM_STD/nRF52840.sct
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_GCC_ARM/NRF52840.ld
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_IAR/nRF52840.icf
  tools/config/__init__.py
Labels: ready for merge, release-version: 5.10.2

#7975 Use high resolution time for Timer::read().
  drivers/Timer.cpp
Labels: ready for merge, release-version: 5.10.2

#7998 MIMXRT1050_EVK: Add RTC support
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/rtc_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.10.2

#8048 NRF52: serial_api: Use polling for putc
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/drivers_nrf/hal/nrf_uarte.h
Labels: ready for merge, release-version: 5.10.2

#8049 Nuvoton: Fix mbed_hal-sleep test failed
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_NUMAKER_PFM_M2351/TARGET_M23_NS/NuMaker-mbed-TZ-secure-example.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_NUMAKER_PFM_M2351/TARGET_M23_NS/cmse_lib.o
  targets/TARGET_NUVOTON/TARGET_M2351/device/stddriver_secure.c
  targets/TARGET_NUVOTON/TARGET_M2351/device/stddriver_secure.h
  targets/TARGET_NUVOTON/TARGET_M2351/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M2351/serial_api.c
  targets/TARGET_NUVOTON/TARGET_M2351/sleep.c
  targets/TARGET_NUVOTON/TARGET_M451/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M451/serial_api.c
  targets/TARGET_NUVOTON/TARGET_M451/sleep.c
  targets/TARGET_NUVOTON/TARGET_M480/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M480/serial_api.c
  targets/TARGET_NUVOTON/TARGET_M480/sleep.c
  targets/TARGET_NUVOTON/TARGET_NANO100/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_NANO100/serial_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/sleep.c
  targets/TARGET_NUVOTON/TARGET_NUC472/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_NUC472/serial_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/sleep.c
  targets/TARGET_NUVOTON/nu_timer.c
  targets/TARGET_NUVOTON/nu_timer.h
Labels: ready for merge, release-version: 5.10.2

#8134 STM32L1 ADC update for internal channels
  targets/TARGET_STM/TARGET_STM32L1/analogin_device.c
Labels: ready for merge, release-version: 5.10.2

#8006 SD - Add required header file and namespace element instead add all
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.h
Labels: ready for merge, release-version: 5.10.2

#7932 ublox c030: Add PC2 pin to ADC pin map
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/PeripheralPins.c
Labels: ready for merge, release-version: 5.10.1

#8085 STM32 RTC : start LSI clock (for targets without LSE)
  targets/TARGET_STM/TARGET_STM32F0/common_objects.h
  targets/TARGET_STM/TARGET_STM32F1/common_objects.h
  targets/TARGET_STM/TARGET_STM32F3/common_objects.h
  targets/TARGET_STM/TARGET_STM32L4/common_objects.h
  targets/TARGET_STM/mbed_overrides.c
  targets/TARGET_STM/rtc_api.c
Labels: ready for merge, release-version: 5.10.2

#7978 Cellular: state machine and easycellular now return error fast if sim…
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
  features/cellular/easy_cellular/EasyCellularConnection.cpp
  features/cellular/easy_cellular/EasyCellularConnection.h
Labels: ready for merge, release-version: 5.10.1

#7876 Tools: Modified version mismatch msg to be warning instead of error
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
Labels: ready for merge, release-version: 5.10.1

#8090 Cleanup SPI constructor and destructor
  drivers/SPI.cpp
  drivers/SPI.h
Labels: ready for merge, release-version: 5.10.1

#8309 use forced_reset_timeout as delay after reset
  TESTS/host_tests/system_reset.py
  TESTS/mbed_platform/system_reset/main.cpp
Labels: ready for merge, release-version: 5.10.1

#7585 NUCLEO_L4R5ZI: add new platform
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/TOOLCHAIN_ARM_MICRO/startup_stm32l4r5xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/TOOLCHAIN_ARM_MICRO/stm32l4r5xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/TOOLCHAIN_ARM_STD/startup_stm32l4r5xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/TOOLCHAIN_ARM_STD/stm32l4r5xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/TOOLCHAIN_GCC_ARM/startup_stm32l4r5xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/TOOLCHAIN_GCC_ARM/stm32l4r5xx.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/TOOLCHAIN_IAR/startup_stm32l4r5xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/TOOLCHAIN_IAR/stm32l4r5xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/cmsis.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/objects.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/stm32l4r5xx.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/stm32l4xx.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/system_stm32l4xx.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/us_ticker_data.h
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
  tools/export/sw4stm32/__init__.py
Labels: ready for merge, release-version: 5.10.1, scope: new-target

#7917 Add overhead count in heap stats
  TESTS/mbed_platform/stats_heap/main.cpp
  platform/mbed_alloc_wrappers.cpp
  platform/mbed_stats.h
Labels: ready for merge, release-version: 5.10.1

#8318 BLE: fix use of invalid cccd index
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioGattServer.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
Labels: ready for merge, release-version: 5.10.1

#8121 Add thread safety info to FatFs/LittleFs
  features/storage/filesystem/fat/FATFileSystem.h
  features/storage/filesystem/littlefs/LittleFileSystem.h
Labels: ready for merge, release-version: 5.10.1

#8257 tests-mbed_hal-sleep: finish UART transmission before sleep test
  TESTS/mbed_hal/sleep/main.cpp
Labels: ready for merge, release-version: 5.10.1

#8119 STM32L496 : wrong ADC init
  targets/TARGET_STM/TARGET_STM32L4/analogin_device.c
Labels: ready for merge, release-version: 5.10.1

#7916 Add LPC1769 template file for MCUXpresso IDE
  tools/export/mcuxpresso/__init__.py
  tools/export/mcuxpresso/lpc1769_cproject.tmpl
Labels: ready for merge, release-version: 5.10.1

#8269 BLE: replace malloc with cordio buffer allocation
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioBLE.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/SimpleEventQueue.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/nRF5xn.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xn.h
Labels: ready for merge, release-version: 5.10.1

#8142 Disable MBEDTLS_CONFIG_HW_SUPPORT on STM targets.
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/mbedtls_device.h
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/mbedtls_device.h
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F756ZG/mbedtls_device.h
Labels: ready for merge, release-version: 5.10.1

#8108 Rename device option STCLK_OFF_DURING_SLEEP
  platform/mbed_power_mgmt.h
  targets/targets.json
  tools/targets/lint.py
Labels: ready for merge, release-version: 5.10.1

#7996 Add nanostack mac tester and testcases
  TEST_APPS/device/nanostack_mac_tester/README.md
  TEST_APPS/device/nanostack_mac_tester/main.cpp
  TEST_APPS/device/nanostack_mac_tester/mbed_app.json
  TEST_APPS/device/nanostack_mac_tester/source/mac_commands.cpp
  TEST_APPS/device/nanostack_mac_tester/source/mac_commands.h
  TEST_APPS/device/nanostack_mac_tester/source/util.cpp
  TEST_APPS/device/nanostack_mac_tester/source/util.h
  TEST_APPS/testcases/nanostack_mac_tester/ED_scan.py
  TEST_APPS/testcases/nanostack_mac_tester/__init__.py
  TEST_APPS/testcases/nanostack_mac_tester/address_read_and_write.py
  TEST_APPS/testcases/nanostack_mac_tester/create_and_join_PAN.py
  TEST_APPS/testcases/nanostack_mac_tester/send_data.py
  TEST_APPS/testcases/nanostack_mac_tester/send_data_indirect.py
  TEST_APPS/testcases/nanostack_mac_tester/send_large_payloads.py
  TEST_APPS/testcases/nanostack_mac_tester/template
  tools/test_configs/NanostackMACTester.json
  tools/test_configs/config_paths.json
  tools/test_configs/target_configs.json
Labels: ready for merge, release-version: 5.10.1

#7304 Add MTS dragonfly, MTS dragonfly l471
  features/cellular/TESTS/api/cellular_network/main.cpp
  features/cellular/TESTS/api/cellular_power/main.cpp
  features/cellular/framework/common/CellularTargets.h
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP.cpp
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP.h
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP_CellularNetwork.cpp
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP_CellularNetwork.h
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP_CellularPower.cpp
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP_CellularPower.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/TOOLCHAIN_ARM_MICRO/startup_stm32l471xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/TOOLCHAIN_ARM_MICRO/stm32l471xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/TOOLCHAIN_ARM_STD/startup_stm32l471xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/TOOLCHAIN_ARM_STD/stm32l471xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/TOOLCHAIN_GCC_ARM/STM32L471XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/TOOLCHAIN_GCC_ARM/startup_stm32l471xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/TOOLCHAIN_IAR/startup_stm32l471xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/TOOLCHAIN_IAR/stm32l471xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/cmsis.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/stm32l471xx.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/stm32l4xx.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/system_stm32l4xx.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/mtqn_low_power.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/mtqn_low_power.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/objects.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/onboard_modem_api.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/ublox_low_level_api.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/ublox_low_level_api.h
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, release-version: 5.10.1

#8252 Adjust heap size on stm32f207
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/TOOLCHAIN_IAR/stm32f207xx.icf
Labels: needs: CI, release-version: 5.10.1

#7861 Removing default flow control for MTB_LAIRD_BL652
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/mbed_lib.json
Labels: ready for merge, release-version: 5.10.2

#8057 Removed cellular PIN code print from debug log.
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
Labels: ready for merge, release-version: 5.10.2

#8061 NRF52: Ensure that we configure hardware after flow control changes
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
Labels: ready for merge, release-version: 5.10.2

#8072 Renesas : Improve Flash iap driver
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/flash_api.c
Labels: ready for merge, release-version: 5.10.2

#8149 Add usticker feature to TMPM066
  targets/TARGET_TOSHIBA/TARGET_TMPM066/us_ticker.c
  targets/targets.json
Labels: ready for merge, release-version: 5.10.2

#8167 Change update file format to binary for all targets
  tools/build_api.py
  tools/device_management.py
  tools/utils.py
Labels: ready for merge, release-version: 5.10.2

#8168 DISCO_L496AG : enable ADC
  targets/TARGET_STM/TARGET_STM32L4/analogin_device.c
Labels: ready for merge, release-version: 5.10.2

#8175 Fix the CMSIS macro ARM_MPU_RASR
  cmsis/TARGET_CORTEX_M/mpu_armv7.h
Labels: ready for merge, release-version: 5.10.2

#8179 Add missing SIM PIN configuration item
  features/netsocket/mbed_lib.json
Labels: ready for merge, release-version: 5.10.2

#8193 M2351: Add license file for default secure library/executable
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_NUMAKER_PFM_M2351/TARGET_M23_NS/LICENSE
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_NUMAKER_PFM_M2351/TARGET_M23_NS/README.md
Labels: ready for merge, release-version: 5.10.2

#8235 Mbedgt netsocket tc fixes
  TESTS/netsocket/README.md
  TESTS/netsocket/tcp/tcpsocket_connect_invalid.cpp
  TESTS/netsocket/udp/udpsocket_sendto_invalid.cpp
  TESTS/network/wifi/wifi_scan.cpp
Labels: ready for merge, release-version: 5.10.2

#8239 Fix for pwmout & serial fuart in TMPM46B
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/pwmout_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/serial_api.c
Labels: ready for merge, release-version: 5.10.2

#8241 Fix WIFI_CONNECT_PARAMS_CHANNEL_FAIL testcase.
  TESTS/network/wifi/wifi_connect_params_channel_fail.cpp
Labels: ready for merge, release-version: 5.10.2

#8268 Cellular: Fix greentea network set credentials test case
  features/cellular/TESTS/api/cellular_network/main.cpp
Labels: ready for merge, release-version: 5.10.2

#8330 Tools: Fix Python3 + firmware header traeback
  tools/build_api.py
Labels: ready for merge, release-version: 5.10.2

#8323 Add blockdevice example back to CI
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.10.2

#8286 STM32 RTC : write RTC time while LPTICKER is enabled
  targets/TARGET_STM/rtc_api.c
Labels: ready for merge, release-version: 5.10.2

#8263 STM32L4: clear error programming flags before erase & program operations
  targets/TARGET_STM/TARGET_STM32L4/flash_api.c
Labels: ready for merge, release-version: 5.10.2

#8243 mcr20a use core_util_critical_section functions
  components/802.15.4_RF/mcr20a-rf-driver/source/MCR20Drv.c
  components/802.15.4_RF/mcr20a-rf-driver/source/NanostackRfPhyMcr20a.cpp
Labels: ready for merge, release-version: 5.10.2

#8225 Adjust stack & heap for IAR on STM32F412xG
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/device/TOOLCHAIN_IAR/stm32f412xx.icf
Labels: ready for merge, release-version: 5.10.2

#8210 platform timer: Call timer start in enable
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp
Labels: ready for merge, release-version: 5.10.2

#7958 nrf_ble: Expose configuration of max characteristics and descriptors
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xGattServer.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/mbed_lib.json
Labels: ready for merge, release-version: 5.10.2

#8327 Guard Atmel RF driver build by DEVICE_I2C
  components/802.15.4_RF/atmel-rf-driver/atmel-rf-driver/NanostackRfPhyAtmel.h
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.cpp
  components/802.15.4_RF/atmel-rf-driver/source/at24mac.cpp
  components/802.15.4_RF/atmel-rf-driver/source/at24mac.h
Labels: ready for merge, release-version: 5.10.2

#7582 Update sleep manager tests
  TESTS/mbed_hal/sleep/main.cpp
  TESTS/mbed_hal/sleep/sleep_test_utils.h
  TESTS/mbed_hal/sleep_manager/main.cpp
  TESTS/mbed_hal/sleep_manager/sleep_manager_api_tests.h
  TESTS/mbed_hal/sleep_manager_racecondition/main.cpp
  TESTS/mbed_hal/sleep_manager_racecondition/sleep_manager_api_racecondition_tests.h
  hal/mbed_sleep_manager.c
  platform/mbed_power_mgmt.h
Labels: ready for merge, release-version: 5.10.2

#7877 Improve the config ajustment script of TLS for ENTROPY_NV_SEED
  features/mbedtls/importer/adjust-config.sh
Labels: component: tls, ready for merge, release-version: 5.10.2

#7898 Travis: fix astyle report (-/+ files)
  .travis.yml
Labels: ready for merge, release-version: 5.10.2

#8114 Registration parameters as struct
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  UNITTESTS/features/cellular/framework/common/util/utiltest.cpp
  UNITTESTS/stubs/AT_CellularNetwork_stub.cpp
  features/cellular/TESTS/api/cellular_network/main.cpp
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/common/CellularUtil.cpp
  features/cellular/framework/common/CellularUtil.h
Labels: ready for merge, release-version: 5.11.0-rc1

#8177 tools/utils: Fix issue with loading json files as ascii on python3 linux
  tools/utils.py
Labels: ready for merge

#8186 Freescale/NXP: Fix alignment of execute region to 8byte boundary
  targets/TARGET_Freescale/TARGET_K20XX/TARGET_K20D50M/device/TOOLCHAIN_GCC_ARM/MK20D5.ld
  targets/TARGET_Freescale/TARGET_K20XX/TARGET_TEENSY3_1/device/TOOLCHAIN_GCC_ARM/MK20DX256.ld
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL05Z/device/TOOLCHAIN_GCC_ARM/MKL05Z4.ld
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_GCC_ARM/MKL25Z4.ld
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_GCC_CW_EWL/MKL25Z4.ld
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_GCC_CW_NEWLIB/MKL25Z4.ld
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL26Z/device/TOOLCHAIN_GCC_ARM/MKL26Z4.ld
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL46Z/device/TOOLCHAIN_GCC_ARM/MKL46Z4.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/TOOLCHAIN_GCC_ARM/MK66FN2M0xxx18.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/device/TOOLCHAIN_GCC_ARM/MK82FN256xxx15.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/device/TOOLCHAIN_GCC_ARM/MKL27Z64xxx4.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/device/TOOLCHAIN_GCC_ARM/MKL43Z256xxx4.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/device/TOOLCHAIN_GCC_ARM/MKL82Z128xxx7.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/device/TOOLCHAIN_GCC_ARM/MKW24D512xxx5.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/TOOLCHAIN_GCC_ARM/MKW41Z512xxx4.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/TARGET_MCU_K22F512/device/TOOLCHAIN_GCC_ARM/MK22FN512xxx12.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/device/TOOLCHAIN_GCC_ARM/MK24FN1M0xxx12.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_GCC_ARM/MK64FN1M0xxx12.ld
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U68/LPC11U68.ld
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U68/LPC11U68.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U24_301/LPC11U24.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U24_401/LPC11U24.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U34_421/LPC11U34.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U35_401/LPC11U35.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U35_501/LPC11U35.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U35_Y5_MBUG/LPC11U35.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U37H_401/LPC11U37.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U37_501/LPC11U37.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPCCAPPUCCINO/LPC11U37.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_ARM/TARGET_OC_MBUINO/LPC11U24.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U24/LPC11U24.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U35_401/LPC11U35.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U35_501/LPC11U35.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U37H_401/LPC11U37.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U37_501/LPC11U37.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CS/LPC11U24.ld
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11CXX/LPC11C24.ld
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11XX/LPC1114.ld
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11XX/LPC1114.ld
  targets/TARGET_NXP/TARGET_LPC13XX/device/TOOLCHAIN_GCC_ARM/LPC1347.ld
  targets/TARGET_NXP/TARGET_LPC15XX/device/TOOLCHAIN_GCC_ARM/LPC1549.ld
  targets/TARGET_NXP/TARGET_LPC15XX/device/TOOLCHAIN_GCC_CR/LPC1549.ld
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_ARM/LPC1768.ld
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_ARM/TARGET_XBED_LPC1768/XBED_LPC1768.ld
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_CR/LPC1768.ld
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_CS/LPC1768.ld
  targets/TARGET_NXP/TARGET_LPC408X/device/TOOLCHAIN_GCC_ARM/LPC4088.ld
  targets/TARGET_NXP/TARGET_LPC408X/device/TOOLCHAIN_GCC_CR/LPC407x_8x.ld
  targets/TARGET_NXP/TARGET_LPC43XX/device/TOOLCHAIN_GCC_ARM/LPC4330.ld
  targets/TARGET_NXP/TARGET_LPC43XX/device/TOOLCHAIN_GCC_CR/LPC43xx.ld
  targets/TARGET_NXP/TARGET_LPC81X/TARGET_ELEKTOR_COCORICO/device/TOOLCHAIN_GCC_ARM/LPC812.ld
  targets/TARGET_NXP/TARGET_LPC81X/TARGET_LPC810/device/TOOLCHAIN_GCC_ARM/LPC810.ld
  targets/TARGET_NXP/TARGET_LPC81X/TARGET_LPC812/device/TOOLCHAIN_GCC_ARM/LPC812.ld
  targets/TARGET_NXP/TARGET_LPC82X/TARGET_LPC824/device/TOOLCHAIN_GCC_ARM/LPC824.ld
  targets/TARGET_NXP/TARGET_LPC82X/TARGET_LPC824/device/TOOLCHAIN_GCC_CR/LPC824.ld
  targets/TARGET_NXP/TARGET_LPC82X/TARGET_SSCI824/device/TOOLCHAIN_GCC_ARM/LPC824.ld
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/TOOLCHAIN_GCC_ARM/LPC54114J256_cm4_flash.ld
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/TOOLCHAIN_GCC_ARM/LPC54628J512.ld
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_GCC_ARM/MIMXRT1052xxxxx.ld
Labels: ready for merge, release-version: 5.10.2

#8245 Nanostack libservice update
  features/frameworks/nanostack-libservice/mbed-client-libservice/ip6string.h
  features/frameworks/nanostack-libservice/source/libip6string/stoip6.c
  features/frameworks/nanostack-libservice/test/libService/unittest/stoip6/main.cpp
  features/frameworks/nanostack-libservice/test/libService/unittest/stoip6/stoip6test.cpp
  features/frameworks/nanostack-libservice/test/libService/unittest/stubs/ipv6_test_values.h
Labels: ready for merge, release-version: 5.11.0-rc1

#8298 Reset channel settings back to default
  TESTS/network/wifi/wifi_set_channel.cpp
Labels: ready for merge, release-version: 5.10.2

#8305 Tools: Fix Microbit releases
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.10.2

#7937 Export, MCUXpresso: Avoid assigning self.libraries
  tools/export/mcuxpresso/__init__.py
Labels: ready for merge, release-version: 5.10.2

#8316 unittests: Add tests for netsocket classes
  UNITTESTS/features/netsocket/EthernetInterface/test_EthernetInterface.cpp
  UNITTESTS/features/netsocket/EthernetInterface/unittest.cmake
  UNITTESTS/features/netsocket/InternetSocket/test_InternetSocket.cpp
  UNITTESTS/features/netsocket/NetworkStack/test_NetworkStack.cpp
  UNITTESTS/features/netsocket/SocketAddress/test_SocketAddress.cpp
  UNITTESTS/features/netsocket/SocketAddress/unittest.cmake
  UNITTESTS/features/netsocket/TCPServer/test_TCPServer.cpp
  UNITTESTS/features/netsocket/TCPSocket/test_TCPSocket.cpp
  UNITTESTS/features/netsocket/UDPSocket/test_UDPSocket.cpp
  UNITTESTS/features/netsocket/WiFiAccessPoint/test_WiFiAccessPoint.cpp
  UNITTESTS/features/netsocket/WiFiAccessPoint/unittest.cmake
  UNITTESTS/target_h/rtos.h
  features/netsocket/EMACInterface.cpp
  features/netsocket/EMACInterface.h
Labels: ready for merge, release-version: 5.10.2

#8122 LPC1768 us_ticker.c timer choice
  targets/TARGET_NXP/TARGET_LPC176X/us_ticker.c
  targets/targets.json
Labels: ready for merge, release-version: 5.10.2

#8213 STM32F1 RTC : save values in register
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_rtc.c
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_rtc.h
  targets/TARGET_STM/rtc_api.c
Labels: ready for merge, release-version: 5.10.2

#8148 Cellular: Quectel BC95 TCP socket support
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.h
Labels: ready for merge, release-version: 5.11.0-rc1

#7902 Fix overflow in disk_get_sector_size()
  features/storage/filesystem/fat/FATFileSystem.cpp
Labels: ready for merge, release-version: 5.10.2

#8183 Adding QOS in response to LinkADRReq and fixing class C bugs
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
  features/lorawan/lorastack/phy/lora_phy_ds.h
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.10.2

#8219 STM32 EMAC : lock deep sleep
  features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac.cpp
Labels: ready for merge, release-version: 5.10.2

#8256 Fix warnings in block devices
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
  features/storage/blockdevice/BufferedBlockDevice.cpp
  features/storage/blockdevice/ChainingBlockDevice.cpp
  features/storage/blockdevice/ExhaustibleBlockDevice.cpp
  features/storage/blockdevice/FlashSimBlockDevice.cpp
Labels: ready for merge, release-version: 5.10.2

#8258 Cellular: Fix compile warnings for CellularNetwork
  features/cellular/framework/API/CellularNetwork.h
Labels: ready for merge, release-version: 5.10.2

#8270 Tools: Ensure vtor reserved bits are all 0
  tools/config/__init__.py
Labels: ready for merge, release-version: 5.10.2

#8273 Update mbed-coap to version 4.7.0
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_coap_protocol.h
  features/frameworks/mbed-coap/module.json
  features/frameworks/mbed-coap/source/include/sn_coap_protocol_internal.h
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.10.2

#8363 Remove mbed-os-example-client
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.10.2

#8180 Cellular: Quectel BG96 TCP socket support
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.h
Labels: ready for merge, release-version: 5.11.0-rc1

#8248 Tools, Resources: Convert to a set during win2unix
  tools/resources/__init__.py
Labels: ready for merge, release-version: 5.10.2

#8393 Revert "Merge pull request #8183 from hasnainvirk/QOS_impl"
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
  features/lorawan/lorastack/phy/lora_phy_ds.h
  features/lorawan/system/lorawan_data_structures.h
Labels: release-version: 5.10.2

#8390 Fixed colorama Python package
  requirements.txt
Labels: release-version: 5.10.2

#5285 Update devices to have minimum 2K RAM and heap, also added test
  TESTS/mbed_hal/minimum_requirements/main.cpp
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_IAR/MKL25Z4.icf
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_IAR/NANO130.icf
  targets/TARGET_NUVOTON/mbed_rtx.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F070RB/device/TOOLCHAIN_GCC_ARM/STM32F070XB.ld
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F070RB/device/TOOLCHAIN_GCC_ARM/STM32F0xxx_retarget.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F070RB/device/TOOLCHAIN_IAR/stm32f070xb.icf
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/device/TOOLCHAIN_GCC_ARM/STM32F072XB.ld
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/device/TOOLCHAIN_GCC_ARM/STM32F0xxx_retarget.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/device/TOOLCHAIN_IAR/stm32f072xb.icf
  targets/TARGET_STM/mbed_rtx.h
  targets/TARGET_TOSHIBA/TARGET_TMPM066/device/TOOLCHAIN_IAR/tmpm066fwug.icf
  targets/TARGET_TOSHIBA/TARGET_TMPM3H6/device/TOOLCHAIN_IAR/tmpm3h6fwfg.icf
  targets/TARGET_TOSHIBA/mbed_rtx.h
  targets/TARGET_WIZNET/TARGET_W7500x/TARGET_WIZwiki_W7500/device/TOOLCHAIN_IAR/W7500_Flash.icf
  targets/TARGET_WIZNET/TARGET_W7500x/TARGET_WIZwiki_W7500ECO/device/TOOLCHAIN_IAR/W7500_Flash.icf
  targets/TARGET_WIZNET/TARGET_W7500x/TARGET_WIZwiki_W7500P/device/TOOLCHAIN_IAR/W7500_Flash.icf
Labels: ready for merge, release-version: 5.10.2

#8002 Storage: Add required header file and namespace element instead add all
  features/storage/blockdevice/BufferedBlockDevice.cpp
  features/storage/blockdevice/ChainingBlockDevice.cpp
  features/storage/blockdevice/ChainingBlockDevice.h
  features/storage/blockdevice/ExhaustibleBlockDevice.cpp
  features/storage/blockdevice/FlashSimBlockDevice.cpp
  features/storage/blockdevice/HeapBlockDevice.cpp
  features/storage/blockdevice/HeapBlockDevice.h
  features/storage/blockdevice/MBRBlockDevice.cpp
  features/storage/blockdevice/MBRBlockDevice.h
  features/storage/blockdevice/ObservingBlockDevice.cpp
  features/storage/blockdevice/ObservingBlockDevice.h
  features/storage/blockdevice/ProfilingBlockDevice.h
  features/storage/blockdevice/ReadOnlyBlockDevice.cpp
  features/storage/blockdevice/SlicingBlockDevice.h
  features/storage/filesystem/fat/FATFileSystem.cpp
  features/storage/filesystem/littlefs/LittleFileSystem.cpp
  features/storage/nvstore/TESTS/nvstore/functionality/main.cpp
Labels: ready for merge, release-version: 5.10.2

#8237 PR template: add "docs update"
  .github/pull_request_template.md
Labels: ready for merge, release-version: 5.10.2

#8234 Renesas : Modify LPTicker driver
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/PeripheralPins.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/os_tick_ostm.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/mbed_drv_cfg.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/os_tick_ostm.c
Labels: ready for merge, release-version: 5.10.2

#8334 mbed dm: Check for missing payload and give a better error message
  tools/device_management.py
Labels: Priority-High, ready for merge, release-version: 5.10.2

#8331 Stream: add necessary flushes, removing unneeded IAR workaround
  TESTS/mbed_platform/Stream/main.cpp
  platform/Stream.cpp
  platform/Stream.h
  platform/mbed_retarget.cpp
Labels: Priority-High, ready for merge, release-version: 5.11.0-rc1

#8410 Rollup: Austin Writathon + a few more docs PRs
  .github/issue_template.md
  UNITTESTS/README.md
  drivers/CAN.h
  drivers/InterruptIn.h
  drivers/QSPI.h
  drivers/Ticker.h
  drivers/Timeout.h
  drivers/Timer.h
  features/device_key/source/DeviceKey.h
  mbed.h
  platform/mbed_error.h
  platform/mbed_mem_trace.h
  platform/mbed_poll.cpp
  platform/mbed_stats.h
  rtos/Mutex.h
Labels: needs: CI

#8208 Align github's issue template with pull request's look&feel.
  .github/issue_template.md
Labels: needs: CI, release-version: 5.10.2, rollup

#8226 Unit tests: improve unit testing documentation
  UNITTESTS/README.md
Labels: needs: CI, release-version: 5.10.2, rollup

#8338 poll: Un-doxygen internal comment
  platform/mbed_poll.cpp
Labels: needs: CI, release-version: 5.10.2, rollup

#8385 improve can documentation
  drivers/CAN.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8389 Fix minor typo in Timeout
  drivers/Timeout.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8391 improve mutex doc
  rtos/Mutex.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8392 Interruptin documentation update
  drivers/InterruptIn.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8394 improve ticker doc
  drivers/Ticker.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8395 Adding doxygen comments for mem trace enum
  platform/mbed_mem_trace.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8397 Updating stats doc comments
  platform/mbed_stats.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8406 Timer documentation update
  drivers/Timer.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8407 DeviceKey doxygen update
  features/device_key/source/DeviceKey.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8409 Fix doxygen comments and spelling errors
  platform/mbed_error.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8310 MCUXpresso: Add Flash support for KL43Z, KL82Z, KW41Z, K22F
  targets/targets.json
Labels: ready for merge, release-version: 5.10.2

#8423 Rollup PR: Additional doc PRs + lingering need:CI PRs
  drivers/AnalogIn.h
  drivers/AnalogOut.h
  drivers/DigitalIn.h
  drivers/DigitalInOut.h
  drivers/DigitalOut.h
  drivers/I2C.h
  events/EventQueue.h
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/LICENSE
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/mbed-bootloader-internal_dfb7cc.bin
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/mbed_lib.json
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  platform/ATCmdParser.h
  platform/mbed_alloc_wrappers.cpp
  platform/mbed_rtc_time.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/spi_api.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/system_clock.c
  targets/TARGET_STM/serial_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/us_ticker.c
  targets/targets.json
  tools/memap.py
Labels: ready for merge

#8062 Signature to track memory allocations by wrapper functions
  platform/mbed_alloc_wrappers.cpp
Labels: needs: CI, release-version: 5.10.2, rollup

#8238 Add usticker feature to TMPM46B
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/us_ticker.c
  targets/targets.json
Labels: needs: CI, release-version: 5.10.2, rollup

#8271 Tools, memap: Silence warnings that we handled correctly
  tools/memap.py
Labels: Priority-High, needs: CI, release-version: 5.10.2, rollup

#8284 STM32: Only LSE clock should be enabled in STOP mode
  targets/TARGET_STM/serial_api.c
Labels: needs: CI, release-version: 5.10.2, rollup

#8370 Cellular: Error handling for socket create
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
Labels: needs: CI, release-version: 5.10.2, rollup

#8379 Renesas : Minor change of SPI driver
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/spi_api.c
Labels: needs: CI, release-version: 5.10.2, rollup

#8408 Added bootloader bin license and config for DISCO_L475VG_IOT01A
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/LICENSE
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/mbed-bootloader-internal_dfb7cc.bin
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/mbed_lib.json
Labels: needs: CI, release-version: 5.10.2, rollup

#8414 Remove protected class from EventQueue Doxy
  events/EventQueue.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8416 wich->which
  platform/mbed_rtc_time.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8417 I2c doc update
  drivers/I2C.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8418 Remove protected members from doxy in Analog/Digital classes
  drivers/AnalogIn.h
  drivers/AnalogOut.h
  drivers/DigitalIn.h
  drivers/DigitalInOut.h
  drivers/DigitalOut.h
Labels: needs: CI, release-version: 5.10.2, rollup

#8420 Doc changes and rephrasing
  platform/ATCmdParser.h
Labels: needs: CI, release-version: 5.10.2, rollup

#7980 Clean up rtos::Thread deprecation warnings
  TESTS/mbed_drivers/lp_ticker/main.cpp
  TESTS/mbed_drivers/mem_trace/main.cpp
  TESTS/mbed_drivers/race_test/main.cpp
  TESTS/mbed_drivers/ticker/main.cpp
  TESTS/mbed_drivers/timeout/timeout_tests.h
  TESTS/mbed_hal/sleep_manager_racecondition/main.cpp
  TESTS/mbed_platform/stats_cpu/main.cpp
  TESTS/mbed_platform/stats_thread/main.cpp
  TESTS/mbedmicro-rtos-mbed/basic/main.cpp
  TESTS/mbedmicro-rtos-mbed/event_flags/main.cpp
  TESTS/mbedmicro-rtos-mbed/heap_and_stack/main.cpp
  TESTS/mbedmicro-rtos-mbed/mail/main.cpp
  TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
  TESTS/mbedmicro-rtos-mbed/mutex/main.cpp
  TESTS/mbedmicro-rtos-mbed/queue/main.cpp
  TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp
  TESTS/mbedmicro-rtos-mbed/signals/main.cpp
  TESTS/mbedmicro-rtos-mbed/threads/main.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest_burst.cpp
  TESTS/netsocket/tcp/tcpsocket_endpoint_close.cpp
  TESTS/netsocket/tcp/tcpsocket_recv_100k.cpp
  TESTS/netsocket/tcp/tcpsocket_recv_timeout.cpp
  TESTS/netsocket/tcp/tcpsocket_thread_per_socket_safety.cpp
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_echotest_burst.cpp
  TESTS/netsocket/udp/udpsocket_recv_timeout.cpp
  TEST_APPS/device/nanostack_mac_tester/main.cpp
  TEST_APPS/device/socket_app/cmd_socket.cpp
  UNITTESTS/features/cellular/framework/AT/athandler/unittest.cmake
  UNITTESTS/stubs/ThisThread_stub.cpp
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.cpp
  components/802.15.4_RF/mcr20a-rf-driver/source/NanostackRfPhyMcr20a.cpp
  drivers/UARTSerial.cpp
  features/cellular/TESTS/api/cellular_network/main.cpp
  features/cellular/framework/AT/ATHandler.cpp
  features/frameworks/greentea-client/source/greentea_metrics.cpp
  features/nanostack/targets/TARGET_NCS36510/NanostackRfPhyNcs36510.cpp
  features/netsocket/emac-drivers/TARGET_RZ_A1_EMAC/rza1_emac.cpp
  features/unsupported/USBHost/USBHost/USBHost.cpp
  features/unsupported/USBHost/USBHost3GModule/WANDongleSerialPort.cpp
  features/unsupported/USBHost/USBHostHub/USBHostHub.cpp
  features/unsupported/USBHost/USBHostMSD/USBHostMSD.cpp
  features/unsupported/USBHost/USBHostSerial/MtxCircBuffer.h
  features/unsupported/tests/rtos/cmsis/isr/main.cpp
  features/unsupported/tests/rtos/mbed/basic/main.cpp
  features/unsupported/tests/rtos/mbed/file/main.cpp
  features/unsupported/tests/rtos/mbed/isr/main.cpp
  features/unsupported/tests/rtos/mbed/mail/main.cpp
  features/unsupported/tests/rtos/mbed/mutex/main.cpp
  features/unsupported/tests/rtos/mbed/queue/main.cpp
  features/unsupported/tests/rtos/mbed/semaphore/main.cpp
  features/unsupported/tests/rtos/mbed/signals/main.cpp
  features/unsupported/tests/rtos/mbed/timer/main.cpp
  features/unsupported/tests/usb/host/mass_storage/main.cpp
  features/unsupported/tests/usb/host/mouse/main.cpp
  platform/mbed_poll.cpp
  platform/mbed_wait_api.h
  platform/mbed_wait_api_rtos.cpp
  rtos/ConditionVariable.cpp
Labels: ready for merge, release-version: 5.11.0-rc1

#8295 Cellular: Update Cinterion AT drivers
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.h
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularNetwork.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.h
Labels: ready for merge

#8299 Making cancel_sending() API robust
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorawan_types.h
Labels: ready for merge, release-version: 5.10.2

#8336 Fix hard-fault when socket created using accept() is closed
  UNITTESTS/features/netsocket/InternetSocket/test_InternetSocket.cpp
  features/netsocket/InternetSocket.cpp
Labels: ready for merge, release-version: 5.10.2

#8317 Add FlashIAP block device as default block device for WISE 1570
  components/storage/blockdevice/COMPONENT_FLASHIAP/FlashIAPBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_FLASHIAP/FlashIAPBlockDevice.h
  components/storage/blockdevice/COMPONENT_FLASHIAP/TESTS/filesystem/fopen/fopen.cpp
  components/storage/blockdevice/COMPONENT_FLASHIAP/mbed_lib.json
  features/storage/TESTS/filesystem/general_filesystem/main.cpp
  features/storage/system_storage/SystemStorage.cpp
  targets/targets.json
Labels: Priority-High, ready for merge, release-version: 5.10.2

#8434 Change Mbed TLS platform error code and value
  features/cryptocell/FEATURE_CRYPTOCELL310/TARGET_MCU_NRF52840/crypto_platform.c
  features/mbedtls/platform/inc/platform_mbed.h
Labels: ready for merge, release-version: 5.10.2

#8429 M2351: Fix LED_GREEN naming error
  targets/TARGET_NUVOTON/TARGET_M2351/PinNames.h
Labels: ready for merge, release-version: 5.10.2

#8427 STM32L4 : sleep issue
  targets/TARGET_STM/sleep.c
Labels: ready for merge, release-version: 5.10.2

#8255 Change behaviour of mbed_asert to use mbed_error instead of mbed_die
  platform/mbed_assert.c
  platform/mbed_error.c
  platform/mbed_error.h
Labels: ready for merge, release-version: 5.11.0-rc1

#8405 [LoRaWAN]: Adding QOS in response to LinkADRReq and fixing class C bugs
  UNITTESTS/features/lorawan/loramac/Test_LoRaMac.cpp
  UNITTESTS/features/lorawan/loraphy/Test_LoRaPHY.cpp
  UNITTESTS/features/lorawan/lorawaninterface/Test_LoRaWANInterface.cpp
  UNITTESTS/features/lorawan/lorawanstack/Test_LoRaWANStack.cpp
  UNITTESTS/stubs/LoRaMac_stub.cpp
  UNITTESTS/stubs/LoRaMac_stub.h
  UNITTESTS/stubs/LoRaPHY_stub.cpp
  UNITTESTS/stubs/LoRaWANStack_stub.cpp
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
  features/lorawan/lorastack/phy/lora_phy_ds.h
  features/lorawan/system/lorawan_data_structures.h
Labels: needs: CI, release-version: 5.10.2

#8419 PortIn.h: Documentation improvements only
  drivers/PortIn.h
Labels: ready for merge, release-version: 5.10.2

#8437 MCUXpresso: Fix for the TRNG HAL driver
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/trng_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/trng_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/trng_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/trng_api.c
Labels: ready for merge, release-version: 5.10.2

#8446 Pin urllib3 pip module in requirements.txt
  .travis.yml
  requirements.txt
Labels: needs: CI, release-version: 5.10.2

#8008 Add required header file and namespace element instead add all
  TESTS/lorawan/loraradio/main.cpp
  TESTS/mbed_platform/FileHandle/TestFile.h
  components/storage/blockdevice/COMPONENT_SPIF/TESTS/block_device/spif/main.cpp
  features/device_key/TESTS/device_key/functionality/main.cpp
  features/frameworks/greentea-client/source/greentea_metrics.cpp
  features/frameworks/greentea-client/source/greentea_test_env.cpp
  features/frameworks/utest/mbed-utest-shim.cpp
  features/frameworks/utest/source/utest_shim.cpp
  features/frameworks/utest/source/utest_stack_trace.cpp
  features/frameworks/utest/utest/utest_scheduler.h
  features/nanostack/mbed-mesh-api/source/LoWPANNDInterface.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEMACInterface.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  features/nanostack/mbed-mesh-api/source/ThreadInterface.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp
  features/nanostack/nanostack-interface/Nanostack.cpp
  features/nanostack/nanostack-interface/Nanostack.h
  features/netsocket/EMACInterface.cpp
  features/netsocket/EMACInterface.h
  features/netsocket/EthernetInterface.h
  features/netsocket/TCPServer.cpp
  features/storage/TESTS/filesystem/general_filesystem/main.cpp
Labels: Priority-High, needs: CI, release-version: 5.10.2

#8302 Use wait_ms(int) instead of wait(float)
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/ota_api.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/sdk/ublox-odin-w2-drivers/OdinWiFiInterface.cpp
Labels: ready for merge, release-version: 5.10.2

#8354 SingletonPtr: const and alignment
  platform/SingletonPtr.h
Labels: ready for merge, release-version: 5.11.0-rc1

#8425 M487: Fix SW2/SW3 interchange error in NUMAKER_IOT_M487
  targets/TARGET_NUVOTON/TARGET_M480/PinNames.h
Labels: ready for merge, release-version: 5.10.2

#8359 Allow overriding build timestamp from env
  tools/toolchains/__init__.py
Labels: needs: CI, release-version: 5.10.2

#8442 Add missing define in drivers/SerialWireOutput.h
  drivers/SerialWireOutput.h
Labels: needs: CI, release-version: 5.10.2

#8453 Fixed lorawan unittests valgrind issues
  UNITTESTS/features/lorawan/loramac/Test_LoRaMac.cpp
  UNITTESTS/features/lorawan/loramacchannelplan/Test_LoRaMacChannelPlan.cpp
  UNITTESTS/features/lorawan/loraphy/Test_LoRaPHY.cpp
  UNITTESTS/features/lorawan/loraphyau915/Test_LoRaPHYAU915.cpp
  UNITTESTS/features/lorawan/loraphycn470/Test_LoRaPHYCN470.cpp
  UNITTESTS/features/lorawan/loraphykr920/Test_LoRaPHYKR920.cpp
  UNITTESTS/features/lorawan/loraphyus915/Test_LoRaPHYUS915.cpp
  UNITTESTS/features/lorawan/lorawanstack/Test_LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
Labels: ready for merge, release-version: 5.10.2

#8451 Added missing _mutex->unlock() to FileBase::lookup().
  platform/FileBase.cpp
Labels: ready for merge, release-version: 5.10.2

#8439 Correct mesh network connection status callback functionality.
  features/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/nd_tasklet.c
  features/nanostack/mbed-mesh-api/source/thread_tasklet.c
Labels: ready for merge, release-version: 5.10.2

#8349 A Reduced SPIF Block Device for Boot Loader
  components/storage/blockdevice/COMPONENT_RSPIF/SPIFReducedBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_RSPIF/SPIFReducedBlockDevice.h
  components/storage/blockdevice/COMPONENT_RSPIF/mbed_lib.json
Labels: ready for merge, release-version: 5.10.2

#8463 Rollup PR
  platform/Callback.h
  platform/ScopedLock.h
  platform/mbed_assert.h
  platform/mbed_critical.h
  platform/mbed_power_mgmt.h
  platform/mbed_rtc_time.h
Labels: needs: CI

#8455 underlyng->underlying
  platform/mbed_critical.h
Labels: needs: CI, release-version: 5.10.2, rollup PR

#8456 Remove extra e in deepsleep
  platform/mbed_power_mgmt.h
Labels: needs: CI, release-version: 5.10.2, rollup PR

#8457 Infered->Inferred
  platform/Callback.h
Labels: needs: CI, release-version: 5.10.2, rollup PR

#8458 locable->lockable
  platform/ScopedLock.h
Labels: needs: CI, release-version: 5.10.2, rollup PR

#8459 Minor mbed_assert doxy typos patch
  platform/mbed_assert.h
Labels: needs: CI, release-version: 5.10.2, rollup PR

#8460 funtion->function
  platform/mbed_rtc_time.h
Labels: needs: CI, release-version: 5.10.2, rollup PR

#8307 Add support for RapidIoT
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_RAPIDIOT/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_RAPIDIOT/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_RAPIDIOT/PinNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_RAPIDIOT/device.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_RAPIDIOT/fsl_clock_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_RAPIDIOT/fsl_clock_config.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_RAPIDIOT/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/flash_api.c
  targets/targets.json
  tools/export/iar/iar_definitions.json
Labels: Priority-High, needs: CI, release-version: 5.10.2, scope: new-target

#8288 tools: Raise NotSupported when target definition is incomplete
  tools/targets/__init__.py
Labels: Priority-High, ready for merge, release-version: 5.10.2

#8381 Fix status sequence and reporting for LWIP stack
  features/lwipstack/LWIPInterface.cpp
Labels: ready for merge, release-version: 5.10.2

#7948 Add enable/disable cb function in mem_trace
  platform/mbed_mem_trace.cpp
  platform/mbed_mem_trace.h
Labels: Priority-High, ready for merge, release-version: 5.11.0-rc1

#8076 Error output improvements
  drivers/UARTSerial.cpp
  drivers/UARTSerial.h
  platform/mbed_board.c
  platform/mbed_error.c
  platform/mbed_error.h
  platform/mbed_interface.h
  platform/mbed_retarget.cpp
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.c
Labels: ready for merge, release-version: 5.11.0-rc1

#8424 Update doxygens to be in sync
  doxyfile_options
  doxygen_options.json
  features/FEATURE_BLE/DOXYGEN_FRONTPAGE_BLE.md
Labels: needs: CI, release-version: 5.10.2

#8400 This PR retrieves the TimerSync function to fix the lockup issue
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/device/TOOLCHAIN_ARM_STD/lib_peripheral_mbed_arm.ar
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/device/TOOLCHAIN_GCC_ARM/lib_peripheral_mbed_gcc.a
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/device/TOOLCHAIN_IAR/lib_peripheral_mbed_iar.a
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/us_ticker.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/soc/realtek/8195a/fwlib/hal_timer.h
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/soc/realtek/8195a/fwlib/rtl8195a/rtl8195a_timer.h
Labels: Priority-High, needs: CI, release-version: 5.10.2

#8421 PortOut.h: Documentation improvements only
  drivers/PortOut.h
Labels: needs: CI, release-version: 5.10.2

#8469 mbedgt-network-wifi WIFI_CONNECT - check for empty passwd
  TESTS/network/wifi/wifi_connect.cpp
Labels: needs: CI, release-version: 5.10.2
