Repository ARMmbed/mbed-os, pull requests merged in 2018-04, with the labels that each got.

#6516 [feature-nrf528xx] Fix off-by-one error in NRF52 serial implementation
  targets/TARGET_NORDIC/TARGET_NRF5x/serial_api.c
Labels: needs: CI

#6512 Move Mbed 5 support check so that it affects the exporters
  tools/build_api.py
  tools/config/__init__.py
Labels: ready for merge

#6518 Inrease thread stack size to 1024 bytes in NVStore test for NRF52
  features/nvstore/TESTS/nvstore/functionality/main.cpp
Labels: ready for merge

#6411 Stack refactoring
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.cpp
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMacChannelPlan.cpp
  features/lorawan/lorastack/mac/LoRaMacChannelPlan.h
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/mac/LoRaMacMcps.cpp
  features/lorawan/lorastack/mac/LoRaMacMcps.h
  features/lorawan/lorastack/mac/LoRaMacMib.cpp
  features/lorawan/lorastack/mac/LoRaMacMib.h
  features/lorawan/lorastack/mac/LoRaMacMlme.cpp
  features/lorawan/lorastack/mac/LoRaMacMlme.h
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYAS923.cpp
  features/lorawan/lorastack/phy/LoRaPHYAS923.h
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.h
  features/lorawan/lorastack/phy/LoRaPHYIN865.cpp
  features/lorawan/lorastack/phy/LoRaPHYKR920.cpp
  features/lorawan/lorastack/phy/LoRaPHYKR920.h
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.h
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.h
  features/lorawan/lorastack/phy/lora_phy_ds.h
  features/lorawan/lorastack/phy/loraphy_target.h
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6533 Fix deep sleep locking for Timeout class
  drivers/Timeout.cpp
Labels: ready for merge, release-version: 5.8.2

#6527 Test line-ending problems
  .travis.yml
Labels: ready for merge, release-version: 5.8.2

#6531 Fix doxygen comments to reflect the deprecated functions
  drivers/InterruptManager.h
  platform/ATCmdParser.h
  platform/CallChain.h
  platform/CriticalSectionLock.h
  platform/mbed_power_mgmt.h
Labels: ready for merge, release-version: 5.8.2

#6490 ADI: Fix EV_COG_AD3029LZ and EV_COG_AD4050LZ us_ticker_fire_interrupt() minimal time interval
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/api/us_ticker.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/api/us_ticker.c
Labels: ready for merge, release-version: 5.8.2

#6442 Add test for MbedCRC.h
  TESTS/mbed_drivers/crc/main.cpp
  drivers/MbedCRC.cpp
  drivers/MbedCRC.h
Labels: ready for merge

#6524 Fix IPv4 address parsing due to not-so-portable scanf modifier
  features/netsocket/SocketAddress.cpp
Labels: ready for merge, release-version: 5.8.2

#6557 LoRa: Fixed cflist decoding issue
  features/lorawan/lorastack/phy/LoRaPHY.cpp
Labels: ready for merge, release-version: 5.8.2

#6552 Error on invalid mbed_lib JSON
  tools/config/__init__.py
Labels: ready for merge

#6530 Exclude files like `.main.cpp` from builds
  tools/toolchains/__init__.py
Labels: ready for merge

#6511 Add new target USI WM-BN-BM-22
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_MTB_USI_WM_BN_BM_22/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_MTB_USI_WM_BN_BM_22/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_MTB_USI_WM_BN_BM_22/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_MTB_USI_WM_BN_BM_22/system_clock.c
  targets/targets.json
Labels: Scope: new-target, ready for merge, release-version: 5.8.3

#6561 Stm32 deep sleep clock
  targets/TARGET_STM/sleep.c
Labels: ready for merge, release-version: 5.8.3

#6481 Code::Blocks project file exporter
  tools/export/__init__.py
  tools/export/codeblocks/__init__.py
  tools/export/codeblocks/cbp.tmpl
  tools/export/codeblocks/mbedignore.tmpl
Labels: release-version: 5.8.3

#6553 Correct armc6 detection logic for STM32L4
  targets/TARGET_STM/TARGET_STM32L4/l4_retarget.c
  targets/TARGET_STM/mbed_rtx.h
Labels: ready for merge, release-version: 5.8.3

#6576 TEST update : tests-mbed_hal-lp_ticker
  TESTS/mbed_hal/lp_ticker/main.cpp
Labels: needs: CI

#6566 LoRa: Stack cleanup
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/phy/loraphy_target.h
  features/lorawan/mbed_lib.json
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6509 Add an NV_SEED test to the config adjustment script
  features/mbedtls/importer/adjust-config.sh
Labels: ready for merge, release-version: 5.8.3

#6572 cellular: ATHandler send delay
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.h
Labels: release-version: 5.8.3

#6505 remove MODULE_UBLOX_ODIN_W2 from targets.json
  targets/targets.json
Labels: ready for merge

#6544 add ADC_AN0-2 mapped on PA_0-2
  targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_RAK811/PeripheralPins.c
Labels: ready for merge

#6550 Remove MPS2 M1
  targets/targets.json
Labels: ready for merge

#6564 Travis: Fix rate-limit issue with Github requests
  .travis.yml
Labels: ready for merge

#6584 tests-mbed_hal-lp_ticker: Add overflow protection.
  TESTS/mbed_hal/lp_ticker/main.cpp
Labels: ready for merge

#6595 Fix typo with NVStore
  features/nvstore/source/nvstore.cpp
Labels: release-version: 5.8.3

#6587 LoRa: Internal include paths corrected
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.cpp
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMacChannelPlan.cpp
  features/lorawan/lorastack/mac/LoRaMacChannelPlan.h
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.h
  features/lorawan/lorastack/mac/LoRaMacCrypto.cpp
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.h
  features/lorawan/lorastack/phy/lora_phy_ds.h
  features/lorawan/system/LoRaWANTimer.cpp
  features/lorawan/system/LoRaWANTimer.h
Labels: ready for merge

#6586 Lora: Introduce new receive API which returns port and flags
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.cpp
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6567 DISCO_F769NI: set clock_source to USE_PLL_HSE_EXTC
  targets/targets.json
Labels: ready for merge, release-version: 5.8.3

#6418 Add an option to use LowPowerTimer for poll
  platform/mbed_lib.json
  platform/mbed_poll.cpp
Labels: ready for merge, release-version: 5.9.0-rc1

#6169 CM3DS Maintenance Pull Request: TRNG support (3/4)
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/LICENSE
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/README.md
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/host/src/tztrng_lib/include/config_fetrng.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/host/src/tztrng_lib/include/config_trng90b.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/host/src/tztrng_lib/include/tztrng.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/host/src/tztrng_lib/include/tztrng_defs.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/host/src/tztrng_lib/include/tztrng_pal.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/host/src/tztrng_lib/llf_rnd.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/host/src/tztrng_lib/llf_rnd_common.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/host/src/tztrng_lib/llf_rnd_cont.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/host/src/tztrng_lib/llf_rnd_trng90b.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/host/src/tztrng_lib/tztrng_driver.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/host/src/tztrng_lib/tztrng_pal.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/mbed-os.py
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/shared/hw/include/dx_env.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/shared/hw/include/dx_reg_base_host.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/TZ-TRNG/shared/hw/include/dx_rng.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/objects.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/trng_api.c
  targets/targets.json
Labels: component: tls, mirrored, ready for merge, tracking

#6569 Lora: small fixes
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
Labels: ready for merge, release-version: 5.8.3

#6619 PR template: fix tick definition
  .github/pull_request_template.md
Labels: ready for merge, release-version: 5.8.3

#6501 Implementation of SLEEP feature for Renesas mbed boards
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/sleep.c
  targets/targets.json
Labels: ready for merge

#6600 [IOTCELL] Setting up channels for AU915
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
Labels: ready for merge, release-version: 5.8.3

#6618 Update mbed-coap to version 4.4.2
  features/FEATURE_COMMON_PAL/mbed-coap/CHANGELOG.md
  features/FEATURE_COMMON_PAL/mbed-coap/module.json
  features/FEATURE_COMMON_PAL/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.8.3

#6626 Cellular: Separated context activation in CellularConnectionFSM.
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
  features/cellular/easy_cellular/CellularConnectionFSM.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: ready for merge

#6634 Add iar export support for STM32L151CC
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.8.3

#6632 cellular: Error messages
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
  features/cellular/easy_cellular/EasyCellularConnection.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularSIM.cpp
Labels: ready for merge, release-version: 5.8.3

#6625 rtl8195am - fix excessive compiler warnings
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/PinNames.h
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/soc/realtek/8195a/fwlib/hal_i2c.h
Labels: ready for merge, release-version: 5.8.3

#6620 Cellular: fixed athandler unit tests.
  features/cellular/UNITTESTS/at/athandler/Makefile
  features/cellular/UNITTESTS/stubs/ATHandler_stub.cpp
  features/cellular/UNITTESTS/stubs/Kernel.cpp
Labels: ready for merge, release-version: 5.8.3

#6613 Macro expansion results in a constant boolean expression
  features/FEATURE_LWIP/lwip-interface/lwip_stack.c
Labels: ready for merge, release-version: 5.8.3

#6609 STM32 PCD negative numbers issue
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_pcd.c
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_pcd.c
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd.c
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pcd.c
Labels: ready for merge

#6605 Rework us_ticker and rtc_api/lp_ticker | Fix compiler warning for spi_api
  targets/TARGET_Maxim/TARGET_MAX32625/rtc_api.c
  targets/TARGET_Maxim/TARGET_MAX32625/spi_api.c
  targets/TARGET_Maxim/TARGET_MAX32625/us_ticker.c
Labels: ready for merge, release-version: 5.8.3

#6601 Add new target MTB_ADV_WISE_1530
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_USI_WM_BN_BM_22/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_USI_WM_BN_BM_22/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_USI_WM_BN_BM_22/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_USI_WM_BN_BM_22/system_clock.c
  targets/targets.json
Labels: Scope: new-target, ready for merge, release-version: 5.8.3

#6599 STM32 compilation warning issues
  features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/stm32f2_eth_init.c
  features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F4/TARGET_ARCH_MAX/stm32f4_eth_init.c
  features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F4/TARGET_MTB_UBLOX_ODIN_W2/stm32f4_eth_init.c
  features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F429ZI/stm32f4_eth_init.c
  features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F439ZI/stm32f4_eth_init.c
  features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F746ZG/stm32f7_eth_init.c
  features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F756ZG/stm32f7_eth_init.c
  targets/TARGET_STM/TARGET_STM32F0/device/stm32f0xx_hal_crc.c
  targets/TARGET_STM/TARGET_STM32F0/device/stm32f0xx_ll_spi.h
  targets/TARGET_STM/TARGET_STM32F0/serial_device.c
  targets/TARGET_STM/TARGET_STM32F1/serial_device.c
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_mmc.c
  targets/TARGET_STM/TARGET_STM32F2/serial_device.c
  targets/TARGET_STM/TARGET_STM32F3/device/stm32f3xx_hal_crc.c
  targets/TARGET_STM/TARGET_STM32F3/device/stm32f3xx_ll_spi.h
  targets/TARGET_STM/TARGET_STM32F3/serial_device.c
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_can_legacy.c
  targets/TARGET_STM/TARGET_STM32F4/serial_device.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_can_legacy.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_crc.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_spi.h
  targets/TARGET_STM/TARGET_STM32F7/serial_device.c
  targets/TARGET_STM/TARGET_STM32L0/device/stm32l0xx_hal_crc.c
  targets/TARGET_STM/TARGET_STM32L0/device/stm32l0xx_ll_spi.h
  targets/TARGET_STM/TARGET_STM32L0/serial_device.c
  targets/TARGET_STM/TARGET_STM32L1/serial_device.c
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_can_legacy.c
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_spi.h
  targets/TARGET_STM/TARGET_STM32L4/serial_device.c
  targets/TARGET_STM/stm_spi_api.c
Labels: ready for merge, release-version: 5.8.3

#6598 LPC4088: Fix hardfault occuring after power-cycle
  targets/TARGET_NXP/TARGET_LPC408X/sleep.c
Labels: ready for merge, release-version: 5.8.3

#6541 Add mbed-os 5 build support for LPC11C24
  targets/TARGET_NXP/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, release-version: 5.8.3

#6466 Nuvoton: Fix issues with SPI
  targets/TARGET_NUVOTON/TARGET_M451/spi_api.c
  targets/TARGET_NUVOTON/TARGET_M480/spi_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/spi_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/spi_api.c
Labels: ready for merge, release-version: 5.8.3

#6468 Fix deep sleep implementation
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/device/MKL27Z644_features.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/drivers/fsl_flash.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/drivers/fsl_flash.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/device/MKL43Z4_features.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/drivers/fsl_flash.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/drivers/fsl_flash.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/device/MKL82Z7_features.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/drivers/fsl_flash.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/drivers/fsl_flash.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/device/MKW24D5_features.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/drivers/fsl_flash.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/drivers/fsl_flash.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/drivers/fsl_flash.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/drivers/fsl_flash.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/TARGET_MCU_K22F512/device/MK22F51212_features.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/drivers/fsl_flash.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/drivers/fsl_flash.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/sleep.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/sleep.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_FF_LPC546XX/device.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/TARGET_LPCXpresso/device.h
Labels: ready for merge, release-version: 5.8.3

#6510 Adding missing @deprecated to function inline documentation
  platform/DirHandle.h
  platform/FileHandle.h
Labels: ready for merge, release-version: 5.8.3

#6570 Cellular: add detach from the network
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6580 Cleanup get_config (mbed compile --config)
  tools/get_config.py
Labels: ready for merge, release-version: 5.8.3

#6588 [IOTCELL-741] Separating public data structures
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.h
  features/lorawan/lorawan_types.h
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6607 Improve SPI block write
  targets/TARGET_Maxim/TARGET_MAX32630/spi_api.c
Labels: ready for merge, release-version: 5.8.3

#6621 Use pyelftools for Realtek post-build script
  tools/targets/REALTEK_RTL8195AM.py
Labels: ready for merge, release-version: 5.8.3

#6627 Nanostack hal timer shortcut
  features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp
  features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.c
Labels: ready for merge, release-version: 5.9.0-rc1

#6637 Add IAR export for STM32L496AG
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.8.3

#6647 Fix MCUXpresso LPC I2C driver
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/i2c_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/drivers/fsl_i2c.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/drivers/fsl_i2c.c
Labels: ready for merge, release-version: 5.8.3

#6648 ADI: Add BUTTON pin names for EV_COG_AD4050LZ and EV_COG_AD3029LZ
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TARGET_EV_COG_AD3029LZ/PinNames.h
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TARGET_EV_COG_AD4050LZ/PinNames.h
Labels: ready for merge, release-version: 5.8.3

#6603 Optional hardware flow control for STDOUT
  platform/mbed_retarget.cpp
  targets/targets.json
Labels: needs: CI, release-version: 5.8.3

#6638 [QSPI] Add support for several STM disco boards
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/objects.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_DISCO_F469NI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/objects.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_DISCO_L476VG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_DISCO_L476VG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/objects.h
  targets/TARGET_STM/qspi_api.c
  targets/targets.json
Labels: ready for merge

#6592 Updates tools to be runnable in Python 3
  tools/config/__init__.py
  tools/test/config/invalid_key/test_data.json
  tools/test/config/invalid_key_lib/test_data.json
  tools/test_api.py
Labels: ready for merge, release-version: 5.9.0-rc1

#6653 Stop lwIP using us_ticker
  features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/lwip_sys_arch.c
Labels: ready for merge, release-version: 5.9.0-rc1

#6651 rtl8195am - Fix more compiler warnings
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/i2c_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/log_uart_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/pwmout_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/spi_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/rtw_emac.cpp
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/api/wifi/wifi_conf.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/api/wifi/wifi_promisc.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/api/wifi/wifi_util.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/drivers/wlan/realtek/src/osdep/lwip_intf.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/network/dhcp/dhcps.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/os/os_dep/osdep_service.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/os/os_dep/tcm_heap.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/soc/realtek/8195a/fwlib/hal_ssi.h
Labels: ready for merge, release-version: 5.8.3

#6441 Disable all deprecated exporters
  tools/export/__init__.py
Labels: ready for merge, release-version: 5.9.0-rc1

#6221 LPC546XX: Add TRNG support
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/objects.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/trng_api.c
  targets/targets.json
Labels: component: tls, mirrored, ready for merge, release-version: 5.8.3, tracking

#6656 target: arch_pro enable USBDEVICE support
  targets/targets.json
Labels: ready for merge

#6660 Enable flow control in Greentea
  features/frameworks/greentea-client/source/greentea_serial.cpp
Labels: ready for merge, release-version: 5.8.3

#6655 USB reset test fix
  TESTS/usb_device/basic/main.cpp
Labels: ready for merge

#6629 Cellular: add plmn for CellularConnectionFSM
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
  features/cellular/easy_cellular/CellularConnectionFSM.h
  features/cellular/easy_cellular/EasyCellularConnection.cpp
  features/cellular/easy_cellular/EasyCellularConnection.h
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6663 Use SingletonPtr in Nanostack HAL
  features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp
Labels: ready for merge, release-version: 5.8.3

#6628 Lora: Make automatic uplink message configurable
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorawan_types.h
  features/lorawan/mbed_lib.json
Labels: ready for merge, release-version: 5.9.0-rc1

#6604 littlefs: Fix some issues with lookahead trust
  features/filesystem/littlefs/littlefs/lfs.c
  features/filesystem/littlefs/littlefs/lfs.h
  features/filesystem/littlefs/littlefs/tests/test_alloc.sh
Labels: Scope: bug-fix, ready for merge, release-version: 5.8.3

#6658 Allow library configs to override target configs
  tools/config/__init__.py
Labels: ready for merge, release-version: 5.8.3

#6673 Add endpoint_remove_all helper function
  usb/device/USBDevice/USBDevice.cpp
  usb/device/USBDevice/USBDevice.h
Labels: ready for merge

#6678 Testing feature-hal-spec-ticker after rebase
  targets/targets.json
Labels: do not merge

#6690 ADI: Enable bootloader for EV_COG_AD3029LZ and EV_COG_AD4050LZ
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TARGET_EV_COG_AD3029LZ/device/startup_ADuCM3029.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TARGET_EV_COG_AD3029LZ/device/startup_ADuCM3029.h
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TOOLCHAIN_ARM_STD/ADuCM3029.sct
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TOOLCHAIN_GCC_ARM/ADuCM3029.ld
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TOOLCHAIN_IAR/ADuCM3029.icf
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/api/cmsis_nvic.h
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/api/flash_api.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TARGET_EV_COG_AD4050LZ/device/startup_ADuCM4050.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TARGET_EV_COG_AD4050LZ/device/startup_ADuCM4050.h
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TOOLCHAIN_ARM_STD/ADuCM4050.sct
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TOOLCHAIN_GCC_ARM/ADuCM4050.ld
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TOOLCHAIN_IAR/ADuCM4050.icf
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/api/cmsis_nvic.h
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/api/flash_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.8.4

#6686 Remove automatic I2C stop after each read
  targets/TARGET_Maxim/TARGET_MAX32620C/i2c_api.c
Labels: ready for merge, release-version: 5.8.4

#6683 Add IAR export and nvstore page size fix for TMPM46B
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/flash_api.c
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.8.4

#6682 Fixed cellular unittests
  features/cellular/UNITTESTS/at/at_cellularnetwork/at_cellularnetworktest.cpp
  features/cellular/UNITTESTS/at/at_cellularnetwork/test_at_cellularnetwork.cpp
  features/cellular/UNITTESTS/at/at_cellularnetwork/test_at_cellularnetwork.h
  features/cellular/UNITTESTS/stubs/AT_CellularNetwork_stub.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6669 make PR type box list "fancier" without making it a github tasklist
  .github/pull_request_template.md
Labels: ready for merge

#6611 Uninitialized variable warning in UARTSerial at -O3
  drivers/UARTSerial.cpp
Labels: ready for merge, release-version: 5.8.4

#6602 requirements: add future
  requirements.txt
Labels: ready for merge, release-version: 5.8.4

#6681 feature-emac: Rework nonblocking connect
  features/FEATURE_LWIP/lwip-interface/LWIPInterface.cpp
  features/FEATURE_LWIP/lwip-interface/LWIPStack.h
  features/FEATURE_LWIP/lwip-interface/ppp_lwip.cpp
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/LoWPANNDInterface.cpp
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/source/ThreadInterface.cpp
  features/netsocket/EMACInterface.cpp
  features/netsocket/EMACInterface.h
  features/netsocket/OnboardNetworkStack.h
Labels: ready for merge

#6703 KL27Z: Flash protection macro addition
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/device/MKL27Z644_features.h
Labels: needs: CI, release-version: 5.8.3

#6474 STM32 LPTICKER update for targets supporting LPTIMER
  hal/mbed_lp_ticker_api.c
  hal/mbed_lp_ticker_wrapper.cpp
  targets/TARGET_STM/lp_ticker.c
  targets/targets.json
Labels: ready for merge

#6725 allow doxygen to generate documentation for SAI peripheral
  doxyfile_options
  doxygen_options.json
  hal/sai_api.h
Labels: needs: CI

#6540 Prevent compiling with unsupported compilers
  tools/build_api.py
  tools/test/config/app_override_libs/targets.json
  tools/test/config/compound_inheritance/targets.json
  tools/test/config/double_define/targets.json
  tools/test/config/feature_compesition/targets.json
  tools/test/config/feature_recursive_add/targets.json
  tools/test/config/feature_recursive_complex/targets.json
  tools/test/config/feature_remove/targets.json
  tools/test/config/feature_uvisor/targets.json
  tools/test/config/macro_inheritance/targets.json
  tools/test/config/override_labels_libs/targets.json
  tools/test/config/override_labels_libs_more/targets.json
  tools/test/config/override_labels_targets/targets.json
  tools/test/config/override_precidence/targets.json
  tools/test/config/override_undefined/targets.json
  tools/test/config/override_undefined_libs/targets.json
  tools/test/config/override_with_labels/targets.json
  tools/test/config/simple_features/targets.json
  tools/test/config/simple_iheritance/targets.json
Labels: ready for merge, release-version: 5.8.4

#6692 Lora: Remove singleton pattern
  features/lorawan/LoRaWANInterface.cpp
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMacCrypto.cpp
  features/lorawan/lorastack/mac/LoRaMacCrypto.h
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6702 Cellular: Fix to prefer IPv6 single stack with fallback to IPv4
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6718 Modifying echo test to be driven more from the device.
  TESTS/host_tests/device_echo.py
  TESTS/mbed_drivers/echo/main.cpp
Labels: release-version: 5.8.4

#6704 USBDevice: endpoint_add/read_start functions return value fix
  usb/device/USBDevice/USBDevice.cpp
Labels: ready for merge

#6727 Update URL that points at a blank page.
  .github/pull_request_template.md
Labels: ready for merge, release-version: 5.8.4

#6677 Cellular: fixed null pointer bug in cellular fsm
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
Labels: ready for merge, release-version: 5.8.4

#6723 STM32 RTC Init minor update
  targets/TARGET_STM/rtc_api.c
  targets/TARGET_STM/rtc_api_hal.h
Labels: ready for merge, release-version: 5.8.4

#6735 LPC546XX: Add check for GPIO IRQ
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/gpio_irq_api.c
Labels: ready for merge, release-version: 5.8.4

#6717 Fix NRF52 SPI pin initialization
  targets/TARGET_NORDIC/TARGET_NRF5x/spi_api.c
Labels: ready for merge, release-version: 5.8.4

#6701 Update to EFR32 15.4 driver
  features/nanostack/FEATURE_NANOSTACK/targets/TARGET_SL_RAIL/NanostackRfPhyEfr32.cpp
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/TARGET_EFR32_1/librail_efr32xg1_release.a
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/TARGET_EFR32_1/librail_efr32xg1_release.ar
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/TARGET_EFR32_12/librail_efr32xg12_release.a
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/TARGET_EFR32_12/librail_efr32xg12_release.ar
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/ble/rail_ble.h
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/ieee802154/rail_ieee802154.h
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/pa.h
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/pti.h
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/rail.h
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/rail_assert_error_codes.h
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/rail_chip_specific.h
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/rail_types.h
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/timing_state.h
Labels: ready for merge, release-version: 5.8.4

#6671 Update doxygen options rules to not strip code comments
  doxygen_options.json
Labels: ready for merge, release-version: 5.8.4

#6745 Clarify mesh configuration values.
  features/FEATURE_COMMON_PAL/nanostack-hal-mbed-cmsis-rtos/mbed_lib.json
  features/nanostack/FEATURE_NANOSTACK/mbed-mesh-api/mbed_lib.json
  features/nanostack/FEATURE_NANOSTACK/sal-stack-nanostack/mbed_lib.json
Labels: ready for merge, release-version: 5.8.4

#6734 LPC54XXX: Set the pin function to Digital mode
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/pinmap.c
Labels: ready for merge, release-version: 5.8.4

#6721 Fix bug in Nordic SDK 14.2 I2C driver
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/drivers_nrf/twi_master/nrf_drv_twi.c
Labels: ready for merge, release-version: 5.9.0-rc1

#6720 Fix bug in Nordic SDK 14.2 SPI driver
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/drivers_nrf/spi_master/nrf_drv_spi.c
Labels: ready for merge, release-version: 5.9.0-rc1

#6750 LoRaWAN: Memory corruption due to band mishandling
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYKR920.cpp
  features/lorawan/lorastack/phy/LoRaPHYKR920.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6748 nrf5x: Fix assert test on SERIAL_RESERVED_CHAR_MATCH
  targets/TARGET_NORDIC/TARGET_NRF5x/serial_api.c
Labels: ready for merge, release-version: 5.9.0-rc1

#6747 Support RTOS-less secure image build with Cortex-M23/M33
  cmsis/RTE_Components.h
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6741 Lora: Split add_mac_command() into separate methods
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.h
Labels: ready for merge, release-version: 5.9.0-rc1

#6590 AStyle addition to travis
  .astyleignore
  .astylerc
  .travis.yml
Labels: ready for merge, release-version: 5.9.0-rc1

#6700 mbr: Added assertions for overlapping partitions
  features/filesystem/bd/MBRBlockDevice.cpp
Labels: ready for merge, release-version: 5.9.0-rc1, scope: feature

#6746 Fix vector table relocation for NRF52
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_COMMON/libraries/bootloader/dfu/nrf_dfu_mbr.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_COMMON/libraries/bootloader/dfu/nrf_dfu_mbr.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_COMMON/libraries/bootloader/dfu/nrf_dfu_types.h
  targets/TARGET_NORDIC/TARGET_NRF5x/reloc_vector_table.c
Labels: needs: CI
