Repository ARMmbed/mbed-os, pull requests merged in 2018-11, with the labels that each got.

#8585 Phy drivers: Added S2-LP driver
  components/802.15.4_RF/stm-s2lp-rf-driver/README.md
  components/802.15.4_RF/stm-s2lp-rf-driver/mbed_lib.json
  components/802.15.4_RF/stm-s2lp-rf-driver/source/NanostackRfPhys2lp.cpp
  components/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.c
  components/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.h
  components/802.15.4_RF/stm-s2lp-rf-driver/source/s2lpReg.h
  components/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver/NanostackRfPhys2lp.h
Labels: ready for merge, release-version: 5.10.3

#8599 DISCO_F769NI: Add bootloader support
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/TARGET_DISCO_F769NI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/TOOLCHAIN_ARM_MICRO/stm32f769xi.sct
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/TOOLCHAIN_ARM_STD/stm32f769xi.sct
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/TOOLCHAIN_GCC_ARM/STM32F769xI.ld
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/TOOLCHAIN_IAR/stm32f769xi.icf
  targets/targets.json
Labels: ready for merge, release-version: 5.10.3

#8588 Fix Ice Tea test execution order to be sorted by names.
  tools/run_icetea.py
Labels: needs: CI, release-version: 5.10.3

#8542 Update python module versions in requirements.txt
  requirements.txt
Labels: ready for merge, release-version: 5.10.3

#8577 Fix Makefile export with Python 3
  tools/export/makefile/__init__.py
Labels: ready for merge, release-version: 5.10.3

#8538 Rework make.py CLI to avoid treating apps as tests
  tools/make.py
Labels: needs: CI, release-version: 5.10.3

#8601 Add format checking to printf-type APIs
  cmsis/TARGET_CORTEX_M/mbed_fault_handler.c
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.h
  drivers/RawSerial.h
  features/storage/filesystem/fat/FATFileSystem.cpp
  platform/Stream.h
  platform/mbed_debug.h
  platform/mbed_error.c
  platform/mbed_error.h
  platform/mbed_interface.h
  platform/mbed_toolchain.h
Labels: needs: CI, release-version: 5.11.0-rc1

#8616 Updated and pinned version for requests
  requirements.txt
Labels: needs: CI, release-version: 5.10.3

#8624 Fix missing doxygen pages
  doxyfile_options
  doxygen_options.json
Labels: ready for merge, release-version: 5.10.3

#8611 Unittest fixes
  UNITTESTS/features/lorawan/loraphycn470/Test_LoRaPHYCN470.cpp
  UNITTESTS/features/lorawan/lorawantimer/Test_LoRaWANTimer.cpp
Labels: ready for merge, release-version: 5.10.3

#8596 Ignore disabled Kinetis USB endpoint interrupts
  usb/device/targets/TARGET_Freescale/USBPhy_Kinetis.cpp
Labels: ready for merge, release-version: feature branch

#8524 Add more generic BlockDevice tests.
  components/storage/blockdevice/COMPONENT_DATAFLASH/DataFlashBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_DATAFLASH/DataFlashBlockDevice.h
  features/storage/TESTS/blockdevice/general_block_device/main.cpp
Labels: ready for merge, release-version: 5.10.4

#8605 Make examples commands return a failure
  tools/test/examples/examples.py
  tools/test/examples/examples_lib.py
Labels: ready for merge, release-version: 5.10.4

#8613 Make sure that TLSSocketWrapper::close() is called before the transport is destroyed.
  features/netsocket/TLSSocket.cpp
  features/netsocket/TLSSocket.h
Labels: ready for merge, release-version: 5.10.4

#8621 Add missing include for TLSSocket
  features/netsocket/nsapi.h
Labels: ready for merge, release-version: 5.10.4

#8606 Fix off-by-one-error in BusIn/Out
  drivers/BusIn.cpp
  drivers/BusInOut.cpp
  drivers/BusOut.cpp
Labels: ready for merge, release-version: 5.10.4

#8604 Increase EMAC test timeout to 1400 seconds
  TESTS/network/emac/main.cpp
Labels: needs: CI, release-version: 5.10.4

#8639 Add get_erase_value() support
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.h
Labels: needs: CI, release-version: 5.11.0-rc1

#8612 Add names to system thread
  events/mbed_shared_queues.cpp
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
  features/lwipstack/lwip/src/include/lwip/opt.h
  features/lwipstack/ppp_lwip.cpp
  rtos/TARGET_CORTEX/mbed_rtos_rtx.c
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
Labels: needs: CI, release-version: 5.11.0-rc1

#8652 Rollup PR for docs
  doxyfile_options
  events/Event.h
  events/EventQueue.h
  events/mbed_shared_queues.h
  features/netsocket/NetworkInterface.h
  platform/CallChain.h
  platform/SharedPtr.h
  platform/mbed_error.h
  platform/mbed_mem_trace.h
  platform/mbed_stats.h
  platform/mbed_toolchain.h
  rtos/Queue.h
  rtos/RtosTimer.h
Labels: needs: CI

#8617 Typo fixes in Doxygen for Platform
  platform/CallChain.h
  platform/SharedPtr.h
  platform/mbed_error.h
  platform/mbed_mem_trace.h
  platform/mbed_stats.h
  platform/mbed_toolchain.h
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8622 Fix typos in Events doxygen
  events/Event.h
  events/EventQueue.h
  events/mbed_shared_queues.h
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8623 Fix typos in RTOS doxygen.
  rtos/Queue.h
  rtos/RtosTimer.h
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8663 Rollup PR: Docs + small fixes
  CONTRIBUTING.md
  README.md
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEMACInterface.cpp
  rtos/Kernel.h
  tools/targets/__init__.py
  tools/test/toolchains/arm_support_test.py
  tools/toolchains/__init__.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
Labels: needs: CI

#8435 Kernel.h doxygen update
  rtos/Kernel.h
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8587 Remove extra _deselect to prevent possible hard fault
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8640 Fix compile warning about initializing and variable order
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8642 nanostack: fix memory leak
  features/nanostack/mbed-mesh-api/source/NanostackEMACInterface.cpp
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8488 Rewrite CThunk so it does not execute from ram
  platform/CThunk.h
  platform/CThunkBase.cpp
  platform/CThunkBase.h
  platform/mbed_lib.json
Labels: needs: CI, release-version: 5.11.0-rc1

#8594 Fix USB traceback during testing when wrong size
  TESTS/host_tests/pyusb_basic.py
Labels: ready for merge, release-version: feature branch

#8653 mbed_lib.json updated for other all C030 targets and code corrected t…
  components/storage/blockdevice/COMPONENT_SD/config/mbed_lib.json
  features/cellular/framework/common/CellularTargets.h
Labels: ready for merge, release-version: 5.10.4

#8645 Detect xinetd service pattern and generate correct pattern (ONME-3733)
  TESTS/netsocket/tcp/tcpsocket_recv_100k.cpp
  TEST_APPS/device/socket_app/cmd_socket.cpp
Labels: ready for merge, release-version: 5.10.4

#8602 Sync 802.15.4 RF drivers
  components/802.15.4_RF/atmel-rf-driver/atmel-rf-driver/NanostackRfPhyAtmel.h
  components/802.15.4_RF/atmel-rf-driver/mbed_lib.json
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.cpp
  components/802.15.4_RF/atmel-rf-driver/source/at24mac.cpp
  components/802.15.4_RF/mcr20a-rf-driver/source/MCR20Drv.c
  components/802.15.4_RF/mcr20a-rf-driver/source/MCR20Drv.h
  components/802.15.4_RF/mcr20a-rf-driver/source/MCR20Overwrites.h
  components/802.15.4_RF/mcr20a-rf-driver/source/MCR20Reg.h
  components/802.15.4_RF/mcr20a-rf-driver/source/NanostackRfPhyMcr20a.cpp
  components/802.15.4_RF/mcr20a-rf-driver/source/XcvrSpi.h
Labels: release-version: 5.10.4, rollup PR

#8589 Support erase value in Flash HAL drivers, FlashIAP and block devices
  TESTS/mbed_drivers/flashiap/main.cpp
  components/storage/blockdevice/COMPONENT_FLASHIAP/FlashIAPBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_FLASHIAP/FlashIAPBlockDevice.h
  drivers/FlashIAP.cpp
  drivers/FlashIAP.h
  hal/TARGET_FLASH_CMSIS_ALGO/flash_common_algo.c
  hal/flash_api.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/flash_api.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/flash_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/flash_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/flash_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF51/flash_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/flash_api.c
  targets/TARGET_NUVOTON/TARGET_M2351/flash_api.c
  targets/TARGET_NXP/TARGET_LPC176X/device/flash_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/flash_api.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/flash_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/flash_api.c
  targets/TARGET_STM/TARGET_STM32F0/flash_api.c
  targets/TARGET_STM/TARGET_STM32F1/flash_api.c
  targets/TARGET_STM/TARGET_STM32F2/flash_api.c
  targets/TARGET_STM/TARGET_STM32F3/flash_api.c
  targets/TARGET_STM/TARGET_STM32F4/flash_api.c
  targets/TARGET_STM/TARGET_STM32F7/flash_api.c
  targets/TARGET_STM/TARGET_STM32L0/flash_api.c
  targets/TARGET_STM/TARGET_STM32L1/flash_api.c
  targets/TARGET_STM/TARGET_STM32L4/flash_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/flash_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/flash_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/flash_api.c
Labels: needs: CI, release-version: 5.11.0-rc1, rollup PR

#7849 Low power timer needs to be reset when setting time
  TESTS/mbed_hal/rtc_time/main.cpp
  platform/mbed_rtc_time.cpp
Labels: needs: CI, release-version: 5.10.4

#8444 Add EMAC driver for CM3DS
  features/netsocket/emac-drivers/TARGET_ARM_SSG/COMPONENT_SMSC9220/mbed_lib.json
  features/netsocket/emac-drivers/TARGET_ARM_SSG/COMPONENT_SMSC9220/smsc9220_emac.cpp
  features/netsocket/emac-drivers/TARGET_ARM_SSG/COMPONENT_SMSC9220/smsc9220_emac.h
  features/netsocket/emac-drivers/TARGET_ARM_SSG/COMPONENT_SMSC9220/smsc9220_emac_config.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/device_cfg.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/smsc9220_eth.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/smsc9220_eth.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/smsc9220_eth_drv.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/smsc9220_eth_drv.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/platform_devices.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/platform_devices.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/ethernet_api.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/mbed_overrides.c
  targets/targets.json
Labels: Priority-High, needs: CI, release-version: 5.10.4, rollup PR

#8551 Increase background stack size to fix overflows
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
  rtos/mbed_lib.json
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8590 Export: Remove DS-5
  tools/export/__init__.py
  tools/export/ds5_5/__init__.py
  tools/export/ds5_5/arch_pro.cproject.tmpl
  tools/export/ds5_5/arch_pro.launch.tmpl
  tools/export/ds5_5/arch_pro.project.tmpl
  tools/export/ds5_5/gr_lychee.cproject.tmpl
  tools/export/ds5_5/gr_lychee.launch.tmpl
  tools/export/ds5_5/gr_lychee.project.tmpl
  tools/export/ds5_5/lpc11u24.cproject.tmpl
  tools/export/ds5_5/lpc11u24.launch.tmpl
  tools/export/ds5_5/lpc11u24.project.tmpl
  tools/export/ds5_5/lpc1768.cproject.tmpl
  tools/export/ds5_5/lpc1768.launch.tmpl
  tools/export/ds5_5/lpc1768.project.tmpl
  tools/export/ds5_5/lpc812.cproject.tmpl
  tools/export/ds5_5/lpc812.launch.tmpl
  tools/export/ds5_5/lpc812.project.tmpl
  tools/export/ds5_5/rz_a1h.cproject.tmpl
  tools/export/ds5_5/rz_a1h.launch.tmpl
  tools/export/ds5_5/rz_a1h.project.tmpl
  tools/export/ds5_5/ublox_c027.cproject.tmpl
  tools/export/ds5_5/ublox_c027.launch.tmpl
  tools/export/ds5_5/ublox_c027.project.tmpl
  tools/export/ds5_5/vk_rz_a1h.cproject.tmpl
  tools/export/ds5_5/vk_rz_a1h.launch.tmpl
  tools/export/ds5_5/vk_rz_a1h.project.tmpl
Labels: needs: CI, release-version: 5.11.0-rc1, rollup PR

#8573 Compile time config flag MBED_CONF_SD_CRC_ENABLED for CRC in SD
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.h
  components/storage/blockdevice/COMPONENT_SD/config/mbed_lib.json
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8324 Add Support for TOSHIBA TMPM3HQ
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/PeripheralNames.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/PinNames.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/PortNames.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/analogin_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/analogout_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/TMPM3HQ.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/TOOLCHAIN_ARM_STD/startup_TMPM3HQ.S
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/TOOLCHAIN_ARM_STD/tmpm3hqfdfg.sct
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/TOOLCHAIN_GCC_ARM/startup_TMPM3HQ.S
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/TOOLCHAIN_GCC_ARM/tmpm3hqfdfg.ld
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/TOOLCHAIN_IAR/startup_TMPM3HQ.S
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/TOOLCHAIN_IAR/tmpm3hqfdfg.icf
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/cmsis.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/cmsis_nvic.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/system_TMPM3HQ.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/system_TMPM3HQ.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/gpio_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/gpio_include.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/gpio_irq_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/gpio_object.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/i2c_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/objects.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/periph_driver/txz_driver_def.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/periph_driver/txz_tspi.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/periph_driver/txz_tspi.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/pinmap.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/port_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/pwmout_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/serial_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/sleep.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/spi_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/us_ticker.c
  targets/TARGET_TOSHIBA/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, scope: new-target

#8528 MCUXpresso: Update LPC Flash driver program page function
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/flash_api.c
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8569 CellularConnectionFSM unchain queue when stopped
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8654 InternetSocket: Fixed missing unlock before return
  features/netsocket/InternetSocket.cpp
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8660 Online: Include project root path
  tools/resources/__init__.py
  tools/toolchains/arm.py
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8662 KW41Z: Add Bootloader support
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/TOOLCHAIN_ARM_STD/MKW41Z512xxx4.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/TOOLCHAIN_GCC_ARM/MKW41Z512xxx4.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/TOOLCHAIN_IAR/MKW41Z512xxx4.icf
  targets/targets.json
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8677 Sync mbed-client-cli files with v0.4.0
  features/frameworks/mbed-client-cli/mbed-client-cli/ns_cmdline.h
  features/frameworks/mbed-client-cli/source/ns_cmdline.c
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8684 Update peripheral pins
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/PeripheralPins.c
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8595 Put quotes around include path options
  tools/toolchains/__init__.py
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8670 Remove protected member functions and protected attributes from rendering
  drivers/BusIn.h
  drivers/BusInOut.h
  drivers/BusOut.h
  drivers/FlashIAP.h
  drivers/I2C.h
  drivers/InterruptManager.h
  drivers/LowPowerTimeout.h
  drivers/MbedCRC.h
  drivers/SPI.h
  drivers/SerialBase.h
  drivers/Timeout.h
  drivers/TimerEvent.h
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8679 STM32 GPIO : code cleaning
  targets/TARGET_STM/TARGET_STM32F2/pin_device.h
  targets/TARGET_STM/TARGET_STM32F4/pin_device.h
  targets/TARGET_STM/TARGET_STM32F7/pin_device.h
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8681 STM32F407VG: Add FLASH support
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/device/flash_data.h
  targets/targets.json
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8687 TLSSocketWrapper: decouple error requirements
  features/netsocket/TLSSocketWrapper.cpp
Labels: ready for merge, release-version: 5.11.0-rc1

#8733 Rollup PR: Resume testing on PRs with false failures
  UNITTESTS/features/netsocket/InternetSocket/test_InternetSocket.cpp
  UNITTESTS/stubs/NetworkStack_stub.h
  features/netsocket/InternetSocket.cpp
  features/netsocket/InternetSocket.h
  features/netsocket/Socket.h
  features/netsocket/TLSSocketWrapper.cpp
  features/netsocket/TLSSocketWrapper.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/flash_api.c
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_NUMAKER_PFM_M2351/TARGET_M23_NS/NuMaker-mbed-TZ-secure-example.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_NUMAKER_PFM_M2351/TARGET_M23_NS/cmse_lib.o
  targets/TARGET_NUVOTON/TARGET_M2351/flash_api.c
  targets/targets.json
Labels: ready for merge

#8692 fix a bug in the FVP platform where flash API page size was wrong
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/flash_api.c
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8717 Format targets.json to put the items of large lists on their own line
  targets/targets.json
Labels: Priority-High, needs: CI, release-version: 5.10.4, rollup PR

#7755 Add USB CDC and Serial tests
  TESTS/host_tests/usb_device_serial.py
  TESTS/usb_device/serial/README.md
  TESTS/usb_device/serial/main.cpp
Labels: needs: CI, release-version: feature branch

#8680 Add PSA build components to build configuration for non-PSA targets
  targets/targets.json
Labels: ready for merge, release-version: 5.11.0-rc1

#7309 New target UNO_91H from RDA Microelectronics.
  platform/mbed_lib.json
  targets/TARGET_RDA/TARGET_UNO_91H/PeripheralNames.h
  targets/TARGET_RDA/TARGET_UNO_91H/PinNames.h
  targets/TARGET_RDA/TARGET_UNO_91H/PortNames.h
  targets/TARGET_RDA/TARGET_UNO_91H/analogin_api.c
  targets/TARGET_RDA/TARGET_UNO_91H/device.h
  targets/TARGET_RDA/TARGET_UNO_91H/device/RDA5981_nvic_virtual.h
  targets/TARGET_RDA/TARGET_UNO_91H/device/RDA5991H.h
  targets/TARGET_RDA/TARGET_UNO_91H/device/TOOLCHAIN_ARM_STD/TARGET_UNO_91H/RDA5981C.sct
  targets/TARGET_RDA/TARGET_UNO_91H/device/TOOLCHAIN_ARM_STD/startup_RDA5991H.S
  targets/TARGET_RDA/TARGET_UNO_91H/device/TOOLCHAIN_ARM_STD/sys.cpp
  targets/TARGET_RDA/TARGET_UNO_91H/device/TOOLCHAIN_GCC_ARM/TARGET_UNO_91H/RDA5981C.ld
  targets/TARGET_RDA/TARGET_UNO_91H/device/TOOLCHAIN_GCC_ARM/TARGET_UNO_91H/startup_RDA5981C.S
  targets/TARGET_RDA/TARGET_UNO_91H/device/TOOLCHAIN_GCC_ARM/rda_retarget.c
  targets/TARGET_RDA/TARGET_UNO_91H/device/TOOLCHAIN_IAR/TARGET_UNO_91H/RDA5981C.icf
  targets/TARGET_RDA/TARGET_UNO_91H/device/TOOLCHAIN_IAR/startup_RDA5991H.S
  targets/TARGET_RDA/TARGET_UNO_91H/device/cmsis.h
  targets/TARGET_RDA/TARGET_UNO_91H/device/cmsis_nvic.h
  targets/TARGET_RDA/TARGET_UNO_91H/device/system_RDA5991H.c
  targets/TARGET_RDA/TARGET_UNO_91H/device/system_RDA5991H.h
  targets/TARGET_RDA/TARGET_UNO_91H/flash_api.c
  targets/TARGET_RDA/TARGET_UNO_91H/gpio_api.c
  targets/TARGET_RDA/TARGET_UNO_91H/gpio_irq_api.c
  targets/TARGET_RDA/TARGET_UNO_91H/gpio_object.h
  targets/TARGET_RDA/TARGET_UNO_91H/lib/LICENSE-permissive-binary-license-1.0.txt
  targets/TARGET_RDA/TARGET_UNO_91H/lib/README.md
  targets/TARGET_RDA/TARGET_UNO_91H/lib/TOOLCHAIN_ARM_STD/libhal.ar
  targets/TARGET_RDA/TARGET_UNO_91H/lib/TOOLCHAIN_GCC_ARM/libhal.a
  targets/TARGET_RDA/TARGET_UNO_91H/lib/TOOLCHAIN_IAR/libhal.a
  targets/TARGET_RDA/TARGET_UNO_91H/mbed_overrides.c
  targets/TARGET_RDA/TARGET_UNO_91H/objects.h
  targets/TARGET_RDA/TARGET_UNO_91H/pinmap.c
  targets/TARGET_RDA/TARGET_UNO_91H/port_api.c
  targets/TARGET_RDA/TARGET_UNO_91H/pwmout_api.c
  targets/TARGET_RDA/TARGET_UNO_91H/rda_ccfg_api.h
  targets/TARGET_RDA/TARGET_UNO_91H/rda_timer_isr.c
  targets/TARGET_RDA/TARGET_UNO_91H/serial_api.c
  targets/TARGET_RDA/TARGET_UNO_91H/sleep.c
  targets/TARGET_RDA/TARGET_UNO_91H/spi_api.c
  targets/TARGET_RDA/TARGET_UNO_91H/trng_api.c
  targets/TARGET_RDA/TARGET_UNO_91H/us_ticker.c
  targets/TARGET_RDA/mbed_rtx.h
  targets/targets.json
Labels: Priority-High, component: tls, needs: CI, release-version: 5.10.4, rollup PR, scope: new-target, tracking

#8697 Resources: Use path names for ignored dirs
  tools/resources/__init__.py
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8701 [Wio 3G] Added default I/F type and pin defs
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/PinNames.h
  targets/targets.json
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8712 ONME-3852 Check that test cases disconnect at the end
  TESTS/network/wifi/wifi_connect_nocredentials.cpp
  TESTS/network/wifi/wifi_connect_params_channel.cpp
  TESTS/network/wifi/wifi_connect_params_null.cpp
  TESTS/network/wifi/wifi_connect_params_valid_secure.cpp
  TESTS/network/wifi/wifi_connect_secure.cpp
  TESTS/network/wifi/wifi_connect_secure_fail.cpp
  TESTS/network/wifi/wifi_get_rssi.cpp
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8727 LoRaWANTimer UT fixed
  UNITTESTS/features/lorawan/lorawantimer/unittest.cmake
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8729 Adding arch option instead MCPU for no dsp and no fpu support
  tools/toolchains/gcc.py
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8734 Patch whitespace inconsistencies in platform lib file
  platform/mbed_lib.json
Labels: needs: CI, release-version: 5.10.4, rollup PR

#8646 Add a Unity macro to assert on platform error code difference
  features/frameworks/unity/unity/unity.h
Labels: needs: CI, release-version: 5.11.0-rc1, rollup PR: B

#8703 Improve the efficiency of BufferedBlockDevice
  features/storage/TESTS/blockdevice/buffered_block_device/main.cpp
  features/storage/blockdevice/BufferedBlockDevice.cpp
  features/storage/blockdevice/BufferedBlockDevice.h
Labels: needs: CI, release-version: 5.11.0-rc1, rollup PR: B

#8735 Compliance test errors fixed
  UNITTESTS/features/lorawan/loramac/Test_LoRaMac.cpp
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/system/lorawan_data_structures.h
Labels: needs: CI, release-version: 5.10.4, rollup PR: B

#8668 Enable Fast Models emac drivers
  features/lwipstack/mbed_lib.json
  features/netsocket/emac-drivers/TARGET_ARM_FM/COMPONENT_LAN91C111/fvp_emac.cpp
  features/netsocket/emac-drivers/TARGET_ARM_FM/COMPONENT_LAN91C111/fvp_emac.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/drivers/lan91c111.c
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/drivers/lan91c111.h
  targets/targets.json
Labels: ready for merge, release-version: 5.11.0-rc1

#8782 Fix traceback when running mbed test
  tools/config/__init__.py
Labels: G, ready for merge, release-version: 5.11.0-rc1

#8673 Add Mbed Configuration Option Range Limits
  tools/config/__init__.py
  tools/test/config/range_limits/lib1/mbed_lib.json
  tools/test/config/range_limits/targets.json
  tools/test/config/range_limits/test_data.json
  tools/test/config/range_limits_invalid/lib1/mbed_lib.json
  tools/test/config/range_limits_invalid/targets.json
  tools/test/config/range_limits_invalid/test_data.json
  tools/test/config/range_limits_override_invalid/lib1/mbed_lib.json
  tools/test/config/range_limits_override_invalid/mbed_app.json
  tools/test/config/range_limits_override_invalid/targets.json
  tools/test/config/range_limits_override_invalid/test_data.json
Labels: G, ready for merge, release-version: 5.11.0-rc1

#8671 Feature: Add non-blocking serial break/unbreak functions
  drivers/SerialBase.cpp
  drivers/SerialBase.h
Labels: G, ready for merge, release-version: 5.11.0-rc1

#8826 Revert "Merge pull request #8272 from NXPmicro/Ensure_RTC_OSC_Start"
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/TARGET_UBRIDGE/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/TARGET_USENSE/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/TARGET_MCU_K22F512/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/TARGET_RO359B/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_HEXIWEAR/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_MTS_GAMBIT/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/mbed_overrides.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/lp_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/rtc_api.c
Labels: Priority-High, ready for merge, release-version: 5.11.0-rc1

#8561 Design document for Crash Reporting feature in MbedOS
  docs/design-documents/platform/crash-reporting/crash_reporting.md
  docs/design-documents/platform/crash-reporting/diagrams/boot-error-report.jpg
  docs/design-documents/platform/crash-reporting/diagrams/boot-error-report.xml
  docs/design-documents/platform/crash-reporting/diagrams/crash-report-region.jpg
  docs/design-documents/platform/crash-reporting/diagrams/crash-report-region.xml
  docs/design-documents/platform/crash-reporting/diagrams/crash-report-seq.jpg
  docs/design-documents/platform/crash-reporting/diagrams/crash-report-seq.xml
Labels: ready for merge, release-version: 5.11.0-rc1

#8743 Add design document for network statistics.
  docs/design-documents/statistics/network_stats.md
Labels: ready for merge, release-version: 5.11.0-rc1

#8778 STM32 LPTICKER with LPTIM : reduce clock feature
  targets/TARGET_STM/lp_ticker.c
  targets/targets.json
Labels: G, ready for merge, release-version: 5.11.0-rc1

#8689 Add ESP8266 driver v1.7
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
  components/wifi/esp8266-driver/README.md
  components/wifi/esp8266-driver/mbed_lib.json
  components/wifi/esp8266-driver/nucleo_esp8266_hw_fc1.jpg
  components/wifi/esp8266-driver/nucleo_esp8266_hw_fc2.jpg
Labels: BREAKING-CHANGE, G, ready for merge, release-version: 5.11.0-rc1

#8607 Fetch ram/rom start/size
  TESTS/mbed_platform/stats_sys/main.cpp
  platform/mbed_stats.c
  platform/mbed_stats.h
  tools/config/__init__.py
  tools/toolchains/__init__.py
Labels: G, release-version: 5.11.0-rc1, rollup PR

#8189 Wait API updated to remove deepsleep lock
  platform/mbed_wait_api.h
  platform/mbed_wait_api_rtos.cpp
Labels: A, Priority-High, ready for merge, release-version: 5.11.0-rc1

#8342 Icetea missing test doc
  TEST_APPS/testcases/README.md
  TEST_APPS/testcases/example/README.md
  TEST_APPS/testcases/nanostack_mac_tester/ED_scan.py
  TEST_APPS/testcases/nanostack_mac_tester/README.md
  TEST_APPS/testcases/nanostack_mac_tester/address_read_and_write.py
  TEST_APPS/testcases/nanostack_mac_tester/create_and_join_PAN.py
  TEST_APPS/testcases/nanostack_mac_tester/send_data.py
  TEST_APPS/testcases/nanostack_mac_tester/send_data_indirect.py
  TEST_APPS/testcases/nanostack_mac_tester/send_large_payloads.py
  TEST_APPS/testcases/netsocket/README.md
Labels: ready for merge, release-version: 5.11.0-rc1

#8784 NRF52 serial fixes
  targets/TARGET_NORDIC/TARGET_NRF5x/README.md
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
Labels: ready for merge, release-version: 5.11.0-rc1

#8756 Adding Murata WSM-BL241 as new target
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_MTB_MURATA_WSM_BL241/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_MTB_MURATA_WSM_BL241/device.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/mbed_lib.json
  targets/targets.json
Labels: G, ready for merge, release-version: 5.11.0-rc1, scope: new-target

#8766 Fix cellular backward compatibility
  features/netsocket/cellular/generic_modem_driver/OnboardCellularInterface.h
Labels: Priority-High, ready for merge, release-version: 5.11.0-rc1

#8814 Cellular: unified return value comments on API folder.
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/API/CellularInformation.h
Labels: ready for merge, release-version: 5.11.0-rc1

#8803 Compatibilize ArmC6 with ArmC5-built archives
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge, release-version: 5.11.0-rc1

#8737 Add low power implementations for CM3DS
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/device_cfg.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/dualtimer_cmsdk_drv.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/dualtimer_cmsdk_drv.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/rtc_pl031_drv.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/rtc_pl031_drv.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/platform_devices.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/platform_devices.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/lp_ticker.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/rtc_api.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/sleep_api.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/us_ticker.c
  targets/targets.json
Labels: A, ready for merge, release-version: 5.11.0-rc1

#8740 Add block device test for small data sizes
  features/storage/TESTS/blockdevice/general_block_device/main.cpp
Labels: needs: CI, release-version: 5.11.0-rc1, rollup PR

#8750 realtek-rtl8195am-wifi-headerfile-updates
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/api/wifi/wifi_ind.h
Labels: G, needs: CI, release-version: 5.11.0-rc1, rollup PR

#8767 Cellular: Update cellular debug prints
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
Labels: needs: CI, release-version: 5.11.0-rc1, rollup PR

#8780 Greentea netsocket and network tests improvements
  TESTS/netsocket/dns/asynchronous_dns_non_async_and_async.cpp
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tcp/tcpsocket_recv_timeout.cpp
  TESTS/network/interface/networkinterface_status.cpp
Labels: needs: CI, rollup PR

#8794 Deprecate TCP/UDPSocket open-calling constructors
  UNITTESTS/features/netsocket/TCPSocket/test_TCPSocket.cpp
  features/netsocket/TCPSocket.h
  features/netsocket/TLSSocket.h
  features/netsocket/UDPSocket.h
Labels: needs: CI, release-version: 5.11.0-rc1, rollup PR

#8837 Update mbed-coap to version 4.7.2
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/module.json
  features/frameworks/mbed-coap/source/sn_coap_builder.c
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: Priority-High, needs: CI, release-version: 5.11.0-rc1, rollup PR

#8719 M2351 RAM / ROM defines updated
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_ARM_MICRO/M2351.sct
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_ARM_STD/M2351.sct
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_GCC_ARM/M2351.ld
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_IAR/M2351.icf
  targets/TARGET_NUVOTON/TARGET_M2351/device/partition_M2351.h
  targets/TARGET_NUVOTON/TARGET_M2351/flash_api.c
  targets/targets.json
Labels: A, ready for merge, release-version: 5.11.0-rc1

#8643 Modify HW accelerator drivers to new error code
  features/cryptocell/FEATURE_CRYPTOCELL310/cc_internal.c
  features/cryptocell/FEATURE_CRYPTOCELL310/cc_internal.h
  features/cryptocell/FEATURE_CRYPTOCELL310/ccm_alt.c
  features/cryptocell/FEATURE_CRYPTOCELL310/ecdh_alt.c
  features/cryptocell/FEATURE_CRYPTOCELL310/ecdsa_alt.c
  features/cryptocell/FEATURE_CRYPTOCELL310/sha1_alt.c
  features/cryptocell/FEATURE_CRYPTOCELL310/sha256_alt.c
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/ecp/ecp_internal_alt.c
  features/mbedtls/targets/TARGET_STM/aes_alt.c
  features/mbedtls/targets/TARGET_STM/md5_alt.c
  features/mbedtls/targets/TARGET_STM/sha1_alt.c
  features/mbedtls/targets/TARGET_STM/sha256_alt.c
  features/mbedtls/targets/TARGET_Silicon_Labs/aes_aes.c
  features/mbedtls/targets/TARGET_Silicon_Labs/crypto_ecp.c
Labels: A, ready for merge, release-version: 5.11.0-rc1

#8851 Change error code from NSAPI_ERROR_PARAMETER to NSAPI_ERROR_NO_CONNEC…
  features/lwipstack/LWIPInterface.cpp
Labels: ready for merge, release-version: 5.11.0-rc1

#8846 Update the Watchdog & Reset_reason host test scripts
  TESTS/host_tests/reset_reason.py
  TESTS/host_tests/sync_on_reset.py
  TESTS/host_tests/watchdog_reset.py
Labels: ready for merge, release-version: 5.11.0-rc1

#8730 Add a new PSA Internal Trusted Storage APIs
  TESTS/psa/prot_internal_storage/its_reset/COMPONENT_PSA_SRV_EMUL/test_pits.c
  TESTS/psa/prot_internal_storage/its_reset/COMPONENT_PSA_SRV_IMPL/test_pits_impl.cpp
  TESTS/psa/prot_internal_storage/its_reset/COMPONENT_PSA_SRV_IMPL/test_pits_impl.h
  TESTS/psa/prot_internal_storage/its_reset/test_pits.h
  TESTS/psa/prot_internal_storage/main.cpp
  components/TARGET_PSA/services/psa_prot_internal_storage/COMPONENT_PSA_SRV_EMUL/psa_prot_internal_storage.cpp
  components/TARGET_PSA/services/psa_prot_internal_storage/COMPONENT_PSA_SRV_IMPL/pits_impl.cpp
  components/TARGET_PSA/services/psa_prot_internal_storage/COMPONENT_PSA_SRV_IMPL/pits_impl.h
  components/TARGET_PSA/services/psa_prot_internal_storage/psa_prot_internal_storage.h
  features/storage/kvstore/conf/mbed_lib.json
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
  targets/targets.json
Labels: ready for merge, release-version: 5.11.0-rc1

#8790 Cellular: Fix ATHandler URC processing
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
Labels: ready for merge, release-version: 5.11.0-rc1

#8848 Add reset_reason feature for TMPM3HQ
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/reset_reason_api.c
  targets/targets.json
Labels: needs: review

#8708 [Wio BG96] Adding platform HAL
  features/cellular/framework/common/CellularTargets.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_BG96/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_BG96/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_BG96/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_BG96/onboard_modem_api.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_BG96/system_clock.c
  targets/targets.json
Labels: needs: review, release-version: 5.11.1, scope: new-target

#8592 Network Socket Statistics
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tcp/tcpsocket_open_close_repeat.cpp
  TESTS/netsocket/tcp/tcpsocket_open_limit.cpp
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udp_tests.h
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_open_close_repeat.cpp
  TESTS/netsocket/udp/udpsocket_open_limit.cpp
  UNITTESTS/features/netsocket/DTLSSocket/unittest.cmake
  UNITTESTS/features/netsocket/DTLSSocketWrapper/unittest.cmake
  UNITTESTS/features/netsocket/EthernetInterface/unittest.cmake
  UNITTESTS/features/netsocket/InternetSocket/unittest.cmake
  UNITTESTS/features/netsocket/NetworkInterface/unittest.cmake
  UNITTESTS/features/netsocket/NetworkStack/unittest.cmake
  UNITTESTS/features/netsocket/TCPServer/unittest.cmake
  UNITTESTS/features/netsocket/TCPSocket/unittest.cmake
  UNITTESTS/features/netsocket/TLSSocket/unittest.cmake
  UNITTESTS/features/netsocket/TLSSocketWrapper/unittest.cmake
  UNITTESTS/features/netsocket/UDPSocket/unittest.cmake
  UNITTESTS/stubs/SocketStats_Stub.cpp
  features/lwipstack/LWIPStack.h
  features/netsocket/InternetSocket.cpp
  features/netsocket/InternetSocket.h
  features/netsocket/SocketStats.cpp
  features/netsocket/SocketStats.h
  features/netsocket/TCPServer.cpp
  features/netsocket/TCPSocket.cpp
  features/netsocket/UDPSocket.cpp
  features/netsocket/mbed_lib.json
  platform/SingletonPtr.h
  platform/mbed_error.h
  tools/test_configs/target_configs.json
Labels: Priority-High, ready for merge, release-version: 5.11.0-rc1, risk: G

#7760 Give an option to remove 'using namespace'
  components/storage/blockdevice/COMPONENT_DATAFLASH/DataFlashBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_DATAFLASH/DataFlashBlockDevice.h
  components/storage/blockdevice/COMPONENT_FLASHIAP/FlashIAPBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_FLASHIAP/FlashIAPBlockDevice.h
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.h
  components/storage/blockdevice/COMPONENT_RSPIF/SPIFReducedBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_RSPIF/SPIFReducedBlockDevice.h
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.h
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.h
  events/mbed_events.h
  features/storage/blockdevice/BlockDevice.h
  features/storage/blockdevice/BufferedBlockDevice.cpp
  features/storage/blockdevice/BufferedBlockDevice.h
  features/storage/blockdevice/ChainingBlockDevice.cpp
  features/storage/blockdevice/ChainingBlockDevice.h
  features/storage/blockdevice/ExhaustibleBlockDevice.cpp
  features/storage/blockdevice/ExhaustibleBlockDevice.h
  features/storage/blockdevice/FlashSimBlockDevice.cpp
  features/storage/blockdevice/FlashSimBlockDevice.h
  features/storage/blockdevice/HeapBlockDevice.cpp
  features/storage/blockdevice/HeapBlockDevice.h
  features/storage/blockdevice/MBRBlockDevice.cpp
  features/storage/blockdevice/MBRBlockDevice.h
  features/storage/blockdevice/ObservingBlockDevice.cpp
  features/storage/blockdevice/ObservingBlockDevice.h
  features/storage/blockdevice/ProfilingBlockDevice.cpp
  features/storage/blockdevice/ProfilingBlockDevice.h
  features/storage/blockdevice/ReadOnlyBlockDevice.cpp
  features/storage/blockdevice/ReadOnlyBlockDevice.h
  features/storage/blockdevice/SlicingBlockDevice.cpp
  features/storage/blockdevice/SlicingBlockDevice.h
  features/storage/filesystem/fat/FATFileSystem.cpp
  features/storage/filesystem/fat/FATFileSystem.h
  features/storage/filesystem/littlefs/LittleFileSystem.cpp
  features/storage/filesystem/littlefs/LittleFileSystem.h
  features/storage/filesystem/mbed_filesystem.h
  mbed.h
  platform/FileSystemHandle.cpp
  platform/FileSystemHandle.h
  rtos/Mail.h
  rtos/rtos.h
Labels: ready for merge, release-version: 5.11.0-rc1, risk: G

#8761 Add MBED_ALL_STATS_ENABLED to config system
  platform/mbed_lib.json
  platform/mbed_stats.h
Labels: Priority-High, ready for merge, release-version: 5.11.0-rc1, risk: G

#8840 Fix build of library archive with Arm Compiler 6
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.11.0-rc1, risk: G

#8704 Fix issues in Cryptocell 310 ccm_alt discovered by On Target Testing
  features/cryptocell/FEATURE_CRYPTOCELL310/ccm_alt.c
  features/cryptocell/FEATURE_CRYPTOCELL310/ccm_alt.h
Labels: ready for merge, release-version: 5.11.0-rc1, risk: G

#8738 Ble extended advertising
  features/FEATURE_BLE/ble/BLE.h
  features/FEATURE_BLE/ble/BLEInstanceBase.h
  features/FEATURE_BLE/ble/BLETypes.h
  features/FEATURE_BLE/ble/DiscoveredCharacteristic.h
  features/FEATURE_BLE/ble/DiscoveredCharacteristicDescriptor.h
  features/FEATURE_BLE/ble/Gap.h
  features/FEATURE_BLE/ble/GapAdvertisingData.h
  features/FEATURE_BLE/ble/GattCharacteristic.h
  features/FEATURE_BLE/ble/GattClient.h
  features/FEATURE_BLE/ble/GattServer.h
  features/FEATURE_BLE/ble/SafeEnum.h
  features/FEATURE_BLE/ble/SecurityManager.h
  features/FEATURE_BLE/ble/ServiceDiscovery.h
  features/FEATURE_BLE/ble/blecommon.h
  features/FEATURE_BLE/ble/common/Bounded.h
  features/FEATURE_BLE/ble/common/Duration.h
  features/FEATURE_BLE/ble/gap/AdvertisingDataBuilder.h
  features/FEATURE_BLE/ble/gap/AdvertisingDataParser.h
  features/FEATURE_BLE/ble/gap/AdvertisingDataSimpleBuilder.h
  features/FEATURE_BLE/ble/gap/AdvertisingDataTypes.h
  features/FEATURE_BLE/ble/gap/AdvertisingParameters.h
  features/FEATURE_BLE/ble/gap/ConnectionParameters.h
  features/FEATURE_BLE/ble/gap/Events.h
  features/FEATURE_BLE/ble/gap/Gap.h
  features/FEATURE_BLE/ble/gap/ScanParameters.h
  features/FEATURE_BLE/ble/gap/Types.h
  features/FEATURE_BLE/ble/generic/GenericGap.h
  features/FEATURE_BLE/ble/generic/GenericGattClient.h
  features/FEATURE_BLE/ble/generic/GenericSecurityManager.h
  features/FEATURE_BLE/ble/pal/Deprecated.h
  features/FEATURE_BLE/ble/pal/GapEvents.h
  features/FEATURE_BLE/ble/pal/GapTypes.h
  features/FEATURE_BLE/ble/pal/PalGap.h
  features/FEATURE_BLE/ble/services/URIBeaconConfigService.h
  features/FEATURE_BLE/ble/services/iBeacon.h
  features/FEATURE_BLE/source/BLE.cpp
  features/FEATURE_BLE/source/Gap.cpp
  features/FEATURE_BLE/source/LegacyGap.cpp
  features/FEATURE_BLE/source/gap/AdvertisingDataBuilder.cpp
  features/FEATURE_BLE/source/gap/AdvertisingParameters.cpp
  features/FEATURE_BLE/source/gap/ConnectionParameters.cpp
  features/FEATURE_BLE/source/gap/Gap.cpp
  features/FEATURE_BLE/source/generic/GenericGap.cpp
  features/FEATURE_BLE/source/generic/GenericGattClient.cpp
  features/FEATURE_BLE/source/generic/GenericSecurityManager.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioGattServer.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioPalGap.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioBLE.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalGap.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalSecurityManager.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/nRF5xGap.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/nRF5xPalSecurityManager.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/nRF5xPalSecurityManager.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xGap.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xPalSecurityManager.cpp
  platform/mbed_error.h
Labels: Priority-High, ready for merge, release-version: 5.11.0-rc1, risk: A

#8863 Adding KVStore Examples for Global API
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.11.0-rc1

#8895 Add crash-reporting example to examples.json
  tools/test/examples/examples.json
Labels: needs: CI, release-version: 5.11.0-rc1, risk: A

#8896 Update Statistics examples in example test json
  tools/test/examples/examples.json
Labels: needs: CI, release-version: 5.11.0-rc1, risk: A

#8897 Add TLS Sockets example to examples.json
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.11.0-rc1, risk: G

#8898 Add crypto example to examples.json
  tools/test/examples/examples.json
Labels: needs: CI, release-version: 5.11.0-rc1, risk: R

#8788 Fix unsigned packing bug in merge_regions #8544
  tools/build_api.py
Labels: ready for merge, release-version: 5.11.1

#8835 Moving some examples testing from K64F to K66F
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.11.1

#8915 Revert "Merge pull request #8788 from kaidokert/master"
  tools/build_api.py
Labels: ready for merge

#8771 STM32 LPTICKER with LPTIM optimisation
  targets/TARGET_STM/lp_ticker.c
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1

#8795 cellular: registration status change fix
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/ATHandler_stub.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: ready for merge, release-version: 5.11.1

#8754 Mbed Crypto Tests
  TESTS/mbed-crypto/sanity/main.cpp
Labels: ready for merge, release-version: 5.11.1

#8779 Migrate old memap file handling into toolchains
  tools/memap.py
  tools/toolchains/__init__.py
Labels: ready for merge, release-version: 5.11.1

#8796 nanostack-mac-tester sync with v1.0.0
  TEST_APPS/device/nanostack_mac_tester/source/mac_commands.cpp
  TEST_APPS/device/nanostack_mac_tester/source/mac_commands.h
  TEST_APPS/device/nanostack_mac_tester/source/mac_tester_util.cpp
  TEST_APPS/device/nanostack_mac_tester/source/mac_tester_util.h
  TEST_APPS/testcases/nanostack_mac_tester/ED_scan.py
  TEST_APPS/testcases/nanostack_mac_tester/address_read_and_write.py
  TEST_APPS/testcases/nanostack_mac_tester/create_and_join_PAN.py
  TEST_APPS/testcases/nanostack_mac_tester/send_data.py
  TEST_APPS/testcases/nanostack_mac_tester/send_data_indirect.py
  TEST_APPS/testcases/nanostack_mac_tester/send_large_payloads.py
Labels: ready for merge, release-version: 5.11.1

#8797 Fix issues in Cryptocell 310 cc_internal discovered by On Target Testing
  features/cryptocell/FEATURE_CRYPTOCELL310/cc_internal.c
Labels: ready for merge, release-version: 5.11.1

#8798 STM32 : Add default deep sleep latency of 3ms
  targets/targets.json
Labels: ready for merge, release-version: 5.11.1

#8817 Correct network status callbacks with ethernet and nanostack
  features/nanostack/mbed-mesh-api/source/NanostackEMACInterface.cpp
  features/nanostack/mbed-mesh-api/source/ethernet_tasklet.c
  features/nanostack/mbed-mesh-api/source/include/enet_tasklet.h
  features/nanostack/mbed-mesh-api/source/include/mesh_system.h
Labels: ready for merge, release-version: 5.11.1

#8827 TARGET_MCUXpresso_MCUS: fix lp ticker init function
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/lp_ticker.c
Labels: ready for merge, release-version: 5.11.1
