Repository ARMmbed/mbed-os, pull requests merged in 2018-08, with the labels that each got.

#7658 Add default interface for wiced WiFi.
  targets/TARGET_WICED/README.md
  targets/TARGET_WICED/wiced_interface/default_wifi_interface.cpp
Labels: ready for merge, release-version: 5.9.5

#7655 Remove device emac check from emac greentea tests
  TESTS/network/emac/main.cpp
Labels: ready for merge, release-version: 5.9.5

#7642 Changing default SPI CS pin to SD card on MTB
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_MTB_MXCHIP_EMW3166/PinNames.h
Labels: ready for merge, release-version: 5.9.5

#7620 Lora: Fix cancel_sending
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
Labels: ready for merge, release-version: 5.9.5

#7552 Renesas: Add LPTICKER
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/PeripheralPins.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/os_tick_ostm.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/mbed_drv_cfg.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/PeripheralPins.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/mbed_drv_cfg.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/lp_ticker.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/mtu2.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/mtu2.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/pwmout_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.9.5

#7465 Skip a few tests if not enough memory can be allocated for them
  TESTS/mbed_platform/error_handling/main.cpp
  features/TESTS/filesystem/buffered_block_device/main.cpp
  features/TESTS/filesystem/heap_block_device/main.cpp
  features/TESTS/filesystem/mbr_block_device/main.cpp
  features/TESTS/filesystem/util_block_device/main.cpp
Labels: ready for merge, release-version: 5.9.5

#7648 Add init reference count to all block devices
  features/TESTS/filesystem/util_block_device/main.cpp
  features/filesystem/bd/BufferedBlockDevice.cpp
  features/filesystem/bd/BufferedBlockDevice.h
  features/filesystem/bd/ChainingBlockDevice.cpp
  features/filesystem/bd/ChainingBlockDevice.h
  features/filesystem/bd/ExhaustibleBlockDevice.cpp
  features/filesystem/bd/ExhaustibleBlockDevice.h
  features/filesystem/bd/FlashSimBlockDevice.cpp
  features/filesystem/bd/FlashSimBlockDevice.h
  features/filesystem/bd/HeapBlockDevice.cpp
  features/filesystem/bd/HeapBlockDevice.h
  features/filesystem/bd/MBRBlockDevice.cpp
  features/filesystem/bd/MBRBlockDevice.h
Labels: ready for merge, release-version: 5.9.5

#7664 fix comment copy/paste error
  rtos/Queue.h
Labels: ready for merge, release-version: 5.9.5

#7646 Tools: Fix incrimental compile dep tracking
  tools/config/__init__.py
  tools/toolchains/__init__.py
Labels: ready for merge, release-version: 5.9.5

#7623 Tools: Omit include path parents when they're scan rules
  tools/resources/__init__.py
Labels: needs: work, release-version: 5.9.5

#7661 Clear CONN_IN_PROGRESS flag after incomplete connect()
  features/lorawan/LoRaWANStack.cpp
Labels: needs: CI, release-version: 5.9.5

#7668 STM32F7: remove HAL_InitTick() declaration in us_ticker_data.h files
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/device/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/us_ticker_data.h
Labels: needs: CI, release-version: 5.9.5

#7374 Cellular: fix greentea tests C027 and BG96
  features/cellular/TESTS/api/cellular_network/main.cpp
  features/cellular/TESTS/api/cellular_power/main.cpp
  features/cellular/TESTS/api/cellular_sim/main.cpp
Labels: ready for merge, release-version: 5.9.5

#7495 LoRaWAN: Reporting scheduling failures
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7564 Cellular: Make ATHandler::cmd_start() virtual
  features/cellular/framework/AT/ATHandler.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7675 Renesas : Improve Flash iap
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/mbed_drv_cfg.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/mbed_drv_cfg.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/flash_api.c
Labels: ready for merge, release-version: 5.9.5

#7676 Nuvoton: Organize file structure
  targets/TARGET_NUVOTON/TARGET_M2351/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_M2351/PeripheralPins.c
  targets/TARGET_NUVOTON/TARGET_M2351/PeripheralPins.h
  targets/TARGET_NUVOTON/TARGET_M2351/PinNames.h
  targets/TARGET_NUVOTON/TARGET_M2351/PortNames.h
  targets/TARGET_NUVOTON/TARGET_M2351/device.h
  targets/TARGET_NUVOTON/TARGET_M2351/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_M2351/objects.h
  targets/TARGET_NUVOTON/TARGET_M451/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_M451/PeripheralPins.c
  targets/TARGET_NUVOTON/TARGET_M451/PeripheralPins.h
  targets/TARGET_NUVOTON/TARGET_M451/PinNames.h
  targets/TARGET_NUVOTON/TARGET_M451/PortNames.h
  targets/TARGET_NUVOTON/TARGET_M451/device.h
  targets/TARGET_NUVOTON/TARGET_M451/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_M451/objects.h
  targets/TARGET_NUVOTON/TARGET_M480/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_M480/PeripheralPins.c
  targets/TARGET_NUVOTON/TARGET_M480/PeripheralPins.h
  targets/TARGET_NUVOTON/TARGET_M480/PinNames.h
  targets/TARGET_NUVOTON/TARGET_M480/PortNames.h
  targets/TARGET_NUVOTON/TARGET_M480/device.h
  targets/TARGET_NUVOTON/TARGET_M480/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_M480/objects.h
  targets/TARGET_NUVOTON/TARGET_NANO100/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_NANO100/PeripheralPins.c
  targets/TARGET_NUVOTON/TARGET_NANO100/PeripheralPins.h
  targets/TARGET_NUVOTON/TARGET_NANO100/PinNames.h
  targets/TARGET_NUVOTON/TARGET_NANO100/PortNames.h
  targets/TARGET_NUVOTON/TARGET_NANO100/device.h
  targets/TARGET_NUVOTON/TARGET_NANO100/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_NANO100/objects.h
  targets/TARGET_NUVOTON/TARGET_NUC472/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_NUC472/PeripheralPins.c
  targets/TARGET_NUVOTON/TARGET_NUC472/PeripheralPins.h
  targets/TARGET_NUVOTON/TARGET_NUC472/PinNames.h
  targets/TARGET_NUVOTON/TARGET_NUC472/PortNames.h
  targets/TARGET_NUVOTON/TARGET_NUC472/device.h
  targets/TARGET_NUVOTON/TARGET_NUC472/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_NUC472/objects.h
Labels: ready for merge, release-version: 5.9.5

#7660 Remove inclusion of mbed.h and mbed namespace from filesystem code
  features/filesystem/Dir.cpp
  features/filesystem/File.cpp
  features/filesystem/FileSystem.cpp
  features/filesystem/fat/FATFileSystem.cpp
  features/filesystem/fat/FATFileSystem.h
  features/filesystem/littlefs/LittleFileSystem.cpp
Labels: ready for merge, release-version: 5.9.5

#7383 FlashIAP: Add timing test
  TESTS/mbed_drivers/flashiap/main.cpp
Labels: needs: CI, release-version: 5.9.5

#7687 BLE: set correct default privacy configuration for centrals
  features/FEATURE_BLE/source/Gap.cpp
Labels: ready for merge, release-version: 5.9.5

#7689 PR template: fix target update list
  .github/pull_request_template.md
Labels: ready for merge, release-version: 5.9.5

#7601 LoRaWAN: Reduced priority for automatic uplinks & higher data rate usage for connection establishment
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYAS923.cpp
  features/lorawan/mbed_lib.json
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7643 STM32: remove uart force_reset at init
  targets/TARGET_STM/serial_api.c
Labels: ready for merge

#7692 netsocket: astyle fix
  features/netsocket/CellularBase.h
  features/netsocket/DNS.h
  features/netsocket/EMACInterface.cpp
  features/netsocket/EMACInterface.h
  features/netsocket/EthInterface.h
  features/netsocket/EthernetInterface.h
  features/netsocket/InternetSocket.cpp
  features/netsocket/InternetSocket.h
  features/netsocket/MeshInterface.h
  features/netsocket/NetworkInterface.h
  features/netsocket/NetworkStack.cpp
  features/netsocket/NetworkStack.h
  features/netsocket/OnboardNetworkStack.h
  features/netsocket/Socket.h
  features/netsocket/SocketAddress.cpp
  features/netsocket/SocketAddress.h
  features/netsocket/TCPServer.h
  features/netsocket/TCPSocket.h
  features/netsocket/UDPSocket.cpp
  features/netsocket/UDPSocket.h
  features/netsocket/WiFiAccessPoint.h
  features/netsocket/WiFiInterface.h
  features/netsocket/nsapi_dns.cpp
  features/netsocket/nsapi_dns.h
  features/netsocket/nsapi_ppp.h
  features/netsocket/nsapi_types.h
Labels: ready for merge, release-version: 5.9.5

#7703 Resolve us_ticker.c api discrepancy between EV_COG_AD4050LZ and EV_COG_AD3029LZ
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/api/us_ticker.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/bsp/config/adi_tmr_config.h
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/bsp/drivers/tmr/adi_tmr.h
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/bsp/tmr/adi_tmr.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/bsp/tmr/adi_tmr_data.c
Labels: ready for merge, release-version: 5.9.5

#7705 FlashIAP: Add a ROM end macro
  drivers/FlashIAP.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7678 Nanostack: fix error code
  features/nanostack/nanostack-interface/Nanostack.cpp
Labels: ready for merge, release-version: 5.9.5

#7691 events: astyle fix
  events/Event.h
  events/EventQueue.cpp
  events/EventQueue.h
Labels: ready for merge, release-version: 5.9.5

#7419 MIMXRT1050EVK: Fix Sleep support
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/sleep.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/lpm.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/lpm.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/mbed_overrides.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_ARM_STD/MIMXRT1052xxxxx.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_GCC_ARM/MIMXRT1052xxxxx.ld
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_IAR/MIMXRT1052xxxxx.icf
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_common.h
  targets/targets.json
Labels: ready for merge, release-version: 5.9.5

#7531 Cellular: sms greentea tests
  features/cellular/TESTS/api/cellular_sms/main.cpp
  features/cellular/framework/AT/AT_CellularSMS.cpp
Labels: ready for merge, release-version: 5.9.5

#7640 iar: remove nxp duplicate definitions
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.9.5

#7663 Move BlockDevice classes inside mbed namespace
  features/filesystem/FileSystem.h
  features/filesystem/bd/BlockDevice.h
  features/filesystem/bd/BufferedBlockDevice.cpp
  features/filesystem/bd/BufferedBlockDevice.h
  features/filesystem/bd/ChainingBlockDevice.cpp
  features/filesystem/bd/ChainingBlockDevice.h
  features/filesystem/bd/ExhaustibleBlockDevice.cpp
  features/filesystem/bd/ExhaustibleBlockDevice.h
  features/filesystem/bd/FlashSimBlockDevice.cpp
  features/filesystem/bd/FlashSimBlockDevice.h
  features/filesystem/bd/HeapBlockDevice.cpp
  features/filesystem/bd/HeapBlockDevice.h
  features/filesystem/bd/MBRBlockDevice.cpp
  features/filesystem/bd/MBRBlockDevice.h
  features/filesystem/bd/ObservingBlockDevice.cpp
  features/filesystem/bd/ObservingBlockDevice.h
  features/filesystem/bd/ProfilingBlockDevice.cpp
  features/filesystem/bd/ProfilingBlockDevice.h
  features/filesystem/bd/ReadOnlyBlockDevice.cpp
  features/filesystem/bd/ReadOnlyBlockDevice.h
  features/filesystem/bd/SlicingBlockDevice.cpp
  features/filesystem/bd/SlicingBlockDevice.h
  features/filesystem/fat/FATFileSystem.cpp
  features/filesystem/fat/FATFileSystem.h
  features/filesystem/littlefs/LittleFileSystem.cpp
  features/filesystem/littlefs/LittleFileSystem.h
  features/filesystem/mbed_filesystem.h
Labels: ready for merge, release-version: 5.9.5

#7721 Fix owner restoration and discard across nvstore init
  features/nvstore/source/nvstore.cpp
Labels: ready for merge, release-version: 5.9.5

#7688 BLE: call secure connections versions of ltk functions
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xPalSecurityManager.cpp
Labels: ready for merge, release-version: 5.9.5

#7717 STM32: check for UART ongoing transfers before entering deepsleep
  targets/TARGET_STM/TARGET_STM32F0/device.h
  targets/TARGET_STM/TARGET_STM32F1/device.h
  targets/TARGET_STM/TARGET_STM32F2/device.h
  targets/TARGET_STM/TARGET_STM32F3/device.h
  targets/TARGET_STM/TARGET_STM32F4/device.h
  targets/TARGET_STM/TARGET_STM32F7/device.h
  targets/TARGET_STM/TARGET_STM32L0/device.h
  targets/TARGET_STM/TARGET_STM32L1/device.h
  targets/TARGET_STM/TARGET_STM32L4/device.h
  targets/TARGET_STM/serial_api.c
  targets/TARGET_STM/sleep.c
Labels: ready for merge, release-version: 5.9.5

#7725 Update Lwip error calls to use new error codes and mbed_error call
  features/lwipstack/lwip-sys/arch/lwip_sys_arch.c
Labels: ready for merge, release-version: 5.9.5

#7731 Cellular: WISE_1570's system clock back to HSE_XTAL
  targets/targets.json
Labels: ready for merge, release-version: 5.9.5

#7727 CircularBuffer: volatile specifier removal
  platform/CircularBuffer.h
Labels: ready for merge, release-version: 5.9.5

#7722 Fix Microlib compatibility for -t ARM
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.9.5

#7729 Rename text region in ARM linker file for Renesas & Realtek boards
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/MBRZA1LU.sct
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/MBRZA1H.sct
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_ARM_STD/VKRZA1H.sct
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_RTL8195A/device/TOOLCHAIN_ARM_STD/rtl8195a.sct
Labels: ready for merge, release-version: 5.9.5

#7523 Add bootloader configuration parameters for MAX32625PICO
  targets/TARGET_Maxim/TARGET_MAX32625/TARGET_MAX32625PICO/PeripheralNames.h
  targets/TARGET_Maxim/TARGET_MAX32625/TARGET_MAX32625PICO/PinNames.h
  targets/TARGET_Maxim/TARGET_MAX32625/TARGET_MAX32625PICO/low_level_init.c
  targets/TARGET_Maxim/TARGET_MAX32625/device/TOOLCHAIN_ARM_STD/TARGET_MAX32625_BOOT/MAX32625.sct
  targets/TARGET_Maxim/TARGET_MAX32625/device/TOOLCHAIN_GCC_ARM/TARGET_MAX32625_BOOT/max32625.ld
  targets/TARGET_Maxim/TARGET_MAX32625/device/TOOLCHAIN_IAR/TARGET_MAX32625_BOOT/MAX32625.icf
  targets/targets.json
Labels: ready for merge, release-version: 5.9.5

#7559 Export: Support Make + ArmC6 + v8m
  tools/export/makefile/Makefile.tmpl
  tools/export/makefile/__init__.py
  tools/resources/__init__.py
Labels: ready for merge, release-version: 5.9.5

#7686 Correct MTB_ADV_WISE_1530 led configuration
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_MTB_MXCHIP_EMW3166/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_USI_WM_BN_BM_22/PinNames.h
  targets/targets.json
Labels: ready for merge

#7738 Timeout tests : unstable result
  TESTS/mbed_drivers/timeout/timeout_tests.h
Labels: needs: CI, release-version: 5.9.6

#7757 Revert "Move BlockDevice classes inside mbed namespace"
  features/filesystem/FileSystem.h
  features/filesystem/bd/BlockDevice.h
  features/filesystem/bd/BufferedBlockDevice.cpp
  features/filesystem/bd/BufferedBlockDevice.h
  features/filesystem/bd/ChainingBlockDevice.cpp
  features/filesystem/bd/ChainingBlockDevice.h
  features/filesystem/bd/ExhaustibleBlockDevice.cpp
  features/filesystem/bd/ExhaustibleBlockDevice.h
  features/filesystem/bd/FlashSimBlockDevice.cpp
  features/filesystem/bd/FlashSimBlockDevice.h
  features/filesystem/bd/HeapBlockDevice.cpp
  features/filesystem/bd/HeapBlockDevice.h
  features/filesystem/bd/MBRBlockDevice.cpp
  features/filesystem/bd/MBRBlockDevice.h
  features/filesystem/bd/ObservingBlockDevice.cpp
  features/filesystem/bd/ObservingBlockDevice.h
  features/filesystem/bd/ProfilingBlockDevice.cpp
  features/filesystem/bd/ProfilingBlockDevice.h
  features/filesystem/bd/ReadOnlyBlockDevice.cpp
  features/filesystem/bd/ReadOnlyBlockDevice.h
  features/filesystem/bd/SlicingBlockDevice.cpp
  features/filesystem/bd/SlicingBlockDevice.h
  features/filesystem/fat/FATFileSystem.cpp
  features/filesystem/fat/FATFileSystem.h
  features/filesystem/littlefs/LittleFileSystem.cpp
  features/filesystem/littlefs/LittleFileSystem.h
  features/filesystem/mbed_filesystem.h
Labels: needs: CI, release-version: 5.10.0-rc1

#7750 Cellular: Fixed sms greentea tests init
  features/cellular/TESTS/api/cellular_sms/main.cpp
Labels: ready for merge, release-version: 5.9.6

#7752 tests-mbed_drivers-timer: change delay method
  TESTS/mbed_drivers/timer/main.cpp
Labels: ready for merge, release-version: 5.9.6

#7771 Update mesh_system_heap_error_handler to use new error handler
  features/nanostack/mbed-mesh-api/source/mesh_system.c
Labels: ready for merge, release-version: 5.9.6

#7735 Optimized CRC implementation - (32-bit ANSI polynomial)
  drivers/MbedCRC.h
  drivers/TableCRC.cpp
  drivers/TableCRC.h
Labels: ready for merge, release-version: 5.9.6

#7590 Tools: Differential Memap
  tools/memap.py
  tools/memap_flamegraph.html
  tools/settings.py
Labels: ready for merge, release-version: 5.10.0-rc1

#7645 nrf_drv_twi: remove redundant nrf_drv_disable call in nrf_drv_twi_uninit
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/drivers_nrf/twi_master/nrf_drv_twi.c
Labels: ready for merge, release-version: 5.9.6

#7693 Fix for CM3DS GPIO api
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/gpio_api.c
Labels: ready for merge, release-version: 5.9.6

#7713 LittleFS: Update to version 1.6
  .travis.yml
  features/filesystem/littlefs/LICENSE.md
  features/filesystem/littlefs/LittleFileSystem.cpp
  features/filesystem/littlefs/LittleFileSystem.h
  features/filesystem/littlefs/littlefs/.travis.yml
  features/filesystem/littlefs/littlefs/LICENSE.md
  features/filesystem/littlefs/littlefs/Makefile
  features/filesystem/littlefs/littlefs/README.md
  features/filesystem/littlefs/littlefs/emubd/lfs_emubd.c
  features/filesystem/littlefs/littlefs/emubd/lfs_emubd.h
  features/filesystem/littlefs/littlefs/lfs.c
  features/filesystem/littlefs/littlefs/lfs.h
  features/filesystem/littlefs/littlefs/lfs_util.c
  features/filesystem/littlefs/littlefs/lfs_util.h
  features/filesystem/littlefs/littlefs/tests/test_files.sh
  features/filesystem/littlefs/littlefs/tests/test_interspersed.sh
  features/filesystem/littlefs/littlefs/tests/test_seek.sh
Labels: ready for merge, release-version: 5.10.0-rc1

#7716 Fix issue #5119, changed pwmout_api.
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/pwmout_api.c
Labels: ready for merge, release-version: 5.9.6

#7777 STM32F1 RTC : wrong Sunday value
  targets/TARGET_STM/rtc_api.c
Labels: ready for merge, release-version: 5.9.6

#7719 Lora: Document all possible error codes for LoRaWANBase methods
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
Labels: ready for merge, release-version: 5.9.6

#7740 Cellular: Handle AT response stop in case IP address is missing from …
  features/cellular/framework/AT/AT_CellularStack.cpp
Labels: ready for merge, release-version: 5.9.6

#7741 tests-mbed_hal-common_tickers: disable ticker free test cases.
  TESTS/mbed_hal/common_tickers/main.cpp
  TESTS/mbed_hal/common_tickers/ticker_api_tests.h
  hal/us_ticker_api.h
Labels: ready for merge, release-version: 5.9.6

#7769 Fix build_data functionality with python 3
  tools/build_api.py
  tools/test.py
  tools/toolchains/__init__.py
Labels: ready for merge, release-version: 5.9.6

#7782 equeue: Fix overflow in rtos-less timeout code
  events/equeue/equeue_mbed.cpp
Labels: ready for merge, release-version: 5.9.6

#7600 Remove unnecessary low power ticker rescheduling
  hal/mbed_ticker_api.c
  hal/ticker_api.h
  rtos/TARGET_CORTEX/SysTimer.cpp
  rtos/TARGET_CORTEX/mbed_rtx_idle.cpp
Labels: ready for merge, release-version: 5.9.6

#7670 Check max possible keys in NVStore tests
  features/nvstore/TESTS/nvstore/functionality/main.cpp
Labels: ready for merge, release-version: 5.9.6

#7797 Fix target_name variable in some use cases
  tools/test_api.py
Labels: ready for merge, release-version: 5.9.6

#7786 Moved ASYNCHRONOUS_DNS_SIMULTANEOUS_REPEAT under mbed extended tests
  TESTS/netsocket/dns/main.cpp
Labels: ready for merge, release-version: 5.9.6

#7667 Cellular: Add CellularDevice::init_module API to be called at startup
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
  features/cellular/easy_cellular/CellularConnectionFSM.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
Labels: needs: CI, release-version: 5.10.0-rc1

#7669 SDT64, 8195, 32620, 32625, 51822, 52832B added to targets
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/PinNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/crc.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/crc.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/device.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/fsl_clock_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/fsl_clock_config.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/fsl_phy.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/fsl_phy.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/mbed_overrides.c
  targets/TARGET_Freescale/mbed_rtx.h
  targets/TARGET_Maxim/TARGET_MAX32620C/TARGET_SDT32620B/PeripheralNames.h
  targets/TARGET_Maxim/TARGET_MAX32620C/TARGET_SDT32620B/PinNames.h
  targets/TARGET_Maxim/TARGET_MAX32625/TARGET_SDT32625B/PeripheralNames.h
  targets/TARGET_Maxim/TARGET_MAX32625/TARGET_SDT32625B/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF51/TARGET_MCU_NRF51822_UNIFIED/TARGET_SDT51822B/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF51/TARGET_MCU_NRF51822_UNIFIED/TARGET_SDT51822B/device.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_SDT52832B/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_SDT52832B/device.h
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/network/dhcp/dhcps.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/network/dhcp/dhcps.h
  targets/TARGET_Realtek/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, scope: new-target

#7706 Refactoring memory regions definitions for Fast Models MPS2 targets
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/TOOLCHAIN_ARM_STD/startup_MPS2.S
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/cmsis_nvic.c
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/cmsis_nvic.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/memory_zones.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/TOOLCHAIN_ARM_STD/startup_MPS2.S
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/cmsis_nvic.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/memory_zones.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/TOOLCHAIN_ARM_STD/startup_MPS2.S
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/cmsis_nvic.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/memory_zones.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/TOOLCHAIN_ARM_STD/startup_MPS2.S
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/cmsis_nvic.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/memory_zones.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/TOOLCHAIN_ARM_STD/startup_CMSDK_CM7.S
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/cmsis_nvic.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/memory_zones.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/flash_api.c
  targets/TARGET_ARM_FM/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, release-version: 5.9.6

#7599 Fix double low power ticker interrupt
  hal/mbed_ticker_api.c
Labels: ready for merge, release-version: 5.10.0-rc1

#7681 BLE: store secure connections ltk in both local and peer entry
  features/FEATURE_BLE/source/generic/GenericSecurityManager.cpp
Labels: ready for merge, release-version: 5.9.6

#7830 Fix uvisor ticker issue on K64F
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/lp_ticker.c
Labels: ready for merge

#7212 FlashIAP & NVStore tests: Skip test if overwriting code in flash
  TESTS/mbed_drivers/flashiap/main.cpp
  features/nvstore/TESTS/nvstore/functionality/main.cpp
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/device/TOOLCHAIN_IAR/tmpm46bf10fg.icf
Labels: ready for merge, release-version: 5.9.6

#7770 LoRa: Fix MAC initialization for connection with parameters
  features/lorawan/lorastack/mac/LoRaMac.cpp
Labels: ready for merge, release-version: 5.9.6

#7768 Cellular: Document all possible error codes for cellular API.
  features/cellular/framework/API/CellularInformation.h
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/API/CellularPower.h
  features/cellular/framework/API/CellularSIM.h
  features/cellular/framework/API/CellularSMS.h
Labels: ready for merge, release-version: 5.9.6

#7775 STM32 wrong MBED_ASSERT use
  targets/TARGET_STM/TARGET_STM32F0/TARGET_DISCO_F051R8/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F031K6/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F042K6/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F070RB/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F1/TARGET_NUCLEO_F103RB/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F302x8/TARGET_NUCLEO_F302R8/system_clock.c
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303x8/TARGET_NUCLEO_F303K8/system_clock.c
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/TARGET_DISCO_F303VC/system_clock.c
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/TARGET_NUCLEO_F303RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/TARGET_NUCLEO_F303ZE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F334x8/TARGET_DISCO_F334C8/system_clock.c
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F334x8/TARGET_NUCLEO_F334R8/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_STEVAL_3DP001V1/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_DISCO_F407VG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F410xB/TARGET_NUCLEO_F410RB/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_SAKURAIO_EVB_01/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_MTB_MXCHIP_EMW3166/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_NUCLEO_F412ZG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_USI_WM_BN_BM_22/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_NUCLEO_F413ZH/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_DISCO_F429ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446ZE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_DISCO_F469NI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/TARGET_NUCLEO_F756ZG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/TARGET_DISCO_F769NI/system_clock.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L011K4/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L031K6/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L053x8/TARGET_DISCO_L053C8/system_clock.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L053x8/TARGET_NUCLEO_L053R8/system_clock.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L072xZ/TARGET_DISCO_L072CZ_LRWAN1/system_clock.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/TARGET_MTB_MURATA_ABZ/system_clock.c
  targets/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/TARGET_NUCLEO_L432KC/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/TARGET_NUCLEO_L433RC_P/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L443xC/TARGET_MTB_ADV_WISE_1510/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_DISCO_L476VG/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_SILICA_SENSOR_NODE/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/TARGET_MTB_ADV_WISE_1570/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/TARGET_NUCLEO_L486RG/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_NUCLEO_L496ZG/system_clock.c
Labels: ready for merge, release-version: 5.9.6

#7793 Template specialization didnt work after addition of default constructor
  drivers/MbedCRC.cpp
  drivers/MbedCRC.h
Labels: ready for merge, release-version: 5.9.6

#7798 Add bootloader support for target NUCLEO_F303RE
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/TARGET_NUCLEO_F303RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/device/TOOLCHAIN_ARM_STD/stm32f303xe.sct
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/device/TOOLCHAIN_GCC_ARM/STM32F303XE.ld
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/device/TOOLCHAIN_IAR/stm32f303xe.icf
  targets/targets.json
Labels: ready for merge, release-version: 5.9.6

#7807 Compiler warning: unused variable in LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMac.h
Labels: ready for merge, release-version: 5.9.6

#7823 MIMXRT1050_EVK: Update the I2C driver
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/i2c_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/objects.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/pinmap.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PeripheralNames.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PeripheralPins.c
Labels: ready for merge, release-version: 5.9.6

#7826 Fix stack size for LwIP on EFM32GG11
  features/lwipstack/mbed_lib.json
  features/netsocket/emac-drivers/TARGET_Silicon_Labs/sl_emac_config.h
Labels: ready for merge, release-version: 5.9.6

#7832 Nanostack: Fix return code for unsupported socket options
  features/nanostack/nanostack-interface/Nanostack.cpp
Labels: ready for merge, release-version: 5.9.6

#7831 LoRaWAN: Restoring default RX2 data rate
  features/lorawan/lorastack/phy/LoRaPHY.cpp
Labels: ready for merge, release-version: 5.9.6

#7524 Fixes for tickless and LPTICKER_DELAY_TICKS
  TESTS/mbed_drivers/sleep_lock/main.cpp
  TESTS/mbed_drivers/timeout/timeout_tests.h
  TESTS/mbed_hal/common_tickers/main.cpp
  TESTS/mbed_hal/common_tickers_freq/main.cpp
  TESTS/mbed_hal/lp_ticker/main.cpp
  TESTS/mbed_hal/rtc/main.cpp
  TESTS/mbed_hal/sleep/main.cpp
  TESTS/mbed_hal/sleep_manager/main.cpp
  TESTS/mbed_hal/sleep_manager_racecondition/main.cpp
  TESTS/mbed_hal/ticker/main.cpp
  TESTS/mbedmicro-rtos-mbed/systimer/main.cpp
  hal/LowPowerTickerWrapper.cpp
  hal/LowPowerTickerWrapper.h
  hal/mbed_lp_ticker_api.c
  hal/mbed_lp_ticker_wrapper.cpp
  hal/mbed_lp_ticker_wrapper.h
  hal/mbed_sleep_manager.c
  hal/mbed_ticker_api.c
  hal/ticker_api.h
  platform/mbed_power_mgmt.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7619 UBLOX cellular api's for UDP and TCP
  features/cellular/TESTS/api/cellular_network/main.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/common/CellularTargets.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularPower.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularPower.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/onboard_modem_api.c
Labels: ready for merge, release-version: 5.10.0-rc1

#7767 Lora: Fix TX_ERROR event if corrupted msg is received for CONFIRMED request
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
Labels: ready for merge, release-version: 5.10.0-rc1

#7780 Rename nanostack configuration (.cfg) files
  features/nanostack/sal-stack-nanostack/source/configs/base/cfg_ethernet.h
  features/nanostack/sal-stack-nanostack/source/configs/base/cfg_local_socket.h
  features/nanostack/sal-stack-nanostack/source/configs/base/cfg_lowpan_border_router.h
  features/nanostack/sal-stack-nanostack/source/configs/base/cfg_lowpan_host.h
  features/nanostack/sal-stack-nanostack/source/configs/base/cfg_lowpan_router.h
  features/nanostack/sal-stack-nanostack/source/configs/base/cfg_rf_tunnel.h
  features/nanostack/sal-stack-nanostack/source/configs/base/cfg_thread_border_router.h
  features/nanostack/sal-stack-nanostack/source/configs/base/cfg_thread_end_device.h
  features/nanostack/sal-stack-nanostack/source/configs/base/cfg_thread_full_end_device.h
  features/nanostack/sal-stack-nanostack/source/configs/base/cfg_thread_router.h
  features/nanostack/sal-stack-nanostack/source/configs/base/ethernet.cfg
  features/nanostack/sal-stack-nanostack/source/configs/base/local_socket.cfg
  features/nanostack/sal-stack-nanostack/source/configs/base/lowpan_border_router.cfg
  features/nanostack/sal-stack-nanostack/source/configs/base/lowpan_host.cfg
  features/nanostack/sal-stack-nanostack/source/configs/base/lowpan_router.cfg
  features/nanostack/sal-stack-nanostack/source/configs/base/rf_tunnel.cfg
  features/nanostack/sal-stack-nanostack/source/configs/base/thread_border_router.cfg
  features/nanostack/sal-stack-nanostack/source/configs/base/thread_end_device.cfg
  features/nanostack/sal-stack-nanostack/source/configs/base/thread_full_end_device.cfg
  features/nanostack/sal-stack-nanostack/source/configs/base/thread_router.cfg
  features/nanostack/sal-stack-nanostack/source/configs/cfg_ethernet_host.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_generic.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_lowpan_border_router.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_lowpan_border_router_rf_tunnel.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_lowpan_border_router_rf_tunnel_ecc.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_lowpan_border_router_rf_tunnel_ecc_release.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_lowpan_host.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_lowpan_router.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_lowpan_router_ecc.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_lowpan_router_ecc_release.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_nanostack_full.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_nanostack_full_debug.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_rf_interface.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_thread_border_router.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_thread_end_device.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_thread_full_end_device.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_thread_router.h
  features/nanostack/sal-stack-nanostack/source/configs/cfg_thread_thci.h
  features/nanostack/sal-stack-nanostack/source/configs/rf_interface.cfg
  features/nanostack/sal-stack-nanostack/source/nsconfig.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7772 Modified Jenkinsfile into one-liner format.
  Jenkinsfile
Labels: ready for merge

#7790 STM32 LPTICKER : RTC wake up timer is reset before setting a new one
  targets/TARGET_STM/lp_ticker.c
  targets/TARGET_STM/rtc_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.9.6

#7785 Lora: Fix join-response failure handling
  features/lorawan/LoRaWANStack.cpp
Labels: ready for merge, release-version: 5.9.6

#7762 Add combined hex target to CMake
  tools/export/cmake/CMakeLists.txt.tmpl
Labels: ready for merge, release-version: 5.9.6

#7739 Update mbed-coap to version 4.6.1
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_coap_protocol.h
  features/frameworks/mbed-coap/module.json
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.10.0-rc1

#7851 littlefs: Fixed issue with cleanup in mount function on error
  features/filesystem/littlefs/LittleFileSystem.cpp
  features/filesystem/littlefs/TESTS/filesystem_integration/format/main.cpp
Labels: ready for merge, release-version: 5.10.0-rc1

#7843 MIMXRT1050: Fix I2C Byte transfer functions
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/i2c_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/objects.h
Labels: ready for merge, release-version: 5.9.6

#7816 Lora: Refactor duty-cycle configuration and introduce config for JOIN request
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYAS923.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYKR920.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.cpp
  features/lorawan/mbed_lib.json
Labels: ready for merge, release-version: 5.10.0-rc1

#7846 Tools: Use Distcc when it's configured
  tools/toolchains/gcc.py
Labels: ready for merge, release-version: 5.10.0-rc1

#7744 RTOS threads test: Handle out of memory cases
  TESTS/mbedmicro-rtos-mbed/threads/main.cpp
Labels: ready for merge, release-version: 5.9.6

#7815 Re-add Shared Pointer Class into platform features
  TESTS/mbed_platform/SharedPtr/main.cpp
  platform/SharedPtr.h
Labels: needs: CI, release-version: 5.10.0-rc1

#7417 Cordio Documentation: Explain how to tests and what tools are available.
  features/FEATURE_BLE/targets/TARGET_CORDIO/doc/HCIAbstraction.md
  features/FEATURE_BLE/targets/TARGET_CORDIO/doc/PortingGuide.md
Labels: ready for merge, release-version: 5.10.0-rc1

#7810 Eventqueue Templatewall Doxygen Rework
  events/Event.h
  events/EventQueue.h
Labels: ready for merge, release-version: 5.9.7

#7730 When stack stats enabled, prevent exceptions if memory allocations fail
  features/frameworks/greentea-client/source/greentea_metrics.cpp
  platform/mbed_stats.c
Labels: ready for merge, release-version: 5.9.7

#7840 WISE_1570 greentea tests
  features/cellular/TESTS/api/cellular_information/main.cpp
  features/cellular/TESTS/api/cellular_network/main.cpp
  features/cellular/TESTS/api/cellular_sim/main.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularPower.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularSIM.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularSIM.h
Labels: ready for merge, release-version: 5.9.7

#7839 Lora: Change visibility of LoRaMac internal methods as private
  features/lorawan/lorastack/mac/LoRaMac.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7652 NRF5x: Fix config of LFCLK source / settings.
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_S132_FULL/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_S132_OTA/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_S140_FULL/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_S140_OTA/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/nrf5x_lf_clk_helper.h
Labels: ready for merge, release-version: 5.9.7

#7854 Nanostack patch release for Mbed OS 5.10
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_pd_sap.c
Labels: ready for merge, release-version: 5.10.0-rc1

#7817 standardise QSPI pin names
  TESTS/mbed_hal/qspi/main.cpp
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_NRF52840_DK/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_NUCLEO_F412ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_NUCLEO_F413ZH/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446ZE/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_DISCO_F469NI/PinNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/TARGET_NUCLEO_F756ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/TARGET_DISCO_F769NI/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/TARGET_NUCLEO_L432KC/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/TARGET_NUCLEO_L433RC_P/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_DISCO_L476VG/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_NUCLEO_L496ZG/PinNames.h
Labels: G, ready for merge, release-version: 5.10.0-rc1

#7673 Fixing import paths of memap.py when excuted as a script
  tools/memap.py
Labels: ready for merge, release-version: 5.9.7

#7714 Add BOOTLOADER feature
  features/FEATURE_BOOTLOADER/mbed_lib.json
  features/FEATURE_BOOTLOADER/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/LICENSE
  features/FEATURE_BOOTLOADER/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/mbed-bootloader-k66f-block_device-sotp-v3_4_0.bin
  features/FEATURE_BOOTLOADER/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/mbed_lib.json
  features/FEATURE_BOOTLOADER/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/LICENSE
  features/FEATURE_BOOTLOADER/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/mbed-bootloader-k64f-block_device-sotp-v3_4_0.bin
  features/FEATURE_BOOTLOADER/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/mbed_lib.json
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/LICENSE
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/mbed-bootloader-nucleo_f411re-block_device-sotp-v3_4_0.bin
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/mbed_lib.json
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/LICENSE
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/mbed-bootloader-nucleo_f429zi-block_device-sotp-v3_4_0.bin
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/mbed_lib.json
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_UBLOX_EVK_ODIN_W2/LICENSE
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_UBLOX_EVK_ODIN_W2/mbed-bootloader-sotp-v3_4_0.bin
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_UBLOX_EVK_ODIN_W2/mbed_lib.json
  tools/build_api.py
  tools/config/__init__.py
Labels: A, ready for merge, release-version: 5.10.0-rc1

#7751 Realtek RTL8195A wifi interface to inherit EMAC interface
  targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.cpp
  targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7802 LoRaWAN: Custom FSB selection in US and Australian regions
  features/lorawan/FSB_Usage.txt
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915Hybrid.h
  features/lorawan/lorastack/phy/loraphy_target.h
  features/lorawan/mbed_lib.json
Labels: ready for merge, release-version: 5.10.0-rc1

#7534 enable MOTE_L152 for OS5
  TESTS/mbed_hal/common_tickers/main.cpp
  targets/targets.json
Labels: ready for merge, release-version: 5.9.7, scope: new-target

#7773 Add some logic related to initialization to various block devices
  features/filesystem/bd/BufferedBlockDevice.cpp
  features/filesystem/bd/BufferedBlockDevice.h
  features/filesystem/bd/ChainingBlockDevice.cpp
  features/filesystem/bd/ChainingBlockDevice.h
  features/filesystem/bd/ExhaustibleBlockDevice.cpp
  features/filesystem/bd/ExhaustibleBlockDevice.h
  features/filesystem/bd/FlashSimBlockDevice.cpp
  features/filesystem/bd/FlashSimBlockDevice.h
  features/filesystem/bd/HeapBlockDevice.cpp
  features/filesystem/bd/HeapBlockDevice.h
  features/filesystem/bd/MBRBlockDevice.cpp
  features/filesystem/bd/MBRBlockDevice.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7758 Include user defined static lib files in the Linker object files paths
  tools/export/e2studio/.cproject.tmpl
  tools/export/gnuarmeclipse/.cproject.tmpl
  tools/export/gnuarmeclipse/__init__.py
Labels: ready for merge, release-version: 5.9.7

#7805 Skip Greentea tests for Mbed OS code coverage on Fast Models
  TESTS/mbed_drivers/ticker/main.cpp
  TESTS/mbed_drivers/timeout/main.cpp
  TESTS/mbed_hal/common_tickers_freq/main.cpp
  TESTS/mbedmicro-rtos-mbed/basic/main.cpp
  TESTS/mbedmicro-rtos-mbed/mail/main.cpp
  TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
  TESTS/mbedmicro-rtos-mbed/threads/main.cpp
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/targets.json
Labels: ready for merge, release-version: 5.10.0-rc1

#7761 ifndef some macros to allow overriding during compilation
  features/frameworks/greentea-client/greentea-client/test_env.h
  features/unsupported/tests/mbed/env/test_env.h
Labels: ready for merge, release-version: 5.9.7

#7569 Tools: Add Uvision6 exporter
  tools/export/__init__.py
  tools/export/cmsis/__init__.py
  tools/export/exporters.py
  tools/export/uvision/__init__.py
  tools/export/uvision/uvision.tmpl
Labels: G, ready for merge, release-version: 5.10.0-rc1

#7828 Platform: Add C++ Span class.
  platform/Span.h
Labels: G, ready for merge, release-version: 5.10.0-rc1

#7848 Message ID in CAN constructor needs to be unsigned
  drivers/CAN.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7857 Cellular: Make AT_CellularStack socket array multi-thread safe
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7870 Cellular: Support for GPRS dial-up
  features/cellular/framework/AT/AT_CellularBase.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: ready for merge, release-version: 5.10.0-rc1

#7402 Replace mbed_mem_tracing_enabled macro with config option
  TESTS/mbed_drivers/mem_trace/main.cpp
  platform/mbed_alloc_wrappers.cpp
  platform/mbed_lib.json
  platform/mbed_retarget.cpp
Labels: BREAKING-CHANGE, ready for merge, release-version: 5.10.0-rc1

#7860 Cellular: Allow cellular modules to override network registration mode
  features/cellular/UNITTESTS/at/at_cellularnetwork/test_at_cellularnetwork.cpp
  features/cellular/UNITTESTS/stubs/AT_CellularNetwork_stub.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularNetwork.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularNetwork.h
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96_CellularNetwork.cpp
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96_CellularNetwork.h
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910_CellularNetwork.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910_CellularNetwork.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.h
  features/cellular/framework/targets/UBLOX/PPP/UBLOX_PPP_CellularNetwork.cpp
  features/cellular/framework/targets/UBLOX/PPP/UBLOX_PPP_CellularNetwork.h
Labels: G, ready for merge, release-version: 5.10.0-rc1

#7878 Corrected mbed-mesh-api thread/6lowpan tasklets interface disconnect/connect
  features/nanostack/mbed-mesh-api/source/nd_tasklet.c
  features/nanostack/mbed-mesh-api/source/thread_tasklet.c
Labels: ready for merge, release-version: 5.9.7

#7818 Allow ThreadInterface::device_eui64_get() before connect()
  features/nanostack/mbed-mesh-api/mbed-mesh-api/LoWPANNDInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/ThreadInterface.h
  features/nanostack/mbed-mesh-api/source/LoWPANNDInterface.cpp
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  features/nanostack/mbed-mesh-api/source/ThreadInterface.cpp
Labels: ready for merge, release-version: 5.10.0-rc1

#7873 realtek: fix #7829 - remove dhcps files
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/network/dhcp/dhcps.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/network/dhcp/dhcps.h
Labels: ready for merge, release-version: 5.9.7

#7880 Update Greentea EMAC tests
  TESTS/network/emac/emac_test_initialize.cpp
  TESTS/network/emac/main.cpp
Labels: ready for merge, release-version: 5.9.7

#7891 Remove unused cmsis includes.
  drivers/CAN.cpp
  drivers/TimerEvent.cpp
Labels: ready for merge, release-version: 5.9.7

#7792 Build tool fixes for Musca support
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
Labels: G, needs: CI, release-version: 5.10.0-rc1

#7644 Tools: Scan for "components"
  tools/resources/__init__.py
  tools/resources/ignore.py
  tools/targets/__init__.py
  tools/test_api.py
  tools/toolchains/__init__.py
Labels: G, ready for merge, release-version: 5.10.0-rc1

#7868 Disable MBEDTLS_HAVE_DATE_TIME as ARMCC does not support gmtime
  features/mbedtls/platform/inc/platform_mbed.h
Labels: G, ready for merge, release-version: 5.10.0-rc1

#7677 Cellular: Gemalto Cinterion support for ELS61 and BGS2
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.h
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularNetwork.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularNetwork.h
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.h
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_Module.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_Module.h
Labels: G, ready for merge, release-version: 5.10.0-rc1

#7795 Cellular: Add getters for device and serial to EasyCellularConnection
  features/cellular/easy_cellular/EasyCellularConnection.cpp
  features/cellular/easy_cellular/EasyCellularConnection.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7788 Cellular: Fixed AT+COPN
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: ready for merge, release-version: 5.9.7

#7781 Add thread safety to CRC class
  TESTS/mbed_drivers/crc/main.cpp
  drivers/MbedCRC.cpp
  drivers/MbedCRC.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7871 Updated linker files (GCC_ARM, ARM, IAR) for NUCLEO_F207ZG and enabled bootloader functionality
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/TOOLCHAIN_ARM_STD/startup_stm32f207xx.S
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/TOOLCHAIN_ARM_STD/stm32f207xx.sct
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/TOOLCHAIN_GCC_ARM/STM32F207ZGTx_FLASH.ld
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/TOOLCHAIN_IAR/stm32f207xx.icf
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/system_clock.c
  targets/targets.json
Labels: ready for merge, release-version: 5.10.0-rc1

#7778 Fix MeshInterface::get_default_instance()
  features/nanostack/mbed-mesh-api/source/LoWPANNDInterface.cpp
  features/nanostack/mbed-mesh-api/source/ThreadInterface.cpp
  features/nanostack/targets/TARGET_NCS36510/NanostackRfPhyNcs36510.cpp
  features/netsocket/mbed_lib.json
  targets/targets.json
  tools/test_configs/6lowpanInterface_host.json
  tools/test_configs/6lowpanInterface_router.json
  tools/test_configs/ThreadInterface_end_device.json
  tools/test_configs/ThreadInterface_router.json
  tools/test_configs/config_paths.json
Labels: A, needs: CI, release-version: 5.10.0-rc1

#7844 Implement device management subcommand
  requirements.txt
  tools/device_management.py
Labels: A, needs: CI, release-version: 5.10.0-rc1

#7899 Bluetooth 5 Phy support
  features/FEATURE_BLE/ble/BLETypes.h
  features/FEATURE_BLE/ble/Gap.h
  features/FEATURE_BLE/ble/generic/GenericGap.h
  features/FEATURE_BLE/ble/pal/PalGap.h
  features/FEATURE_BLE/source/generic/GenericGap.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioPalGap.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioBLE.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalGap.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/btle/btle.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xGap.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xGap.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7662 Add Error Decoding URL to error report
  platform/mbed_error.c
  platform/mbed_lib.json
Labels: A, needs: CI, release-version: 5.10.0-rc1
