Repository ARMmbed/mbed-os, pull requests merged in 2018-06, with the labels that each got.

#6803 Wise 1510 uart config
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L443xC/TARGET_MTB_ADV_WISE_1510/PinNames.h
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#7007 AStyle: Fix astyle indentation
  .astylerc
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#7052 Cellular: BC95 socket creation to fail on missing socket id in the re…
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
Labels: ready for merge, release-version: 5.8.6, release-version: 5.9.1

#7056 fix realtek_rtl8195am IPv6 build fails update
  targets/TARGET_Realtek/TARGET_AMEBA/rtw_emac.cpp
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/api/wifi/wifi_conf.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/network/dhcp/dhcps.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/common/network/dhcp/dhcps.h
Labels: ready for merge, release-version: 5.8.6

#6987 STM32 ADC update
  targets/TARGET_STM/TARGET_STM32F0/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F0/device/stm32f0xx_hal_adc.h
  targets/TARGET_STM/TARGET_STM32F1/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F2/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F3/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F3/device/stm32f3xx_hal_adc.h
  targets/TARGET_STM/TARGET_STM32F3/device/stm32f3xx_hal_adc_ex.c
  targets/TARGET_STM/TARGET_STM32F4/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc.h
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_adc.h
  targets/TARGET_STM/TARGET_STM32F7/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_adc.h
  targets/TARGET_STM/TARGET_STM32L0/analogin_device.c
  targets/TARGET_STM/TARGET_STM32L0/device/stm32l0xx_hal_adc.h
  targets/TARGET_STM/TARGET_STM32L1/analogin_device.c
  targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_adc.h
  targets/TARGET_STM/TARGET_STM32L4/analogin_device.c
Labels: needs: CI, release-version: 5.8.6, release-version: 5.9.1

#7075 BLE: Replace Serial with RawSerial in Cordio H4 Transport Driver
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/H4TransportDriver.h
Labels: needs: CI, release-version: 5.8.6, release-version: 5.9.1

#7032 Update cmsis/rtx for Cortex-A
  cmsis/TARGET_CORTEX_A/irq_ctrl_gic.c
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_ARM/TARGET_CORTEX_A/irq_ca.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_CORTEX_A/irq_ca.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_CORTEX_A/irq_ca.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_thread.c
Labels: needs: CI, release-version: 5.8.6, release-version: 5.9.1

#7062 DISCO_F413ZH : map SPI3 to WIFI module
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/PinNames.h
Labels: needs: CI, release-version: 5.8.6, release-version: 5.9.1

#7082 Update mbed-coap to version 4.4.4
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/module.json
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: needs: CI, release-version: 5.8.6

#7078 Windows pytest fixes
  tools/test/memap/parse_test.py
  tools/test/test_api/test_api_test.py
  tools/test/toolchains/api_test.py
Labels: ready for merge, release-version: 5.9.0-rc2

#7074 Remove redundant Cryptocell libraries
  features/cryptocell/FEATURE_CRYPTOCELL310/TARGET_MCU_NRF52840/TOOLCHAIN_ARM/libnrf_cc310_ext_softfp_0.9.9.a
  features/cryptocell/FEATURE_CRYPTOCELL310/TARGET_MCU_NRF52840/TOOLCHAIN_ARM/libnrf_cc310_trng_softfp_0.9.9.a
  features/cryptocell/FEATURE_CRYPTOCELL310/binaries/TOOLCHAIN_ARM/libnrf_cc310_core_softfp_0.9.9.a
  features/cryptocell/FEATURE_CRYPTOCELL310/binaries/TOOLCHAIN_GCC_ARM/libcc_310_core.a.mod
  features/cryptocell/FEATURE_CRYPTOCELL310/binaries/TOOLCHAIN_GCC_ARM/libcc_310_core.a~31bb423e11968b6c6cfbd1735561b06af3862622
Labels: ready for merge, release-version: 5.9.0-rc2

#7072 Edit warning about FEATURE_UVISOR being deprecated
  features/FEATURE_UVISOR/includes/uvisor/api/inc/uvisor_deprecation.h
Labels: ready for merge, release-version: 5.9.0-rc2

#7070 set the tolerance to 5% if NO_SYSTICK is enabled
  TESTS/mbed_drivers/timer/main.cpp
Labels: ready for merge, release-version: 5.9.0-rc2

#7060 UBLOX_C027: init us_ticker in the target initialization
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_UBLOX_C027/ublox_low_level_api.c
Labels: ready for merge, release-version: 5.9.0-rc2

#7050 Fix for filename capture not working
  platform/mbed_error.c
  platform/mbed_error.h
Labels: ready for merge, release-version: 5.9.0-rc2

#6848 Check that no GPL licence inside code
  .travis.yml
Labels: ready for merge, release-version: 5.9.1

#7089 BLE fixes (SM whitelist creation, Nordic scatter file fix, missing TLS initialisation)
  features/FEATURE_BLE/ble/generic/SecurityDb.h
  features/FEATURE_BLE/source/generic/GenericSecurityManager.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/nRF5xGap.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xCrypto.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xCrypto.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_ARM_STD/nRF52832.sct
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_ARM_STD/nRF52840.sct
Labels: ready for merge, release-version: 5.9.0-rc2

#6582 Implement zoomable html-flamegraph memap output
  tools/build_api.py
  tools/memap.py
  tools/memap_flamegraph.html
Labels: ready for merge, release-version: 5.10.0-rc1

#7092 Additional fixes for running Python 3 in Windows
  tools/build_api.py
  tools/memap.py
  tools/notifier/term.py
  tools/test/examples/examples_lib.py
  tools/test/memap/parse_test.py
  tools/toolchains/__init__.py
Labels: G, needs: CI, release-version: 5.9.0-rc2

#6515 Only schedule mbed_ticker interrupt if queue->head is changed
  TESTS/mbed_hal/ticker/main.cpp
  hal/mbed_ticker_api.c
Labels: ready for merge, release-version: 5.9.1

#7095 Fixing some coverity issues.
  features/device_key/TESTS/device_key/functionality/main.cpp
Labels: ready for merge, release-version: 5.9.1

#7081 Fix mbed_crc_ctor is missing in some MbedCRC constructor
  drivers/MbedCRC.cpp
Labels: ready for merge, release-version: 5.9.1

#6914 build: fix notifier typo and passing to builds API
  tools/build.py
  tools/test_api.py
  tools/toolchains/__init__.py
Labels: ready for merge

#7132 Tool: Use TerminalNotifier in Mbed 2 release
  tools/build_release.py
Labels: ready for merge, release-version: 5.9.0-rc2

#7143 STM32 : few targets does not support LPTICKER
  targets/targets.json
Labels: ready for merge, release-version: 5.9.1

#7136 error: fix undeclared memcpy
  platform/mbed_error.c
Labels: ready for merge, release-version: 5.9.1

#7111 Python 3 makefile export issue
  tools/export/makefile/__init__.py
Labels: ready for merge, release-version: 5.9.1

#7124 Tool: Use TerminalNotifier in singletest
  tools/test_api.py
Labels: ready for merge, release-version: 5.9.1

#6860 Nordic BLE: Allow configuration of softdevice parameters
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/btle/btle.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/btle/btle.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/btle/custom/custom_helper.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_S132_FULL/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_S140_FULL/mbed_lib.json
Labels: ready for merge, release-version: 5.9.1

#6949 Support mbed_start_application for Cortex-M23
  platform/mbed_application.c
  platform/mbed_application.h
Labels: ready for merge, release-version: 5.9.1

#6999 Extend feature which displays errors/warnings as Link
  tools/notifier/term.py
  tools/toolchains/__init__.py
Labels: ready for merge, release-version: 5.10.0-rc1

#7120 Fixed DNS resolution in case all sendto operations fail
  features/netsocket/nsapi_dns.cpp
Labels: needs: CI, release-version: 5.9.1

#7067 Add ISM43362 driver support for STM32 wifi DISCO boards
  tools/test_configs/ISM43362Interface.json
  tools/test_configs/config_paths.json
  tools/test_configs/target_configs.json
Labels: ready for merge, release-version: 5.9.1

#7144 Add configuration options to enable CMAC in mbedtls by default
  features/mbedtls/importer/Makefile
  features/mbedtls/importer/adjust-config.sh
  features/mbedtls/importer/adjust-no-entropy-config.sh
Labels: ready for merge, release-version: 5.9.0-rc3

#7173 Make Nanostack C++ constructor initialise Nanostack
  features/nanostack/nanostack-interface/Nanostack.cpp
Labels: ready for merge, release-version: 5.9.1

#7167 Add show full path option to armc6 linker
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge, release-version: 5.9.1

#7148 Tool, build_release: Return nonzero when builds fail
  tools/build_release.py
Labels: ready for merge, release-version: 5.9.1

#7147 Upgrade uvisor to v0.31.1
  features/FEATURE_UVISOR/AUTHORS.txt
  features/FEATURE_UVISOR/VERSION.txt
  features/FEATURE_UVISOR/targets/TARGET_UVISOR_SUPPORTED/TARGET_ARM_BEETLE_SOC/TARGET_DEBUG/TARGET_M3/libconfiguration_beetle_cortex_m3_0x20000000_0x140.a
  features/FEATURE_UVISOR/targets/TARGET_UVISOR_SUPPORTED/TARGET_ARM_BEETLE_SOC/TARGET_RELEASE/TARGET_M3/libconfiguration_beetle_cortex_m3_0x20000000_0x140.a
  features/FEATURE_UVISOR/targets/TARGET_UVISOR_SUPPORTED/TARGET_EFM32/TARGET_DEBUG/TARGET_M3/libconfiguration_efm32_cortex_m3_p1.a
  features/FEATURE_UVISOR/targets/TARGET_UVISOR_SUPPORTED/TARGET_EFM32/TARGET_DEBUG/TARGET_M4/libconfiguration_efm32_cortex_m4_p1.a
  features/FEATURE_UVISOR/targets/TARGET_UVISOR_SUPPORTED/TARGET_EFM32/TARGET_RELEASE/TARGET_M3/libconfiguration_efm32_cortex_m3_p1.a
  features/FEATURE_UVISOR/targets/TARGET_UVISOR_SUPPORTED/TARGET_EFM32/TARGET_RELEASE/TARGET_M4/libconfiguration_efm32_cortex_m4_p1.a
  features/FEATURE_UVISOR/targets/TARGET_UVISOR_SUPPORTED/TARGET_M480/TARGET_DEBUG/TARGET_M4/libconfiguration_m480_cortex_m4_0x20000000_0x0.a
  features/FEATURE_UVISOR/targets/TARGET_UVISOR_SUPPORTED/TARGET_M480/TARGET_RELEASE/TARGET_M4/libconfiguration_m480_cortex_m4_0x20000000_0x0.a
  features/FEATURE_UVISOR/targets/TARGET_UVISOR_SUPPORTED/TARGET_MCU_K64F/TARGET_DEBUG/TARGET_M4/libconfiguration_kinetis_cortex_m4_0x1fff0000.a
  features/FEATURE_UVISOR/targets/TARGET_UVISOR_SUPPORTED/TARGET_MCU_K64F/TARGET_RELEASE/TARGET_M4/libconfiguration_kinetis_cortex_m4_0x1fff0000.a
  features/FEATURE_UVISOR/targets/TARGET_UVISOR_SUPPORTED/TARGET_STM32F4/TARGET_DEBUG/TARGET_M4/libconfiguration_stm32_cortex_m4_0x10000000_0x0.a
  features/FEATURE_UVISOR/targets/TARGET_UVISOR_SUPPORTED/TARGET_STM32F4/TARGET_RELEASE/TARGET_M4/libconfiguration_stm32_cortex_m4_0x10000000_0x0.a
Labels: ready for merge, release-version: 5.9.1

#7141 Kinetis EMAC: Make number of buffers configurable
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/kinetis_emac.cpp
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/kinetis_emac_config.h
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/mbed_lib.json
Labels: ready for merge, release-version: 5.9.1

#7121 Nanostack EMAC - avoid initialisation race
  features/nanostack/mbed-mesh-api/source/NanostackEMACInterface.cpp
Labels: ready for merge, release-version: 5.9.1

#7086 NXP lpc17xx emac driver
  features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/TARGET_LPCTarget/lpc17_emac.c
  features/FEATURE_LWIP/lwip-interface/lwip-eth/arch/TARGET_NXP/TARGET_LPCTarget/lwipopts_conf.h
  features/FEATURE_LWIP/lwip-interface/mbed_lib.json
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_LPCTarget/lpc17_emac.cpp
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_LPCTarget/lpc17_emac.h
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_LPCTarget/lpc17xx_emac.h
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_LPCTarget/lpc_emac_config.h
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_LPCTarget/lpc_phy.h
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_LPCTarget/lpc_phy_dp83848.cpp
  targets/targets.json
Labels: ready for merge, release-version: 5.9.1

#6978 Support default tz_module in event loop thread for M23/M33
  features/FEATURE_LWIP/lwip-interface/lwip-sys/arch/lwip_sys_arch.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.c
Labels: ready for merge, release-version: 5.9.1

#6938 LoRaWAN: Style and bug fixes
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.cpp
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/phy/lora_phy_ds.h
  features/lorawan/lorawan_types.h
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.9.1

#7164 Fix NVStore README file (changed APIs)
  features/nvstore/README.md
Labels: ready for merge, release-version: 5.9.1

#7160 Fixed ppp_lwip_disconnect hangs when connection failure.
  features/FEATURE_LWIP/lwip-interface/ppp_lwip.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: ready for merge, release-version: 5.9.1

#7159 Add targets to Greentea EMAC tests
  TESTS/network/emac/emac_test_initialize.cpp
  TESTS/network/emac/main.cpp
  tools/test_configs/WicedInterface.json
Labels: ready for merge, release-version: 5.9.1

#7150 Nordic: Fix nrf sections on ARMCC
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_ARM_STD/nRF52832.sct
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_ARM_STD/nRF52840.sct
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/libraries/experimental_section_vars/nrf_section_iter.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/libraries/experimental_section_vars/nrf_section_iter.h
Labels: ready for merge, release-version: 5.9.1

#7106 STM32: Replace HAL_GetTick
  targets/TARGET_STM/TARGET_STM32F0/TARGET_DISCO_F051R8/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F030R8/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F031K6/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F042K6/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F070RB/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F072RB/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_NUCLEO_F091RC/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F1/TARGET_BLUEPILL_F103C8/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F1/TARGET_DISCO_F100RB/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F1/TARGET_NUCLEO_F103RB/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F302x8/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303x8/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F334x8/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTB_MTS_DRAGONFLY/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F405RG/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xC/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F410xB/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L011K4/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L031K6/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L053x8/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L072xZ/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_MTS_XDOT/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_MTB_RAK811/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_NZ32_SC151/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L443xC/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/hal_tick.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/device/hal_tick.h
  targets/TARGET_STM/hal_tick_16b.c
  targets/TARGET_STM/hal_tick_32b.c
  targets/TARGET_STM/hal_tick_common.c
  targets/TARGET_STM/sleep.c
Labels: ready for merge, release-version: 5.9.1

#7103 Greentea test updated for NXP lpc17xx
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest_burst.cpp
  TESTS/network/emac/emac_TestMemoryManager.cpp
  TESTS/network/emac/emac_TestNetworkStack.cpp
  TESTS/network/emac/emac_TestNetworkStack.h
  TESTS/network/emac/emac_util.cpp
  TESTS/network/emac/emac_util.h
Labels: ready for merge

#7088 STM32F76x: Add support of dual bank flash mode
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/flash_data.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/flash_data.h
  targets/TARGET_STM/TARGET_STM32F7/flash_api.c
  targets/targets.json
Labels: ready for merge

#7028 USBCDC defaults
  usb/device/USBSerial/USBCDC.h
Labels: ready for merge

#6948 STM32 ETH : remove TX RX locking interrupt perforation
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_eth.c
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_eth.c
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_eth.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_eth.c
Labels: ready for merge

#6922 Fix USB problems on the LPC1768
  usb/device/targets/TARGET_NXP/USBHAL_LPC17.cpp
Labels: ready for merge

#6178 Add target definition: nrf51 16k on MCU_NRF51_UNIFIED platform
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF51/TARGET_MCU_NRF51822_UNIFIED/device/TOOLCHAIN_GCC_ARM/TARGET_MCU_NRF51_16K_S130/NRF51822.ld
  targets/targets.json
Labels: ready for merge, scope: new-target

#7084 Cellular: Enable AT debug also when mbed-trace is disabled
  features/cellular/framework/AT/ATHandler.cpp
Labels: ready for merge, release-version: 5.9.1

#7179 Fix USB on Kinetis devices
  features/unsupported/USBDevice/targets/TARGET_Freescale/USBHAL_KL25Z.cpp
Labels: needs: CI, release-version: 5.9.1

#7119 NSAPI: Use IPv6 conversion routines from frameworks
  features/netsocket/SocketAddress.cpp
Labels: needs: CI, release-version: 5.9.1

#7176 Fix data aligment problem at STM32F4 hash write
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash.c
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash_ex.c
Labels: needs: CI, release-version: 5.9.1

#7182 Cellular: Disable Greentea tracing to consume less memory
  features/cellular/TESTS/socket/udp/template_mbed_app.json.txt
Labels: needs: CI, release-version: 5.9.1

#7161 Correct PPPCellularInterface::get_gateway()
  features/FEATURE_LWIP/lwip-interface/ppp_lwip.cpp
  features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.cpp
Labels: release-version: 5.9.1

#7151 Fixes for RZ_A1H issue 6543
  rtos/TARGET_CORTEX/SysTimer.cpp
  rtos/TARGET_CORTEX/rtx5/Include/os_tick.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/os_tick_ostm.c
Labels: ready for merge, release-version: 5.9.1

#7166 BLE: fix pairing for misconfigured devices (deny pairing correctly)
  features/FEATURE_BLE/source/generic/GenericSecurityManager.cpp
Labels: ready for merge, release-version: 5.9.1

#6935 ticker test improvement
  TESTS/mbed_drivers/lp_ticker/main.cpp
  TESTS/mbed_drivers/ticker/main.cpp
Labels: ready for merge, release-version: 5.9.1

#6831 Add HAL CRC test and header file
  TESTS/mbed_hal/crc/crc_api_tests.h
  TESTS/mbed_hal/crc/main.cpp
  hal/crc_api.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/mbed_crc_api.c
  targets/TARGET_STM/mbed_crc_api.c
Labels: ready for merge, release-version: 5.9.1

#7131 new mdot bootloader
  tools/bootloaders/MTS_DRAGONFLY_F411RE/bootloader.bin
  tools/bootloaders/MTS_MDOT_F411RE/bootloader.bin
Labels: ready for merge, release-version: 5.9.1

#7185 Fix isochronous endpoints on LPC1768
  usb/device/targets/TARGET_NXP/USBHAL_LPC17.cpp
Labels: needs: review

#7139 Fix greentea test failure on Renesas Cortex-A9 targets
  cmsis/TARGET_CORTEX_A/cmsis_armcc.h
Labels: ready for merge, release-version: 5.9.1

#7117 Fix compile error with MBED_MEM_TRACING_ENABLED and ARMC6
  platform/mbed_retarget.cpp
Labels: ready for merge, release-version: 5.9.1

#7123 BLE: check flags to make sure the IRK has been stored before retrieving it
  features/FEATURE_BLE/ble/generic/SecurityDb.h
Labels: ready for merge, release-version: 5.9.1

#7098 [Wio 3G] Adding platform
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/common/CellularTargets.h
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96.cpp
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96.h
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96_CellularNetwork.cpp
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96_CellularNetwork.h
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96_CellularPower.cpp
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96_CellularPower.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/onboard_modem_api.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/system_clock.c
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, release-version: 5.9.1, scope: new-target

#6962 Cellular: release resources in state machine.
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
  features/cellular/easy_cellular/CellularConnectionFSM.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: ready for merge, release-version: 5.9.1

#7090 Add non-blocking write function for USBCDC
  features/unsupported/USBDevice/USBSerial/USBCDC.cpp
  features/unsupported/USBDevice/USBSerial/USBCDC.h
Labels: ready for merge, release-version: 5.10.0-rc1

#7194 Increased LWIP main worker thread stack size for debug builds
  features/FEATURE_LWIP/lwip-interface/lwipopts.h
Labels: ready for merge, release-version: 5.9.1

#7018 fix typo in a comment
  hal/sai_api.h
Labels: ready for merge

#7152 USB audio
  usb/device/USBAudio/USBAudio.cpp
  usb/device/USBAudio/USBAudio.h
  usb/device/USBAudio/USBAudio_Types.h
  usb/device/utilities/ByteBuffer.cpp
  usb/device/utilities/ByteBuffer.h
Labels: needs: CI

#7197 Tools: Allow exporting of uARM-only targets to uvision
  tools/export/uvision/__init__.py
  tools/toolchains/__init__.py
  tools/toolchains/arm.py
Labels: release-version: 5.9.1

#7051 Extend SAI Driver class documentation
  drivers/SAI.h
Labels: ready for merge

#7196 Tools: Remove second header when every bl config param is used
  tools/config/__init__.py
Labels: ready for merge, release-version: 5.9.1

#7195 Cellular: Semaphore wasn't released in easycellular release build.
  features/cellular/easy_cellular/EasyCellularConnection.cpp
Labels: ready for merge, release-version: 5.9.1

#7128 Fix flash_program_page API in LPC boards.
  TESTS/mbed_hal/flash/functional_tests/main.cpp
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/flash_api.c
Labels: ready for merge, release-version: 5.9.1

#7036 tests-mbed_hal-sleep fix
  TESTS/mbed_hal/sleep/main.cpp
Labels: ready for merge, release-version: 5.9.1

#7058 Fix two issues in ExhaustibleBlockDevice
  features/filesystem/bd/ExhaustibleBlockDevice.cpp
Labels: ready for merge, release-version: 5.9.2

#7209 Tolerate packet loss up to 30% in udp echo tests
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_echotest_burst.cpp
Labels: ready for merge, release-version: 5.9.2

#7215 Fix Kinetis bug causing USB to get stuck sending
  usb/device/targets/TARGET_Freescale/USBPhy_Kinetis.cpp
Labels: ready for merge

#7231 Tools: Force small lib when compiling with uARM
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.9.2

#7174 tools: crash_log_parser: make ELF and MAP parameters optional
  tools/debug_tools/crash_log_parser/crash_log_parser.py
Labels: ready for merge, release-version: 5.10.0-rc1

#7073 NRF52_DK: SLEEP enable
  targets/targets.json
Labels: ready for merge, release-version: 5.9.2

#7208 Added long echo sequence test to EMAC tests
  TESTS/network/emac/README.md
  TESTS/network/emac/emac_test_unicast_long.cpp
  TESTS/network/emac/emac_tests.h
  TESTS/network/emac/emac_util.cpp
  TESTS/network/emac/emac_util.h
  TESTS/network/emac/main.cpp
Labels: ready for merge, release-version: 5.9.2

#7201 LPC54628: Update the ADC clock divider based on the input clock source
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/analogin_api.c
Labels: ready for merge, release-version: 5.9.2

#7211 Nordic BLE: Accept connection parameter update
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/btle/btle.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/btle/btle.cpp
Labels: component: ble, devices: nordic, ready for merge, release-version: 5.9.2

#7237 Enable COG boards instruction cache
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TARGET_EV_COG_AD3029LZ/device/system_ADuCM3029.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TOOLCHAIN_ARM_STD/ADuCM3029.sct
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TOOLCHAIN_GCC_ARM/ADuCM3029.ld
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TOOLCHAIN_IAR/ADuCM3029.icf
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TARGET_EV_COG_AD4050LZ/device/system_ADuCM4050.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TOOLCHAIN_ARM_STD/ADuCM4050.sct
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TOOLCHAIN_GCC_ARM/ADuCM4050.ld
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TOOLCHAIN_IAR/ADuCM4050.icf
  targets/targets.json
Labels: ready for merge, release-version: 5.9.2

#7234 Spelling error in fault handler
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.c
Labels: ready for merge, release-version: 5.9.2

#7225 STM32: Add comments for HAL_InitTick function
  targets/TARGET_STM/hal_tick_16b.c
  targets/TARGET_STM/hal_tick_32b.c
Labels: ready for merge, release-version: 5.9.2

#7233 Fix various USB warnings
  TESTS/usb_device/basic/USBTester.cpp
  TESTS/usb_device/basic/USBTester.h
  usb/device/USBAudio/USBAudio.cpp
  usb/device/USBDevice/EndpointResolver.cpp
  usb/device/USBHID/USBHID.cpp
Labels: needs: CI

#7249 Maxim: Rename files to fix warning
  targets/TARGET_Maxim/TARGET_MAX32620C/mxc/mxc_aes.c
  targets/TARGET_Maxim/TARGET_MAX32625/mxc/mxc_aes.c
  targets/TARGET_Maxim/TARGET_MAX32630/mxc/mxc_aes.c
Labels: ready for merge, release-version: 5.9.2

#7226 Make MTB_ADV_WISE_1570 respect MBED_APP_START & enable bootloader
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/TARGET_MTB_ADV_WISE_1570/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_ARM_MICRO/stm32l486xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_ARM_STD/stm32l486xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_GCC_ARM/STM32L486XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_IAR/stm32l486xx.icf
  targets/targets.json
Labels: ready for merge, release-version: 5.9.2

#7207 Change DNS global class definitions to singletons
  features/netsocket/nsapi_dns.cpp
Labels: ready for merge, release-version: 5.9.2

#6555 Update the STM32 USB driver to the new API
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_pcd.c
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_pcd.h
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_ll_usb.c
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_ll_usb.h
  targets/targets.json
  usb/device/targets/TARGET_STM/USBEndpoints_STM32.h
  usb/device/targets/TARGET_STM/USBPhyHw.h
  usb/device/targets/TARGET_STM/USBPhy_STM32.cpp
Labels: needs: review

#7245 Fix default interface selection by using correct macro names.
  features/netsocket/NetworkInterfaceDefaults.cpp
Labels: ready for merge

#7242 Rename text region in ARM linker file for a few NXP CPUs
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/TOOLCHAIN_ARM_STD/MK66FN2M0xxx18.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/device/TOOLCHAIN_ARM_STD/MK82FN256xxx15.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/device/TOOLCHAIN_ARM_STD/MKL27Z64xxx4.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/device/TOOLCHAIN_ARM_STD/MKL43Z256xxx4.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/device/TOOLCHAIN_ARM_STD/MKL82Z128xxx7.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/device/TOOLCHAIN_ARM_STD/MKW24D512xxx5.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/device/TOOLCHAIN_ARM_STD/MKW41Z512xxx4.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/TARGET_MCU_K22F512/device/TOOLCHAIN_ARM_STD/MK22FN512xxx12.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/device/TOOLCHAIN_ARM_STD/MK24FN1M0xxx12.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_ARM_STD/MK64FN1M0xxx12.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/TOOLCHAIN_ARM_STD/LPC54114J256_cm4.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC546XX/device/TOOLCHAIN_ARM_STD/LPC54628J512.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_ARM_STD/MIMXRT1052xxxxx.sct
Labels: needs: CI, release-version: 5.9.2

#7191 LoRaWAN: Fine tuning timing for delays and receive windows
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/phy/LoRaPHY.cpp
Labels: ready for merge, release-version: 5.9.2

#7263 NRF51 Post-build: Allow Hex BL, SD, APP
  tools/targets/__init__.py
Labels: ready for merge, release-version: 5.9.2

#7261 IAR: Suppress C "bypasses initialization" warning
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge, release-version: 5.9.2

#7259 Provide default WiFi interfaces for Ublox and Realtek
  targets/TARGET_Realtek/TARGET_AMEBA/default_wifi_interface.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/sdk/ublox-odin-w2-drivers/default_wifi_interface.cpp
  targets/targets.json
Labels: ready for merge, release-version: 5.9.2

#7216 Asynchronous DNS greentea tests
  TESTS/netsocket/dns/asynchronous_dns.cpp
  TESTS/netsocket/dns/asynchronous_dns_cache.cpp
  TESTS/netsocket/dns/asynchronous_dns_cancel.cpp
  TESTS/netsocket/dns/asynchronous_dns_external_event_queue.cpp
  TESTS/netsocket/dns/asynchronous_dns_invalid_host.cpp
  TESTS/netsocket/dns/asynchronous_dns_non_async_and_async.cpp
  TESTS/netsocket/dns/asynchronous_dns_simultaneous.cpp
  TESTS/netsocket/dns/asynchronous_dns_simultaneous_cache.cpp
  TESTS/netsocket/dns/asynchronous_dns_simultaneous_repeat.cpp
  TESTS/netsocket/dns/asynchronous_dns_timeouts.cpp
  TESTS/netsocket/dns/dns_tests.h
  TESTS/netsocket/dns/main.cpp
Labels: ready for merge, release-version: 5.9.2

#7206 K64f non-blocking powerup
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/kinetis_emac.cpp
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/fsl_phy.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/fsl_phy.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/fsl_phy.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/fsl_phy.h
Labels: ready for merge, release-version: 5.9.2

#7205 STM32: Fix data alignment issue in HASH function for F2, F7, L4
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_hash.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hash.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hash_ex.c
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_hash.c
Labels: ready for merge, release-version: 5.9.2

#7264 Suppress shift warning for IAR compiler as well
  drivers/MbedCRC.h
Labels: ready for merge, release-version: 5.9.2

#7241 STM32: Reduce HAL_deepsleep stack usage
  targets/TARGET_STM/sleep.c
Labels: ready for merge, release-version: 5.9.2

#7271 Fix lpc43xx serial pin map compiling error
  targets/TARGET_NXP/TARGET_LPC43XX/serial_api.c
Labels: needs: CI

#7266 update arm_pack_manager index
  tools/arm_pack_manager/aliases.json
  tools/arm_pack_manager/index.json
Labels: ready for merge, release-version: 5.9.2

#7272 Add binary drivers for MTB_MXCHIP_EMW3166
  targets/TARGET_WICED/LICENSE-permissive-binary-license-1.0.txt
  targets/TARGET_WICED/README.md
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/wiced_interface/WicedInterface.h
  targets/TARGET_WICED/wiced_interface/wiced_emac.h
  targets/targets.json
Labels: needs: review, release-version: 5.9.2

#7175 Enable new HAL us_ticker API on fast model MPS2 platform
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/us_ticker.c
  targets/targets.json
Labels: needs: CI, release-version: 5.9.2

#7172 Unify RTC, lp ticker, and us ticker for NRF51 and NRF52 series
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF51/flash_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF51/i2c_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF51/trng_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/common_rtc.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/flash_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/i2c_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/lp_ticker.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/us_ticker.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/us_ticker.h
  targets/TARGET_NORDIC/TARGET_NRF5x/common_rtc.c
  targets/TARGET_NORDIC/TARGET_NRF5x/common_rtc.h
  targets/TARGET_NORDIC/TARGET_NRF5x/lp_ticker.c
  targets/TARGET_NORDIC/TARGET_NRF5x/us_ticker.c
Labels: ready for merge, release-version: 5.9.2

#7267 Remove endpoint parameter from USB callbacks
  TESTS/usb_device/basic/USBTester.cpp
  TESTS/usb_device/basic/USBTester.h
  usb/device/USBAudio/USBAudio.cpp
  usb/device/USBAudio/USBAudio.h
  usb/device/USBDevice/USBDevice.cpp
  usb/device/USBDevice/USBDevice.h
  usb/device/USBHID/USBHID.cpp
  usb/device/USBHID/USBHID.h
  usb/device/USBMIDI/USBMIDI.cpp
  usb/device/USBMIDI/USBMIDI.h
  usb/device/USBMSD/USBMSD.cpp
  usb/device/USBMSD/USBMSD.h
  usb/device/USBSerial/USBCDC.cpp
  usb/device/USBSerial/USBCDC.h
Labels: needs: CI

#7274 Travis: fix mongodb key expired error
  .travis.yml
Labels: needs: CI, release-version: 5.9.2

#7288 Fix Greentea test code with wakeup from deepsleep
  TESTS/mbed_hal/sleep/main.cpp
Labels: ready for merge, release-version: 5.9.2

#7283 Update Greentea netsocket and wifi tests
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/udp/main.cpp
  TESTS/network/wifi/wifi_connect_secure_fail.cpp
Labels: ready for merge, release-version: 5.9.2

#7280 Fix SPI initialization for NRF52 series
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/spi_api.c
Labels: ready for merge, release-version: 5.9.2

#7268 USBMSD fixes
  usb/device/USBMSD/USBMSD.cpp
  usb/device/USBMSD/USBMSD.h
Labels: ready for merge

#7220 Fix mbed::InterruptIn.mode() in NRF5x targets
  targets/TARGET_NORDIC/TARGET_NRF5x/gpio_api.c
Labels: ready for merge, release-version: 5.9.2

#6973 Support thread-safety with ARMC6
  rtos/TARGET_CORTEX/mbed_boot.c
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
Labels: needs: CI, release-version: 5.9.2

#7133 Override ROM/RAM start/size for TrustZone targets
  tools/config/__init__.py
  tools/toolchains/__init__.py
Labels: needs: CI, release-version: 5.10.0-rc1

#7291 adding USTICKER label for C027
  targets/targets.json
Labels: ready for merge, release-version: 5.9.2

#7221 Cordio: Add tests that validates a cordio port.
  features/FEATURE_BLE/targets/TARGET_CORDIO/TESTS/cordio_hci/driver/main.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/TESTS/cordio_hci/transport/main.cpp
Labels: component: ble, needs: CI, release-version: 5.9.2

#7145 NRF52: add a separate .nvictable section and allow .noinit to be used…
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_ARM_STD/nRF52832.sct
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_GCC_ARM/NRF52832.ld
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_IAR/nRF52832.icf
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_GCC_ARM/NRF52840.ld
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/reloc_vector_table.c
Labels: ready for merge, release-version: 5.10.0-rc1

#7275 Cellular: fixed defect where SIM interface was closed too early
  features/cellular/easy_cellular/CellularConnectionFSM.cpp
  features/cellular/easy_cellular/CellularConnectionFSM.h
Labels: needs: CI, release-version: 5.9.2

#7262 BLE: Add setScanParams overload to the Gap API
  features/FEATURE_BLE/ble/Gap.h
Labels: ready for merge, release-version: 5.9.2

#7284 Add binary drivers for MTB_USI_WM_BN_BM_22 and MTB_ADV_WISE_1530
  features/FEATURE_BLE/targets/TARGET_CYW4343X/HCIDriver.cpp
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/targets.json
Labels: ready for merge, release-version: 5.9.2

#7296 Add names to Idle/timer thread
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
Labels: ready for merge, release-version: 5.9.2

#6925 Support Flash iAP and Bootloader for GR-PEACH and GR-LYCHEE
  platform/mbed_application.c
  platform/mbed_application.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/MBRZA1LU.sct
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/mem_RZ_A1LU.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_GCC_ARM/RZA1LU.ld
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_IAR/MBRZA1LU.icf
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/inc/iobitmasks/spibsc_iobitmask.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/mbed_sf_boot.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/mmu_RZ_A1LU.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/system_RZ_A1LU.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/mbed_drv_cfg.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/MBRZA1H.sct
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/mem_RZ_A1H.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_GCC_ARM/RZA1H.ld
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_IAR/MBRZA1H.icf
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/inc/iobitmasks/spibsc_iobitmask.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/mbed_sf_boot.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/mmu_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/system_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/mbed_drv_cfg.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/flash_api.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/objects.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/spibsc.h
  targets/targets.json
  tools/arm_pack_manager/index.json
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.9.2

#7218 fix qspi command transfer for NORDIC
  targets/TARGET_NORDIC/TARGET_NRF5x/qspi_api.c
Labels: ready for merge

#7298 Various USB fixes
  usb/device/USBDevice/USBDevice.cpp
  usb/device/USBDevice/USBDevice.h
  usb/device/targets/TARGET_Freescale/USBPhy_Kinetis.cpp
Labels: needs: CI

#7269 Cellular: add cellular network tests
  features/cellular/TESTS/api/cellular_network/main.cpp
  features/cellular/UNITTESTS/at/at_cellularnetwork/Makefile
  features/cellular/UNITTESTS/at/at_cellularnetwork/at_cellularnetworktest.cpp
  features/cellular/UNITTESTS/at/at_cellularnetwork/test_at_cellularnetwork.cpp
  features/cellular/UNITTESTS/at/at_cellularnetwork/test_at_cellularnetwork.h
  features/cellular/UNITTESTS/at/at_cellularsms/test_at_cellularsms.cpp
  features/cellular/UNITTESTS/stubs/ATHandler_stub.cpp
  features/cellular/UNITTESTS/stubs/ATHandler_stub.h
  features/cellular/UNITTESTS/stubs/AT_CellularBase_stub.cpp
  features/cellular/UNITTESTS/stubs/AT_CellularInformation_stub.cpp
  features/cellular/UNITTESTS/stubs/AT_CellularSIM_stub.cpp
  features/cellular/framework/API/CellularPower.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/AT/AT_CellularPower.h
Labels: ready for merge, release-version: 5.9.2

#7214 Error handling configuration updates and Optimization for exception handling
  TESTS/mbed_platform/error_handling/main.cpp
  platform/mbed_error.c
  platform/mbed_error.h
  platform/mbed_error_hist.c
  platform/mbed_error_hist.h
  platform/mbed_lib.json
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.c
  rtos/TARGET_CORTEX/TARGET_CORTEX_M/mbed_rtx_fault_handler.h
Labels: ready for merge, release-version: 5.9.2

#7210 Fix nordic security cancellation
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/nRF5xGap.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/nRF5xGap.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/nRF5xPalSecurityManager.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF51/source/nRF5xn.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xGap.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xGap.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xPalSecurityManager.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NRF52/source/nRF5xn.h
Labels: component: ble, devices: nordic, ready for merge, release-version: 5.9.2

#7243 Disable XTS cipher mode by default when importing Mbed TLS
  features/mbedtls/importer/adjust-config.sh
  features/mbedtls/importer/adjust-no-entropy-config.sh
Labels: component: tls, ready for merge, tracking

#7311 Modify RAM size definition of ARMCC for GR-LYCHEE
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/mem_RZ_A1LU.h
Labels: release-version: 5.9.2

#7192 Create abstract Socket interface
  features/netsocket/InternetSocket.cpp
  features/netsocket/InternetSocket.h
  features/netsocket/NetworkInterface.h
  features/netsocket/NetworkStack.h
  features/netsocket/Socket.h
  features/netsocket/SocketAddress.cpp
  features/netsocket/SocketAddress.h
  features/netsocket/TCPServer.cpp
  features/netsocket/TCPServer.h
  features/netsocket/TCPSocket.cpp
  features/netsocket/TCPSocket.h
  features/netsocket/UDPSocket.cpp
  features/netsocket/UDPSocket.h
Labels: needs: CI, release-version: 5.10.0-rc1

#7299 MBR: Fix issue with MBR init asserting on bad partition size
  features/filesystem/bd/MBRBlockDevice.cpp
Labels: ready for merge, release-version: 5.9.2

#7338 Download astyle from AWS instead of SourceForge
  .travis.yml
Labels: needs: CI, release-version: 5.9.2

#7324 Fix LED_RED mapping on NUCLEO_F429ZI
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PinNames.h
Labels: needs: CI

#7247 Tools: Check compiler version
  tools/build_api.py
  tools/test/toolchains/api_test.py
  tools/toolchains/__init__.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
Labels: ready for merge, release-version: 5.9.2

#7320 Update mbed-coap to version 4.5.0
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_coap_protocol.h
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/module.json
  features/frameworks/mbed-coap/source/include/sn_coap_protocol_internal.h
  features/frameworks/mbed-coap/source/sn_coap_builder.c
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.9.2

#7323 Improve serial performance for NRF52 series
  targets/TARGET_NORDIC/TARGET_NRF5x/README.md
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
Labels: ready for merge, release-version: 5.9.2

#7341 Cellular: improved observing of disconnect for callbacks.
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
Labels: ready for merge, release-version: 5.9.2

#7330 Clean-up targets.json
  targets/targets.json
Labels: ready for merge, release-version: 5.9.2

#7336 Fix connected UDPSocket filtering
  features/netsocket/UDPSocket.cpp
Labels: ready for merge, release-version: 5.9.2

#7344 LoRaWAN: Fixing transport of fatal TX timeout event
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
Labels: ready for merge, release-version: 5.9.2

#7353 build_api script : separate PeripheralPins.o
  tools/build_api.py
Labels: ready for merge, release-version: 5.9.2
