Repository ARMmbed/mbed-os, pull requests merged in 2019-05, with the labels that each got.

#10513 Fix ARMC6 fpu detection for M33 core
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.12.3

#9624 SPI::write: fix number of transmitted symbols.
  drivers/SPI.cpp
Labels: ready for merge, release-version: feature branch

#10493 STM32F303RE: Activate FLASHIAP
  targets/targets.json
Labels: ready for merge, release-version: 5.12.3

#10516 32 Byte key derivation may fail with a 16 Byte ROT key
  features/device_key/source/DeviceKey.cpp
Labels: ready for merge, release-version: 5.12.3

#10435 Add support for QSPI to Cypress Boards
  TESTS/mbed_hal/qspi/flash_configs/S25FL512S_config.h
  TESTS/mbed_hal/qspi/flash_configs/flash_configs.h
  TESTS/mbed_hal/qspi/main.cpp
  TESTS/mbed_hal/qspi/qspi_test_utils.cpp
  TESTS/mbed_hal/qspi/qspi_test_utils.h
  components/storage/blockdevice/COMPONENT_QSPIF/mbed_lib.json
  targets/TARGET_Cypress/TARGET_PSOC6/PeripheralPins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_4343W/PeripheralNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_4343W/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_4343W/PinNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/PeripheralNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/PinNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/PeripheralNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/PinNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062_4343W/PeripheralNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062_4343W/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062_4343W/TARGET_CY8CPROTO_062_4343W/PinNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/PeripheralNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/PinNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/objects.h
  targets/TARGET_Cypress/TARGET_PSOC6/qspi_api.c
  targets/targets.json
Labels: devices: cypress, ready for merge, release-version: 5.12.3

#10471 SDP-K1: Updates to target code
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_SDP_K1/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_SDP_K1/system_clock.c
Labels: ready for merge, release-version: 5.12.3

#10449 Configure UNO_91H to support PDMC compile
  targets/TARGET_RDA/TARGET_UNO_91H/device/TOOLCHAIN_ARM_STD/TARGET_UNO_91H/RDA5981C.sct
  targets/TARGET_RDA/TARGET_UNO_91H/device/TOOLCHAIN_GCC_ARM/TARGET_UNO_91H/RDA5981C.ld
  targets/TARGET_RDA/TARGET_UNO_91H/device/TOOLCHAIN_IAR/TARGET_UNO_91H/RDA5981C.icf
  targets/TARGET_RDA/TARGET_UNO_91H/flash_api.c
  targets/TARGET_RDA/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, release-version: 5.12.3

#10485 NVStore.cpp compiler warning removal (os_ret)
  features/storage/nvstore/source/nvstore.cpp
Labels: ready for merge, release-version: 5.12.3

#10525 Fix 'LICENSE' file 404 link error in README.md
  README.md
Labels: ready for merge, release-version: 5.12.3

#10463 Cellular: Add WISE-1570 handling for socket closing URC
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.h
Labels: ready for merge, release-version: 5.12.3

#10465 Cellular: fix calls to ATHandler::read_string(...) give correct size
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularInformation.cpp
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
Labels: ready for merge, release-version: 5.12.3

#10509 LPC55S69: Add support for UART hardware flow control
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/serial_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_LPCXpresso/PeripheralPins.c
  targets/targets.json
Labels: ready for merge, release-version: 5.12.3

#10355 KVStore: Support external storage out of mbed-os tree
  features/storage/kvstore/conf/filesystem/mbed_lib.json
  features/storage/kvstore/conf/filesystem_no_rbp/mbed_lib.json
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/kvstore/conf/tdb_external/mbed_lib.json
  features/storage/kvstore/conf/tdb_external_no_rbp/mbed_lib.json
Labels: ready for merge, release-version: 5.13.0-rc1

#10468 Add support for CAN to SiLabs targets
  targets/TARGET_Silicon_Labs/TARGET_EFM32/PeripheralNames.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/can_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/emlib/inc/em_can.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/emlib/src/em_can.c
  targets/targets.json
Labels: ready for merge, release-version: 5.12.4

#10496 Allow application to override LWIP_RAW
  features/lwipstack/lwipopts.h
Labels: ready for merge, release-version: 5.12.4

#10524 TRAVIS: turn off upload python test code coverage
  .travis.yml
Labels: ready for merge, release-version: 5.12.4

#10544 Py3 fixes for test scripts
  TESTS/host_tests/rtc_reset.py
  features/storage/filesystem/littlefs/TESTS/host_tests/unexpected_reset.py
Labels: ready for merge

#10530 C027 Fix for modemOn flag
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_UBLOX_C027/ublox_low_level_api.c
Labels: ready for merge, release-version: 5.12.4

#10529 Cellular: Target name change for ublox cellular instance
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/ONBOARD_UBLOX.cpp
Labels: ready for merge, release-version: 5.12.4

#10287 Enable MTS_DRAGONFLY_F411RE to register with Pelion
  components/storage/blockdevice/COMPONENT_SPIF/mbed_lib.json
  features/lwipstack/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/device/TOOLCHAIN_ARM_STD/stm32f411re.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/device/TOOLCHAIN_GCC_ARM/NUCLEO_F411RE.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/device/TOOLCHAIN_GCC_ARM/startup_STM32F41x.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/device/TOOLCHAIN_IAR/stm32f411xe.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/device/flash_data.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/device/system_clock.c
  targets/targets.json
  tools/targets/__init__.py
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 5.12.4

#10527 Nuvoton: Add COMPONENT_FLASHIAP support
  targets/targets.json
Labels: ready for merge, release-version: 5.12.4

#10500 This removes many const char* warnings related with LWIP_ASSERT()
  features/lwipstack/lwip-sys/arch/cc.h
  features/lwipstack/lwip-sys/arch/lwip_sys_arch.c
Labels: ready for merge, release-version: 5.12.4

#10479 STM32WB: Update Flash size
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xG/device/TOOLCHAIN_ARM_MICRO/stm32wb55xx.sct
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xG/device/TOOLCHAIN_ARM_STD/stm32wb55xx.sct
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xG/device/TOOLCHAIN_GCC_ARM/stm32wb55xx.ld
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xG/device/TOOLCHAIN_IAR/stm32wb55xx.icf
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xG/device/flash_data.h
Labels: ready for merge, release-version: 5.12.4

#10512 requirements: update urllib3 to 1.24.2
  requirements.txt
Labels: ready for merge, release-version: 5.12.4

#10511 Cellular: Fix setting of statemachine timeout
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/common/CellularCommon.h
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
Labels: ready for merge, release-version: 5.12.4

#10523 Removing support of FLASHIAP in general_filesystem tests
  features/storage/TESTS/filesystem/general_filesystem/main.cpp
Labels: ready for merge, release-version: 5.12.4

#10538 Enabled crash reporting for DISCO_F407VG target
  platform/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/device/TOOLCHAIN_ARM_MICRO/STM32F407xx.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/device/TOOLCHAIN_ARM_STD/STM32F407xx.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/device/TOOLCHAIN_GCC_ARM/STM32F407XG.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/device/TOOLCHAIN_IAR/stm32f407xx.icf
Labels: ready for merge, release-version: 5.12.4

#10543 Cellular: Increase receiving timeout for UDP echo non-blocking test
  TESTS/netsocket/udp/udpsocket_echotest.cpp
Labels: ready for merge, release-version: 5.12.4

#10541 Adding QSPI support to target RHOMBIO_L476DMW1K
  TESTS/mbed_hal/qspi/flash_configs/flash_configs.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_RHOMBIO_L476DMW1K/PeripheralPins.c
  targets/targets.json
Labels: ready for merge, release-version: 5.12.4

#10539 Add mbed studio flag during assembly
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.12.4

#10534 NANO130: Fix optimization error with NVIC_SetVector/NVIC_GetVector on ARMC6
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_IAR/NANO130.icf
  targets/TARGET_NUVOTON/TARGET_NANO100/device/cmsis_nvic.h
Labels: release-version: 5.12.4

#10505 Improve importer.py
  tools/importer/README.md
  tools/importer/importer.py
Labels: ready for merge, release-version: 5.13.0-rc1

#10456 LWIP 2.1.2 tcpip thread stack overflow fix.
  features/lwipstack/lwip/src/netif/ppp/lwip_utils.c
Labels: ready for merge, release-version: 5.12.4

#10147 Assembler atomics
  TESTS/mbed_platform/atomic/main.cpp
  TESTS/mbed_platform/critical_section/main.cpp
  UNITTESTS/features/lorawan/lorawanstack/unittest.cmake
  UNITTESTS/features/netsocket/DTLSSocket/unittest.cmake
  UNITTESTS/features/netsocket/DTLSSocketWrapper/unittest.cmake
  UNITTESTS/features/netsocket/InternetSocket/unittest.cmake
  UNITTESTS/features/netsocket/TCPServer/unittest.cmake
  UNITTESTS/features/netsocket/TCPSocket/unittest.cmake
  UNITTESTS/features/netsocket/TLSSocket/unittest.cmake
  UNITTESTS/features/netsocket/TLSSocketWrapper/unittest.cmake
  UNITTESTS/features/netsocket/UDPSocket/unittest.cmake
  UNITTESTS/stubs/mbed_atomic_stub.c
  UNITTESTS/stubs/mbed_critical_stub.c
  components/TARGET_PSA/TARGET_MBED_SPM/COMPONENT_SPE/handles_manager.c
  components/TARGET_PSA/TARGET_MBED_SPM/COMPONENT_SPE/spm_common.c
  components/storage/blockdevice/COMPONENT_DATAFLASH/DataFlashBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_FLASHIAP/FlashIAPBlockDevice.cpp
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  features/lorawan/LoRaWANStack.h
  features/netsocket/InternetSocket.cpp
  features/netsocket/InternetSocket.h
  features/storage/blockdevice/BufferedBlockDevice.cpp
  features/storage/blockdevice/ChainingBlockDevice.cpp
  features/storage/blockdevice/ExhaustibleBlockDevice.cpp
  features/storage/blockdevice/FlashSimBlockDevice.cpp
  features/storage/blockdevice/HeapBlockDevice.cpp
  features/storage/blockdevice/MBRBlockDevice.cpp
  features/storage/nvstore/source/nvstore.cpp
  mbed.h
  platform/CircularBuffer.h
  platform/DeepSleepLock.h
  platform/SharedPtr.h
  platform/SingletonPtr.h
  platform/internal/mbed_atomic_impl.c
  platform/internal/mbed_atomic_impl.h
  platform/mbed_atomic.h
  platform/mbed_critical.c
  platform/mbed_critical.h
  platform/mbed_error.c
  platform/mbed_retarget.cpp
  platform/mbed_sleep_manager.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
  targets/TARGET_NUVOTON/TARGET_M2351/crypto/crypto-misc.cpp
  targets/TARGET_NUVOTON/TARGET_M480/crypto/crypto-misc.cpp
  targets/TARGET_NUVOTON/TARGET_NUC472/crypto/crypto-misc.cpp
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/flash_api.c
  targets/TARGET_STM/trng_api.c
  usb/device/USBDevice/USBDevice.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10570 STM32 astyle updates
  targets/TARGET_STM/TARGET_STM32F7/flash_api.c
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xG/TARGET_NUCLEO_WB55RG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xG/TARGET_NUCLEO_WB55RG/system_clock.c
  targets/TARGET_STM/TARGET_STM32WB/flash_api.c
  targets/TARGET_STM/TARGET_STM32WB/wb_sleep.c
  targets/TARGET_STM/mbed_crc_api.c
  targets/TARGET_STM/mbed_rtx.h
  targets/TARGET_STM/stm_spi_api.c
  targets/TARGET_STM/trng_api.c
Labels: ready for merge, release-version: 5.12.4

#10480 SPI: Prime asynch transaction buffer on construction
  drivers/SPI.cpp
Labels: ready for merge, release-version: 5.12.4

#10573 Change "aplication" to "application"
  rtos/Mutex.cpp
Labels: ready for merge, release-version: 5.12.4

#10557 Cellular: Initialize CellularContext member variables in correct class
  UNITTESTS/stubs/CellularContext_stub.cpp
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/device/CellularContext.cpp
Labels: ready for merge, release-version: 5.12.4

#10575 BLE: fix CCC callback not being called when writing to a CCC
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
Labels: ready for merge, release-version: 5.12.4

#10579 Cellular: fix Quectel BG96 missing unlock at socket_connect
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
Labels: ready for merge, release-version: 5.12.4

#10578 Modify PinName file to keep correspondence with spec
  targets/TARGET_TT/TARGET_TT_M3HQ/PinNames.h
  targets/TARGET_TT/TARGET_TT_M4G9/PinNames.h
Labels: ready for merge, release-version: 5.12.4

#10483 PSOC6: move mbed_sdk_init to mbed_overrides.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_4343W/device/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/device/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/device/TARGET_MCU_PSOC6_M0/system_psoc6_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/device/TARGET_MCU_PSOC6_M4/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062_4343W/device/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/device/TARGET_MCU_PSOC6_M0/system_psoc6_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/device/TARGET_MCU_PSOC6_M4/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/mbed_overrides.c
Labels: ready for merge, release-version: 5.12.4

#10520 Permit non-TrustZone ARMv8 build
  components/TARGET_PSA/TARGET_TFM/tf-m-integration.md
  targets/targets.json
  tools/build_api.py
  tools/targets/__init__.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
Labels: ready for merge, release-version: 5.12.4

#10554 Cellular: fixed compile warnings from cellular
  features/cellular/framework/device/CellularContext.cpp
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.cpp
Labels: ready for merge, release-version: 5.12.4

#9443 Add USBCDC_ECM class
  usb/device/USBCDC_ECM/USBCDC_ECM.cpp
  usb/device/USBCDC_ECM/USBCDC_ECM.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10580 BLE: put the acl buffer size in config
  features/FEATURE_BLE/targets/TARGET_CORDIO/mbed_lib.json
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioBLE.cpp
Labels: ready for merge, release-version: 5.13.0-rc1

#10615 This allows CPP application to use the functions from cc.h.
  features/lwipstack/lwip-sys/arch/cc.h
Labels: ready for merge

#10593 Cellular: Fix flow control pin configs for BC95 and Gemalto targets
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
Labels: ready for merge, release-version: 5.13.0-rc1

#10594 ARMC5: fix mbed_atomic_impl.h assembly
  platform/internal/mbed_atomic_impl.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10598 Add Wi-Sun certificate options to mesh api configuration json
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: 5.13.0-rc1

#9960 Use LP tickers for waiting in no RTOS builds when available
  platform/mbed_wait_api_no_rtos.c
Labels: ready for merge, release-version: 5.13.0-rc1

#10476 LWIP TCP socket close - disconnecting fix
  features/lwipstack/LWIPStack.cpp
  features/lwipstack/LWIPStack.h
  features/lwipstack/lwipopts.h
  features/lwipstack/mbed_lib.json
Labels: ready for merge, release-version: 5.13.0-rc1

#10521 TEST: update python script to enable examples smoke test
  tools/test/examples/examples_lib.py
Labels: ready for merge, release-version: 5.13.0-rc1

#10605 K66F: Update SAI and SAI EDMA driver to SDK 2.5
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/drivers/fsl_sai.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/drivers/fsl_sai.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/drivers/fsl_sai_edma.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/drivers/fsl_sai_edma.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10620 Update mbed-coap to version 4.8.0
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_coap_protocol.h
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.13.0-rc1

#10489 gpio_api.h: Clarify desired behaviour for NC
  TESTS/mbed_hal/gpio/main.cpp
  hal/gpio_api.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/gpio_api.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/gpio_api.c
  targets/TARGET_ARM_SSG/TARGET_IOTSS/gpio_api.c
  targets/TARGET_Atmel/TARGET_SAM_CortexM0P/gpio_api.c
  targets/TARGET_Atmel/TARGET_SAM_CortexM4/gpio_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/gpio_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/gpio_api.c
  targets/TARGET_TT/TARGET_TT_M4G9/gpio_api.c
  targets/TARGET_WIZNET/TARGET_W7500x/gpio_api.c
  targets/TARGET_ublox/TARGET_HI2110/gpio_api.c
Labels: ready for merge, release-version: 5.13.0-rc1

#10478 DataFlash: Change erase size to pages to reduce memory usage.
  components/storage/blockdevice/COMPONENT_DATAFLASH/DataFlashBlockDevice.cpp
Labels: ready for merge, release-version: 5.13.0-rc1

#10581 BLE - Management of Tx path on Cordio.
  features/FEATURE_BLE/ble/GattServer.h
  features/FEATURE_BLE/ble/generic/GenericGattClient.h
  features/FEATURE_BLE/ble/pal/PalGattClient.h
  features/FEATURE_BLE/source/generic/GenericGattClient.tpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalAttClient.cpp
Labels: ready for merge, release-version: 5.13.0-rc1

#10606 PSA release script update: add toolchain option
  tools/psa/README.md
  tools/psa/release.py
Labels: ready for merge, release-version: 5.13.0-rc1

#10617 Change W7500 GPIO Driver
  targets/TARGET_WIZNET/TARGET_W7500x/W7500x_Peripheral_Library/W7500x_gpio.c
Labels: ready for merge, release-version: 5.13.0-rc1

#10587 GR_LYCHEE,RZ_A1H,VK_RZ_A1H: Fix greentea test failure with ARMC6
  cmsis/TARGET_CORTEX_A/cmsis_armcc.h
  cmsis/TARGET_CORTEX_A/cmsis_armclang.h
  cmsis/TARGET_CORTEX_A/cmsis_gcc.h
  cmsis/TARGET_CORTEX_A/cmsis_iccarm.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/system_RZ_A1LU.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/system_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/system_VK_RZ_A1H.c
Labels: ready for merge, release-version: 5.13.0-rc1

#10482 Allow NC pins to be instantiated on Silicon Labs platforms
  targets/TARGET_Silicon_Labs/TARGET_EFM32/gpio_api.c
Labels: ready for merge, release-version: 5.13.0-rc1

#10602 Runtime DNS server addition implement
  features/lwipstack/LWIPStack.cpp
  features/lwipstack/LWIPStack.h
  features/lwipstack/lwip/src/core/lwip_dns.c
Labels: ready for merge, release-version: 5.13.0-rc1

#10623 Cellular: fix unit test valgrind warnings
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  UNITTESTS/features/lorawan/loramac/Test_LoRaMac.cpp
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/ATHandler_stub.h
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
Labels: ready for merge, release-version: 5.13.0-rc1

#10621 fix usb_device-msd test python dependencies
  LICENSE.md
  requirements.txt
Labels: ready for merge, release-version: 5.13.0-rc1

#10597 SysTimer should be buildable without lp ticker
  TESTS/mbedmicro-rtos-mbed/systimer/main.cpp
  rtos/TARGET_CORTEX/SysTimer.cpp
  rtos/TARGET_CORTEX/SysTimer.h
  rtos/TARGET_CORTEX/mbed_rtx_idle.cpp
Labels: ready for merge, release-version: 5.13.0-rc1

#10614 Include mbed-greentea==1.7.1 for mbed-os-tools==0.0.8
  requirements.txt
Labels: ready for merge, release-version: 5.13.0-rc1

#10638 Fix AdvertisingDataBuilder UUID Insertion Bug
  features/FEATURE_BLE/source/gap/AdvertisingDataBuilder.cpp
Labels: ready for merge, release-version: 5.13.0-rc1

#10639 Cellular: Preventing Socket ID assignment until actual socket creation at the modem
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularStack.cpp
Labels: ready for merge, release-version: 5.13.0-rc1

#10640 BLE HealthThermometerService: correct GATT characteristics
  features/FEATURE_BLE/ble/services/HealthThermometerService.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10635 BLE: deprecate UARTService and suppress compiler warnings
  features/FEATURE_BLE/ble/services/UARTService.h
  features/FEATURE_BLE/ble/services/URIBeaconConfigService.h
  features/FEATURE_BLE/ble/services/iBeacon.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10473 Add exception case for IPV6 only mode of BG96.
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
Labels: ready for merge, release-version: 5.13.0-rc1

#10591 M2351: Fix serial sync error in SPDMC test
  targets/targets.json
Labels: ready for merge, release-version: 5.13.0-rc1

#10634 BLE: fix deprecated API calls in battery and thermometer services
  features/FEATURE_BLE/ble/services/BatteryService.h
  features/FEATURE_BLE/ble/services/HealthThermometerService.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10636 +UPSND sent to poll activation status
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/ONBOARD_UBLOX.cpp
Labels: ready for merge, release-version: 5.13.0-rc1

#10616 Fix bug Operator new[] out of memory
  targets/TARGET_TT/TARGET_TT_M4G9/device/TOOLCHAIN_GCC_ARM/tmpm4g9f15fg.ld
Labels: ready for merge, release-version: 5.13.0-rc1

#10553 Add semihosting and SWO examples to mbed_override_console().
  platform/mbed_retarget.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10646 Fix deprecation notice for ble::Gap::getState()
  features/FEATURE_BLE/ble/Gap.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10627 Remove targets FUTURE_SEQUANA_M0_PSA and FUTURE_SEQUANA_PSA
  TESTS/mbed_hal/spm/main.cpp
  TESTS/mbedmicro-rtos-mbed/mail/main.cpp
  TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
  TESTS/mbedmicro-rtos-mbed/threads/main.cpp
  features/storage/kvstore/conf/global/mbed_lib.json
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
  features/storage/nvstore/mbed_lib.json
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_M0_PSA/cyprotection.c
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_M0_PSA/cyprotection.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_M0_PSA/cyprotection_config.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_M0_PSA/spm_hal_api.c
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_M0_PSA/spm_init_api.c
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/LICENSE-permissive-binary-license-1.0.txt
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/README.md
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/crypto_access_control.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/psa_release_1.0.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/spm_client.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/spm_server.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/spm_smoke.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/spm_init_api.c
  targets/targets.json
  tools/test/config/config_test.py
Labels: ready for merge, release-version: 5.13.0-rc1

#10625 TESTS: update examples.json to enable testing
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.13.0-rc1

#10442 Cellular: Make AT_CellularContext::get_context() virtual
  features/cellular/framework/AT/AT_CellularContext.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10540 Check in files for the FPGA CI Test Shield
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/DynamicPinList.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/DynamicPinList.h
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/I2CTester.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/I2CTester.h
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/MbedTester.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/MbedTester.h
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/SPIMasterTester.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/SPIMasterTester.h
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/SPISlaveTester.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/SPISlaveTester.h
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/SPITester.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/SPITester.h
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/UARTTester.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/UARTTester.h
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/fpga_config.h
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/test_utils.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10427 Set compilers to C++14 and C11
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/MbedTester.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xGap.cpp
  tools/export/coide/arch_max.coproj.tmpl
  tools/export/coide/arch_pro.coproj.tmpl
  tools/export/coide/disco_f051r8.coproj.tmpl
  tools/export/coide/disco_f100rb.coproj.tmpl
  tools/export/coide/disco_f303vc.coproj.tmpl
  tools/export/coide/disco_f334c8.coproj.tmpl
  tools/export/coide/disco_f401vc.coproj.tmpl
  tools/export/coide/disco_f407vg.coproj.tmpl
  tools/export/coide/disco_f429zi.coproj.tmpl
  tools/export/coide/disco_l053c8.coproj.tmpl
  tools/export/coide/kl05z.coproj.tmpl
  tools/export/coide/kl25z.coproj.tmpl
  tools/export/coide/lpc1768.coproj.tmpl
  tools/export/coide/mote_l152rc.coproj.tmpl
  tools/export/coide/mts_mdot_f405rg.coproj.tmpl
  tools/export/coide/mts_mdot_f411re.coproj.tmpl
  tools/export/coide/nucleo_f030r8.coproj.tmpl
  tools/export/coide/nucleo_f042k6.coproj.tmpl
  tools/export/coide/nucleo_f070rb.coproj.tmpl
  tools/export/coide/nucleo_f072rb.coproj.tmpl
  tools/export/coide/nucleo_f091rc.coproj.tmpl
  tools/export/coide/nucleo_f103rb.coproj.tmpl
  tools/export/coide/nucleo_f302r8.coproj.tmpl
  tools/export/coide/nucleo_f303re.coproj.tmpl
  tools/export/coide/nucleo_f334r8.coproj.tmpl
  tools/export/coide/nucleo_f401re.coproj.tmpl
  tools/export/coide/nucleo_f410rb.coproj.tmpl
  tools/export/coide/nucleo_f411re.coproj.tmpl
  tools/export/coide/nucleo_f446re.coproj.tmpl
  tools/export/coide/nucleo_l053r8.coproj.tmpl
  tools/export/coide/nucleo_l152re.coproj.tmpl
  tools/export/coide/nz32_sc151.coproj.tmpl
  tools/export/coide/ublox_c027.coproj.tmpl
  tools/export/uvision/__init__.py
  tools/export/uvision/uvision.tmpl
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: BREAKING-CHANGE, ready for merge, release-version: 5.13.0-rc1

#10596 Introduce Semaphore::acquire methods
  TESTS/lorawan/loraradio/main.cpp
  TESTS/mbed_drivers/lp_ticker/main.cpp
  TESTS/mbed_drivers/ticker/main.cpp
  TESTS/mbed_drivers/timeout/timeout_tests.h
  TESTS/mbed_drivers/timerevent/main.cpp
  TESTS/mbed_platform/error_handling/main.cpp
  TESTS/mbedmicro-rtos-mbed/event_flags/main.cpp
  TESTS/mbedmicro-rtos-mbed/rtostimer/main.cpp
  TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp
  TESTS/mbedmicro-rtos-mbed/signals/main.cpp
  TESTS/mbedmicro-rtos-mbed/systimer/main.cpp
  TESTS/mbedmicro-rtos-mbed/threads/main.cpp
  TESTS/netsocket/dns/asynchronous_dns_cache.cpp
  TESTS/netsocket/dns/asynchronous_dns_cancel.cpp
  TESTS/netsocket/dns/asynchronous_dns_non_async_and_async.cpp
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/dns/synchronous_dns_cache.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tls/tlssocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/network/emac/emac_util.cpp
  TESTS/network/interface/networkinterface_status.cpp
  TESTS/network/multihoming/multihoming_asynchronous_dns.cpp
  TESTS/network/multihoming/multihoming_udpsocket_echotest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  UNITTESTS/stubs/Semaphore_stub.cpp
  UNITTESTS/stubs/Semaphore_stub.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularContext.cpp
  features/lwipstack/LWIPStack.cpp
  features/lwipstack/LWIPStack.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/mbed-mesh-api/source/LoWPANNDInterface.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  features/nanostack/mbed-mesh-api/source/ThreadInterface.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/netsocket/TCPServer.h
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/kinetis_emac.cpp
  features/netsocket/emac-drivers/TARGET_GD_EMAC/gd32xx_emac.h
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/numaker_emac.h
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_IMX/imx_emac.cpp
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_LPCTarget/lpc17_emac.cpp
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_MCU_LPC546XX/lpc546xx_emac.cpp
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/rda5981x_emac.h
  features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac.h
  features/netsocket/emac-drivers/TARGET_Silicon_Labs/sl_emac.cpp
  rtos/ConditionVariable.cpp
  rtos/Semaphore.cpp
  rtos/Semaphore.h
  rtos/Thread.cpp
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/ipc_rpc.cpp
  targets/TARGET_Realtek/TARGET_AMEBA/rtw_emac.h
  targets/TARGET_WICED/wiced_interface/wiced_emac.h
  usb/device/utilities/AsyncOp.cpp
  usb/device/utilities/events/TaskBase.cpp
Labels: ready for merge, release-version: 5.13.0-rc1

#10686 MAX32630.sct fix
  targets/TARGET_Maxim/TARGET_MAX32630/device/TOOLCHAIN_ARM_STD/MAX3263x.sct
Labels: ready for merge, release-version: 5.13.1

#10680 Add compilation flags to rf_configuration
  components/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.c
Labels: ready for merge, release-version: 5.13.1

#10674 TARGET_TT: adding switches to PinNames
  targets/TARGET_TT/TARGET_TT_M3HQ/PinNames.h
  targets/TARGET_TT/TARGET_TT_M4G9/PinNames.h
Labels: ready for merge, release-version: 5.13.1

#10663 PSOC6: move cmsis.h and device.h out from psoc6pdl directory
  targets/TARGET_Cypress/TARGET_PSOC6/cmsis.h
  targets/TARGET_Cypress/TARGET_PSOC6/device.h
Labels: ready for merge, release-version: 5.13.1

#10656 Cellular: AT_CellularContext disconnect in non-blocking mode
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
Labels: ready for merge, release-version: 5.13.1

#10651 USBHost: Wait for device to implement SET ADDRESS
  features/unsupported/USBHost/USBHost/USBHost.cpp
Labels: ready for merge, release-version: 5.13.1
