Repository ARMmbed/mbed-os, pull requests merged in 2019-03, with the labels that each got.

#9874 Add mbed_lib.json to usb folder
  usb/mbed_lib.json
Labels: ready for merge, release-version: 5.12.0-rc1, risk: A

#9780 Crypto Service - keys access control TESTS
  TESTS/psa/crypto_access_control/COMPONENT_NSPE/main.cpp
  TESTS/psa/crypto_access_control/COMPONENT_PSA_SRV_IPC/test_partition_proxy.c
  TESTS/psa/crypto_access_control/COMPONENT_PSA_SRV_IPC/test_partition_proxy.h
  TESTS/psa/crypto_access_control/COMPONENT_SPE/TARGET_MBED_SPM/psa_test_partition_partition.c
  TESTS/psa/crypto_access_control/COMPONENT_SPE/psa_setup.c
  TESTS/psa/crypto_access_control/COMPONENT_SPE/psa_test_partition_partition.h
  TESTS/psa/crypto_access_control/COMPONENT_SPE/test_partition.c
  TESTS/psa/crypto_access_control/crypto_acl_test_partition_psa.json
  TESTS/psa/crypto_access_control/psa_test_partition_ifs.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/crypto_access_control.hex
Labels: ready for merge, release-version: 5.12.0-rc1, risk: A

#9792 NUCLEO_L073RZ Bootloader support
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/device/TOOLCHAIN_ARM_MICRO/stm32l073xz.sct
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/device/TOOLCHAIN_ARM_STD/stm32l073xz.sct
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/device/TOOLCHAIN_GCC_ARM/STM32L073XZ.ld
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/device/TOOLCHAIN_IAR/stm32l073xx.icf
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/device/system_clock.c
  targets/targets.json
Labels: ready for merge, release-version: 5.12.0-rc1, risk: A

#9800 Bare-metal profile
  platform/bare_metal/mbed_lib.json
Labels: ready for merge, release-version: 5.12.0-rc1, risk: A

#9812 Add wait_ns API
  TESTS/mbed_platform/wait_ns/main.cpp
  platform/mbed_wait_api.h
  platform/mbed_wait_api_no_rtos.c
  targets/TARGET_NUVOTON/TARGET_M2351/device/M2351.h
Labels: ready for merge, release-version: 5.12.0-rc1, risk: A

#9817 Apply artifact_name configuration parameter to exported projects
  tools/export/__init__.py
Labels: ready for merge, release-version: 5.12.0-rc1, risk: A

#9871 ESP8266: receive is able to handle device busy indication
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9883 Free dynamic memory in Crypto Service proxy (PSA targets)
  components/TARGET_PSA/services/crypto/COMPONENT_PSA_SRV_IPC/psa_crypto_spm.c
Labels: ready for merge, release-version: 5.12.0-rc1

#9835 Add define to skip greentea sync
  features/frameworks/greentea-client/source/greentea_test_env.cpp
Labels: needs: CI, release-version: 5.12.0-rc1, risk: A

#9785 Use us ticker for tickless on devs with wrapper
  TESTS/mbedmicro-rtos-mbed/systimer/main.cpp
  rtos/TARGET_CORTEX/mbed_rtx_idle.cpp
  targets/targets.json
Labels: ready for merge, release-version: 5.12.0-rc1

#9891 Correct the device name for NUC472 / M453 - IAR 8
  tools/export/iar/iar_definitions.json
Labels: needs: CI, release-version: 5.12.0-rc1, risk: G

#9885 ESP8266: graceful disconnect on network state timeout
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
Labels: ready for merge, release-version: 5.12.0-rc1, risk: G

#9879 Lock sleep when USB is initialized
  usb/device/targets/TARGET_Freescale/USBPhy_Kinetis.cpp
  usb/device/targets/TARGET_NXP/USBHAL_LPC17.cpp
  usb/device/targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhy_RZ_A1.cpp
  usb/device/targets/TARGET_STM/USBPhy_STM32.cpp
Labels: ready for merge, release-version: 5.12.0-rc1, risk: G

#9866 QSPI write alignment fix for nRF52x
  targets/TARGET_NORDIC/TARGET_NRF5x/qspi_api.c
Labels: ready for merge, release-version: 5.12.0-rc1

#9899 Regenerate mbed-spm files
  TESTS/psa/crypto_access_control/COMPONENT_SPE/psa_setup.c
Labels: ready for merge, release-version: 5.12.0-rc1

#9892 Update PSOC6 postbuild prints
  tools/targets/PSOC6.py
Labels: ready for merge, release-version: 5.12.0-rc1

#9845 Add spi_get_peripheral_name() to stm_spi
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PeripheralNames.h
  targets/TARGET_STM/stm_spi_api.c
Labels: ready for merge, release-version: 5.12.0-rc1

#9797 API to temporarily enable/disable FileHandles
  UNITTESTS/stubs/UARTSerial_stub.cpp
  drivers/UARTSerial.cpp
  drivers/UARTSerial.h
  platform/FileHandle.h
  platform/mbed_retarget.cpp
  platform/mbed_retarget.h
Labels: ready for merge, release-version: 5.12.0-rc1, risk: A

#9898 Cellular: fix connect-disconnect sequence called many times
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  UNITTESTS/stubs/AT_CellularNetwork_stub.cpp
  UNITTESTS/stubs/CellularDevice_stub.cpp
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
Labels: BREAKING-CHANGE, ready for merge, release-version: 5.12.0-rc1

#9469 SPI upgrade - per-peripheral mutex and GPIO-based SSEL
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.h
  drivers/SPI.cpp
  drivers/SPI.h
  drivers/mbed_lib.json
  hal/spi_api.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PeripheralNames.h
Labels: ready for merge, release-version: 5.12.0-rc1, risk: A

#9067 Move socket-stats-enable config to socket-stats-enabled
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tcp/tcpsocket_bind_address.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_invalid.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_null.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_port_fail.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_unopened.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_wrong_type.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tcp/tcpsocket_open_close_repeat.cpp
  TESTS/netsocket/tcp/tcpsocket_open_destruct.cpp
  TESTS/netsocket/tcp/tcpsocket_open_limit.cpp
  TESTS/netsocket/tcp/tcpsocket_open_twice.cpp
  TESTS/netsocket/tls/main.cpp
  TESTS/netsocket/tls/tls_tests.h
  TESTS/netsocket/tls/tlssocket_echotest.cpp
  TESTS/netsocket/tls/tlssocket_open_destruct.cpp
  TESTS/netsocket/tls/tlssocket_open_limit.cpp
  TESTS/netsocket/tls/tlssocket_open_twice.cpp
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udp_tests.h
  TESTS/netsocket/udp/udpsocket_bind_address.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_invalid.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_null.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_port.cpp
  TESTS/netsocket/udp/udpsocket_bind_port.cpp
  TESTS/netsocket/udp/udpsocket_bind_port_fail.cpp
  TESTS/netsocket/udp/udpsocket_bind_unopened.cpp
  TESTS/netsocket/udp/udpsocket_bind_wrong_type.cpp
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_open_close_repeat.cpp
  TESTS/netsocket/udp/udpsocket_open_destruct.cpp
  TESTS/netsocket/udp/udpsocket_open_limit.cpp
  TESTS/netsocket/udp/udpsocket_open_twice.cpp
  TESTS/network/l3ip/main.cpp
  TESTS/network/multihoming/main.cpp
  TESTS/network/multihoming/multihoming_tests.h
  TESTS/network/multihoming/multihoming_udpsocket_echotest.cpp
  UNITTESTS/stubs/SocketStats_Stub.cpp
  features/netsocket/SocketStats.cpp
  features/netsocket/SocketStats.h
  features/netsocket/mbed_lib.json
Labels: PM_ACCEPTED, needs: CI, release-version: 5.12.0-rc1, risk: A

#9906 DOCS: fix doxygen not being generated for BLE classes
  doxyfile_options
Labels: PM_ACCEPTED, needs: CI, release-version: 5.12.0-rc1

#9913 Fix bug in crypto_acl test
  TESTS/psa/crypto_access_control/COMPONENT_NSPE/main.cpp
Labels: release-version: 5.12.0-rc1

#9916 Skip test on Cortex M33 devices
  TESTS/mbed_hal/spm/main.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9915 Update TF-M sources
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_spm.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_thread.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_api.c
  tools/importer/tfm_importer.json
Labels: ready for merge, release-version: 5.12.0-rc1

#9888 ARM Toolchain update to ARM Compiler 6.11(ARMC6)
  TESTS/mbed_platform/stats_sys/main.cpp
  features/storage/FEATURE_STORAGE/cfstore/configuration-store/configuration_store.h
  platform/mbed_retarget.cpp
  rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_core_ca.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_COMMON/softdevice/common/nrf_sdh_ble.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/libraries/experimental_section_vars/nrf_section.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/libraries/experimental_section_vars/nrf_section_iter.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/mem_RZ_A1LU.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/startup_RZ_A1LU.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/startup_RZ_A1LU.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/weak_handler.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/weak_handler.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/mbed_sf_boot.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/mmu_RZ_A1LU.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/mem_RZ_A1H.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/startup_RZ_A1H.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/startup_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/weak_handler.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/weak_handler.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/mbed_sf_boot.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/mmu_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_ARM_STD/mem_VK_RZ_A1H.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_ARM_STD/startup_VK_RZ_A1H.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_ARM_STD/startup_VK_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_ARM_STD/weak_handler.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/mmu_VK_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/flash_api.c
  targets/TARGET_RENESAS/mbed_rtx.h
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/targets.json
  tools/build_api.py
  tools/export/cdt/__init__.py
  tools/export/makefile/__init__.py
  tools/export/uvision/__init__.py
  tools/targets/REALTEK_RTL8195AM.py
  tools/targets/__init__.py
  tools/test/build_api/build_api_test.py
  tools/test/toolchains/api_test.py
  tools/toolchains/arm.py
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc1, risk: A

#9875 Fix multihoming tests
  TESTS/network/multihoming/main.cpp
  TESTS/network/multihoming/multihoming_asynchronous_dns.cpp
  TESTS/network/multihoming/multihoming_synchronous_dns.cpp
  TESTS/network/multihoming/multihoming_tests.h
  TESTS/network/multihoming/multihoming_udpsocket_echotest.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9932 Fix direct access to device key test for small erase/program ratio
  features/storage/TESTS/kvstore/direct_access_devicekey_test/main.cpp
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc1

#9946 Fix include paths for the assembler for makefiles
  tools/export/makefile/__init__.py
Labels: PM_ACCEPTED, needs: CI, release-version: 5.12.0-rc1

#9931 Reduce number of threads in block device test
  features/storage/TESTS/blockdevice/general_block_device/main.cpp
  features/storage/TESTS/filesystem/general_filesystem/main.cpp
Labels: PM_ACCEPTED, needs: CI, release-version: 5.12.0-rc2

#9917 Add attestation doxygen
  components/TARGET_PSA/services/attestation/attestation.h
  components/TARGET_PSA/services/attestation/psa_attest_inject_key.h
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc1

#9738 Tools: Reoder post-build hooks and bl merging
  tools/build_api.py
  tools/hooks.py
  tools/regions.py
  tools/targets/__init__.py
  tools/test/build_api/build_api_test.py
  tools/toolchains/__init__.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
  tools/toolchains/mbed_toolchain.py
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc1, risk: R

#9918 Unify PSA code generators
  .travis.yml
  tools/psa/generate_partition_code.py
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc1

#9940 Reduce flash page size from 512 to 32 bytes in PSOC6 based boards
  targets/TARGET_Cypress/TARGET_PSOC6/flash_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/drivers/include/cy_flash.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/device/drivers/peripheral/flash/cy_flash.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/flash_api.c
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#9894 PSA tools: Find secure image at post-build
  tools/psa/__init__.py
  tools/test/spm/test_find_secure_image.py
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2, risk: R

#9907 BLE - Fix cordio configuration
  features/FEATURE_BLE/source/generic/GenericGap.tpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioBLE.cpp
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#9911 Add TF-M flags to doxygen
  doxyfile_options
  doxygen_options.json
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#9957 Fix issues found in LPC55S69 integration
  TESTS/psa/spm_client/COMPONENT_NSPE/main.cpp
  TESTS/psa/spm_server/COMPONENT_NSPE/main.cpp
  TESTS/psa/spm_server/COMPONENT_SPE/tests.c
  components/TARGET_PSA/TARGET_TFM/mbed_lib.json
Labels: PM_ACCEPTED, needs: CI, release-version: 5.12.0-rc2

#9956 Add attestation doxygen
  components/TARGET_PSA/services/attestation/psa_initial_attestation_api.h
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#9928 Secure binaries release script
  tools/psa/release.py
Labels: PM_ACCEPTED, needs: CI, release-version: 5.12.0-rc2

#9939 Fix for secure partition
  components/TARGET_PSA/services/crypto/COMPONENT_SPE/psa_crypto_partition.c
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/crypto_access_control.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/psa_release_1.0.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/spm_client.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/spm_server.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/spm_smoke.hex
Labels: PM_ACCEPTED, needs: CI, release-version: 5.12.0-rc2

#9963 PSA tools docs
  tools/psa/README.md
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#9976 PSA: Remove unused type which was conflicting wiith errno.h
  components/TARGET_PSA/TARGET_MBED_SPM/psa_defs.h
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#9953 PSA: automatic mocking of PSA targets in test builds
  tools/test_api.py
Labels: PM_ACCEPTED, needs: CI, release-version: 5.12.0-rc2

#9973 TF-M config: Add max_ns_thread_count parameter
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/mbed_lib.json
  features/storage/TESTS/blockdevice/general_block_device/main.cpp
Labels: ready for merge, release-version: 5.12.0-rc2

#9978 PSA: Fix psa/release.py tool
  tools/psa/release.py
Labels: PM_ACCEPTED, needs: CI, release-version: 5.12.0-rc2

#9990 Sync PSA compliance test to latest version
  components/TARGET_PSA/TESTS/compliance_crypto/test_c043/test_c043.c
  features/frameworks/TARGET_PSA/mbed_lib.json
  features/frameworks/TARGET_PSA/pal/pal_mbed_os_intf.cpp
  features/frameworks/TARGET_PSA/psa_manifest/sid.h
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#9982 Nanostack update for Mbed OS 5.12
  features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot/tls_sec_prot_lib.c
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#9977 NUCLEO_L073RZ: IAR linker script issue
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/device/TOOLCHAIN_IAR/stm32l073xx.icf
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#10001 PSA: release.py - add build profile
  tools/psa/release.py
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#10011 Removed cymetadata section from FUTURE_SEQUANA targets
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_CY8C63XX/device/cymetadata.c
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#10002 Disable PSA in baremetal profiles
  components/TARGET_PSA/mbed_lib.json
  tools/psa/tfm/mbed_app.json
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#10012 Generate BLE Static Random Address on U-blox Odin-W2 platform
  features/FEATURE_BLE/targets/TARGET_CORDIO_ODIN_W2/HCIDriver.cpp
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#9996 PSA: Fix error codes masking in psa_attestation_inject_key()
  TESTS/psa/attestation/main.cpp
  components/TARGET_PSA/services/attestation/COMPONENT_PSA_SRV_IPC/psa_attest_inject_key.c
  components/TARGET_PSA/services/attestation/COMPONENT_SPE/psa_attestation_partition.c
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#10026 add needed crypto macros to secure side
  tools/psa/tfm/mbed_app.json
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#10023 Fix crypto compliance tests
  components/TARGET_PSA/TESTS/compliance_crypto/test_c024/test_c024.c
  components/TARGET_PSA/TESTS/compliance_crypto/test_c025/test_c025.c
  components/TARGET_PSA/TESTS/compliance_crypto/test_c039/test_c039.c
  components/TARGET_PSA/TESTS/compliance_crypto/test_c040/test_c040.c
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#10025 PSA: PSoC 6 Correct TRNG behaviour
  targets/TARGET_Cypress/TARGET_PSOC6/trng_api.c
  targets/targets.json
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#10010 Update PSA tools
  tools/psa/README.md
  tools/psa/release.py
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#9997 platform reset API rename
  TESTS/psa/attestation/main.cpp
  TESTS/psa/its_ps/main.cpp
  components/TARGET_PSA/inc/psa/client.h
  components/TARGET_PSA/inc/psa/lifecycle.h
  components/TARGET_PSA/services/platform/COMPONENT_PSA_SRV_EMUL/platform_emul.c
  components/TARGET_PSA/services/platform/COMPONENT_PSA_SRV_IMPL/platform_srv_impl.c
  components/TARGET_PSA/services/platform/COMPONENT_PSA_SRV_IMPL/platform_srv_impl.h
  components/TARGET_PSA/services/platform/COMPONENT_PSA_SRV_IPC/platform_ipc.c
  components/TARGET_PSA/services/platform/COMPONENT_SPE/platform_partition.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/cmsis_nvic_virtual.c
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#10027 TF-M patch: Handle extended stack frame in tfm_svcall_psa_call
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/include/tfm_svcalls.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_svcalls.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_handler.c
  tools/importer/tfm_importer.json
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#10038 PSA: release.py updates to fixes situation where the script would get stuck
  tools/psa/release.py
Labels: PM_ACCEPTED, ready for merge, release-version: 5.12.0-rc2

#10041 Fix include in psa compliance tests to mbedtls config file
  features/frameworks/TARGET_PSA/pal/pal_crypto_config.h
  tools/importer/psa_compliance_importer.json
Labels: PM_ACCEPTED, needs: review, release-version: 5.12.0-rc2

#10033 Port spi_get_peripheral_name fix to some Freescale boards
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/spi_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/TARGET_FRDM/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/spi_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_FRDM/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_RAPIDIOT/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/spi_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/spi_api.c
Labels: PM_ACCEPTED, needs: CI, release-version: 5.12.0-rc2

#10031 Add new mbed-os-example-attestation example
  tools/test/examples/examples.json
Labels: PM_ACCEPTED, needs: work, release-version: 5.12.0-rc2

#10042 BLE: fix conflicting include by qualifying cordio pal includes
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/sec/common/sec_main.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/sec/common/sec_main.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_audio_amp.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_bb.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_bb_ble.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_bb_ble_tester.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_btn.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_cfg.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_crypto.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_io_exp.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_led.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_nvm.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_radio.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_rtc.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_sys.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_timer.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_twi.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/platform/include/pal_uart.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/sources/port/baremetal/wsf_assert.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/sources/port/baremetal/wsf_bufio.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/sources/port/baremetal/wsf_heap.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/sources/port/baremetal/wsf_nvm.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/sources/port/baremetal/wsf_timer.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/sources/port/baremetal/wsf_trace.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack_adaptation/pal_mbed_os_adaptation.cpp
Labels: PM_ACCEPTED, release-version: 5.12.0-rc2

#10046 PSA: release.py bugfix - send the correct parameter to _get_target_info()
  tools/psa/release.py
Labels: ready for merge, release-version: 5.12.0-rc2

#10077 create green-tea init for attestation test
  TESTS/psa/attestation/main.cpp
Labels: ready for merge, release-version: 5.12.0-rc2

#10047 Reduce 32KB from LPC55S69_S binary size
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/TOOLCHAIN_IAR/LPC55S69_cm33_core0_flash.icf
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/partition/flash_layout.h
  targets/targets.json
Labels: ready for merge, release-version: 5.12.0-rc3

#10089 Make the presence of cmsis-pack-manager package optional
  tools/arm_pack_manager/__init__.py
Labels: ready for merge, release-version: 5.12.0-rc3

#10044 Correct check for the ARM toolchain binary in the PATH.
  tools/build.py
  tools/make.py
  tools/test.py
Labels: ready for merge, release-version: 5.12.0-rc3

#9994 Correct FPU settings traceback found by IAR
  tools/export/cmsis/__init__.py
Labels: ready for merge, release-version: 5.12.0-rc3

#9837 Cellular: CGACT not supported in coming firmware in BG96
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  UNITTESTS/stubs/AT_CellularNetwork_stub.cpp
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularContext.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularContext.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularNetwork.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularNetwork.h
Labels: ready for merge, release-version: 5.12.1

#9872 Fix for NUCLEO_F207 UDPSOCKET_ECHOTEST_BURST_NONBLOCK fails.
  features/netsocket/emac-drivers/TARGET_STM_EMAC/mbed_lib.json
Labels: ready for merge, release-version: 5.12.1

#9873 Corrected timeout for +UDNSRN command
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
Labels: ready for merge, release-version: 5.12.1

#9884 STM32F429 ARM MICRO startup file update
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_ARM_MICRO/startup_stm32f429xx.S
Labels: release-version: 5.12.1

#9893 ESP8266: astyle fixes
  .astyleignore
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 5.12.1

#9895 Fix for i2c_t object not being initialized to 0 causing timeout
  targets/TARGET_STM/i2c_api.c
Labels: ready for merge, release-version: 5.12.1

#9902 Remove assertion of MDMRST in case of SARA-R4
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/ublox_low_level_api.c
Labels: ready for merge, release-version: 5.12.1

#9896 wait_us without usticker
  platform/mbed_wait_api_no_rtos.c
Labels: ready for merge, release-version: 5.12.1

#9900 DNS send returning WOULD_BLOCK forces delayed retry
  features/netsocket/nsapi_dns.cpp
Labels: ready for merge, release-version: 5.12.1

#10034 PSA: PSoc 6 configurable secure memory size
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT_M0_PSA/cyprotection_config.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT_PSA/prebuilt/crypto_access_control.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT_PSA/prebuilt/psa_release_1.0.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT_PSA/prebuilt/spm_client.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT_PSA/prebuilt/spm_server.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT_PSA/prebuilt/spm_smoke.hex
  targets/targets.json
Labels: ready for merge, release-version: 5.12.0-rc3

#10101 LPC55S69_S: reduce ITS size to 32KB
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/TOOLCHAIN_IAR/LPC55S69_cm33_core0_flash.icf
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/cmse_lib.o
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/crypto_access_control.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/spm_client.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/spm_server.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/spm_smoke.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/tfm.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/partition/flash_layout.h
  targets/targets.json
Labels: needs: CI, release-version: 5.12.0-rc3

#10088 Temporary disable Crypto HW accelerator on UBLOX_EVK_ODIN_W2
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/mbedtls_device.h
Labels: needs: CI, release-version: 5.12.0-rc3

#10097 Rollup PRs: simple fixes
  TEST_APPS/device/socket_app/cmd_socket.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  features/FEATURE_BLE/source/generic/GenericSecurityManager.tpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  targets/TARGET_Atmel/TARGET_SAM_CortexM0P/TARGET_SAML21J18A/analogout_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C62XX/TARGET_MCU_PSOC6_M0/system_psoc6_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C62XX/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_4343W/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062_4343W/device/system_psoc6.h
  targets/TARGET_GigaDevice/TARGET_GD32E10X/can_api.c
  targets/TARGET_GigaDevice/TARGET_GD32F30X/can_api.c
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/can_api.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/PeripheralPins.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/i2c_api.c
Labels: ready for merge

#9925 SAML21J18A: #endif without #if in analogout_api.c
  targets/TARGET_Atmel/TARGET_SAM_CortexM0P/TARGET_SAML21J18A/analogout_api.c
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9930 NUCLEO_H743ZI: Arduino A5 is mapped on ADC3_IN6
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/PeripheralPins.c
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9965 Fix undefined tr_debug for QUECTEL_BG96 cellular feature
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9972 cellular: BC95 memory leak fix
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9979 TEST_APPS socket_app leaks memory when cannot initialize packetSizes
  TEST_APPS/device/socket_app/cmd_socket.cpp
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9980 Dead pointer usage in GenericSecurityManager
  features/FEATURE_BLE/source/generic/GenericSecurityManager.tpp
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9985 GigaDevice targets can return uninitialized variable in CAN driver
  targets/TARGET_GigaDevice/TARGET_GD32E10X/can_api.c
  targets/TARGET_GigaDevice/TARGET_GD32F30X/can_api.c
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/can_api.c
Labels: needs: CI, release-version: 5.12.1, rollup PR

#10048 Fix for reallocation memory fail in TMPM46B
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/i2c_api.c
Labels: needs: CI, release-version: 5.12.1, rollup PR

#10073 Removed PSoC6 SystemInit Workaround for ARM compiler
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C62XX/TARGET_MCU_PSOC6_M0/system_psoc6_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C62XX/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_4343W/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062_4343W/device/system_psoc6.h
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9905 Tests: check if recv returned too much data
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest_burst.cpp
  TESTS/netsocket/tcp/tcpsocket_recv_100k.cpp
  TESTS/netsocket/tls/tlssocket_echotest.cpp
  TESTS/netsocket/tls/tlssocket_echotest_burst.cpp
Labels: ready for merge, release-version: 5.12.1

#10116 Rollup pt2: fixes for 5.12.1
  TESTS/mbed-crypto/sanity/main.cpp
  TESTS/mbed_hal/spm/main.cpp
  TESTS/psa/attestation/main.cpp
  TESTS/psa/crypto_access_control/COMPONENT_NSPE/main.cpp
  TESTS/psa/crypto_init/main.cpp
  TESTS/psa/entropy_inject/main.cpp
  TESTS/psa/its_ps/main.cpp
  TESTS/psa/spm_client/COMPONENT_NSPE/main.cpp
  TESTS/psa/spm_server/COMPONENT_NSPE/main.cpp
  TESTS/psa/spm_smoke/COMPONENT_NSPE/main.cpp
  UNITTESTS/features/cellular/framework/device/cellularstatemachine/cellularstatemachinetest.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/CordioHCIDriver.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
  features/frameworks/TARGET_PSA/val_greentea.cpp
  features/lwipstack/lwip-sys/arch/cc.h
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/unsupported/tests/mbed/tsi/main.cpp
  requirements.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/sdk/ublox-odin-w2-drivers/OdinWiFiInterface.cpp
Labels: ready for merge

#9914 Remove #ifndef NO_GREENTEA from tests
  TESTS/mbed-crypto/sanity/main.cpp
  TESTS/mbed_hal/spm/main.cpp
  TESTS/psa/attestation/main.cpp
  TESTS/psa/crypto_access_control/COMPONENT_NSPE/main.cpp
  TESTS/psa/crypto_init/main.cpp
  TESTS/psa/entropy_inject/main.cpp
  TESTS/psa/its_ps/main.cpp
  TESTS/psa/spm_client/COMPONENT_NSPE/main.cpp
  TESTS/psa/spm_server/COMPONENT_NSPE/main.cpp
  TESTS/psa/spm_smoke/COMPONENT_NSPE/main.cpp
  features/frameworks/TARGET_PSA/val_greentea.cpp
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9924 Update Wi-SUN network default name
  features/nanostack/mbed-mesh-api/mbed_lib.json
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9936 Fix lwip to compile if MBED_CONF_LWIP_DEBUG_ENABLED is defined
  features/lwipstack/lwip-sys/arch/cc.h
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9937 Cellular: removed manual registering state.
  UNITTESTS/features/cellular/framework/device/cellularstatemachine/cellularstatemachinetest.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9948 BLE:Cordio:insert_descriptor check r/w properties
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9984 tsi/main.cpp is using wrong `printf` format
  features/unsupported/tests/mbed/tsi/main.cpp
Labels: needs: CI, rollup PR

#9986 OdinWifiInterface is calling memcpy with a null pointer
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/sdk/ublox-odin-w2-drivers/OdinWiFiInterface.cpp
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9998 Remove intervaltree from requirements.txt for mbed-os as it contradic…
  requirements.txt
Labels: needs: CI, release-version: 5.12.1, rollup PR

#10093 BLE:Fix cordio reset sequence
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/CordioHCIDriver.cpp
Labels: needs: CI, release-version: 5.12.1, rollup PR

#10102 Remove fuzzywuzzy dependency
  requirements.txt
Labels: needs: CI, release-version: 5.12.1, rollup PR

#9941 Add missing RSPIF component to the defaut BlockDevice handler
  features/storage/system_storage/SystemStorage.cpp
Labels: ready for merge, release-version: 5.12.1

#10113 Use secure/non-secure rom for bl modes
  tools/config/__init__.py
  tools/test/config/config_test.py
Labels: ready for merge, release-version: 5.12.0-rc3

#10106 Update manifest tool to version 1.4.8 and install it from pypi
  requirements.txt
Labels: ready for merge, release-version: 5.12.1

#10086 Add bootloader support for the LPC55S69 board
  features/FEATURE_BOOTLOADER/targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/mbed-bootloader-lpc55s69-v1_0_0.hex
  features/FEATURE_BOOTLOADER/targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/mbed_lib.json
  platform/mbed_application.c
  platform/mbed_application.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/TOOLCHAIN_ARMC6/LPC55S69_cm33_core0_flash.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/TOOLCHAIN_GCC_ARM/LPC55S69_cm33_core0_flash.ld
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/TOOLCHAIN_IAR/LPC55S69_cm33_core0_flash.icf
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/cmsis_nvic_virtual.c
  targets/targets.json
  tools/psa/__init__.py
  tools/targets/LPC55S69.py
Labels: needs: CI, release-version: 5.12.0-rc3

#9801 Correctly include EventQueue.h
  TESTS/netsocket/dns/main.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularbase/at_cellularbasetest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularinformation/at_cellularinformationtest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/at_cellularsmstest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/at_cellularstacktest.cpp
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  UNITTESTS/features/lorawan/lorawanstack/Test_LoRaWANStack.cpp
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/CellularDevice_stub.cpp
  UNITTESTS/stubs/EventQueue_stub.cpp
  UNITTESTS/target_h/events/mbed_events.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/SimpleEventQueue.h
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.h
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_fhss_timer.cpp
  features/netsocket/NetworkStack.cpp
  features/netsocket/nsapi_dns.cpp
Labels: ready for merge, release-version: 5.12.1

#9919 BLE - Report extended advertising in legacy handler
  features/FEATURE_BLE/source/generic/GenericGap.tpp
Labels: ready for merge, release-version: 5.12.1

#9921 BLE:Cordio:Fix insert characteristic not handle error
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
Labels: ready for merge, release-version: 5.12.1

#9935 Increased timeout for lwip waiting netif_is_link_up
  features/lwipstack/LWIPInterface.cpp
  features/lwipstack/lwipopts.h
Labels: ready for merge, release-version: 5.12.1

#9952 Fix PWM driver of RZ/A1
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/PeripheralNames.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/PeripheralPins.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/PeripheralNames.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/PeripheralNames.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/pwmout_api.c
Labels: ready for merge, release-version: 5.12.1

#9964 Add imports of basestring for python 3
  tools/build_release.py
  tools/export/__init__.py
  tools/targets/lint.py
Labels: ready for merge, release-version: 5.12.1

#9988 BLE: fix tick rate set to 10 ms
  features/FEATURE_BLE/targets/TARGET_CORDIO/mbed_lib.json
Labels: ready for merge, release-version: 5.12.1

#9992 BLE - Use low power timing primitives
  features/FEATURE_BLE/ble/generic/GenericGap.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioBLE.h
Labels: ready for merge, release-version: 5.12.1

#10014 Update nanostack-interface error mapping
  features/nanostack/nanostack-interface/Nanostack.cpp
Labels: ready for merge, release-version: 5.12.1

#10065 Correct post-build-hook detection logic
  tools/targets/__init__.py
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 5.12.1

#10084 Cellular: AT information response to return false on empty prefix
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
Labels: ready for merge, release-version: 5.12.1

#10092 BLE:fix on_phy_update_complete function
  features/FEATURE_BLE/ble/pal/PalGap.h
Labels: ready for merge, release-version: 5.12.1

#10100 Cellular: Support Cinterion EHS5-E cellular module
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.h
Labels: ready for merge, release-version: 5.12.1

#10118 Selectively append changes to exported config files
  tools/export/exporters.py
Labels: ready for merge, release-version: 5.12.1

#10122 mbed_error.c: fix warnings
  platform/mbed_error.c
Labels: ready for merge, release-version: 5.12.1

#10029 Cellular: Remove compile dependency of UARTSerial
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/device/CellularContext.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
Labels: ready for merge, release-version: 5.12.1

#10045 Uvision exporter fixes for Python 3, CPM updates, and Windows path issues
  tools/export/exporters.py
  tools/export/uvision/__init__.py
Labels: ready for merge, release-version: 5.12.1

#10098 Cinterion Cellular: Setup connection profile with username and password
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularContext.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.h
Labels: ready for merge, release-version: 5.12.1

#10081 Cellular: call AT+CGEREP after sim is ready
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  UNITTESTS/stubs/AT_CellularNetwork_stub.cpp
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/AT/AT_CellularBase.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.cpp
  features/cellular/framework/targets/GENERIC/GENERIC_AT3GPP/GENERIC_AT3GPP.cpp
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26.cpp
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/PPP/UBLOX_PPP.cpp
Labels: ready for merge, release-version: 5.12.1

#10105 test_configs: generic app config for boards with Wi-Fi
  tools/test_configs/WiFiInterface.json
Labels: ready for merge, release-version: 5.12.1

#10108 Fix functionality for FlashIAPBD & SlicingBD
  components/storage/blockdevice/COMPONENT_FLASHIAP/FlashIAPBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_FLASHIAP/FlashIAPBlockDevice.h
  features/storage/blockdevice/BlockDevice.h
  features/storage/blockdevice/SlicingBlockDevice.cpp
  features/storage/blockdevice/SlicingBlockDevice.h
Labels: ready for merge, release-version: 5.12.0-rc3

#10159 Update secure binaries for RC3
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT_PSA/prebuilt/crypto_access_control.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT_PSA/prebuilt/psa_release_1.0.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT_PSA/prebuilt/spm_client.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT_PSA/prebuilt/spm_server.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT_PSA/prebuilt/spm_smoke.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/crypto_access_control.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/psa_release_1.0.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/spm_client.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/spm_server.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/spm_smoke.hex
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/crypto_access_control.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/spm_client.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/spm_server.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/spm_smoke.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/tfm.bin
Labels: needs: review

#10005 cellular: remove last CELLULAR_DEVICE references
  features/cellular/TESTS/api/cellular_information/main.cpp
  features/cellular/TESTS/socket/udp/main.cpp
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/common/CellularTargets.h
  features/cellular/framework/device/CellularDevice.cpp
Labels: ready for merge, release-version: 5.12.1

#10140 Cellular: fix astyle for files that already in master
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularSMS.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularStack.h
Labels: ready for merge, release-version: 5.12.1

#10157 Deduplicate IAR MBED_ROM__xxxx defines
  tools/config/__init__.py
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 5.12.0-rc4

#10149 STM32H7 ADC internal channels
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/analogin_device.c
Labels: ready for merge, release-version: 5.12.1

#10133 Adding STM32_F439 as a new MTB target
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MTB_STM32_F439/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MTB_STM32_F439/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MTB_STM32_F439/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MTB_STM32_F439/system_clock.c
  targets/targets.json
Labels: ready for merge, release-version: 5.12.1, scope: new-target

#10142 Nanostack 802.15.4 RF drivers update
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.cpp
  components/802.15.4_RF/mcr20a-rf-driver/source/NanostackRfPhyMcr20a.cpp
  components/802.15.4_RF/stm-s2lp-rf-driver/README.md
  components/802.15.4_RF/stm-s2lp-rf-driver/source/NanostackRfPhys2lp.cpp
  components/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.c
Labels: ready for merge, release-version: 5.12.1

#10138 Cellular: don't allow ATHandler read/write if filehandle not usable
  features/cellular/framework/AT/ATHandler.cpp
Labels: ready for merge, release-version: 5.12.1

#10120 Cellular: Fix network interface test for cellular targets
  TESTS/network/interface/networkinterface_status.cpp
Labels: ready for merge, release-version: 5.12.1

#10173 Collect excluded libraries into ignored_dirs
  tools/resources/__init__.py
  tools/test/resources/resource_test.py
Labels: ready for merge, release-version: 5.12.0-rc4

#10172 Cellular: Fix plmn trace for IAR
  features/cellular/framework/AT/AT_CellularContext.cpp
Labels: ready for merge, release-version: 5.12.0-rc4

#9444 Usb msd tests
  TESTS/host_tests/pyusb_msd.py
  TESTS/usb_device/msd/README.md
  TESTS/usb_device/msd/TestUSBMSD.h
  TESTS/usb_device/msd/main.cpp
  usb/device/USBMSD/USBMSD.cpp
  usb/device/USBMSD/USBMSD.h
Labels: ready for merge, release-version: 5.12.1

#10144 Atmel RF: use system wait_ns
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.cpp
Labels: ready for merge, release-version: 5.12.1

#9959 Refactor socket stats to reduce boiler plate
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_invalid.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_null.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_port_fail.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_unopened.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_wrong_type.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tcp/tcpsocket_open_close_repeat.cpp
  TESTS/netsocket/tcp/tcpsocket_open_destruct.cpp
  TESTS/netsocket/tcp/tcpsocket_open_twice.cpp
  TESTS/netsocket/tls/main.cpp
  TESTS/netsocket/tls/tlssocket_echotest.cpp
  TESTS/netsocket/tls/tlssocket_open_destruct.cpp
  TESTS/netsocket/tls/tlssocket_open_limit.cpp
  TESTS/netsocket/tls/tlssocket_open_twice.cpp
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udpsocket_bind_address.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_invalid.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_null.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_port.cpp
  TESTS/netsocket/udp/udpsocket_bind_port.cpp
  TESTS/netsocket/udp/udpsocket_bind_port_fail.cpp
  TESTS/netsocket/udp/udpsocket_bind_unopened.cpp
  TESTS/netsocket/udp/udpsocket_bind_wrong_type.cpp
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_open_close_repeat.cpp
  TESTS/netsocket/udp/udpsocket_open_destruct.cpp
  TESTS/netsocket/udp/udpsocket_open_twice.cpp
Labels: ready for merge, release-version: 5.12.1

#10187 Fall back to configuration information when CPM reports no memories
  tools/config/__init__.py
Labels: needs: review, release-version: 5.12.0-rc4

#10188 Configure sector information in `targets.json`
  tools/config/__init__.py
Labels: needs: review, release-version: 5.12.0-rc4

#10180 Fix SPIF speed for MTB_ADV_WISE_1570 and max packet size for BC95
  components/storage/blockdevice/COMPONENT_SPIF/mbed_lib.json
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
Labels: ready for merge, release-version: 5.12.1

#10179 Cellular: C030_N2XX default interface
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.cpp
Labels: ready for merge, release-version: 5.12.1

#10178 Nuvoton: Remove SD component from targets.json
  targets/targets.json
Labels: ready for merge, release-version: 5.12.1

#10166 Travis CI: Tweak astyle to not over-exclude files
  .astyleignore
  TESTS/mbed_hal/stack_size_unification/main.cpp
  TESTS/mbed_hal/stack_size_unification/stack_size_unification.h
  usb/device/targets/TARGET_Freescale/USBPhyHw.h
  usb/device/targets/TARGET_Freescale/USBPhy_Kinetis.cpp
  usb/device/targets/TARGET_NXP/USBHAL_LPC17.cpp
  usb/device/targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhyHw.h
  usb/device/targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhy_RZ_A1.cpp
  usb/device/targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhy_RZ_A1_Def.h
  usb/device/targets/TARGET_STM/USBPhyHw.h
  usb/device/targets/TARGET_STM/USBPhy_STM32.cpp
  usb/device/targets/TARGET_Template/USBPhyHw.h
  usb/device/targets/TARGET_Template/USBPhy_template.cpp
Labels: ready for merge, release-version: 5.12.1
