Repository ARMmbed/mbed-os, pull requests merged in 2019-11, with the labels that each got.

#11786 Discard join accept if it is not received in a class A RX window afte…
  features/lorawan/lorastack/mac/LoRaMac.cpp
Labels: needs: CI, release-version: feature branch

#11789 STM32H7: code and feature alignment for both NUCLEO and DISCO targets
  features/storage/kvstore/conf/global/mbed_lib.json
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI2/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI2/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI2/system_clock.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/device/TOOLCHAIN_ARM_STD/stm32h743xI.sct
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/device/TOOLCHAIN_GCC_ARM/STM32H743xI.ld
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/device/TOOLCHAIN_IAR/stm32h743xI.icf
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/flash_data.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/system_clock.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I_CM7/TOOLCHAIN_ARM_STD/stm32h747xI.sct
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I_CM7/TOOLCHAIN_GCC_ARM/STM32H747xI.ld
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I_CM7/TOOLCHAIN_IAR/stm32h747xI.icf
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/flash_data.h
  targets/TARGET_STM/TARGET_STM32H7/flash_api.c
  targets/targets.json
  tools/targets/STM32_gen_PeripheralPins.py
Labels: ready for merge, release-version: 5.14.2

#11780 Nuvoton: Add implementations of HAL API i2c_free and analogin_free
  targets/TARGET_NUVOTON/TARGET_M2351/analogin_api.c
  targets/TARGET_NUVOTON/TARGET_M2351/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M251/analogin_api.c
  targets/TARGET_NUVOTON/TARGET_M251/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M261/analogin_api.c
  targets/TARGET_NUVOTON/TARGET_M261/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M451/analogin_api.c
  targets/TARGET_NUVOTON/TARGET_M451/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M480/analogin_api.c
  targets/TARGET_NUVOTON/TARGET_M480/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/analogin_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/analogin_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/i2c_api.c
Labels: ready for merge, release-version: 5.14.2

#11475 TEST: add atecc608a example to compilation test
  tools/test/examples/examples.json
Labels: release-version: 5.14.2

#11772 Cellular: updated cellular context flags and cid in ublox-api
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.cpp
Labels: ready for merge, release-version: 5.14.2

#11641 PmwOut: Add method to enable/disable PWM
  UNITTESTS/drivers/PwmOut/test_pwmout.cpp
  UNITTESTS/drivers/PwmOut/unittest.cmake
  UNITTESTS/stubs/pwmout_api_stub.c
  UNITTESTS/target_h/PinNames.h
  UNITTESTS/target_h/objects.h
  UNITTESTS/target_h/platform/mbed_power_mgmt.h
  drivers/PwmOut.h
  drivers/source/PwmOut.cpp
Labels: ready for merge, release-version:6.0.0-rc1

#11783 Adding set baud rate routine
  TESTS/netsocket/tcp/tcpsocket_recv_100k.cpp
  UNITTESTS/features/cellular/framework/AT/athandler/unittest.cmake
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  UNITTESTS/target_h/myCellularDevice.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.h
Labels: ready for merge, release-version:6.0.0-rc1

#11279 Add API to get ipv6 link local address
  TESTS/network/interface/README.md
  TESTS/network/interface/networkinterface_status.cpp
  UNITTESTS/features/netsocket/EthernetInterface/test_EthernetInterface.cpp
  UNITTESTS/stubs/NetworkInterface_stub.cpp
  UNITTESTS/stubs/NetworkStack_stub.cpp
  features/lwipstack/LWIPInterface.cpp
  features/lwipstack/LWIPStack.h
  features/lwipstack/lwip_tools.cpp
  features/netsocket/EMACInterface.cpp
  features/netsocket/EMACInterface.h
  features/netsocket/NetworkInterface.cpp
  features/netsocket/NetworkInterface.h
  features/netsocket/NetworkStack.cpp
  features/netsocket/NetworkStack.h
  features/netsocket/OnboardNetworkStack.h
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
Labels: devices: cypress, needs: CI, release-version:6.0.0-rc1

#11693 UDPSOCKET_ECHOTEST change to tolerate duplicate packets
  TESTS/netsocket/udp/udpsocket_echotest.cpp
Labels: ready for merge, release-version: 5.14.2

#11375 NSAPI DNS query IP version check for non LWIP stacks.
  features/netsocket/nsapi_dns.cpp
Labels: ready for merge, release-version: 5.14.2

#11683 Baremetal profile fixes
  UNITTESTS/features/cellular/framework/device/cellularstatemachine/unittest.cmake
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
  features/netsocket/L3IPInterface.cpp
Labels: ready for merge, release-version: 5.14.2

#11719 Ensure modem echo is off before sending other AT commands
  features/cellular/framework/AT/AT_CellularDevice.cpp
Labels: ready for merge, release-version: 5.14.2

#11808 Document Socket API functions return values.
  features/netsocket/DTLSSocket.h
  features/netsocket/InternetDatagramSocket.h
  features/netsocket/InternetSocket.h
  features/netsocket/Socket.h
  features/netsocket/TCPSocket.h
  features/netsocket/TLSSocket.h
  features/netsocket/TLSSocketWrapper.h
Labels: ready for merge, release-version: 5.14.2

#11800 Update common Cypress libraries
  targets/TARGET_Cypress/TARGET_PSOC6/common/cy_network_buffer.c
  targets/TARGET_Cypress/TARGET_PSOC6/common/cy_network_buffer.h
  targets/TARGET_Cypress/TARGET_PSOC6/common/cy_serial_flash_prog.c
  targets/TARGET_Cypress/TARGET_PSOC6/common/cy_serial_flash_qspi.c
  targets/TARGET_Cypress/TARGET_PSOC6/mbed_overrides.c
Labels: devices: cypress, ready for merge

#11782 equeue: avoid non-standard bit shifts
  events/source/equeue.c
  events/source/tests/tests.c
Labels: ready for merge, release-version: 5.14.2

#11813 Fix ARM issue 11795: - Cypress: SPI FPGA test: tester always respond …
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_spi.c
Labels: ready for merge, release-version: 5.14.2

#11815 Updated targets.json file to go along with pr-11770
  targets/targets.json
Labels: needs: CI, release-version: 5.14.2

#11811 STM32H7 FLASH API issue with M4 core
  targets/TARGET_STM/TARGET_STM32H7/flash_api.c
Labels: ready for merge, release-version: 5.14.2

#11810 SecureStore: Add member initializers for inc_handle_t
  features/storage/kvstore/securestore/SecureStore.cpp
Labels: devices: cypress, ready for merge

#11829 USB STM32: Don't wrap direct function calls in MBED_ASSERT
  targets/TARGET_STM/USBPhy_STM32.cpp
Labels: ready for merge, release-version: 5.14.2

#11818 Adding baud rate setting to TLS and UDP echo burst tests
  TESTS/netsocket/tls/main.cpp
  TESTS/netsocket/udp/udpsocket_echotest_burst.cpp
Labels: ready for merge, release-version: 5.14.2

#11755 Unittests for nsapi_dns
  UNITTESTS/features/netsocket/nsapi_dns/test_nsapi_dns.cpp
  UNITTESTS/features/netsocket/nsapi_dns/unittest.cmake
  UNITTESTS/stubs/NetworkStack_stub.cpp
  features/netsocket/nsapi_dns.cpp
Labels: ready for merge, release-version: 5.14.2

#11816 Fix failure of building non-RTOS for GR-PEACH, GR-LYCHEE and VK-RZ/A1H
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/os_tick_ostm.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/os_tick_ostm.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/os_tick_ostm.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/sleep.c
Labels: ready for merge, release-version: 5.14.2

#11682 Make FPGA tests to pass on CI targets (SPI, analogIn, PWM)
  TESTS/mbed_hal_fpga_ci_test_shield/pwm/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
  hal/mbed_compat.c
  hal/spi_api.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/pwmout_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/spi_api.c
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/TARGET_NUCLEO_F303RE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/PeripheralPins.c
Labels: ready for merge, release-version:6.0.0-rc1

#11830 Cypress: Add implementation of free() for gpio
  targets/TARGET_Cypress/TARGET_PSOC6/cy_analogin_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/cy_gpio_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/cy_i2c_api.c
Labels: Priority-Medium, devices: cypress, ready for merge

#11831 BLE: Added call to delete the security database object upon SM reset.
  features/FEATURE_BLE/source/generic/GenericSecurityManager.tpp
Labels: ready for merge, release-version: 5.14.2

#11823 IOTBTOOL-333: Fix SimpleQueue build failure on py3
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 5.14.2

#11634 Serial design draft
  docs/design-documents/drivers/serial/diagrams/buffered-serial.png
  docs/design-documents/drivers/serial/diagrams/buffered-serial.xml
  docs/design-documents/drivers/serial/diagrams/retarget.png
  docs/design-documents/drivers/serial/diagrams/retarget.xml
  docs/design-documents/drivers/serial/diagrams/serial-classes.png
  docs/design-documents/drivers/serial/diagrams/serial-classes.xml
  docs/design-documents/drivers/serial/diagrams/unbuffered-serial.png
  docs/design-documents/drivers/serial/diagrams/unbuffered-serial.xml
  docs/design-documents/drivers/serial/serial.md
Labels: ready for merge, release-version:6.0.0-rc1

#11839 SerialBase.h|cpp [-Wreorder] compiler warning fix
  drivers/SerialBase.h
  drivers/source/SerialBase.cpp
Labels: ready for merge, release-version: 5.14.2

#11836 Add sender address and port verification to UDPSOCKET_ECHOTEST
  TESTS/netsocket/udp/udpsocket_echotest.cpp
Labels: ready for merge, release-version: 5.14.2

#11834 Fix flag checks to allow disabling unsecure tests
  TESTS/network/wifi/main.cpp
Labels: ready for merge, release-version: 5.14.2

#11833 TESTS: turn off blinky log compare test due to example changed
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.14.2

#11822 TLSSOCKET_HANDSHAKE_INVALID test skip if DNS AAA record not available.
  TESTS/netsocket/tls/tlssocket_handshake_invalid.cpp
Labels: ready for merge, release-version: 5.14.2

#11651 TF-M: Python script to clone TF-M
  tools/psa/build_tfm.py
Labels: ready for merge, release-version: feature branch

#11814 USBMSD: implement MODE SENSE (10) command
  drivers/USBMSD.h
  drivers/source/usb/USBMSD.cpp
Labels: ready for merge, release-version: 5.14.2

#11827 DISCO STM32H747I ETHERNET support, but disabled.
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/TARGET_DISCO_H747I/stm32h7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I_CM7/TOOLCHAIN_ARM_STD/stm32h747xI.sct
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I_CM7/TOOLCHAIN_GCC_ARM/STM32H747xI.ld
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I_CM7/TOOLCHAIN_IAR/stm32h747xI.icf
Labels: ready for merge, release-version: 5.14.2

#11685 Check-in PSA related auto-generated files to support online compiler.
  components/TARGET_PSA/TARGET_MBED_SPM/COMPONENT_SPE/psa_setup.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/inc/tfm_partition_defs.inc
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/inc/tfm_partition_list.inc
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/inc/tfm_service_list.inc
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/inc/tfm_spm_signal_defs.h
  components/TARGET_PSA/services/inc/autogen_sid.h
  components/TARGET_PSA/services/inc/mbed_spm_partitions.h
  tools/build.py
  tools/make.py
  tools/project.py
  tools/psa/README.md
  tools/psa/__init__.py
  tools/psa/release.py
  tools/psa/spm_template_file_list.json
  tools/test.py
Labels: ready for merge, release-version: 5.14.2

#11721 Bare metal greentea support
  TESTS/configs/baremetal.json
  TESTS/events/queue/main.cpp
  TESTS/events/timing/main.cpp
  TESTS/integration/COMMON/download_test.cpp
  TESTS/integration/COMMON/download_test.h
  TESTS/integration/COMMON/file_test.cpp
  TESTS/integration/COMMON/file_test.h
  TESTS/integration/fs-single/main.cpp
  TESTS/integration/fs-threaded/main.cpp
  TESTS/integration/net-single/main.cpp
  TESTS/integration/net-threaded/main.cpp
  TESTS/integration/stress-net-fs/main.cpp
  TESTS/mbed_drivers/crc/main.cpp
  TESTS/mbed_drivers/lp_timeout/main.cpp
  TESTS/mbed_drivers/lp_timer/main.cpp
  TESTS/mbed_drivers/race_test/main.cpp
  TESTS/mbed_drivers/rtc/main.cpp
  TESTS/mbed_drivers/timer/main.cpp
  TESTS/mbed_drivers/watchdog/main.cpp
  TESTS/mbed_drivers/watchdog_reset/main.cpp
  TESTS/mbed_hal/common_tickers/main.cpp
  TESTS/mbed_hal/common_tickers_freq/main.cpp
  TESTS/mbed_hal/lp_ticker/main.cpp
  TESTS/mbed_hal/sleep/main.cpp
  TESTS/mbed_hal/sleep_manager/main.cpp
  TESTS/mbed_hal/sleep_manager_racecondition/main.cpp
  TESTS/mbed_hal/stack_size_unification/main.cpp
  TESTS/mbed_hal/watchdog/main.cpp
  TESTS/mbed_platform/crash_reporting/main.cpp
  TESTS/mbed_platform/error_handling/main.cpp
  TESTS/mbedmicro-rtos-mbed/MemoryPool/main.cpp
  TESTS/mbedmicro-rtos-mbed/basic/main.cpp
  TESTS/mbedmicro-rtos-mbed/condition_variable/main.cpp
  TESTS/mbedmicro-rtos-mbed/event_flags/main.cpp
  TESTS/mbedmicro-rtos-mbed/heap_and_stack/main.cpp
  TESTS/mbedmicro-rtos-mbed/kernel_tick_count/main.cpp
  TESTS/mbedmicro-rtos-mbed/mail/main.cpp
  TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
  TESTS/mbedmicro-rtos-mbed/mutex/main.cpp
  TESTS/mbedmicro-rtos-mbed/queue/main.cpp
  TESTS/mbedmicro-rtos-mbed/rtostimer/main.cpp
  TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp
  TESTS/mbedmicro-rtos-mbed/signals/main.cpp
  TESTS/mbedmicro-rtos-mbed/systimer/main.cpp
  TESTS/mbedmicro-rtos-mbed/threads/LockGuard.h
  TESTS/mbedmicro-rtos-mbed/threads/SynchronizedIntegral.h
  TESTS/mbedmicro-rtos-mbed/threads/main.cpp
  TESTS/usb_device/basic/USBEndpointTester.cpp
  TESTS/usb_device/basic/USBTester.cpp
  TESTS/usb_device/basic/main.cpp
  TESTS/usb_device/hid/main.cpp
  TESTS/usb_device/msd/main.cpp
  TESTS/usb_device/serial/main.cpp
  features/frameworks/greentea-client/source/greentea_metrics.cpp
  features/frameworks/greentea-client/source/greentea_test_env.cpp
Labels: release-version: 5.15.0-rc1

#11825 Bare metal green tea test for storage component
  components/storage/blockdevice/COMPONENT_SD/TESTS/filesystem/parallel/main.cpp
  features/storage/TESTS/blockdevice/general_block_device/main.cpp
  features/storage/TESTS/kvstore/filesystemstore_tests/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_2/main.cpp
  features/storage/TESTS/kvstore/static_tests/main.cpp
  features/storage/nvstore/TESTS/nvstore/functionality/main.cpp
Labels: release-version: 5.15.0-rc1

#11821 Skip Bare Metal green tea test for PSA component
  TESTS/mbedtls/selftest/main.cpp
  TESTS/psa/attestation/main.cpp
  TESTS/psa/its_ps/main.cpp
  components/TARGET_PSA/TESTS/compliance_attestation/test_a001/main.c
  components/TARGET_PSA/TESTS/compliance_its/test_s001/main.c
  components/TARGET_PSA/TESTS/compliance_its/test_s002/main.c
  components/TARGET_PSA/TESTS/compliance_its/test_s004/main.c
  components/TARGET_PSA/TESTS/compliance_its/test_s005/main.c
  components/TARGET_PSA/TESTS/compliance_its/test_s006/main.c
  components/TARGET_PSA/TESTS/compliance_its/test_s007/main.c
  components/TARGET_PSA/TESTS/compliance_its/test_s008/main.c
  components/TARGET_PSA/TESTS/compliance_its/test_s009/main.c
  components/TARGET_PSA/TESTS/compliance_its/test_s010/main.c
  features/frameworks/TARGET_PSA/pal/pal_mbed_os_intf.cpp
Labels: needs: CI, release-version: 5.15.0-rc1

#11824 Skip Bare Metal green tea test for Network component
  TESTS/lorawan/loraradio/main.cpp
  TESTS/netsocket/dns/asynchronous_dns.cpp
  TESTS/netsocket/dns/asynchronous_dns_cache.cpp
  TESTS/netsocket/dns/asynchronous_dns_cancel.cpp
  TESTS/netsocket/dns/asynchronous_dns_external_event_queue.cpp
  TESTS/netsocket/dns/asynchronous_dns_invalid_host.cpp
  TESTS/netsocket/dns/asynchronous_dns_non_async_and_async.cpp
  TESTS/netsocket/dns/asynchronous_dns_simultaneous.cpp
  TESTS/netsocket/dns/asynchronous_dns_simultaneous_cache.cpp
  TESTS/netsocket/dns/asynchronous_dns_simultaneous_repeat.cpp
  TESTS/netsocket/dns/asynchronous_dns_timeouts.cpp
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/dns/synchronous_dns.cpp
  TESTS/netsocket/dns/synchronous_dns_cache.cpp
  TESTS/netsocket/dns/synchronous_dns_invalid.cpp
  TESTS/netsocket/dns/synchronous_dns_multiple.cpp
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_invalid.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_null.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_port_fail.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_unopened.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_wrong_type.cpp
  TESTS/netsocket/tcp/tcpsocket_connect_invalid.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest_burst.cpp
  TESTS/netsocket/tcp/tcpsocket_endpoint_close.cpp
  TESTS/netsocket/tcp/tcpsocket_open_close_repeat.cpp
  TESTS/netsocket/tcp/tcpsocket_open_destruct.cpp
  TESTS/netsocket/tcp/tcpsocket_open_limit.cpp
  TESTS/netsocket/tcp/tcpsocket_open_twice.cpp
  TESTS/netsocket/tcp/tcpsocket_recv_100k.cpp
  TESTS/netsocket/tcp/tcpsocket_recv_timeout.cpp
  TESTS/netsocket/tcp/tcpsocket_send_repeat.cpp
  TESTS/netsocket/tcp/tcpsocket_send_timeout.cpp
  TESTS/netsocket/tcp/tcpsocket_setsockopt_keepalive_valid.cpp
  TESTS/netsocket/tcp/tcpsocket_thread_per_socket_safety.cpp
  TESTS/netsocket/tls/main.cpp
  TESTS/netsocket/udp/main.cpp
  TESTS/network/emac/emac_TestMemoryManager.cpp
  TESTS/network/emac/emac_TestNetworkStack.cpp
  TESTS/network/emac/emac_ctp.cpp
  TESTS/network/emac/emac_membuf.cpp
  TESTS/network/emac/emac_test_broadcast.cpp
  TESTS/network/emac/emac_test_initialize.cpp
  TESTS/network/emac/emac_test_memory.cpp
  TESTS/network/emac/emac_test_multicast_filter.cpp
  TESTS/network/emac/emac_test_unicast.cpp
  TESTS/network/emac/emac_test_unicast_burst.cpp
  TESTS/network/emac/emac_test_unicast_frame_len.cpp
  TESTS/network/emac/emac_test_unicast_long.cpp
  TESTS/network/emac/emac_util.cpp
  TESTS/network/emac/main.cpp
  TESTS/network/interface/main.cpp
  TESTS/network/l3ip/cellular_driver_l3ip.cpp
  TESTS/network/l3ip/main.cpp
Labels: release-version: 5.15.0-rc1

#11843 Fix ethernet memory handling issues on CM3DS
  features/netsocket/emac-drivers/TARGET_ARM_SSG/COMPONENT_SMSC9220/smsc9220_emac.cpp
  features/netsocket/emac-drivers/TARGET_ARM_SSG/COMPONENT_SMSC9220/smsc9220_emac_config.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/smsc9220_eth_drv.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/smsc9220_eth_drv.h
Labels: ready for merge, release-version: 5.14.2

#11828 MCU_LPC11U35_501: fix MCU inheritance
  targets/targets.json
Labels: ready for merge, release-version: 5.14.2

#11854 ATHandler build warning fixed
  features/cellular/framework/AT/ATHandler.cpp
Labels: ready for merge, release-version: 5.14.2

#11850 Correct PB_6/PB_7 Serial AF mapping
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/TARGET_MTB_MURATA_ABZ/PeripheralPins.c
Labels: ready for merge, release-version: 5.14.2

#11848 Remove ITM Trace support from Arduino Nano 33 BLE
  targets/targets.json
Labels: release-version: 5.14.2

#11796 mbed_retarget: Add a minimal console implementation to provide basic functionalities
  platform/Stream.h
  platform/cxxsupport/mstd_mutex
  platform/mbed_lib.json
  platform/mbed_retarget.h
  platform/source/Stream.cpp
  platform/source/mbed_retarget.cpp
  tools/test/travis-ci/doxy-spellchecker/ignore.en.pws
Labels: release-version:6.0.0-rc1

#11531 Improve QSPIFBlockDevice conformance to SFDP
  TESTS/mbed_hal/qspi/main.cpp
  TESTS/mbed_hal/qspi/qspi_test_utils.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.h
  features/storage/TESTS/blockdevice/general_block_device/main.cpp
  features/storage/TESTS/kvstore/filesystemstore_tests/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_2/main.cpp
  features/storage/TESTS/kvstore/securestore_whitebox/main.cpp
  features/storage/TESTS/kvstore/tdbstore_whitebox/main.cpp
Labels: Priority-High, devices: cypress, ready for merge, release-version: 5.14.2

#11559 MbedCRC and CRC HAL revisions
  TESTS/mbed_drivers/crc/main.cpp
  TESTS/mbed_hal/crc/main.cpp
  UNITTESTS/empty_baseline/unittest.cmake
  UNITTESTS/target_h/cmsis.h
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.h
  drivers/MbedCRC.h
  drivers/internal/TableCRC.h
  drivers/mbed_lib.json
  drivers/source/MbedCRC.cpp
  drivers/source/TableCRC.cpp
  features/storage/filesystem/littlefs/LittleFileSystem.cpp
  features/storage/kvstore/direct_access_devicekey/DirectAccessDevicekey.cpp
  features/storage/kvstore/tdbstore/TDBStore.cpp
  hal/crc_api.h
  platform/source/mbed_error.c
  targets/TARGET_Cypress/TARGET_PSOC6/cy_crc_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/objects.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/mbed_crc_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/objects.h
  targets/TARGET_STM/TARGET_STM32F0/common_objects.h
  targets/TARGET_STM/TARGET_STM32F3/common_objects.h
  targets/TARGET_STM/TARGET_STM32F7/common_objects.h
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/TARGET_STM/TARGET_STM32L0/common_objects.h
  targets/TARGET_STM/TARGET_STM32L4/common_objects.h
  targets/TARGET_STM/TARGET_STM32WB/common_objects.h
  targets/TARGET_STM/mbed_crc_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/common/objects.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/crc_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/crc_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/objects.h
Labels: BREAKING-CHANGE, ready for merge, release-version:6.0.0-rc1

#11790 nrf52: reset UARTE peripheral in serial_free
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
Labels: needs: CI, release-version: 5.14.2

#11869 IOTSTOR-978: Skip a unstable testcase until fixed
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
Labels: ready for merge, release-version: 5.14.2

#11714 LWIP::get_ipv6_addr for link-local only
  features/lwipstack/LWIPInterface.cpp
  features/lwipstack/lwip_tools.cpp
Labels: ready for merge, release-version: 5.14.2

#11580 Remove target dependency in ublox cellular APIs
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/PPP/UBLOX_PPP.cpp
  features/cellular/framework/targets/UBLOX/README.md
  targets/targets.json
Labels: ready for merge, release-version: 5.14.2

#11736 Nuvoton: Remove TRNG support
  targets/TARGET_NUVOTON/TARGET_M480/objects.h
  targets/TARGET_NUVOTON/TARGET_M480/trng_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/objects.h
  targets/TARGET_NUVOTON/TARGET_NUC472/trng_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.14.2

#11841 WiFi: Re-order Greentea tests with minor fixes
  TESTS/network/wifi/README.md
  TESTS/network/wifi/main.cpp
  TESTS/network/wifi/wifi_connect_disconnect_repeat.cpp
  TESTS/network/wifi/wifi_connect_params_valid_secure.cpp
  TESTS/network/wifi/wifi_connect_params_valid_unsecure.cpp
  TESTS/network/wifi/wifi_connect_secure.cpp
  TESTS/network/wifi/wifi_get_rssi.cpp
  TESTS/network/wifi/wifi_tests.h
Labels: release-version: 5.14.2

#11844 EFM32: Enable RESET_REASON and WATCHDOG for EFM32GG11_STK3701
  targets/targets.json
Labels: release-version: 5.14.2

#11861 Replace calls to printf() with mbed-trace in netsocket tests
  TESTS/integration/COMMON/common_defines_test.h
  TESTS/integration/COMMON/download_test.cpp
  TESTS/integration/COMMON/file_test.cpp
  TESTS/integration/net-single/main.cpp
  TESTS/integration/net-threaded/main.cpp
  TESTS/integration/stress-net-fs/main.cpp
  TESTS/netsocket/dns/asynchronous_dns_cache.cpp
  TESTS/netsocket/dns/asynchronous_dns_cancel.cpp
  TESTS/netsocket/dns/asynchronous_dns_non_async_and_async.cpp
  TESTS/netsocket/dns/dns_tests.h
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/dns/synchronous_dns_cache.cpp
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest_burst.cpp
  TESTS/netsocket/tcp/tcpsocket_open_limit.cpp
  TESTS/netsocket/tcp/tcpsocket_recv_100k.cpp
  TESTS/netsocket/tcp/tcpsocket_recv_timeout.cpp
  TESTS/netsocket/tcp/tcpsocket_send_timeout.cpp
  TESTS/netsocket/tcp/tcpsocket_thread_per_socket_safety.cpp
  TESTS/netsocket/tls/main.cpp
  TESTS/netsocket/tls/tls_tests.h
  TESTS/netsocket/tls/tlssocket_echotest.cpp
  TESTS/netsocket/tls/tlssocket_echotest_burst.cpp
  TESTS/netsocket/tls/tlssocket_open_limit.cpp
  TESTS/netsocket/tls/tlssocket_recv_timeout.cpp
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udp_tests.h
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_echotest_burst.cpp
  TESTS/netsocket/udp/udpsocket_open_limit.cpp
  TESTS/netsocket/udp/udpsocket_recv_timeout.cpp
  TESTS/netsocket/udp/udpsocket_sendto_timeout.cpp
Labels: release-version: 5.14.2

#11859 Cellular: Fix queue scheduling for bare metal
  features/cellular/framework/device/CellularStateMachine.cpp
Labels: release-version: 5.14.2

#11871 TESTS: Add socket.set_timeout in udpsocket_echotest
  TESTS/netsocket/udp/udpsocket_echotest.cpp
Labels: release-version: 5.14.2

#11867 Fix for Cypress GPIO driver (fix for issue #11835)
  targets/TARGET_Cypress/TARGET_PSOC6/cy_gpio_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/gpio_object.h
Labels: devices: cypress, release-version: 5.15.0-rc1

#11820 Change `explicit pinmap` to `static pinmap`
  TESTS/mbed_hal_fpga_ci_test_shield/analogin/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/pwm/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/uart/main.cpp
  UNITTESTS/stubs/pwmout_api_stub.c
  drivers/I2C.h
  drivers/I2CSlave.h
  drivers/QSPI.h
  drivers/SPI.h
  drivers/SPISlave.h
  drivers/Serial.h
  drivers/SerialBase.h
  drivers/UARTSerial.h
  drivers/source/I2C.cpp
  drivers/source/I2CSlave.cpp
  drivers/source/QSPI.cpp
  drivers/source/SPI.cpp
  drivers/source/Serial.cpp
  drivers/source/SerialBase.cpp
  drivers/source/UARTSerial.cpp
  hal/static_pinmap.cpp
  hal/static_pinmap.h
  platform/source/mbed_retarget.cpp
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PinNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/pwmout_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/analogin_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/analogout_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/i2c_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/PortNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/analogin_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/analogin_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/i2c_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/lp_analogin_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/serial_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/spi_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_LPCXpresso/PinNames.h
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/TARGET_NUCLEO_F303RE/PinNames.h
  targets/TARGET_STM/TARGET_STM32F3/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F3/analogout_device.c
  targets/TARGET_STM/TARGET_STM32F3/serial_device.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F4/analogout_device.c
  targets/TARGET_STM/TARGET_STM32F4/serial_device.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/PinNames.h
  targets/TARGET_STM/TARGET_STM32L0/analogin_device.c
  targets/TARGET_STM/TARGET_STM32L0/analogout_device.c
  targets/TARGET_STM/TARGET_STM32L0/serial_device.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/analogin_device.c
  targets/TARGET_STM/TARGET_STM32L4/analogout_device.c
  targets/TARGET_STM/TARGET_STM32L4/serial_device.c
  targets/TARGET_STM/can_api.c
  targets/TARGET_STM/i2c_api.c
  targets/TARGET_STM/pwmout_api.c
  targets/TARGET_STM/qspi_api.c
  targets/TARGET_STM/serial_api.c
  targets/TARGET_STM/stm_spi_api.c
Labels: release-version: feature branch

#11872 Change mbed-os-example-wifi to build only DISCO_L475VG_IOT01A
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.14.2

#11713 Remove Tickless from STM32F4 targets
  targets/targets.json
Labels: release-version: 5.15.0-rc1

#11882 DISCO_L475VG_IOT01A: Fix baremetal profile Greentea tests
  TESTS/configs/baremetal.json
Labels: release-version: 5.15.0-rc1

#11654 Adjustment of netsocket tests to the lossy mesh network limitation.
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tls/main.cpp
  TESTS/netsocket/udp/main.cpp
Labels: release-version: 5.15.0-rc1

#11888 Pelion enable for UNO_91H
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/RdaWiFiInterface.cpp
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/RdaWiFiInterface.h
  targets/TARGET_RDA/TARGET_UNO_91H/device/RDA5981_nvic_virtual.h
  targets/TARGET_RDA/TARGET_UNO_91H/device/system_RDA5991H.c
  targets/TARGET_RDA/TARGET_UNO_91H/flash_api.c
  targets/TARGET_RDA/TARGET_UNO_91H/rda_ccfg_api.c
  targets/TARGET_RDA/TARGET_UNO_91H/serial_api.c
  targets/TARGET_RDA/TARGET_UNO_91H/us_ticker.c
Labels: release-version: 5.15.0-rc1

#11902 Cellular: Enable ePCO IE for BG96 driver
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularNetwork.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
Labels: ready for merge, release-version: 5.14.2

#11895 TESTS: Allow ipv6_link_local_address() as unsupported
  TESTS/network/interface/networkinterface_status.cpp
Labels: release-version: 5.15.0-rc1

#11868 Cypress Target update to support Manufacturing Test.
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.cpp
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.h
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/whd_emac.cpp
Labels: devices: cypress, release-version: 5.15.0-rc1

#11846 Add support for Makerdiary nRF52840-MDK
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_MAKERDIARY_NRF52840_MDK/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_MAKERDIARY_NRF52840_MDK/device.h
  targets/targets.json
Labels: release-version: 5.15.0-rc1, scope: new-target

#11885 Update to WHD 1.60 release
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/generated_mac_address.txt
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/inc/whd_version.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/firmware/COMPONENT_43012/43012C0-mfgtest.bin
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/firmware/COMPONENT_43012/43012C0-mfgtest.clm_blob
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/firmware/COMPONENT_43012/43012C0-mfgtest_bin.c
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/firmware/COMPONENT_43012/43012C0-mfgtest_clm_blob.c
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/firmware/COMPONENT_43012/43012C0.bin
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/firmware/COMPONENT_43012/43012C0.clm_blob
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/firmware/COMPONENT_43012/43012C0_bin.c
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/firmware/COMPONENT_43012/43012C0_clm_blob.c
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/firmware/COMPONENT_43012/resources.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/src/whd_wifi_api.c
Labels: Priority-High, devices: cypress, release-version: 5.15.0-rc1

#11911 Update mbed-coap to version 5.1.2
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/doxygen/libcoap_doxy
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: release-version: 5.15.0-rc1

#11875 Baremetal: Fix ARM toolchain Greentea test compilation for NUCLEO_F411RE
  TESTS/configs/baremetal.json
Labels: release-version: 5.15.0-rc1

#11908 I2C byte read/write transmition improvement
  targets/TARGET_Cypress/TARGET_PSOC6/cy_i2c_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/objects.h
Labels: devices: cypress, release-version: 5.15.0-rc1

#11899 Fixes to PR template
  .github/pull_request_template.md
Labels: release-version: 5.15.0-rc1

#11877 Fix for sending IPv6 UDP packet over link local interface
  features/lwipstack/LWIPStack.cpp
  features/lwipstack/lwip_tools.cpp
Labels: devices: cypress, ready for merge, release-version: 5.15.0-rc1

#11720 ATCmdParser: merge scanf and recv functions
  UNITTESTS/platform/ATCmdParser/test_ATCmdParser.cpp
  UNITTESTS/platform/ATCmdParser/unittest.cmake
  UNITTESTS/stubs/ATCmdParser_stub.cpp
  UNITTESTS/target_h/ATCmdParser.h
  platform/ATCmdParser.h
  platform/source/ATCmdParser.cpp
Labels: release-version: 5.15.0-rc1

#11915 TESTS: Fix TCP/TLS send_timeout test to non-blocking
  TESTS/netsocket/tcp/tcpsocket_send_timeout.cpp
  TESTS/netsocket/tls/tlssocket_send_timeout.cpp
Labels: ready for merge, release-version: 5.15.0-rc1

#11919 Cypress: FPGA: Improve SPI async calls
  targets/TARGET_Cypress/TARGET_PSOC6/cy_spi_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/objects.h
Labels: devices: cypress, release-version: 5.15.0-rc1

#11914 Deprecate string-based APIs in IPCore
  TESTS/network/emac/emac_TestNetworkStack.cpp
  TESTS/network/emac/emac_TestNetworkStack.h
  TESTS/network/l3ip/cellular_driver_l3ip.cpp
  TESTS/network/l3ip/cellular_driver_l3ip.h
  UNITTESTS/features/cellular/framework/device/cellularcontext/cellularcontexttest.cpp
  UNITTESTS/features/netsocket/EthernetInterface/test_EthernetInterface.cpp
  UNITTESTS/features/netsocket/EthernetInterface/unittest.cmake
  UNITTESTS/features/netsocket/nsapi_dns/test_nsapi_dns.cpp
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  UNITTESTS/stubs/AT_CellularStack_stub.cpp
  UNITTESTS/stubs/NetworkInterface_stub.cpp
  UNITTESTS/stubs/NetworkStack_stub.cpp
  UNITTESTS/stubs/NetworkStack_stub.h
  UNITTESTS/target_h/myCellularContext.h
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/lwipstack/LWIPInterface.cpp
  features/lwipstack/LWIPStack.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/netsocket/CellularInterface.h
  features/netsocket/DTLSSocket.h
  features/netsocket/EMACInterface.cpp
  features/netsocket/EMACInterface.h
  features/netsocket/InternetDatagramSocket.h
  features/netsocket/InternetSocket.h
  features/netsocket/L3IP.h
  features/netsocket/NetworkInterface.cpp
  features/netsocket/NetworkInterface.h
  features/netsocket/NetworkStack.cpp
  features/netsocket/NetworkStack.h
  features/netsocket/OnboardNetworkStack.h
  features/netsocket/TCPSocket.h
  features/netsocket/TLSSocket.h
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
Labels: release-version: 5.15.0-rc1

#11890 S2-LP: sync with development repository
  components/802.15.4_RF/stm-s2lp-rf-driver/source/NanostackRfPhys2lp.cpp
Labels: release-version: 5.15.0-rc1

#11851 Enable FAT ChaN lib configuration with mbed_lib.json
  UNITTESTS/features/storage/blockdevice/HeapBlockDevice/unittest.cmake
  features/storage/filesystem/fat/ChaN/ffconf.h
  features/storage/filesystem/fat/ChaN/mbed_lib.json
Labels: release-version: 5.15.0-rc1

#11870 STM32F7: linker scripts updates
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_ARM_STD/stm32f746xg.sct
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_GCC_ARM/STM32F746xG.ld
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_IAR/stm32f746xg.icf
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/device/TOOLCHAIN_ARM_STD/stm32f756xg.sct
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/device/TOOLCHAIN_GCC_ARM/STM32F756xG.ld
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/device/TOOLCHAIN_IAR/stm32f756xg.icf
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_ARM_STD/stm32f767xi.sct
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_GCC_ARM/STM32F767xI.ld
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_IAR/stm32f767xi.icf
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/TOOLCHAIN_ARM_STD/stm32f769xi.sct
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/TOOLCHAIN_GCC_ARM/STM32F769xI.ld
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/TOOLCHAIN_IAR/stm32f769xi.icf
Labels: ready for merge, release-version: 5.15.0-rc1

#11923 Cellular: Fix PPP to wait until connected event from (LWIP) PPP
  features/cellular/framework/device/CellularContext.cpp
Labels: ready for merge, release-version: 5.15.0-rc1

#11913 LPC55S69_NS default TDBStore size increased to 32kB
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: release-version: 5.15.0-rc1

#11930 Add FlashIAP to NUCLEO_L4R5ZI
  targets/targets.json
Labels: release-version: 5.15.0-rc1

#11925 Fixed greentea minimal-printf test for microlib
  TESTS/mbed_platform/minimal-printf/compliance/main.cpp
Labels: needs: CI, release-version: 5.15.0-rc1

#11773 Fix watchdog reset test
  TESTS/mbed_drivers/watchdog_reset/main.cpp
  TESTS/mbed_hal/watchdog_reset/main.cpp
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/watchdog_api.c
Labels: release-version: 5.15.0-rc1

#11865 IAR: Enable linker optimizations for develop/release profile
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: release-version: 5.15.0-rc1

#11881 UBLOX_EVK_ODIN_W2: Fix baremetal build and greentea tests
  features/FEATURE_BLE/mbed_lib.json
  features/FEATURE_BLE/targets/TARGET_CORDIO/TESTS/cordio_hci/driver/main.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/TESTS/cordio_hci/transport/main.cpp
  features/lwipstack/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/sdk/ublox-odin-w2-drivers/OdinWiFiInterface.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/sdk/ublox-odin-w2-drivers/OdinWiFiInterface.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/sdk/ublox-odin-w2-drivers/default_wifi_interface.cpp
Labels: ready for merge, release-version: 5.15.0-rc1

#11901 Update MPN for CYW9P62S1_43012EVB_01 board
  targets/targets.json
Labels: devices: cypress, release-version: 5.15.0-rc1

#11926 Fixed greentea FileHandle test for microlib
  TESTS/mbed_platform/FileHandle/main.cpp
Labels: release-version: 5.15.0-rc1

#11928 Allow MBED_ASSERT to throw errors in unittests, so we can verify it.
  UNITTESTS/drivers/PwmOut/unittest.cmake
  UNITTESTS/drivers/Watchdog/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularbase/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularinformation/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/athandler/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellularcontext/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellularstatemachine/unittest.cmake
  UNITTESTS/features/lorawan/loramac/unittest.cmake
  UNITTESTS/features/lorawan/loramaccommand/unittest.cmake
  UNITTESTS/features/lorawan/loramaccrypto/unittest.cmake
  UNITTESTS/features/lorawan/loraphy/unittest.cmake
  UNITTESTS/features/lorawan/loraphyas923/unittest.cmake
  UNITTESTS/features/lorawan/loraphyau915/unittest.cmake
  UNITTESTS/features/lorawan/loraphycn470/unittest.cmake
  UNITTESTS/features/lorawan/loraphycn779/unittest.cmake
  UNITTESTS/features/lorawan/loraphyeu433/unittest.cmake
  UNITTESTS/features/lorawan/loraphyeu868/unittest.cmake
  UNITTESTS/features/lorawan/loraphyin865/unittest.cmake
  UNITTESTS/features/lorawan/loraphykr920/unittest.cmake
  UNITTESTS/features/lorawan/loraphyus915/unittest.cmake
  UNITTESTS/features/lorawan/lorawaninterface/unittest.cmake
  UNITTESTS/features/lorawan/lorawanstack/unittest.cmake
  UNITTESTS/features/lorawan/lorawantimer/unittest.cmake
  UNITTESTS/features/netsocket/DTLSSocket/unittest.cmake
  UNITTESTS/features/netsocket/DTLSSocketWrapper/unittest.cmake
  UNITTESTS/features/netsocket/EthernetInterface/unittest.cmake
  UNITTESTS/features/netsocket/InternetSocket/unittest.cmake
  UNITTESTS/features/netsocket/NetworkInterface/unittest.cmake
  UNITTESTS/features/netsocket/NetworkStack/unittest.cmake
  UNITTESTS/features/netsocket/TCPServer/unittest.cmake
  UNITTESTS/features/netsocket/TCPSocket/unittest.cmake
  UNITTESTS/features/netsocket/TLSSocket/unittest.cmake
  UNITTESTS/features/netsocket/TLSSocketWrapper/unittest.cmake
  UNITTESTS/features/netsocket/UDPSocket/unittest.cmake
  UNITTESTS/features/netsocket/cellular/CellularNonIPSocket/unittest.cmake
  UNITTESTS/features/netsocket/nsapi_dns/unittest.cmake
  UNITTESTS/features/storage/blockdevice/HeapBlockDevice/test.cpp
  UNITTESTS/features/storage/blockdevice/HeapBlockDevice/unittest.cmake
  UNITTESTS/moduletests/storage/blockdevice/SlicingBlockDevice/unittest.cmake
  UNITTESTS/platform/ATCmdParser/unittest.cmake
  UNITTESTS/stubs/mbed_assert_stub.cpp
  UNITTESTS/target_h/platform/mbed_assert.h
Labels: release-version: 5.15.0-rc1

#11819 Add code to verify if external Wifi module is still responsible
  TESTS/netsocket/dns/asynchronous_dns_timeouts.cpp
Labels: release-version: 5.15.0-rc1

#11887 Add target for CYW9P62S1_43438EVB_01
  features/FEATURE_BLE/targets/TARGET_Cypress/COMPONENT_CYW43XXX/firmware/COMPONENT_43438/w_bt_firmware_controller.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.timestamp
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_notices.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/qspi_config.cfg
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/design.cycapsense
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/design.cyqspi
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/design.modus
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/SDIO_HOST/SDIO_HOST.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/SDIO_HOST/SDIO_HOST.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/SDIO_HOST/SDIO_HOST_cfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/SDIO_HOST/SDIO_HOST_cfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/cybsp.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/cybsp.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/cybsp_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM0P/TOOLCHAIN_ARM/cy8c6xx7_cm0plus.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM0P/TOOLCHAIN_ARM/startup_psoc6_01_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/cy8c6xx7_cm0plus.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/startup_psoc6_01_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM0P/TOOLCHAIN_IAR/cy8c6xx7_cm0plus.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM0P/TOOLCHAIN_IAR/startup_psoc6_01_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM0P/system_psoc6_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM4/TOOLCHAIN_ARM/cy8c6xx7_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM4/TOOLCHAIN_ARM/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/cy8c6xx7_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM4/TOOLCHAIN_IAR/cy8c6xx7_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM4/TOOLCHAIN_IAR/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/COMPONENT_CM4/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_WHD/resources/firmware/TARGET_43438/resources.h
  targets/targets.json
Labels: devices: cypress, release-version: 5.15.0-rc1

#11886 Add target for CY8CPROTO-062S3-4343W
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/resource_imp/wiced_resource.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/PeripheralNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM0P/TOOLCHAIN_ARM/cy8c6xx5_cm0plus.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM0P/TOOLCHAIN_ARM/startup_psoc6_03_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/cy8c6xx5_cm0plus.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/startup_psoc6_03_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM0P/TOOLCHAIN_IAR/cy8c6xx5_cm0plus.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM0P/TOOLCHAIN_IAR/startup_psoc6_03_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM0P/system_psoc6_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM4/TOOLCHAIN_ARM/cy8c6xx5_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM4/TOOLCHAIN_ARM/startup_psoc6_03_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/cy8c6xx5_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/startup_psoc6_03_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM4/TOOLCHAIN_IAR/cy8c6xx5_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM4/TOOLCHAIN_IAR/startup_psoc6_03_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/COMPONENT_CM4/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S3_4343W/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.timestamp
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_notices.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/qspi_config.cfg
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/design.cycapsense
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/design.cyqspi
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/design.modus
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/cybsp.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/cybsp.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/cybsp_types.h
  targets/targets.json
  tools/export/cdt/cdt_definitions.json
Labels: devices: cypress, release-version: 5.15.0-rc1, scope: new-target

#11936 DNS tests: Cancel asynchronous dns query if it times out
  TESTS/netsocket/dns/asynchronous_dns_non_async_and_async.cpp
Labels: release-version: 5.15.0-rc1

#11937 Cellular: Replace CellularSocket.rx_avail with pending_bytes
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularStack.cpp
Labels: ready for merge, release-version: 5.15.0-rc1

#10618 Tools: check for GCC 9, rather than 6
  tools/test/toolchains/api_test.py
  tools/toolchains/gcc.py
Labels: release-version: 5.15.0-rc1

#11943 Split integration tests in fs/net
  TESTS/integration/COMMON/common_defines_fs_test.h
  TESTS/integration/COMMON/common_defines_net_test.h
  TESTS/integration/fs-single/main.cpp
  TESTS/integration/fs-threaded/main.cpp
  TESTS/integration/net-single/main.cpp
  TESTS/integration/net-threaded/main.cpp
  TESTS/integration/stress-net-fs/main.cpp
Labels: release-version: 5.15.0-rc1

#11873 Make SMS configurable in Cellular stack
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/unittest.cmake
  UNITTESTS/stubs/NetworkInterfaceDefaults_stub.cpp
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/API/CellularSMS.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/AT/AT_CellularSMS.cpp
  features/cellular/framework/AT/AT_CellularSMS.h
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.h
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularSMS.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularSMS.h
  features/cellular/mbed_lib.json
Labels: release-version: 5.15.0-rc1

#11944 Cypress: Minor fix for mbed astyle
  targets/TARGET_Cypress/TARGET_PSOC6/PinNames.h
Labels: release-version: 5.15.0-rc1

#11946 Revert "MbedCRC and CRC HAL revisions"
  TESTS/mbed_drivers/crc/main.cpp
  TESTS/mbed_hal/crc/main.cpp
  UNITTESTS/empty_baseline/unittest.cmake
  UNITTESTS/target_h/cmsis.h
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.h
  drivers/MbedCRC.h
  drivers/internal/TableCRC.h
  drivers/mbed_lib.json
  drivers/source/MbedCRC.cpp
  drivers/source/TableCRC.cpp
  features/storage/filesystem/littlefs/LittleFileSystem.cpp
  features/storage/kvstore/direct_access_devicekey/DirectAccessDevicekey.cpp
  features/storage/kvstore/tdbstore/TDBStore.cpp
  hal/crc_api.h
  platform/source/mbed_error.c
  targets/TARGET_Cypress/TARGET_PSOC6/cy_crc_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/objects.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/mbed_crc_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/objects.h
  targets/TARGET_STM/TARGET_STM32F0/common_objects.h
  targets/TARGET_STM/TARGET_STM32F3/common_objects.h
  targets/TARGET_STM/TARGET_STM32F7/common_objects.h
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/TARGET_STM/TARGET_STM32L0/common_objects.h
  targets/TARGET_STM/TARGET_STM32L4/common_objects.h
  targets/TARGET_STM/TARGET_STM32WB/common_objects.h
  targets/TARGET_STM/mbed_crc_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/common/objects.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/crc_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/crc_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/objects.h
Labels: release-version: 5.15.0-rc1

#11947 Minimal Console: Fix syntax errors
  platform/source/mbed_retarget.cpp
Labels: release-version: 5.15.0-rc1

#11956 tests-mbed_hal-sleep_manager: fix regression found on since PR #11721
  TESTS/mbed_hal/sleep_manager/main.cpp
Labels: release-version: 5.15.0-rc1

#11949 Fix for ARMC5 compilation errors for some targets
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
Labels: release-version: 5.15.0-rc1

#11921 Updates to tools for Python 3 compatibility
  tools/device_management.py
  tools/export/exporters.py
  tools/flash_algo/__init__.py
  tools/host_tests/default_auto.py
  tools/host_tests/detect_auto.py
  tools/host_tests/dev_null_auto.py
  tools/host_tests/echo.py
  tools/host_tests/echo_flow_control.py
  tools/host_tests/hello_auto.py
  tools/host_tests/host_registry.py
  tools/host_tests/host_test.py
  tools/host_tests/mbedrpc.py
  tools/host_tests/net_test.py
  tools/host_tests/rpc.py
  tools/host_tests/rtc_auto.py
  tools/host_tests/serial_complete_auto.py
  tools/host_tests/serial_nc_rx_auto.py
  tools/host_tests/serial_nc_tx_auto.py
  tools/host_tests/stdio_auto.py
  tools/host_tests/tcpecho_client.py
  tools/host_tests/tcpecho_client_auto.py
  tools/host_tests/tcpecho_server.py
  tools/host_tests/tcpecho_server_auto.py
  tools/host_tests/tcpecho_server_loop.py
  tools/host_tests/udp_link_layer_auto.py
  tools/host_tests/udpecho_client.py
  tools/host_tests/udpecho_client_auto.py
  tools/host_tests/udpecho_server.py
  tools/host_tests/udpecho_server_auto.py
  tools/host_tests/wait_us_auto.py
  tools/host_tests/wfi_auto.py
  tools/memap.py
  tools/notifier/__init__.py
  tools/singletest.py
  tools/targets/REALTEK_RTL8195AM.py
  tools/targets/STM32_gen_PeripheralPins.py
  tools/targets/__init__.py
  tools/targets/lint.py
  tools/test.py
  tools/test/detect_targets_test.py
  tools/test_api.py
  tools/test_exporters.py
  tools/tests.py
  tools/toolchains/mbed_toolchain.py
Labels: release-version: 5.15.0-rc1

#11938 STM32: Update and align serial_clear implementations
  targets/TARGET_STM/TARGET_STM32F0/serial_device.c
  targets/TARGET_STM/TARGET_STM32F1/serial_device.c
  targets/TARGET_STM/TARGET_STM32F2/serial_device.c
  targets/TARGET_STM/TARGET_STM32F3/serial_device.c
  targets/TARGET_STM/TARGET_STM32F4/serial_device.c
  targets/TARGET_STM/TARGET_STM32F7/serial_device.c
  targets/TARGET_STM/TARGET_STM32H7/serial_device.c
  targets/TARGET_STM/TARGET_STM32L0/serial_device.c
  targets/TARGET_STM/TARGET_STM32L1/serial_device.c
  targets/TARGET_STM/TARGET_STM32L4/serial_device.c
  targets/TARGET_STM/TARGET_STM32WB/serial_device.c
Labels: release-version: 5.15.0-rc1

#11967 Fixed crashing nsapi_dns unittest
  UNITTESTS/features/netsocket/nsapi_dns/test_nsapi_dns.cpp
Labels: needs: CI, release-version: 5.15.0-rc1

#11918 IOTSTOR-978: Bugfixes to TDBStore and SecureStore
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/static_tests/main.cpp
  features/storage/kvstore/tdbstore/TDBStore.cpp
  features/storage/kvstore/tdbstore/TDBStore.h
Labels: release-version: 5.15.0-rc1

#11941 Remove string-based API usage within mbed-os
  TESTS/netsocket/README.md
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_invalid.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_null.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_wrong_type.cpp
  TESTS/netsocket/tcp/tcpsocket_connect_invalid.cpp
  TESTS/netsocket/tcp/tcpsocket_setsockopt_keepalive_valid.cpp
  TESTS/netsocket/tls/main.cpp
  TESTS/netsocket/tls/tlssocket_connect_invalid.cpp
  TESTS/netsocket/tls/tlssocket_handshake_invalid.cpp
  TESTS/netsocket/tls/tlssocket_no_cert.cpp
  TESTS/netsocket/tls/tlssocket_send_closed.cpp
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udpsocket_bind_address.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_invalid.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_null.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_port.cpp
  TESTS/netsocket/udp/udpsocket_sendto_invalid.cpp
  TESTS/netsocket/udp/udpsocket_sendto_repeat.cpp
  TESTS/network/multihoming/main.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/at_cellularstacktest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellularcontext/unittest.cmake
  UNITTESTS/features/netsocket/DTLSSocket/test_DTLSSocket.cpp
  UNITTESTS/features/netsocket/EthernetInterface/test_EthernetInterface.cpp
  UNITTESTS/features/netsocket/InternetSocket/test_InternetSocket.cpp
  UNITTESTS/features/netsocket/NetworkInterface/test_NetworkInterface.cpp
  UNITTESTS/features/netsocket/NetworkStack/test_NetworkStack.cpp
  UNITTESTS/features/netsocket/TCPSocket/test_TCPSocket.cpp
  UNITTESTS/features/netsocket/TLSSocket/test_TLSSocket.cpp
  UNITTESTS/features/netsocket/UDPSocket/test_UDPSocket.cpp
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/device/CellularContext.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.h
  features/nanostack/mbed-mesh-api/source/LoWPANNDInterface.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/netsocket/EMACInterface.cpp
  features/netsocket/NetworkStack.cpp
  features/netsocket/PPPInterface.cpp
  features/netsocket/PPPInterface.h
Labels: release-version: 5.15.0-rc1

#11959 Minimal Console: Fix compilation error
  platform/mbed_retarget.h
  platform/source/mbed_retarget.cpp
Labels: release-version: 5.15.0-rc1

#11979 Bare metal greentea tests compilation fixes
  TESTS/configs/baremetal.json
  TESTS/mbed_hal/watchdog_reset/main.cpp
Labels: release-version: 5.15.0-rc1

#11971 TDBStore: Unlock the master mutex even after garbage_collect()
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: release-version: 5.15.0-rc1

#11966 Fix targets.json syntax errors
  targets/targets.json
Labels: release-version: 5.15.0-rc1

#11963 STM32 USB : Add __HAL_RCC_PWR_CLK_ENABLE
  targets/TARGET_STM/USBPhy_STM32.cpp
Labels: release-version: 5.15.0-rc1

#11958 Add support for Wi-SUN RF channel configuration
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: release-version: 5.15.0-rc1

#11950 DISCO_H747I: add support of MBED_TICKLESS
  features/mbedtls/targets/TARGET_STM/TARGET_STM32L4/aes_alt.c
  targets/TARGET_STM/TARGET_STM32F0/common_objects.h
  targets/TARGET_STM/TARGET_STM32F1/common_objects.h
  targets/TARGET_STM/TARGET_STM32F2/objects.h
  targets/TARGET_STM/TARGET_STM32F3/common_objects.h
  targets/TARGET_STM/TARGET_STM32F4/common_objects.h
  targets/TARGET_STM/TARGET_STM32F7/common_objects.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/h747i_sleep.c
  targets/TARGET_STM/TARGET_STM32H7/analogin_device.c
  targets/TARGET_STM/TARGET_STM32H7/device/stm32h7xx_hal_rcc.c
  targets/TARGET_STM/TARGET_STM32H7/flash_api.c
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/TARGET_STM/TARGET_STM32H7/pin_device.h
  targets/TARGET_STM/TARGET_STM32L0/common_objects.h
  targets/TARGET_STM/TARGET_STM32L1/common_objects.h
  targets/TARGET_STM/TARGET_STM32L4/common_objects.h
  targets/TARGET_STM/TARGET_STM32WB/common_objects.h
  targets/TARGET_STM/can_api.c
  targets/TARGET_STM/gpio_api.c
  targets/TARGET_STM/gpio_object.h
  targets/TARGET_STM/i2c_api.c
  targets/TARGET_STM/lp_ticker.c
  targets/TARGET_STM/mbed_overrides.c
  targets/TARGET_STM/pinmap.c
  targets/TARGET_STM/qspi_api.c
  targets/TARGET_STM/rtc_api.c
  targets/TARGET_STM/serial_api.c
  targets/TARGET_STM/sleep.c
  targets/TARGET_STM/stm_spi_api.c
  targets/TARGET_STM/trng_api.c
  targets/TARGET_STM/us_ticker.c
  targets/targets.json
  tools/export/iar/iar_definitions.json
Labels: release-version: 5.15.0-rc1

#11978 LPC55S69_NS: Fix baremetal compilation error
  components/TARGET_PSA/mbed_lib.json
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/cmsis_nvic_virtual.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/cmsis_nvic_virtual.h
Labels: release-version: 5.15.0-rc1

#11935 Cellular: Mark to be deprecated in CellularDevice
  features/cellular/framework/API/CellularDevice.h
Labels: ready for merge, release-version: 5.15.0-rc1
