Repository ARMmbed/mbed-os, pull requests merged in 2019-02, with the labels that each got.

#9342 Add support for debug and program launch configurations
  tools/export/cdt/__init__.py
  tools/export/cdt/cdt_definitions.json
  tools/export/cdt/pyocd_settings_gnu_arm.tmpl
  tools/export/cdt/pyocd_settings_gnu_mcu.tmpl
Labels: ready for merge, release-version: 5.11.4

#9588 DISCO L475VG IOT01A: heap in SRAM2 region
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/mbed-bootloader-internal_dfb7cc.bin
  features/FEATURE_BOOTLOADER/targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_ARM_STD/stm32l475xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_GCC_ARM/STM32L475XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_IAR/stm32l475xx.icf
Labels: ready for merge, release-version: 5.11.4

#9585 PSOC6: M0 core binary image for BLE controller updated to version 1.05
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/hex/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/hex/psoc63_m0_ble_controller_1.01.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/hex/psoc63_m0_ble_controller_1.05.hex
Labels: ready for merge, release-version: 5.11.4

#9388 Fix for ARMc6 compiler errors
  features/FEATURE_BLE/source/generic/GenericGap.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalSecurityManager.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/cordio_stack/wsf/common/include/wsf_types.h
Labels: ready for merge, release-version: 5.11.4

#9431 Update IAR Armv8M changes
  targets/TARGET_NUVOTON/TARGET_M2351/device/system_M2351.h
  tools/export/iar/iar_definitions.json
  tools/toolchains/iar.py
Labels: ready for merge, release-version: 5.11.4

#9534 STM32 Serial Flow Control
  targets/TARGET_STM/TARGET_STM32F0/serial_device.c
  targets/TARGET_STM/TARGET_STM32F1/serial_device.c
  targets/TARGET_STM/TARGET_STM32F2/serial_device.c
  targets/TARGET_STM/TARGET_STM32F3/serial_device.c
  targets/TARGET_STM/TARGET_STM32F4/serial_device.c
  targets/TARGET_STM/TARGET_STM32F7/serial_device.c
  targets/TARGET_STM/TARGET_STM32H7/serial_device.c
  targets/TARGET_STM/TARGET_STM32L0/serial_device.c
  targets/TARGET_STM/TARGET_STM32L1/serial_device.c
  targets/TARGET_STM/TARGET_STM32L4/serial_device.c
Labels: ready for merge, release-version: 5.11.4

#9594 Remove SERIAL_FC on devices which don't support it
  targets/targets.json
Labels: ready for merge, release-version: 5.11.4

#9581 SharedPtr: use atomic load
  platform/SharedPtr.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9583 STM32F2: Enable TRNG
  targets/TARGET_STM/TARGET_STM32F2/objects.h
  targets/targets.json
Labels: ready for merge, release-version: 5.11.4

#9580 Fix SharedPtr::reset
  platform/SharedPtr.h
Labels: ready for merge, release-version: 5.11.4

#9556 [Wio 3G] Modified pin map
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/PinNames.h
Labels: ready for merge, release-version: 5.11.4

#9553 STM32: Enable SERIAL_FC for all
  targets/targets.json
Labels: ready for merge, release-version: 5.11.4

#9595 Define USBTX and USBRX for targets without them
  targets/TARGET_NXP/TARGET_LPC11UXX/TARGET_LPC11U37H_401/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F405RG/PinNames.h
Labels: ready for merge, release-version: 5.11.4

#9589 Improve error message for exports for OS2-only targets
  tools/project.py
Labels: ready for merge, release-version: 5.11.4

#9378 Add get_connection_status() override in CellularContext
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9593 Standardize Arduino form factor
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_FRDM/PinNames.h
  targets/TARGET_NXP/TARGET_LPC81X/TARGET_LPC812/PinNames.h
  targets/targets.json
Labels: ready for merge, release-version: 5.11.4

#9557 [Wio BG96] Modified pin map
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_BG96/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_BG96/PinNames.h
Labels: ready for merge, release-version: 5.11.4

#9579 FHSS timer: Use singleton pointer
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_fhss_timer.cpp
Labels: ready for merge, release-version: 5.11.4

#9526 Remove yotta and minar references in NCS36510
  targets/TARGET_ONSEMI/TARGET_NCS36510/device/NCS36510.h
  targets/TARGET_ONSEMI/TARGET_NCS36510/target_config.h
Labels: ready for merge, release-version: 5.11.4

#9606 Correct typo no_dsp - nodsp
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.11.4

#9615 FUTURE_SEQUANA: Remove special "tags" from M0 hex images
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/hex/psoc63_m0_ble_controller_1.05.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/hex/psoc63_m0_default_1.02.hex
Labels: ready for merge, release-version: 5.11.4

#9524 Remove IAR supported from targets failing IAR 8.32 build
  targets/targets.json
Labels: ready for merge, release-version: feature branch

#9614 Fix cortex-m33-S gcc compilation error
  tools/toolchains/gcc.py
Labels: ready for merge, release-version: 5.11.4

#9625 Fix cortex-m33 armlink error
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.11.4

#9596 Implement Linker command/response files in make export
  tools/export/makefile/Makefile.tmpl
  tools/export/makefile/__init__.py
Labels: ready for merge, release-version: 5.11.4

#9021 tools: check that part size is not exceeding region size
  tools/build_api.py
  tools/test/build_api/build_api_test.py
Labels: ready for merge, release-version: 5.11.4

#9631 Update linker scripts for bootloader target TMPM46B
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/device/TOOLCHAIN_IAR/tmpm46bf10fg.icf
Labels: ready for merge, release-version: 5.11.4

#9619 Correct the dsp flag from no_dsp to nodsp
  tools/toolchains/gcc.py
Labels: ready for merge, release-version: 5.11.4

#9566 Fix warning in Crypto when using boot seed injection
  features/mbedtls/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/inc/default_random_seed.h
  features/mbedtls/platform/inc/platform_mbed.h
  targets/targets.json
Labels: ready for merge, release-version: 5.12.0-rc1

#7976 Add SPI basic test and test header file.
  TESTS/mbed_hal/spi/main.cpp
  TESTS/mbed_hal/spi/spi_api_tests.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PinNames.h
  targets/TARGET_STM/stm_spi_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/spi_api.c
  targets/targets.json
  tools/test/examples/examples.json
Labels: ready for merge, release-version: feature branch

#9651 FUTURE_SEQUANA_M0_PSA - fix CM4 starting address
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_M0_PSA/spm_hal_api.c
Labels: ready for merge, release-version: 5.11.5

#9636 Fix compiler warnings
  TESTS/netsocket/tls/tlssocket_echotest.cpp
  TESTS/network/interface/networkinterface_status.cpp
  platform/mbed_board.c
Labels: ready for merge, release-version: 5.11.5

#9424 Allows multiple network status listeners
  UNITTESTS/features/netsocket/EthernetInterface/unittest.cmake
  UNITTESTS/features/netsocket/NetworkInterface/test_NetworkInterface.cpp
  UNITTESTS/features/netsocket/NetworkInterface/unittest.cmake
  UNITTESTS/stubs/NetworkInterface_stub.cpp
  UNITTESTS/stubs/mbed_error.c
  features/frameworks/nanostack-libservice/mbed-client-libservice/ns_list.h
  features/netsocket/NetworkInterface.cpp
  features/netsocket/NetworkInterface.h
  platform/Callback.h
  tools/test/travis-ci/doxy-spellchecker/ignore.en.pws
Labels: ready for merge, release-version: 5.12.0-rc1

#9647 FUTURE_SEQUANA: SPI HAL fixes
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/hex/psoc63_m0_ble_controller_1.01.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/hex/psoc63_m0_default_1.02.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_CY8C63XX/TARGET_MCU_PSOC6_M4/hex/psoc63_m0_default_1.03.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/objects.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/pinmap.c
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/spi_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.11.5

#9633 Improvement to artifact delivery method
  tools/config/__init__.py
Labels: ready for merge, release-version: 5.12.0-rc1

#9613 K64/ARM: Update to 2-region model for HEAP and Stack Memory
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_ARM_STD/MK64FN1M0xxx12.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_ARM_STD/sys.cpp
  targets/TARGET_Freescale/mbed_rtx.h
Labels: ready for merge, release-version: 5.11.5

#9184 Adds an NFC System Test suite
  TEST_APPS/device/nfcapp/NFCCommands.cpp
  TEST_APPS/device/nfcapp/NFCCommands.h
  TEST_APPS/device/nfcapp/NFCProcessCtrl.cpp
  TEST_APPS/device/nfcapp/NFCProcessCtrl.h
  TEST_APPS/device/nfcapp/NFCProcessEEPROM.cpp
  TEST_APPS/device/nfcapp/NFCProcessEEPROM.h
  TEST_APPS/device/nfcapp/NFCTestShim.cpp
  TEST_APPS/device/nfcapp/NFCTestShim.h
  TEST_APPS/device/nfcapp/SmartPoster.cpp
  TEST_APPS/device/nfcapp/SmartPoster.h
  TEST_APPS/device/nfcapp/main.cpp
  TEST_APPS/device/nfcapp/mbed_app.json
  TEST_APPS/device/nfcapp/uart.cpp
  TEST_APPS/icetea_plugins/nfc_test_parsers.py
  TEST_APPS/icetea_plugins/plugins_to_load.py
  TEST_APPS/testcases/nfc/README.md
  TEST_APPS/testcases/nfc/__init__.py
  TEST_APPS/testcases/nfc/img/creamscone-mobile.png
  TEST_APPS/testcases/nfc/img/inter-op-view.png
  TEST_APPS/testcases/nfc/img/simple-overview.png
  TEST_APPS/testcases/nfc/mobileapi.md
  TEST_APPS/testcases/nfc/nfc_clf_wrapper.py
  TEST_APPS/testcases/nfc/nfc_cli_helper.py
  TEST_APPS/testcases/nfc/nfc_messages.py
  TEST_APPS/testcases/nfc/test_nfc.py
  TEST_APPS/testcases/nfc/test_self.py
Labels: ready for merge, release-version: 5.12.0-rc1

#9657 Revert "MIMXRT1050_EVK: Add IAR support in the exporter"
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.11.5

#9652 Fix minor bugs in secure targets file filtering
  tools/build.py
  tools/make.py
  tools/paths.py
  tools/resources/__init__.py
  tools/test.py
Labels: needs: CI, release-version: 5.11.5

#9663 RealTek post script fix for ARMC6
  tools/targets/REALTEK_RTL8195AM.py
Labels: ready for merge, release-version: feature branch

#9372 BLE - Nordic: Release crypto cell when not in use.
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xPalSecurityManager.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xPalSecurityManager.h
Labels: ready for merge, release-version: 5.11.5

#9582 Greentea Socket test improvements
  TESTS/netsocket/dns/asynchronous_dns_cancel.cpp
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tcp/tcpsocket_bind_address_invalid.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_wrong_type.cpp
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udp_tests.h
  TESTS/netsocket/udp/udpsocket_bind_address_invalid.cpp
  TESTS/netsocket/udp/udpsocket_bind_wrong_type.cpp
  TESTS/netsocket/udp/udpsocket_recv_timeout.cpp
Labels: ready for merge, release-version: 5.11.5

#9584 TLSSocket send/recv return WOULD_BLOCK error instead of NO_CONNECTION
  features/netsocket/TLSSocketWrapper.cpp
Labels: ready for merge, release-version: 5.11.5

#9605 Restore MBEDTLS_PSA_CRYPTO_C for PSA targets
  targets/targets.json
Labels: ready for merge, release-version: 5.11.5

#9650 Multi thread Block Device Tests Fix - Ensure unique block address
  components/storage/blockdevice/COMPONENT_SPIF/TESTS/block_device/spif/main.cpp
  features/storage/TESTS/blockdevice/general_block_device/main.cpp
Labels: ready for merge, release-version: 5.11.5

#9656 M2351: Fix crypto AC management
  targets/TARGET_NUVOTON/TARGET_M2351/crypto/crypto-misc.cpp
  targets/TARGET_NUVOTON/TARGET_M2351/crypto/crypto-misc.h
  targets/TARGET_NUVOTON/TARGET_M480/crypto/crypto-misc.cpp
  targets/TARGET_NUVOTON/TARGET_NUC472/crypto/crypto-misc.cpp
Labels: ready for merge, release-version: 5.11.5

#9630 Publish tests documentation for DNS, Emac, NetworkInterface and Wifi
  TESTS/netsocket/README.md
  TESTS/network/emac/README.md
  TESTS/network/interface/README.md
  TESTS/network/wifi/README.md
Labels: ready for merge, release-version: 5.12.0-rc1

#9514 BG96 netsocket tests
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.h
Labels: ready for merge, release-version: 5.11.5

#9658 REALTEK_RTL8195AM binary timestamp
  tools/targets/REALTEK_RTL8195AM.py
Labels: ready for merge, release-version: 5.11.5

#9587 targets: QUECTEL: Fix build warning
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.cpp
Labels: release-version: 5.11.5

#9602 STM32 GPIO: use maximum speed
  targets/TARGET_STM/pinmap.c
Labels: ready for merge, release-version: 5.11.5

#9570 tests-netsocket-udp: UDPSOCKET_ECHOTEST_NONBLOCK fixes
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udp_tests.h
  TESTS/netsocket/udp/udpsocket_echotest.cpp
Labels: ready for merge, release-version: 5.11.5

#9607 AC6 Build fixes for Nordic targets
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/TARGET_SOFTDEVICE_COMMON/softdevice/common/nrf_sdh_ble.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/libraries/experimental_section_vars/nrf_section.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/libraries/experimental_section_vars/nrf_section_iter.h
  targets/targets.json
Labels: ready for merge, release-version: feature branch

#9677 Add MBEDTLS_ENTROPY_NV_SEED to NUCLEO_F411RE to fix the build
  targets/targets.json
Labels: ready for merge, release-version: 5.11.5

#9673 Fix Py3.7 mdot target build
  tools/targets/__init__.py
  tools/toolchains/__init__.py
Labels: ready for merge, release-version: 5.11.5

#9680 FUTURE_SEQUANA: Fixed Arduino signal mappings
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA/PinNames.h
Labels: ready for merge, release-version: 5.11.5

#9501 Add WIFI support for RDA target UNO_91H
  TESTS/network/emac/main.cpp
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/RdaWiFiInterface.cpp
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/RdaWiFiInterface.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/csl_mbed.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/maclib_task.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/rda5981_flash.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/rda5981_ota.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/rda5981_sniffer.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/rda5991h_wland.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/rda_sys_wrapper.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/wland_dbg.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/wland_flash.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/wland_flash_wp.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/wland_ota.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/wland_rf.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/wland_types.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/lib/LICENSE-permissive-binary-license-1.0.txt
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/lib/README.md
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/lib/TOOLCHAIN_ARM_STD/libwifi_sta_ap.ar
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/lib/TOOLCHAIN_GCC_ARM/libwifi_sta_ap.a
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/lib/TOOLCHAIN_IAR/libwifi_sta_ap.a
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/src/maclib_task.c
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/src/rda5991h_wland.c
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/src/rda_sys_wrapper.c
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/src/wland_flash.c
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/src/wland_flash_wp.c
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/src/wland_ota.c
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/rda5981x_emac.cpp
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/rda5981x_emac.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/rda5981x_emac_config.h
  targets/TARGET_RDA/TARGET_UNO_91H/device/RDA5991H.h
  targets/TARGET_RDA/TARGET_UNO_91H/trng_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.11.5

#9326 Doxygen correction
  features/nfc/nfc/NFCController.h
  features/nfc/nfc/NFCEEPROM.h
  features/nfc/nfc/ndef/MessageBuilder.h
  features/nfc/nfc/ndef/MessageParser.h
  features/nfc/nfc/ndef/common/SimpleMessageParser.h
Labels: docathlon2019, ready for merge, release-version: 5.11.5

#9679 Default behavior of C030-R412M should be to use modem IP stack
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/ONBOARD_UBLOX.cpp
Labels: ready for merge, release-version: 5.11.5

#9600 Atomic extensions: 64-bit, bool, exchange
  UNITTESTS/stubs/mbed_critical_stub.c
  platform/mbed_critical.c
  platform/mbed_critical.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9678 FUTURE_SEQUANA_PSA: fixed deep sleep mode
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_CY8C63XX/device.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_M0_PSA/spm_init_api.c
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/psa_debug_1.0.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/psa_release_1.0.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/lp_ticker.c
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/psoc6_utils.c
  targets/targets.json
Labels: ready for merge, release-version: 5.11.5

#9693 platform: fix build warning in mbed_error
  platform/mbed_error.c
Labels: ready for merge, release-version: 5.11.5

#9697 Disable psco6 iar8 till libraries are available
  targets/targets.json
Labels: needs: CI, release-version: feature branch

#9576 Remove redundant ifdef DEVICE_TRNG from DeviceKey
  features/device_key/source/DeviceKey.cpp
Labels: Manually Patch, ready for merge, release-version: 5.11.5-alpha

#9681 Make a few trivial syntactic changes to better support cross-compilation
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularSMS.cpp
  features/cellular/framework/common/CellularLog.cpp
Labels: ready for merge, release-version: 5.11.5

#9686 Greentea tests: set correct port to test against google.com
  TESTS/netsocket/tls/tlssocket_handshake_invalid.cpp
Labels: ready for merge, release-version: 5.11.5

#9702 Fix dependencies of platform partition
  TESTS/psa/spm_client/COMPONENT_SPE/psa_setup.c
  TESTS/psa/spm_server/COMPONENT_SPE/psa_setup.c
  TESTS/psa/spm_smoke/COMPONENT_SPE/psa_setup.c
  components/TARGET_PSA/TARGET_MBED_SPM/COMPONENT_SPE/psa_setup.c
  components/TARGET_PSA/services/platform/COMPONENT_SPE/TARGET_MBED_SPM/psa_platform_partition.c
  components/TARGET_PSA/services/platform/COMPONENT_SPE/psa_platform_partition.h
  components/TARGET_PSA/services/platform/platform_psa.json
Labels: ready for merge, release-version: 5.12.0-rc1

#9692 target: UBLOX: Fix build warning in UBLOX_AT_CellularNetwork.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.cpp
Labels: ready for merge, release-version: 5.11.5

#9645 Change TESTS/netsocket/ for cellular testing
  TESTS/netsocket/README.md
  TESTS/netsocket/dns/asynchronous_dns_simultaneous_repeat.cpp
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest_burst.cpp
  TESTS/netsocket/tcp/tcpsocket_endpoint_close.cpp
  TESTS/netsocket/tcp/tcpsocket_open_destruct.cpp
  TESTS/netsocket/tcp/tcpsocket_send_repeat.cpp
  TESTS/netsocket/tcp/tcpsocket_send_timeout.cpp
  TESTS/netsocket/tls/tls_tests.h
  TESTS/netsocket/tls/tlssocket_echotest_burst.cpp
  TESTS/netsocket/tls/tlssocket_open_destruct.cpp
  TESTS/netsocket/tls/tlssocket_recv_timeout.cpp
  TESTS/netsocket/tls/tlssocket_send_repeat.cpp
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_echotest_burst.cpp
  TESTS/netsocket/udp/udpsocket_open_destruct.cpp
  TESTS/netsocket/udp/udpsocket_sendto_timeout.cpp
  tools/test_configs/CellularInterface.json
Labels: ready for merge, release-version: 5.12.0-rc1

#9701 Refactor psa entropy inject test
  TESTS/psa/entropy_inject/main.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9694 nanostack: icmpv6: fix build warning
  features/nanostack/sal-stack-nanostack/source/Common_Protocols/icmpv6.c
Labels: ready for merge, release-version: 5.11.5

#9696 features: nanostack: fix warning in thread_extension.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread/thread_extension.h
Labels: ready for merge, release-version: 5.11.5

#9691 btle: fix build warning about unused clockConfiguration
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/btle/btle.cpp
Labels: ready for merge, release-version: 5.11.5

#9639 ESP8266: connect() checks errors from ESP chip
  TESTS/network/wifi/main.cpp
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
Labels: needs: review

#9685 Fix sleep tracing not finding matching driver during unlock.
  platform/mbed_sleep_manager.c
Labels: ready for merge, release-version: 5.11.5

#9713 Add release notes section to PR template
  .github/pull_request_template.md
Labels: ready for merge, release-version: 5.11.5

#9684 enet_tasklet_disconnect() should generate event to tasklet.
  features/nanostack/mbed-mesh-api/source/ethernet_tasklet.c
  features/nanostack/mbed-mesh-api/source/include/mesh_system.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9628 Bare metal mbed_lib updates
  components/TARGET_PSA/services/COMPONENT_PSA_SRV_IMPL/mbed_lib.json
  features/storage/kvstore/conf/global/mbed_lib.json
  features/storage/kvstore/conf/mbed_lib.json
  features/storage/kvstore/direct_access_devicekey/mbed_lib.json
  features/storage/kvstore/filesystemstore/mbed_lib.json
  features/storage/kvstore/global_api/mbed_lib.json
  features/storage/kvstore/kv_map/mbed_lib.json
  features/storage/kvstore/tdbstore/mbed_lib.json
Labels: ready for merge, release-version: 5.12.0-rc1

#9719 Release candidate for mbed-os-5.11.5-alpha
  features/device_key/source/DeviceKey.cpp
  platform/mbed_version.h
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_CY8CKIT_062_4343W/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_CY8CKIT_062_WIFI_BT/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_CY8CMOD_062_4343W/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_CYW943012P6EVB_01/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_CY8CKIT_062_4343W/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_CY8CKIT_062_WIFI_BT/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_CY8CMOD_062_4343W/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_CYW943012P6EVB_01/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_CY8CKIT_062_4343W/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_CY8CKIT_062_WIFI_BT/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_CY8CMOD_062_4343W/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_CYW943012P6EVB_01/libwiced_drivers.a
Labels: needs: CI

#9635 Do not provide a default Pelion host address.
  tools/device_management.py
Labels: ready for merge, release-version: 5.11.5

#9714 Only GCC_ARM toolchain is supported, removing legacy code
  platform/mbed_retarget.cpp
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_GCC_CW_EWL/MKL25Z4.ld
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_GCC_CW_EWL/startup_MKL25Z4.c
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_GCC_CW_NEWLIB/MKL25Z4.ld
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_GCC_CW_NEWLIB/startup_MKL25Z4.S
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U24/LPC11U24.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U35_401/LPC11U35.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U35_501/LPC11U35.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U37H_401/LPC11U37.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11U37_501/LPC11U37.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CR/startup_LPC11xx.cpp
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CS/LPC11U24.ld
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_GCC_CS/startup_LPC11xx.S
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11XX/LPC1114.ld
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/TOOLCHAIN_GCC_CR/TARGET_LPC11XX/startup_LPC11xx.cpp
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/TOOLCHAIN_GCC_CS/startup_LPC11xx.S
  targets/TARGET_NXP/TARGET_LPC15XX/device/TOOLCHAIN_GCC_CR/LPC1549.ld
  targets/TARGET_NXP/TARGET_LPC15XX/device/TOOLCHAIN_GCC_CR/startup_LPC15xx.cpp
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_CR/LPC1768.ld
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_CR/startup_LPC17xx.cpp
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_CS/LPC1768.ld
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_GCC_CS/startup_LPC17xx.S
  targets/TARGET_NXP/TARGET_LPC408X/device/TOOLCHAIN_GCC_CR/LPC407x_8x.ld
  targets/TARGET_NXP/TARGET_LPC408X/device/TOOLCHAIN_GCC_CR/startup_lpc407x_8x.cpp
  targets/TARGET_NXP/TARGET_LPC43XX/device/TOOLCHAIN_GCC_CR/LPC43xx.ld
  targets/TARGET_NXP/TARGET_LPC43XX/device/TOOLCHAIN_GCC_CR/startup_LPC43xx.cpp
  targets/TARGET_NXP/TARGET_LPC82X/TARGET_LPC824/device/TOOLCHAIN_GCC_CR/LPC824.ld
  targets/TARGET_NXP/TARGET_LPC82X/TARGET_LPC824/device/TOOLCHAIN_GCC_CR/startup_LPC824_CR.cpp
Labels: ready for merge, release-version: 5.11.5

#9715 Add .inc as a header file type.
  tools/resources/__init__.py
Labels: ready for merge, release-version: 5.11.5

#9706 Cellular: fix onboard modems powering failure.
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTB_MTS_DRAGONFLY/ONBOARD_TELIT_HE910.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/ONBOARD_TELIT_HE910.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9724 tools/utils: ensure default build profiles are processed first
  tools/utils.py
Labels: ready for merge, release-version: 5.11.5

#9722 Add flash sum check
  TESTS/mbed_drivers/flashiap/main.cpp
Labels: ready for merge, release-version: 5.11.5

#9537 BLE: Add MTU events
  features/FEATURE_BLE/ble/GattClient.h
  features/FEATURE_BLE/ble/GattServer.h
  features/FEATURE_BLE/ble/gap/Gap.h
  features/FEATURE_BLE/ble/generic/GenericGap.h
  features/FEATURE_BLE/ble/generic/GenericGattClient.h
  features/FEATURE_BLE/ble/pal/PalGap.h
  features/FEATURE_BLE/ble/pal/PalGattClient.h
  features/FEATURE_BLE/source/generic/GenericGap.cpp
  features/FEATURE_BLE/source/generic/GenericGattClient.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioBLE.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioGattServer.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioPalAttClient.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioBLE.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalAttClient.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_MCU_NRF51822/source/nRF5xGattServer.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF51/source/nRF5xGattServer.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/btle/btle.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xGattServer.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9601 LoRaWAN: Proper size checks for link ADR cmds & correct include path in Unittests framework
  UNITTESTS/CMakeLists.txt
  UNITTESTS/features/lorawan/loraphyau915/Test_LoRaPHYAU915.cpp
  UNITTESTS/features/lorawan/loraphycn470/Test_LoRaPHYCN470.cpp
  UNITTESTS/features/lorawan/loraphyus915/Test_LoRaPHYUS915.cpp
  UNITTESTS/features/lorawan/lorawanstack/Test_LoRaWANStack.cpp
  UNITTESTS/stubs/LoRaPHY_stub.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/phy/LoRaPHY.cpp
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
Labels: ready for merge, release-version: 5.11.5

#9654 Update mbed-coap to version 4.7.4
  features/frameworks/mbed-coap/.yotta_ignore
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/Makefile.test
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/run_unit_tests.sh
  features/frameworks/mbed-coap/source/include/sn_coap_protocol_internal.h
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.11.5

#9641 Fix for RDA targets failing AC6 builds
  targets/TARGET_RDA/mbed_rtx.h
  targets/targets.json
Labels: needs: CI, release-version: feature branch

#9667 Linker files for LPC11U68 and LPC1549 updated
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U68/LPC11U68.ld
  targets/TARGET_NXP/TARGET_LPC15XX/device/TOOLCHAIN_GCC_ARM/LPC1549.ld
  targets/targets.json
Labels: release-version: 5.12.0-rc1

#9709 Reverting to original doxy configuration
  features/nfc/nfc/NFCController.h
  features/nfc/nfc/NFCEEPROM.h
  features/nfc/nfc/ndef/MessageBuilder.h
  features/nfc/nfc/ndef/MessageParser.h
  features/nfc/nfc/ndef/common/SimpleMessageParser.h
Labels: ready for merge, release-version: 5.11.5

#9710 crypto: Remove PSA Crypto API from targets without entropy
  targets/targets.json
Labels: ready for merge, release-version: 5.12.0-rc1

#9649 Fix IntelliSense in VSCode export
  tools/export/vscode/__init__.py
Labels: ready for merge, release-version: 5.11.5

#9660 Cellular: clean sensitive information from trace
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/at_cellulardevicetest.cpp
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/ATHandler_stub.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularDevice.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9473 ESP8266: treats reset-ready-message as OOB
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9728 Cellular: Fix sigio to be released in ATHandler destructor
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  UNITTESTS/stubs/FileHandle_stub.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
Labels: needs: CI, release-version: 5.12.0-rc1

#9743 Enable ODIN target in Feature IAR 8 branch
  targets/targets.json
Labels: ready for merge, release-version: feature branch

#9502 readme: add list of licenses - not Apache 2.0
  LICENSE
  LICENSE-apache-2.0.txt
  README.md
Labels: ready for merge, release-version: 5.11.5

#9740 Remove pyocd requirement and update icetea.
  requirements.txt
Labels: ready for merge, release-version: 5.11.5

#9742 tools: export: MCUXpresso: fix case inconsistencies in .templ file names
  tools/export/mcuxpresso/__init__.py
Labels: needs: CI, release-version: 5.11.5

#9609 GR_LYCHEE,RZ_A1H,VK_RZ_A1H: Update to fix ARMC6 build failures
  rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_core_ca.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/mem_RZ_A1LU.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/startup_RZ_A1LU.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/startup_RZ_A1LU.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/weak_handler.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/weak_handler.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/mbed_sf_boot.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/mmu_RZ_A1LU.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/mem_RZ_A1H.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/startup_RZ_A1H.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/startup_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/weak_handler.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/weak_handler.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/mbed_sf_boot.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/mmu_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_ARM_STD/mem_VK_RZ_A1H.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_ARM_STD/startup_VK_RZ_A1H.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_ARM_STD/startup_VK_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_ARM_STD/weak_handler.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/mmu_VK_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/flash_api.c
  targets/TARGET_RENESAS/mbed_rtx.h
Labels: ready for merge, release-version: feature branch

#9741 ESP8266: connect() returns OK in non-blocking calls
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 5.11.5

#9718 Greentea tests: user-configurable timeouts
  TESTS/netsocket/dns/dns_tests.h
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tls/tls_tests.h
  TESTS/netsocket/udp/udp_tests.h
  TESTS/network/emac/main.cpp
  TESTS/network/interface/main.cpp
  TESTS/network/wifi/main.cpp
Labels: ready for merge, release-version: 5.11.5

#9307 Configuration options for STM_EMAC buffer counts
  features/netsocket/emac-drivers/TARGET_STM_EMAC/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_conf.h
Labels: ready for merge, release-version: 5.11.5

#9748 BLE:Cordio: ATTS setting for write cback should use bitwise or
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
Labels: ready for merge, release-version: 5.11.5

#9705 Cellular: Fix cellular stack and drivers for netsocket tests
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26.h
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9730 Greentea: Remove TLSSocket_simultaneous test
  TESTS/netsocket/tls/main.cpp
Labels: needs: review

#9753 Update Nanostack_HAL licenses and copyright year
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_fhss_timer.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_interrupt.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_interrupt_private.h
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_random.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/cs_nvm/cs_nvm.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/cs_nvm/test/test_cs_nvm_unit/unittest/cs_nvm/csnvmtest.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/cs_nvm/test/test_cs_nvm_unit/unittest/cs_nvm/main.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/cs_nvm/test/test_cs_nvm_unit/unittest/cs_nvm/test_cs_nvm.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/cs_nvm/test/test_cs_nvm_unit/unittest/cs_nvm/test_cs_nvm.h
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/cs_nvm/test/test_cs_nvm_unit/unittest/stubs/configuration_store_stub.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/cs_nvm/test/test_cs_nvm_unit/unittest/stubs/configuration_store_stub.h
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/cs_nvm/test/test_cs_nvm_unit/unittest/stubs/ns_trace_stub.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/cs_nvm/test/test_cs_nvm_unit/unittest/stubs/nsdynmemLIB_stub.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/cs_nvm/test/test_cs_nvm_unit/unittest/stubs/nsdynmemLIB_stub.h
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/cs_nvm/test/test_cs_nvm_unit/unittest/stubs/timeout_stub.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.h
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop_mbed.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop_mutex.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop_mutex.h
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_hal_init.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_hal_init.h
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/nvm/nvm_ram.c
Labels: ready for merge, release-version: 5.11.5

#9755 support in more types then just RSA_KEYPAIR
  components/TARGET_PSA/services/crypto/COMPONENT_PSA_SRV_IPC/psa_crypto_spm.c
Labels: ready for merge, release-version: 5.11.5

#9493 Initialize platform in trng test
  TESTS/mbed_hal/trng/main.cpp
  UNITTESTS/features/lorawan/loramaccrypto/unittest.cmake
  UNITTESTS/stubs/LoRaMacCrypto_stub.cpp
  features/device_key/source/DeviceKey.cpp
  features/lorawan/lorastack/mac/LoRaMacCrypto.cpp
  features/lorawan/lorastack/mac/LoRaMacCrypto.h
  features/lwipstack/lwip/src/apps/snmp/lwip_snmpv3_mbedtls.c
  features/mbedtls/platform/src/mbed_trng.cpp
  features/mbedtls/platform/src/platform_alt.cpp
  features/nanostack/coap-service/source/coap_security_handler.c
  features/nanostack/coap-service/test/coap-service/unittest/stub/mbedtls_stub.c
  features/nanostack/coap-service/test/coap-service/unittest/stub/mbedtls_stub.h
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_random.c
  features/netsocket/TLSSocketWrapper.cpp
  features/storage/kvstore/securestore/SecureStore.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9617 SPE: Fix up atomic usage
  components/TARGET_PSA/TARGET_MBED_SPM/COMPONENT_SPE/handles_manager.c
  components/TARGET_PSA/TARGET_MBED_SPM/COMPONENT_SPE/handles_manager.h
  components/TARGET_PSA/TARGET_MBED_SPM/COMPONENT_SPE/spm_common.c
  components/TARGET_PSA/TARGET_MBED_SPM/COMPONENT_SPE/spm_internal.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9655 Cellular: Non-IP doxygen updates
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/AT/AT_ControlPlane_netif.h
  features/cellular/mbed_lib.json
  features/netsocket/cellular/CellularNonIPSocket.h
  features/netsocket/cellular/ControlPlane_netif.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9751 Cellular: Fix ATHandler set/restore_at_timeout with mutex lock
  features/cellular/framework/AT/ATHandler.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9754 Fix SPM returning the wrong value
  components/TARGET_PSA/services/crypto/COMPONENT_PSA_SRV_IPC/psa_crypto_spm.c
Labels: ready for merge, release-version: 5.12.0-rc1

#9698 Netsocket documentation cleanup
  TESTS/netsocket/README.md
Labels: ready for merge, release-version: 5.12.0-rc1

#9690 Pinmap design doc
  docs/design-documents/hal/0002-pinmap-extension.md
Labels: ready for merge, release-version: 5.12.0-rc1

#9503 ESP8266: OOB handling done based on arrival of SIGIOs
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9555 Wio BG96: Modified sequence of module startup
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_BG96/ONBOARD_QUECTEL_BG96.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_BG96/onboard_modem_api.c
Labels: ready for merge, release-version: 5.12.0-rc1

#9736 tools/test/cmsis: add license header
  TESTS/mbedmicro-mbed/attributes/attributes.c
  TESTS/mbedmicro-mbed/attributes/weak.c
  TESTS/mbedmicro-mbed/static_assert/test_c.c
  TESTS/mbedmicro-mbed/static_assert/test_cpp.cpp
  TESTS/network/wifi/wifi_tests.h
  cmsis/mbed_cmsis_conf.h
  tools/arm_pack_manager/__init__.py
  tools/arm_pack_manager/pack_manager.py
  tools/check_release.py
  tools/dev/intel_hex_utils.py
  tools/export/exporters.py
  tools/host_tests/midi.py
  tools/importer/importer.py
  tools/memap.py
  tools/misc/find_c_includes.py
  tools/misc/remove-device-h.py
  tools/project.py
  tools/test/__init__.py
  tools/test/examples/examples.py
  tools/test/examples/examples_lib.py
  tools/test/memap/parse_test.py
  tools/test/pylint.py
  tools/test/spm/__init__.py
  tools/test/toolchains/api_test.py
  tools/test/toolchains/arm_support_test.py
  tools/test_configs/__init__.py
Labels: ready for merge, release-version: 5.11.5

#9756 PSOC6: enable export to CMake
  tools/export/cmake/__init__.py
  tools/export/exporters.py
  tools/export/makefile/__init__.py
Labels: ready for merge, release-version: 5.11.5

#9763 BLE: fixed initialisation order in GattServer
  features/FEATURE_BLE/ble/GattServer.h
Labels: ready for merge, release-version: 5.11.5

#9765 Add config header to assembly compilation
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.11.5

#9554 Wio 3G: Modified sequence of module startup.
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/ONBOARD_QUECTEL_UG96.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/ONBOARD_QUECTEL_UG96.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/onboard_modem_api.c
Labels: ready for merge, release-version: 5.12.0-rc1

#9616 nRF52 serial: Tighten/simplify atomics
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
Labels: ready for merge, release-version: 5.11.5

#9775 PSOC6: fix port_write API
  targets/TARGET_Cypress/TARGET_PSOC6/port_api.c
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/port_api.c
Labels: ready for merge, release-version: 5.11.5

#9776 adv builder helper now returns an object
  features/FEATURE_BLE/ble/gap/AdvertisingDataSimpleBuilder.h
Labels: ready for merge, release-version: 5.11.5

#9277 Sleep: error flags fix
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: BREAKING-CHANGE, ready for merge, release-version: 5.12.0-rc1

#9759 Multiple memory handling fixes
  UNITTESTS/features/netsocket/DTLSSocketWrapper/test_DTLSSocketWrapper.cpp
  UNITTESTS/features/netsocket/NetworkInterface/test_NetworkInterface.cpp
  UNITTESTS/features/netsocket/TCPSocket/test_TCPSocket.cpp
  UNITTESTS/features/netsocket/TLSSocketWrapper/test_TLSSocketWrapper.cpp
  UNITTESTS/features/netsocket/WiFiAccessPoint/test_WiFiAccessPoint.cpp
  UNITTESTS/stubs/NetworkStack_stub.h
  features/netsocket/InternetSocket.cpp
  features/netsocket/SocketAddress.cpp
  features/netsocket/SocketAddress.h
  features/netsocket/TLSSocketWrapper.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9745 Fix incorrect return value in psa_security_lifecycle_state (emul)
  components/TARGET_PSA/services/platform/COMPONENT_PSA_SRV_EMUL/platform_emul.c
Labels: ready for merge, release-version: 5.12.0-rc1

#9774 license: use .md extension
  LICENSE.md
Labels: ready for merge, release-version: 5.11.5

#9219 LoRaWAN: Retiring LoRaWANBase class
  features/lorawan/LoRaWANBase.h
  features/lorawan/LoRaWANInterface.cpp
  features/lorawan/LoRaWANInterface.h
  features/lorawan/LoRaWANStack.h
  features/lorawan/lorastack/mac/LoRaMac.h
  features/lorawan/lorastack/mac/LoRaMacCommand.h
  features/lorawan/lorastack/phy/LoRaPHY.h
  features/lorawan/lorastack/phy/LoRaPHYAS923.h
  features/lorawan/lorastack/phy/LoRaPHYAU915.h
  features/lorawan/lorastack/phy/LoRaPHYCN470.h
  features/lorawan/lorastack/phy/LoRaPHYCN779.h
  features/lorawan/lorastack/phy/LoRaPHYEU433.h
  features/lorawan/lorastack/phy/LoRaPHYEU868.h
  features/lorawan/lorastack/phy/LoRaPHYIN865.h
  features/lorawan/lorastack/phy/LoRaPHYKR920.h
  features/lorawan/lorastack/phy/LoRaPHYUS915.h
  features/lorawan/lorastack/phy/lora_phy_ds.h
  features/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9670 Add units to timeout argument in EventFlags
  rtos/EventFlags.cpp
  rtos/EventFlags.h
  rtos/Mail.h
  rtos/Mutex.h
  rtos/Queue.h
  rtos/Semaphore.h
  rtos/ThisThread.h
  rtos/Thread.h
Labels: ready for merge, release-version: 5.11.5

#9782 Adding RHOMBIO_L476DMW1K as a new Board target
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_RHOMBIO_L476DMW1K/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_RHOMBIO_L476DMW1K/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_RHOMBIO_L476DMW1K/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_RHOMBIO_L476DMW1K/system_clock.c
  targets/targets.json
Labels: ready for merge, release-version: 5.11.5, scope: new-target

#9777 Adding STM32_L475 as a new MTB target
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_MTB_STM_L475/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_MTB_STM_L475/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_MTB_STM_L475/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_MTB_STM_L475/system_clock.c
  targets/targets.json
Labels: ready for merge, release-version: 5.11.5, scope: new-target

#9767 Remove ITM from NRF52_DK and DELTA_DFBM_NQ620 targets
  targets/TARGET_NORDIC/TARGET_NRF5x/README.md
  targets/targets.json
Labels: needs: review, release-version: 5.11.5

#9783 Ensure header CRC is written as unsigned int
  tools/build_api.py
Labels: needs: CI, release-version: 5.12.0-rc1

#9796 New Wiced binaries
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_CY8CKIT_062_4343W/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_CY8CKIT_062_WIFI_BT/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_CY8CMOD_062_4343W/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_CYW943012P6EVB_01/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_CY8CKIT_062_4343W/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_CY8CKIT_062_WIFI_BT/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_CY8CMOD_062_4343W/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_CYW943012P6EVB_01/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_CY8CKIT_062_4343W/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_CY8CKIT_062_WIFI_BT/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_CY8CMOD_062_4343W/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_CYW943012P6EVB_01/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
Labels: needs: CI, release-version: 5.12.0-rc1

#9798 STM32 LPTICKER (LPTIM): correct init execution after bootloader
  targets/TARGET_STM/lp_ticker.c
Labels: needs: CI, release-version: 5.11.5

#9772 Additions to TF-M source integration
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/mbed_lib.json
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_spm.c
  components/TARGET_PSA/TARGET_TFM/mbed_lib.json
  components/TARGET_PSA/TARGET_TFM/tf-m-integration.md
  requirements.txt
  tools/importer/tfm_importer.json
  tools/psa/tfm/__init__.py
  tools/psa/tfm/bin_utils/__init__.py
  tools/psa/tfm/bin_utils/assemble.py
  tools/psa/tfm/bin_utils/imgtool.py
  tools/psa/tfm/bin_utils/imgtool_lib/__init__.py
  tools/psa/tfm/bin_utils/imgtool_lib/image.py
  tools/psa/tfm/bin_utils/imgtool_lib/keys.py
  tools/psa/tfm/bin_utils/imgtool_lib/version.py
  tools/psa/tfm/mbed_app.json
Labels: needs: CI, release-version: 5.12.0-rc1

#9752 Add comment fix warning
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
Labels: needs: CI, release-version: 5.12.0-rc1

#9708 Implement PSA protected storage & restructure PSA storage implementation
  TESTS/mbed-crypto/sanity/main.cpp
  TESTS/psa/entropy_inject/main.cpp
  TESTS/psa/its/main.cpp
  TESTS/psa/its_ps/main.cpp
  components/TARGET_PSA/TARGET_MBED_SPM/psa_defs.h
  components/TARGET_PSA/inc/psa/error.h
  components/TARGET_PSA/inc/psa/protected_storage.h
  components/TARGET_PSA/inc/psa/storage_common.h
  components/TARGET_PSA/services/crypto/COMPONENT_PSA_SRV_IPC/psa_crypto_spm.c
  components/TARGET_PSA/services/platform/COMPONENT_PSA_SRV_IMPL/platform_srv_impl.c
  components/TARGET_PSA/services/platform/COMPONENT_SPE/platform_partition.c
  components/TARGET_PSA/services/psa_prot_internal_storage/COMPONENT_PSA_SRV_IMPL/pits_impl.h
  components/TARGET_PSA/services/psa_prot_internal_storage/psa_prot_internal_storage.h
  components/TARGET_PSA/services/storage/common/psa_storage_common_impl.cpp
  components/TARGET_PSA/services/storage/common/psa_storage_common_impl.h
  components/TARGET_PSA/services/storage/its/COMPONENT_PSA_SRV_EMUL/psa_prot_internal_storage.cpp
  components/TARGET_PSA/services/storage/its/COMPONENT_PSA_SRV_IMPL/TARGET_TFM/its_tfm_impl.cpp
  components/TARGET_PSA/services/storage/its/COMPONENT_PSA_SRV_IMPL/pits_impl.cpp
  components/TARGET_PSA/services/storage/its/COMPONENT_PSA_SRV_IMPL/pits_impl.h
  components/TARGET_PSA/services/storage/its/COMPONENT_PSA_SRV_IPC/psa_prot_internal_storage.c
  components/TARGET_PSA/services/storage/its/COMPONENT_SPE/TARGET_MBED_SPM/psa_its_partition.c
  components/TARGET_PSA/services/storage/its/COMPONENT_SPE/its_partition.c
  components/TARGET_PSA/services/storage/its/COMPONENT_SPE/psa_its_partition.h
  components/TARGET_PSA/services/storage/its/pits_psa.json
  components/TARGET_PSA/services/storage/its/psa_its_ifs.h
  components/TARGET_PSA/services/storage/its/psa_prot_internal_storage.h
  components/TARGET_PSA/services/storage/ps/COMPONENT_NSPE/protected_storage.cpp
  features/mbedtls/mbed-crypto/VERSION.txt
  features/mbedtls/mbed-crypto/importer/Makefile
  features/mbedtls/mbed-crypto/inc/psa/crypto.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_extra.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_platform.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_se_driver.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_sizes.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_types.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_values.h
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto.c
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto_core.h
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto_service_integration.h
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto_slot_management.c
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto_storage.c
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto_storage.h
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto_storage_backend.h
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto_storage_file.c
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto_storage_its.c
  features/mbedtls/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/src/default_random_seed.cpp
  targets/targets.json
  tools/psa/generate_tfm_partition_code.py
Labels: needs: CI, release-version: 5.12.0-rc1

#9802 Fix psa_system_reset() on PSA IPC platform
  components/TARGET_PSA/services/platform/COMPONENT_PSA_SRV_IPC/platform_ipc.c
Labels: needs: CI, release-version: 5.12.0-rc1

#9806 Update mbed_stats.c to use __ARMCC_VERSION flag for compatibility with AC6
  platform/mbed_stats.c
Labels: ready for merge, release-version: 5.12.0-rc1

#9807 IAR 8 version update
  tools/test/toolchains/api_test.py
  tools/toolchains/iar.py
Labels: ready for merge, release-version: feature branch

#9666 Use new delivery for FUTURE_SEQUANA_PSA
  TESTS/psa/spm_client/TARGET_FUTURE_SEQUANA_PSA/spm_client.hex
  TESTS/psa/spm_server/TARGET_FUTURE_SEQUANA_PSA/spm_server.hex
  TESTS/psa/spm_smoke/TARGET_FUTURE_SEQUANA_PSA/spm_smoke.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/README.md
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/export_binaries.py
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/psa_debug_1.0.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/psa_release_1.0.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/spm_client.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/spm_server.hex
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/TARGET_FUTURE_SEQUANA_PSA/prebuilt/spm_smoke.hex
  targets/targets.json
Labels: ready for merge, release-version: 5.12.0-rc1

#9825 Remove unnecessary prints in FileSystemStore class
  features/storage/kvstore/filesystemstore/FileSystemStore.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9822 return the new values for key type & size even if function fails
  components/TARGET_PSA/services/crypto/COMPONENT_SPE/psa_crypto_partition.c
Labels: ready for merge, release-version: 5.12.0-rc1

#9791 Support mbed_start_application for Cortex-M0+
  platform/mbed_application.c
  platform/mbed_application.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9821 PSOC6: send HCI reset after patch RAM download
  features/FEATURE_BLE/targets/TARGET_Cypress/TARGET_CYW43XXX/HCIDriver.cpp
Labels: ready for merge, release-version: 5.12.0-rc1, risk: G

#9829 Fix SPM error codes
  components/TARGET_PSA/services/crypto/COMPONENT_PSA_SRV_IPC/psa_crypto_spm.c
Labels: ready for merge, release-version: 5.12.0-rc1, risk: G
