Repository ARMmbed/mbed-os, pull requests merged in 2019-09, with the labels that each got.

#11306 At handler improvements
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/AT_CellularInformation.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularInformation.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularInformation.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_ControlPlane_netif.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularContext.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularInformation.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96_CellularContext.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularStack.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.cpp
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910.cpp
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910_CellularContext.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.h
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularStack.cpp
Labels: release-version: 5.14.0-rc1

#11291 Stm32 ospi qspi fallback support
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/PeripheralPins.c
  targets/TARGET_STM/qspi_api.c
  tools/targets/STM32_gen_PeripheralPins.py
Labels: ready for merge, release-version: 5.14.0-rc1

#11391 EvenQueue: fix template functions passing UserAllocatedEvent<...> as argument.
  events/EventQueue.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11400 nsapi_dns: cleanup dns queue when running out or memory
  features/netsocket/nsapi_dns.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11402 STM32L4 USB device
  targets/TARGET_STM/USBPhy_STM32.cpp
  targets/targets.json
Labels: ready for merge, release-version: 5.14.0-rc1

#10684 Cellular: fix ATHandler destructor possible crash on delete
  UNITTESTS/features/cellular/framework/AT/at_cellularbase/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularinformation/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  UNITTESTS/features/cellular/framework/AT/athandler/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellularcontext/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellularstatemachine/unittest.cmake
  UNITTESTS/features/lorawan/loramac/unittest.cmake
  UNITTESTS/features/lorawan/lorawaninterface/unittest.cmake
  UNITTESTS/features/lorawan/lorawanstack/unittest.cmake
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/ConditionVariable_stub.cpp
  UNITTESTS/stubs/ConditionVariable_stub.h
  UNITTESTS/stubs/mbed_rtos_rtx_stub.c
  UNITTESTS/stubs/rtx_mutex_stub.c
  UNITTESTS/target_h/cmsis_os2.h
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/AT_CellularStack.h
Labels: ready for merge, release-version: 5.14.1

#11314 Add executable analaysis tool for floating point checks.
  tools/executable_analysis_tools/elf-float-checker.py
  tools/executable_analysis_tools/test_elf-float-checker.py
Labels: ready for merge, release-version: 5.14.1

#11330 RTL8195AM - resuscitate AMEBA GCC/ARMCC support
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/device/TOOLCHAIN_GCC_ARM/rtl8195a.ld
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/i2c_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/pwmout_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/serial_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/spi_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/os/cmsis_rtos/cmsis_rtos_service.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/os/os_dep/osdep_service.c
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/os/os_dep/tcm_heap.c
  targets/targets.json
Labels: release-version: 5.14.1

#11338 Bring down interface when stopping softap
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdSoftAPInterface.cpp
Labels: ready for merge, release-version: 5.14.1

#11381 M263: Enlarge required deep sleep latency
  targets/targets.json
Labels: release-version: 5.14.1

#11383 Change LSI_VALUE in STM implementation.
  targets/TARGET_STM/TARGET_STM32F0/device/stm32f0xx_ll_rcc.h
  targets/TARGET_STM/TARGET_STM32F3/device/stm32f3xx_ll_rcc.h
  targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_ll_rcc.h
Labels: release-version: 5.14.1

#11380 M263: Enlarge LPTICKER_DELAY_TICKS for safe
  targets/targets.json
Labels: ready for merge, release-version: 5.14.1

#11368 Add pin speed controlling interface
  targets/TARGET_STM/PinNamesTypes.h
  targets/TARGET_STM/pinmap.c
Labels: ready for merge, release-version: 5.14.1

#11393 Cast void pointer before deallocating with delete[]
  rtos/source/Thread.cpp
Labels: ready for merge, release-version: 5.14.1

#11379 M263: Fix FPGA CI testing failing
  targets/TARGET_NUVOTON/TARGET_M261/PeripheralPins.c
  targets/TARGET_NUVOTON/TARGET_M261/PinNames.h
  targets/TARGET_NUVOTON/TARGET_M261/analogin_api.c
  targets/TARGET_NUVOTON/TARGET_M261/analogout_api.c
  targets/TARGET_NUVOTON/TARGET_M261/dma_api.c
  targets/TARGET_NUVOTON/TARGET_M261/gpio_api.c
  targets/TARGET_NUVOTON/TARGET_M261/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M261/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M261/objects.h
  targets/TARGET_NUVOTON/TARGET_M261/pinmap.c
  targets/TARGET_NUVOTON/TARGET_M261/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_M261/serial_api.c
  targets/TARGET_NUVOTON/TARGET_M261/spi_api.c
  targets/TARGET_NUVOTON/TARGET_M261/us_ticker.c
Labels: ready for merge, release-version: 5.14.1

#11410 Mesh API, Wi-SUN: Initialize Wi-SUN settings with values from json
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: 5.14.1

#11046 Initial implementation of Cypress Crypto hardware acceleration for mbedTLS
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/TARGET_PSOC6_01/sha1_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/TARGET_PSOC6_01/sha256_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/TARGET_PSOC6_01/sha512_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/TARGET_PSOC6_02/sha1_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/TARGET_PSOC6_02/sha256_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/TARGET_PSOC6_02/sha512_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/aes_alt.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/aes_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/crypto_common.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/crypto_common.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/ecdsa_alt.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/ecp_alt.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/ecp_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/ecp_curves_alt.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/mbedtls_device.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/sha1_alt.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/sha256_alt.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_PSOC6/sha512_alt.c
  targets/targets.json
Labels: ready for merge, release-version: 5.14.1

#11382 Use very verbose to see more details in case of problem
  tools/test/examples/examples_lib.py
Labels: ready for merge, release-version: 5.14.1

#11395 Avoid non-trivial copy when initializing lorastack struct
  features/lorawan/lorastack/mac/LoRaMac.cpp
Labels: ready for merge, release-version: 5.14.1

#11394 Replace wait_ms calls with rtos::ThisThread::sleep_for
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.cpp
Labels: release-version: 5.14.1

#11385 Fix problem with low level lp_ticker STM wrapper
  targets/TARGET_STM/lp_ticker.c
Labels: ready for merge, release-version: 5.14.1

#11396 Remove floating point from AT_CellularSMS
  features/cellular/framework/AT/AT_CellularSMS.cpp
Labels: ready for merge, release-version: 5.14.1

#11372 Cellular: Fix BG96 power on and connect
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/unittest.cmake
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.h
Labels: ready for merge, release-version: 5.14.1

#11376 Update PDL documentation and metadata
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/RELEASE.md
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/drivers/include/cy_usbfs_dev_drv.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/personalities/peripheral/connectivity_bt-1.0.cypersonality
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/personalities/peripheral/connectivity_wifi-1.0.cypersonality
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/personalities/peripheral/csd-2.0.cypersonality
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/personalities/platform/power-1.2.cypersonality
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/version.xml
Labels: ready for merge, release-version: 5.14.0-rc2

#11418 NRF52: fix config
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/mbed_lib.json
  targets/targets.json
Labels: ready for merge, release-version: 5.14.0-rc2

#11419 Adds missing include required by fixed-width format specifiers
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
Labels: ready for merge, release-version: 5.14.1

#10991 Explaining how to opt in modules
  features/cryptocell/FEATURE_CRYPTOCELL310/Readme.md
Labels: ready for merge, release-version: 5.14.1

#11423 Nanostack release for mbedos 5 14
  features/nanostack/sal-stack-nanostack/Makefile
  features/nanostack/sal-stack-nanostack/nanostack/ws_bbr_api.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps/Generic/protocol_6lowpan_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common_defines.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_llc.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_llc_data_service.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_neighbor_class.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_lib.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_lib.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.h
  features/nanostack/sal-stack-nanostack/source/Common_Protocols/icmpv6.c
  features/nanostack/sal-stack-nanostack/source/Core/ns_monitor.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_control.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_control.h
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_downward.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/auth_eap_tls_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/auth_eap_tls_sec_prot.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/supp_eap_tls_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/supp_eap_tls_sec_prot.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot/auth_fwh_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot/auth_fwh_sec_prot.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot/supp_fwh_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot/supp_fwh_sec_prot.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot/auth_gkh_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot/auth_gkh_sec_prot.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot/supp_gkh_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot/tls_sec_prot_lib.c
  features/nanostack/sal-stack-nanostack/source/ipv6_stack/protocol_ipv6.c
Labels: ready for merge, release-version: 5.14.0-rc2

#11427 ESP8266Interface buffer null-terminated and parameters of scan function in correct order
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 5.14.1

#11408 Remove mbed_trace dependency to Nanomesh headers
  features/frameworks/mbed-trace/mbed-trace/mbed_trace.h
  features/frameworks/nanostack-libservice/mbed-client-libservice/ns_trace.h
Labels: ready for merge, release-version: 5.14.1

#11332 mbed_error.c: Better HW fault exceptions and stack dump
  platform/mbed_lib.json
  platform/source/TARGET_CORTEX_M/mbed_fault_handler.c
  platform/source/mbed_error.c
Labels: ready for merge, release-version: 5.15.0-rc1

#11412 Kinetis update to fix tickless
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/sleep.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/serial_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/sleep.c
Labels: ready for merge, release-version: 5.14.0-rc2

#11377 Fixed byte string related TypeError if using python3.
  TESTS/host_tests/pyusb_msd.py
Labels: ready for merge, release-version: 5.14.1

#11006 Introduce an Mbed config to enable XIP
  targets/TARGET_Cypress/TARGET_PSOC6/mbed_overrides.c
  targets/targets.json
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 5.15.0-rc1

#11438 Correct doxy-spellchecker error message
  tools/test/travis-ci/doxy-spellchecker/spell.sh
Labels: ready for merge, release-version: 5.14.1

#11435 Update to Mbed TLS 2.19.0 and Mbed Crypto 2.0.0
  features/mbedtls/VERSION.txt
  features/mbedtls/importer/Makefile
  features/mbedtls/inc/mbedtls/check_config.h
  features/mbedtls/inc/mbedtls/config.h
  features/mbedtls/inc/mbedtls/net_sockets.h
  features/mbedtls/inc/mbedtls/version.h
  features/mbedtls/mbed-crypto/VERSION.txt
  features/mbedtls/mbed-crypto/importer/Makefile
  features/mbedtls/mbed-crypto/inc/mbedtls/bignum.h
  features/mbedtls/mbed-crypto/inc/mbedtls/bn_mul.h
  features/mbedtls/mbed-crypto/inc/mbedtls/ecdh.h
  features/mbedtls/mbed-crypto/inc/mbedtls/ecdsa.h
  features/mbedtls/mbed-crypto/inc/mbedtls/ecp.h
  features/mbedtls/mbed-crypto/inc/psa/crypto.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_platform.h
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto.c
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_its_file.c
  features/mbedtls/mbed-crypto/src/bignum.c
  features/mbedtls/mbed-crypto/src/des.c
  features/mbedtls/mbed-crypto/src/ecdh.c
  features/mbedtls/mbed-crypto/src/ecdsa.c
  features/mbedtls/mbed-crypto/src/ecjpake.c
  features/mbedtls/mbed-crypto/src/ecp.c
  features/mbedtls/mbed-crypto/src/hmac_drbg.c
  features/mbedtls/mbed-crypto/src/platform_util.c
  features/mbedtls/mbed-crypto/src/sha512.c
  features/mbedtls/src/Makefile
  features/mbedtls/src/net_sockets.c
  features/mbedtls/src/ssl_tls.c
  features/mbedtls/src/x509_crt.c
  features/mbedtls/src/x509write_crt.c
  features/mbedtls/src/x509write_csr.c
Labels: ready for merge, release-version: 5.14.0-rc2

#11417 Change stack sizes of threads used in tests. GR_LYCHEE failing CI
  TESTS/mbed_platform/stats_cpu/main.cpp
  TESTS/mbedmicro-rtos-mbed/threads/main.cpp
Labels: ready for merge, release-version: 5.14.1

#11414 Cellular: Add API to clear CellularDevice
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  UNITTESTS/stubs/AT_CellularNetwork_stub.cpp
  UNITTESTS/stubs/CellularDevice_stub.cpp
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/mbed_lib.json
Labels: ready for merge, release-version: 5.15.0-rc1

#11448 STM license file update
  targets/TARGET_STM/TARGET_STM32F0/flash_api.c
  targets/TARGET_STM/TARGET_STM32F1/flash_api.c
  targets/TARGET_STM/TARGET_STM32F2/flash_api.c
  targets/TARGET_STM/TARGET_STM32F3/flash_api.c
  targets/TARGET_STM/TARGET_STM32F4/flash_api.c
  targets/TARGET_STM/TARGET_STM32F7/flash_api.c
  targets/TARGET_STM/TARGET_STM32H7/flash_api.c
  targets/TARGET_STM/TARGET_STM32L0/flash_api.c
  targets/TARGET_STM/TARGET_STM32L1/flash_api.c
  targets/TARGET_STM/TARGET_STM32L4/flash_api.c
  targets/TARGET_STM/TARGET_STM32WB/flash_api.c
Labels: release-version: 5.14.1

#11447 Coverity changes in USBHID.cpp
  drivers/source/usb/USBHID.cpp
Labels: ready for merge, release-version: 5.14.1

#11443 Enable asynchronous serial with DMA for K66F
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/dma_reqs.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/serial_api.c
  targets/targets.json
Labels: release-version: 5.14.1

#11449 Coverity changes in USBDevice.cpp
  drivers/source/usb/USBDevice.cpp
Labels: ready for merge, release-version: 5.14.1

#11254 Update gcc.py for preprocessing in linker script
  tools/toolchains/gcc.py
Labels: ready for merge, release-version: 5.14.1

#11384 ST DISCO-H747I introduction
  targets/TARGET_STM/TARGET_STM32H7/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/device/system_stm32h7xx.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/system_clock.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/system_stm32h7xx.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I_CM7/TOOLCHAIN_ARM_STD/startup_stm32h747xx.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I_CM7/TOOLCHAIN_ARM_STD/stm32h747xI.sct
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I_CM7/TOOLCHAIN_GCC_ARM/STM32H747xI.ld
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I_CM7/TOOLCHAIN_GCC_ARM/startup_stm32h747xx.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I_CM7/TOOLCHAIN_IAR/startup_stm32h747xx.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I_CM7/TOOLCHAIN_IAR/stm32h747xI.icf
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/device/stm32h747xx.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/flash_data.h
  targets/TARGET_STM/TARGET_STM32H7/us_ticker_data.h
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
Labels: release-version: 5.14.1, scope: new-target

#11420 Fixed smsc9220_emac link_out memory management.
  features/netsocket/emac-drivers/TARGET_ARM_SSG/COMPONENT_SMSC9220/smsc9220_emac.cpp
Labels: ready for merge, release-version: 5.14.1

#11441 Organize source files and add Doxygen labels
  TESTS/mbedmicro-rtos-mbed/systimer/main.cpp
  events/source/equeue_mbed.cpp
  platform/mbed_thread.h
  platform/source/SysTimer.cpp
  platform/source/SysTimer.h
  platform/source/mbed_os_timer.cpp
  platform/source/mbed_os_timer.h
  platform/source/mbed_thread.cpp
  rtos/source/Kernel.cpp
  rtos/source/Semaphore.cpp
  rtos/source/TARGET_CORTEX/mbed_rtx_idle.cpp
  rtos/source/ThisThread.cpp
Labels: ready for merge, release-version: 5.14.0-rc2, risk: A

#11450 Minimal-printf: Set default configurations to false
  platform/mbed_lib.json
  platform/source/minimal-printf/README.md
Labels: ready for merge, release-version: 5.14.0-rc2, risk: A

#11421 Dns synchronous cache fix
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/dns/synchronous_dns_cache.cpp
Labels: ready for merge, release-version: 5.14.1

#11445 Add catch-all rule to makefile template
  tools/export/makefile/Makefile.tmpl
Labels: ready for merge, release-version: 5.14.1

#11424 Stack type ip versions
  UNITTESTS/stubs/CellularUtil_stub.cpp
  features/cellular/framework/AT/AT_CellularBase.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/common/CellularUtil.cpp
  features/cellular/framework/common/CellularUtil.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
Labels: ready for merge, release-version: 5.14.1

#11465 Updated mbedTLS CRYPTO target to be more flexibly configured for supported boards
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/TARGET_MXCRYPTO_01/sha1_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/TARGET_MXCRYPTO_01/sha256_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/TARGET_MXCRYPTO_01/sha512_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/TARGET_MXCRYPTO_02/sha1_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/TARGET_MXCRYPTO_02/sha256_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/TARGET_MXCRYPTO_02/sha512_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/aes_alt.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/aes_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/crypto_common.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/crypto_common.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/ecdsa_alt.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/ecp_alt.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/ecp_alt.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/ecp_curves_alt.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/mbedtls_device.h
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/sha1_alt.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/sha256_alt.c
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/sha512_alt.c
  targets/targets.json
Labels: ready for merge, release-version: 5.14.1

#11472 Suppress Coverity warnings
  platform/source/mbed_retarget.cpp
  rtos/source/TARGET_CORTEX/rtx4/cmsis_os1.c
Labels: ready for merge, release-version: 5.14.1

#11409 esp8266 nonblocking connect/disconnect
  TESTS/network/wifi/README.md
  TESTS/network/wifi/main.cpp
  TESTS/network/wifi/wifi_connect_disconnect_nonblock.cpp
  TESTS/network/wifi/wifi_tests.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
Labels: ready for merge

#11459 Replaced in ESP8266::_oob_* recv() with scanf()
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
Labels: ready for merge, release-version: 5.15.0-rc1

#11484 Delaying message id random initialization to later stage.
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.14.0-rc3

#11474 Remove Mbed Crypto source files before importing
  features/mbedtls/mbed-crypto/importer/Makefile
Labels: ready for merge, release-version: 5.14.1

#11471 STM32WB ADC : consecutive VBAT reading
  targets/TARGET_STM/TARGET_STM32WB/analogin_device.c
Labels: ready for merge, release-version: 5.14.1

#11479 no-systick targets: fix systick irq handler setup
  rtos/source/TARGET_CORTEX/mbed_rtx_idle.cpp
Labels: ready for merge, release-version: 5.14.0-rc3

#11460 ESP8266 Unified Mbed trace prints.
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: release-version: 5.14.1

#11407 Add OKDO platform
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_OKDO_ODIN_W2/PinNames.h
  targets/targets.json
Labels: needs: CI, scope: new-target

#11462 Minimal-printf: Remove file printing in README and update tables
  platform/source/minimal-printf/README.md
Labels: ready for merge

#11487 Convert TZ target name 'NPSA' to test spec platform name
  tools/test_api.py
Labels: ready for merge, release-version: 5.14.0-rc3

#11493 Update to Mbed TLS 2.19.1
  features/mbedtls/VERSION.txt
  features/mbedtls/importer/Makefile
  features/mbedtls/inc/mbedtls/check_config.h
  features/mbedtls/inc/mbedtls/ssl.h
  features/mbedtls/src/ssl_tls.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot/tls_sec_prot_lib.c
Labels: ready for merge, release-version: 5.14.0-rc3

#11440 Add missing documentation about tls testing
  TESTS/netsocket/README.md
  TESTS/netsocket/tls/cert.h
  TESTS/netsocket/tls/main.cpp
Labels: ready for merge, release-version: 5.14.1

#11452 Coverity changes in USBMSD.cpp
  drivers/source/usb/USBMSD.cpp
Labels: ready for merge, release-version: 5.14.1

#11454 ST: Change the LSI_VALUE according to documentation
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_ll_rcc.h
Labels: ready for merge, release-version: 5.14.1

#11498 iar export: fix invalid optmization flag - remove from misc
  tools/export/iar/__init__.py
Labels: ready for merge, release-version: 5.14.1

#11499 Cellular: Fix stop tag for Quectel M26 send command
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.cpp
Labels: ready for merge, release-version: 5.14.1

#11490 Cellular: Add flow control (IFC) in BG96 AT driver
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
Labels: ready for merge, release-version: 5.14.1

#11473 Fix compilation warnings from GCC in netsocket/network tests
  TESTS/netsocket/dns/synchronous_dns_cache.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tcp/tcpsocket_recv_100k.cpp
  TESTS/netsocket/tls/tlssocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/network/emac/main.cpp
  TESTS/network/interface/networkinterface_status.cpp
  TESTS/network/l3ip/main.cpp
  TESTS/network/multihoming/multihoming_asynchronous_dns.cpp
  TESTS/network/multihoming/multihoming_synchronous_dns.cpp
  TESTS/network/multihoming/multihoming_udpsocket_echotest.cpp
  TESTS/network/wifi/main.cpp
Labels: ready for merge, release-version: 5.14.1

#11470 Prevent unreachable statements and correct variable sizes.
  drivers/USBAudio.h
  rtos/source/Semaphore.cpp
  rtos/source/TARGET_CORTEX/mbed_rtos_rtx.c
  rtos/source/TARGET_CORTEX/mbed_rtx_handlers.c
Labels: ready for merge, release-version: 5.14.1

#11469 Cellular: Disable cellular.clear-on-connect by default
  features/cellular/mbed_lib.json
Labels: ready for merge, release-version: 5.15.0-rc1

#11456 IOTBTOOL-349: Correct handling of spaces in project name.
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 5.14.1

#11488 Cellular: Fix get_interface_name to not include leading zero
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  features/cellular/framework/AT/AT_CellularContext.cpp
Labels: ready for merge

#11455 minimal-printf: Add capability to run floating point tests manually
  TESTS/mbed_platform/minimal-printf/compliance/README.md
  TESTS/mbed_platform/minimal-printf/compliance/test_config.json
Labels: ready for merge, release-version: 5.14.1

#11526 Fix added to unlock AT handler mutex
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
Labels: ready for merge, release-version: 5.14.0-rc3

#11521 Bux fix: Context can be cleared using CGDCONT after sim ready state
  features/cellular/framework/device/CellularStateMachine.cpp
Labels: ready for merge, release-version: 5.14.0-rc3

#11522 Sys timer should let deep sleep happen
  platform/source/SysTimer.cpp
Labels: ready for merge, release-version: 5.14.0-rc3

#11347 Fix NRF52832 softdevice memory map
  targets/targets.json
Labels: ready for merge, release-version: 5.14.1

#11489 Examples.py add --jobs argument
  tools/test/examples/examples.py
  tools/test/examples/examples_lib.py
Labels: ready for merge, release-version: 5.14.1

#11463 Enable tickless mode in MAX32630FTHR
  targets/targets.json
Labels: ready for merge, release-version: 5.15.0-rc1

#11430 Member get_interface_name implemented in ESP8266Interface
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
Labels: ready for merge, release-version: 5.14.1

#11516 Update to latest psoc6csp
  targets/TARGET_Cypress/TARGET_PSOC6/cy_analogout_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/include/cyabs_chip.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/include/cyabs_fs.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/resource/include/cyabs_resource.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/resource/source/cyabs_resource.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/rtos/include/COMPONENT_RTX/cyabs_rtos_impl.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/rtos/include/cyabs_rtos.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/rtos/source/COMPONENT_RTX/cyabs_rtos_rtxv5.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/core_lib/include/cy_result.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_adc.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_comp.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_crc.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_dac.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_dma.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_flash.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_gpio.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_hw_resources.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_hw_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_hwmgr.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_i2c.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_i2s.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_implementation.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_interconnect.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_lptimer.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_modules.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_opamp.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_pdmpcm.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_pin_package.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_pwm.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_qspi.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_rtc.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_scb_common.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_sdhc.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_sdio.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_spi.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_system.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_tcpwm_common.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_timer.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_trng.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_uart.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_usb_dev.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_utils.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_wdt.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_adc.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_crypto_common.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_dac.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_hwmgr.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_i2c.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_pwm.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_qspi.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_scb_common.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_sdhc.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_spi.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_timer.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_uart.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_udb_sdio.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_usb_dev.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_wdt.c
Labels: ready for merge, release-version: 5.14.1

#10940 Deinitialize the pin definition
  drivers/AnalogOut.h
  hal/analogout_api.h
Labels: ready for merge, release-version: 5.15.0-rc1

#11523 Correct force inline syntax for IAR compiler
  drivers/Ticker.h
Labels: ready for merge, release-version: 5.14.1

#11525 STM32WB/STM32H7 : LSI selection when LSE is not available
  targets/TARGET_STM/TARGET_STM32H7/device/stm32h7xx_hal_rcc.h
  targets/TARGET_STM/TARGET_STM32WB/device/stm32_hal_legacy.h
  targets/TARGET_STM/lp_ticker.c
  targets/TARGET_STM/mbed_overrides.c
  targets/TARGET_STM/rtc_api.c
Labels: ready for merge, release-version: 5.14.1

#11538 Cellular: Enable IPV6 for WISE_1570
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
Labels: ready for merge, release-version: 5.14.1

#11480 Enable tickless mode in additional tested targets
  targets/targets.json
Labels: release-version: 5.15.0-rc1

#11404 FUTURE_SEQUANA: InterruptIn implementation bug fix
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/gpio_irq_api.c
Labels: ready for merge, release-version: 5.14.1

#11494 Fix Coverity issue: Initialize FlashIAP non-static member in constructor
  drivers/FlashIAP.h
  drivers/source/FlashIAP.cpp
  platform/NonCopyable.h
Labels: ready for merge, release-version: 5.14.1

#11495 Improve cellular unittests
  UNITTESTS/features/cellular/framework/AT/at_cellularbase/at_cellularbasetest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  UNITTESTS/features/cellular/framework/common/list/listtest.cpp
  UNITTESTS/features/cellular/framework/common/list/unittest.cmake
  UNITTESTS/features/cellular/framework/common/util/utiltest.cpp
  UNITTESTS/features/cellular/framework/device/cellulardevice/cellulardevicetest.cpp
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/ATHandler_stub.h
  UNITTESTS/stubs/CellularStateMachine_stub.cpp
  UNITTESTS/stubs/CellularStateMachine_stub.h
  UNITTESTS/target_h/myCellularDevice.h
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/common/CellularUtil.cpp
Labels: ready for merge, release-version: 5.14.1

#11478 Refactor CRC constructor method to remove warning
  drivers/MbedCRC.h
Labels: ready for merge, release-version: 5.14.1

#11564 Fix ARMC6 linker error for the bare metal profile
  platform/source/mbed_retarget.cpp
  rtos/source/TARGET_CORTEX/TOOLCHAIN_ARM_MICRO/mbed_boot_arm_micro.c
Labels: ready for merge, release-version: 5.14.1

#11562 STM32H7: memory relocation
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/device/TOOLCHAIN_ARM_STD/startup_stm32h743xx.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/device/TOOLCHAIN_ARM_STD/stm32h743xI.sct
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/device/TOOLCHAIN_GCC_ARM/STM32H743xI.ld
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/device/TOOLCHAIN_IAR/stm32h743xI.icf
Labels: needs: CI, release-version: 5.14.1

#11439 Remove unreachable statements warnings
  drivers/source/usb/USBDevice.cpp
  hal/mbed_pinmap_common.c
  hal/mbed_ticker_api.c
Labels: ready for merge

#11560 Explicitly set tdb internal flash size for PSoC6 Targets
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
Labels: ready for merge, release-version: 5.14.1

#11517 TCP Packet loss happens due to running of out of Mailbox size.
  features/lwipstack/lwip-sys/arch/sys_arch.h
  features/lwipstack/lwipopts.h
  features/lwipstack/mbed_lib.json
Labels: ready for merge, release-version: 5.14.1

#11568 Speed up unit test build with parallel jobs
  UNITTESTS/unit_test/test.py
Labels: ready for merge, release-version: 5.14.1

#11491 Equeue chain, add documentation of using equeue_destroy
  TESTS/events/equeue/main.cpp
  UNITTESTS/events/equeue/test_equeue.cpp
  events/equeue.h
  events/source/tests/tests.c
Labels: ready for merge, release-version: 5.14.1

#11514 ESP8266 unlocks deep sleep when disconnected
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 5.15.0-rc1

#11458 Tests: USB: Use libusb0 backend on Windows
  TESTS/host_tests/pyusb_basic.py
  TESTS/host_tests/usb_device_hid.py
Labels: ready for merge, release-version: 5.14.1

#11483 Change reset_reason test timeout.
  TESTS/mbed_drivers/reset_reason/main.cpp
  TESTS/mbed_hal/reset_reason/main.cpp
Labels: ready for merge, release-version: 5.14.1

#11590 Moved Cypress TriggerMux initialization out of the HAL and into the BSP
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/SDIO_HOST/SDIO_HOST.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/SDIO_HOST/SDIO_HOST_cfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/SDIO_HOST/SDIO_HOST_cfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/SDIO_HOST/SDIO_HOST.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/SDIO_HOST/SDIO_HOST_cfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/SDIO_HOST/SDIO_HOST_cfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_udb_sdio.c
Labels: ready for merge, release-version: 5.14.1

#11541 esp8266 _oob_* : recv() brought back where it was needed
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
Labels: ready for merge, release-version: 5.14.1

#11585 NRF52: Fixed missing guard in port_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/port_api.c
Labels: ready for merge, release-version: 5.14.1

#11587 ATCmdParser doxygen header's documentation update for scanf
  platform/ATCmdParser.h
  platform/source/ATCmdParser.cpp
Labels: ready for merge, release-version: 5.14.1

#11546 Tests: USB: Fix Python 3 compatibility
  TESTS/host_tests/pyusb_basic.py
  TESTS/host_tests/usb_device_serial.py
  requirements.txt
Labels: release-version: 5.14.1

#11518 Cypress Cordio Driver Update
  features/FEATURE_BLE/targets/TARGET_Cypress/TARGET_CYW43XXX/CyH4TransportDriver.cpp
  features/FEATURE_BLE/targets/TARGET_Cypress/TARGET_CYW43XXX/CyH4TransportDriver.h
  features/FEATURE_BLE/targets/TARGET_Cypress/TARGET_CYW43XXX/HCIDriver.cpp
Labels: ready for merge, release-version: 5.14.1

#11540 Tests: USB: Update error handling in basic tests
  TESTS/host_tests/pyusb_basic.py
Labels: ready for merge, release-version: 5.14.1

#11596 LoRa: Fix build warning about _ongoing_tx_msg
  features/lorawan/lorastack/mac/LoRaMac.cpp
Labels: ready for merge, release-version: 5.14.1

#11597 Missing errno.h include
  features/cellular/framework/AT/ATHandler.cpp
Labels: ready for merge, release-version: 5.14.1

#11535 DNS manual cleanup mechanism added
  TESTS/netsocket/dns/asynchronous_dns.cpp
  TESTS/netsocket/dns/asynchronous_dns_cache.cpp
  TESTS/netsocket/dns/asynchronous_dns_cancel.cpp
  TESTS/netsocket/dns/asynchronous_dns_external_event_queue.cpp
  TESTS/netsocket/dns/asynchronous_dns_invalid_host.cpp
  TESTS/netsocket/dns/asynchronous_dns_non_async_and_async.cpp
  TESTS/netsocket/dns/asynchronous_dns_simultaneous.cpp
  TESTS/netsocket/dns/asynchronous_dns_simultaneous_cache.cpp
  TESTS/netsocket/dns/asynchronous_dns_simultaneous_repeat.cpp
  TESTS/netsocket/dns/asynchronous_dns_timeouts.cpp
  TESTS/netsocket/dns/dns_tests.h
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/dns/synchronous_dns.cpp
  TESTS/netsocket/dns/synchronous_dns_cache.cpp
  TESTS/netsocket/dns/synchronous_dns_invalid.cpp
  TESTS/netsocket/dns/synchronous_dns_multiple.cpp
  TESTS/network/multihoming/multihoming_asynchronous_dns.cpp
  TESTS/network/multihoming/multihoming_synchronous_dns.cpp
  TESTS/network/multihoming/multihoming_tests.h
  TESTS/network/multihoming/multihoming_udpsocket_echotest.cpp
  UNITTESTS/stubs/nsapi_dns_stub.cpp
  features/netsocket/nsapi_dns.cpp
  features/netsocket/nsapi_dns.h
Labels: ready for merge, release-version: 5.15.0-rc1
