Repository ARMmbed/mbed-os, pull requests merged in 2019-07, with the labels that each got.

#10840 Cellular: cellular socket flags updated
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularStack.cpp
Labels: ready for merge, release-version: 5.13.1

#10910 Increase dns-response-wait-time
  features/netsocket/mbed_lib.json
Labels: ready for merge, release-version: 5.13.1

#10908 Fix netconn_recv_tcp_pbuf ARMC6 linker error
  features/lwipstack/LWIPStack.cpp
Labels: ready for merge, release-version: 5.13.1

#10900 Armcc5 compilation fixes
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/nanostack/nanostack-interface/Nanostack.h
Labels: ready for merge, release-version: 5.13.1

#10881 Fix Nordic/Mbed Critical Section API Inconsistency (In Builds w/o Softdevice)
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/components/libraries/README.md
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/components/libraries/util/app_util_platform.c
Labels: ready for merge, release-version: 5.13.1

#10861 Make the sys_arch_protect() mutex be recursive.
  features/lwipstack/lwip-sys/arch/lwip_sys_arch.c
Labels: ready for merge, release-version: 5.13.1

#10859 Removing I2C and SPI pin names in SDP-K1 PinNames.h file.
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_SDP_K1/PinNames.h
Labels: ready for merge, release-version: 5.13.1

#10842 Cellular: Stack type fixes
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
Labels: ready for merge, release-version: 5.13.1

#10884 NUCLEO_H743ZI2 new target support
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/PinNames.h
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1, scope: new-target

#10869 LPC55S69: fix cosFactor data size in header file
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/drivers/fsl_powerquad_data.h
Labels: ready for merge

#10829 PSA: TFM import
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/platform/include/tfm_spm_hal.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/include/tfm_spm.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/include/tfm_thread.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/psa_client.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/psa_service.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_arch_v8m.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_spm.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_svcalls.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_thread.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_boot_data.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_core.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_handler.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_nspm.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_nspm.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_secure_api.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_secure_api.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_spm_services.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_svc.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/ns_callable/tfm_psa_api_veneers.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_api.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_api.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_db.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_db_setup.h
  tools/importer/tfm_importer.json
Labels: ready for merge, release-version: 5.14.0-rc1

#10855 Nuvoton: Fix idle thread stack underflow in debug build
  rtos/mbed_lib.json
Labels: ready for merge, release-version: 5.13.1

#10921 STMOD_CELLULAR: readme file additional information
  components/cellular/COMPONENT_STMOD_CELLULAR/README.md
  components/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.cpp
Labels: ready for merge, release-version: 5.13.1

#10928 STM: Correct macro test in us_ticker_defines.h
  targets/TARGET_STM/us_ticker_defines.h
Labels: ready for merge, release-version: 5.13.1

#10920 Kinetis MCUXpresso: Update the clock drivers
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/drivers/fsl_clock.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/drivers/fsl_clock.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/drivers/fsl_clock.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/drivers/fsl_clock.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/drivers/fsl_clock.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/drivers/fsl_clock.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/drivers/fsl_clock.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/drivers/fsl_clock.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/drivers/fsl_clock.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/drivers/fsl_clock.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/drivers/fsl_clock.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/drivers/fsl_clock.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/drivers/fsl_clock.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/drivers/fsl_clock.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/drivers/fsl_clock.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/drivers/fsl_clock.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/drivers/fsl_clock.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/drivers/fsl_clock.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_clock.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_clock.h
Labels: ready for merge, release-version: 5.13.1

#10701 STM: replace C++ low power ticker wrapper with a low level wrapper
  targets/TARGET_STM/lp_ticker.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10934 Fix: Low frequency clock will now selected by given "lf_clock_src" setting.
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/NRFCordioHCIDriver.cpp
Labels: ready for merge, release-version: 5.13.1

#10619 Fastmodel: enable flashIAP and kvstore
  components/storage/blockdevice/COMPONENT_FLASHIAP/mbed_lib.json
  features/storage/TESTS/kvstore/filesystemstore_tests/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_2/main.cpp
  features/storage/TESTS/kvstore/securestore_whitebox/main.cpp
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/memory_zones.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/memory_zones.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/memory_zones.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/memory_zones.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/memory_zones.h
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10939 Fix SAADC resolution for nRF52-based targets
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
Labels: ready for merge, release-version: 5.13.1

#10925 Doubled ATHandler's BUFF_SIZE
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  features/cellular/framework/AT/ATHandler.h
Labels: ready for merge, release-version: 5.13.1

#10932 Internal delay loop code alignment to 16
  platform/mbed_wait_api_no_rtos.c
Labels: ready for merge, release-version: 5.13.1

#10938 K64F, STM32F429: IAR linker scripts dynamic heap fix
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_IAR/MK64FN1M0xxx12.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_IAR/stm32f429xx_flash.icf
Labels: ready for merge, release-version: 5.13.1

#10944 Update I2CTester for fpga-ci-test-shield
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/I2CTester.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/I2CTester.h
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/fpga_config.h
Labels: ready for merge, release-version: 5.13.2

#10894 Add adjust-check-config script to mbedtls importer
  features/mbedtls/importer/Makefile
  features/mbedtls/importer/adjust-check-config.sh
Labels: ready for merge, release-version: 5.13.2

#10820 Bring FPGA-Test-Shield tests into Mbed-os master.
  TESTS/mbed_hal_fpga_ci_test_shield/analogin/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/analogout/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/gpio/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/gpio_irq/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/pwm/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/uart/main.cpp
Labels: ready for merge, release-version: 5.13.2

#10813 Make ARMC5 and IAR develop profile also size optimized
  tools/profiles/develop.json
Labels: ready for merge, release-version: 5.14.0-rc1

#10837 Toolchain attributes - use C++11/C11
  platform/mbed_assert.h
  platform/mbed_toolchain.h
Labels: ready for merge, release-version: 5.14.0-rc1

#10948 BLE: Stop flexing on Tesla
  features/FEATURE_BLE/ble/GattCharacteristic.h
Labels: ready for merge, release-version: 5.13.2

#10961 add hal i2c test for fpga_ci_test_shield
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/i2c_test.h
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/main.cpp
Labels: ready for merge, release-version: 5.13.2

#10953 I2c ref impl k64f fixes
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/i2c_api.c
Labels: ready for merge, release-version: feature branch

#10633 Add new features to Toshiba's TMPM4G9
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/Periph_Driver/inc/txz_i2c_api.h
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/Periph_Driver/src/txz_i2c_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/device.h
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/device/TOOLCHAIN_ARM_STD/tmpm4g9f15.sct
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/gpio_irq_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/i2c_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/objects.h
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/rtc_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/serial_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/spi_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.2, scope: new-target

#10798 TARGET_TT:Add GPIO INT pin with PT1
  targets/TARGET_TT/TARGET_TT_M3HQ/gpio_irq_api.c
Labels: ready for merge, release-version: 5.13.2

#10919 AT Cellular Network: mutex lock issue
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: ready for merge, release-version: 5.13.2

#10933 Nordic NRF52832 cache ON
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/system_nrf52.c
Labels: ready for merge

#10968 Add FLASHIAP for MTB_STM_S2LP
  targets/targets.json
Labels: ready for merge, release-version: 5.13.2

#10867 LoRaPHY: Pass frequency set in rx_config() to caller
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYCN470.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
Labels: ready for merge, release-version: 5.13.2

#10874 Add new features to Toshiba's TMPM3H6
  targets/TARGET_TOSHIBA/TARGET_TMPM3H6/device.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3H6/i2c_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3H6/objects.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3H6/rtc_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3H6/serial_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3H6/spi_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.2

#10873 Add new features to Toshiba's TMPM3HQ
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/crc_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/TOOLCHAIN_ARM_STD/tmpm3hqfdfg.sct
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/TOOLCHAIN_GCC_ARM/tmpm3hqfdfg.ld
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/device/TOOLCHAIN_IAR/tmpm3hqfdfg.icf
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/flash_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/i2c_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/objects.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/periph_driver/tmpm3hq_fc.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/periph_driver/tmpm3hq_fc.h
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/rtc_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/serial_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/spi_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.2

#10868 Add C++11/14 support utility file
  platform/mbed_cxxsupport.h
Labels: ready for merge, release-version: 5.14.0-rc1

#10964 Add newline after mbed error so greentea shows it
  platform/mbed_error.c
Labels: Priority-High, ready for merge, release-version: 5.13.2

#10971 Nanostack: sync libservice with changes in master copy
  features/frameworks/nanostack-libservice/mbed-client-libservice/nsdynmemLIB.h
  features/frameworks/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c
  features/frameworks/nanostack-libservice/test/libService/unittest/nsdynmem/dynmemtest.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#10950 Enable split heap in K64F/K66F devices
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/TOOLCHAIN_ARM_STD/MK66FN2M0xxx18.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/TOOLCHAIN_GCC_ARM/MK66FN2M0xxx18.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_ARM_STD/MK64FN1M0xxx12.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_GCC_ARM/MK64FN1M0xxx12.ld
  targets/targets.json
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge, release-version: 5.13.2

#10967 ESP8266: fix driver's support AT firmware version
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
Labels: ready for merge, release-version: 5.13.1

#10984 Skip form factor pins marked as NC
  TESTS/mbed_hal_fpga_ci_test_shield/gpio/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/gpio_irq/main.cpp
Labels: ready for merge, release-version: 5.13.1

#10975 Restrict FPGA tests to Arduino form factor
  TESTS/mbed_hal_fpga_ci_test_shield/analogin/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/analogout/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/gpio/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/gpio_irq/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/pwm/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/uart/main.cpp
Labels: Priority-High, ready for merge, release-version: 5.13.1

#10466 STM32H7: WATCHDOG and RESET_REASON support
  targets/TARGET_STM/TARGET_STM32H7/device/stm32h7xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32H7/device/stm32h7xx_hal_iwdg.c
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/TARGET_STM/reset_reason.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10972 add new target IM880B
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/PinNames.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/TOOLCHAIN_ARM_MICRO/startup_stm32l151xba.S
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/TOOLCHAIN_ARM_MICRO/stm32l151cba.sct
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/TOOLCHAIN_ARM_STD/startup_stm32l151xba.S
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/TOOLCHAIN_ARM_STD/stm32l151cba.sct
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/TOOLCHAIN_GCC_ARM/STM32L151XB-A.ld
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/TOOLCHAIN_GCC_ARM/startup_stm32l151xba.S
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/TOOLCHAIN_IAR/startup_stm32l151xba.S
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/TOOLCHAIN_IAR/stm32l152xba.icf
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/cmsis.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/stm32l151xba.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/stm32l1xx.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/system_stm32l1xx.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/objects.h
  targets/targets.json
  tools/export/iar/iar_definitions.json
Labels: ready for merge, scope: new-target

#10977 Fix out-of-bounds array access in tests-mbedmicro-rtos-mbed-malloc
  TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
Labels: ready for merge

#10816 Bring FPGA SPI tests to feature-hal-spec-spi
  TESTS/mbed_hal/spi/main.cpp
  TESTS/mbed_hal/spi/spi_api_tests.h
  TESTS/mbed_hal_fpga_ci_test_shield/spi/README.MD
  TESTS/mbed_hal_fpga_ci_test_shield/spi/k66f_sclk_idle.png
  TESTS/mbed_hal_fpga_ci_test_shield/spi_master/fpga_spi_master_test.h
  TESTS/mbed_hal_fpga_ci_test_shield/spi_master/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/spi_slave/fpga_spi_slave_test.h
  TESTS/mbed_hal_fpga_ci_test_shield/spi_slave/main.cpp
  hal/spi_api.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/spi_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/spi_api.c
  targets/targets.json
  tools/test/examples/examples.json
Labels: Priority-High, ready for merge, release-version: feature branch

#10989 SPI FPGA test extension + SPI driver fix (K64F)
  TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/spi_api.c
Labels: ready for merge, release-version: 5.13.1

#10990 Fix doxygen_options.json for ResetReason
  doxygen_options.json
Labels: ready for merge, release-version: 5.13.1

#10982 STM32 LPUART minor update for easy maintenance
  targets/TARGET_STM/serial_api.c
Labels: release-version: 5.13.1

#10976 Fix error in tests-mbed_drivers-ticker when LED2 is not connected
  TESTS/mbed_drivers/ticker/main.cpp
Labels: ready for merge, release-version: 5.13.1

#10954 Watchdog: Clean up the doxygen comments
  drivers/Watchdog.h
Labels: ready for merge, release-version: 5.13.1

#10973 I2c feature update docs
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/i2c_test.h
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/main.cpp
  docs/design-documents/hal/0001-i2c-overhaul.md
  hal/i2c_api.h
Labels: Priority-High, ready for merge, release-version: feature branch

#10885 Reduce Callback.h using C++11
  platform/Callback.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11011 Allow re-initialising an I2C peripheral on Silicon Labs targets
  targets/TARGET_Silicon_Labs/TARGET_EFM32/i2c_api.c
Labels: ready for merge, release-version: 5.13.1

#11012 Remove FPGA analog out test
  TESTS/mbed_hal_fpga_ci_test_shield/analogout/main.cpp
Labels: ready for merge, release-version: 5.13.1

#11002 LPC546XX: Add pins to LPCXpresso restricted list
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/TARGET_LPCXpresso/mbed_overrides.c
Labels: ready for merge, release-version: 5.13.1

#10997 Removing absolute paths to compiler executables
  tools/export/vscode/launch.tmpl
Labels: ready for merge, release-version: 5.13.1

#11013 Revert "K64F, STM32F429: IAR linker scripts dynamic heap fix"
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_IAR/MK64FN1M0xxx12.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_IAR/stm32f429xx_flash.icf
Labels: Priority-High, ready for merge, release-version: 5.13.1

#10963 PSA TESTS: Include mbedtls/config.h before evaluating MBEDTLS_PSA_CRYPTO_C
  TESTS/mbed-crypto/sanity/main.cpp
  TESTS/psa/attestation/main.cpp
  TESTS/psa/crypto_access_control/COMPONENT_NSPE/main.cpp
  TESTS/psa/crypto_init/main.cpp
Labels: ready for merge

#11027 PSOC6: add LwIP configuration for Cypress boards
  features/lwipstack/mbed_lib.json
Labels: Manually Patch, needs: CI, release-version: 5.13.1

#10274 Add Atomic<T> template
  TESTS/mbed_platform/atomic/main.cpp
  UNITTESTS/CMakeLists.txt
  UNITTESTS/stubs/ATHandler_stub.cpp
  features/cellular/framework/AT/AT_CellularSMS.cpp
  mbed.h
  platform/Atomic.h
  platform/internal/mbed_atomic_impl.h
  platform/mbed_atomic.h
Labels: ready for merge

#11037 Apply refactoring from 50ffc35e15bd50366c3eeaa7817aec7a17d77e75
  drivers/ResetReason.h
  drivers/source/ResetReason.cpp
Labels: release-version: feature branch

#11036 Fix Watchdog Doxygen documentation
  drivers/Watchdog.h
Labels: needs: CI, release-version: feature branch

#11010 FPGA SPI: ASYNC issue
  TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
Labels: needs: CI

#10895 Reduce Event.h and EventQueue.h using C++11
  events/Event.h
  events/EventQueue.h
Labels: ready for merge

#11003 LPC MCUXpresso: Remove extra I2C transaction on byte write
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/i2c_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/objects.h
Labels: ready for merge, release-version: 5.13.2

#11022 Fix watchdog tests failing with OOM
  TESTS/mbed_drivers/watchdog/main.cpp
  TESTS/mbed_hal/watchdog/main.cpp
Labels: ready for merge

#11015 Fix wrongly declared ADC pinout for EFM32GG11 STK3701A
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG11/PeripheralPins.c
Labels: ready for merge, release-version: 5.13.2

#11008 Enable FPGA-based SPI testing on Silicon Labs targets
  targets/TARGET_Silicon_Labs/TARGET_EFM32/spi_api.c
Labels: ready for merge, release-version: 5.13.2

#11007 Fix PWM output on Silicon Labs targets for large pulsewidths
  targets/TARGET_Silicon_Labs/TARGET_EFM32/pwmout_api.c
Labels: ready for merge, release-version: 5.13.2

#11005 FPGA PWM: wait 1 period before measurement
  TESTS/mbed_hal_fpga_ci_test_shield/pwm/main.cpp
Labels: ready for merge, release-version: 5.13.2

#11004 FPGA I2C: correct init bloc number
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/main.cpp
Labels: ready for merge, release-version: 5.13.2

#10994 Add DEVICE_SERIAL_FC guards to serial HAL API
  TESTS/mbed_hal_fpga_ci_test_shield/uart/main.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/test_utils.h
  hal/serial_api.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/serial_api.c
  targets/TARGET_ARM_SSG/TARGET_MPS2/serial_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.2

#11049 Normalize line endings for IM880B startup files.
  .gitattributes
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/TOOLCHAIN_ARM_MICRO/startup_stm32l151xba.S
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/TOOLCHAIN_ARM_STD/startup_stm32l151xba.S
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/TOOLCHAIN_GCC_ARM/startup_stm32l151xba.S
  targets/TARGET_STM/TARGET_STM32L1/TARGET_IM880B/device/TOOLCHAIN_IAR/startup_stm32l151xba.S
Labels: ready for merge, release-version: 5.13.2

#11014 Increase ADC tolerance to 5% in FPGA-based tests
  TESTS/mbed_hal_fpga_ci_test_shield/analogin/main.cpp
Labels: ready for merge

#11026 Add a restricted peripheral list
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/test_utils.h
  hal/mbed_pinmap_common.c
  hal/mbed_pinmap_default.c
  hal/pinmap.h
Labels: ready for merge, release-version: 5.13.2

#11028 Fix FPGA CI Test Shield warnings
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/MbedTester.cpp
Labels: ready for merge, release-version: 5.13.2

#11042 Fixed serial_device IRQ infinite loop bug due to uint8_t overflowing in STM devices
  targets/TARGET_STM/TARGET_STM32F0/serial_device.c
  targets/TARGET_STM/TARGET_STM32F1/serial_device.c
  targets/TARGET_STM/TARGET_STM32F2/serial_device.c
  targets/TARGET_STM/TARGET_STM32F3/serial_device.c
  targets/TARGET_STM/TARGET_STM32F4/serial_device.c
  targets/TARGET_STM/TARGET_STM32F7/serial_device.c
  targets/TARGET_STM/TARGET_STM32H7/serial_device.c
  targets/TARGET_STM/TARGET_STM32L0/serial_device.c
  targets/TARGET_STM/TARGET_STM32L1/serial_device.c
  targets/TARGET_STM/TARGET_STM32L4/serial_device.c
  targets/TARGET_STM/TARGET_STM32WB/serial_device.c
Labels: ready for merge, release-version: 5.13.2

#10644 Add a gpio pinmap
  TESTS/mbed_hal/pinmap/main.cpp
  hal/gpio_api.h
  hal/mbed_gpio.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/TARGET_FRDM/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/TARGET_FRDM/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_FRDM/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_FRDM/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/PeripheralPins.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11053 Add Mbed bootloader support to CY8CKIT_062_WIFI_BT and CY8CPROTO_062_4343W
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#11052 Update MCUXpresso AnalogIn driver for LPC devices
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/analogin_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/LPC54114_cm4_features.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/drivers/fsl_adc.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/drivers/fsl_adc.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/drivers/fsl_clock.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/drivers/fsl_clock.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/TARGET_LPCXpresso/mbed_overrides.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/device/LPC54628_features.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/drivers/fsl_adc.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/drivers/fsl_adc.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/drivers/fsl_clock.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/drivers/fsl_clock.h
Labels: ready for merge, release-version: 5.13.2

#11050 DISCO_L4R9I new target
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/TOOLCHAIN_ARM_MICRO/startup_stm32l4r9xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/TOOLCHAIN_ARM_MICRO/stm32l4r9xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/TOOLCHAIN_ARM_STD/startup_stm32l4r9xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/TOOLCHAIN_ARM_STD/stm32l4r9xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/TOOLCHAIN_GCC_ARM/startup_stm32l4r9xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/TOOLCHAIN_GCC_ARM/stm32l4r9xx.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/TOOLCHAIN_IAR/startup_stm32l4r9xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/TOOLCHAIN_IAR/stm32l4r9xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/objects.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/stm32l4r9xx.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/stm32l4xx.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/system_stm32l4xx.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/us_ticker_data.h
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11058 BLE: allow overriding event signal
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioBLE.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11035 mbedtls: Update to Mbed TLS 2.18.1
  features/mbedtls/VERSION.txt
  features/mbedtls/importer/Makefile
  features/mbedtls/inc/mbedtls/platform.h
  features/mbedtls/inc/mbedtls/version.h
  features/mbedtls/mbed-crypto/VERSION.txt
  features/mbedtls/mbed-crypto/importer/Makefile
  features/mbedtls/mbed-crypto/src/ecp.c
  features/mbedtls/src/Makefile
Labels: needs: review, ready for merge, release-version: 5.13.2

#11060 MCUXpresso: Update LPC spi driver
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/objects.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/pinmap.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/spi_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/TARGET_LPCXpresso/PeripheralNames.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/TARGET_LPCXpresso/PeripheralPins.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/TARGET_LPCXpresso/device.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_LPCXpresso/PeripheralNames.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_LPCXpresso/PeripheralPins.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/TARGET_FF_LPC546XX/PeripheralNames.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/TARGET_LPCXpresso/PeripheralNames.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/TARGET_LPCXpresso/PeripheralPins.c
Labels: ready for merge, release-version: 5.13.2

#11064 MCUXpresso: Fix the LPC GPIO IRQ driver
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/gpio_irq_api.c
Labels: ready for merge, release-version: 5.13.2

#11079 NRF52840: enable TRNG in Nordic SDK config
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
Labels: ready for merge, release-version: 5.13.2

#11080 Add target for CY8CKIT_062S2_43012
  features/lwipstack/mbed_lib.json
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_clocks.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_clocks.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_notices.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_peripherals.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_peripherals.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_pins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_pins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_qspi_memslot.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_qspi_memslot.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_routing.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_routing.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_system.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/cycfg_system.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/GeneratedSource/qspi_config.cfg
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/PinNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/cybsp_cy8ckit_062s2_43012.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/cybsp_cy8ckit_062s2_43012.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/cybsp_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/design.modus
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/PeripheralNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M0/TOOLCHAIN_ARM/cy8c6xxa_cm0plus.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M0/TOOLCHAIN_ARM/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M0/TOOLCHAIN_GCC_ARM/cy8c6xxa_cm0plus.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M0/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M0/TOOLCHAIN_IAR/cy8c6xxa_cm0plus.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M0/TOOLCHAIN_IAR/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M0/system_psoc6_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M4/TOOLCHAIN_ARM/cy8c6xxa_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M4/TOOLCHAIN_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M4/TOOLCHAIN_GCC_ARM/cy8c6xxa_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M4/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M4/TOOLCHAIN_IAR/cy8c6xxa_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M4/TOOLCHAIN_IAR/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TARGET_MCU_PSOC6_M4/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_WHD/resources/nvram/TARGET_CY8CMOD_062S2_43012/wifi_nvram_image.h
  targets/targets.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11078 NRF52840: fix include path issues for ble pal cordio ll and gcc
  features/FEATURE_BLE/targets/TARGET_CORDIO_LL/stack/controller/sources/ble/bb/bb_ble_reslist.c
  features/FEATURE_BLE/targets/TARGET_CORDIO_LL/stack/controller/sources/ble/lctr/lctr_act_enc.c
  features/FEATURE_BLE/targets/TARGET_CORDIO_LL/stack/controller/sources/ble/ll/ll_main_enc_slave.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_bb_ble_rf.c
Labels: ready for merge, release-version: 5.13.2

#11062 Fix SAADC resolution for nRF52-based targets... again
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
Labels: ready for merge, release-version: 5.13.2

#11059 GCC ARM: Increase develop and release debug level
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge, release-version: 5.13.2

#11077 NRF52840: remove align instructions from gcc linker for ARM.extab exi…
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_GCC_ARM/NRF52840.ld
Labels: ready for merge, release-version: 5.13.2

#11076 ARMC5 <array> extensions
  platform/cxxsupport/TOOLCHAIN_ARMC5/array
Labels: ready for merge, release-version: 5.14.0-rc1

#11070 IAR: Suppress "exceptions are disabled" warning
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge, release-version: 5.14.0-rc1

#10847 PSA storage: Conform to "PSA 1.0.0" spec release
  TESTS/psa/its_ps/main.cpp
  components/TARGET_PSA/inc/psa/protected_storage.h
  components/TARGET_PSA/inc/psa/storage_common.h
  components/TARGET_PSA/services/storage/common/psa_storage_common_impl.cpp
  components/TARGET_PSA/services/storage/common/psa_storage_common_impl.h
  components/TARGET_PSA/services/storage/its/COMPONENT_PSA_SRV_EMUL/psa_prot_internal_storage.cpp
  components/TARGET_PSA/services/storage/its/COMPONENT_PSA_SRV_IMPL/pits_impl.cpp
  components/TARGET_PSA/services/storage/its/COMPONENT_PSA_SRV_IMPL/pits_impl.h
  components/TARGET_PSA/services/storage/its/COMPONENT_PSA_SRV_IPC/psa_prot_internal_storage.c
  components/TARGET_PSA/services/storage/its/COMPONENT_SPE/its_partition.c
  components/TARGET_PSA/services/storage/its/psa_prot_internal_storage.h
  components/TARGET_PSA/services/storage/ps/COMPONENT_NSPE/protected_storage.cpp
  features/frameworks/TARGET_PSA/pal/pal_internal_trusted_storage_intf.c
  features/frameworks/TARGET_PSA/pal/pal_protected_storage_intf.c
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_its.h
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_storage.c
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_its_file.c
  features/mbedtls/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/src/default_random_seed.cpp
  features/storage/kvstore/filesystemstore/FileSystemStore.cpp
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11084 NVStore.cpp (and KVStore) - run-time failure handling missing
  features/storage/kvstore/securestore/SecureStore.cpp
  features/storage/nvstore/source/nvstore.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11096 Fix Ethernet driver build
  hal/ethernet_api.h
Labels: release-version: feature branch

#11090 Cellular: Fix to delete context just once
  features/cellular/framework/AT/AT_CellularContext.cpp
Labels: ready for merge, release-version: 5.13.2

#11038 Extend the GPIO HAL API tests
  TESTS/mbed_hal_fpga_ci_test_shield/gpio/main.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/test_utils.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11086 Mbed-os compile without DEVICE_SERIAL
  features/frameworks/greentea-client/greentea-client/greentea_serial.h
  features/frameworks/greentea-client/source/greentea_serial.cpp
  features/frameworks/greentea-client/source/greentea_test_env.cpp
  features/frameworks/utest/source/unity_handler.cpp
  features/frameworks/utest/source/utest_default_handlers.cpp
  features/frameworks/utest/utest/utest_serial.h
Labels: ready for merge, release-version: 5.13.3

#11101 PSoC 6 I2C and SPI driver updates
  targets/TARGET_Cypress/TARGET_PSOC6/cy_i2c_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/cy_spi_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_hw_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_utils.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_i2c.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_spi.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_uart.c
Labels: ready for merge, release-version: 5.13.3

#11093 Fix CI for branch feature-public-headers
  TESTS/mbed_hal/qspi/main.cpp
  TESTS/mbed_hal/qspi/qspi_test_utils.cpp
  TESTS/mbed_hal/sleep/main.cpp
  TESTS/mbed_hal/sleep_manager/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/uart/main.cpp
  UNITTESTS/drivers/Watchdog/unittest.cmake
  drivers/source/usb/AsyncOp.cpp
  drivers/source/usb/ByteBuffer.cpp
  drivers/source/usb/EndpointResolver.cpp
  drivers/source/usb/LinkedListBase.cpp
  drivers/source/usb/OperationListBase.cpp
  drivers/source/usb/PolledQueue.cpp
  drivers/source/usb/TaskBase.cpp
  drivers/source/usb/USBAudio.cpp
  drivers/source/usb/USBCDC.cpp
  drivers/source/usb/USBCDC_ECM.cpp
  drivers/source/usb/USBDevice.cpp
  drivers/source/usb/USBHID.cpp
  drivers/source/usb/USBKeyboard.cpp
  drivers/source/usb/USBMIDI.cpp
  drivers/source/usb/USBMSD.cpp
  drivers/source/usb/USBMouse.cpp
  drivers/source/usb/USBMouseKeyboard.cpp
  drivers/source/usb/USBSerial.cpp
  drivers/source/usb/mbed_lib.json
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/NRFCordioHCIDriver.cpp
  tools/build_api.py
  tools/toolchains/mbed_toolchain.py
Labels: needs: CI, release-version: feature branch

#10947 Port the cryptocell 310 cmac driver
  features/cryptocell/FEATURE_CRYPTOCELL310/cmac_alt.c
  features/cryptocell/FEATURE_CRYPTOCELL310/cmac_alt.h
  features/cryptocell/FEATURE_CRYPTOCELL310/mbedtls_device.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11066 Cellular: Fix cellular statemachine stop and BG96 power up
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
Labels: ready for merge, release-version: 5.13.3

#11071 PSOC6: USB device implementation
  targets/targets.json
  usb/device/targets/TARGET_Cypress/TARGET_PSOC6/USBPhyHw.h
  usb/device/targets/TARGET_Cypress/TARGET_PSOC6/USBPhy_PSOC6.cpp
Labels: release-version: 5.14.0-rc1

#11074 Add a gpio-irq pinmap
  TESTS/mbed_hal/pinmap/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/gpio_irq/main.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/test_utils.h
  hal/gpio_irq_api.h
  hal/mbed_gpio_irq.c
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/gpio_irq_api.c
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/objects.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11114 Address comments on workaround for Mbed OS 2 CI build after Public
  tools/build_api.py
  tools/test/build_api/build_api_test.py
  tools/toolchains/mbed_toolchain.py
Labels: needs: review, release-version: feature branch
