Repository ARMmbed/mbed-os, pull requests merged in 2019-01, with the labels that each got.

#9209 More static place for astyle
  .travis.yml
Labels: ready for merge, release-version: 5.11.2

#9066 Equeue chaining bug fixes
  UNITTESTS/stubs/EventQueue_stub.cpp
  UNITTESTS/stubs/equeue_stub.c
  events/EventQueue.cpp
  events/EventQueue.h
  events/equeue/equeue.c
  events/equeue/equeue.h
Labels: ready for merge, release-version: 5.11.2

#9128 Fix SPM HAL test
  TESTS/mbed_hal/spm/main.cpp
Labels: ready for merge, release-version: 5.11.2

#9186 Fix ticker_read_us() race condition.
  hal/mbed_ticker_api.c
Labels: ready for merge

#9187 Resolves build failures with IAR 8.x
  components/storage/blockdevice/COMPONENT_FLASHIAP/TESTS/filesystem/fopen/fopen.cpp
  components/storage/blockdevice/COMPONENT_SD/TESTS/filesystem/files/main.cpp
  components/storage/blockdevice/COMPONENT_SD/TESTS/filesystem/seek/main.cpp
Labels: ready for merge

#9175 Greentea tests ignore bind returning UNSUPPORTED
  TESTS/netsocket/tcp/tcpsocket_bind_address.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_invalid.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_null.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_port_fail.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_unopened.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_wrong_type.cpp
  TESTS/netsocket/udp/udpsocket_bind_address.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_invalid.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_null.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_port.cpp
  TESTS/netsocket/udp/udpsocket_bind_port.cpp
  TESTS/netsocket/udp/udpsocket_bind_port_fail.cpp
  TESTS/netsocket/udp/udpsocket_bind_unopened.cpp
  TESTS/netsocket/udp/udpsocket_bind_wrong_type.cpp
Labels: ready for merge, release-version: 5.11.2

#9154 ARMC6: Use float-abi=hard
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.11.2

#9191 Nuvoton: Fix crypto compile error with Mbed OS 2
  targets/TARGET_NUVOTON/TARGET_M480/crypto/crypto-misc.cpp
  targets/TARGET_NUVOTON/TARGET_NUC472/crypto/crypto-misc.cpp
Labels: ready for merge, release-version: 5.11.2

#9197 Nuvoton: Fix UART flow control CTS/RTS
  targets/TARGET_NUVOTON/TARGET_M2351/serial_api.c
  targets/TARGET_NUVOTON/TARGET_M451/serial_api.c
  targets/TARGET_NUVOTON/TARGET_M480/serial_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/serial_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/serial_api.c
Labels: ready for merge, release-version: 5.11.2

#9198 Fixing bug - overwrite of default configuration values for RBP start address and size fails
  features/storage/kvstore/conf/kv_config.cpp
Labels: ready for merge, release-version: 5.11.2

#9202 Realtek-RTL8195AM-Hide_Debugging_Messages
  targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.cpp
  targets/TARGET_Realtek/TARGET_AMEBA/RTWInterface.h
Labels: ready for merge, release-version: 5.11.2

#9218 Change to mbedtls_platform_zeroize()
  features/cryptocell/FEATURE_CRYPTOCELL310/ecdh_alt.c
  features/cryptocell/FEATURE_CRYPTOCELL310/ecdsa_alt.c
Labels: ready for merge, release-version: 5.11.2

#9182 Disable MPU support on NRF52x platforms
  targets/targets.json
Labels: ready for merge, release-version: 5.11.2

#9220 BLE: NRF52 returns used tx/rx phy on phy update callback
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xGap.cpp
Labels: ready for merge, release-version: 5.11.2

#9246 STM32L0 TEMPERATURE ADC CHANNEL minor update
  targets/TARGET_STM/TARGET_STM32L0/analogin_device.c
  targets/TARGET_STM/TARGET_STM32L0/device/stm32l0xx_hal_adc.c
Labels: ready for merge, release-version: 5.11.2

#9250 Fix Python 3 syntax in rtc host test
  TESTS/host_tests/rtc_calc_auto.py
Labels: ready for merge, release-version: 5.11.2

#9058 BLE: suppress scan timeout if we disabled scanning
  features/FEATURE_BLE/ble/generic/GenericGap.h
  features/FEATURE_BLE/source/generic/GenericGap.cpp
Labels: ready for merge, release-version: 5.11.2

#9167 Modify IRQ handler processing when unusing RTOS at Cortex-A
  cmsis/TARGET_CORTEX_A/TOOLCHAIN_IAR/cmain.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/MBRZA1LU.sct
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/startup_RZ_A1LU.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/sys.cpp
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/weak_handler.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_GCC_ARM/startup_RZ1ALU.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_GCC_ARM/weak_handler.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_IAR/weak_handler.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/MBRZA1H.sct
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/startup_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/sys.cpp
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/weak_handler.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_GCC_ARM/startup_RZ1AH.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_GCC_ARM/weak_handler.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_IAR/weak_handler.S
Labels: ready for merge, release-version: 5.11.2

#9173 Prevent ESP8266 stopping HW control on init
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 5.11.2

#9183 Allow LwIP TCP retransmissions to be configured and tune those smaller.
  features/lwipstack/lwipopts.h
  features/lwipstack/mbed_lib.json
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/mbed_lib.json
Labels: ready for merge, release-version: 5.11.2

#9227 [SDT64B] changed UART0 to UART2, added UART_5 on SDT64B
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/PinNames.h
Labels: ready for merge, release-version: 5.11.2

#9229 hal-qspi_test: move frequency setting before flash init
  TESTS/mbed_hal/qspi/main.cpp
  TESTS/mbed_hal/qspi/qspi_test.h
Labels: ready for merge, release-version: 5.11.2

#9233 FastModel: update platform header, removed unwanted smsc9220 device
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/FVP_MPS2.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/SDK/fpga.c
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/SDK/fpga.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/cmsis.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/SMM_MPS2.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/cmsis.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/SMM_MPS2.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/cmsis.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/SMM_MPS2.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/cmsis.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/SMM_MPS2.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/cmsis.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/i2c_api.c
Labels: ready for merge, release-version: 5.11.2

#9234 nanostack-mac-tester sync with v1.0.1
  TEST_APPS/testcases/nanostack_mac_tester/ED_scan.py
Labels: ready for merge, release-version: 5.11.2

#9114 Simplified astyle travis test to be easier to reason about
  .travis.yml
Labels: ready for merge, release-version: 5.11.2

#9252 STM32L4 ADC : power optimisation for VBAT channel
  targets/TARGET_STM/TARGET_STM32L4/analogin_device.c
Labels: needs: CI, release-version: 5.11.2

#9226 Cellular: Unit tests for Non-IP socket
  UNITTESTS/features/netsocket/cellular/CellularNonIPSocket/test_CellularNonIPSocket.cpp
  UNITTESTS/features/netsocket/cellular/CellularNonIPSocket/unittest.cmake
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  UNITTESTS/stubs/CellularContext_stub.h
  UNITTESTS/stubs/ControlPlane_netif_stub.h
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_ControlPlane_netif.h
  features/cellular/framework/device/CellularContext.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularContext.cpp
  features/netsocket/cellular/CellularNonIPSocket.cpp
  features/netsocket/cellular/CellularNonIPSocket.h
  features/netsocket/cellular/ControlPlane_netif.h
Labels: ready for merge, release-version: feature branch

#9239 Increases events.shared-stacksize to 2K
  events/mbed_lib.json
Labels: ready for merge, release-version: 5.11.2

#9152 Cellular: fix state machine to check network attach
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
Labels: ready for merge, release-version: 5.11.2

#9237 Refactoring and fixing some issues in KVStore configuration.
  docs/design-documents/features/storage/Configuration/CONFIGURATION.md
  features/storage/kvstore/conf/filesystem/mbed_lib.json
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/kvstore/conf/mbed_lib.json
  features/storage/kvstore/conf/tdb_external/mbed_lib.json
Labels: BREAKING-CHANGE, ready for merge, release-version: 5.11.2

#9271 Correcting the error-case trace from mesh-api interfaces
  features/nanostack/mbed-mesh-api/source/LoWPANNDInterface.cpp
  features/nanostack/mbed-mesh-api/source/ThreadInterface.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-version: 5.11.2

#9268 Calculate FlashIAPBlockDevice start address and size automatically for test only
  components/storage/blockdevice/COMPONENT_FLASHIAP/TESTS/filesystem/fopen/fopen.cpp
Labels: ready for merge, release-version: 5.11.2

#9241 TDBStore: fix bug in sector blank check for variant sized sectors
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: ready for merge, release-version: 5.11.2

#9200 TDBStore: Perform garbage collection on failed writes
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: ready for merge, release-version: 5.11.2

#9264 reduce info traces to debug level to prevent logs overflow
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
Labels: ready for merge, release-version: 5.11.2

#9289 travis: add keys for ubuntu - workaround
  .travis.yml
Labels: needs: CI, release-version: 5.11.2

#9256 STM32L0 & STM32L1: FLASH is EEPROM
  targets/TARGET_STM/TARGET_STM32L0/flash_api.c
  targets/TARGET_STM/TARGET_STM32L1/flash_api.c
Labels: ready for merge, release-version: 5.11.2

#9278 DeviceKey: [Security Fix] Generated ROT-key is still used when TRNG fails
  features/device_key/source/DeviceKey.cpp
Labels: ready for merge, release-version: 5.11.2

#9165 Renesas : Add USB Device feature
  targets/targets.json
  usb/device/targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBEndpoints_RZ_A1.h
  usb/device/targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhyHw.h
  usb/device/targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhy_RZ_A1.cpp
  usb/device/targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhy_RZ_A1_Def.h
Labels: ready for merge, release-version: feature branch

#9290 ESP8266: Set HW reset time to 2ms
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 5.11.2

#9284 ESP8266: Fixes AT-layer socket_open-functions
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
Labels: ready for merge, release-version: 5.11.2

#9188 Add more information to error url to enhance error analytics
  platform/mbed_error.c
  platform/mbed_lib.json
  tools/toolchains/__init__.py
Labels: ready for merge, release-version: 5.12.0-rc1

#9215 Direct access to device key
  features/storage/TESTS/kvstore/direct_access_devicekey_test/main.cpp
  features/storage/kvstore/tdbstore/DirectAccessDevicekey.cpp
  features/storage/kvstore/tdbstore/DirectAccessDevicekey.h
Labels: ready for merge, release-version: 5.11.2

#9260 Use mbed_error_printf instead of debug for ISR friendly prints
  hal/mbed_sleep_manager.c
Labels: ready for merge, release-version: 5.11.2

#9269 SDT64B: Add TARGET_SDT64B, a bootloader file on SDT64B
  features/FEATURE_BOOTLOADER/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/LICENSE
  features/FEATURE_BOOTLOADER/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/mbed-bootloader-sdt64b-block_device-sotp-v3_3_0.bin
  features/FEATURE_BOOTLOADER/targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/mbed_lib.json
Labels: ready for merge, release-version: 5.11.2

#9311 Edit README.md
  events/README.md
Labels: ready for merge, release-version: 5.11.2

#9274 fix MPU compilation issue
  targets/TARGET_RDA/TARGET_UNO_91H/device/RDA5991H.h
  targets/targets.json
Labels: ready for merge, release-version: 5.11.2

#9310 SPIFBlockDevice docs update
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.h
Labels: docathlon2019, ready for merge, release-version: 5.11.2

#9313 STM32L476VG: fix wrong pin map function on ADC channels
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_DISCO_L476VG/PeripheralPins.c
Labels: ready for merge, release-version: 5.11.2

#9315 LPC546XX: Do not make MCU_LPC546XX target public
  targets/targets.json
Labels: ready for merge, release-version: 5.11.2

#9244 Kvstore tests api change to run on K64F only
  features/storage/TESTS/kvstore/filesystemstore_tests/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_2/main.cpp
  features/storage/TESTS/kvstore/securestore_whitebox/main.cpp
  features/storage/TESTS/kvstore/static_tests/main.cpp
  features/storage/TESTS/kvstore/tdbstore_whitebox/main.cpp
  features/storage/kvstore/mbed_lib.json
Labels: ready for merge, release-version: 5.11.2

#9319 tools/importer script changes
  tools/importer/importer.py
Labels: needs: CI, release-version: 5.11.2

#9346 Travis CI: Corrected astyle job behavior with non-master base branch PRs
  .travis.yml
Labels: ready for merge, release-version: 5.11.2

#9350 GD32_F450ZI: Support boot stack size configuration option
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/device/TOOLCHAIN_ARM_STD/gd32f450zi.sct
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/device/TOOLCHAIN_GCC_ARM/GD32F450xI.ld
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/device/TOOLCHAIN_IAR/gd32f450zi.icf
Labels: ready for merge, release-version: 5.12.0-rc1

#9321 STM32 : typo error in QSPI
  targets/TARGET_STM/qspi_api.c
Labels: ready for merge, release-version: 5.11.2

#9323 STM32: astyle check
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32H7/analogout_device.c
  targets/TARGET_STM/TARGET_STM32H7/common_objects.h
  targets/TARGET_STM/TARGET_STM32H7/flash_api.c
  targets/TARGET_STM/TARGET_STM32H7/pin_device.h
  targets/TARGET_STM/TARGET_STM32H7/pwmout_device.c
  targets/TARGET_STM/TARGET_STM32H7/serial_device.c
  targets/TARGET_STM/TARGET_STM32H7/spi_api.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/PinNames.h
  targets/TARGET_STM/hal_tick_overrides.c
  targets/TARGET_STM/i2c_api.c
  targets/TARGET_STM/qspi_api.c
  targets/TARGET_STM/serial_api.c
  targets/TARGET_STM/stm_spi_api.c
Labels: ready for merge, release-version: 5.11.2

#9334 Doxygen fixes in block devices
  features/storage/blockdevice/BlockDevice.h
  features/storage/blockdevice/MBRBlockDevice.h
  features/storage/blockdevice/ProfilingBlockDevice.h
  features/storage/blockdevice/SlicingBlockDevice.h
Labels: docathlon2019, ready for merge, release-version: 5.11.2

#9327 STM32: replace missing #ifdef DEVICE_xxx
  targets/TARGET_STM/TARGET_STM32H7/can_device.h
  targets/TARGET_STM/TARGET_STM32H7/common_objects.h
  targets/TARGET_STM/TARGET_STM32H7/i2c_device.h
  targets/TARGET_STM/TARGET_STM32H7/pwmout_device.c
  targets/TARGET_STM/TARGET_STM32H7/pwmout_device.h
  targets/TARGET_STM/TARGET_STM32L0/common_objects.h
Labels: ready for merge, release-version: 5.11.2

#9305 Minor Doxygen fixes for all file system classes
  features/storage/filesystem/FileSystem.h
  features/storage/filesystem/fat/FATFileSystem.h
  features/storage/filesystem/littlefs/LittleFileSystem.h
Labels: docathlon2019, ready for merge, release-version: 5.11.2

#9362 Fix the general block device for better support of low memory boards
  features/storage/TESTS/blockdevice/general_block_device/main.cpp
Labels: ready for merge, release-version: 5.11.2

#9330 Doxygen update for LoRaRadio class
  features/lorawan/LoRaRadio.h
Labels: docathlon2019, ready for merge, release-version: 5.11.2

#9355 Parameterise the repo used in the Mbed TLS importer script
  features/mbedtls/importer/Makefile
Labels: ready for merge, release-version: 5.11.2

#9295 Add missing END to Armv8M IAR assembly files
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_M23/irq_armv8mbl_common.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_IAR/TARGET_M33/irq_armv8mml_common.S
  tools/importer/cmsis_importer.json
Labels: ready for merge, release-version: 5.11.2

#9324 Avoid building mbed_tz_context.c for TF-M targets
  cmsis/TARGET_CORTEX_M/mbed_tz_context.c
  tools/importer/cmsis_importer.json
Labels: ready for merge, release-version: 5.11.2

#9341 Flush ESP8266 serial input buffers after HW reset
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 5.11.2

#9332 Update and cleanup BLE.h doxygen
  features/FEATURE_BLE/ble/BLE.h
Labels: docathlon2019, ready for merge, release-version: 5.11.2

#9329 SDBlockDevice docs update
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.h
Labels: docathlon2019, ready for merge, release-version: 5.11.2

#6622 Add nanostack support for KW41Z
  TEST_APPS/testcases/nanostack_mac_tester/ED_scan.py
  TEST_APPS/testcases/nanostack_mac_tester/address_read_and_write.py
  TEST_APPS/testcases/nanostack_mac_tester/create_and_join_PAN.py
  TEST_APPS/testcases/nanostack_mac_tester/send_data.py
  TEST_APPS/testcases/nanostack_mac_tester/send_data_indirect.py
  TEST_APPS/testcases/nanostack_mac_tester/send_large_payloads.py
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/sal-stack-nanostack/mbed_lib.json
  features/nanostack/targets/TARGET_NXP/TARGET_KW41Z/NanostackRfPhyKw41z.cpp
  features/nanostack/targets/TARGET_NXP/TARGET_KW41Z/NanostackRfPhyKw41z.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/Common/EmbeddedTypes.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/OSAbstraction/Interface/fsl_os_abstraction.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/OSAbstraction/Interface/fsl_os_abstraction_config.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/OSAbstraction/Source/fsl_os_abstraction_mbed.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_ant_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_ble_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_common_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_gfsk_bt_0p3_h_0p5_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_gfsk_bt_0p5_h_0p32_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_gfsk_bt_0p5_h_0p5_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_gfsk_bt_0p5_h_0p7_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_gfsk_bt_0p5_h_1p0_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_gfsk_bt_0p7_h_0p5_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_mode_datarate_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_msk_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/cfgs_kw4x_3x_2x/fsl_xcvr_zgbe_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/dbg_ram_capture.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/dbg_ram_capture.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/fsl_xcvr.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/fsl_xcvr.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/fsl_xcvr_trim.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/fsl_xcvr_trim.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/ifr_radio.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/middleware/wireless/TARGET_FRAMEWORK_5_3_3/XCVR/MKW41Z4/ifr_radio.h
  targets/targets.json
  tools/test_configs/NanostackMACTester.json
  tools/test_configs/target_configs.json
Labels: ready for merge, release-version: 5.11.3

#9371 travis: set hypothesis to v3.88
  .travis.yml
Labels: needs: CI, release-version: 5.11.2

#9363 Remove unnecessary error prints in FileSystemStore
  features/storage/kvstore/filesystemstore/FileSystemStore.cpp
Labels: ready for merge, release-version: 5.11.3

#9357 NUCLEO_H743ZI : enable TICKLESS
  targets/targets.json
Labels: ready for merge, release-version: 5.11.3

#9356 ESP8266 - fixes disconnect to check the state from modem
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 5.11.3

#9352 mbed_boot_arm_std.c: remove redundant compiler check
  rtos/TARGET_CORTEX/TOOLCHAIN_ARM_STD/mbed_boot_arm_std.c
  rtos/TARGET_CORTEX/TOOLCHAIN_GCC_ARM/mbed_boot_gcc_arm.c
Labels: ready for merge, release-version: 5.12.0-rc1

#8443 Add Ice Tea SPI communication test.
  TEST_APPS/device/spi_com/main.cpp
  TEST_APPS/device/spi_com/mbed_app.json
  TEST_APPS/device/spi_com/spi_master.h
  TEST_APPS/device/spi_com/spi_slave.h
  TEST_APPS/device/spi_com/spi_test_common.h
  TEST_APPS/testcases/spi_com/README.md
  TEST_APPS/testcases/spi_com/__init__.py
  TEST_APPS/testcases/spi_com/com_test.png
  TEST_APPS/testcases/spi_com/spi_wire_connection.png
  TEST_APPS/testcases/spi_com/test_env.png
  TEST_APPS/testcases/spi_com/test_spi_com.py
Labels: ready for merge, release-version: feature branch

#8970 Add doxygen spellcheck job to Travis
  .travis.yml
  drivers/MbedCRC.h
  features/netsocket/L3IPInterface.h
  features/netsocket/TLSSocketWrapper.h
  features/netsocket/cellular/generic_modem_driver/PPPCellularInterface.h
  platform/ATCmdParser.h
  platform/mbed_critical.h
  platform/mbed_error.h
  tools/test/travis-ci/doxy-spellchecker/en.dat
  tools/test/travis-ci/doxy-spellchecker/en_affix.dat
  tools/test/travis-ci/doxy-spellchecker/en_phonet.dat
  tools/test/travis-ci/doxy-spellchecker/ignore.en.pws
  tools/test/travis-ci/doxy-spellchecker/spell.sh
Labels: ready for merge, release-version: 5.11.3

#9245 LoRAWAN: volatile bool -> atomic_flag
  UNITTESTS/features/lorawan/lorawanstack/unittest.cmake
  UNITTESTS/stubs/LoRaWANStack_stub.cpp
  UNITTESTS/stubs/mbed_critical_stub.c
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/LoRaWANStack.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9391 Add pyocd depencency to resolve Travis CI issue
  requirements.txt
Labels: ready for merge, release-version: 5.11.2

#9374 Add QSPIF as default storage for LPCXpresso546XX
  targets/targets.json
Labels: ready for merge, release-version: 5.11.3

#9365 Fix for asserion failing in BLE::callDispatcher with gcc debug profile.
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioBLE.cpp
Labels: ready for merge, release-version: 5.11.3

#9361 Removing dependency of TDBStore in SystemStorage file and moving some file location - TFM support.
  features/storage/kvstore/direct_access_devicekey/DirectAccessDevicekey.cpp
  features/storage/kvstore/direct_access_devicekey/DirectAccessDevicekey.h
  features/storage/kvstore/include/KVStore.h
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: ready for merge, release-version: 5.11.3

#9337 unittest: remove cellular driver L3IP stub
  features/netsocket/cellular/cellular_driver_l3ip.cpp
  features/netsocket/cellular/cellular_driver_l3ip.h
Labels: ready for merge, release-version: 5.11.3

#9288 Gemalto Crinterion UDP test adjustments
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_sendto_timeout.cpp
Labels: ready for merge, release-version: 5.11.3

#9261 Initial version for Quectel M26 GSM/GPRS Module.
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26.h
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularContext.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularContext.h
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularNetwork.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularNetwork.h
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularPower.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularPower.h
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularSIM.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularSIM.h
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.h
Labels: ready for merge, release-version: 5.11.3

#8497 Add get/settimeofday retargets
  platform/mbed_rtc_time.cpp
  platform/mbed_rtc_time.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9369 Add target C030-R412M
  features/cellular/framework/common/CellularTargets.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/onboard_modem_api.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/ublox_low_level_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.11.3, scope: new-target

#9280 Sleep manager implements all the API's in platform file
  platform/mbed_sleep_manager.c
Labels: ready for merge, release-version: 5.11.3

#9297 uARM targets now build in correct ARM_MICRO directory
  tools/build_api.py
Labels: ready for merge, release-version: 5.11.3

#9331 ESP8266: prevent WOULD BLOCK from TX if UDP
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 5.11.3

#9096 BLE: Enforce advertising data payload limits
  features/FEATURE_BLE/ble/gap/AdvertisingParameters.h
  features/FEATURE_BLE/ble/gap/Gap.h
  features/FEATURE_BLE/ble/generic/GenericGap.h
  features/FEATURE_BLE/ble/pal/PalGap.h
  features/FEATURE_BLE/source/gap/Gap.cpp
  features/FEATURE_BLE/source/generic/GenericGap.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioPalGap.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalGap.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9405 Travis: Fix doxy-spellcheck job
  platform/mbed_rtc_time.h
  tools/test/travis-ci/doxy-spellchecker/ignore.en.pws
Labels: ready for merge, release-version: 5.11.3

#8887 Adding debugger awarness with Keil MDK
  rtos/TARGET_CORTEX/mbed_rtos_rtx.c
  rtos/TARGET_CORTEX/rtx5/RTX/Source/rtx_lib.c
  tools/importer/cmsis_importer.json
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge, release-version: 5.12.0-rc1

#9257 FLASHIAP test: skip test if test region overlaps code
  TESTS/mbed_drivers/flashiap/main.cpp
Labels: ready for merge, release-version: 5.11.3

#9316 Add FLASH support to TARGET_MAX32620C and brd targets
  targets/TARGET_Maxim/TARGET_MAX32620C/device/TOOLCHAIN_IAR/MAX32620.icf
  targets/TARGET_Maxim/TARGET_MAX32620C/flash_api.c
  targets/TARGET_Maxim/TARGET_MAX32620C/objects.h
  targets/targets.json
Labels: ready for merge, release-version: 5.11.3

#9333 Minor Doxygen fixes for BufferedBlockDevice and iBeacon
  features/FEATURE_BLE/ble/services/iBeacon.h
  features/storage/blockdevice/BufferedBlockDevice.h
Labels: docathlon2019, ready for merge, release-version: 5.11.3

#9335 thread_mle_message_handler: fix build warning
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread/thread_mle_message_handler.c
Labels: ready for merge, release-version: 5.11.3

#9339 Fix Out-Of-Band (OOB) data generation for BLE OOB pairing
  features/FEATURE_BLE/source/generic/GenericSecurityManager.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xPalSecurityManager.cpp
Labels: ready for merge, release-version: 5.11.3

#9366 ESP8266: add an error check for data overflow from modem side
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
Labels: ready for merge, release-version: 5.11.3

#9376 TCP/UDP greentea tests refactoring and cleanup
  TESTS/netsocket/README.md
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_invalid.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_null.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_address_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_port.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_port_fail.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_unopened.cpp
  TESTS/netsocket/tcp/tcpsocket_bind_wrong_type.cpp
  TESTS/netsocket/tcp/tcpsocket_connect_invalid.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tcp/tcpsocket_echotest_burst.cpp
  TESTS/netsocket/tcp/tcpsocket_endpoint_close.cpp
  TESTS/netsocket/tcp/tcpsocket_open_close_repeat.cpp
  TESTS/netsocket/tcp/tcpsocket_open_destruct.cpp
  TESTS/netsocket/tcp/tcpsocket_open_limit.cpp
  TESTS/netsocket/tcp/tcpsocket_open_twice.cpp
  TESTS/netsocket/tcp/tcpsocket_recv_100k.cpp
  TESTS/netsocket/tcp/tcpsocket_setsockopt_keepalive_valid.cpp
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udpsocket_bind_address.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_invalid.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_null.cpp
  TESTS/netsocket/udp/udpsocket_bind_address_port.cpp
  TESTS/netsocket/udp/udpsocket_bind_port.cpp
  TESTS/netsocket/udp/udpsocket_bind_port_fail.cpp
  TESTS/netsocket/udp/udpsocket_bind_wrong_type.cpp
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_echotest_burst.cpp
  TESTS/netsocket/udp/udpsocket_open_close_repeat.cpp
  TESTS/netsocket/udp/udpsocket_open_destruct.cpp
  TESTS/netsocket/udp/udpsocket_open_limit.cpp
  TESTS/netsocket/udp/udpsocket_open_twice.cpp
  TESTS/netsocket/udp/udpsocket_recv_timeout.cpp
  TESTS/netsocket/udp/udpsocket_sendto_invalid.cpp
  TESTS/netsocket/udp/udpsocket_sendto_repeat.cpp
  TESTS/netsocket/udp/udpsocket_sendto_timeout.cpp
  tools/test_configs/6lowpanInterface_host.json
  tools/test_configs/6lowpanInterface_router.json
  tools/test_configs/ESP8266Interface.json
  tools/test_configs/EthernetInterface.json
  tools/test_configs/HeapBlockDeviceAndEthernetInterface.json
  tools/test_configs/HeapBlockDeviceAndWifiInterface.json
  tools/test_configs/ISM43362Interface.json
  tools/test_configs/SpwfSAInterface.json
  tools/test_configs/ThreadInterface_end_device.json
  tools/test_configs/ThreadInterface_router.json
  tools/test_configs/no_network.json
Labels: ready for merge, release-version: 5.11.3

#9380 UNO_91H: open hal lib source
  targets/TARGET_RDA/TARGET_UNO_91H/lib/LICENSE-permissive-binary-license-1.0.txt
  targets/TARGET_RDA/TARGET_UNO_91H/lib/README.md
  targets/TARGET_RDA/TARGET_UNO_91H/lib/TOOLCHAIN_ARM_STD/libhal.ar
  targets/TARGET_RDA/TARGET_UNO_91H/lib/TOOLCHAIN_GCC_ARM/libhal.a
  targets/TARGET_RDA/TARGET_UNO_91H/lib/TOOLCHAIN_IAR/libhal.a
  targets/TARGET_RDA/TARGET_UNO_91H/rda_ccfg_api.c
Labels: ready for merge, release-version: 5.11.3

#9403 Clarify addition to CONFIGURATION.md
  docs/design-documents/features/storage/Configuration/CONFIGURATION.md
Labels: ready for merge, release-version: 5.11.3

#9386 SD default configuration for ST boards is already defined in TARGET_STM
  components/storage/blockdevice/COMPONENT_SD/config/mbed_lib.json
Labels: ready for merge, release-version: 5.11.3

#9385 Fixes typos in SMSC9220 Ethernet driver
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/smsc9220_eth_drv.h
Labels: ready for merge, release-version: 5.11.3

#9407 DirectAccess DeviceKey: add support for default storage type
  features/storage/TESTS/kvstore/direct_access_devicekey_test/main.cpp
  features/storage/kvstore/direct_access_devicekey/DirectAccessDevicekey.cpp
Labels: ready for merge, release-version: 5.11.3

#9406 Extended mount to check all metadata-pairs
  features/storage/filesystem/littlefs/littlefs/lfs.c
Labels: ready for merge, release-version: 5.11.3

#9344 Fix bug in templated attach function
  features/unsupported/USBDevice/USBSerial/USBSerial.h
Labels: ready for merge

#9377 test: general_block_device fix to always erase prior the first program
  features/storage/TESTS/blockdevice/general_block_device/main.cpp
Labels: ready for merge, release-version: 5.11.3

#9418 tools: build_api: remove redundant initialization and fix spelling
  tools/build_api.py
Labels: ready for merge, release-version: 5.11.3

#8688 STM32F7: Add support of the new USB Device API
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd.h
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_usb.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_ll_usb.h
  targets/targets.json
  usb/device/targets/TARGET_STM/USBPhy_STM32.cpp
Labels: ready for merge, release-version: feature branch

#9373 Tests: USB: Fix endpoint halt test
  TESTS/host_tests/pyusb_basic.py
  TESTS/usb_device/basic/USBEndpointTester.cpp
  TESTS/usb_device/basic/USBEndpointTester.h
Labels: release-version: feature branch

#9428 STM32H743ZI: iar removal as not supported in v7.x
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.11.3

#9258 FLASH test: skip test if test region overlaps code
  TESTS/mbed_hal/flash/functional_tests/main.cpp
Labels: ready for merge, release-version: 5.11.3

#9401 tools: adds and implements a --custom-targets command line switch
  tools/device_management.py
  tools/options.py
  tools/project.py
Labels: ready for merge, release-version: 5.12.0-rc1

#9248 InternetSocket: use atomics, not volatile
  UNITTESTS/features/netsocket/DTLSSocket/unittest.cmake
  UNITTESTS/features/netsocket/DTLSSocketWrapper/unittest.cmake
  UNITTESTS/features/netsocket/InternetSocket/test_InternetSocket.cpp
  UNITTESTS/features/netsocket/InternetSocket/unittest.cmake
  UNITTESTS/features/netsocket/TCPServer/unittest.cmake
  UNITTESTS/features/netsocket/TCPSocket/unittest.cmake
  UNITTESTS/features/netsocket/TLSSocket/unittest.cmake
  UNITTESTS/features/netsocket/TLSSocketWrapper/unittest.cmake
  UNITTESTS/features/netsocket/UDPSocket/unittest.cmake
  features/netsocket/InternetSocket.cpp
  features/netsocket/InternetSocket.h
  features/netsocket/TCPServer.cpp
  features/netsocket/TCPSocket.cpp
  features/netsocket/UDPSocket.cpp
Labels: ready for merge, release-version: 5.12.0-rc1

#9422 PB_1 is not connected to D4 in R412M above
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/PinNames.h
Labels: ready for merge, release-version: 5.11.3

#9398 Revert "Warn with ARMC6 and not v8m"
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.12.0-rc1

#9247 Add atomic loads and stores and barriers
  UNITTESTS/stubs/mbed_critical_stub.c
  platform/mbed_critical.c
  platform/mbed_critical.h
  platform/mbed_toolchain.h
Labels: ready for merge, release-version: 5.12.0-rc1

#9427 BLE: fix possible truncation
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/btle/btle.cpp
Labels: ready for merge, release-version: 5.11.3

#9399 BLE: fix missing null checks on Gap event handler
  features/FEATURE_BLE/source/generic/GenericGap.cpp
  platform/mbed_error.h
Labels: ready for merge, release-version: 5.11.3

#9415 Allow NSAPI_ERROR_UNSUPPORTED from Socket::setsockopt()
  TESTS/netsocket/tcp/tcpsocket_setsockopt_keepalive_valid.cpp
Labels: ready for merge, release-version: 5.11.3

#9389 Travis CI: Bind remaining python modules
  .travis.yml
  requirements.txt
  tools/test/toolchains/api_test.py
Labels: ready for merge, release-version: 5.11.3

#9286 travis: Add include_check job
  .travis.yml
Labels: ready for merge, release-version: 5.11.3

#9440 Put LittleFS emulated BD module under .mbedignore
  features/storage/filesystem/littlefs/littlefs/emubd/.mbedignore
Labels: ready for merge, release-version: 5.11.3

#9328 Doxygen fixes for IP networking area
  doxyfile_options
  features/cellular/README.md
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/API/CellularInformation.h
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/API/CellularSMS.h
  features/cellular/framework/AT/ATHandler.h
  features/netsocket/CellularBase.h
  features/netsocket/DNS.h
  features/netsocket/DTLSSocket.h
  features/netsocket/DTLSSocketWrapper.h
  features/netsocket/EthInterface.h
  features/netsocket/MeshInterface.h
  features/netsocket/NetworkInterface.h
  features/netsocket/NetworkStack.h
  features/netsocket/Socket.h
  features/netsocket/SocketAddress.h
  features/netsocket/TCPServer.h
  features/netsocket/TCPSocket.h
  features/netsocket/TLSSocket.h
  features/netsocket/TLSSocketWrapper.h
  features/netsocket/WiFiInterface.h
  features/netsocket/nsapi_dns.h
  tools/test/travis-ci/doxy-spellchecker/ignore.en.pws
Labels: docathlon2019, ready for merge

#8665 STM32L4: Add support of the new USB Device API
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pcd.c
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pcd.h
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_usb.c
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_ll_usb.h
  targets/targets.json
  usb/device/targets/TARGET_STM/USBPhy_STM32.cpp
Labels: ready for merge, release-version: feature branch

#9439 Examples: enabled some examples build for FVP_MPS2_M3 target
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.11.3

#9397 Fixing folder path for KVStore FILESYSTEM configuration.
  features/storage/TESTS/kvstore/static_tests/main.cpp
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/kvstore/conf/kv_config.h
  features/storage/kvstore/filesystemstore/FileSystemStore.cpp
Labels: ready for merge, release-version: 5.11.3

#9360 LPC546XX, LPC54114: Add README and LICENSE files for the power libraries
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/TOOLCHAIN_ARM_STD/LICENSE
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/TOOLCHAIN_ARM_STD/libpower.README
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/TOOLCHAIN_GCC_ARM/LICENSE
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/TOOLCHAIN_GCC_ARM/libpower.README
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/TOOLCHAIN_IAR/LICENSE
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/TOOLCHAIN_IAR/libpower.README
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/device/TOOLCHAIN_ARM_STD/LICENSE
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/device/TOOLCHAIN_ARM_STD/libpower.README
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/device/TOOLCHAIN_GCC_ARM/LICENSE
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/device/TOOLCHAIN_GCC_ARM/libpower.README
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/device/TOOLCHAIN_IAR/LICENSE
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/device/TOOLCHAIN_IAR/libpower.README
Labels: ready for merge, release-version: 5.11.3

#9411 STM32L496xG: increase IAR heap size
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/device/TOOLCHAIN_IAR/stm32l496xx.icf
Labels: ready for merge, release-version: 5.11.3

#9448 Fix links to https://os.mbed.com documentation
  .github/issue_template.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  UNITTESTS/README.md
Labels: ready for merge, release-version: 5.11.3

#9433 Set DSP and floating point flags for ASM files
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.11.3

#9392 Documentation of TLSSocket behavior on AUTH_FAILURE
  UNITTESTS/features/netsocket/DTLSSocketWrapper/test_DTLSSocketWrapper.cpp
  UNITTESTS/features/netsocket/TLSSocketWrapper/test_TLSSocketWrapper.cpp
  features/netsocket/Socket.h
  features/netsocket/TLSSocket.h
  features/netsocket/TLSSocketWrapper.cpp
  features/netsocket/TLSSocketWrapper.h
Labels: ready for merge, release-version: 5.11.3

#9404 DSP_PRESENT flag is needed for Armv8m devices having DSP enabled
  tools/toolchains/__init__.py
Labels: ready for merge, release-version: 5.11.3

#9302 Add TRNG checkup in devicekey
  features/device_key/source/DeviceKey.cpp
Labels: ready for merge, release-version: 5.11.3

#9368 PSOC6: Fixes for serial hal driver, asynchronous mode.
  targets/TARGET_Cypress/TARGET_PSOC6/serial_api.c
Labels: ready for merge, release-version: 5.11.3

#9421 ESP8266: implements possibility to decide between non-blocking/blocking connect.
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
Labels: ready for merge, release-version: 5.11.3

#9437 FPU_USED to be set based on HW FPU support + Squash commits
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_ARM/TARGET_M33/irq_armv8mml.S
  rtos/TARGET_CORTEX/rtx5/RTX/Source/TOOLCHAIN_GCC/TARGET_M33/irq_armv8mml.S
  tools/importer/cmsis_importer.json
Labels: ready for merge, release-version: 5.11.3

#9453 mbed-host-tests minimum requirement set
  requirements.txt
Labels: ready for merge, release-version: 5.11.3

#9291 NRF5x: QSPI SFDP read, min read/write implementation
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/drivers_nrf/hal/nrf_qspi.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_14_2/drivers_nrf/qspi/nrf_drv_qspi.h
  targets/TARGET_NORDIC/TARGET_NRF5x/qspi_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.11.3

#9488 Fix licenses in travis test and realtek lib
  targets/TARGET_Realtek/TARGET_AMEBA/sdk/soc/realtek/common/bsp/basic_types.h
  tools/test/travis-ci/doxy-spellchecker/en_phonet.dat
Labels: ready for merge, release-version: 5.11.3

#9223 Update PSA binaries importer for FUTURE_SEQUANA_PSA
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_FUTURE_SEQUANA_PSA/prebuilt/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_FUTURE_SEQUANA_PSA/prebuilt/export_binaries.py
Labels: needs: CI, release-version: 5.11.3

#9492 Travis CI: Fix for license check job
  .travis.yml
Labels: ready for merge, release-version: 5.11.3

#9500 TCPSocket.cpp setting socket should terminate with semicolon
  features/netsocket/TCPSocket.cpp
Labels: ready for merge, release-version: 5.11.4

#9498 Remove outdated text and fix spelling in README.md
  features/frameworks/unity/README.md
Labels: ready for merge, release-version: 5.11.4

#9466 Improve PSoC 6 post-build hooks, whitelist makefile export
  targets/targets.json
  tools/export/makefile/__init__.py
  tools/targets/PSOC6.py
  tools/targets/__init__.py
Labels: ready for merge, release-version: 5.11.4

#9474 Fix newlines at end of files
  features/netsocket/DNS.h
  features/netsocket/DTLSSocketWrapper.h
  features/netsocket/L3IPInterface.h
  features/nfc/source/nfc/NFCRemoteInitiator.cpp
  features/storage/filesystem/littlefs/littlefs/lfs_util.c
Labels: ready for merge, release-version: 5.11.4

#9482 ARCH_PRO: add missing SPI pin definitions
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_ARCH_PRO/PinNames.h
Labels: ready for merge, release-version: 5.11.4

#9497 Remove yotta from README.md
  features/frameworks/greentea-client/README.md
Labels: ready for merge, release-version: 5.11.4

#9499 Remove unused yotta module metadata
  features/FEATURE_BLE/module.json
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_MCU_NRF51822/module.json
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_MCU_NRF51822/sdk/module.json
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF51/module.json
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/module.json
  features/frameworks/mbed-client-randlib/module.json
  features/frameworks/mbed-coap/module.json
  features/frameworks/mbed-trace/module.json
  features/frameworks/nanostack-libservice/module.json
  features/nanostack/mbed-mesh-api/module.json
  features/nanostack/sal-stack-nanostack-eventloop/module.json
Labels: ready for merge, release-version: 5.11.4

#9509 PSOC6.py: generate hex files with 16 bytes per row
  tools/targets/PSOC6.py
Labels: ready for merge, release-version: 5.11.4

#9430 LPC546XX, MIMXRT1050: Update to fix ARMC6 build failures
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/drivers/fsl_common.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/xip/evkbimxrt1050_flexspi_nor_config.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/xip/evkbimxrt1050_sdram_ini_dcd.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/cmsis_nvic.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_common.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_flexspi_nor_boot.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_flexspi_nor_boot.h
Labels: needs: CI, release-version: 5.11.4
