Repository ARMmbed/mbed-os, pull requests merged in 2019-12, with the labels that each got.

#11980 DISCO_L4R9I: update clock configuration for all clock sources
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/system_clock.c
  targets/targets.json
Labels: release-version: 6.0.0-alpha

#11927 Speed up unittests by not limitting Make to spawn more processes
  UNITTESTS/unit_test/test.py
Labels: release-version: 6.0.0-alpha

#11962 Bug in mbed_alloc_wrappers.cpp
  platform/source/mbed_alloc_wrappers.cpp
Labels: release-version: 6.0.0-alpha

#11952 Fix for Dragonfly nano and registration for LTE-M plans
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP.cpp
Labels: release-version: 6.0.0-alpha

#11995 MCU_NRF52840 target configuration fixes
  targets/targets.json
Labels: release-version: 6.0.0-alpha

#11991 TESTS: Fix integration tests
  TESTS/integration/COMMON/common_defines_fs_test.h
  TESTS/integration/COMMON/download_test.cpp
  TESTS/integration/COMMON/download_test.h
  TESTS/integration/COMMON/file_test.cpp
  TESTS/integration/COMMON/file_test.h
Labels: release-version: 5.15.0-rc2

#11880 Remove deprecated Callback methods
  TESTS/mbed_functional/callback/main.cpp
  TESTS/mbed_functional/callback_big/main.cpp
  TESTS/mbed_functional/callback_small/main.cpp
  platform/Callback.h
Labels: BREAKING-CHANGE, release-version: 6.0.0-alpha

#11594 M2351: Pre-build secure image/lib to favor pelion application
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NPSA_NS/TARGET_NU_PREBUILD_SECURE/NuMaker-mbed-TZ-secure-example.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NPSA_NS/TARGET_NU_PREBUILD_SECURE/README.md
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NPSA_NS/TARGET_NU_PREBUILD_SECURE/cmse_lib.o
  targets/targets.json
Labels: needs: CI, release-version: 6.0.0-alpha

#12006 FIX: fix a bug introduced by static pinmap
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/serial_api.c
Labels: needs: CI, release-version: 5.15.0-rc2

#11957 MbedCRC and CRC HAL revisions (6.0 redo)
  TESTS/mbed_drivers/crc/main.cpp
  TESTS/mbed_hal/crc/main.cpp
  UNITTESTS/empty_baseline/unittest.cmake
  UNITTESTS/target_h/cmsis.h
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.h
  drivers/MbedCRC.h
  drivers/internal/TableCRC.h
  drivers/mbed_lib.json
  drivers/source/MbedCRC.cpp
  drivers/source/TableCRC.cpp
  features/storage/filesystem/littlefs/LittleFileSystem.cpp
  features/storage/filesystem/littlefs/TESTS/filesystem/seek/main.cpp
  features/storage/filesystem/littlefs/littlefs/lfs_util.h
  features/storage/kvstore/direct_access_devicekey/DirectAccessDevicekey.cpp
  features/storage/kvstore/tdbstore/TDBStore.cpp
  hal/crc_api.h
  platform/source/mbed_error.c
  targets/TARGET_Cypress/TARGET_PSOC6/cy_crc_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/objects.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/mbed_crc_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/objects.h
  targets/TARGET_STM/TARGET_STM32F0/common_objects.h
  targets/TARGET_STM/TARGET_STM32F3/common_objects.h
  targets/TARGET_STM/TARGET_STM32F7/common_objects.h
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/TARGET_STM/TARGET_STM32L0/common_objects.h
  targets/TARGET_STM/TARGET_STM32L4/common_objects.h
  targets/TARGET_STM/TARGET_STM32WB/common_objects.h
  targets/TARGET_STM/mbed_crc_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/common/objects.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/crc_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/crc_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/objects.h
Labels: needs: CI, release-version: 6.0.0-alpha

#12008 Cellular: Fix ATHandler string handling
  features/cellular/framework/AT/ATHandler.cpp
Labels: release-version: 6.0.0-alpha

#11920 Simplify pull request template headers and instructions
  .github/pull_request_template.md
Labels: release-version: 6.0.0-alpha

#12012 USB device HID test: remove duplicated define
  TESTS/usb_device/hid/main.cpp
Labels: release-version: 6.0.0-alpha

#12011 STMOD_CELLULAR: improve debug print
  components/cellular/COMPONENT_STMOD_CELLULAR/README.md
  components/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.cpp
Labels: release-version: 6.0.0-alpha

#11970 Avoid crashes during fault handler
  platform/mbed_interface.h
  platform/source/TARGET_CORTEX_M/mbed_fault_handler.c
  platform/source/mbed_error.c
Labels: release-version: 6.0.0-alpha

#11975 PPPinterface: remove faulty address getter check for invalid pointer
  features/netsocket/PPPInterface.cpp
Labels: release-version: 6.0.0-alpha

#11891 minimal-printf: Enable using a target configuration parameter
  platform/source/minimal-printf/README.md
  targets/targets.json
  tools/test/toolchains/test_toolchains.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
  tools/toolchains/mbed_toolchain.py
Labels: release-version: 6.0.0-alpha

#11878 Improve API documentation and test coverage
  UNITTESTS/features/netsocket/EthernetInterface/test_EthernetInterface.cpp
  UNITTESTS/features/netsocket/NetworkInterface/test_NetworkInterface.cpp
  UNITTESTS/features/netsocket/PPPInterface/test_PPPInterface.cpp
  UNITTESTS/features/netsocket/PPPInterface/unittest.cmake
  UNITTESTS/features/netsocket/TCPSocket/test_TCPSocket.cpp
  UNITTESTS/features/netsocket/TLSSocketWrapper/test_TLSSocketWrapper.cpp
  UNITTESTS/features/netsocket/WiFiAccessPoint/test_WiFiAccessPoint.cpp
  UNITTESTS/stubs/NetworkStack_stub.h
  UNITTESTS/stubs/OnboardNetworkStack_mock.h
  features/netsocket/EMACInterface.h
  features/netsocket/InternetDatagramSocket.h
  features/netsocket/NetworkInterface.h
  features/netsocket/NetworkStack.h
  features/netsocket/PPPInterface.cpp
  features/netsocket/PPPInterface.h
  features/netsocket/SocketAddress.h
  features/netsocket/TCPSocket.h
  features/netsocket/TLSSocketWrapper.h
  features/netsocket/nsapi_dns.h
Labels: release-version: 6.0.0-alpha

#11986 Storage related test improvements and small fixes
  UNITTESTS/moduletests/storage/blockdevice/BufferedBlockDevice/moduletest.cpp
  UNITTESTS/moduletests/storage/blockdevice/BufferedBlockDevice/unittest.cmake
  UNITTESTS/moduletests/storage/blockdevice/SlicingBlockDevice/moduletest.cpp
  features/storage/TESTS/blockdevice/general_block_device/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_2/main.cpp
  features/storage/TESTS/kvstore/tdbstore_whitebox/main.cpp
  features/storage/blockdevice/BufferedBlockDevice.cpp
  features/storage/blockdevice/FlashSimBlockDevice.cpp
  features/storage/blockdevice/HeapBlockDevice.cpp
  features/storage/blockdevice/SlicingBlockDevice.cpp
Labels: release-version: 6.0.0-alpha

#12025 Platform: Delete an unused astyle output file
  platform/astyle-branch.out
Labels: release-version: 6.0.0-alpha

#12024 ONME-4366 - Fix UBLOX_EVK_ODIN_W2 fails in emac tests due to heap mem…
  TESTS/network/emac/emac_util.cpp
Labels: release-version: 6.0.0-alpha

#11976 LWIP system mailbox overflow fix
  features/lwipstack/lwip-sys/arch/lwip_sys_arch.c
Labels: release-version: 6.0.0-alpha

#12029 STM32F0: create STM32F091xC target
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/TARGET_NUCLEO_F091RC/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/TARGET_NUCLEO_F091RC/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/TARGET_NUCLEO_F091RC/PinNames.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/TOOLCHAIN_ARM_MICRO/startup_stm32f091xc.S
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/TOOLCHAIN_ARM_MICRO/stm32f091rc.sct
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/TOOLCHAIN_ARM_STD/startup_stm32f091xc.S
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/TOOLCHAIN_ARM_STD/stm32f091rc.sct
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/TOOLCHAIN_GCC_ARM/STM32F091XC.ld
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/TOOLCHAIN_GCC_ARM/startup_stm32f091xc.S
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/TOOLCHAIN_IAR/startup_stm32f091xc.S
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/TOOLCHAIN_IAR/stm32f091xc.icf
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/cmsis_nvic.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/stm32f091xc.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/stm32f0xx.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/system_stm32f0xx.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/device/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/objects.h
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
Labels: release-version: 6.0.0-alpha

#12015 STM EMAC: compilation issue with ARMC5
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
Labels: release-version: 6.0.0-alpha

#11988 Small fixes for SecureStore
  features/storage/kvstore/securestore/SecureStore.cpp
  features/storage/kvstore/securestore/SecureStore.h
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: needs: CI, release-version: 6.0.0-alpha

#12017 NVStore: already deprecated implementation removed
  TESTS/configs/baremetal.json
  TESTS/host_tests/trng_reset.py
  TESTS/integration/COMMON/sample.txt
  UNITTESTS/empty_baseline/unittest.cmake
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/mbed_lib.json
  docs/design-documents/features/storage/BlockDevices/get_type_method.md
  features/device_key/README.md
  features/storage/kvstore/tdbstore/TDBStore.cpp
  features/storage/nvstore/README.md
  features/storage/nvstore/TESTS/nvstore/functionality/main.cpp
  features/storage/nvstore/mbed_lib.json
  features/storage/nvstore/source/nvstore.cpp
  features/storage/nvstore/source/nvstore.h
  features/storage/system_storage/SystemStorage.cpp
  features/storage/system_storage/SystemStorage.h
  tools/test/examples/examples.json
Labels: release-version: 6.0.0-alpha

#12018 STM32_EMAC cleanup
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_OLIMEX_STM32E407_F407ZG/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_OLIMEX_STM32E407_F407ZG/stm32f4_eth_init.c
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
Labels: release-version: 6.0.0-alpha

#12038 Cypress: Remove qspi_frequency() call.
  targets/TARGET_Cypress/TARGET_PSOC6/cy_qspi_api.c
Labels: devices: cypress, release-version: 6.0.0-alpha

#12041 Add QSPI and relevant test support for target EP_AGORA
  TESTS/mbed_hal/qspi/flash_configs/NORDIC/EP_AGORA/flash_config.h
  TESTS/mbed_hal/qspi/flash_configs/W25Q32JV_config.h
  TESTS/mbed_hal/qspi/flash_configs/flash_configs.h
  targets/targets.json
Labels: release-version: 6.0.0-alpha

#12034 SysTimer: Suppress implicit virtual warning
  platform/source/SysTimer.h
Labels: release-version: 6.0.0-alpha

#12030 Updates the Cypress WiFi Host Driver to 1.7.0
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/generated_mac_address.txt
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/inc/whd_version.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/src/include/whd_events_int.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/src/whd_ap.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_WHD/resources/firmware/TARGET_43438/resources.h
Labels: Priority-High, devices: cypress, release-version: 5.15.0-rc2

#12039 Fix build errors for bare metal greentea tests on NRF52840_DK
  TESTS/configs/baremetal.json
Labels: release-version: 5.15.0-rc2

#12047 NANO130: Fix OOM with packing algorithm at IAR linking
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_IAR/NANO130.icf
Labels: release-version: 5.15.0-rc2

#12051 Unittest configuration mechanism improved
  UNITTESTS/CMakeLists.txt
  UNITTESTS/drivers/PwmOut/unittest.cmake
  UNITTESTS/drivers/Watchdog/unittest.cmake
  UNITTESTS/empty_baseline/unittest.cmake
  UNITTESTS/events/equeue/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/athandler/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellularcontext/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellularstatemachine/unittest.cmake
  UNITTESTS/features/lorawan/loramac/unittest.cmake
  UNITTESTS/features/lorawan/loramacchannelplan/unittest.cmake
  UNITTESTS/features/lorawan/loramaccommand/unittest.cmake
  UNITTESTS/features/lorawan/loramaccrypto/unittest.cmake
  UNITTESTS/features/lorawan/loraphy/unittest.cmake
  UNITTESTS/features/lorawan/loraphyas923/unittest.cmake
  UNITTESTS/features/lorawan/loraphyau915/unittest.cmake
  UNITTESTS/features/lorawan/loraphycn470/unittest.cmake
  UNITTESTS/features/lorawan/loraphycn779/unittest.cmake
  UNITTESTS/features/lorawan/loraphyeu433/unittest.cmake
  UNITTESTS/features/lorawan/loraphyeu868/unittest.cmake
  UNITTESTS/features/lorawan/loraphyin865/unittest.cmake
  UNITTESTS/features/lorawan/loraphykr920/unittest.cmake
  UNITTESTS/features/lorawan/loraphyus915/Test_LoRaPHYUS915.cpp
  UNITTESTS/features/lorawan/loraphyus915/unittest.cmake
  UNITTESTS/features/lorawan/lorawaninterface/unittest.cmake
  UNITTESTS/features/lorawan/lorawanstack/unittest.cmake
  UNITTESTS/features/lorawan/lorawantimer/Test_LoRaWANTimer.cpp
  UNITTESTS/features/lorawan/lorawantimer/unittest.cmake
  UNITTESTS/features/netsocket/cellular/CellularNonIPSocket/unittest.cmake
  UNITTESTS/features/netsocket/nsapi_dns/unittest.cmake
  UNITTESTS/features/storage/blockdevice/HeapBlockDevice/unittest.cmake
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
Labels: release-version: 6.0.0-alpha

#12013 Add UDP ECHOTEST with connect/send/recv calls
  TESTS/netsocket/README.md
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udp_tests.h
  TESTS/netsocket/udp/udpsocket_echotest.cpp
Labels: release-version: 6.0.0-alpha

#12044 increamed qspi size for cypress integration fs tests
  TESTS/integration/COMMON/target_extended.json
Labels: devices: cypress, release-version: 6.0.0-alpha

#12043 Modify itm_api.c for EFM32 targets
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG/TARGET_EFM32GG_STK3700/device_peripherals.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG11/TARGET_EFM32GG11_STK3701/device_peripherals.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32LG/TARGET_EFM32LG_STK3600/device_peripherals.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32PG/TARGET_EFM32PG_STK3401/device_peripherals.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32PG12/TARGET_EFM32PG12_STK3402/device_peripherals.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32WG/TARGET_EFM32WG_STK3800/device_peripherals.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/itm_api.c
  targets/targets.json
Labels: release-version: 6.0.0-alpha

#12033 static pin-map: patch for SerialBase class
  drivers/SerialBase.h
  drivers/source/SerialBase.cpp
Labels: release-version: 5.15.0-rc2

#12058 Add static pin-map support: SDBlockDevice, kvstore, system storage (reduce ROM used by Mbed Cloud Client example)
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.h
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/system_storage/SystemStorage.cpp
Labels: release-version: 5.15.0-rc2

#12073 Unittests fixed
  UNITTESTS/features/cellular/framework/AT/at_cellularinformation/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/unittest.cmake
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  UNITTESTS/stubs/CellularDevice_stub.cpp
  UNITTESTS/target_h/myCellularDevice.h
Labels: release-version: 6.0.0-alpha

#12059 Config: fix bootloader config errors - propagate errors
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_IAR/stm32f746xg.icf
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/device/TOOLCHAIN_IAR/stm32f756xg.icf
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_IAR/stm32f767xi.icf
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/TOOLCHAIN_IAR/stm32f769xi.icf
  targets/targets.json
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 5.15.0-rc2

#12069 STM32: astyle update
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F7/aes_alt.c
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F7/aes_alt.h
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/TARGET_DISCO_H747I/stm32h7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/TARGET_NUCLEO_H743ZI/stm32h7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/TARGET_NUCLEO_H743ZI2/stm32h7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/lan8742/lan8742.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/lan8742/lan8742.h
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
  targets/TARGET_STM/TARGET_STM32F2/serial_device.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/TARGET_ARCH_MAX/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/TARGET_ARCH_MAX/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/TARGET_ARCH_MAX/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/objects.h
  targets/TARGET_STM/TARGET_STM32F4/pwmout_device.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/system_stm32h7xx.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/system_clock.c
  targets/TARGET_STM/reset_reason.c
  targets/TARGET_STM/watchdog_api.c
Labels: release-version: 6.0.0-alpha

#12052 fpga tests: clear uart fix
  TESTS/mbed_hal_fpga_ci_test_shield/uart/main.cpp
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_uart.c
Labels: devices: cypress, needs: CI, release-version: 6.0.0-alpha

#12057 NUC472/M487: Limit EMAC receive frame length as 1518
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/TARGET_M480/m480_eth.c
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/TARGET_M480/m480_eth.h
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/TARGET_NUC472/nuc472_eth.c
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/TARGET_NUC472/nuc472_eth.h
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/numaker_emac.cpp
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/numaker_emac_config.h
Labels: release-version: 6.0.0-alpha

#12061 NANO130: Support dynamic heap configuration on IAR
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_IAR/NANO130.icf
Labels: release-version: 6.0.0-alpha

#12080 Unittest cleanup made
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularinformation/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/athandler/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellulardevice/unittest.cmake
  UNITTESTS/features/netsocket/cellular/CellularNonIPSocket/unittest.cmake
  UNITTESTS/stubs/UARTSerial_stub.cpp
Labels: release-version: 6.0.0-alpha

#12022 Make ESP8266 compatible with bare metal profile
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
Labels: release-version: 6.0.0-alpha

#12078 Cellular: Add PPP/IP config flags in CellularInterface.json
  tools/test_configs/CellularInterface.json
Labels: release-version: 6.0.0-alpha

#12071 Minimal Console: Use static pin map
  platform/source/mbed_retarget.cpp
Labels: release-version: 6.0.0-alpha

#12079 Coverity fixes
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.h
  features/frameworks/mbed-client-cli/source/ns_cmdline.c
Labels: ready for merge, release-version: 6.0.0-alpha

#11998 Linker script changes for the TARGET - CY8CPROTO_064_SB
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/device/COMPONENT_CM4/TOOLCHAIN_ARM/cyb06xx7_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/cyb06xx7_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/partition/flash_layout.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/partition/region_defs.h
Labels: needs: CI, release-version: feature branch

#11817 ESP8266 "busy s..." fix (ONME-4352)
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  platform/ATCmdParser.h
  platform/source/ATCmdParser.cpp
Labels: ready for merge, release-version: 6.0.0-alpha

#11961 UnbufferedSerial: Introduce the class to replace RawSerial
  TESTS/host_tests/serial_comms.py
  TESTS/mbed_drivers/unbuffered_serial/main.cpp
  drivers/RawSerial.h
  drivers/SerialBase.h
  drivers/UnbufferedSerial.h
  drivers/source/UnbufferedSerial.cpp
  mbed.h
  platform/mbed_lib.json
Labels: ready for merge, release-version: 6.0.0-alpha

#11866 Update pycryptodome version
  requirements.txt
Labels: ready for merge, release-version: 6.0.0-alpha

#12085 PSA setup template changes.
  tools/psa/templates/psa_setup.c.tpl
Labels: release-version: 6.0.0-alpha

#12112 Notify on configuration exception rather than breaking build
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 5.15.0-rc3

#12117 Storage features: fix static pin-map for ARMC5
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/system_storage/SystemStorage.cpp
Labels: ready for merge, release-version: 5.15.0-rc3

#12119 Release candidate for mbed-os-5.15.0-rc3
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/system_storage/SystemStorage.cpp
  tools/toolchains/mbed_toolchain.py
Labels: needs: CI

#12108 Wi-sun network event handler update
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: release-version: 6.0.0-alpha

#12100 Rollback Post Binary Hook - NU_PFM_M2351_NPSA_NS
  tools/targets/__init__.py
Labels: release-version: feature branch

#12019 Cypress: rework lptimer hal
  targets/TARGET_Cypress/TARGET_PSOC6/cy_lp_ticker_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_lptimer.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_lptimer.c
Labels: devices: cypress, ready for merge, release-version: 6.0.0-alpha

#12032 Add MBED_FALLTHROUGH attribute
  TESTS/mbedmicro-mbed/attributes/attributes.c
  TESTS/mbedmicro-mbed/attributes/main.cpp
  platform/mbed_toolchain.h
Labels: ready for merge, release-version: 6.0.0-alpha

#12048 SharedPtr: add nullptr constructor
  TESTS/mbed_platform/SharedPtr/main.cpp
  platform/SharedPtr.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-alpha

#12064 Valgrind support added for unittests
  UNITTESTS/CMakeLists.txt
  UNITTESTS/mbed_unittest.py
  UNITTESTS/moduletests/storage/blockdevice/SlicingBlockDevice/moduletest.cpp
  UNITTESTS/unit_test/get_tools.py
  UNITTESTS/unit_test/options.py
  UNITTESTS/unit_test/test.py
Labels: ready for merge, release-version: 6.0.0-alpha

#12067 STM32 GPIO IRQ : add a critical section in gpio_irq_init
  targets/TARGET_STM/gpio_irq_api.c
Labels: ready for merge, release-version: 6.0.0-alpha

#12088 Cellular: Fix AT command for COPS manual network selection
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: ready for merge

#12097 cypress target: fix iar warnings
  targets/TARGET_Cypress/TARGET_PSOC6/cy_port_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/cy_serial_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/cy_spi_api.c
Labels: devices: cypress, ready for merge

#12098 Wrong order of code fixed
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 6.0.0-alpha

#12099 Implemented recommended fix from https://github.com/STMicroelectronic…
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_uart.c
Labels: ready for merge

#12101 Bare metal: Retrieve error context after crash
  TESTS/mbed_platform/crash_reporting/main.cpp
  platform/source/mbed_sdk_boot.c
Labels: ready for merge

#12110 Moved CP Max recv len into mbed_lib.json
  features/cellular/framework/AT/AT_ControlPlane_netif.h
  features/cellular/mbed_lib.json
  features/netsocket/cellular/ControlPlane_netif.h
Labels: ready for merge

#12111 Microlib: Disable feof function usage in general filesystem test
  features/storage/TESTS/filesystem/general_filesystem/main.cpp
Labels: ready for merge

#12114 Cellular: Fix to not use all zero address for DNS
  features/cellular/framework/AT/AT_CellularContext.cpp
Labels: ready for merge

#12118 Fixed Serial ambiguity for enable_input and enable_output
  drivers/Serial.h
Labels: ready for merge

#12120 ONME-4433 SocketAddress::operator== should also check port
  UNITTESTS/MODULETESTS/features/netsocket/IfaceDnsSocket/test_IfaceDnsSocket.cpp
  features/netsocket/SocketAddress.cpp
Labels: ready for merge

#12086 TARGET_STM: fix flash api 64bit address alignment on L4 and WB
  targets/TARGET_STM/TARGET_STM32L4/flash_api.c
  targets/TARGET_STM/TARGET_STM32WB/flash_api.c
Labels: ready for merge

#12045 Netsocket test adjusted to Wisun
  TESTS/configs/mbedtls_wisun_config.h
  TESTS/configs/wisun_S2LP.json
  TESTS/netsocket/dns/dns_tests.h
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tls/tls_tests.h
  TESTS/netsocket/udp/udp_tests.h
Labels: release-version: 6.0.0-alpha

#11964 Python script automate tf-m build build process
  .gitignore
  features/FEATURE_PSA/TARGET_TFM/VERSION.txt
  features/FEATURE_PSA/supporting_psa_in_mbed-os.md
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/tfm_s.axf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/tfm_s.hex
  targets/targets.json
  tools/export/cces/__init__.py
  tools/export/cdt/__init__.py
  tools/export/cmsis/__init__.py
  tools/export/exporters.py
  tools/export/iar/__init__.py
  tools/export/makefile/__init__.py
  tools/export/sw4stm32/__init__.py
  tools/export/uvision/__init__.py
  tools/psa/build_tfm.py
  tools/targets/__init__.py
  tools/tests.py
Labels: needs: work, release-version: feature branch

#11997 Remove deprecated FunctionPointer class
  TESTS/mbed_functional/functionpointer/main.cpp
  drivers/source/Ticker.cpp
  mbed.h
  platform/FunctionPointer.h
Labels: ready for merge, release-version: 6.0.0-alpha-1

#12121 Serial: Deprecate the class and promote UnbufferedSerial instead
  drivers/Serial.h
Labels: ready for merge

#12131 Cellular: Fix Gemalto/Cinterion driver
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
Labels: ready for merge

#12132 LWIP: Remove unused MBOX configs
  features/lwipstack/lwipopts.h
  features/lwipstack/mbed_lib.json
Labels: ready for merge

#12113 Fix for issue #12104 (STM32 can_init_freq() ignores frequency)
  targets/TARGET_STM/can_api.c
Labels: release-version: 6.0.0-alpha-1

#12133 Cellular: Suppress long AT traces
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/mbed_lib.json
Labels: release-version: 6.0.0-alpha-1

#12070 Add pytest test case to validate PSA target mandatory attributes
  features/FEATURE_PSA/supporting_psa_in_mbed-os.md
  targets/targets.json
  tools/build_api.py
  tools/psa/build_tfm.py
  tools/targets/__init__.py
  tools/test/psa/psa_test.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
Labels: release-version: feature branch

#12083 Cellular: Add check for network congestion in BC95 driver
  TESTS/netsocket/udp/udpsocket_echotest_burst.cpp
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.h
Labels: release-version: 6.0.0-alpha-1

#12140 STM32 clean mbed_rtx.h file
  rtos/source/TARGET_CORTEX/mbed_lib.json
  targets/TARGET_STM/mbed_rtx.h
Labels: ready for merge

#12134 Fix LPC11U35_401 baremetal build
  targets/TARGET_NXP/TARGET_LPC11UXX/device/cmsis_nvic.c
  targets/TARGET_NXP/TARGET_LPC11UXX/us_ticker.c
  targets/targets.json
Labels: Release review required, ready for merge

#11999 Add instructions for providing mbed-os version affected
  .github/issue_template.md
Labels: ready for merge

#12063 Move get_ip_address_if() to NetworkStack and include it in multihoming test
  TESTS/network/multihoming/main.cpp
  features/lwipstack/LWIPInterface.cpp
  features/lwipstack/LWIPStack.cpp
  features/lwipstack/LWIPStack.h
  features/netsocket/OnboardNetworkStack.h
Labels: ready for merge, release-version: 6.0.0-alpha-1

#12089 Update offloaded TLSSocket to TLSSocket design
  docs/design-documents/features/connectivity/TLSSocket - Design document.md
Labels: ready for merge

#12141 Thread: remove constructors deprecated in 5.1
  rtos/Thread.h
  rtos/source/Thread.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-1

#12138 TESTS-MBED_HAL-COMMON_TICKERS no more executed
  TESTS/mbed_hal/common_tickers/main.cpp
  TESTS/mbed_hal/common_tickers_freq/main.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-1

#12126 Robustify equeue multithread unit test
  UNITTESTS/events/equeue/test_equeue.cpp
Labels: Release review required, ready for merge
