Repository ARMmbed/mbed-os, pull requests merged in 2019-10, with the labels that each got.

#11595 Check return of BlockDevice::init() in TDBStore.
  features/storage/kvstore/tdbstore/TDBStore.cpp
  features/storage/kvstore/tdbstore/TDBStore.h
Labels: ready for merge, release-version: 5.15.0-rc1

#11566 EP_AGORA: Add config logic to enable BLE, cell, and LoRa by default
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_AGORA/ONBOARD_TELIT_ME910.cpp
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_AGORA/ONBOARD_TELIT_ME910.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_AGORA/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_AGORA/onboard_modem_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.14.1

#11581 Cellular: Fix setting of PDP context ID (cid)
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  UNITTESTS/stubs/AT_CellularStack_stub.cpp
  UNITTESTS/target_h/myCellularContext.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
Labels: ready for merge, release-version: 5.14.1

#11582 TEST: change integration fs test format and mount order
  TESTS/integration/fs-single/main.cpp
Labels: ready for merge, release-version: 5.14.1

#11598 AT_CellularDevice.cpp - unused variable err warning
  features/cellular/framework/AT/AT_CellularDevice.cpp
Labels: ready for merge, release-version: 5.14.1

#11486 update googletest to v1.8.1
  UNITTESTS/CMakeLists.txt
  UNITTESTS/README.md
  UNITTESTS/googletest-CMakeLists.txt.in
Labels: ready for merge, release-version: 5.14.1

#11572 Tighten GCC 2-region _sbrk
  platform/source/mbed_retarget.cpp
Labels: ready for merge, release-version: 5.14.1

#11357 Offloaded TLSSocket and BG96 support for it
  TESTS/netsocket/tls/main.cpp
  TESTS/netsocket/tls/tlssocket_endpoint_close.cpp
  TESTS/netsocket/tls/tlssocket_handshake_invalid.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/at_cellularstacktest.cpp
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.h
  features/netsocket/TLSSocket.cpp
  features/netsocket/TLSSocket.h
  features/netsocket/mbed_lib.json
  features/netsocket/nsapi_types.h
Labels: ready for merge, release-version:6.0.0-rc1

#11589 Enable PSA tests for fastmodel
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/objects.h
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/trng_api.c
  targets/targets.json
Labels: ready for merge

#11399 Add explicit pin-map support for K64F and NUCLEO_F429ZI
  TESTS/mbed_hal_fpga_ci_test_shield/analogin/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/pwm/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/uart/main.cpp
  drivers/AnalogIn.h
  drivers/AnalogOut.h
  drivers/I2C.h
  drivers/I2CSlave.h
  drivers/PwmOut.h
  drivers/SPI.h
  drivers/SPISlave.h
  drivers/Serial.h
  drivers/SerialBase.h
  drivers/UARTSerial.h
  drivers/source/AnalogIn.cpp
  drivers/source/I2C.cpp
  drivers/source/I2CSlave.cpp
  drivers/source/PwmOut.cpp
  drivers/source/SPI.cpp
  drivers/source/SPISlave.cpp
  drivers/source/Serial.cpp
  drivers/source/SerialBase.cpp
  drivers/source/UARTSerial.cpp
  hal/analogin_api.h
  hal/analogout_api.h
  hal/explicit_pinmap.cpp
  hal/explicit_pinmap.h
  hal/i2c_api.h
  hal/pwmout_api.h
  hal/serial_api.h
  hal/spi_api.h
  platform/cxxsupport/mstd_cstddef
  platform/source/mbed_retarget.cpp
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralPinMaps.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PinNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/pwmout_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/spi_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/analogin_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/analogout_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/i2c_api.c
  targets/TARGET_ONSEMI/TARGET_NCS36510/objects.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PeripheralPinMaps.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F4/analogout_device.c
  targets/TARGET_STM/TARGET_STM32F4/common_objects.h
  targets/TARGET_STM/TARGET_STM32F4/serial_device.c
  targets/TARGET_STM/i2c_api.c
  targets/TARGET_STM/pwmout_api.c
  targets/TARGET_STM/serial_api.c
  targets/TARGET_STM/stm_spi_api.c
Labels: ready for merge

#11558 Coverity fixes
  features/cellular/framework/common/CellularUtil.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/frameworks/mbed-coap/source/sn_coap_builder.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread/thread_mle_message_handler.c
Labels: ready for merge, release-version: 5.14.1

#11548 Cellular: Fix resolving of DNS server IPv4/6 address
  UNITTESTS/features/cellular/framework/common/util/utiltest.cpp
  UNITTESTS/stubs/CellularUtil_stub.cpp
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/common/CellularUtil.cpp
Labels: ready for merge, release-version: 5.14.1

#11601 DNS tests modification for ESP8266-specific scenario
  TESTS/netsocket/dns/asynchronous_dns_timeouts.cpp
  TESTS/netsocket/dns/dns_tests.h
Labels: ready for merge, release-version: 5.14.1

#11607 Tests: USB: Move control endpoint buffers to heap
  TESTS/usb_device/basic/USBEndpointTester.cpp
  TESTS/usb_device/basic/USBEndpointTester.h
  TESTS/usb_device/basic/USBTester.cpp
  TESTS/usb_device/basic/USBTester.h
Labels: ready for merge, release-version: 5.14.1

#11638 Change imgtool lib import to relative import
  tools/psa/tfm/bin_utils/imgtool.py
Labels: ready for merge

#11625 Revert tickless on UBLOX_EVK_ODIN_W2
  targets/targets.json
Labels: ready for merge

#11618 Cellular: Fix CellularStateMachine to not loop between init/power states
  features/cellular/framework/device/CellularStateMachine.cpp
Labels: ready for merge, release-version: 5.14.1

#11639 Nanostack patch release for mbedos 5.14.1
  features/nanostack/coap-service/test/coap-service/unittest/makefile_defines.txt
  features/nanostack/sal-stack-nanostack/nanostack/dhcp_service_api.h
  features/nanostack/sal-stack-nanostack/nanostack/sw_mac.h
  features/nanostack/sal-stack-nanostack/nanostack/ws_bbr_api.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC/mac_helper.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC/mac_helper.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_config.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_lib.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.c
  features/nanostack/sal-stack-nanostack/source/Common_Protocols/icmpv6.c
  features/nanostack/sal-stack-nanostack/source/Common_Protocols/udp.c
  features/nanostack/sal-stack-nanostack/source/DHCPv6_client/dhcpv6_client_service.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_defines.h
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mcps_sap.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mcps_sap.h
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mlme.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mlme.h
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_pd_sap.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_security_mib.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_security_mib.h
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/sw_mac.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_control.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_control.h
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_downward.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_policy.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_policy.h
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_structures.h
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_upward.c
  features/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_api.c
  features/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_api.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/auth_eap_tls_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/eap_tls_sec_prot_lib.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/eap_tls_sec_prot_lib.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/supp_eap_tls_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot/auth_fwh_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot/supp_fwh_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot/auth_gkh_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot/supp_gkh_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_certs.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_certs.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_lib.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_lib.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot/tls_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot/tls_sec_prot.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot/tls_sec_prot_lib.c
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/dhcp_service_api.c
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6.c
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6.h
  features/nanostack/sal-stack-nanostack/source/libNET/src/ns_net.c
Labels: Manually Patch, ready for merge, release-version: 5.14.1

#11551 Coverity updates
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  features/nfc/source/nfc/NFCEEPROM.cpp
  features/nfc/source/nfc/ndef/common/Text.cpp
  features/nfc/source/nfc/ndef/common/URI.cpp
Labels: ready for merge, release-version: 5.14.1

#11297 Differentiate alt and dummy cycles in QSPIF
  TESTS/mbed_hal/qspi/qspi_test_utils.h
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.h
  drivers/QSPI.h
  drivers/source/QSPI.cpp
  features/storage/TESTS/kvstore/direct_access_devicekey_test/main.cpp
  hal/qspi_api.h
  targets/TARGET_Cypress/TARGET_PSOC6/cy_qspi_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_qspi.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_qspi.c
  targets/TARGET_STM/qspi_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/qspi_api.c
Labels: ready for merge, release-version: 5.14.1

#11561 Add TARGET_CY8CPROTO_063_BLE
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.timestamp
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_notices.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/design.modus
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/PeripheralNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/PinNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/cybsp.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/cybsp.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/cybsp_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/device/TOOLCHAIN_ARM/cy8c6xx7_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/device/TOOLCHAIN_ARM/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/device/TOOLCHAIN_GCC_ARM/cy8c6xx7_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/device/TOOLCHAIN_GCC_ARM/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/device/TOOLCHAIN_IAR/cy8c6xx7_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/device/TOOLCHAIN_IAR/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/device/system_psoc6_cm4.c
  targets/targets.json
Labels: ready for merge, release-version: 5.14.1

#11626 DISCO_L4R9I: update default STMOD+ pin
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/PinNames.h
Labels: ready for merge, release-version: 5.14.1

#11621 STM32L151: update calibration memory address
  targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_ll_adc.h
Labels: ready for merge, release-version: 5.14.1

#11627 pinmap_peripheral function: update error code for easier debug
  hal/mbed_pinmap_common.c
Labels: ready for merge, release-version: 5.14.1

#11615 Cellular: Remove old deprecated tests
  TESTS/netsocket/README.md
  features/cellular/README.md
  features/cellular/TESTS/api/cellular_device/main.cpp
  features/cellular/TESTS/api/cellular_information/main.cpp
  features/cellular/TESTS/api/cellular_network/main.cpp
  features/cellular/TESTS/api/cellular_sms/main.cpp
  features/cellular/TESTS/cellular_tests_common.h
  features/cellular/TESTS/socket/udp/main.cpp
  features/cellular/TESTS/socket/udp/template_mbed_app.json.txt
  features/cellular/junit_xsl.xslt
  features/cellular/xsl_script.sh
Labels: release-version: 5.14.1

#11678 Travis CI: Fixed issue where jobs are getting stalled/timing out
  tools/test/travis-ci/functions.sh
Labels: ready for merge, release-version: 5.14.1

#11649 Fix memory leak on NetworkInterface destruction
  features/netsocket/NetworkInterface.cpp
Labels: ready for merge, release-version: 5.14.1

#11612 IPCore unittests improvements
  UNITTESTS/features/netsocket/DTLSSocket/test_DTLSSocket.cpp
  UNITTESTS/features/netsocket/InternetSocket/test_InternetSocket.cpp
  UNITTESTS/features/netsocket/NetworkInterface/test_NetworkInterface.cpp
  UNITTESTS/features/netsocket/SocketAddress/test_SocketAddress.cpp
  UNITTESTS/features/netsocket/TCPSocket/test_TCPSocket.cpp
  UNITTESTS/features/netsocket/TLSSocketWrapper/test_TLSSocketWrapper.cpp
  UNITTESTS/features/netsocket/UDPSocket/test_UDPSocket.cpp
Labels: ready for merge, release-version: 5.14.1

#11647 Nanostack RF driver updates for Mbed OS 5.14.1
  components/802.15.4_RF/stm-s2lp-rf-driver/source/NanostackRfPhys2lp.cpp
  components/802.15.4_RF/stm-s2lp-rf-driver/source/s2lpReg.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 5.14.1

#11512 Fix Failure in Cryptocell tests on Montgomrery curve
  features/cryptocell/FEATURE_CRYPTOCELL310/ecdh_alt.c
Labels: ready for merge, release-version: 5.14.2

#11609 IOTBTOOL-407 Fix microbit to use Arm C5
  targets/targets.json
Labels: ready for merge, release-version: 5.14.2

#11623 STMOD_CELLULAR: set CTS with PullDown
  components/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.cpp
Labels: ready for merge, release-version: 5.14.2

#11660 Fix dropped bytes on spi write
  targets/TARGET_Cypress/TARGET_PSOC6/cy_spi_api.c
Labels: ready for merge, release-version: 5.14.2

#11669 Fixed issue with integer overflow when converting time units
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/rtos/include/cyabs_rtos.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/rtos/source/COMPONENT_RTX/cyabs_rtos_rtxv5.c
Labels: ready for merge, release-version: 5.14.2

#11667 Fixes IPv6 multicast join issue
  features/lwipstack/LWIPStack.cpp
Labels: ready for merge, release-version: 5.14.2

#11547 Fix for UBLOX_EVK_ODIN_W2 fails in emac test.
  TESTS/network/emac/emac_test_multicast_filter.cpp
  TESTS/network/emac/main.cpp
  TESTS/network/emac/mbed_lib.json
Labels: release-version: 5.14.2

#11686 Corrected nanostack PAE controller
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
Labels: ready for merge, release-version: 5.14.2

#11661 mbed_rtc_time.h lacks an include guard
  platform/mbed_rtc_time.h
Labels: release-version: 5.14.2

#11645 Enable tickless for PSoC6 targets
  targets/targets.json
Labels: ready for merge, release-version: 5.14.2

#11673 stm32f4xx_hal_pcd.c@346,22: unused variable 'ep'
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd.c
Labels: ready for merge, release-version: 5.14.2

#11628 Make devicekey remainder test more meaningful
  features/storage/TESTS/kvstore/direct_access_devicekey_test/main.cpp
Labels: ready for merge, release-version: 5.14.1

#11671 nrf5x - add missing gpio_set implementation
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF51/gpio_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/gpio_api.c
Labels: ready for merge, release-version: 5.14.2

#11676 nrf52 - fix i2c/twi driver
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/modules/nrfx/drivers/src/nrfx_twi.c
Labels: ready for merge, release-version: 5.14.2

#11642 STMOD_CELLULAR: remove flow control support for DISCO_L4R9I
  components/cellular/COMPONENT_STMOD_CELLULAR/README.md
  components/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.cpp
  components/cellular/COMPONENT_STMOD_CELLULAR/mbed_lib.json
Labels: ready for merge, release-version: 5.14.2

#11622 nRF52 SDK 15.0 - Enable more than 1 interrupt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
Labels: ready for merge, release-version: 5.14.2

#11630 Cellular: Change visibility of _is_connected as protected
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
Labels: ready for merge, release-version: 5.14.2

#11636 EFM32GG11_STK3701: add QSPIF component config
  components/storage/blockdevice/COMPONENT_QSPIF/mbed_lib.json
Labels: ready for merge, release-version: 5.14.2

#11646 Fix swapped BT pins on CYW943012P6EVB-01
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/COMPONENT_BSP_DESIGN_MODUS/design.modus
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/cybsp_types.h
Labels: ready for merge, release-version: 5.14.2

#11635 USBDevice: add documentation on USB suspend/resume to enter deep sleep
  drivers/internal/USBDevice.h
Labels: release-version: 5.14.2

#11694 Fix components setting for GR-PEACH and GR-LYCHEE
  targets/targets.json
Labels: ready for merge, release-version: 5.14.2

#11692 NRF52840_DK: enables FLASHIAP for the device
  targets/targets.json
Labels: ready for merge, release-version: 5.14.2

#11688 Clearing UART TC Flag prevents deep sleep, so do not clear it
  targets/TARGET_STM/TARGET_STM32F0/serial_device.c
  targets/TARGET_STM/TARGET_STM32F1/serial_device.c
  targets/TARGET_STM/TARGET_STM32F2/serial_device.c
  targets/TARGET_STM/TARGET_STM32F3/serial_device.c
  targets/TARGET_STM/TARGET_STM32F4/serial_device.c
  targets/TARGET_STM/TARGET_STM32F7/serial_device.c
  targets/TARGET_STM/TARGET_STM32H7/serial_device.c
  targets/TARGET_STM/TARGET_STM32L0/serial_device.c
  targets/TARGET_STM/TARGET_STM32L1/serial_device.c
  targets/TARGET_STM/TARGET_STM32L4/serial_device.c
  targets/TARGET_STM/TARGET_STM32WB/serial_device.c
Labels: ready for merge, release-version: 5.14.2

#11644 Cypress Cordio BT Driver setting Host MCU active during Host Wake assert
  features/FEATURE_BLE/targets/TARGET_Cypress/TARGET_CYW43XXX/CyH4TransportDriver.cpp
  features/FEATURE_BLE/targets/TARGET_Cypress/TARGET_CYW43XXX/CyH4TransportDriver.h
  features/FEATURE_BLE/targets/TARGET_Cypress/TARGET_CYW43XXX/HCIDriver.cpp
Labels: ready for merge, release-version: 5.14.2

#11599 FUTURE_SEQUANA: SPI HAL API fixes
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/spi_api.c
Labels: ready for merge, release-version: 5.14.2

#11434 Initial addition of files to support CY8CKIT_064S2_4343W target
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.timestamp
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_dmas.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_dmas.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_notices.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/qspi_config.cfg
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/design.cycapsense
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/design.cyqspi
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/design.modus
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/PeripheralNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/PinNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/cybsp.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/cybsp.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/cybsp_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/TOOLCHAIN_ARM/cyb06xxa_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/TOOLCHAIN_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/TOOLCHAIN_GCC_ARM/cyb06xxa_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/TOOLCHAIN_IAR/cyb06xxa_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/TOOLCHAIN_IAR/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/secure_image_parameters.json
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/policy/policy_single_stage_CM4_2m.json
  targets/targets.json
Labels: ready for merge, release-version: 5.14.2, scope: new-target

#11604 Introduce qspi_inst_t type for QSPI instructions
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.h
  drivers/QSPI.h
  drivers/source/QSPI.cpp
Labels: ready for merge, release-version: 5.14.2

#11602 Allow for arbitrary QSPI alt sizes
  TESTS/mbed_hal/qspi/qspi_test_utils.h
  hal/qspi_api.h
  targets/TARGET_STM/qspi_api.c
Labels: ready for merge, release-version: 5.14.2

#11701 ARM toolchain: heap setup micro-optimisation
  platform/source/mbed_retarget.cpp
Labels: ready for merge, release-version:6.0.0-rc1

#11648 OLIMEX_STM32E407_F407ZG: Added new target platform
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_OLIMEX_STM32E407_F407ZG/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_OLIMEX_STM32E407_F407ZG/stm32f4_eth_init.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_OLIMEX_STM32E407_F407ZG/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_OLIMEX_STM32E407_F407ZG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_OLIMEX_STM32E407_F407ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/TARGET_OLIMEX_STM32E407_F407ZG/system_clock.c
  targets/TARGET_STM/USBPhy_STM32.cpp
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
  tools/arm_pack_manager/aliases.json
  tools/arm_pack_manager/legacy-names.json
Labels: ready for merge, scope: new-target

#11603 Report errors returned by _qspi_configure_format
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
Labels: ready for merge, release-version: 5.14.2

#11556 modified Wi-SUN tasklet to return success when calling connect twice
  features/nanostack/nanostack-interface/Nanostack.cpp
Labels: BREAKING-CHANGE, ready for merge, release-version: 5.15.0-rc1

#11699 Fix for missing os_cb_section
  platform/source/mbed_sdk_boot.c
Labels: ready for merge, release-version: 5.14.2

#11457 tools: add silent option to build
  tools/build.py
  tools/test.py
  tools/test_api.py
Labels: ready for merge

#11586 Cleaned up Mbed LWIP configurations
  features/lwipstack/lwip-sys/arch/cc.h
  features/lwipstack/lwip/src/include/lwip/lwip_errno.h
  features/lwipstack/lwipopts.h
  features/lwipstack/mbed_lib.json
  features/netsocket/ppp/include/ppp_opts.h
Labels: ready for merge, release-version: 5.14.2

#11657 Cellular: Fix apn check
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
Labels: ready for merge, release-version: 5.14.2

#11679 STM32L4 TRNG clock configuration
  targets/TARGET_STM/trng_api.c
Labels: ready for merge, release-version: 5.14.2

#11708 TARGET_STM: remove warning and fix typo on SPI
  targets/TARGET_STM/stm_spi_api.c
Labels: ready for merge, release-version: 5.14.2

#11717 Fix Quectel M26 context hang
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26.cpp
Labels: release-version: 5.14.2

#11444 QSPI : Define default pins at drivers level
  TESTS/mbed_hal/qspi/flash_configs/flash_configs.h
  TESTS/mbed_hal/qspi/main.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/mbed_lib.json
  drivers/mbed_lib.json
  targets/targets.json
Labels: ready for merge, release-version:6.0.0-rc1

#11429 Move script to check for floats and make it Python 2 compatible
  tools/test/examples/elf_float_checker.py
  tools/test/examples/test_elf_float_checker.py
Labels: ready for merge, release-version: 5.14.2

#11620 Fix enum type to align with psa-arch-tests
  components/TARGET_PSA/TESTS/compliance_attestation/test_a001/test_a001.c
  components/TARGET_PSA/TESTS/compliance_attestation/test_a001/test_a001.h
  components/TARGET_PSA/TESTS/compliance_its/test_s001/test_s001.c
  components/TARGET_PSA/TESTS/compliance_its/test_s001/test_s001.h
  components/TARGET_PSA/TESTS/compliance_its/test_s002/test_s002.c
  components/TARGET_PSA/TESTS/compliance_its/test_s002/test_s002.h
  components/TARGET_PSA/TESTS/compliance_its/test_s003/test_s003.c
  components/TARGET_PSA/TESTS/compliance_its/test_s003/test_s003.h
  components/TARGET_PSA/TESTS/compliance_its/test_s004/test_s004.c
  components/TARGET_PSA/TESTS/compliance_its/test_s004/test_s004.h
  components/TARGET_PSA/TESTS/compliance_its/test_s005/test_s005.c
  components/TARGET_PSA/TESTS/compliance_its/test_s005/test_s005.h
  components/TARGET_PSA/TESTS/compliance_its/test_s006/test_s006.c
  components/TARGET_PSA/TESTS/compliance_its/test_s006/test_s006.h
  components/TARGET_PSA/TESTS/compliance_its/test_s007/test_s007.c
  components/TARGET_PSA/TESTS/compliance_its/test_s007/test_s007.h
  components/TARGET_PSA/TESTS/compliance_its/test_s008/test_s008.c
  components/TARGET_PSA/TESTS/compliance_its/test_s008/test_s008.h
  components/TARGET_PSA/TESTS/compliance_its/test_s009/test_s009.c
  components/TARGET_PSA/TESTS/compliance_its/test_s009/test_s009.h
  components/TARGET_PSA/TESTS/compliance_its/test_s010/test_s010.c
  components/TARGET_PSA/TESTS/compliance_its/test_s010/test_s010.h
  features/frameworks/TARGET_PSA/val.h
  features/frameworks/TARGET_PSA/val_greentea.cpp
Labels: ready for merge, release-version: 5.14.2

#11690 Changed mbed gpio-port api to match gpio api
  targets/TARGET_Cypress/TARGET_PSOC6/cy_port_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/gpio_object.h
Labels: ready for merge, release-version: 5.14.2

#11691 QSPI: document use of QSPI_NO_INST
  drivers/QSPI.h
Labels: ready for merge, release-version: 5.14.2

#11672 STM32F767ZI - I2C FastModePlus not properly enabled
  targets/TARGET_STM/i2c_api.c
Labels: ready for merge, release-version: 5.14.2

#11684 Add support for nRF52 Watchdog
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/watchdog_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/modules/nrfx/drivers/src/nrfx_wdt.c
Labels: ready for merge, release-version: 5.14.2

#11724 iar export for TT_M3HQ and TT_M4G9
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.14.2

#11706 MCU_NRF52840: Switches to correct Product Anomaly Notification(PAN) macro
  targets/targets.json
Labels: ready for merge, release-version: 5.14.2

#11677 Update BT Firmware to version 128.
  features/FEATURE_BLE/targets/TARGET_Cypress/TARGET_CYW43XXX/firmware/TARGET_43012/w_bt_firmware_controller.c
Labels: ready for merge, release-version: 5.14.2

#11702 Update issue template
  .github/issue_template.md
Labels: ready for merge

#11536 STM32 EMAC configuration update
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/stm32f2_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F2/stm32f2_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F2/stm32xx_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_ARCH_MAX/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_ARCH_MAX/stm32f4_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_MODULE_UBLOX_ODIN_W2/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_MODULE_UBLOX_ODIN_W2/stm32f4_eth_init.cpp
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_MODULE_UBLOX_ODIN_W2/wifi_emac/wifi_emac.cpp
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_MODULE_UBLOX_ODIN_W2/wifi_emac/wifi_emac.h
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F429ZI/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F429ZI/stm32f4_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F439ZI/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F439ZI/stm32f4_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_C030/stm32f4_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/TARGET_UBLOX_C030/stm32f4_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/stm32xx_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F7/TARGET_DISCO_F746NG/stm32f7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F7/TARGET_DISCO_F769NI/stm32f7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F746ZG/stm32f7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F756ZG/stm32f7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F7/TARGET_NUCLEO_F767ZI/stm32f7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F7/stm32f7_eth_conf.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F7/stm32xx_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/TARGET_NUCLEO_H743ZI/stm32h7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/TARGET_NUCLEO_H743ZI2/stm32h7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/lan8742/lan8742.c
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/lan8742/lan8742.h
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/stm32xx_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM/mbed_lib.json
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.h
  targets/targets.json
Labels: ready for merge, release-version: 5.14.2

#11728 minimal_printf: Fix high level C functions that print to the console
  platform/source/minimal-printf/mbed_printf_armlink_overrides.c
Labels: ready for merge, release-version: 5.14.2

#11624 LittleFS: Update to v1.7.2
  features/storage/filesystem/littlefs/littlefs/.travis.yml
  features/storage/filesystem/littlefs/littlefs/Makefile
  features/storage/filesystem/littlefs/littlefs/README.md
  features/storage/filesystem/littlefs/littlefs/emubd/lfs_emubd.c
  features/storage/filesystem/littlefs/littlefs/lfs.c
  features/storage/filesystem/littlefs/littlefs/lfs.h
  features/storage/filesystem/littlefs/littlefs/scripts/prefix.py
  features/storage/filesystem/littlefs/littlefs/tests/test_alloc.sh
  features/storage/filesystem/littlefs/littlefs/tests/test_dirs.sh
  features/storage/filesystem/littlefs/littlefs/tests/test_seek.sh
  features/storage/filesystem/littlefs/littlefs/tests/test_truncate.sh
Labels: ready for merge, release-version: 5.14.2

#11729 minimal-printf: Fix handling of the two character sequence %%
  TESTS/mbed_platform/minimal-printf/compliance/main.cpp
  platform/source/minimal-printf/mbed_printf_implementation.c
Labels: ready for merge, release-version: 5.14.2

#11725 DeviceKey: Fix random key doesn't generate with custom entropy source
  features/device_key/TESTS/device_key/functionality/main.cpp
  features/device_key/source/DeviceKey.cpp
Labels: ready for merge, release-version: 5.14.2

#11662 Allow WhdAccessPoint scan results with extended parameters
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdAccessPoint.cpp
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdAccessPoint.h
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdSTAInterface.cpp
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdSTAInterface.h
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdSoftAPInterface.h
Labels: ready for merge, release-version: 5.14.2

#11650 Nuvoton: Re-implement TRNG HAL with TRNG H/W
  targets/TARGET_NUVOTON/TARGET_M2351/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NPSA_NS/TARGET_NU_PREBUILD_SECURE/NuMaker-mbed-TZ-secure-example.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NPSA_NS/TARGET_NU_PREBUILD_SECURE/README.md
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NPSA_NS/TARGET_NU_PREBUILD_SECURE/cmse_lib.o
  targets/TARGET_NUVOTON/TARGET_M2351/crypto/crypto-misc.cpp
  targets/TARGET_NUVOTON/TARGET_M2351/crypto/crypto-misc.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/M2351.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/M2351_funcs.S
  targets/TARGET_NUVOTON/TARGET_M2351/device/StdDriver/m2351_bootloader.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/StdDriver/m2351_crypto.c
  targets/TARGET_NUVOTON/TARGET_M2351/device/StdDriver/m2351_crypto.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/StdDriver/m2351_mkromlib.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/partition_M2351.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/system_M2351.c
  targets/TARGET_NUVOTON/TARGET_M2351/hal_secure.h
  targets/TARGET_NUVOTON/TARGET_M2351/trng_api.c
  targets/TARGET_NUVOTON/TARGET_M2351/trng_api.cpp
  targets/TARGET_NUVOTON/TARGET_M261/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_M261/crypto/crypto-misc.cpp
  targets/TARGET_NUVOTON/TARGET_M261/crypto/crypto-misc.h
  targets/TARGET_NUVOTON/TARGET_M261/device/M261.h
  targets/TARGET_NUVOTON/TARGET_M261/device/StdDriver/m261_mkromlib.h
  targets/TARGET_NUVOTON/TARGET_M261/device/system_M261.c
  targets/TARGET_NUVOTON/TARGET_M261/trng_api.c
  targets/TARGET_NUVOTON/TARGET_M261/trng_api.cpp
  targets/targets.json
Labels: needs: CI, ready for merge, release-version: 5.14.2

#11734 nxp LPC55S69: fix i2c pin mapping
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_LPCXpresso/PinNames.h
Labels: ready for merge, release-version: 5.14.2

#11578 Add synchronization and switching between WhdSoftAPInterface and WhdSTAInterfaces
  features/netsocket/emac-drivers/TARGET_WHD/interface/CyDhcpServer.cpp
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdSTAInterface.cpp
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdSTAInterface.h
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdSoftAPInterface.cpp
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdSoftAPInterface.h
  features/netsocket/emac-drivers/TARGET_WHD/interface/whd_emac.cpp
  features/netsocket/emac-drivers/TARGET_WHD/interface/whd_interface.cpp
  features/netsocket/emac-drivers/TARGET_WHD/interface/whd_interface.h
Labels: devices: cypress, release-version: 5.14.2

#11563 Simplify pull request template
  .github/pull_request_template.md
Labels: ready for merge

#11749 M2351: Change base target name 'NU_PFM_M2351_CM' to 'NU_PFM_M2351'
  targets/targets.json
Labels: ready for merge, release-version: 5.14.2

#11747 Update the internal kvstore flash reservation size to from 7k to 65K for Cypress Devices
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
Labels: devices: cypress, ready for merge, release-version: 5.14.2

#11748 Fix spurious link up/down when AP IP address range change
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdSTAInterface.cpp
Labels: devices: cypress, ready for merge

#11631 Qspi frequency test fix
  TESTS/mbed_hal/qspi/flash_configs/SiliconLabs/EFM32GG11_STK3701/flash_config.h
  TESTS/mbed_hal/qspi/main.cpp
Labels: ready for merge, release-version: 5.14.2

#11710 Update examples testing scripts
  tools/test/examples/README.md
  tools/test/examples/examples.json
  tools/test/examples/examples.py
  tools/test/examples/examples_lib.py
Labels: ready for merge

#11718 Handle legacy process event first on connection complete
  features/FEATURE_BLE/source/generic/GenericGap.tpp
Labels: ready for merge, release-version: 5.14.2

#11743 fpga i2c test: limit tested peripherals
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/main.cpp
Labels: ready for merge, release-version: 5.14.2

#11571 Allow OS_THREAD_LIBSPACE_NUM as a macro
  rtos/source/TARGET_CORTEX/mbed_rtx_conf.h
  rtos/source/TARGET_CORTEX/rtx5/RTX/Config/RTX_Config.h
  tools/test_configs/CellularInterface.json
Labels: ready for merge, release-version: 5.14.2

#11752 FlashIAP: Get erase value from HAL instead of hardcoding it
  TESTS/mbed_drivers/flashiap/main.cpp
  drivers/source/FlashIAP.cpp
Labels: ready for merge, release-version: 5.14.2

#11742 Fix the reset_reason host test in the CI
  TESTS/host_tests/reset_reason.py
Labels: ready for merge, release-version: 5.14.2

#11739 Nrf52 i2c byte rw fix
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/i2c_api.c
Labels: ready for merge, release-version: 5.14.2

#11754 Cellular: Added write_hex_string to AT handler
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
Labels: ready for merge, release-version: 5.14.2

#11715 Add CYW9P62S1_43012EVB_01 board
  TESTS/mbed_hal/qspi/flash_configs/flash_configs.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.timestamp
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_notices.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/qspi_config.cfg
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/design.cycapsense
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/design.cyqspi
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/design.modus
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/PeripheralNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/PinNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/SDIO_HOST/SDIO_HOST.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/SDIO_HOST/SDIO_HOST.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/SDIO_HOST/SDIO_HOST_cfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/SDIO_HOST/SDIO_HOST_cfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/cybsp.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/cybsp.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/cybsp_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/device/TOOLCHAIN_ARM/cy8c6xx7_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/device/TOOLCHAIN_ARM/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/device/TOOLCHAIN_GCC_ARM/cy8c6xx7_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/device/TOOLCHAIN_GCC_ARM/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/device/TOOLCHAIN_IAR/cy8c6xx7_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/device/TOOLCHAIN_IAR/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/device/system_psoc6_cm4.c
  targets/targets.json
Labels: devices: cypress, ready for merge, release-version: 5.14.2, scope: new-target

#11695 GREENTEA: init trace if trace is enabled in json
  features/frameworks/greentea-client/source/greentea_test_env.cpp
Labels: ready for merge, release-version: 5.14.2

#11632 Add explicit pin-map support for extra targets
  drivers/AnalogIn.h
  drivers/AnalogOut.h
  drivers/CAN.h
  drivers/I2C.h
  drivers/I2CSlave.h
  drivers/PwmOut.h
  drivers/QSPI.h
  drivers/SPI.h
  drivers/SPISlave.h
  drivers/Serial.h
  drivers/source/CAN.cpp
  drivers/source/QSPI.cpp
  hal/can_api.h
  hal/explicit_pinmap.cpp
  hal/explicit_pinmap.h
  hal/qspi_api.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/PeripheralPinMaps.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/PeripheralPins.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/PortNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/analogin_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/analogin_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/i2c_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/lp_analogin_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/serial_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/spi_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_LPCXpresso/PeripheralPinMaps.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_LPCXpresso/PeripheralPins.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_LPCXpresso/PinNames.h
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/TARGET_NUCLEO_F303RE/PeripheralPinMaps.h
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/TARGET_NUCLEO_F303RE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/TARGET_NUCLEO_F303RE/PinNames.h
  targets/TARGET_STM/TARGET_STM32F3/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F3/analogout_device.c
  targets/TARGET_STM/TARGET_STM32F3/common_objects.h
  targets/TARGET_STM/TARGET_STM32F3/serial_device.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/PeripheralPinMaps.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PeripheralPinMaps.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/PeripheralPinMaps.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/PinNames.h
  targets/TARGET_STM/TARGET_STM32L0/analogin_device.c
  targets/TARGET_STM/TARGET_STM32L0/analogout_device.c
  targets/TARGET_STM/TARGET_STM32L0/common_objects.h
  targets/TARGET_STM/TARGET_STM32L0/serial_device.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PeripheralPinMaps.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/analogin_device.c
  targets/TARGET_STM/TARGET_STM32L4/analogout_device.c
  targets/TARGET_STM/TARGET_STM32L4/common_objects.h
  targets/TARGET_STM/TARGET_STM32L4/serial_device.c
  targets/TARGET_STM/can_api.c
  targets/TARGET_STM/qspi_api.c
Labels: ready for merge, release-version: feature branch

#11756 Add option to use CCMRAM on F303xE.
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/device/TOOLCHAIN_ARM_STD/stm32f303xe.sct
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/device/TOOLCHAIN_GCC_ARM/STM32F303XE.ld
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/device/TOOLCHAIN_IAR/stm32f303xe.icf
Labels: ready for merge, release-version: 5.14.2

#10924 Free serial resources if not needed anymore
  UNITTESTS/stubs/SerialBase_stub.cpp
  drivers/SerialBase.h
  drivers/source/SerialBase.cpp
  drivers/source/UARTSerial.cpp
  targets/TARGET_Maxim/TARGET_MAX32600/serial_api.c
  targets/TARGET_Maxim/TARGET_MAX32620C/serial_api.c
  targets/TARGET_Maxim/TARGET_MAX32625/serial_api.c
  targets/TARGET_Maxim/TARGET_MAX32630/serial_api.c
Labels: ready for merge, release-version:6.0.0-rc1

#11767 Increase STM32 default deep sleep latency to 4ms
  targets/targets.json
Labels: release-version: 5.14.2

#11032 Add test header files and defined behavior for APIs tested using FPGA-Test-Shield
  TESTS/mbed_hal_fpga_ci_test_shield/analogin/analogin_fpga_test.h
  TESTS/mbed_hal_fpga_ci_test_shield/analogin/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/gpio/gpio_fpga_test.h
  TESTS/mbed_hal_fpga_ci_test_shield/gpio/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/gpio_irq/gpio_irq_fpga_test.h
  TESTS/mbed_hal_fpga_ci_test_shield/gpio_irq/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/i2c_fpga_test.h
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/pwm/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/pwm/pwm_fpga_test.h
  TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/spi/spi_fpga_test.h
  TESTS/mbed_hal_fpga_ci_test_shield/uart/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/uart/uart_fpga_test.h
  hal/analogin_api.h
  hal/analogout_api.h
  hal/gpio_api.h
  hal/gpio_irq_api.h
  hal/i2c_api.h
  hal/mbed_compat.c
  hal/pwmout_api.h
  hal/serial_api.h
  hal/spi_api.h
Labels: ready for merge, release-version:6.0.0-rc1

#11735 Dns unittest preparation
  features/netsocket/nsapi_dns.cpp
  features/netsocket/nsapi_dns.h
Labels: ready for merge, release-version: 5.14.2

#11619 Add FLASHIAP component to DISCO_H747
  features/storage/kvstore/conf/global/mbed_lib.json
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32H7/flash_api.c
  targets/targets.json
Labels: release-version: 5.14.2

#11765 Cypress: fix GPIO mode NONE
  targets/TARGET_Cypress/TARGET_PSOC6/PinNamesTypes.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/include/cyhal_gpio.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_gpio.c
Labels: devices: cypress, ready for merge, release-version: 5.14.2

#11759 STM32 QSPI: Use defines for setting address size
  targets/TARGET_STM/qspi_api.c
Labels: ready for merge, release-version: 5.14.2

#11697 USB-Cypress: Lock sleep when USB is initialized
  targets/TARGET_Cypress/TARGET_PSOC6/cy_usb_phy.cpp
Labels: ready for merge, release-version: 5.14.2

#11203 Add watchdog lower limit timeout test
  TESTS/mbed_hal/watchdog_timing/main.cpp
  TESTS/mbed_hal/watchdog_timing/watchdog_timing_tests.h
  hal/watchdog_api.h
  targets/TARGET_Cypress/TARGET_PSOC6/cy_watchdog_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_M451/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_M480/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/watchdog_api.c
  targets/TARGET_NXP/TARGET_LPC176X/watchdog_api.c
  targets/TARGET_ONSEMI/TARGET_NCS36510/watchdog_api.c
  targets/TARGET_STM/watchdog_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/watchdog_api.c
Labels: ready for merge, release-version:6.0.0-rc1

#11770 Update CM0P pre-built images to build 1.0.0.35
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_BLESS/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_BLESS/psoc6_cm0p_bless.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_01_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_02_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_03_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_01_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_02_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_03_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/TARGET_CM0P_SLEEP/psoc6_01_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/TARGET_CM0P_SLEEP/psoc6_02_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/version.xml
Labels: devices: cypress, ready for merge, release-version: 5.14.2

#11763 Display full path of generated coverage output from unittests.
  UNITTESTS/unit_test/coverage.py
Labels: ready for merge, release-version: 5.14.2

#11777 IOTBTOOL-377: Fix scatter file include path online
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.14.2

#11785 Deprecates NVStore
  features/storage/nvstore/source/nvstore.h
Labels: ready for merge, release-version: 5.15.0-rc1

#11776 Fix for issue #11769 (Cypress: PWM FPGA test wrong assert)
  targets/TARGET_Cypress/TARGET_PSOC6/cy_pwmout_api.c
Labels: devices: cypress, ready for merge, release-version: 5.14.2

#11687 Update to Mbed TLS 2.20.0d0 and Mbed Crypto 2.1.0d0
  features/mbedtls/VERSION.txt
  features/mbedtls/importer/Makefile
  features/mbedtls/inc/mbedtls/check_config.h
  features/mbedtls/inc/mbedtls/config.h
  features/mbedtls/inc/mbedtls/version.h
  features/mbedtls/mbed-crypto/VERSION.txt
  features/mbedtls/mbed-crypto/importer/Makefile
  features/mbedtls/mbed-crypto/inc/mbedtls/asn1.h
  features/mbedtls/mbed-crypto/inc/mbedtls/asn1write.h
  features/mbedtls/mbed-crypto/inc/mbedtls/ctr_drbg.h
  features/mbedtls/mbed-crypto/inc/mbedtls/hmac_drbg.h
  features/mbedtls/mbed-crypto/inc/mbedtls/md_internal.h
  features/mbedtls/mbed-crypto/inc/psa/crypto.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_extra.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_se_driver.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_types.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_values.h
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/COMPONENT_NSPE/crypto_struct.h
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto.c
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_se.c
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_se.h
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_slot_management.c
  features/mbedtls/mbed-crypto/platform/COMPONENT_SPE/crypto_struct_spe.h
  features/mbedtls/mbed-crypto/src/asn1parse.c
  features/mbedtls/mbed-crypto/src/asn1write.c
  features/mbedtls/mbed-crypto/src/ecp_curves.c
  features/mbedtls/mbed-crypto/src/md.c
  features/mbedtls/mbed-crypto/src/md_wrap.c
  features/mbedtls/mbed-crypto/src/pkcs5.c
  features/mbedtls/src/error.c
  features/mbedtls/src/ssl_tls.c
Labels: BREAKING-CHANGE, ready for merge, release-version:6.0.0-rc1
