Repository ARMmbed/mbed-os, pull requests merged in 2019-04, with the labels that each got.

#10240 Add Python modules to LICENSE file
  LICENSE.md
Labels: ready for merge, release-version: 5.12.1

#10271 SPI defined/undefined behavior update
  docs/design-documents/hal/0000-spi-overhaul.md
Labels: ready for merge, release-version: feature branch

#10270 BLE SimpleAdvertisingBuilder moved functions out of mbed_assert calls
  features/FEATURE_BLE/ble/gap/AdvertisingDataSimpleBuilder.h
Labels: ready for merge, release-version: 5.12.1

#10171 Fix QSPIF Bus mode mask and quad enable write SR size
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
Labels: ready for merge, release-version: 5.12.1

#10275 Updated AWS url for astyle.
  .travis.yml
Labels: ready for merge, release-version: 5.12.1

#10056 Cellular: retry logic for CellularContext connect
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  UNITTESTS/stubs/CellularContext_stub.cpp
  UNITTESTS/stubs/CellularStateMachine_stub.cpp
  UNITTESTS/target_h/myCellularContext.h
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/common/CellularCommon.h
  features/cellular/framework/device/CellularContext.cpp
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
Labels: ready for merge, release-version: 5.12.1

#10280 Remove CFSTORE VERSION file (colliding with an ARM 6.12 C++ header file)
  features/storage/FEATURE_STORAGE/cfstore/VERSION
Labels: ready for merge, release-version: 5.12.1

#10281 Adding support for S2_LP (WiSUN) as a new MTB target
  components/802.15.4_RF/stm-s2lp-rf-driver/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_MTB_STM_S2LP/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_MTB_STM_S2LP/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_MTB_STM_S2LP/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_MTB_STM_S2LP/system_clock.c
  targets/targets.json
Labels: ready for merge, release-version: 5.12.1

#10248 TARGET_STM32F7: Refresh cache when erasing or programming flash
  targets/TARGET_STM/TARGET_STM32F7/flash_api.c
Labels: ready for merge, release-version: 5.12.1

#10276 Parse Errors and Warnings from Arm Compiler 6
  tools/toolchains/arm.py
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 5.12.1

#9111 CAN: Fix signness mismatch in `CANMessage` constructors
  drivers/CAN.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10246 LPC55S69: Update Flash driver to set clock frequency
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/flash_api.c
Labels: ready for merge, release-version: 5.12.1

#10229 Cellular: Power ON Wait Increased for C030_U201
  features/cellular/TESTS/api/cellular_device/main.cpp
Labels: ready for merge, release-version: 5.12.1

#10143 STM32 ADC INTERNAL CHANNEL reset after read
  targets/TARGET_STM/TARGET_STM32F0/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F1/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_adc.h
  targets/TARGET_STM/TARGET_STM32F2/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_adc.h
  targets/TARGET_STM/TARGET_STM32F3/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F4/analogin_device.c
  targets/TARGET_STM/TARGET_STM32F7/analogin_device.c
  targets/TARGET_STM/TARGET_STM32H7/analogin_device.c
  targets/TARGET_STM/TARGET_STM32L0/analogin_device.c
  targets/TARGET_STM/TARGET_STM32L1/analogin_device.c
  targets/TARGET_STM/TARGET_STM32L4/analogin_device.c
Labels: ready for merge, release-version: 5.12.1

#10290 README link to license guide 404s
  README.md
Labels: ready for merge, release-version: 5.12.1

#10289 PSOC6: Rebuild WICED libraries
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_CY8CKIT_062_4343W/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_CY8CKIT_062_WIFI_BT/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_CY8CMOD_062_4343W/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARM/TARGET_CYW943012P6EVB_01/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_CY8CKIT_062_4343W/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_CY8CKIT_062_WIFI_BT/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_CY8CMOD_062_4343W/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_CYW943012P6EVB_01/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_CY8CKIT_062_4343W/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_CY8CKIT_062_WIFI_BT/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_CY8CMOD_062_4343W/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_CYW943012P6EVB_01/libwiced_drivers.a
Labels: ready for merge, release-version: 5.12.1

#10291 FUTURE_SEQUANA: Fixed LP ticker for M0 core
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/lp_ticker.c
Labels: ready for merge, release-version: 5.12.1

#10121 Cellular: Improve ATHandler AT debug traces
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
Labels: ready for merge, release-version: 5.12.1

#10267 PSOC6: Modify lp_ticker to 32 bit
  targets/TARGET_Cypress/TARGET_PSOC6/lp_ticker.c
Labels: ready for merge, release-version: 5.12.1

#10269 cellular: valgrind defect fix
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/at_cellulardevicetest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/at_cellularsmstest.cpp
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/ATHandler_stub.h
Labels: ready for merge, release-version: 5.12.1

#10294 NUCLEO_L4R5ZI_P: enable sw4stm32 export
  tools/export/sw4stm32/__init__.py
Labels: ready for merge, release-version: 5.12.1

#10296 Build script: add explicit console log in case of linker script error
  tools/build_api.py
Labels: ready for merge, release-version: 5.12.1

#10302 BLE: force mandatory services to have lowest handles
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioGattServer.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
Labels: ready for merge, release-version: 5.12.1

#10288 Revert limiting Renesas targets to ARMC6
  targets/targets.json
Labels: ready for merge, release-version: 5.12.1

#10282 Nuvoton: Support export IAR8 project
  tools/export/iar/__init__.py
  tools/export/iar/ewp.tmpl
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.12.1

#10304 equeue: align passed-in buffer
  events/equeue/equeue.c
Labels: ready for merge, release-version: 5.12.1

#10295 eclipse_gcc_arm export improvement
  tools/export/cdt/__init__.py
  tools/export/cdt/cdt_definitions.json
Labels: ready for merge, release-version: 5.12.1

#10317 Fix for DigitalOut(NC) instantiation for all Toshiba targets
  targets/TARGET_TOSHIBA/TARGET_TMPM066/gpio_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3H6/gpio_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/gpio_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/gpio_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/gpio_api.c
Labels: ready for merge, release-version: 5.12.1

#10299 MIMXRT1050: Fix ENET issues
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_IMX/imx_emac.cpp
Labels: ready for merge, release-version: 5.12.1

#10020 Fix single-threaded apps for IAR v8 builds
  rtos/TARGET_CORTEX/TOOLCHAIN_IAR/mbed_boot_iar.c
Labels: ready for merge

#9981 test_soap_connection_handler leaks memory when open_connection fails
  features/nanostack/coap-service/test/coap-service/unittest/coap_connection_handler/test_coap_connection_handler.c
Labels: ready for merge, release-version: 5.12.2

#10124 Enable low-power ticker and Sleep for FastModels
  TESTS/mbed_drivers/lp_timeout/main.cpp
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/lp_ticker.c
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/sleep_api.c
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/us_ticker.c
  targets/targets.json
Labels: ready for merge, release-version: 5.12.2

#10343 TARGET_STM32F7: Reset QSPI in default mode on abort for all versions.
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/stm32f746xx.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/device/stm32f756xx.h
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_qspi.c
Labels: ready for merge, release-version: 5.12.2

#10340 BLE: fix missing implementation call
  features/FEATURE_BLE/source/GattClient.tpp
Labels: ready for merge, release-version: 5.12.2

#10338 Cellular: Fix deleting of state machine to correct class
  UNITTESTS/features/cellular/framework/device/cellularstatemachine/cellularstatemachinetest.cpp
  UNITTESTS/stubs/CellularStateMachine_stub.cpp
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
Labels: ready for merge, release-version: 5.12.2

#10335 PSA release.py - Check that required toolchains are in PATH
  tools/psa/release.py
Labels: ready for merge, release-version: 5.12.2

#10333 Allow toolchain paths to be wrapped in quotes
  tools/settings.py
Labels: ready for merge, release-version: 5.12.2

#10332 Break up large prints from --supported
  tools/make.py
Labels: ready for merge, release-version: 5.12.2

#10330 Reduce greentea socket tests failures related to network issues
  TESTS/netsocket/README.md
  TESTS/netsocket/tls/tlssocket_recv_timeout.cpp
  TESTS/netsocket/udp/udpsocket_recv_timeout.cpp
Labels: ready for merge, release-version: 5.12.2

#10318 Crash with MTB_MXCHIP_EMW3166 has been corrected.
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
Labels: ready for merge, release-version: 5.12.2

#10301 examples test compile optional verbose
  tools/test/examples/examples.py
  tools/test/examples/examples_lib.py
Labels: ready for merge, release-version: 5.12.2

#10254 Remove unused tools modules and document the used ones.
  tools/README.md
  tools/build_travis.py
  tools/check_release.json
  tools/check_release.py
  tools/compliance/__init__.py
  tools/compliance/ioper_base.py
  tools/compliance/ioper_runner.py
  tools/compliance/ioper_test_fs.py
  tools/compliance/ioper_test_target_id.py
  tools/data/__init__.py
  tools/data/rpc/RPCClasses.h
  tools/data/rpc/class.cpp
  tools/data/support.py
  tools/dev/__init__.py
  tools/dev/dsp_fir.py
  tools/dev/intel_hex_utils.py
  tools/dev/rpc_classes.py
  tools/dev/syms.py
  tools/git_hooks/__init__.py
  tools/libraries.py
  tools/misc/find_c_includes.py
  tools/misc/remove-device-h.py
  tools/singletest.py
  tools/size.py
  tools/synch.py
  tools/test_api.py
  tools/test_db.py
  tools/test_mysql.py
  tools/test_webapi.py
  tools/tests.py
  tools/upload_results.py
Labels: ready for merge, release-version: 5.13.0-rc1

#9967 Fix for projects exported as a zip file (affects online compiler)
  tools/export/__init__.py
  tools/export/exporters.py
  tools/export/makefile/__init__.py
  tools/export/vscode/__init__.py
  tools/export/vscode/c_cpp_properties.tmpl
  tools/resources/__init__.py
  tools/test/config/config_test.py
Labels: ready for merge, release-version: 5.12.2

#10324 Cellular: new state machine state and better info from stm
  UNITTESTS/features/cellular/framework/device/cellulardevice/cellulardevicetest.cpp
  UNITTESTS/features/cellular/framework/device/cellularstatemachine/cellularstatemachinetest.cpp
  UNITTESTS/stubs/CellularStateMachine_stub.h
  UNITTESTS/target_h/myCellularDevice.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/common/CellularCommon.h
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
Labels: ready for merge, release-version: 5.12.2

#10341 Cellular: Check for URC during AT response stop
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
Labels: ready for merge, release-version: 5.12.2

#10354 Cellular: Using new rather than malloc in debug_print
  features/cellular/framework/AT/ATHandler.cpp
Labels: ready for merge, release-version: 5.12.2

#10292 Cellular: Basic driver for Quectel EC25/EC21
  features/cellular/framework/targets/QUECTEL/EC2X/QUECTEL_EC2X.cpp
  features/cellular/framework/targets/QUECTEL/EC2X/QUECTEL_EC2X.h
  features/cellular/framework/targets/QUECTEL/EC2X/mbed_lib.json
Labels: ready for merge, release-version: 5.12.2

#9966 tools: fix the path generated to the sct file
  tools/export/makefile/__init__.py
  tools/export/uvision/__init__.py
  tools/resources/__init__.py
  tools/test/resources/resource_test.py
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 5.12.2

#10004 M2351: Support memory custom partition
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_ARMC6/M2351.sct
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_ARM_STD/M2351.sct
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_GCC_ARM/M2351.ld
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_IAR/M2351.icf
  targets/TARGET_NUVOTON/TARGET_M2351/device/partition_M2351.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/partition_M2351_mem.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/partition_M2351_mem.icf
  targets/TARGET_NUVOTON/TARGET_M2351/flash_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.12.2

#10350 Fix doxygen comment in USBDevice
  usb/device/USBPhy/USBPhy.h
Labels: ready for merge, release-version: 5.12.2

#10328 Add option to disable default UART console
  platform/mbed_lib.json
  platform/mbed_retarget.cpp
  targets/targets.json
Labels: ready for merge, release-version: 5.13.0-rc1

#10348 Parse M33 + GCC_ARM map files
  tools/memap.py
Labels: needs: CI, release-version: 5.12.2

#10347 Fix detection of supported targets for mbed 2 builds
  targets/targets.json
  tools/build.py
  tools/build_api.py
Labels: ready for merge, release-version: 5.12.2

#10268 PSoC6 serial driver: Setup RTS and TX lines on deepsleep entry/exit
  targets/TARGET_Cypress/TARGET_PSOC6/serial_api.c
Labels: ready for merge, release-version: 5.12.2

#10286 PSA: TFM import from master branch
  components/TARGET_PSA/TARGET_TFM/COMPONENT_NSPE/interface/src/tfm_ns_lock_rtx.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/bl2/include/boot_record.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/bl2/include/tfm_boot_status.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/dir_core.dox
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/include/tfm_message_queue.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/include/tfm_spm.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/include/tfm_svcalls.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/include/tfm_wait.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_arch_v8m.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_pools.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_spm.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_svcalls.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_thread.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_wait.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/secure_utilities.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_boot_data.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_handler.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_memory_utils.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_secure_api.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_secure_api.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_spm_services.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/include/dir_include.dox
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/dir_spm.dox
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_api.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_api.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_db.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_db_setup.h
  components/TARGET_PSA/TARGET_TFM/interface/include/psa_client.h
  components/TARGET_PSA/TARGET_TFM/interface/include/psa_service.h
  components/TARGET_PSA/TARGET_TFM/interface/include/tfm_api.h
  tools/importer/tfm_importer.json
Labels: ready for merge, release-version: 5.12.2

#10363 Flagging WEAK method implementation for default construction
  features/cellular/framework/targets/QUECTEL/EC2X/QUECTEL_EC2X.cpp
Labels: ready for merge, release-version: 5.12.2

#10232 PSA Crypto Service - multipart operation memory fixes
  components/TARGET_PSA/services/crypto/COMPONENT_PSA_SRV_IPC/psa_crypto_spm.c
  components/TARGET_PSA/services/crypto/COMPONENT_SPE/psa_crypto_partition.c
Labels: ready for merge, release-version: 5.12.2

#10368 FUTURE_SEQUANA_PSA fix PSA Protected storage
  features/storage/kvstore/conf/global/mbed_lib.json
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
Labels: ready for merge, release-version: 5.12.2

#10369 L3IP interface input handler change.
  features/lwipstack/LWIPInterface.cpp
Labels: ready for merge, release-version: 5.12.2

#10225 Mail/MemoryPool: blocking alloc
  TESTS/mbedmicro-rtos-mbed/MemoryPool/main.cpp
  rtos/Mail.h
  rtos/MemoryPool.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10021 Enable post build bootloader merging in uvision
  tools/export/__init__.py
  tools/export/exporters.py
  tools/export/uvision/__init__.py
  tools/export/uvision/debug_init.ini
  tools/export/uvision/export_info.tmpl
  tools/export/uvision/flash_init.ini
  tools/export/uvision/postbuild.py
  tools/export/uvision/uvision.tmpl
  tools/export/uvision/uvision_debug.tmpl
  tools/regions.py
  tools/test/build_api/build_api_test.py
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 5.13.0-rc1

#10364 Refactor PSA code generators
  tools/psa/README.md
  tools/psa/generate_mbed_spm_partition_code.py
  tools/psa/generate_partition_code.py
  tools/psa/generate_tfm_partition_code.py
  tools/psa/mbed_spm/mbed_spm_generated_file_list.json
  tools/psa/mbed_spm_tfm_common.py
  tools/test/spm/test_generate_partition_code.py
Labels: ready for merge, release-version: 5.13.0-rc1

#10376 LPC55S69: Fix APB bridge security programming
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_S/target_cfg.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/flash_api.c
Labels: ready for merge, release-version: 5.12.2

#10349 Fix crash capture feature for nuvoton
  platform/mbed_crash_data_offsets.h
  platform/mbed_lib.json
  targets/TARGET_NUVOTON/TARGET_M480/device/TOOLCHAIN_IAR/M487.icf
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_ARM_MICRO/TARGET_NU_XRAM_SUPPORTED/NUC472.sct
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_ARM_STD/TARGET_NU_XRAM_SUPPORTED/NUC472.sct
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_GCC_ARM/TARGET_NU_XRAM_SUPPORTED/NUC472.ld
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_IAR/TARGET_NU_XRAM_SUPPORTED/NUC472_442.icf
Labels: ready for merge, release-version: 5.12.2

#10257 Correct Python 3 errors and lint warnings in build_release.py
  tools/build_release.py
Labels: ready for merge, release-version: 5.12.2

#9844 Travis CI: Stages, OS update, apt-get relief!
  .travis.yml
  features/storage/filesystem/littlefs/littlefs/tests/stats.py
  tools/test/travis-ci/functions.sh
Labels: needs: CI, release-version: 5.12.2

#10380 Nordic QSPI data must be written from/read to aligned buffers in RAM
  targets/TARGET_NORDIC/TARGET_NRF5x/qspi_api.c
Labels: ready for merge, release-version: 5.12.2

#10378 STM32: protect compilation when DEVICE_USTICKER is disabled
  targets/TARGET_STM/hal_tick_overrides.c
  targets/TARGET_STM/us_ticker.c
Labels: ready for merge, release-version: 5.12.2

#10393 approcah -> approach
  docs/design-documents/features/storage/TDBStore/TDBStore_design.md
Labels: ready for merge, release-version: 5.12.2

#8919 Add one board Green Tea SPI Communication Test
  TESTS/mbed_hal/spi_com/README.md
  TESTS/mbed_hal/spi_com/com_test.png
  TESTS/mbed_hal/spi_com/main.cpp
  TESTS/mbed_hal/spi_com/spi_com_test.h
  TESTS/mbed_hal/spi_com/spi_ob_wire_connection.png
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PinNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/spi_api.c
  targets/targets.json
  tools/test/examples/examples.json
Labels: ready for merge, release-version: feature branch

#10053 Cellular: Make CellularStateMachine timeouts configurable
  UNITTESTS/stubs/CellularStateMachine_stub.cpp
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/device/CellularContext.cpp
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
Labels: ready for merge, release-version: 5.13.0-rc1

#10395 mbed_error: Avoid negative left shift
  platform/mbed_error.h
Labels: ready for merge, release-version: 5.12.2

#10384 Toshiba: Cortex-M4 -> Cortex-M4F
  targets/targets.json
Labels: ready for merge, release-version: 5.12.2

#10381 ECHOTEST internal loop simplification and fix
  TESTS/netsocket/tcp/tcpsocket_echotest.cpp
  TESTS/netsocket/tls/tlssocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_echotest.cpp
Labels: ready for merge, release-version: 5.12.2

#10334 MXRT1050_EVK: Fixes test failure seen with ARM & IAR toolchain
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_ARM_STD/MIMXRT1052xxxxx.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_IAR/MIMXRT1052xxxxx.icf
Labels: ready for merge, release-version: 5.12.2

#10391 Update the writing example in unit testing README
  UNITTESTS/README.md
Labels: ready for merge, release-version: 5.12.2

#10385 README file for wifi tests gives configuration example
  TESTS/network/wifi/README.md
Labels: ready for merge, release-version: 5.12.2

#9870 Re-enable MPS2 platform
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0/device/TOOLCHAIN_ARM_STD/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0/device/TOOLCHAIN_GCC_ARM/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0/device/TOOLCHAIN_IAR/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0P/device/CMSDK_CM0plus.h
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0P/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0P/device/TOOLCHAIN_ARM_STD/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0P/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0P/device/TOOLCHAIN_GCC_ARM/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0P/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0P/device/TOOLCHAIN_IAR/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M3/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M3/device/TOOLCHAIN_ARM_STD/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M3/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M3/device/TOOLCHAIN_GCC_ARM/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M3/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M3/device/TOOLCHAIN_IAR/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M4/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M4/device/TOOLCHAIN_ARM_STD/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M4/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M4/device/TOOLCHAIN_GCC_ARM/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M4/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M4/device/TOOLCHAIN_IAR/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M7/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M7/device/TOOLCHAIN_ARM_STD/startup_CMSDK_CM7.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M7/device/TOOLCHAIN_GCC_ARM/MPS2.ld
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M7/device/TOOLCHAIN_GCC_ARM/startup_MPS2.S
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M7/device/TOOLCHAIN_IAR/MPS2.icf
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M7/device/TOOLCHAIN_IAR/startup_MPS2.S
  targets/TARGET_ARM_SSG/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, scope: new-target

#10358 Error print improvements
  drivers/UARTSerial.cpp
  platform/mbed_assert.c
  platform/mbed_board.c
  platform/mbed_error.c
  platform/mbed_error.h
  platform/mbed_interface.h
  rtos/Mutex.cpp
  rtos/TARGET_CORTEX/mbed_rtx_handlers.c
Labels: ready for merge, release-version: 5.12.2

#10383 GigaDevice: Cortex-M4 -> Cortex-M4F
  targets/targets.json
Labels: ready for merge, release-version: 5.12.2

#10414 ExhaustibleBD: licensed under Apache 2.0
  features/storage/blockdevice/ExhaustibleBlockDevice.h
Labels: ready for merge, release-version: 5.12.2

#10375 Cellular: Fix to delete PDP context on disconnect
  features/cellular/framework/AT/AT_CellularContext.cpp
Labels: ready for merge, release-version: 5.12.2

#10382 SDP_K1: Cortex-M4 -> Cortex-M4F
  targets/targets.json
Labels: ready for merge, release-version: 5.12.2

#10415 rtos/drivers: add license information
  drivers/LICENSE-mit.txt
  drivers/LICENSE.md
  rtos/LICENSE-mit.txt
  rtos/LICENSE.md
Labels: ready for merge, release-version: 5.12.2

#10096 Add USB HID tests
  LICENSE.md
  TESTS/host_tests/usb_device_hid.py
  TESTS/usb_device/hid/README.md
  TESTS/usb_device/hid/main.cpp
  TESTS/usb_device/hid/requirements.txt
  requirements.txt
  usb/device/USBHID/USBHID.cpp
Labels: ready for merge, release-version: 5.12.2

#10419 FUTURE_SEQUANA: Clean up "unused variable" compiler warnings
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/device/drivers/include/cy_ctdac.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/device/drivers/include/cy_gpio.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/device/drivers/include/cy_ipc_drv.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/device/drivers/include/cy_sar.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/device/drivers/include/cy_scb_common.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/device/drivers/include/cy_sysclk.h
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/device/drivers/include/cy_tcpwm.h
Labels: ready for merge, release-version: 5.12.2

#10421 Update Jinja2 for CVE-2019-10906 fix
  requirements.txt
Labels: ready for merge, release-version: 5.12.2

#10367 Increase background stack size to fix overflows with debug profile
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
  rtos/mbed_lib.json
Labels: ready for merge, release-version: 5.12.2

#10420 Updated mbed-cloud-sdk to 2.0.6
  requirements.txt
Labels: ready for merge, release-version: 5.12.2

#10418 CordioGattServer: reset settings variable before ANDing the properties to it
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
Labels: ready for merge, release-version: 5.12.2

#10417 suppress coverity error
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack_adaptation/wsf_os.c
Labels: ready for merge, release-version: 5.12.2

#10407 Fix warnings on PSA secure builds
  TESTS/psa/spm_client/COMPONENT_NSPE/main.cpp
  TESTS/psa/spm_server/COMPONENT_NSPE/main.cpp
  TESTS/psa/spm_smoke/COMPONENT_NSPE/main.cpp
  components/TARGET_PSA/inc/psa/service.h
  components/TARGET_PSA/services/attestation/COMPONENT_PSA_SRV_IMPL/attest_iat_claims_loader.c
  components/TARGET_PSA/services/attestation/COMPONENT_SPE/psa_attestation_partition.c
  components/TARGET_PSA/services/storage/its/COMPONENT_SPE/its_partition.c
Labels: ready for merge, release-version: 5.12.2

#10412 FUTURE_SEQUANA: Fix flash_api bug introduced with e16d2d81d9
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/flash_api.c
Labels: ready for merge, release-version: 5.12.2

#10377 Fix ESP8266 driver behavior on connection failures
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
Labels: ready for merge, release-version: 5.12.2

#10314 i.MX RT1050: Reactivate data cache
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_IMX/imx_emac.cpp
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/mbed_overrides.c
  targets/targets.json
Labels: ready for merge, release-version: 5.12.2

#10019 uARM - Move heap region after IRAM1
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_ARM_MICRO/TARGET_LPC11U24_301/LPC11U24.sct
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_ARM_MICRO/TARGET_LPC11U24_401/LPC11U24.sct
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_ARM_MICRO/TARGET_LPC11U34_421/LPC11U34.sct
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_ARM_MICRO/TARGET_LPC11U35_401/LPC11U35.sct
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_ARM_MICRO/TARGET_LPC11U37H_401/LPC11U37.sct
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_ARM_MICRO/TARGET_LPC11U37_501/LPC11U37.sct
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_ARM_MICRO/TARGET_MCU_LPC11U35_501/LPC11U35.sct
  targets/TARGET_NXP/TARGET_LPC11UXX/device/TOOLCHAIN_ARM_MICRO/TARGET_OC_MBUINO/LPC11U24.sct
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/TOOLCHAIN_ARM_MICRO/TARGET_LPC11CXX/LPC11C24.sct
  targets/TARGET_NXP/TARGET_LPC13XX/device/TOOLCHAIN_ARM_MICRO/LPC1347.sct
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_ARM_MICRO/LPC1768.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xG/device/TOOLCHAIN_ARM_MICRO/STM32F407xx.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/device/TOOLCHAIN_ARM_MICRO/stm32f439xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/TOOLCHAIN_ARM_MICRO/stm32l471xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_ARM_MICRO/stm32l475xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_ARM_MICRO/stm32l476xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_ARM_MICRO/stm32l486xx.sct
Labels: ready for merge, release-version: 5.12.2

#10394 Networking: Fix some ARMC6 warnings
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  features/lwipstack/LWIPStack.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  features/nanostack/mbed-mesh-api/source/LoWPANNDInterface.cpp
  features/nanostack/mbed-mesh-api/source/ThreadInterface.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/mbed-mesh-api/source/nd_tasklet.c
  features/nanostack/mbed-mesh-api/source/thread_tasklet.c
Labels: ready for merge, release-version: 5.12.2

#10406 Modify CMSIS pack manager to properly handle OSError
  tools/arm_pack_manager/__init__.py
Labels: ready for merge, release-version: 5.12.2

#10386 ARM MPS2: Cortex-M4 -> M4F & M7 -> M7FD
  targets/targets.json
Labels: ready for merge, release-version: 5.12.2

#10387 Atmel SAMG55: Cortex-M4 -> Cortex-M4F
  targets/targets.json
Labels: ready for merge, release-version: 5.12.2

#10408 Update comments and improve readability for the BusInOut class
  drivers/BusInOut.h
Labels: ready for merge, release-version: 5.12.2

#10411 Cellular: Added BG96 handling for socket closing URC
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
Labels: ready for merge, release-version: 5.12.2

#10018 STM: Update linker script for using SRAM1 and SRAM2 in ARM
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L443xC/device/TOOLCHAIN_ARM_STD/stm32l443xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_ARM_STD/stm32l475xx.sct
  targets/TARGET_STM/mbed_rtx.h
Labels: ready for merge, release-version: 5.12.3

#10078 Fix heap init error in rtos-less code
  platform/mbed_retarget.cpp
Labels: ready for merge, release-version: 5.12.3

#10322 GCC: remove `-fno-builtin` option
  tools/export/kds/hexiwear_cproject.tmpl
  tools/export/kds/k22f_cproject.tmpl
  tools/export/kds/k64f_cproject.tmpl
  tools/export/lpcxpresso/lpc4088_cproject.tmpl
  tools/export/lpcxpresso/lpc4088_dm_cproject.tmpl
  tools/export/lpcxpresso/lpc4330_m4_cproject.tmpl
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge, release-version: 5.13.0-rc1

#10390 Correct some CPU selections in tools
  targets/targets.json
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
Labels: ready for merge, release-version: 5.12.3

#10410 Nanostack: translate errors from sendmsg
  features/nanostack/nanostack-interface/Nanostack.cpp
Labels: ready for merge, release-version: 5.13.0-rc1

#10426 UDPSOCKET_ECHOTEST fails if a packet of every size was not sent
  TESTS/netsocket/README.md
  TESTS/netsocket/udp/udpsocket_echotest.cpp
Labels: ready for merge, release-version: 5.12.3

#10434 Nanostack network handle does not always call status cb for BOOTSTRAP events
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
Labels: ready for merge, release-version: 5.12.3

#10436 NUC472: Workaround for unknown error with power-down
  targets/TARGET_NUVOTON/TARGET_NUC472/sleep.c
  targets/TARGET_NUVOTON/TARGET_NUC472/us_ticker.c
Labels: ready for merge, release-version: 5.12.3

#10438 PSA: Pass TFM_LVL macro to linker files
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 5.12.3

#10451 MIMXRT1050: Readd IAR support
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.12.3

#10453 Cellular: Minor doc update for CellualrSocket object
  features/cellular/framework/AT/AT_CellularStack.h
Labels: ready for merge, release-version: 5.12.3

#10461 Update wifi driver for rda target UNO_91H
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/RdaWiFiInterface.cpp
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/csl_mbed.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/inc/rda5991h_wland.h
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/lib/TOOLCHAIN_ARM_STD/libwifi_sta_ap.ar
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/lib/TOOLCHAIN_GCC_ARM/libwifi_sta_ap.a
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/lib/TOOLCHAIN_IAR/libwifi_sta_ap.a
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/src/maclib_task.c
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/src/rda5991h_wland.c
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/src/rda_sys_wrapper.c
  features/netsocket/emac-drivers/TARGET_RDA_EMAC/rda5981x_emac.cpp
Labels: ready for merge, release-version: 5.12.3

#10462 Nanostack: release connect_semaphore only when it is pending
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
Labels: ready for merge, release-version: 5.12.3

#10475 Implement nanostack eventloop tick timer
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_hal_init.c
Labels: ready for merge, release-version: 5.13.0-rc1

#10402 Cellular: send disconnect to correct ctx
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/AT_CellularNetwork_stub.cpp
  UNITTESTS/stubs/CellularContext_stub.cpp
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/AT_CellularBase.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/device/CellularContext.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
Labels: ready for merge, release-version: 5.12.3

#10490 Cellular: Added UT for case when read_string buff size hits middle of…
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
Labels: ready for merge, release-version: 5.12.3

#10398 Clean up ARM toolchains from get_mbed_official_release()
  tools/build_api.py
Labels: ready for merge, release-version: 5.13.0-rc1

#10303 STM32L4xx: IAR memory maps updated
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_IAR/stm32l475xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_IAR/stm32l476xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_IAR/stm32l486xx.icf
Labels: ready for merge, release-version: 5.12.3

#10502 PSA: TFM import
  components/TARGET_PSA/TARGET_TFM/COMPONENT_NSPE/interface/src/tfm_ns_lock_rtx.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/bl2/include/tfm_boot_status.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/include/tfm_spm.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/psa_client.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/psa_service.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_arch_v8m.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_spm.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_svcalls.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/secure_utilities.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_boot_data.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_core.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_core.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_handler.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_internal.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_nspm.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_psa_api_client.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_secure_api.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_secure_api.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_spm_services.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_svc.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_api.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_api.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_db.h
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/spm/spm_db_setup.h
  components/TARGET_PSA/TARGET_TFM/interface/include/tfm_ns_lock.h
  components/TARGET_PSA/TARGET_TFM/interface/include/tfm_ns_svc.h
  tools/importer/tfm_importer.json
Labels: ready for merge, release-version: 5.12.3

#10443 Fix for downloading the wrong binary in the online compiler
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 5.12.3

#10492 Remove sleep lock/unlock from Silicon Labs HAL implementation
  targets/TARGET_Silicon_Labs/TARGET_EFM32/i2c_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/spi_api.c
Labels: ready for merge, release-version: 5.12.3

#10488 Cellular: Add description for CellularProperty
  features/cellular/framework/AT/AT_CellularBase.h
Labels: ready for merge, release-version: 5.12.3

#10477 Wi-SUN: adds greentea test config
  tools/test_configs/Wi-SUNInterface.json
Labels: ready for merge, release-version: 5.12.3

#10474 fix usb msd test python dependencies
  LICENSE.md
  requirements.txt
Labels: ready for merge, release-version: 5.12.3

#10448 Size should be calculate after confirm the final start address
  tools/config/__init__.py
Labels: ready for merge, release-version: 5.12.3

#9944 GCC - Add support to split heap across 2-RAM banks
  TESTS/mbedmicro-rtos-mbed/heap_and_stack/main.cpp
  TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
  platform/mbed_retarget.cpp
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/device/TOOLCHAIN_GCC_ARM/STM32L471XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L443xC/device/TOOLCHAIN_GCC_ARM/STM32L443XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_GCC_ARM/STM32L475XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_GCC_ARM/STM32L476XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_GCC_ARM/STM32L486XX.ld
  targets/targets.json
Labels: ready for merge, release-version: 5.13.0-rc1

#10507 PSA: mbedSPM correct SPM initialization order
  rtos/TARGET_CORTEX/mbed_rtos_rtx.c
Labels: ready for merge, release-version: 5.12.3

#10506 Add missing ADC pins mapping for FRMD-K66F (#10498)
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/TARGET_FRDM/PeripheralPins.c
Labels: ready for merge, release-version: 5.12.3

#10472 Fix USB control transfers using small size
  usb/device/USBDevice/USBDevice.cpp
Labels: ready for merge, release-version: 5.12.3

#10401 NUC472: Support crash capture for no-XRAM configuration
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_ARM_MICRO/TARGET_NU_XRAM_UNSUPPORTED/NUC472.sct
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_ARM_STD/TARGET_NU_XRAM_UNSUPPORTED/NUC472.sct
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_GCC_ARM/TARGET_NU_XRAM_UNSUPPORTED/NUC472.ld
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_IAR/TARGET_NU_XRAM_UNSUPPORTED/NUC472_442.icf
Labels: ready for merge, release-version: 5.12.3
