Repository ARMmbed/mbed-os, pull requests merged in 2019-06, with the labels that each got.

#10501 Remove excessive info and debug prints in SPIF driver
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
Labels: ready for merge, release-version: 5.13.1

#10697 STM32H7: flash issue while erasing sector in Bank 1
  targets/TARGET_STM/TARGET_STM32H7/flash_api.c
Labels: ready for merge, release-version: 5.13.1

#10588 Cell bg96 power
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.h
  features/cellular/framework/targets/QUECTEL/BG96/mbed_lib.json
Labels: ready for merge, release-version: 5.13.1

#10647 Fix LWIP warning issues found by Coverity scan
  features/lwipstack/lwip/src/api/lwip_api_msg.c
  features/lwipstack/lwip/src/core/ipv4/lwip_ip4_frag.c
  features/lwipstack/lwip/src/core/lwip_dns.c
Labels: ready for merge, release-version: 5.13.1

#10660 Add SCLK and SIN stats to SPIMasterTester
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/SPIMasterTester.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/SPIMasterTester.h
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/fpga_config.h
Labels: ready for merge, release-version: 5.14.0-rc1

#10696 Cellular: Fix socket connect on UBLOX_AT driver
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
Labels: ready for merge, release-version: 5.13.1

#10683 Export wait_ns to be overridable
  platform/mbed_wait_api_no_rtos.c
Labels: ready for merge, release-version: 5.14.0-rc1

#10716 Update requirement for manifest-tool
  requirements.txt
Labels: ready for merge, release-version: 5.13.0-rc2

#10722 mbed-crypto: Automatically enable entropy injection
  features/mbedtls/platform/inc/platform_mbed.h
Labels: ready for merge, release-version: 5.13.0-rc2

#10747 Cypress: Fix issue #10613
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_4343W/device/TOOLCHAIN_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/device/TOOLCHAIN_ARM/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/device/TARGET_MCU_PSOC6_M0/TOOLCHAIN_ARM/startup_psoc6_01_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/device/TARGET_MCU_PSOC6_M4/TOOLCHAIN_ARM/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062_4343W/device/TOOLCHAIN_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/device/TARGET_MCU_PSOC6_M0/TOOLCHAIN_ARM/startup_psoc6_01_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/device/TARGET_MCU_PSOC6_M4/TOOLCHAIN_ARM/startup_psoc6_01_cm4.S
Labels: ready for merge, release-version: 5.13.0-rc2

#10698 timeout_tests: do not call sleep from test thread
  TESTS/mbed_drivers/timeout/timeout_tests.h
Labels: ready for merge, release-version: 5.13.1

#10740 ARMC6: Suppress "register deprecated" warning
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge, release-version: 5.13.0-rc2

#10654 USBHostMSD: Implement BlockDevice get_type()
  features/unsupported/USBHost/USBHostMSD/USBHostMSD.cpp
  features/unsupported/USBHost/USBHostMSD/USBHostMSD.h
Labels: ready for merge

#10733 Fix nrf52 memory pools
  features/FEATURE_BLE/targets/TARGET_CORDIO/mbed_lib.json
  features/FEATURE_BLE/targets/TARGET_CORDIO_LL/mbed_lib.json
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_MCU_NRF52840/mbed_lib.json
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/NRFCordioHCIDriver.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/mbed_lib.json
Labels: ready for merge, release-version: 5.13.0-rc2

#10755 hal_qspi_test: undo buggy code
  TESTS/mbed_hal/qspi/flash_configs/S25FL512S_config.h
  TESTS/mbed_hal/qspi/qspi_test_utils.cpp
  TESTS/mbed_hal/qspi/qspi_test_utils.h
Labels: ready for merge, release-version: 5.13.1

#10629 Add support for the Embedded Planet Agora target
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_AGORA/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_AGORA/device.h
  targets/targets.json
Labels: ready for merge, scope: new-target

#10770 mbed-crypto: Update to Mbed Crypto 1.1.0d1
  features/mbedtls/mbed-crypto/VERSION.txt
  features/mbedtls/mbed-crypto/importer/Makefile
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto.c
  features/mbedtls/mbed-crypto/src/dhm.c
Labels: ready for merge, release-version: 5.13.0-rc3

#10786 Re-enable complilation for wifi and nanostack examples
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.13.0-rc3

#10437 PSA: Exclude mbed-hal-spm test for M23 target
  TESTS/mbed_hal/spm/main.cpp
Labels: ready for merge, release-version: 5.13.1

#10653 STM USBHALHost: Fix NULL pointer dereference
  features/unsupported/USBHost/targets/TARGET_STM/USBHALHost_STM.h
Labels: ready for merge, release-version: 5.13.1

#10709 Default to Cordio BLE stack for NRF52* targets
  TESTS/mbed_hal/critical_section/main.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/TESTS/cordio_hci/transport/main.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_crypto.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.0-rc3

#10665 Add hardcoded Echo server defaults for Greentea socket tests.
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tcp/tcp_tests.h
  TESTS/netsocket/tcp/tcpsocket_connect_invalid.cpp
  TESTS/netsocket/tcp/tcpsocket_endpoint_close.cpp
  TESTS/netsocket/tcp/tcpsocket_recv_100k.cpp
  TESTS/netsocket/tcp/tcpsocket_setsockopt_keepalive_valid.cpp
  TESTS/netsocket/test_params.h
  TESTS/netsocket/tls/main.cpp
  TESTS/netsocket/tls/tls_tests.h
  TESTS/netsocket/tls/tlssocket_connect_invalid.cpp
  TESTS/netsocket/tls/tlssocket_endpoint_close.cpp
  TESTS/netsocket/tls/tlssocket_no_cert.cpp
  TESTS/netsocket/tls/tlssocket_send_closed.cpp
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udp_tests.h
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_echotest_burst.cpp
  TESTS/netsocket/udp/udpsocket_recv_timeout.cpp
  TESTS/netsocket/udp/udpsocket_sendto_invalid.cpp
  TESTS/netsocket/udp/udpsocket_sendto_repeat.cpp
  TESTS/netsocket/udp/udpsocket_sendto_timeout.cpp
Labels: ready for merge, release-version: 5.13.1

#10672 Fix typos in the FPGA CI Test Shield component
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/MbedTester.h
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/test_utils.h
Labels: ready for merge, release-version: 5.13.1

#10695 GD32_F450ZI : Add bootloader support
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10699 MbedCRC: make buffers const void *
  drivers/MbedCRC.h
Labels: ready for merge, release-version: 5.14.0-rc1

#10705 Atomics: GCC fix for M23 (ARMv8-M baseline)
  platform/internal/mbed_atomic_impl.h
Labels: ready for merge, release-version: 5.13.1

#10708 TARGET_STM: SPI: add pulse on master transmissions
  targets/TARGET_STM/stm_spi_api.c
Labels: ready for merge, release-version: 5.13.1

#10739 M487: Fix wait_ns test failed
  targets/TARGET_NUVOTON/TARGET_M480/device/system_M480.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10742 CThunk: Fix assertion when CThunk object is destroyed
  platform/CThunk.h
Labels: ready for merge, release-version: 5.13.1

#10746 PSA protected storage: Add encrypt & RB protect flags by default to set.
  components/TARGET_PSA/services/storage/common/psa_storage_common_impl.cpp
  components/TARGET_PSA/services/storage/common/psa_storage_common_impl.h
  components/TARGET_PSA/services/storage/its/COMPONENT_PSA_SRV_IMPL/pits_impl.cpp
  components/TARGET_PSA/services/storage/ps/COMPONENT_NSPE/protected_storage.cpp
Labels: ready for merge, release-version: 5.13.1

#10749 Examples: enable more tests for examples
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.13.1

#10751 TARGET_TT:Setting wisely pin mode for TT_M3HQ.
  targets/TARGET_TT/TARGET_TT_M3HQ/pinmap.c
Labels: ready for merge, release-version: 5.13.1

#10752 STM32L0: Add DEVICE_SPI_COUNT to DISCO_L072CZ_LRWAN1 + MTB_MURATA_ABZ
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L072xZ/TARGET_DISCO_L072CZ_LRWAN1/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L0x2xZ/TARGET_MTB_MURATA_ABZ/PeripheralNames.h
Labels: ready for merge, release-version: 5.13.1

#10757 Add support I2C 3 for target EFM32G11
  targets/TARGET_Silicon_Labs/TARGET_EFM32/i2c_api.c
Labels: ready for merge, release-version: 5.13.1

#10758 Move Seeed ARCH_MAX to TARGET_STM32F407xE MCU
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/TARGET_ARCH_MAX/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/TARGET_ARCH_MAX/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/TARGET_ARCH_MAX/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/TARGET_ARCH_MAX/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/TOOLCHAIN_ARM_MICRO/STM32F407xx.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/TOOLCHAIN_ARM_MICRO/startup_STM32F407xx.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/TOOLCHAIN_ARM_STD/STM32F407xx.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/TOOLCHAIN_ARM_STD/startup_STM32F407xx.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/TOOLCHAIN_GCC_ARM/STM32F407XG.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/TOOLCHAIN_GCC_ARM/startup_stm32f407xx.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/TOOLCHAIN_IAR/startup_stm32f407xx.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/TOOLCHAIN_IAR/stm32f407xx.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/flash_data.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/stm32f407xx.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/stm32f4xx.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/system_stm32f4xx.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/device/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/objects.h
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10761 Fix networkinterface non-blocking status test
  TESTS/network/interface/networkinterface_status.cpp
Labels: ready for merge, release-version: 5.13.1

#10772 Workarounds for GAP advertising issues on Cordio
  features/FEATURE_BLE/source/generic/GenericGap.tpp
Labels: ready for merge, release-version: 5.13.1

#10775 STM32H7: refactor TARGET directory
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/flash_data.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32H7/common_objects.h
  targets/TARGET_STM/TARGET_STM32H7/device/stm32h7xx.h
  targets/TARGET_STM/TARGET_STM32H7/device/stm32h7xx_hal_rtc.h
  targets/TARGET_STM/TARGET_STM32H7/device/system_stm32h7xx.h
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/TARGET_STM/mbed_rtx.h
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10707 Add C++14 sized delete operators
  platform/mbed_retarget.cpp
Labels: ready for merge, release-version: 5.13.1

#10762 Disable only time drifting test cases and fix GREENTEA_SETUP() call in tests
  TESTS/mbed_drivers/lp_ticker/main.cpp
  TESTS/mbed_drivers/lp_timeout/main.cpp
  TESTS/mbed_drivers/ticker/main.cpp
  TESTS/mbed_drivers/timeout/main.cpp
  TESTS/mbed_hal/common_tickers_freq/main.cpp
  TESTS/mbed_hal/critical_section/main.cpp
  TESTS/mbed_platform/wait_ns/main.cpp
  TESTS/mbedmicro-rtos-mbed/basic/main.cpp
  TESTS/mbedmicro-rtos-mbed/kernel_tick_count/main.cpp
  TESTS/mbedmicro-rtos-mbed/mail/main.cpp
  TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
  TESTS/mbedmicro-rtos-mbed/threads/main.cpp
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10793 STM32: remove compilation warnings
  targets/TARGET_STM/TARGET_STM32F0/device/stm32f0xx_hal_tim.c
  targets/TARGET_STM/TARGET_STM32F0/device/stm32f0xx_hal_tim_ex.c
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_adc.c
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_adc_ex.c
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_tim.c
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_tim_ex.c
  targets/TARGET_STM/TARGET_STM32F1/device/stm32f1xx_hal_usart.c
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_adc.c
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_flash_ex.c
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_hcd.c
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_tim.c
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_tim_ex.c
  targets/TARGET_STM/TARGET_STM32F3/device/stm32f3xx_hal_tim.c
  targets/TARGET_STM/TARGET_STM32F3/device/stm32f3xx_hal_tim_ex.c
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc.c
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ex.c
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hcd.c
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim.c
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim_ex.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hcd.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_pcd.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_tim.c
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_tim_ex.c
  targets/TARGET_STM/TARGET_STM32F7/flash_api.c
  targets/TARGET_STM/TARGET_STM32H7/device/stm32h7xx_hal_hrtim.c
  targets/TARGET_STM/TARGET_STM32H7/device/stm32h7xx_hal_tim.c
  targets/TARGET_STM/TARGET_STM32H7/device/stm32h7xx_hal_tim_ex.c
  targets/TARGET_STM/TARGET_STM32L0/device/stm32l0xx_hal_tim.c
  targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_adc.c
  targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_adc_ex.c
  targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_rtc_ex.c
  targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_tim.c
  targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_uart.c
  targets/TARGET_STM/TARGET_STM32L1/device/stm32l1xx_hal_usart.c
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_hcd.c
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_pcd.c
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_tim.c
  targets/TARGET_STM/TARGET_STM32L4/device/stm32l4xx_hal_tim_ex.c
  targets/TARGET_STM/TARGET_STM32WB/device/stm32wbxx_hal_tim.c
  targets/TARGET_STM/TARGET_STM32WB/device/stm32wbxx_hal_tim_ex.c
  targets/TARGET_STM/can_api.c
  targets/TARGET_STM/gpio_irq_api.c
  targets/TARGET_STM/i2c_api.c
Labels: ready for merge, release-version: 5.13.1

#10790 STM32H7 enable LPUART
  targets/TARGET_STM/TARGET_STM32H7/serial_device.c
Labels: ready for merge, release-version: 5.13.1

#10794 LWIP DNS servers setting/getting fixed.
  features/lwipstack/LWIPInterface.cpp
  features/lwipstack/lwip/src/core/lwip_dns.c
  features/netsocket/mbed_lib.json
  features/netsocket/nsapi_dns.cpp
Labels: ready for merge, release-version: 5.13.1

#10805 Fix ARMC5 compilation
  features/netsocket/NetworkInterface.cpp
  platform/SingletonPtr.h
Labels: ready for merge, release-version: 5.13.0-rc3

#10809 ns_list: avoid UINT_FAST8_MAX (fix ARM C 5 builds)
  features/frameworks/nanostack-libservice/mbed-client-libservice/ns_list.h
Labels: ready for merge, release-version: 5.13.0-rc3

#10753 Fix nrf52 enabled uart count and enable uart0/1
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
Labels: ready for merge, release-version: 5.13.0-rc3

#10802 Update to mbedtls 2.18.0rc3
  features/mbedtls/VERSION.txt
  features/mbedtls/importer/Makefile
  features/mbedtls/inc/mbedtls/check_config.h
  features/mbedtls/inc/mbedtls/config.h
  features/mbedtls/inc/mbedtls/error.h
  features/mbedtls/inc/mbedtls/ssl.h
  features/mbedtls/inc/mbedtls/ssl_internal.h
  features/mbedtls/mbed-crypto/VERSION.txt
  features/mbedtls/mbed-crypto/importer/Makefile
  features/mbedtls/mbed-crypto/inc/psa/crypto_platform.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_sizes.h
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/COMPONENT_NSPE/crypto_struct.h
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_SPE/crypto_struct_spe.h
  features/mbedtls/platform/inc/platform_mbed.h
  features/mbedtls/src/Makefile
  features/mbedtls/src/error.c
  features/mbedtls/src/ssl_cli.c
  features/mbedtls/src/ssl_srv.c
  features/mbedtls/src/ssl_tls.c
  features/mbedtls/src/version_features.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.0-rc3

#10764 BG96 ipv6 support and socket id fix for BG96 and M26
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.cpp
Labels: ready for merge, release-version: 5.13.1

#10823 Nuvoton: Fix channel release in analogout_free()
  targets/TARGET_NUVOTON/TARGET_M2351/analogout_api.c
  targets/TARGET_NUVOTON/TARGET_M451/analogout_api.c
  targets/TARGET_NUVOTON/TARGET_M480/analogout_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/analogout_api.c
Labels: needs: CI, release-version: 5.13.1

#10779 Add support for SPIF of size bigger than 16Mbyte
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
Labels: ready for merge, release-version: 5.13.1

#10804 TARGET_STM: SPI: update pull up config depending on clk polarity
  targets/TARGET_STM/stm_spi_api.c
Labels: ready for merge, release-version: 5.13.1

#10833 fix IAR compile error on fastmodels
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10777 Bring back the missing watchdog commits
  TESTS/mbed_hal/watchdog/main.cpp
  TESTS/mbed_hal/watchdog_reset/main.cpp
  TESTS/mbed_hal/watchdog_timing/main.cpp
Labels: needs: CI, release-version: feature branch

#10659 Replace uses of ArrayView with mbed::Span
  features/FEATURE_BLE/ble/ArrayView.h
  features/FEATURE_BLE/ble/BLETypes.h
  features/FEATURE_BLE/ble/Gap.h
  features/FEATURE_BLE/ble/gap/AdvertisingDataBuilder.h
  features/FEATURE_BLE/ble/gap/AdvertisingDataParser.h
  features/FEATURE_BLE/ble/gap/Events.h
  features/FEATURE_BLE/ble/generic/GenericGap.h
  features/FEATURE_BLE/ble/generic/GenericSecurityManager.h
  features/FEATURE_BLE/ble/generic/SecurityDb.h
  features/FEATURE_BLE/ble/pal/AttClient.h
  features/FEATURE_BLE/ble/pal/AttClientToGattClientAdapter.h
  features/FEATURE_BLE/ble/pal/AttServerMessage.h
  features/FEATURE_BLE/ble/pal/GapEvents.h
  features/FEATURE_BLE/ble/pal/GenericAccessService.h
  features/FEATURE_BLE/ble/pal/PalGattClient.h
  features/FEATURE_BLE/ble/pal/SimpleAttServerMessage.h
  features/FEATURE_BLE/source/generic/GenericGap.tpp
  features/FEATURE_BLE/source/generic/GenericGattClient.tpp
  features/FEATURE_BLE/source/generic/GenericSecurityManager.tpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioPalAttClient.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioPalGap.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioPalGenericAccessService.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF51/source/nRF5xCrypto.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF51/source/nRF5xCrypto.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF51/source/nRF5xGap.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF51/source/nRF5xPalGattClient.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF51/source/nRF5xPalGattClient.tpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF51/source/nRF5xPalSecurityManager.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF51/source/nRF5xPalSecurityManager.tpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xCrypto.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xCrypto.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xGap.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xPalGattClient.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xPalGattClient.tpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xPalSecurityManager.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/nRF5xPalSecurityManager.tpp
Labels: ready for merge, release-version: 5.14.0-rc1

#10689 nRF52840 USB Device Implementation
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/integration/nrfx/legacy/nrf_drv_usbd.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/integration/nrfx/legacy/nrf_drv_usbd.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/integration/nrfx/legacy/nrf_drv_usbd_errata.h
  targets/targets.json
  usb/device/targets/TARGET_NORDIC/TARGET_MCU_NRF52840/USBPhyHw.h
  usb/device/targets/TARGET_NORDIC/TARGET_MCU_NRF52840/USBPhy_Nordic.cpp
Labels: ready for merge, release-version: 5.13.1

#10776 UDPSOCKET_ECHOTEST_NONBLOCK performance improvement.
  TESTS/netsocket/udp/udpsocket_echotest.cpp
Labels: ready for merge, release-version: 5.13.1

#10818 Release candidate for mbed-os-5.13.0-rc3
  TESTS/mbed_hal/critical_section/main.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/TESTS/cordio_hci/transport/main.cpp
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_crypto.c
  features/frameworks/nanostack-libservice/mbed-client-libservice/ns_list.h
  features/mbedtls/VERSION.txt
  features/mbedtls/importer/Makefile
  features/mbedtls/inc/mbedtls/check_config.h
  features/mbedtls/inc/mbedtls/config.h
  features/mbedtls/inc/mbedtls/error.h
  features/mbedtls/inc/mbedtls/ssl.h
  features/mbedtls/inc/mbedtls/ssl_internal.h
  features/mbedtls/mbed-crypto/VERSION.txt
  features/mbedtls/mbed-crypto/importer/Makefile
  features/mbedtls/mbed-crypto/inc/psa/crypto_platform.h
  features/mbedtls/mbed-crypto/inc/psa/crypto_sizes.h
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/COMPONENT_NSPE/crypto_struct.h
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_PSA_SRV_IMPL/psa_crypto.c
  features/mbedtls/mbed-crypto/platform/TARGET_PSA/COMPONENT_SPE/crypto_struct_spe.h
  features/mbedtls/mbed-crypto/src/dhm.c
  features/mbedtls/platform/inc/platform_mbed.h
  features/mbedtls/src/Makefile
  features/mbedtls/src/error.c
  features/mbedtls/src/ssl_cli.c
  features/mbedtls/src/ssl_srv.c
  features/mbedtls/src/ssl_tls.c
  features/mbedtls/src/version_features.c
  features/netsocket/NetworkInterface.cpp
  platform/SingletonPtr.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
  targets/targets.json
  tools/test/examples/examples.json
Labels: needs: CI

#10484 Cellular: Telit ME910 driver
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910.cpp
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910.h
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910_CellularContext.cpp
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910_CellularContext.h
  features/cellular/framework/targets/TELIT/ME910/mbed_lib.json
Labels: ready for merge, release-version: 5.13.1

#10536 Changes required by the ST low power ticker wrapper.
  TESTS/mbed_drivers/timeout/timeout_tests.h
  TESTS/mbed_hal/sleep/main.cpp
  hal/mbed_ticker_api.c
Labels: release-version: 5.13.1

#10688 Add a top level README file for USB tests
  TESTS/usb_device/README.md
  TESTS/usb_device/basic/README.md
  TESTS/usb_device/basic/zadig_conf/README.md
  TESTS/usb_device/hid/README.md
  TESTS/usb_device/msd/README.md
  TESTS/usb_device/serial/README.md
Labels: ready for merge, release-version: 5.13.1

#10741 M2351: Override wait_ns to provide more accurate implementation
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/wait_ns.c
Labels: needs: preceding PR, ready for merge, release-version: 5.13.1

#10744 Fixes in Sys Timer test
  TESTS/mbedmicro-rtos-mbed/systimer/main.cpp
Labels: ready for merge, release-version: 5.13.1

#10756 Cleaned up trace log SPIF Block Device
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
Labels: ready for merge, release-version: 5.13.1

#10769 PSOC6: add SOFTFP to standard component list
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10782 GR_LYCHEE,RZ_A1H,VK_RZ_A1H: Fix greentea test failure with ARMC6
  TESTS/mbed_drivers/crc/main.cpp
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/flash_api.c
Labels: ready for merge, release-version: 5.13.1

#10792 Fix: Allow target size restriction for LPC55S69
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10795 FastModel: trun off MPU for FVP_MPS2_M0P
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/CMSDK_CM0plus.h
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10807 NSAPI/lwIP: Use netconn_recv_tcp_pbuf
  features/lwipstack/LWIPStack.cpp
  features/lwipstack/LWIPStack.h
Labels: ready for merge, release-version: 5.13.1

#10811 socket close callback
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
Labels: ready for merge, release-version: 5.13.1

#10812 Cellular: fix athandler to use correct timeout in case of multiple urc's
  features/cellular/framework/AT/ATHandler.cpp
Labels: ready for merge, release-version: 5.13.1

#10825 Cellular: Fix PLMN debug trace for IAR
  features/cellular/framework/device/CellularStateMachine.cpp
Labels: ready for merge, release-version: 5.13.1

#10702 Add extra idle debug stack size in case all STATS are enabled
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
Labels: ready for merge, release-version: 5.13.1

#10694 Cellular: add method to set authentication type to CellularContext
  UNITTESTS/features/cellular/framework/device/cellularcontext/cellularcontexttest.cpp
  UNITTESTS/features/cellular/framework/device/cellularcontext/unittest.cmake
  UNITTESTS/stubs/CellularContext_stub.cpp
  UNITTESTS/stubs/CellularDevice_stub.cpp
  UNITTESTS/stubs/CellularDevice_stub.h
  UNITTESTS/stubs/ControlPlane_netif_stub.h
  UNITTESTS/stubs/ThisThread_stub.cpp
  UNITTESTS/target_h/myCellularDevice.h
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/device/CellularContext.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#10808 Cellular: Added handling for BG96 network PDP context deactivation
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.h
Labels: ready for merge, release-version: 5.13.1

#10866 Adding stmod_cellular component
  components/cellular/COMPONENT_STMOD_CELLULAR/README.md
  components/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.cpp
  components/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.h
  components/cellular/COMPONENT_STMOD_CELLULAR/mbed_lib.json
Labels: ready for merge, release-version: 5.14.0-rc1

#10845 Wrong timeout value in greentea tests
  features/storage/TESTS/blockdevice/general_block_device/main.cpp
  features/storage/TESTS/filesystem/general_filesystem/main.cpp
  features/storage/TESTS/kvstore/static_tests/main.cpp
Labels: release-version: 5.13.1

#10875 Cellular: Remove IPV6 and IPV4V6 as supported properties for BG96
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
Labels: ready for merge, release-version: 5.13.0-rc4

#10870 HAL I2C: adds missing DEVICE_I2C guards
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/i2c_api.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/i2c_api.c
  targets/TARGET_ARM_SSG/TARGET_IOTSS/i2c_api.c
  targets/TARGET_ARM_SSG/TARGET_MPS2/i2c_api.c
  targets/TARGET_Atmel/TARGET_SAM_CortexM0P/i2c_api.c
  targets/TARGET_Atmel/TARGET_SAM_CortexM4/i2c_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/i2c_api.c
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/i2c_api.c
  targets/TARGET_Freescale/TARGET_K20XX/i2c_api.c
  targets/TARGET_Freescale/TARGET_KLXX/i2c_api.c
  targets/TARGET_Maxim/TARGET_MAX32600/i2c_api.c
  targets/TARGET_Maxim/TARGET_MAX32610/i2c_api.c
  targets/TARGET_Maxim/TARGET_MAX32620/i2c_api.c
  targets/TARGET_Maxim/TARGET_MAX32620C/i2c_api.c
  targets/TARGET_Maxim/TARGET_MAX32625/i2c_api.c
  targets/TARGET_Maxim/TARGET_MAX32630/i2c_api.c
  targets/TARGET_NORDIC/TARGET_MCU_NRF51822/i2c_api.c
  targets/TARGET_NXP/TARGET_LPC11UXX/i2c_api.c
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/i2c_api.c
  targets/TARGET_NXP/TARGET_LPC13XX/i2c_api.c
  targets/TARGET_NXP/TARGET_LPC15XX/i2c_api.c
  targets/TARGET_NXP/TARGET_LPC176X/i2c_api.c
  targets/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088/i2c_api.c
  targets/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088_DM/i2c_api.c
  targets/TARGET_NXP/TARGET_LPC43XX/i2c_api.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/i2c_api.c
  targets/TARGET_Realtek/TARGET_AMEBA/TARGET_MCU_RTL8195A/i2c_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM066/i2c_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3H6/i2c_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/i2c_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/i2c_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/i2c_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/i2c_api.c
  targets/TARGET_TT/TARGET_TT_M4G9/i2c_api.c
Labels: ready for merge, release-version: 5.13.1

#10893 cellular: fix file permission
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.cpp
Labels: ready for merge, release-version: 5.13.1

#10858 Check Cellular Properties have been set
  features/cellular/framework/AT/AT_CellularBase.cpp
Labels: ready for merge, release-version: 5.13.1

#10706 mem pool size: Fix calculation of memory pool size for portability
  rtos/MemoryPool.h
  rtos/TARGET_CORTEX/mbed_rtos_storage.h
Labels: ready for merge, release-version: 5.13.1

#10821 Cellular: Refactor APN db implementation to reduce memory usage
  features/cellular/framework/common/APN_db.cpp
  features/cellular/framework/common/APN_db.h
Labels: ready for merge, release-version: 5.14.0-rc1

#10834 Fixed UDP sendto if IP version not match
  features/lwipstack/LWIPStack.cpp
  features/lwipstack/lwip_tools.cpp
Labels: ready for merge, release-version: 5.13.1

#10835 M23: Fix compile error with mbed fault handler
  platform/TARGET_CORTEX_M/mbed_fault_handler.c
Labels: ready for merge, release-version: 5.13.1

#10856 STM32: enable CRC for all L0/L4/F7
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10846 MbedCRC doxygen fixes
  drivers/MbedCRC.h
  hal/crc_api.h
Labels: ready for merge, release-version: 5.13.1

#10704 microlib support: Fix build with Arm Compiler 6 and MicroLib
  rtos/TARGET_CORTEX/TOOLCHAIN_ARM_MICRO/mbed_boot_arm_micro.c
Labels: ready for merge, release-version: 5.13.1

#10879 PSA Crypto for all targets
  features/mbedtls/mbed-crypto/importer/Makefile
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/COMPONENT_NSPE/crypto_struct.h
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto.c
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_core.h
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_invasive.h
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_its.h
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_service_integration.h
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_slot_management.c
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_slot_management.h
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_storage.c
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_storage.h
  features/mbedtls/mbed-crypto/platform/COMPONENT_PSA_SRV_IMPL/psa_its_file.c
  features/mbedtls/mbed-crypto/platform/COMPONENT_SPE/crypto_struct_spe.h
  features/mbedtls/mbed-crypto/platform/mbed_lib.json
Labels: ready for merge, release-version: 5.13.1

#10774 Fix serial IRQ handling
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/serial_api.c
  targets/TARGET_STM/TARGET_STM32F0/serial_device.c
  targets/TARGET_STM/TARGET_STM32F3/serial_device.c
  targets/TARGET_STM/TARGET_STM32F7/serial_device.c
  targets/TARGET_STM/TARGET_STM32H7/serial_device.c
  targets/TARGET_STM/TARGET_STM32L0/serial_device.c
  targets/TARGET_STM/TARGET_STM32L4/serial_device.c
  targets/TARGET_STM/TARGET_STM32WB/serial_device.c
Labels: ready for merge, release-version: 5.13.1

#10896 microlib support: Specify compiler version unable to build without the fix
  rtos/TARGET_CORTEX/TOOLCHAIN_ARM_MICRO/mbed_boot_arm_micro.c
Labels: ready for merge, release-version: 5.13.1

#10864 TLSSocket: print certificate info only when tracing is enabled
  features/netsocket/TLSSocketWrapper.cpp
Labels: ready for merge, release-version: 5.13.1

#10826 Add STM32H743ZI to IAR export definition
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 5.13.1

#10888 Remove macro MBEDTLS_PSA_CRYPTO_C from PSA targets
  components/TARGET_PSA/services/attestation/COMPONENT_PSA_SRV_IMPL/attest_crypto.c
  components/TARGET_PSA/services/crypto/COMPONENT_PSA_SRV_IPC/psa_crypto_spm.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.1

#10781 Include TICKLESS stack size increase even without LPTICKER_DELAY_TICKS
  rtos/TARGET_CORTEX/mbed_rtx_conf.h
  rtos/mbed_lib.json
Labels: ready for merge, release-version: 5.13.1

#10791 bootloader: Fix LPC55S69 bootloader segmentation
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/TOOLCHAIN_ARMC6/LPC55S69_cm33_core0_flash.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/TOOLCHAIN_GCC_ARM/LPC55S69_cm33_core0_flash.ld
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/TOOLCHAIN_IAR/LPC55S69_cm33_core0_flash.icf
Labels: ready for merge, release-version: 5.13.1

#10700 Update HAL Sleep manager test to cope with STM32 LPTIM HW
  TESTS/mbed_hal/sleep_manager/main.cpp
  platform/mbed_sleep_manager.c
Labels: Priority-High, ready for merge, release-version: 5.13.1

#10374 I2c ref impl
  docs/design-documents/hal/0001-i2c-overhaul.md
  drivers/I2C.cpp
  drivers/I2C.h
  drivers/I2CSlave.cpp
  drivers/I2CSlave.h
  hal/i2c_api.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_i2c.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_i2c.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/i2c_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/objects.h
  targets/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088/ethernet_api.c
  targets/TARGET_STM/TARGET_STM32F0/common_objects.h
  targets/TARGET_STM/TARGET_STM32F1/common_objects.h
  targets/TARGET_STM/TARGET_STM32F2/objects.h
  targets/TARGET_STM/TARGET_STM32F3/common_objects.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/min_battery_voltage.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/min_battery_voltage.h
  targets/TARGET_STM/TARGET_STM32F4/common_objects.h
  targets/TARGET_STM/TARGET_STM32F7/common_objects.h
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/TARGET_STM/TARGET_STM32L0/common_objects.h
  targets/TARGET_STM/TARGET_STM32L1/common_objects.h
  targets/TARGET_STM/TARGET_STM32L4/common_objects.h
  targets/TARGET_STM/TARGET_STM32WB/common_objects.h
  targets/TARGET_STM/i2c_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/PeripheralNames.h
  targets/targets.json
  tools/test/examples/examples.json
Labels: ready for merge, release-version: feature branch

#10824 STM32: pwmout_write: configure channel only when not already enabled
  targets/TARGET_STM/TARGET_STM32F0/common_objects.h
  targets/TARGET_STM/TARGET_STM32F1/common_objects.h
  targets/TARGET_STM/TARGET_STM32F2/objects.h
  targets/TARGET_STM/TARGET_STM32F3/common_objects.h
  targets/TARGET_STM/TARGET_STM32F4/common_objects.h
  targets/TARGET_STM/TARGET_STM32F7/common_objects.h
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/TARGET_STM/TARGET_STM32L0/common_objects.h
  targets/TARGET_STM/TARGET_STM32L1/common_objects.h
  targets/TARGET_STM/TARGET_STM32L4/common_objects.h
  targets/TARGET_STM/TARGET_STM32WB/common_objects.h
  targets/TARGET_STM/pwmout_api.c
Labels: ready for merge, release-version: 5.13.1

#10767 usb_device-msd test: fix powershell unmount script issue
  TESTS/host_tests/pyusb_msd.py
  TESTS/usb_device/README.md
  TESTS/usb_device/msd/main.cpp
Labels: ready for merge, release-version: 5.13.1

#10609 wait_us optimization
  TESTS/mbed_hal/us_ticker/main.cpp
  components/TARGET_PSA/services/storage/common/psa_storage_common_impl.cpp
  hal/mbed_us_ticker_api.c
  hal/us_ticker_api.h
  platform/mbed_retarget.cpp
  platform/mbed_sdk_boot.c
  platform/mbed_toolchain.h
  platform/mbed_wait_api.h
  platform/mbed_wait_api_no_rtos.c
  platform/mbed_wait_api_rtos.cpp
  rtos/TARGET_CORTEX/mbed_boot.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/us_ticker_defines.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/us_ticker_defines.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/us_ticker_defines.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/us_ticker_defines.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/us_ticker_defines.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/us_ticker_defines.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/us_ticker_defines.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/us_ticker_defines.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/us_ticker_defines.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/us_ticker.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/us_ticker_defines.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/objects.h
  targets/TARGET_STM/device.h
  targets/TARGET_STM/us_ticker.c
  targets/TARGET_STM/us_ticker_defines.h
  targets/targets.json
Labels: Priority-High, ready for merge, release-version: 5.13.1
