Repository ARMmbed/mbed-os, pull requests merged in 2019-08, with the labels that each got.

#11132 Fix MBED_ASSERT for UTs
  UNITTESTS/target_h/platform/mbed_assert.h
Labels: ready for merge, release-version: 5.13.3

#11135 Upstream PR #11073 review request changes
  drivers/BusIn.h
  drivers/BusInOut.h
  drivers/BusOut.h
  drivers/Ethernet.h
  drivers/InterruptIn.h
  drivers/InterruptManager.h
  drivers/SerialWireOutput.h
  drivers/Watchdog.h
  drivers/internal/AsyncOp.h
  drivers/internal/ByteBuffer.h
  drivers/internal/EndpointResolver.h
  drivers/internal/LinkEntry.h
  drivers/internal/LinkedList.h
  drivers/internal/LinkedListBase.h
  drivers/internal/MIDIMessage.h
  drivers/internal/OperationList.h
  drivers/internal/OperationListBase.h
  drivers/internal/PolledQueue.h
  drivers/internal/Task.h
  drivers/internal/TaskBase.h
  drivers/internal/TaskQueue.h
  drivers/internal/USBDevice.h
  drivers/source/usb/mbed_lib.json
  events/internal/equeue_platform.h
  events/mbed_events.h
  features/device_key/source/DeviceKey.h
  platform/CallChain.h
  platform/internal/CThunkBase.h
  platform/source/CallChain.cpp
  usb/device/targets/TARGET_Freescale/USBEndpoints_Kinetis.h
  usb/device/targets/TARGET_Freescale/USBPhyHw.h
  usb/device/targets/TARGET_Freescale/USBPhy_Kinetis.cpp
  usb/device/targets/TARGET_NORDIC/TARGET_MCU_NRF52840/USBPhyHw.h
  usb/device/targets/TARGET_NORDIC/TARGET_MCU_NRF52840/USBPhy_Nordic.cpp
  usb/device/targets/TARGET_NXP/USBEndpoints_LPC17_LPC23.h
  usb/device/targets/TARGET_NXP/USBHAL_LPC17.cpp
  usb/device/targets/TARGET_NXP/USBPhyHw.h
  usb/device/targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBEndpoints_RZ_A1.h
  usb/device/targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhyHw.h
  usb/device/targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhy_RZ_A1.cpp
  usb/device/targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhy_RZ_A1_Def.h
  usb/device/targets/TARGET_STM/USBEndpoints_STM32.h
  usb/device/targets/TARGET_STM/USBPhyHw.h
  usb/device/targets/TARGET_STM/USBPhy_STM32.cpp
  usb/device/targets/TARGET_Template/USBPhyHw.h
  usb/device/targets/TARGET_Template/USBPhy_template.cpp
  usb/device/targets/mbed_lib.json
Labels: needs: review, release-version: feature branch

#10913 Port CC 310 sha 512 driver
  features/cryptocell/FEATURE_CRYPTOCELL310/mbedtls_device.h
  features/cryptocell/FEATURE_CRYPTOCELL310/sha512_alt.c
  features/cryptocell/FEATURE_CRYPTOCELL310/sha512_alt.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11146 Mark Ethernet.h methods as Deprecated in Doxygen documentation
  drivers/Ethernet.h
Labels: release-version: feature branch

#10877 Cellular: Ublox cellular context activation updated for C030_R412M
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.h
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.cpp
Labels: ready for merge, release-version: 5.13.3

#11082 Cellular: Add BG96 AT driver with DNS support
  TESTS/netsocket/dns/asynchronous_dns_cancel.cpp
  TESTS/netsocket/dns/dns_tests.h
  TESTS/netsocket/dns/main.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.h
  features/cellular/mbed_lib.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11099 Update EP_AGORA target pinout
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_AGORA/PinNames.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11131 FUTURE_SEQUANA: Add missing serial_free() implementation
  targets/TARGET_Cypress/TARGET_PSOC6_FUTURE/serial_api.c
Labels: ready for merge, release-version: 5.13.3

#10980 LwIP: make TCPIP_THREAD_PRIO configurable
  features/lwipstack/lwipopts.h
  features/lwipstack/mbed_lib.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11009 FPGA SPI: remove 4 and 12 bits size support
  TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11160 Nuvoton: Remove dead code nu_delay_cycle_x4
  targets/TARGET_NUVOTON/nu_timer.c
  targets/TARGET_NUVOTON/nu_timer.h
Labels: ready for merge, release-version: 5.13.3

#11149 Cellular: Remove unnecessary local variables
  features/cellular/framework/AT/AT_CellularContext.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11145 Implement queue.count()
  rtos/Queue.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11141 freescale: fix i2c_byte_read function
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/i2c_api.c
Labels: ready for merge, release-version: 5.13.3

#11138 fix rom start & size for CY8CKIT_062_WIFI_BT & CY8CPROTO_062_4343W
  targets/targets.json
Labels: ready for merge, release-version: 5.13.3

#11123 NRF52 need to call TIMER_TASK_SHUTDOWN for current consumption
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/us_ticker.c
Labels: ready for merge, release-version: 5.13.3

#11154 Cellular API shutdown to stop state machine
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/device/CellularDevice.cpp
Labels: ready for merge, release-version: 5.13.3

#11151 Fix PSoC 6 inout pins
  targets/TARGET_Cypress/TARGET_PSOC6/cy_gpio_api.c
Labels: ready for merge, release-version: 5.13.3

#11163 Bring back SPIF module-specific debug logs
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SPIF/mbed_lib.json
Labels: ready for merge, release-version: 5.13.3

#11173 Coverity and compilation warnings fixes
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.h
  features/netsocket/nsapi_dns.cpp
  features/storage/blockdevice/BufferedBlockDevice.cpp
  features/storage/filesystem/fat/ChaN/ff.cpp
  features/storage/filesystem/fat/FATFileSystem.cpp
  features/storage/filesystem/littlefs/LittleFileSystem.cpp
  features/storage/filesystem/littlefs/littlefs/lfs.c
  features/storage/kvstore/filesystemstore/FileSystemStore.cpp
  features/storage/kvstore/kv_map/KVMap.cpp
  features/storage/kvstore/securestore/SecureStore.cpp
  features/storage/kvstore/tdbstore/TDBStore.cpp
  features/storage/nvstore/source/nvstore.cpp
Labels: ready for merge, release-version: 5.13.3

#11162 Add DNS servers from cellular PDP to nsapi
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/unittest.cmake
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/netsocket/nsapi_dns.cpp
Labels: ready for merge, release-version: 5.13.3

#11119 Riot Micro cellular device
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT.h
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularContext.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularContext.h
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularNetwork.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularNetwork.h
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularStack.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularStack.h
  features/cellular/framework/targets/RiotMicro/AT/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_RIOT_MICRO_MODULE/ONBOARD_RM1000_AT.cpp
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_RIOT_MICRO_MODULE/ONBOARD_RM1000_AT.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_RIOT_MICRO_MODULE/TARGET_RM6100/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_RIOT_MICRO_MODULE/TARGET_RM7100/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_RIOT_MICRO_MODULE/device.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_RIOT_MICRO_MODULE/onboard_modem_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.3

#11161 Fix include path issues on NRF5x with Cordio
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/include/audio_board.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_bb.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_bb_ble.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_cfg.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_crypto.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_led.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_nvm.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_rtc.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_sys.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_timer.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_twi.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_uart.c
Labels: ready for merge, release-version: 5.13.3

#11179 Zero initialise all NVStore&kvstore members
  features/storage/kvstore/kv_map/KVMap.cpp
  features/storage/kvstore/tdbstore/TDBStore.cpp
  features/storage/nvstore/source/nvstore.cpp
Labels: ready for merge, release-version: 5.13.3

#11168 Xpresso: qspi_write fix
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/qspi_api.c
Labels: ready for merge, release-version: 5.13.3

#11150 __cplusplus guard fixed pwmout_device.h for STM32F4
  targets/TARGET_STM/TARGET_STM32F4/pwmout_device.h
Labels: ready for merge, release-version: 5.13.3

#11051 Minimal printf
  TESTS/mbed_drivers/c_strings/main.cpp
  TESTS/mbed_platform/minimal-printf/compliance/README.md
  TESTS/mbed_platform/minimal-printf/compliance/main.cpp
  TESTS/mbed_platform/minimal-printf/compliance/mbed_printf.c
  TESTS/mbed_platform/minimal-printf/compliance/mbed_printf.h
  TESTS/mbed_platform/minimal-printf/compliance/test_app.json
  platform/mbed_lib.json
  platform/source/minimal-printf/README.md
  platform/source/minimal-printf/mbed_printf_armlink_overrides.c
  platform/source/minimal-printf/mbed_printf_implementation.c
  platform/source/minimal-printf/mbed_printf_implementation.h
  platform/source/minimal-printf/mbed_printf_wrapper.c
  tools/export/gnuarmeclipse/.cproject.tmpl
  tools/profiles/minimal-printf.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11103 STM32F7: Do not generate redundant IN tokens
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_hcd.c
Labels: ready for merge, release-version: 5.13.3

#11056 HAL I2C design doc update
  docs/design-documents/hal/0001-i2c-overhaul.md
Labels: ready for merge

#11139 STM32F413 Crash Capture
  platform/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/device/TOOLCHAIN_ARM_MICRO/stm32f413xh.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/device/TOOLCHAIN_ARM_STD/stm32f413xh.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/device/TOOLCHAIN_GCC_ARM/STM32F413xH.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/device/TOOLCHAIN_IAR/stm32f413xx.icf
Labels: ready for merge, release-version: 5.13.3

#11116 Define I²C related pin names for the L-Tek FF_LPC546XX target
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/TARGET_FF_LPC546XX/PinNames.h
Labels: ready for merge, release-version: 5.13.4

#11137 Add Arduino Nano 33 BLE target
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_ARDUINO_NANO33BLE/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_ARDUINO_NANO33BLE/device.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/mbed_lib.json
  targets/targets.json
Labels: ready for merge, scope: new-target

#11157 Relax us ticker frequency requirement + test update
  TESTS/mbed_hal/us_ticker/main.cpp
  TESTS/mbed_hal/us_ticker/us_ticker_api_tests.h
  hal/us_ticker_api.h
Labels: ready for merge, release-version: 5.13.4

#11166 Fix inclusion of test related directories by build tool
  components/TARGET_PSA/services/attestation/qcbor/.mbedignore
Labels: ready for merge, release-version: 5.13.4

#11167 Fix lp ticker and common ticker tests
  TESTS/mbed_hal/common_tickers/main.cpp
  TESTS/mbed_hal/lp_ticker/main.cpp
Labels: ready for merge, release-version: 5.13.4

#11189 __cplusplus guard fixed pwmout_device.h for STM32 families
  targets/TARGET_STM/TARGET_STM32F0/pwmout_device.h
  targets/TARGET_STM/TARGET_STM32F1/pwmout_device.h
  targets/TARGET_STM/TARGET_STM32F2/pwmout_device.h
  targets/TARGET_STM/TARGET_STM32F3/pwmout_device.h
  targets/TARGET_STM/TARGET_STM32F7/pwmout_device.h
  targets/TARGET_STM/TARGET_STM32H7/pwmout_device.h
  targets/TARGET_STM/TARGET_STM32L0/pwmout_device.h
  targets/TARGET_STM/TARGET_STM32L1/pwmout_device.h
  targets/TARGET_STM/TARGET_STM32L4/pwmout_device.h
  targets/TARGET_STM/TARGET_STM32WB/pwmout_device.h
Labels: ready for merge, release-version: 5.13.4

#11191 Cellular: move RAT reading to better support ublox custom boards
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.h
Labels: ready for merge, release-version: 5.13.4

#11193 FATFileSystem::stat() enabled for all compilers
  features/storage/TESTS/filesystem/fat_filesystem/main.cpp
  features/storage/filesystem/fat/FATFileSystem.cpp
Labels: ready for merge, release-version: 5.13.4

#11213 Moved partial profile to a subdirectory
  platform/source/minimal-printf/README.md
  tools/export/gnuarmeclipse/.cproject.tmpl
  tools/profiles/extensions/minimal-printf.json
Labels: ready for merge, release-version: 5.13.4

#11200 Cellular: moved string_to_pdp_type from AT_CellularContext to Cellula…
  UNITTESTS/features/cellular/framework/common/util/utiltest.cpp
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  UNITTESTS/stubs/CellularUtil_stub.cpp
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/common/CellularUtil.cpp
  features/cellular/framework/common/CellularUtil.h
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910_CellularContext.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11020 Nuvoton: Enlarge required deep sleep latency
  targets/targets.json
Labels: ready for merge, release-version: 5.13.4

#11231 Python3 fixes
  tools/export/exporters.py
  tools/export/gnuarmeclipse/__init__.py
  tools/export/iar/__init__.py
  tools/test/examples/examples_lib.py
Labels: needs: review

#11021 Nuvoton: Enlarge LPTICKER_DELAY_TICKS for safe
  targets/targets.json
Labels: ready for merge

#11148 Cellular: Fix SIM pin enter command
  features/cellular/framework/AT/AT_CellularDevice.cpp
Labels: ready for merge, release-version: 5.13.4

#11126 Optimize debug profile flags for size
  tools/profiles/debug.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11180 tweak atomic_test timeout
  TESTS/mbed_platform/atomic/main.cpp
Labels: ready for merge, release-version: 5.13.4

#11190 Cellular: failure when deleting created context is not considered error
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11198 Remove redundant file accidentally added
  features/cryptocell/FEATURE_CRYPTOCELL310/ecdsa_alt.c.mod
Labels: ready for merge, release-version: 5.13.3

#11208 Atomics: GCC fix for M23 (again)
  platform/internal/mbed_atomic_impl.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11221 Valgrind issues fixed
  UNITTESTS/features/lorawan/lorawanstack/Test_LoRaWANStack.cpp
Labels: ready for merge, release-version: feature branch

#11243 Python3 fixes
  tools/test/examples/examples_lib.py
Labels: needs: review

#11222 BLE: fix recursive call
  features/FEATURE_BLE/ble/pal/PalGap.h
Labels: ready for merge, release-version: 5.13.4

#11165 Allows placing KVStore and update images on separate storage devices - to internal and external flash
  features/storage/TESTS/kvstore/direct_access_devicekey_test/main.cpp
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/kvstore/direct_access_devicekey/DirectAccessDevicekey.cpp
Labels: ready for merge, release-version: 5.13.4

#11242 removed Cellular unittests
  UNITTESTS/features/cellular/framework/AT/at_cellularbase/at_cellularbasetest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularbase/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/at_cellulardevicetest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularinformation/at_cellularinformationtest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularinformation/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/at_cellularsmstest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/at_cellularstacktest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/athandler/athandlertest.cpp
  UNITTESTS/features/cellular/framework/AT/athandler/unittest.cmake
  UNITTESTS/features/cellular/framework/common/util/unittest.cmake
  UNITTESTS/features/cellular/framework/common/util/utiltest.cpp
  UNITTESTS/features/cellular/framework/device/cellulardevice/cellulardevicetest.cpp
  UNITTESTS/features/cellular/framework/device/cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellularstatemachine/cellularstatemachinetest.cpp
  UNITTESTS/features/cellular/framework/device/cellularstatemachine/unittest.cmake
  UNITTESTS/features/netsocket/DTLSSocket/dtls_test_config.h
  UNITTESTS/features/netsocket/DTLSSocket/test_DTLSSocket.cpp
  UNITTESTS/features/netsocket/DTLSSocket/unittest.cmake
  UNITTESTS/features/netsocket/DTLSSocketWrapper/dtls_test_config.h
  UNITTESTS/features/netsocket/DTLSSocketWrapper/test_DTLSSocketWrapper.cpp
  UNITTESTS/features/netsocket/DTLSSocketWrapper/unittest.cmake
  UNITTESTS/features/netsocket/EthernetInterface/test_EthernetInterface.cpp
  UNITTESTS/features/netsocket/EthernetInterface/unittest.cmake
  UNITTESTS/features/netsocket/InternetSocket/test_InternetSocket.cpp
  UNITTESTS/features/netsocket/InternetSocket/unittest.cmake
  UNITTESTS/features/netsocket/NetworkInterface/test_NetworkInterface.cpp
  UNITTESTS/features/netsocket/NetworkInterface/unittest.cmake
  UNITTESTS/features/netsocket/NetworkStack/test_NetworkStack.cpp
  UNITTESTS/features/netsocket/NetworkStack/unittest.cmake
  UNITTESTS/features/netsocket/SocketAddress/test_SocketAddress.cpp
  UNITTESTS/features/netsocket/SocketAddress/unittest.cmake
  UNITTESTS/features/netsocket/TCPServer/test_TCPServer.cpp
  UNITTESTS/features/netsocket/TCPServer/unittest.cmake
  UNITTESTS/features/netsocket/TCPSocket/test_TCPSocket.cpp
  UNITTESTS/features/netsocket/TCPSocket/unittest.cmake
  UNITTESTS/features/netsocket/TLSSocket/test_TLSSocket.cpp
  UNITTESTS/features/netsocket/TLSSocket/tls_test_config.h
  UNITTESTS/features/netsocket/TLSSocket/unittest.cmake
  UNITTESTS/features/netsocket/TLSSocketWrapper/test_TLSSocketWrapper.cpp
  UNITTESTS/features/netsocket/TLSSocketWrapper/tls_test_config.h
  UNITTESTS/features/netsocket/TLSSocketWrapper/unittest.cmake
  UNITTESTS/features/netsocket/UDPSocket/test_UDPSocket.cpp
  UNITTESTS/features/netsocket/UDPSocket/unittest.cmake
  UNITTESTS/features/netsocket/WiFiAccessPoint/test_WiFiAccessPoint.cpp
  UNITTESTS/features/netsocket/WiFiAccessPoint/unittest.cmake
  UNITTESTS/features/netsocket/cellular/CellularNonIPSocket/test_CellularNonIPSocket.cpp
  UNITTESTS/features/netsocket/cellular/CellularNonIPSocket/unittest.cmake
Labels: ready for merge, release-version: feature branch

#11118 Add new features to Toshiba's TMPM46B
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/Periph_Driver/src/tmpm46b_esg.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/analogin_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/device.h
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/device/TOOLCHAIN_ARM_STD/tmpm46bf10fg.sct
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/device/system_TMPM46B.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/flash_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/gpio_irq_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/i2c_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/objects.h
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/pinmap.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/port_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/pwmout_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/reset_reason_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/rtc_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/serial_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/spi_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/trng_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.4

#11262 Loramac UT fixed
  UNITTESTS/features/lorawan/loramac/Test_LoRaMac.cpp
Labels: ready for merge, release-version: feature branch

#11127 Fix ANALOGIN support for LPC55S69
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/lp_analogin_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_LPCXpresso/PeripheralNames.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_LPCXpresso/PeripheralPins.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_LPCXpresso/mbed_overrides.c
Labels: ready for merge, release-version: 5.13.4

#11142 Relocate USB target specific code to root `targets` directory
  hal/usb/TARGET_Templates/USBPhyHw.h
  hal/usb/TARGET_Templates/USBPhy_template.cpp
  targets/TARGET_Cypress/TARGET_PSOC6/cy_usb_phy.cpp
  targets/TARGET_Cypress/TARGET_PSOC6/cy_usb_phy_hw.h
  targets/TARGET_Freescale/USBEndpoints_Kinetis.h
  targets/TARGET_Freescale/USBPhyHw.h
  targets/TARGET_Freescale/USBPhy_Kinetis.cpp
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/USBPhyHw.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/USBPhy_Nordic.cpp
  targets/TARGET_NXP/USBEndpoints_LPC17_LPC23.h
  targets/TARGET_NXP/USBHAL_LPC17.cpp
  targets/TARGET_NXP/USBPhyHw.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBEndpoints_RZ_A1.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhyHw.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhy_RZ_A1.cpp
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/USBPhy_RZ_A1_Def.h
  targets/TARGET_STM/USBEndpoints_STM32.h
  targets/TARGET_STM/USBPhyHw.h
  targets/TARGET_STM/USBPhy_STM32.cpp
  usb/device/targets/mbed_lib.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11224 Coverity issues fixed
  UNITTESTS/stubs/CellularUtil_stub.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/AT_CellularSMS.cpp
  features/cellular/framework/common/CellularUtil.cpp
  features/cellular/framework/common/CellularUtil.h
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.cpp
  features/lwipstack/LWIPStack.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11169 TLSSocketWrapper::recvfrom sets SocketAddress output variable
  UNITTESTS/features/netsocket/TLSSocketWrapper/test_TLSSocketWrapper.cpp
  UNITTESTS/features/netsocket/TLSSocketWrapper/unittest.cmake
  features/netsocket/TLSSocketWrapper.cpp
Labels: ready for merge, release-version: 5.13.4

#11172 make watchdog kick reset test pass CI (LSI problem)
  TESTS/mbed_drivers/watchdog_reset/main.cpp
  TESTS/mbed_hal/watchdog_reset/main.cpp
Labels: ready for merge, release-version: 5.13.4

#11183 M252KG: Fix kvstore-static_tests failing with OOM
  features/storage/TESTS/kvstore/static_tests/main.cpp
Labels: ready for merge, release-version: 5.13.4

#11188 MIMXRT1050_EVK: Add TRNG support
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/trng_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.4

#11201 Cellular: Fixed improper AT handler setup through virtual calls in co…
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  features/cellular/framework/AT/ATHandler.cpp
  features/cellular/framework/AT/ATHandler.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11211 Review follow-up mstd fixes
  platform/cxxsupport/README.md
  platform/cxxsupport/mstd_functional
Labels: ready for merge, release-version: 5.14.0-rc1

#11212 Change default optimisation level to O1 when exporting to uVision
  tools/export/uvision/uvision.tmpl
Labels: ready for merge, release-version: 5.14.0-rc1

#11216 BLE: make advertising data parser handle early termination
  features/FEATURE_BLE/ble/gap/AdvertisingDataParser.h
Labels: ready for merge, release-version: 5.13.4

#11226 LPC1768 Watchdog & Reset Reason
  targets/TARGET_NXP/TARGET_LPC176X/reset_reason.c
  targets/TARGET_NXP/TARGET_LPC176X/watchdog_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.4

#11237 Fix TT_M3HQ build problem
  targets/TARGET_TT/TARGET_TT_M3HQ/i2c_api.c
  targets/TARGET_TT/TARGET_TT_M3HQ/spi_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.4

#11239 crypto: Copy legacy crypto from Mbed Crypto
  features/lwipstack/lwipopts.h
  features/mbedtls/importer/Makefile
  features/mbedtls/importer/adjust-config.sh
  features/mbedtls/mbed-crypto/importer/Makefile
Labels: ready for merge, release-version: 5.14.0-rc1

#11241 LoRaWAN: Terminate RX when receiving uplink messages
  features/lorawan/lorastack/mac/LoRaMac.cpp
Labels: ready for merge, release-version: 5.13.4

#11247 AT_CellularSMS: set "international" flag in PDU when applicable
  features/cellular/framework/AT/AT_CellularSMS.cpp
Labels: ready for merge, release-version: 5.13.4

#11255 Update NVRAM image for target CY8CMOD-062S2-43012
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_WHD/resources/nvram/TARGET_CY8CMOD_062S2_43012/wifi_nvram_image.h
Labels: ready for merge, release-version: 5.13.4

#11249 Make AT_CellularSMS::list_messages support index 0 in SMS inbox
  UNITTESTS/features/cellular/framework/AT/at_cellularsms/at_cellularsmstest.cpp
  features/cellular/framework/AT/AT_CellularSMS.cpp
Labels: release-version: 5.14.0-rc1

#11067 Add Unittest equeue tests
  TESTS/events/equeue/main.cpp
  UNITTESTS/events/equeue/test_equeue.cpp
  UNITTESTS/events/equeue/unittest.cmake
  UNITTESTS/stubs/EqueuePosix_stub.c
Labels: release-version: 5.13.4

#11236 Force inline Timer::attach() to get rid of floating-point instructions
  TESTS/mbed_hal/rtc/main.cpp
  drivers/Ticker.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11178 ST: Watchdog: Fix timeout registers value calculation
  targets/TARGET_STM/watchdog_api.c
Labels: ready for merge, release-version: 5.13.4

#11204 BLE: add nonscannable connectable type
  features/FEATURE_BLE/ble/gap/Types.h
  features/FEATURE_BLE/ble/pal/GapTypes.h
Labels: ready for merge, release-version: 5.13.4

#11244 Netsocket: Change DNS retry and total attempt counts
  features/netsocket/mbed_lib.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11104 Enterprise security support
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdSTAInterface.cpp
  features/netsocket/nsapi_types.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11194 Greentea testing wifi connect nonblocked
  TESTS/network/wifi/README.md
  TESTS/network/wifi/main.cpp
  TESTS/network/wifi/wifi_connect_nonblock.cpp
  TESTS/network/wifi/wifi_tests.h
Labels: ready for merge, release-version: 5.13.4

#11274 Add ethernet support on NUCLEO_H743ZI board
  features/lwipstack/lwip-sys/arch/lwip_sys_arch.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F2/stm32xx_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/stm32xx_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F7/stm32xx_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32H7/TARGET_NUCLEO_H743ZI/lan8742/lan8742.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32H7/TARGET_NUCLEO_H743ZI/lan8742/lan8742.h
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32H7/stm32h7_eth_init.c
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32H7/stm32xx_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac.cpp
  features/netsocket/emac-drivers/TARGET_STM_EMAC/stm32xx_emac.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/device/TOOLCHAIN_ARM_STD/stm32h743xI.sct
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/device/TOOLCHAIN_GCC_ARM/STM32H743xI.ld
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/device/TOOLCHAIN_IAR/stm32h743xI.icf
  targets/TARGET_STM/TARGET_STM32H7/device/stm32h7xx_hal_conf.h
  targets/targets.json
Labels: ready for merge, release-version: 5.13.4

#10796 NXP: Enable MBED_TICKLESS on various NXP platforms
  features/nanostack/targets/TARGET_NXP/TARGET_KW41Z/NanostackRfPhyKw41z.cpp
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/kinetis_emac.cpp
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_IMX/imx_emac.cpp
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/drivers/fsl_smc.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/drivers/fsl_smc.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/drivers/fsl_smc.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/drivers/fsl_smc.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/drivers/fsl_smc.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/drivers/fsl_smc.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/drivers/fsl_smc.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/drivers/fsl_smc.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/drivers/fsl_smc.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/drivers/fsl_smc.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/drivers/fsl_smc.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/drivers/fsl_smc.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/drivers/fsl_smc.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/drivers/fsl_smc.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/drivers/fsl_smc.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/drivers/fsl_smc.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/drivers/fsl_smc.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/drivers/fsl_smc.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_smc.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/drivers/fsl_smc.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/serial_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/spi_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/sleep.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/serial_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/sleep.c
  targets/targets.json
Labels: ready for merge, release-version: 5.13.4

#11270 Update mbed-coap to version 4.8.1
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/Makefile.test
  features/frameworks/mbed-coap/mbed-coap/sn_coap_header.h
  features/frameworks/mbed-coap/mbed-coap/sn_coap_protocol.h
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/source/include/sn_coap_header_internal.h
  features/frameworks/mbed-coap/source/include/sn_coap_protocol_internal.h
  features/frameworks/mbed-coap/source/sn_coap_builder.c
  features/frameworks/mbed-coap/source/sn_coap_header_check.c
  features/frameworks/mbed-coap/source/sn_coap_parser.c
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.13.4

#11220 Fix cellular dns test with IAR compiled binary
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/tcp/main.cpp
  TESTS/netsocket/tls/main.cpp
  TESTS/netsocket/udp/main.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/at_cellularstacktest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/unittest.cmake
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/device/CellularContext.cpp
Labels: release-version: 5.13.4

#11261 MCUXpresso: Add TICKLESS support for LPC platforms
  targets/targets.json
Labels: ready for merge, release-version: 5.13.4

#11260 Typo in USBSerial.h function prevents compilation
  drivers/USBSerial.h
Labels: ready for merge, release-version: 5.13.4

#11246 Cellular: Fix BG96 AT driver for IPv6
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11267 NXP MCUXpresso: optimize us_ticker for LPC platforms
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/us_ticker.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/us_ticker_defines.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/us_ticker.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/us_ticker_defines.h
Labels: release-version: 5.13.4

#11273 Fix Coverity uninitialized pointer field Thread.h
  rtos/source/Thread.cpp
Labels: ready for merge, release-version: 5.13.4

#11284 K22: Add USBDEVICE support
  targets/targets.json
Labels: ready for merge, release-version: 5.13.4

#11280 Tweak stm_spi_api Coverity warning.
  targets/TARGET_STM/stm_spi_api.c
Labels: ready for merge, release-version: 5.13.4

#11282 K22F: Add FlashIAP for storage
  targets/targets.json
Labels: ready for merge, release-version: 5.13.4

#11215 LPC1768: Make use of the other 32K of RAM
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_ARM_STD/LPC1768.sct
Labels: release-version: 5.13.4

#11250 hal fhss timer: removed unnecessary and potentially unsafe memset
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_fhss_timer.cpp
Labels: release-version: 5.13.4

#11259 FATFS / IAR compilation issue Pe029
  features/storage/filesystem/fat/FATFileSystem.cpp
Labels: ready for merge, release-version: 5.13.4

#11272 mbed fault handler: fix mbed_fault_context parameter
  platform/source/TARGET_CORTEX_M/TOOLCHAIN_ARM/except.S
  platform/source/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.S
  platform/source/TARGET_CORTEX_M/TOOLCHAIN_IAR/except.S
  platform/source/TARGET_CORTEX_M/mbed_fault_handler.c
  platform/source/TARGET_CORTEX_M/mbed_fault_handler.h
Labels: release-version: 5.14.0-rc1

#10907 Port aes cc310 driver
  features/cryptocell/FEATURE_CRYPTOCELL310/aes_alt.c
  features/cryptocell/FEATURE_CRYPTOCELL310/aes_alt.h
  features/cryptocell/FEATURE_CRYPTOCELL310/mbedtls_device.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11245 AT_CellularSMS: allow configuring SMS encoding (7-bit/8-bit) at initialization
  UNITTESTS/stubs/AT_CellularSMS_stub.cpp
  features/cellular/framework/API/CellularSMS.h
  features/cellular/framework/AT/AT_CellularSMS.cpp
  features/cellular/framework/AT/AT_CellularSMS.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11294 KL43Z: Enable FALSHIAP storage
  targets/targets.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11289 Replace TEST_ASSERT_INT_WITHIN usage in netsocket tests
  TESTS/netsocket/tcp/tcpsocket_recv_timeout.cpp
  TESTS/netsocket/udp/udpsocket_echotest_burst.cpp
  TESTS/netsocket/udp/udpsocket_recv_timeout.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11298 Explicitly set rbp_internal_size for TARGET_PSOC6
  features/storage/kvstore/conf/filesystem/mbed_lib.json
  features/storage/kvstore/conf/tdb_external/mbed_lib.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11136 USBDevice: Avoid forcing end device to be derived from USBDevice class
  drivers/USBKeyboard.h
  drivers/USBMouseKeyboard.h
  drivers/USBSerial.h
  drivers/internal/USBDevice.h
  drivers/source/usb/USBDevice.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11269 storage: fix potential memory corruption and check return values
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
  features/storage/filesystem/fat/ChaN/ff.cpp
  features/storage/filesystem/littlefs/littlefs/lfs.c
Labels: ready for merge, release-version: 5.14.0-rc1

#11266 ADC internal temperature support and EMAC header fix
  features/netsocket/emac-drivers/TARGET_STM_EMAC/TARGET_STM32F4/TARGET_MODULE_UBLOX_ODIN_W2/wifi_emac/wifi_emac.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_MBED_CONNECT_ODIN/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_MTB_UBLOX_ODIN_W2/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/TARGET_UBLOX_EVK_ODIN_W2/PinNames.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11301 STM32L4+ : increase system clock from 80 MHz to 120 MHz
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/system_clock.c
Labels: ready for merge, release-version: 5.14.0-rc1

#10750 Changed EventQueue::cancel to return boolean value
  UNITTESTS/stubs/EventQueue_stub.cpp
  UNITTESTS/stubs/equeue_stub.c
  events/EventQueue.h
  events/equeue.h
  events/source/EventQueue.cpp
  events/source/equeue.c
Labels: ready for merge, release-version: 5.14.0-rc1

#11276 Add integration tests
  TESTS/integration/COMMON/common_defines_test.h
  TESTS/integration/COMMON/download_test.cpp
  TESTS/integration/COMMON/download_test.h
  TESTS/integration/COMMON/file_test.cpp
  TESTS/integration/COMMON/file_test.h
  TESTS/integration/COMMON/sample.h
  TESTS/integration/COMMON/sample.txt
  TESTS/integration/COMMON/target_extended.json
  TESTS/integration/fs-single/main.cpp
  TESTS/integration/fs-threaded/main.cpp
  TESTS/integration/net-single/main.cpp
  TESTS/integration/net-threaded/main.cpp
  TESTS/integration/stress-net-fs/main.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11293 K82F: Add USBDEVICE support
  targets/TARGET_Freescale/USBPhy_Kinetis.cpp
  targets/targets.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11265 Add <mstd_tuple> and ARMC5 <tuple>
  platform/cxxsupport/TOOLCHAIN_ARMC5/tuple
  platform/cxxsupport/mstd_iterator
  platform/cxxsupport/mstd_tuple
  platform/cxxsupport/mstd_utility
Labels: ready for merge, release-version: 5.14.0-rc1

#11345 Fix bare-metal configuration to support Pelion Device Management Client
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_fhss_timer.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop_mbed.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop_mutex.c
  rtos/EventFlags.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11181 mbed-mesh-api: Add new API for Wi-SUN configuration
  features/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/mbed-mesh-api/source/include/mesh_system.h
  features/nanostack/mbed-mesh-api/source/include/wisun_tasklet.h
  features/nanostack/mbed-mesh-api/source/mesh_system.c
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: 5.14.0-rc1

#11344 S2-LP: Sync with development repository
  components/802.15.4_RF/stm-s2lp-rf-driver/source/NanostackRfPhys2lp.cpp
  components/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.c
  components/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.h
  components/802.15.4_RF/stm-s2lp-rf-driver/source/s2lpReg.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11322 Updated the LWIP buffer pool size for PSoC6
  features/lwipstack/mbed_lib.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11369 Specify QSPI frequency for more Cypress targets
  components/storage/blockdevice/COMPONENT_QSPIF/mbed_lib.json
Labels: ready for merge

#11302 Enable json overriding ESP8266 default baud rate
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/mbed_lib.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11339 mbed-os/LwIP changes and fixes in auto-IP for Bonjour Conformance Test
  features/lwipstack/lwip/src/core/ipv4/lwip_autoip.c
  features/lwipstack/lwipopts.h
Labels: ready for merge, release-version: 5.14.0-rc1

#11349 TDBStore bugfix: won't rely on flash erase value to detect is a sector erased
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11304 RSSI getter fixed for ESP8266
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11309 MCUXpresso Kinetis SPI drive: Add a delay between CS assertion and first sclk edge
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/spi_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/spi_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL82Z/spi_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/spi_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/spi_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/spi_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/spi_api.c
Labels: release-version: 5.14.0-rc1

#11296 Fix missing offset in TBStore read from flash
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: needs: CI, release-version: 5.14.0-rc1, rollup PR

#11337 Updating SDP-K1 PinNames.h.
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_SDP_K1/PinNames.h
Labels: needs: CI, release-version: 5.14.0-rc1, rollup PR

#11348 Mutex: _count incrementation brought back
  rtos/source/Mutex.cpp
Labels: needs: CI, release-version: 5.14.0-rc1, rollup PR

#11343 ESP8266: Support power pin in custom wiring
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
  components/wifi/esp8266-driver/mbed_lib.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11225 µVision export: Handle more C++ language standards
  tools/export/uvision/__init__.py
Labels: ready for merge, release-version: 5.14.0-rc1

#11359 Update mbed-coap to version 5.1.0
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_coap_header.h
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/source/include/sn_coap_protocol_internal.h
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: BREAKING-CHANGE, ready for merge, release-version: 5.14.0-rc1

#11275 Enable building feature storage with a bare metal profile
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/kvstore/direct_access_devicekey/DirectAccessDevicekey.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11235 minimal-printf should not bypass the retargetting code
  TESTS/mbed_platform/minimal-printf/compliance/mbed_printf.c
  TESTS/mbed_platform/minimal-printf/compliance/mbed_printf.h
  TESTS/mbed_platform/minimal-printf/compliance/test_app.json
  platform/mbed_lib.json
  platform/source/minimal-printf/README.md
  platform/source/minimal-printf/mbed_printf_implementation.c
  platform/source/minimal-printf/mbed_printf_wrapper.c
  tools/profiles/extensions/minimal-printf.json
Labels: CI finished, ready for merge, release-version: 5.14.0-rc1

#11354 Update linker scripts based on latest PDL 1.3
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/device/TOOLCHAIN_ARM/cy8c6xx7_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/device/TOOLCHAIN_GCC_ARM/cy8c6xx7_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/device/TOOLCHAIN_IAR/cy8c6xx7_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/device/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/device/TOOLCHAIN_ARM/cy8c6xx7_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/device/TOOLCHAIN_GCC_ARM/cy8c6xx7_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/device/TOOLCHAIN_IAR/cy8c6xx7_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/device/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TOOLCHAIN_ARM/cy8c6xxa_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TOOLCHAIN_GCC_ARM/cy8c6xxa_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/TOOLCHAIN_IAR/cy8c6xxa_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062S2_43012/device/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062_4343W/device/TOOLCHAIN_ARM/cy8c6xxa_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062_4343W/device/TOOLCHAIN_GCC_ARM/cy8c6xxa_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062_4343W/device/TOOLCHAIN_IAR/cy8c6xxa_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062_4343W/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CMOD_062_4343W/device/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/device/TOOLCHAIN_ARM/cy8c6xx7_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/device/TOOLCHAIN_GCC_ARM/cy8c6xx7_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/device/TOOLCHAIN_IAR/cy8c6xx7_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/device/system_psoc6_cm4.c
  targets/targets.json
Labels: ready for merge, release-version: 5.14.0-rc1

#11356 Fix WHD link state change event handling
  features/netsocket/emac-drivers/TARGET_WHD/interface/WhdSTAInterface.cpp
  features/netsocket/emac-drivers/TARGET_WHD/interface/whd_emac.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11355 Initial support for Serial Flash on PSoC Devices
  targets/TARGET_Cypress/TARGET_PSOC6/common/cybsp_serial_flash.c
  targets/TARGET_Cypress/TARGET_PSOC6/common/cybsp_serial_flash.h
  targets/TARGET_Cypress/TARGET_PSOC6/common/cybsp_serial_flash_prog.c
  targets/TARGET_Cypress/TARGET_PSOC6/mbed_overrides.c
Labels: ready for merge, release-version: 5.14.0-rc1

#11353 Add reserved resources metadata to Cypress BSPs
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_4343W/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_063_BLE/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
Labels: ready for merge, release-version: 5.14.0-rc1

#10711 Add i2cee-driver to components
  components/storage/blockdevice/COMPONENT_I2CEE/.travis.yml
  components/storage/blockdevice/COMPONENT_I2CEE/I2CEEBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_I2CEE/I2CEEBlockDevice.h
  components/storage/blockdevice/COMPONENT_I2CEE/LICENSE.md
  components/storage/blockdevice/COMPONENT_I2CEE/README.md
  components/storage/blockdevice/COMPONENT_I2CEE/TESTS/block_device/i2cee/main.cpp
Labels: ready for merge, release-version: 5.14.0-rc1

#11018 PSOC6_SB: initial integration of Cypress Secure Boot target CY8CPROTO_064_SB
  LICENSE.md
  features/storage/nvstore/mbed_lib.json
  requirements.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.timestamp
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_notices.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/qspi_config.cfg
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/COMPONENT_BSP_DESIGN_MODUS/design.modus
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/PeripheralNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/PinNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/cybsp.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/cybsp.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/cybsp_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/device/TOOLCHAIN_ARM/cyb06xx7_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/device/TOOLCHAIN_ARM/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/device/TOOLCHAIN_GCC_ARM/cyb06xx7_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/device/TOOLCHAIN_GCC_ARM/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/device/TOOLCHAIN_IAR/cyb06xx7_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/device/TOOLCHAIN_IAR/startup_psoc6_01_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/device/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/secure_image_parameters.json
  targets/TARGET_Cypress/TARGET_PSOC6/common/cybsp_serial_flash_prog.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/devices/include/cyb06447bzi_d54.h
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/.gitignore
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/encrypted_image_runner.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/aes_cipher.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/create_aesHeader.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/ecc_kdf.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/imgtool.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/imgtool/__init__.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/imgtool/image.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/imgtool/keys/__init__.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/imgtool/keys/ecdsa.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/imgtool/keys/ecdsa_test.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/imgtool/keys/general.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/imgtool/keys/rsa.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/imgtool/keys/rsa_test.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/imgtool/imgtool/version.py
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/policy/example_cert.pem
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/policy/policy_single_stage_CM4.json
  targets/TARGET_Cypress/TARGET_PSOC6/sb-tools/policy/policy_single_stage_CM4_smif.json
  targets/targets.json
  tools/targets/PSOC6.py
  tools/targets/__init__.py
Labels: ready for merge, release-version: 5.14.0-rc1

#11342 add queue static allocation support
  TESTS/events/equeue/main.cpp
  TESTS/events/queue/main.cpp
  UNITTESTS/events/equeue/test_equeue.cpp
  UNITTESTS/stubs/EqueuePosix_stub.c
  events/EventQueue.h
  events/UserAllocatedEvent.h
  events/equeue.h
  events/mbed_events.h
  events/source/EventQueue.cpp
  events/source/equeue.c
  events/source/equeue_posix.c
  events/source/tests/tests.c
Labels: ready for merge, release-version: 5.14.0-rc1
