Repository ARMmbed/mbed-os, pull requests merged in 2020-05, with the labels that each got.

#12876 802.15.4 STM S2LP driver update
  components/802.15.4_RF/stm-s2lp-rf-driver/mbed_lib.json
  components/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver/NanostackRfPhys2lp.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12735 Make MUSCA B1 and MUSCA A1 TF-M ready
  components/TARGET_PSA/services/attestation/COMPONENT_PSA_SRV_IMPL/attest_boot_status_loader.c
  platform/mbed_lib.json
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/TOOLCHAIN_GCC_ARM/musca_ns.ld
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/device_cfg.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/partition/flash_layout.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/partition/image_macros_preprocessed.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/partition/region_defs.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/device/TOOLCHAIN_GCC_ARM/musca_ns.ld
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/device/device_cfg.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/device/device_definition.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/partition/flash_layout.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/partition/image_macros_preprocessed.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/partition/region_defs.h
  tools/psa/tfm/bin_utils/assemble.py
  tools/targets/ARM_MUSCA_A1.py
  tools/targets/ARM_MUSCA_B1.py
Labels: ready for merge, release-version: 6.0.0-beta-1

#12913 usbcdc: provide doxygen only macro for doxy builder
  drivers/USBCDC_ECM.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12883 [feature-wisun] Add getsockopt option to read network property
  UNITTESTS/features/netsocket/InternetSocket/test_InternetSocket.cpp
  features/nanostack/nanostack-interface/Nanostack.cpp
  features/netsocket/InternetSocket.cpp
  features/netsocket/InternetSocket.h
  features/netsocket/nsapi_types.h
Labels: ready for merge, release-version: feature branch

#12919 ExhaustibleBlockDevice: revert commit 10481f2
  UNITTESTS/features/storage/blockdevice/ExhaustibleBlockDevice/test_ExhaustibleBlockDevice.cpp
  features/storage/blockdevice/ExhaustibleBlockDevice.cpp
  features/storage/blockdevice/ExhaustibleBlockDevice.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12849 TEST: Update example test
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12924 STM32F4 bypass PLL configuration when already done by bootloader
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/system_clock.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12931 [feature-wisun] Add possibility to configure Mesh MAC neighbourtable size.
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/nd_tasklet.c
  features/nanostack/mbed-mesh-api/source/thread_tasklet.c
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: feature branch

#12938 Correct core RTOS sleep routine timing
  platform/source/mbed_os_timer.cpp
  platform/source/mbed_os_timer.h
  rtos/source/TARGET_CORTEX/mbed_rtx_idle.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12941 Correct Timeout rescheduling
  drivers/source/Timeout.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12934 [mbed-os-5.15]Add possibility to configure Mesh MAC neighbourtable size.
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/nd_tasklet.c
  features/nanostack/mbed-mesh-api/source/thread_tasklet.c
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: 5.15.4

#12933 Backport Arm C static RAM fix to Mbed OS 5.15 (#12462) (Mbed OS 5.15)
  tools/memap.py
Labels: ready for merge, release-version: 5.15.4

#12915 Optimise HAL_GetTick API
  targets/TARGET_STM/hal_tick_overrides.c
  targets/TARGET_STM/us_ticker.c
Labels: ready for merge, release-version: 6.0.0-rc1

#12856 ST Boards: Remove uARM tooolchain support
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/device/TOOLCHAIN_ARM_MICRO/startup_stm32f303xe.S
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/device/TOOLCHAIN_ARM_MICRO/stm32f303xe.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TOOLCHAIN_ARM_MICRO/startup_stm32f401xe.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TOOLCHAIN_ARM_MICRO/stm32f401xe.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TOOLCHAIN_ARM_STD/stm32f401xe.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TOOLCHAIN_ARM_MICRO/startup_stm32f411xe.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TOOLCHAIN_ARM_MICRO/stm32f411re.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_ARM_MICRO/startup_stm32l475xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_ARM_MICRO/stm32l475xx.sct
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-rc1

#12801 Add base support for STM32H745
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/TARGET_GENERIC_H745I_CM4/TOOLCHAIN_ARM_STD/startup_stm32h745xx.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/TARGET_GENERIC_H745I_CM4/TOOLCHAIN_ARM_STD/stm32h745xI_CM4.sct
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/TARGET_GENERIC_H745I_CM4/TOOLCHAIN_GCC_ARM/STM32H745xI_CM4.ld
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/TARGET_GENERIC_H745I_CM4/TOOLCHAIN_GCC_ARM/startup_stm32h745xx.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/TARGET_GENERIC_H745I_CM4/TOOLCHAIN_IAR/startup_stm32h745xx.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/TARGET_GENERIC_H745I_CM4/TOOLCHAIN_IAR/stm32h745xI_CM4.icf
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/TARGET_GENERIC_H745I_CM7/TOOLCHAIN_ARM_STD/startup_stm32h745xx.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/TARGET_GENERIC_H745I_CM7/TOOLCHAIN_ARM_STD/stm32h745xI.sct
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/TARGET_GENERIC_H745I_CM7/TOOLCHAIN_GCC_ARM/STM32H745xI.ld
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/TARGET_GENERIC_H745I_CM7/TOOLCHAIN_GCC_ARM/startup_stm32h745xx.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/TARGET_GENERIC_H745I_CM7/TOOLCHAIN_IAR/startup_stm32h747xx.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/TARGET_GENERIC_H745I/TARGET_GENERIC_H745I_CM7/TOOLCHAIN_IAR/stm32h747xI.icf
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/device/stm32h745xx.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/flash_data.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/system_clock.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/system_stm32h7xx.c
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-rc1, scope: new-target

#12805 Tests: USBSerial: Handle minimal printf limitations
  TESTS/host_tests/usb_device_serial.py
  TESTS/usb_device/serial/main.cpp
Labels: ready for merge, release-version: 6.0.0-rc1

#12916 USB basic and hid greentea test cleanup and enable to the bare metal profile
  TESTS/configs/baremetal.json
  TESTS/host_tests/pyusb_basic.py
  TESTS/usb_device/basic/USBEndpointTester.cpp
  TESTS/usb_device/basic/USBEndpointTester.h
  TESTS/usb_device/basic/USBTester.cpp
  TESTS/usb_device/basic/USBTester.h
  TESTS/usb_device/basic/main.cpp
  TESTS/usb_device/hid/main.cpp
Labels: ready for merge, release-version: 6.0.0-rc1

#12944 Fix the USB MSD greentea host side pyusb_msd.py script
  TESTS/host_tests/pyusb_msd.py
Labels: ready for merge, release-version: 6.0.0-rc1

#12808 KVStore: Remove incorrect check with non-default configuration of FLASHIAP
  features/storage/kvstore/conf/kv_config.cpp
Labels: ready for merge, release-version: 6.0.0-rc1

#12865 Nuvoton: Support bare-metal profile on NANO130 and M453
  targets/TARGET_NUVOTON/TARGET_M451/device/M451_mem.h
  targets/TARGET_NUVOTON/TARGET_M451/device/M451_mem.icf.h
  targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_ARM/M453.sct
  targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_ARM_MICRO/M453.sct
  targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_ARM_STD/M453.sct
  targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_GCC_ARM/M453.ld
  targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_IAR/M453.icf
  targets/TARGET_NUVOTON/TARGET_M451/flash_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/device/NANO100_mem.h
  targets/TARGET_NUVOTON/TARGET_NANO100/device/NANO100_mem.icf.h
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_ARM/NANO130.sct
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_ARM_MICRO/NANO130.sct
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_ARM_STD/NANO130.sct
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_GCC_ARM/NANO130.ld
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_IAR/NANO130.icf
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-rc1

#12875 KVStore: Fix buffer overrun when device key size doesn't match
  features/device_key/TESTS/device_key/functionality/main.cpp
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: ready for merge, release-version: 6.0.0-rc1

#12888 Musca-B1: Fix I2C pinmap array
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/pinmap_ns.c
Labels: ready for merge, release-version: 6.0.0-rc1

#12890 [SX1272 & SX1276 Driver] Fix Fifo Pointer in Continuous Mode
  components/lora/COMPONENT_SX1272/SX1272_LoRaRadio.cpp
  components/lora/COMPONENT_SX1276/SX1276_LoRaRadio.cpp
Labels: ready for merge, release-version: 6.0.0-rc1

#12896 Nuvoton: Fix watchdog reset failure on meeting Hard Fault
  targets/TARGET_NUVOTON/TARGET_M451/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_M480/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/watchdog_api.c
Labels: ready for merge, release-version: 6.0.0-rc1

#12902 USB: Convert to Chrono
  drivers/internal/AsyncOp.h
  drivers/source/usb/AsyncOp.cpp
  drivers/source/usb/USBMouse.cpp
  drivers/source/usb/USBMouseKeyboard.cpp
Labels: ready for merge, release-version: 6.0.0-rc1

#12904 SDBlockDevice: Convert to Chrono
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.h
Labels: ready for merge, release-version: 6.0.0-rc1

#12947 Fix setting the QE bit on ISSI Flash memories
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
Labels: ready for merge, release-version: 6.0.0-rc1

#12945 Cleaning up PinNames.h for SDP-K1 board.
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_SDP_K1/PinNames.h
Labels: ready for merge, release-version: 6.0.0-rc1

#12906 Work around C++14 assert problem
  platform/mbed_chrono.h
  platform/mbed_toolchain.h
Labels: ready for merge, release-version: 6.0.0-rc1

#12914 Add possibility to configure Mesh MAC neighbourtable size.
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/nd_tasklet.c
  features/nanostack/mbed-mesh-api/source/thread_tasklet.c
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: 6.0.0-rc1

#12923 Nuvoton: Refine more on watchdog HAL
  targets/TARGET_NUVOTON/TARGET_M451/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_M480/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/watchdog_api.c
Labels: ready for merge, release-version: 6.0.0-rc1

#12959 STM32: targets json rework
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-rc1

#12901 Rationalise Mail/Queue/MemoryPool timing APIs
  TESTS/mbedmicro-rtos-mbed/MemoryPool/main.cpp
  TESTS/mbedmicro-rtos-mbed/mail/main.cpp
  TESTS/mbedmicro-rtos-mbed/queue/main.cpp
  TESTS/mbedmicro-rtos-mbed/threads/main.cpp
  rtos/Mail.h
  rtos/MemoryPool.h
  rtos/Queue.h
Labels: ready for merge, release-version: 6.0.0-rc1

#12836 Wi-SUN added regulatory domain Brazil
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.h
Labels: ready for merge, release-version: 6.0.0-rc1

#12956 NRFCordioHCIDriver: remove idle_hook (and RTOS dependency)
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/NRFCordioHCIDriver.cpp
Labels: ready for merge, release-version: 6.0.0-rc1

#12967 Update DOXYGEN_FRONTPAGE.md
  DOXYGEN_FRONTPAGE.md
Labels: TEST-PR, mergify skip, release-type: patch

#12968 Update LICENSE-apache-2.0.txt
  LICENSE-apache-2.0.txt
Labels: TEST-PR, mergify skip, release-type: patch

#12958 Fix vector table bug when using bootloader on STM32WB55
  targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/system_stm32wbxx.c
Labels: ready for merge, release-version: 6.0.0-rc1

#12721 ESP8266: static address configuration and dhcp enable/disable added
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
Labels: ready for merge, release-version: 6.0.0-rc1

#12428 nsapi_dns: Convert to Chrono
  UNITTESTS/stubs/Kernel_stub.cpp
  features/netsocket/nsapi_dns.cpp
Labels: ready for merge, release-version: 6.0.0-rc1

#12432 NFC: Convert to Chrono
  features/nfc/source/nfc/NFCController.cpp
Labels: needs: CI

#12433 ESP8266: Convert to Chrono
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
Labels: ready for merge, release-version: 6.0.0-rc1

#12971 MemoryPool fixes
  rtos/MemoryPool.h
Labels: ready for merge, release-version: 6.0.0-rc1

#12951 Clean-up S2LP driver configuration
  components/802.15.4_RF/stm-s2lp-rf-driver/mbed_lib.json
  components/802.15.4_RF/stm-s2lp-rf-driver/source/NanostackRfPhys2lp.cpp
  components/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver/NanostackRfPhys2lp.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_MTB_STM_S2LP/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_MTB_STM_S2LP/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_MTB_STM_S2LP/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_MTB_STM_S2LP/system_clock.c
  targets/targets.json
  tools/test_configs/Wi-SUNInterface.json
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-rc1

#12903 Nanostack HAL: Convert to Chrono
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_fhss_timer.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer.cpp
Labels: ready for merge, release-version: 6.0.0-rc1

#12942 Add Timeout rescheduling test
  TESTS/mbed_drivers/lp_timeout/main.cpp
  TESTS/mbed_drivers/timeout/main.cpp
  TESTS/mbed_drivers/timeout/timeout_tests.h
Labels: needs: review, release-version: 6.0.0-rc1

#12623 LPC1114: baremetal profile support
  TESTS/mbed_hal/stack_size_unification/main.cpp
  features/storage/TESTS/blockdevice/heap_block_device/main.cpp
  features/storage/TESTS/blockdevice/mbr_block_device/main.cpp
  features/storage/TESTS/blockdevice/util_block_device/main.cpp
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/TOOLCHAIN_ARM_STD/TARGET_LPC11XX/LPC1114.sct
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11XX/LPC1114.ld
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/TOOLCHAIN_GCC_ARM/startup_LPC11xx.S
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/cmsis_nvic.c
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/us_ticker.c
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-rc1

#12981 IOTSTOR-1044 - SPIFBlockDevice is broken in Mbed OS master(6),
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
Labels: ready for merge, release-version: 6.0.0-rc1

#12984 Disable mbed 2 and unsupported targets
  targets/targets.json
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-rc1

#12978 Update psoc6pdl to v1.5.2
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/RELEASE.md
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/devices/include/psoc6a256k.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/drivers/include/cy_ctb.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/drivers/include/cy_sd_host.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/drivers/include/cy_syslib.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/drivers/source/cy_ctb.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/drivers/source/cy_sd_host.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/drivers/source/cy_syslib.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/personalities/peripheral/connectivity_wifi-1.0.cypersonality
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/personalities/platform/eco-1.2.cypersonality
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/personalities_2.0/peripheral/connectivity_wifi-1.0.cypersonality
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/udd/devices/MXS40/PSoC6A256K/PSoC6A256K/base/view.xml
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/udd/devices/MXS40/PSoC6A256K/PSoC6A256K/info.xml
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/udd/devices/MXS40/PSoC6A256K/info.xml
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/udd/devices/MXS40/PSoC6A2M/studio/smartio.cysem
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/udd/devices/MXS40/PSoC6A2M/studio/smartio.cyvis
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/udd/devices/MXS40/PSoC6A2M/studio/smartioResourceMap.txt
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/udd/devices/MXS40/PSoC6A512K/studio/smartio.cysem
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/udd/devices/MXS40/PSoC6A512K/studio/smartio.cyvis
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/udd/devices/MXS40/PSoC6A512K/studio/smartioResourceMap.txt
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/udd/devices/MXS40/PSoC6ABLE2/studio/smartio.cysem
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/udd/devices/MXS40/PSoC6ABLE2/studio/smartio.cyvis
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/udd/devices/MXS40/PSoC6ABLE2/studio/smartioResourceMap.txt
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6pdl/version.xml
Labels: ready for merge, release-version: 6.0.0-rc1

#12982 build api: fix release version
  targets/targets.json
  tools/build_api.py
Labels: ready for merge, release-version: 6.0.0-rc1

#12995 build tools: fix target toolchain
  targets/targets.json
  tools/build_api.py
Labels: ready for merge, release-version: 6.0.0-rc1

#13007 tools: Support default_lib and c_lib
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 6.0.0-rc2

#13008 tools: Warn when ARMC5 is no longer supported
  tools/build_api.py
  tools/toolchains/arm.py
Labels: ready for merge, release-version: 6.0.0-rc2
