Repository ARMmbed/mbed-os, pull requests merged in 2020-06, with the labels that each got.

#13054 Update mbed version number
  platform/mbed_version.h
Labels: ready for merge

#12973 Cellular: Enable tac info for ALT1250
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP.cpp
Labels: ready for merge, release-type: patch

#12985 Update CYSBSYSKIT_01
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/inc/scl_common.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/src/IPC/scl_ipc.c
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/src/include/scl_version.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/cybsp.c
Labels: devices: cypress, ready for merge, release-type: patch

#12979 stack_size_unification test: set expected stack sizes from config
  TESTS/mbed_hal/stack_size_unification/main.cpp
  rtos/source/TARGET_CORTEX/mbed_lib.json
  targets/TARGET_TOSHIBA/mbed_rtx.h
Labels: ready for merge, release-type: patch

#12983 Mutex::unlock - decrement _count inside lock
  rtos/source/Mutex.cpp
Labels: ready for merge, release-type: patch

#13064 nxp: fix vector redefinition from CMSIS
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/fsl_common.c
Labels: ready for merge, release-type: patch

#12988 OS timer uses LPTICKER by default, then USTICKER
  platform/source/mbed_os_timer.cpp
  rtos/source/TARGET_CORTEX/mbed_rtx_idle.cpp
Labels: ready for merge, release-type: patch

#13052 BLE: fix conn params update
  features/FEATURE_BLE/source/generic/GenericGap.tpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalGap.tpp
Labels: ready for merge, release-type: patch

#12991 Nuvoton: Support EMAC bus reset as while bus err
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/TARGET_M480/m480_eth.c
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/TARGET_NUC472/nuc472_eth.c
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/numaker_emac.cpp
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/numaker_emac.h
Labels: ready for merge, release-type: patch

#13013 Cellular: Fix packet data registration after CREG
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: ready for merge, release-type: patch

#13014 DISCO_H747I_CM4 is supporting now hex format
  targets/TARGET_STM/TARGET_STM32H7/README.md
  targets/targets.json
Labels: ready for merge, release-type: patch

#13048 Allowed to set Wi-SUN certificates in DISCONNECTED state
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-type: patch

#13030 Fix ThisThread::get_name definition
  TESTS/mbedmicro-rtos-mbed/threads/main.cpp
  rtos/source/ThisThread.cpp
Labels: ready for merge, release-type: patch

#13015 Force callback non-trivial for IAR
  platform/Callback.h
  platform/mbed_lib.json
Labels: ready for merge, release-type: patch

#13041 Cordio: put parentheses to correct order of precedence in ternary expressions
  features/FEATURE_BLE/targets/TARGET_CORDIO_LL/stack/controller/sources/ble/lctr/lctr_int_adv_master_ae.h
  features/FEATURE_BLE/targets/TARGET_CORDIO_LL/stack/controller/sources/ble/lctr/lctr_isr_conn_slave.c
  features/FEATURE_BLE/targets/TARGET_CORDIO_LL/stack/controller/sources/ble/lctr/lctr_main_adv_master_ae.c
Labels: ready for merge, release-type: patch

#13043 NRF serial: Use nrf_uarte_event_t enum to avoid implicit conversion
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
Labels: ready for merge, release-type: patch

#13047 NRF: Migrate ARM Compiler 5 feature re-locate zero initialized variables
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/reloc_vector_table.c
Labels: ready for merge, release-type: patch

#12996 STM32F412 bypass PLL configuration when already done by bootloader
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_NUCLEO_F412ZG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/system_clock.c
Labels: ready for merge, release-type: patch

#13035 Fix capacity check when service data are added to BLE advertising payload
  features/FEATURE_BLE/source/gap/AdvertisingDataBuilder.cpp
Labels: ready for merge, release-type: patch

#13019 Documentation update - MBRBlockDevice::partition type parameter
  features/storage/blockdevice/MBRBlockDevice.h
Labels: release-type: patch

#13045 CYESKIT_064B0S2_4343W: Remove parentheses from arduino pins
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/cybsp_types.h
Labels: devices: cypress, ready for merge, release-type: patch

#13044 NRF: fix implicit declarations
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_crypto.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/common_rtc.h
Labels: ready for merge, release-type: patch

#13042 Ensure all overridden virtual functions are marked with `override`
  features/lwipstack/LWIPStack.h
  features/nanostack/nanostack-interface/Nanostack.h
  features/netsocket/ppp/ppp_service.h
Labels: ready for merge, release-type: patch

#13034 ST boards: Fix sleep tracing
  rtos/source/TARGET_CORTEX/mbed_boot.c
  rtos/source/TARGET_CORTEX/mbed_boot.h
  rtos/source/TARGET_CORTEX/mbed_rtos_rtx.c
Labels: ready for merge, release-type: patch

#13016 tests-mbed_hal-rtc patch to match IAR compilation issue
  TESTS/mbed_hal/rtc/main.cpp
Labels: ready for merge, release-type: patch

#13022 STM32: add weak TargetBSP_Init function
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/system_stm32h7xx.c
  targets/TARGET_STM/mbed_overrides.c
Labels: ready for merge, release-type: patch

#12882 [Mbed OS 5.15] Add getsockopt option to read network property
  UNITTESTS/features/netsocket/InternetSocket/test_InternetSocket.cpp
  features/nanostack/nanostack-interface/Nanostack.cpp
  features/netsocket/InternetSocket.cpp
  features/netsocket/InternetSocket.h
  features/netsocket/nsapi_types.h
Labels: Release review required, ready for merge, release-version: 5.15.4

#12892 Add new configuration parameters to Wi-SUN network interface and Border Router class (Mbed OS 5.15)
  features/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackPPPInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  features/nanostack/mbed-mesh-api/source/NanostackPPPInterface.cpp
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/mbed-mesh-api/source/include/wisun_tasklet.h
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: Release review required, ready for merge, release-version: 5.15.4

#12894 Nanostack: Add config for Wi-SUN device type (Mbed OS 5.15)
  features/nanostack/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: 5.15.4

#12895 Added kv store adaptation to nanostack file interface (Mbed OS 5.15)
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/mbed_lib.json
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_file_system_api.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_file_system_api.h
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_hal_init.c
Labels: ready for merge, release-version: 5.15.4

#12970 Nuvoton: Refine more on watchdog HAL (5.15)
  targets/TARGET_NUVOTON/TARGET_M451/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_M480/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/watchdog_api.c
Labels: Release review required, ready for merge

#12972 Alt1250 enable tac info for registration status (mbed 5.15)
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP.cpp
Labels: ready for merge, release-version: 5.15.4

#12986 M2351: Enable non-PSA minimal secure build (5.15)
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NPSA_NS/TARGET_NU_PREBUILD_SECURE/NuMaker-mbed-TZ-secure-example.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NPSA_NS/TARGET_NU_PREBUILD_SECURE/README.md
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NPSA_NS/TARGET_NU_PREBUILD_SECURE/cmse_lib.o
  targets/targets.json
Labels: Release review required, ready for merge, release-version: 5.15.4

#13031 Mbed OS 5.15: Warn on unrecognised error
  tools/config/__init__.py
Labels: Release review required, ready for merge, release-version: 5.15.4

#13077 Python reference equality changed to value equality
  tools/config/__init__.py
Labels: ready for merge, release-type: patch

#13066 mergify: add release type
  .mergify.yml
Labels: ready for merge, release-type: patch

#12893 Add Wi-SUN statistics interface (Mbed OS 5.15)
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/mbed-mesh-api/source/include/wisun_tasklet.h
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: 5.15.4

#12969 Nuvoton: Fix watchdog reset failure on meeting Hard Fault (5.15)
  targets/TARGET_NUVOTON/TARGET_M451/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_M480/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/watchdog_api.c
Labels: ready for merge, release-version: 5.15.4

#13053 STM32 more information in README file
  targets/TARGET_STM/README.md
  targets/TARGET_STM/TARGET_STM32WB/README.md
Labels: ready for merge, release-type: patch

#13002 Deprecate MBED_STATIC_ASSERT and MBED_STRUCT_STATIC_ASSERT for built-in keyword
  platform/mbed_assert.h
Labels: ready for merge, release-type: patch

#13063 [feature-wisun] targets:lpspi and uart_3: Update the lpspi driver and add uart_3 support
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/spi_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PeripheralPins.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_lpspi.c
Labels: ready for merge, release-version: feature branch

#13090 STM: move us_ticker_defines.h include
  targets/TARGET_STM/device.h
  targets/TARGET_STM/hal_tick_overrides.c
Labels: ready for merge, release-type: patch

#13089 Add a coverage_patterns kwarg to ARM_MICRO
  tools/toolchains/arm.py
Labels: ready for merge, release-type: patch

#13081 Reinstate post build hooks for legacy targets
  tools/targets/__init__.py
Labels: ready for merge, release-type: patch

#13069 Cellular: Fix unittest for CellularNetwork
  UNITTESTS/features/cellular/framework/AT/at_cellularnetwork/at_cellularnetworktest.cpp
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
Labels: ready for merge, release-type: patch

#13060 BLE: fix direct advertising on Cordio
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioPalGap.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalGap.tpp
Labels: ready for merge, release-type: patch

#13055 BLE: RF tester commands (and Cordio unhandled command complete)
  features/FEATURE_BLE/targets/TARGET_CORDIO/doc/HCIAbstraction.md
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/CordioHCIDriver.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/CordioHCIDriver.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/mbed_lib.json
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioBLE.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/include/dm_api.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/include/hci_api.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/hci/dual_chip/hci_evt.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/dm/dm_dev.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/dm/dm_main.c
Labels: ready for merge, release-type: feature

#13037 BLE: Fix privacy and signing handling in Security Manager
  features/FEATURE_BLE/ble/SecurityManager.h
  features/FEATURE_BLE/ble/generic/FileSecurityDb.h
  features/FEATURE_BLE/ble/generic/GenericSecurityManager.h
  features/FEATURE_BLE/ble/generic/MemorySecurityDb.h
  features/FEATURE_BLE/ble/generic/SecurityDb.h
  features/FEATURE_BLE/ble/pal/PalSecurityManager.h
  features/FEATURE_BLE/mbed_lib.json
  features/FEATURE_BLE/source/generic/FileSecurityDb.cpp
  features/FEATURE_BLE/source/generic/GenericSecurityManager.tpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioPalSecurityManager.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalSecurityManager.tpp
Labels: ready for merge, release-type: feature

#13039 BLE: remove limitation in the Cordio to update adv payload
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/dm/dm_adv_leg.c
Labels: ready for merge, release-type: patch

#12615 FPGA UART test cases addition with 7 and 9 bits data length
  TESTS/configs/fpga.json
  TESTS/mbed_hal_fpga_ci_test_shield/README.md
  TESTS/mbed_hal_fpga_ci_test_shield/fpga_test_shield.jpg
  TESTS/mbed_hal_fpga_ci_test_shield/uart/main.cpp
  targets/targets.json
Labels: ready for merge, release-type: patch

#13084 [feature-wisun] Added Wi-SUN interface and Border Router API.
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-version: feature branch

#13073 STM32H7: FPGA tests support
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI2/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/analogin_device.c
  targets/TARGET_STM/gpio_api.c
Labels: ready for merge, release-type: patch

#12772 Add enum class flag definition to platform
  platform/mbed_enum_flags.h
Labels: ready for merge, release-type: feature

#13091 STM32 baremetal support step3/3 (F2/F4)
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/TOOLCHAIN_ARM/stm32f207xx.sct
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/TOOLCHAIN_GCC_ARM/STM32F207ZGTx_FLASH.ld
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/TOOLCHAIN_IAR/stm32f207xx.icf
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TOOLCHAIN_ARM/stm32f401xe.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TOOLCHAIN_GCC_ARM/STM32F401XE.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TOOLCHAIN_IAR/stm32f401xe.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TOOLCHAIN_ARM/stm32f411re.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TOOLCHAIN_GCC_ARM/STM32F411XE.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TOOLCHAIN_IAR/stm32f411xe.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TOOLCHAIN_ARM/stm32f412xg.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TOOLCHAIN_GCC_ARM/STM32F412xG.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TOOLCHAIN_IAR/stm32f412xx.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_NUCLEO_F413ZH/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TOOLCHAIN_ARM/stm32f413xh.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TOOLCHAIN_GCC_ARM/STM32F413xH.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TOOLCHAIN_IAR/stm32f413xx.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_DISCO_F429ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TOOLCHAIN_ARM/stm32f429xx.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TOOLCHAIN_GCC_ARM/STM32F429xI.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TOOLCHAIN_IAR/stm32f429xx_flash.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TOOLCHAIN_ARM/stm32f439xx.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TOOLCHAIN_GCC_ARM/STM32F439ZI.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TOOLCHAIN_IAR/stm32f439xx_flash.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446ZE/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TOOLCHAIN_ARM/stm32f446xx.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TOOLCHAIN_GCC_ARM/STM32F446XE.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TOOLCHAIN_IAR/stm32f446xx.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_DISCO_F469NI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TOOLCHAIN_ARM/stm32f469xx.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TOOLCHAIN_GCC_ARM/STM32F469XI.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TOOLCHAIN_IAR/stm32f469xx.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/cmsis_nvic.h
Labels: ready for merge, release-type: patch

#13001 STM32 baremetal support step2 (L1/L4/WB)
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/mbox_def.h
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/shci.c
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/shci.h
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/shci_tl.c
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/shci_tl.h
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/stm32_wpan_common.h
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/stm_list.c
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/stm_list.h
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/tl.h
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/tl_mbox.c
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/hw_ipcc.c
  targets/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device/TOOLCHAIN_ARM/stm32l152re.sct
  targets/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device/TOOLCHAIN_GCC_ARM/STM32L152XE.ld
  targets/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device/TOOLCHAIN_IAR/stm32l152xe.icf
  targets/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/TOOLCHAIN_ARM/stm32l432xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/TOOLCHAIN_GCC_ARM/STM32L432XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/TOOLCHAIN_IAR/stm32l432xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/device/TOOLCHAIN_ARM/stm32l433xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/device/TOOLCHAIN_GCC_ARM/STM32L433XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/device/TOOLCHAIN_IAR/stm32l433xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L452xE/device/TOOLCHAIN_ARM/stm32l452xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L452xE/device/TOOLCHAIN_GCC_ARM/STM32L452XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L452xE/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_ARM/stm32l475xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_GCC_ARM/STM32L475XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_IAR/stm32l475xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_ARM/stm32l476xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_GCC_ARM/STM32L476XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_IAR/stm32l476xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_ARM/stm32l486xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_GCC_ARM/STM32L486XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_IAR/stm32l486xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/device/TOOLCHAIN_ARM/stm32l496xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/device/TOOLCHAIN_GCC_ARM/STM32L496XX.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/device/TOOLCHAIN_IAR/stm32l496xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/TOOLCHAIN_ARM/stm32l4r5xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/TOOLCHAIN_GCC_ARM/stm32l4r5xx.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/TOOLCHAIN_IAR/stm32l4r5xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/TOOLCHAIN_ARM/stm32l4r9xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/TOOLCHAIN_GCC_ARM/stm32l4r9xx.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/TOOLCHAIN_IAR/stm32l4r9xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/hw.h
  targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/otp.c
  targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/otp.h
  targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/utilities_common.h
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xx/cmsis_nvic.h
  targets/targets.json
Labels: ready for merge, release-type: patch

#13072 [mbed-os-5.15] Allowed to set Wi-SUN certificates in DISCONNECTED state
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: mergify skip, needs: CI, release-version: 5.15.4

#13093 UNITTESTS: Fix TestPPPInterface::get_interface_name
  UNITTESTS/features/netsocket/PPPInterface/test_PPPInterface.cpp
Labels: ready for merge, release-type: patch

#13095 STM32: MCU_STM32 supports rtos and bare-metal profiles
  targets/targets.json
Labels: ready for merge, release-type: patch

#13117 Fix compliation warnings
  features/storage/kvstore/conf/kv_config.cpp
Labels: ready for merge, release-type: patch

#13100 Fix BOOT_HEADER_SIZE allocation in ARM scatter files (#13058)
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_ARM/cyb06xxa_cm0plus.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/device/COMPONENT_CM0P/TOOLCHAIN_ARM/cyb06xx7_cm0plus.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_064_SB/device/COMPONENT_CM4/TOOLCHAIN_ARM/cyb06xx7_cm4.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_ARM/cyb06xxa_cm0plus.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_ARM/cyb06xxa_cm4.sct
Labels: ready for merge, release-type: patch

#12898 Add new configuration parameters to Wi-SUN network interface and Border Router class
  features/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackPPPInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  features/nanostack/mbed-mesh-api/source/NanostackPPPInterface.cpp
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/mbed-mesh-api/source/include/wisun_tasklet.h
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-type: feature

#12966 DRAGONFLY_F413RH: Update power on and power off functionality
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_MTS_DRAGONFLY_F413RH/ONBOARD_TELIT_HE910.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_MTS_DRAGONFLY_F413RH/ONBOARD_TELIT_HE910.h
Labels: devices: multitech, ready for merge, release-type: patch

#12900 Added kv store adaptation to nanostack file interface
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/mbed_lib.json
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_file_system_api.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_file_system_api.h
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_hal_init.c
Labels: ready for merge, release-type: feature

#12747 STM32 MBEDTLS support with HW crypto
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F4/aes_alt.h
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F437xG/mbedtls_device.h
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F439xI/mbedtls_device.h
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F756xG/mbedtls_device.h
  features/mbedtls/targets/TARGET_STM/TARGET_STM32L4/aes_alt.c
  features/mbedtls/targets/TARGET_STM/TARGET_STM32L4/aes_alt.h
  features/mbedtls/targets/TARGET_STM/TARGET_STM32L443xC/mbedtls_device.h
  features/mbedtls/targets/TARGET_STM/TARGET_STM32L486xG/mbedtls_device.h
  features/mbedtls/targets/TARGET_STM/TARGET_STM32L562xx/mbedtls_device.h
  features/mbedtls/targets/TARGET_STM/TARGET_STM32WB55xx/mbedtls_device.h
  features/mbedtls/targets/TARGET_STM/aes_alt.cpp
  features/mbedtls/targets/TARGET_STM/aes_alt.h
  features/mbedtls/targets/TARGET_STM/aes_alt_stm32l4.c
  features/mbedtls/targets/TARGET_STM/aes_alt_stm32l4.h
  features/mbedtls/targets/TARGET_STM/ccm_alt.cpp
  features/mbedtls/targets/TARGET_STM/ccm_alt.h
  features/mbedtls/targets/TARGET_STM/cryp_stm32.c
  features/mbedtls/targets/TARGET_STM/cryp_stm32.h
  features/mbedtls/targets/TARGET_STM/gcm_alt.cpp
  features/mbedtls/targets/TARGET_STM/gcm_alt.h
  features/mbedtls/targets/TARGET_STM/hash_stm32.c
  features/mbedtls/targets/TARGET_STM/hash_stm32.h
  features/mbedtls/targets/TARGET_STM/md5_alt.c
  features/mbedtls/targets/TARGET_STM/md5_alt.cpp
  features/mbedtls/targets/TARGET_STM/md5_alt.h
  features/mbedtls/targets/TARGET_STM/sha1_alt.c
  features/mbedtls/targets/TARGET_STM/sha1_alt.cpp
  features/mbedtls/targets/TARGET_STM/sha1_alt.h
  features/mbedtls/targets/TARGET_STM/sha256_alt.c
  features/mbedtls/targets/TARGET_STM/sha256_alt.cpp
  features/mbedtls/targets/TARGET_STM/sha256_alt.h
  targets/targets.json
Labels: ready for merge, release-type: patch

#13040 BLE: Add tx power control to cordio HCI driver
  features/FEATURE_BLE/targets/TARGET_CORDIO/doc/HCIAbstraction.md
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/CordioHCIDriver.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/CordioHCIDriver.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/mbed_lib.json
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/HCIDriver.cpp
Labels: ready for merge, release-type: feature

#13120 CMake: Add support for WIO_3G target
  cmake/target.cmake
  features/cellular/framework/CMakeLists.txt
  features/cellular/framework/targets/CMakeLists.txt
  features/cellular/framework/targets/QUECTEL/CMakeLists.txt
  features/cellular/framework/targets/QUECTEL/UG96/CMakeLists.txt
  features/mbedtls/CMakeLists.txt
  features/mbedtls/targets/CMakeLists.txt
  features/mbedtls/targets/TARGET_STM/CMakeLists.txt
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F439xI/CMakeLists.txt
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/CMSIS/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/Legacy/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/CMakeLists.txt
Labels: needs: work, release-version: feature branch

#13125 Update mbed version to 5.15.4
  platform/mbed_version.h
Labels: ready for merge, release-version: 5.15.4

#12899 Added Wi-SUN statistics interface
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/mbed-mesh-api/source/include/wisun_tasklet.h
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-type: feature

#13130 Cypress: us_ticker fixes
  targets/TARGET_Cypress/TARGET_PSOC6/cy_mbed_post_init.h
  targets/TARGET_Cypress/TARGET_PSOC6/cy_sleep_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/cy_us_ticker.h
  targets/TARGET_Cypress/TARGET_PSOC6/cy_us_ticker_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/mbed_overrides.c
Labels: ready for merge, release-type: patch

#13009 Add support for the Telit ME310 module
  features/cellular/framework/targets/TELIT/ME310/TELIT_ME310.cpp
  features/cellular/framework/targets/TELIT/ME310/TELIT_ME310.h
  features/cellular/framework/targets/TELIT/ME310/TELIT_ME310_CellularContext.cpp
  features/cellular/framework/targets/TELIT/ME310/TELIT_ME310_CellularContext.h
  features/cellular/framework/targets/TELIT/ME310/TELIT_ME310_CellularNetwork.cpp
  features/cellular/framework/targets/TELIT/ME310/TELIT_ME310_CellularNetwork.h
  features/cellular/framework/targets/TELIT/ME310/TELIT_ME310_CellularStack.cpp
  features/cellular/framework/targets/TELIT/ME310/TELIT_ME310_CellularStack.h
  features/cellular/framework/targets/TELIT/ME310/mbed_lib.json
Labels: ready for merge, release-type: patch

#13036 STM32_gen_PeripheralPins.py script v1.12
  tools/targets/STM32_gen_PeripheralPins.py
Labels: ready for merge, release-type: patch

#13098 Cellular: Fix CellularContext destructor memory leak
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  features/cellular/framework/API/CellularContext.h
Labels: ready for merge, release-type: patch

#12471 Extend AnalogIn API: read_voltage
  drivers/AnalogIn.h
  drivers/source/AnalogIn.cpp
  targets/targets.json
  tools/test/travis-ci/doxy-spellchecker/ignore.en.pws
Labels: ready for merge, release-type: feature

#13119 Move target implementations of NanostackRfPhy into nanostack-interface
  features/nanostack/nanostack-interface/targets/TARGET_NXP/TARGET_KW41Z/NanostackRfPhyKw41z.cpp
  features/nanostack/nanostack-interface/targets/TARGET_NXP/TARGET_KW41Z/NanostackRfPhyKw41z.h
  features/nanostack/nanostack-interface/targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/NanostackRfPhyEfr32.cpp
  features/nanostack/nanostack-interface/targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/NanostackRfPhyEfr32.h
Labels: ready for merge, release-type: patch

#12751 STM32WB: enable USB Device
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xx/TARGET_NUCLEO_WB55RG/system_clock.c
  targets/TARGET_STM/USBPhyHw.h
  targets/TARGET_STM/USBPhy_STM32.cpp
  targets/targets.json
Labels: ready for merge, release-type: patch

#12824 Optimise fault handler assembly
  TESTS/mbed_platform/crash_reporting/main.cpp
  platform/internal/mbed_fault_handler.h
  platform/source/TARGET_CORTEX_M/TOOLCHAIN_ARM/except.S
  platform/source/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.S
  platform/source/TARGET_CORTEX_M/TOOLCHAIN_IAR/except.S
  platform/source/TARGET_CORTEX_M/mbed_fault_handler.c
  platform/source/mbed_crash_data_offsets.h
  platform/source/mbed_error.c
Labels: ready for merge, release-type: patch

#12937 Modify the operation of setting qspi frequency when calling Octo controller
  targets/TARGET_STM/qspi_api.c
Labels: ready for merge, release-type: patch

#12998 Fix Mbed TLS `adjust-config.sh` script
  features/mbedtls/importer/adjust-config.sh
Labels: ready for merge, release-type: patch

#13115 MIMXRT1050_EVK: Add USB support
  features/nanostack/targets/TARGET_Freescale/TARGET_KW41Z/NanostackRfPhyKw41z.cpp
  features/nanostack/targets/TARGET_Freescale/TARGET_KW41Z/NanostackRfPhyKw41z.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/mbed_overrides.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_ARM_STD/MIMXRT1052xxxxx.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/usb_device_ch9.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/usb_device_ch9.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/usb_device_class.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/usb_device_class.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/usb_device_config.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/USBEndpoints_MCUXpresso.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/USBPhyHw_MCUXpresso.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/USBPhy_MCUXpresso.cpp
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/device/usb_device.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/device/usb_device_dci.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/device/usb_device_dci.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/device/usb_device_ehci.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/device/usb_device_ehci.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/device/usb_device_khci.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/device/usb_device_khci.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/device/usb_device_lpcip3511.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/device/usb_device_lpcip3511.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/include/usb.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/include/usb_misc.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/include/usb_spec.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/phy/usb_phy.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/phy/usb_phy.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/osa/fsl_os_abstraction.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/osa/fsl_os_abstraction_mbed.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/osa/fsl_os_abstraction_mbed.h
  targets/targets.json
Labels: needs: CI

#13148 M2351: Remove from master
  targets/targets.json
Labels: ready for merge, release-type: patch

#13143 STM32H7: correct Ethernet issue in baremetal
  targets/TARGET_STM/TARGET_STM32H7/STM32Cube_FW/stm32h7xx_hal_conf.h
Labels: ready for merge, release-type: patch

#13135 Restore MTS_MDOT_F411RE bootloader binary
  tools/bootloaders/MTS_MDOT_F411RE/LICENSE.txt
  tools/bootloaders/MTS_MDOT_F411RE/bootloader.bin
Labels: ready for merge, release-type: patch

#13144 Fix esp8266 driver compilation warning
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
Labels: ready for merge, release-type: patch

#13046 Use std::chrono based functions
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udp_tests.h
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.cpp
  components/802.15.4_RF/stm-s2lp-rf-driver/source/NanostackRfPhys2lp.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
  features/FEATURE_BLE/ble/common/Duration.h
  features/FEATURE_BLE/source/generic/GenericGap.tpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioBLE.cpp
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularStack.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularStack.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularNetwork.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.h
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularStack.h
  features/frameworks/utest/source/utest_shim.cpp
  features/lorawan/system/LoRaWANTimer.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  features/nanostack/mbed-mesh-api/source/NanostackPPPInterface.cpp
  features/netsocket/NetworkStack.cpp
  features/nfc/source/nfc/NFCController.cpp
  platform/source/mbed_rtc_time.cpp
Labels: ready for merge, release-type: patch

#13118 Replaced rtos profile with full profile
  targets/targets.json
Labels: ready for merge, release-type: patch

#12905 Timer: minor revisions
  TESTS/mbed_drivers/timer/main.cpp
  drivers/Timer.h
  drivers/source/Timer.cpp
Labels: ready for merge, release-type: feature

#13149 Cellular: ALT1250: Store RAT to permament memory
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP_CellularNetwork.cpp
Labels: ready for merge, release-type: patch

#13128 Add support for Embedded Planet target Atlas
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_ATLAS/ONBOARD_TELIT_ME310.cpp
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_ATLAS/ONBOARD_TELIT_ME310.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_ATLAS/PinNames.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_ATLAS/device.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_ATLAS/mbed_lib.json
  targets/targets.json
Labels: ready for merge, release-type: patch, scope: new-target

#13142 EMAC: Fix Chrono compliation warnings
  features/netsocket/emac-drivers/TARGET_ARM_FM/COMPONENT_LAN91C111/fvp_emac.cpp
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/kinetis_emac.cpp
  features/netsocket/emac-drivers/TARGET_GD_EMAC/gd32xx_emac.cpp
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/numaker_emac.cpp
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_IMX/imx_emac.cpp
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_MCU_LPC546XX/lpc546xx_emac.cpp
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
Labels: needs: CI, release-type: patch

#13158 [WIFI] Add NSAPI_PRESENT macro in the WicedInterface
  targets/TARGET_WICED/wiced_interface/WicedInterface.h
  targets/TARGET_WICED/wiced_interface/default_wifi_interface.cpp
Labels: ready for merge, release-type: patch

#13159 CMake: Restore TOOLCHAIN_ARM directory names
  rtos/source/TARGET_CORTEX/CMakeLists.txt
  rtos/source/TARGET_CORTEX/TOOLCHAIN_ARM_STD/mbed_boot_arm_std.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_ARM_STD/MK64FN1M0xxx12.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TOOLCHAIN_ARM_STD/startup_stm32f439xx.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TOOLCHAIN_ARM_STD/stm32f439xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_ARM_STD/startup_stm32l475xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_ARM_STD/stm32l475xx.sct
Labels: needs: CI, needs: review, release-version: feature branch

#13124 [feature-wisun] 802.15.4 Atmel RF driver update
  components/802.15.4_RF/atmel-rf-driver/atmel-rf-driver/NanostackRfPhyAtmel.h
  components/802.15.4_RF/atmel-rf-driver/mbed_lib.json
Labels: ready for merge, release-version: feature branch

#13132 [feature-wisun] Fix routing_table_get API
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
Labels: ready for merge, release-version: feature branch

#13070 add mbed-os-example-aws to the example list
  tools/test/examples/examples.json
Labels: Priority-High, ready for merge, release-type: patch

#13165 Remove Musca A1 target
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/LICENSE
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/LICENSE-BSD-3-Clause
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/LICENSE-permissive-binary-license-1.0.txt
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/PeripheralNames.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/PinNames.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/README.md
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/TOOLCHAIN_ARMC6/musca_ns.sct
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/TOOLCHAIN_ARMC6/startup_cmsdk_musca_ns.S
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/TOOLCHAIN_GCC_ARM/musca_ns.ld
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/TOOLCHAIN_GCC_ARM/startup_cmsdk_musca_ns.S
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/TOOLCHAIN_IAR/musca_ns.icf
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/TOOLCHAIN_IAR/startup_cmsdk_musca_ns.S
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/cmsis.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/cmsis_cpu.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/cmsis_nvic.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/device_cfg.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/drivers/musca_a1_scc_drv.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/drivers/musca_a1_scc_drv.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/drivers/timer_cmsdk_drv.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/drivers/timer_cmsdk_drv.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/drivers/timer_gp_drv.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/drivers/timer_gp_drv.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/drivers/uart_pl011_drv.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/drivers/uart_pl011_drv.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/platform_regs.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/platform_retarget.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/platform_retarget_dev.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/platform_retarget_dev.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/platform_retarget_pins.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/system_cmsdk_musca.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/system_cmsdk_musca.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/system_core_musca.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/device/system_musca.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/gpio_api.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/gpio_irq_api.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/gpio_object.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/lp_ticker.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/mcuboot.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/objects.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/partition/flash_layout.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/partition/image_macros_preprocessed.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/partition/region_defs.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/pinmap.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/s_veneers.o
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/serial_api.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/sleep_api.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/tfm_s.axf
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/tfm_s.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/us_ticker.c
  targets/targets.json
Labels: Priority-High, ready for merge, release-type: patch

#13177 CMake: Add support NFC
  cmake/target.cmake
  features/CMakeLists.txt
  features/nfc/CMakeLists.txt
  features/nfc/acore/CMakeLists.txt
  features/nfc/stack/CMakeLists.txt
  features/nfc/stack/tech/CMakeLists.txt
  features/nfc/stack/transceiver/CMakeLists.txt
Labels: needs: CI, release-version: feature branch

#13175 psa: Remove not needed TF-M ITS KVStore adapter
  TESTS/configs/experimental.json
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/services/storage/its/its_tfm_impl.cpp
Labels: ready for merge, release-type: patch

#13192 CMake: Add support for LoRaWAN
  cmake/target.cmake
  components/CMakeLists.txt
  components/lora/CMakeLists.txt
  components/lora/COMPONENT_SX126X/CMakeLists.txt
  components/lora/COMPONENT_SX1272/CMakeLists.txt
  components/lora/COMPONENT_SX1276/CMakeLists.txt
  features/CMakeLists.txt
  features/lorawan/CMakeLists.txt
  features/lorawan/lorastack/CMakeLists.txt
  features/lorawan/system/CMakeLists.txt
Labels: ready for merge, release-version: feature branch

#13202 Tools release 6.1.0
  .travis.yml
  tools/build_api.py
  tools/build_profiles.py
  tools/config/__init__.py
  tools/latest_targets.json
  tools/legacy_targets.json
  tools/project.py
  tools/targets/__init__.py
  tools/toolchains/mbed_toolchain.py
Labels: needs: work

#13204 CMake: Add PSA support
  cmake/target.cmake
  features/FEATURE_EXPERIMENTAL_API/CMakeLists.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/CMakeLists.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/CMakeLists.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/services/CMakeLists.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/services/attestation/CMakeLists.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/services/attestation/qcbor/CMakeLists.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/services/attestation/tfm_impl/t_cose/CMakeLists.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/services/storage/CMakeLists.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/CMakeLists.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_DUALCPU/CMakeLists.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V8M/CMakeLists.txt
Labels: ready for merge, release-version: feature branch
