Repository ARMmbed/mbed-os, pull requests merged in 2020-08, with the labels that each got.

#13387 CMake: Fix various issues that prevented usage of the ARM Toolchain
  CMakeLists.txt
  cmake/toolchain.cmake
  cmake/toolchains/ARM.cmake
  rtos/source/TARGET_CORTEX/CMakeLists.txt
  rtos/source/TARGET_CORTEX/rtx5/CMakeLists.txt
  rtos/source/TARGET_CORTEX/rtx5/RTX/CMakeLists.txt
Labels: needs: review, release-version: feature branch

#13306 Include mbed_assert.h in Queue
  rtos/include/rtos/Queue.h
Labels: ready for merge, release-type: patch

#13294 Update MTS_DRAGONFLY_F411RE bootloader to work with mbed 5 & 6
  tools/bootloaders/MTS_DRAGONFLY_F411RE/bootloader.bin
Labels: ready for merge, release-type: patch

#13374 Fixed ThisThread flag_wait_any functions (fix #13360)
  rtos/source/ThisThread.cpp
Labels: ready for merge, release-type: patch

#13405 CMake: Remove default build type selection from top level source file
  CMakeLists.txt
Labels: ready for merge, release-version: feature branch

#13403 CMake: Remove hardcoded targets in modules
  CMakeLists.txt
  cmake/cores/Cortex-A9.cmake
  cmake/cores/Cortex-M0+.cmake
  cmake/cores/Cortex-M0.cmake
  cmake/cores/Cortex-M1.cmake
  cmake/cores/Cortex-M23-NS.cmake
  cmake/cores/Cortex-M23.cmake
  cmake/cores/Cortex-M3.cmake
  cmake/cores/Cortex-M33-NS.cmake
  cmake/cores/Cortex-M33.cmake
  cmake/cores/Cortex-M33F-NS.cmake
  cmake/cores/Cortex-M33F.cmake
  cmake/cores/Cortex-M33FE-NS.cmake
  cmake/cores/Cortex-M33FE.cmake
  cmake/cores/Cortex-M4.cmake
  cmake/cores/Cortex-M4F.cmake
  cmake/cores/Cortex-M7.cmake
  cmake/cores/Cortex-M7F.cmake
  cmake/cores/Cortex-M7FD.cmake
  cmake/profiles/debug.cmake
  cmake/profiles/develop.cmake
  cmake/profiles/release.cmake
  cmake/toolchain.cmake
  cmake/toolchains/ARM.cmake
  cmake/toolchains/GCC_ARM.cmake
  cmake/util.cmake
Labels: release-version: feature branch

#13401 Added error checking to can_filter() for Classic CAN
  targets/TARGET_STM/can_api.c
Labels: ready for merge, release-type: patch

#13408 Fix memory leak in DNS cache
  connectivity/netsocket/source/nsapi_dns.cpp
Labels: ready for merge, release-type: patch

#13349 travis: Reject changes to tools
  .travis.yml
Labels: ready for merge, release-type: patch

#13409 Move BlueNRG-MS driver into connectivity/drivers/ble/FEATURE_BLE
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_MS/BlueNrgMsHCIDriver.cpp
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_MS/README.md
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_MS/mbed_lib.json
Labels: ready for merge, release-type: patch

#13390 Fix cancel connect
  connectivity/FEATURE_BLE/include/ble/Gap.h
  connectivity/FEATURE_BLE/include/ble/internal/PalGap.h
  connectivity/FEATURE_BLE/libraries/TARGET_CORDIO/include/ble/internal/PalGapImpl.h
  connectivity/FEATURE_BLE/libraries/TARGET_CORDIO/source/PalGapImpl.cpp
  connectivity/FEATURE_BLE/libraries/ble-api-implementation/include/ble/internal/GapImpl.h
  connectivity/FEATURE_BLE/libraries/ble-api-implementation/source/GapImpl.cpp
Labels: ready for merge, release-type: patch

#13373 Adding QSPI support to SDP-K1 board support package.
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_SDP_K1/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_SDP_K1/PinNames.h
  targets/targets.json
Labels: Release review required, release-version: 5.15.5

#13381 Nuvoton: Update M252 target name (5.15)
  targets/targets.json
Labels: ready for merge, release-version: 5.15.5

#13420 Updating with new links and correct branding
  DOXYGEN_FRONTPAGE.md
Labels: ready for merge, release-type: patch

#13421 CMake: Use `mbed_` prefix for CMake functions
  CMakeLists.txt
Labels: ready for merge, release-version: feature branch

#13382 M252: Support custom board
  targets/TARGET_NUVOTON/TARGET_M251/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_M251/PinNamesCommon.h
  targets/TARGET_NUVOTON/TARGET_M251/TARGET_NUMAKER_IOT_M252/PinNames.h
  targets/TARGET_NUVOTON/TARGET_M251/device/M251_mem.h
  targets/TARGET_NUVOTON/TARGET_M251/device/M251_mem.icf.h
  targets/TARGET_NUVOTON/TARGET_M251/device/TOOLCHAIN_ARMC6/M251.sct
  targets/TARGET_NUVOTON/TARGET_M251/device/TOOLCHAIN_GCC_ARM/M251.ld
  targets/TARGET_NUVOTON/TARGET_M251/device/TOOLCHAIN_IAR/M251.icf
  targets/TARGET_NUVOTON/TARGET_M251/flash_api.c
  targets/targets.json
Labels: ready for merge, release-type: patch, scope: new-target

#13418 Update PSoC64 TFM release package.
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_0/TARGET_TFM_DUALCPU/src/platform_ns_mailbox.c
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_0/VERSION.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_0/include/platform_multicore.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/COMPONENT_TFM_S_FW/VERSION.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/COMPONENT_TFM_S_FW/tfm_s.axf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/COMPONENT_TFM_S_FW/tfm_s.hex
Labels: Priority-High, devices: cypress, ready for merge, release-type: patch

#13426 travis: Check CMake builds CMake-capable targets
  .travis.yml
Labels: needs: CI, release-version: feature branch

#13441 CMake cryptocell: fix include path
  connectivity/drivers/mbedtls/FEATURE_CRYPTOCELL310/CMakeLists.txt
Labels: ready for merge, release-version: feature branch

#13447 psoc64: Update TF-M release image
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/COMPONENT_TFM_S_FW/VERSION.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/COMPONENT_TFM_S_FW/tfm_s.axf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/COMPONENT_TFM_S_FW/tfm_s.hex
Labels: ready for merge, release-type: patch

#13453 [feature-wisun] Updating mbed-mesh-api.
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-version: feature branch

#13412 Add support for RADIUS configuration options to Wi-SUN
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-version: feature branch

#13468 Add ccache to travis
  .travis.yml
  tools/test/travis-ci/functions.sh
Labels: ready for merge, release-type: patch

#13433 Refactor device_key
  docs/design-documents/features/storage/SecureStore/SecureStore_design.md
  drivers/device_key/README.md
  drivers/device_key/include/device_key/DeviceKey.h
  drivers/device_key/mbed_lib.json
  drivers/device_key/source/DeviceKey.cpp
  drivers/device_key/tests/TESTS/device_key/functionality/main.cpp
  storage/kvstore/securestore/include/securestore/SecureStore.h
  tools/test/travis-ci/doxy-spellchecker/ignore.en.pws
Labels: ready for merge, release-type: patch

#13472 Fix for targets where DEVICE_SPI or DEVICE_INTERRUPTIN are defined but not both
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/atmel-rf-driver/NanostackRfPhyAtmel.h
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAT86RF215.cpp
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/source/rfbits.h
Labels: ready for merge, release-type: patch

#13481 STM32G0 compilation warning
  targets/TARGET_STM/TARGET_STM32G0/STM32Cube_FW/STM32G0xx_HAL_Driver/stm32g0xx_ll_rtc.h
  targets/TARGET_STM/TARGET_STM32G0/serial_device.c
Labels: ready for merge, release-type: patch

#13470 Update dragonfly linkers
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/TOOLCHAIN_ARM/stm32f411re.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/TOOLCHAIN_GCC_ARM/STM32F411XE.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/TOOLCHAIN_GCC_ARM/startup_STM32F41x.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/TOOLCHAIN_GCC_ARM/startup_stm32f411xe.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/TOOLCHAIN_IAR/stm32f411xe.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/TOOLCHAIN_ARM/stm32f411re.sct
Labels: ready for merge, release-type: patch

#13462 BLE remove address from API to cancel connect
  connectivity/FEATURE_BLE/include/ble/Gap.h
  connectivity/FEATURE_BLE/include/ble/internal/PalGap.h
  connectivity/FEATURE_BLE/libraries/TARGET_CORDIO/include/ble/internal/PalGapImpl.h
  connectivity/FEATURE_BLE/libraries/TARGET_CORDIO/source/PalGapImpl.cpp
  connectivity/FEATURE_BLE/libraries/ble-api-implementation/include/ble/internal/GapImpl.h
  connectivity/FEATURE_BLE/libraries/ble-api-implementation/source/GapImpl.cpp
Labels: ready for merge, release-type: patch

#13467 Cypress: Update psoc6cm0p library to 1.2.1.676
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_BLESS/psoc6_cm0p_bless.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_01_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_02_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_03_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_04_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SECURE/psoc6_02_cm0p_secure.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SECURE/psoc6_02_cm0p_secure.hex
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SECURE/psoc6_03_cm0p_secure.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SECURE/psoc6_03_cm0p_secure.hex
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_01_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_02_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_03_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_04_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/version.xml
Labels: ready for merge, release-type: patch

#13456 USBPhyHw: remove mbed.h inclusion
  targets/TARGET_Freescale/USBPhyHw.h
  targets/TARGET_Freescale/USBPhy_Kinetis.cpp
Labels: needs: review, release-type: patch

#13459 platform: fix internal platform headers
  events/source/equeue_mbed.cpp
  platform/include/platform/internal/SysTimer.h
  platform/include/platform/internal/mbed_error_hist.h
  platform/include/platform/internal/mbed_os_timer.h
  platform/source/SysTimer.cpp
  platform/source/mbed_error.c
  platform/source/mbed_error_hist.c
  platform/source/mbed_os_timer.cpp
  platform/source/mbed_thread.cpp
  rtos/include/rtos/Kernel.h
  rtos/source/EventFlags.cpp
  rtos/source/Kernel.cpp
  rtos/source/Semaphore.cpp
  rtos/source/TARGET_CORTEX/mbed_rtx_idle.cpp
  rtos/source/ThisThread.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/systimer/main.cpp
Labels: needs: review, release-type: patch

#13006 NUCLEO_G031K8: Add new target
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G031xx/TARGET_NUCLEO_G031K8/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G031xx/TARGET_NUCLEO_G031K8/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G031xx/TARGET_NUCLEO_G031K8/PinNames.h
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G031xx/TARGET_NUCLEO_G031K8/system_clock.c
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G031xx/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G071xx/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32G0/serial_device.c
  targets/TARGET_STM/lp_ticker.c
  targets/targets.json
Labels: ready for merge, release-type: patch, scope: new-target

#13391 targets: clock: change default core clock to 528M
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/fsl_clock_config.c
Labels: ready for merge, release-version: feature branch

#13502 Targets: Add default "supported_form_factors" for all targets
  targets/targets.json
Labels: ready for merge, release-type: patch

#13334 CMake Travis: add additional examples
  .travis.yml
Labels: ready for merge, release-version: feature branch

#13493 Fix SSID bug on Cypress Targets
  connectivity/drivers/emac/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.cpp
Labels: devices: cypress, ready for merge, release-type: patch

#13497 Updating mbed-mesh-api
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  connectivity/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  connectivity/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-type: patch

#13494 Add WiSun network size configs in JSON
  connectivity/nanostack/mbed-mesh-api/mbed_lib.json
  connectivity/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-type: patch

#13487 ci: Update `arm-none-eabi-` version
  tools/test/travis-ci/functions.sh
Labels: ready for merge, release-version: 5.15.6

#13514 STM32 USB: use SNG_BUF
  targets/TARGET_STM/USBPhy_STM32.cpp
Labels: ready for merge, release-type: patch
