Repository ARMmbed/mbed-os, pull requests merged in 2020-09, with the labels that each got.

#13513 STM32 readme update
  targets/TARGET_STM/README.md
Labels: ready for merge, release-type: patch

#13509 Adding STM32L071xx target
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/TOOLCHAIN_ARM/startup_stm32l071xx.S
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/TOOLCHAIN_ARM/stm32l071xx.sct
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/TOOLCHAIN_GCC_ARM/STM32L071xx.ld
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/TOOLCHAIN_GCC_ARM/startup_stm32l071xx.S
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/TOOLCHAIN_IAR/startup_stm32l071xx.S
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/TOOLCHAIN_IAR/stm32l071xx_flash.icf
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/TOOLCHAIN_IAR/stm32l071xx_sram.icf
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/stm32l071xx.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/stm32l0xx.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/system_stm32l0xx.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/objects.h
  targets/TARGET_STM/TARGET_STM32L0/device/stm32l0xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32L0/device/stm32l0xx_hal_tsc.h
  targets/targets.json
Labels: ready for merge, release-type: patch, scope: new-target

#13527 [feature-wisun] Nanostack pre-release v12.5.0
  features/nanostack/sal-stack-nanostack/nanostack/dhcp_service_api.h
  features/nanostack/sal-stack-nanostack/nanostack/mlme.h
  features/nanostack/sal-stack-nanostack/nanostack/net_interface.h
  features/nanostack/sal-stack-nanostack/nanostack/ws_bbr_api.h
  features/nanostack/sal-stack-nanostack/nanostack/ws_management_api.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC/mac_helper.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC/mac_helper.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common_defines.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_config.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_empty_functions.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_llc_data_service.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_management_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_neighbor_class.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_neighbor_class.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_lib.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_lib.h
  features/nanostack/sal-stack-nanostack/source/Common_Protocols/icmpv6.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_defines.h
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mcps_sap.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mlme.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_pd_sap.c
  features/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/protocol_core.c
  features/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_api.c
  features/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_api.h
  features/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_eapol_pdu_if.c
  features/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_socket_if.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/eap_tls_sec_prot_lib.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/eap_tls_sec_prot_lib.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/radius_eap_tls_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot/radius_client_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_cfg.h
  features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.c
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/dhcp_service_api.c
  features/nanostack/sal-stack-nanostack/source/libNET/src/net_dns.c
  features/nanostack/sal-stack-nanostack/source/libNET/src/net_dns_internal.h
  features/nanostack/sal-stack-nanostack/source/libNET/src/ns_net.c
  features/nanostack/sal-stack-nanostack/sources.mk
Labels: ready for merge, release-version: feature branch

#13517 [feature-wisun] RADIUS shared secret .json parameter set correction
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
Labels: ready for merge, release-version: feature branch

#13526 [feature-wisun] targets:RT1050: Fix the low speed switch issue
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/specific.c
Labels: ready for merge, release-version: feature branch

#13507 [feature-wisun] Enable Nanostack DNS cache usage
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  features/nanostack/nanostack-interface/Nanostack.cpp
  features/nanostack/nanostack-interface/Nanostack.h
Labels: needs: review, release-version: feature branch

#13533 Update test examples.json AWS config
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#13486 Fix heap stats overhead_size calculation
  platform/source/mbed_alloc_wrappers.cpp
Labels: ready for merge, release-type: patch

#13523 STM32H7 ADC: No MultiMode configuration needed for ADC2
  targets/TARGET_STM/TARGET_STM32H7/analogin_device.c
Labels: ready for merge, release-type: patch

#13524 device_management.py supports application access keys
  tools/device_management.py
Labels: ready for merge, release-type: patch

#13540 CMake: Use cmake toolchain file
  CMakeLists.txt
  cmake/toolchain.cmake
Labels: ready for merge, release-version: feature branch

#13530 [feature-wisun] Added configuration for RADIUS retry timer to WisunBorderRouter
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
Labels: ready for merge, release-version: feature branch

#13521 [feature-wisun] Added APIs for Device min sense and CCA threshold table.
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-version: feature branch

#13427 CMake: Fix cmake response files
  CMakeLists.txt
  cmake/toolchain.cmake
Labels: ready for merge, release-version: feature branch

#13430 Relocated libraries in features/frameworks
  .codecheckignore
  UNITTESTS/CMakeLists.txt
  UNITTESTS/empty_baseline/unittest.cmake
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellulardevice/unittest.cmake
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularinformation/unittest.cmake
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularnetwork/unittest.cmake
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularsms/unittest.cmake
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularstack/unittest.cmake
  connectivity/cellular/tests/UNITTESTS/framework/common/util/unittest.cmake
  connectivity/cellular/tests/UNITTESTS/framework/device/athandler/unittest.cmake
  connectivity/drivers/cellular/COMPONENT_STMOD_CELLULAR/README.md
  drivers/source/SFDP.cpp
  features/frameworks/mbed-client-randlib/.mbedignore
  features/frameworks/mbed-client-randlib/.yotta_ignore
  platform/mbed-trace/.gitignore
  platform/mbed-trace/.mbedignore
  platform/mbed-trace/CMakeLists.txt
  platform/mbed-trace/CONTRIBUTING.md
  platform/mbed-trace/Jenkinsfile
  platform/mbed-trace/LICENSE
  platform/mbed-trace/Makefile.nanomesh
  platform/mbed-trace/README.md
  platform/mbed-trace/include/mbed-trace/mbed_trace.h
  platform/mbed-trace/mbed_lib.json
  platform/mbed-trace/source/CMakeLists.txt
  platform/mbed-trace/source/mbed_trace.c
  platform/randlib/.gitignore
  platform/randlib/.mbedignore
  platform/randlib/.yotta_ignore
  platform/randlib/LICENSE
  platform/randlib/Makefile
  platform/randlib/apache-2.0.txt
  platform/randlib/include/mbed-client-randlib/platform/arm_hal_random.h
  platform/randlib/include/mbed-client-randlib/randLIB.h
  platform/randlib/mbed_lib.json
  platform/randlib/source/randLIB.c
  platform/randlib/tests/unit/Makefile
  platform/randlib/tests/unit/MakefileWorker.mk
  platform/randlib/tests/unit/makefile_defines.txt
  platform/randlib/tests/unit/randlib/Makefile
  platform/randlib/tests/unit/randlib/main.cpp
  platform/randlib/tests/unit/randlib/randlibtest.cpp
  platform/randlib/tests/unit/randlib/test_randlib.c
  platform/randlib/tests/unit/randlib/test_randlib.h
  platform/randlib/tests/unit/run_tests
  platform/randlib/tests/unit/stubs/open_stub.c
  platform/randlib/tests/unit/stubs/random_stub.c
  storage/kvstore/source/FileSystemStore.cpp
  storage/kvstore/tests/UNITTESTS/FileSystemStore/unittest.cmake
  storage/kvstore/tests/UNITTESTS/TDBStore/unittest.cmake
Labels: ready for merge, release-type: patch

#13544 TEST: remove MUSCA_B1 from attestation example test
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#13550 [feature-wisun] Nanostack release v12.5.0
  components/802.15.4_RF/atmel-rf-driver/atmel-rf-driver/NanostackRfPhyAtmel.h
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAT86RF215.cpp
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.cpp
  components/802.15.4_RF/atmel-rf-driver/source/rfbits.h
  components/802.15.4_RF/stm-s2lp-rf-driver/source/NanostackRfPhys2lp.cpp
  features/nanostack/sal-stack-nanostack/nanostack/ws_bbr_api.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_config.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_eapol_relay.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  features/nanostack/sal-stack-nanostack/source/Common_Protocols/icmpv6.c
  features/nanostack/sal-stack-nanostack/source/DHCPv6_Server/DHCPv6_Server_service.c
  features/nanostack/sal-stack-nanostack/source/DHCPv6_Server/DHCPv6_server_service.h
  features/nanostack/sal-stack-nanostack/source/DHCPv6_client/dhcpv6_client_api.h
  features/nanostack/sal-stack-nanostack/source/DHCPv6_client/dhcpv6_client_service.c
  features/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_socket_if.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/eap_tls_sec_prot_lib.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/eap_tls_sec_prot_lib.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/radius_eap_tls_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot/avp_helper.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot/radius_client_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.c
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6.c
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6.h
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6_server.c
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6_server.h
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6_vendordata.c
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6_vendordata.h
  features/nanostack/sal-stack-nanostack/source/libNET/src/net_dns.c
  features/nanostack/sal-stack-nanostack/sources.mk
Labels: release-version: feature branch

#13501 USB-DEVICE tests: move host scripts
  drivers/tests/TESTS/host_tests/pyusb_basic.py
  drivers/tests/TESTS/host_tests/pyusb_msd.py
  drivers/tests/TESTS/host_tests/usb_device_hid.py
  drivers/tests/TESTS/host_tests/usb_device_serial.py
  drivers/tests/TESTS/usb_device/msd/main.cpp
Labels: ready for merge, release-type: patch

#13476 Fix trivial compiler Warnings
  connectivity/cellular/source/framework/device/CellularContext.cpp
  connectivity/cellular/source/framework/device/CellularStateMachine.cpp
  connectivity/drivers/cellular/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
  connectivity/drivers/cellular/TELIT/ME310/TELIT_ME310_CellularStack.cpp
  connectivity/drivers/cellular/TELIT/ME310/TELIT_ME310_CellularStack.h
  connectivity/drivers/cellular/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  connectivity/libraries/ppp/source/ppp_service.cpp
  connectivity/libraries/ppp/source/ppp_service_if.cpp
  connectivity/nanostack/sal-stack-nanostack/source/Common_Protocols/tcp.c
  connectivity/netsocket/source/nsapi_dns.cpp
  drivers/source/SFDP.cpp
Labels: ready for merge, release-type: patch

#13536 Nuvoton: Fix degrading QSPI to SPI
  targets/TARGET_NUVOTON/TARGET_M2351/spi_api.c
  targets/TARGET_NUVOTON/TARGET_M480/spi_api.c
Labels: ready for merge, release-type: patch

#13552 general_block_device test: support non-uniform erase sizes
  storage/blockdevice/tests/TESTS/blockdevice/general_block_device/main.cpp
Labels: ready for merge, release-type: patch

#13561 CMake: mbed_add_cmake_directory_if_labels checks presence of CMakeLists.txt before adding subdirectory
  cmake/util.cmake
Labels: ready for merge, release-version: feature branch

#13562 Nanostack release v12.5.0
  connectivity/nanostack/sal-stack-nanostack/nanostack/dhcp_service_api.h
  connectivity/nanostack/sal-stack-nanostack/nanostack/mlme.h
  connectivity/nanostack/sal-stack-nanostack/nanostack/net_interface.h
  connectivity/nanostack/sal-stack-nanostack/nanostack/ws_bbr_api.h
  connectivity/nanostack/sal-stack-nanostack/nanostack/ws_management_api.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC/mac_helper.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC/mac_helper.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common_defines.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_config.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_eapol_relay.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_empty_functions.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_llc_data_service.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_management_api.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_neighbor_class.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_neighbor_class.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_lib.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_lib.h
  connectivity/nanostack/sal-stack-nanostack/source/Common_Protocols/icmpv6.c
  connectivity/nanostack/sal-stack-nanostack/source/DHCPv6_Server/DHCPv6_Server_service.c
  connectivity/nanostack/sal-stack-nanostack/source/DHCPv6_Server/DHCPv6_server_service.h
  connectivity/nanostack/sal-stack-nanostack/source/DHCPv6_client/dhcpv6_client_api.h
  connectivity/nanostack/sal-stack-nanostack/source/DHCPv6_client/dhcpv6_client_service.c
  connectivity/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_defines.h
  connectivity/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mcps_sap.c
  connectivity/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mlme.c
  connectivity/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_pd_sap.c
  connectivity/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/protocol_core.c
  connectivity/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_api.c
  connectivity/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_api.h
  connectivity/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_eapol_pdu_if.c
  connectivity/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_socket_if.c
  connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/eap_tls_sec_prot_lib.c
  connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/eap_tls_sec_prot_lib.h
  connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/radius_eap_tls_sec_prot.c
  connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot/avp_helper.h
  connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot/radius_client_sec_prot.c
  connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot.h
  connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_cfg.h
  connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.c
  connectivity/nanostack/sal-stack-nanostack/source/libDHCPv6/dhcp_service_api.c
  connectivity/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6.c
  connectivity/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6.h
  connectivity/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6_server.c
  connectivity/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6_server.h
  connectivity/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6_vendordata.c
  connectivity/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6_vendordata.h
  connectivity/nanostack/sal-stack-nanostack/source/libNET/src/net_dns.c
  connectivity/nanostack/sal-stack-nanostack/source/libNET/src/net_dns_internal.h
  connectivity/nanostack/sal-stack-nanostack/source/libNET/src/ns_net.c
  connectivity/nanostack/sal-stack-nanostack/sources.mk
Labels: ready for merge, release-type: patch

#13546 Remove duplicate mbed-os/TESTS/host_tests scripts
  TESTS/host_tests/crash_reporting.py
  TESTS/host_tests/device_echo.py
  TESTS/host_tests/reset_reason.py
  TESTS/host_tests/rtc_calc_auto.py
  TESTS/host_tests/rtc_reset.py
  TESTS/host_tests/serial_comms.py
  TESTS/host_tests/sync_on_reset.py
  TESTS/host_tests/system_reset.py
  TESTS/host_tests/timing_drift_auto.py
  TESTS/host_tests/trng_reset.py
  TESTS/host_tests/watchdog_reset.py
Labels: ready for merge, release-type: patch

#13537 Nuvoton: Fix degrading QSPI to SPI (5.15)
  targets/TARGET_NUVOTON/TARGET_M2354/spi_api.c
Labels: Release review required, ready for merge

#13571 [feature-wisun] Nanostack release v12.5.1
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_structures.h
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_upward.c
Labels: ready for merge, release-version: feature branch

#13575 CMake: Gcc Arm prebuild step fix
  CMakeLists.txt
  cmake/toolchains/GCC_ARM.cmake
Labels: needs: review, release-version: feature branch

#13516 Cypress: Rename CY8CKIT_064B0S2_4343W to CY8CKIT064B0S2_4343W
  hal/tests/TESTS/mbed_hal/qspi/flash_configs/flash_configs.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/nvram/TARGET_CY8CKIT064B0S2_4343W/wifi_nvram_image.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.timestamp
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_notices.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/qspi_config.cfg
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/design.cycapsense
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/design.cyqspi
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/design.modus
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/cybsp.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/cybsp.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/cybsp_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_ARM/cyb06xxa_cm0plus.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_ARM/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/cyb06xxa_cm0plus.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_IAR/cyb06xxa_cm0plus.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_IAR/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM0P/system_psoc6_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_ARM/cyb06xxa_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/cyb06xxa_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_IAR/cyb06xxa_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_IAR/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM4/hex/psoc6_02_cm0p_secure.hex
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/COMPONENT_CM4/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/device/system_psoc6.h
  targets/targets.json
  tools/targets/PSOC6.py
Labels: ready for merge, release-type: patch

#13484 KVSTORE tests: move directories
  storage/kvstore/tests/TESTS/direct_access_devicekey/tdb/main.cpp
  storage/kvstore/tests/TESTS/securestore/whitebox/main.cpp
Labels: ready for merge, release-type: patch

#13547 Nuvoton: Fixed NUC472 SD buffer alignment
  targets/TARGET_NUVOTON/TARGET_NUC472/device/StdDriver/nuc472_sd.c
Labels: ready for merge, release-type: patch

#13572 STM32H7 ADC: clock selection lost after deepsleep
  targets/TARGET_STM/TARGET_STM32H7/analogin_device.c
Labels: ready for merge, release-type: patch

#13574 Fix a typo in PeripheralPins.c for EFM32GG11
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG11/PeripheralPins.c
Labels: ready for merge, release-type: patch

#13518 add option for a custom cert in connectivity-netsocket-netsocket-tls
  connectivity/netsocket/tests/TESTS/netsocket/tls/cert.h
Labels: ready for merge, release-type: patch

#13573 Add RADIUS configuration options to Wi-SUN
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  connectivity/nanostack/mbed-mesh-api/mbed_lib.json
  connectivity/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  connectivity/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-type: feature

#13564 STM32Gx: LSI clock selection when LSE is not available
  targets/TARGET_STM/TARGET_STM32G0/STM32Cube_FW/STM32G0xx_HAL_Driver/Legacy/stm32_hal_legacy.h
  targets/TARGET_STM/TARGET_STM32G4/STM32Cube_FW/STM32G4xx_HAL_Driver/Legacy/stm32_hal_legacy.h
Labels: ready for merge, release-type: patch

#13542 B_L4S5I_IOT01A: new ST target
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_MS/mbed_lib.json
  connectivity/drivers/mbedtls/TARGET_STM/TARGET_STM32L4S5xI/mbedtls_device.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/TARGET_B_L4S5I_IOT01A/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/TARGET_B_L4S5I_IOT01A/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/TARGET_B_L4S5I_IOT01A/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/TARGET_B_L4S5I_IOT01A/system_clock.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/device/TOOLCHAIN_ARM/startup_stm32l4s5xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/device/TOOLCHAIN_ARM/stm32l4s5xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/device/TOOLCHAIN_GCC_ARM/startup_stm32l4s5xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/device/TOOLCHAIN_GCC_ARM/stm32l4s5xx.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/device/TOOLCHAIN_IAR/startup_stm32l4s5xx.S
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/device/TOOLCHAIN_IAR/stm32l4s5xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/device/stm32l4s5xx.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/device/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/objects.h
  targets/targets.json
Labels: ready for merge, release-type: patch

#13560 Host privacy implementation
  connectivity/FEATURE_BLE/include/ble/common/Duration.h
  connectivity/FEATURE_BLE/include/ble/gap/Types.h
  connectivity/FEATURE_BLE/source/cordio/source/BLEInstanceBaseImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/BLEInstanceBaseImpl.h
  connectivity/FEATURE_BLE/source/cordio/source/PalEventQueueImpl.h
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.h
  connectivity/FEATURE_BLE/source/cordio/source/PalPrivateAddressControllerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalPrivateAddressControllerImpl.h
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.h
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.cpp
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.h
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.h
  connectivity/FEATURE_BLE/source/pal/GapTypes.h
  connectivity/FEATURE_BLE/source/pal/PalGap.h
  connectivity/FEATURE_BLE/source/pal/PalPrivateAddressController.h
  connectivity/FEATURE_BLE/source/pal/PalSecurityManager.h
Labels: needs: work, release-version: feature branch

#13400 Call mbed_tfm_init before mbed_toolchain_init
  cmsis/device/rtos/include/mbed_boot.h
  cmsis/device/rtos/source/mbed_boot.c
Labels: ready for merge, release-type: patch

#13584 Revert "Always build both .hex and .bin files"
  connectivity/libraries/nanostack-libservice/test/libService/unittest/Makefile
  connectivity/libraries/nanostack-libservice/test/libService/unittest/MakefileWorker.mk
  tools/toolchains/mbed_toolchain.py
Labels: Priority-High, needs: review

#13583 STM32: correct few Arduino pins value
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/TARGET_NUCLEO_F303ZE/PinNames.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L072xZ/TARGET_DISCO_L072CZ_LRWAN1/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/TARGET_NUCLEO_L433RC_P/PinNames.h
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L552xx/TARGET_NUCLEO_L552ZE_Q/PinNames.h
  targets/targets.json
Labels: ready for merge, release-type: patch

#13492 Fix pwm out resets after suspend
  UNITTESTS/stubs/pwmout_api_stub.c
  drivers/include/drivers/PwmOut.h
  drivers/source/PwmOut.cpp
  hal/include/hal/pwmout_api.h
  targets/TARGET_Cypress/TARGET_PSOC6/cy_pwmout_api.c
  targets/TARGET_Freescale/TARGET_K20XX/pwmout_api.c
  targets/TARGET_Freescale/TARGET_KLXX/pwmout_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/pwmout_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/pwmout_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL27Z/pwmout_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/pwmout_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/pwmout_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/pwmout_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/pwmout_api.c
  targets/TARGET_GigaDevice/TARGET_GD32F30X/pwmout_api.c
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/pwmout_api.c
  targets/TARGET_Maxim/TARGET_MAX32600/pwmout_api.c
  targets/TARGET_Maxim/TARGET_MAX32610/pwmout_api.c
  targets/TARGET_Maxim/TARGET_MAX32620/pwmout_api.c
  targets/TARGET_Maxim/TARGET_MAX32620C/pwmout_api.c
  targets/TARGET_Maxim/TARGET_MAX32625/pwmout_api.c
  targets/TARGET_Maxim/TARGET_MAX32630/pwmout_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_M2351/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_M251/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_M261/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_M451/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_M480/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/pwmout_api.c
  targets/TARGET_NXP/TARGET_LPC11U6X/pwmout_api.c
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/pwmout_api.c
  targets/TARGET_NXP/TARGET_LPC176X/pwmout_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/pwmout_api.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/pwmout_api.c
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/pwmout_api.c
  targets/TARGET_STM/pwmout_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/pwmout_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/pwmout_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/pwmout_api.c
Labels: ready for merge, release-type: feature

#13558 STM32L4+ : SRAM3 is powered off in deepsleep
  targets/TARGET_STM/sleep.c
  targets/targets.json
Labels: ready for merge, release-type: patch

#13579 double negation fixed and ifs normalised
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
Labels: ready for merge, release-type: patch

#13587 MCU_STM32G031xx : decrease boot-stack-size
  targets/targets.json
Labels: ready for merge, release-type: patch

#13580 TEST: Update example scripts for cmake feature
  tools/test/examples/README.md
  tools/test/examples/examples.py
  tools/test/examples/examples_lib.py
Labels: ready for merge, release-type: patch

#13585 [feature-wisun] Nanostack release v12.5.2
  features/nanostack/sal-stack-nanostack/nanostack/net_ws_test.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common_defines.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_empty_functions.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_llc_data_service.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_test_api.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mcps_sap.c
  features/nanostack/sal-stack-nanostack/source/libNET/src/net_dns.c
Labels: ready for merge, release-version: feature branch

#13582 Ble privacy scanning initiating
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.h
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
  connectivity/FEATURE_BLE/source/pal/PalGap.h
Labels: needs: review, release-version: feature branch

#13588 [feature-wisun] Added initialization check to RADIUS ipv6 address
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
Labels: ready for merge, release-version: feature branch

#13592 Add test examples.json config for Azure and Google Cloud
  tools/test/examples/examples.json
Labels: Priority-High, ready for merge, release-type: patch

#13569 targets:RT1050: Fix the flash erase and program issue for qspi nor fl…
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/flash_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/flash_defines.h
Labels: ready for merge, release-version: feature branch

#13594 PSA - Generate root of trust before accessing kvstore
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/TESTS/its_ps/main.cpp
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/services/storage/its/pits_impl.cpp
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/services/storage/ps/protected_storage.cpp
Labels: mergify skip, needs: work

#13608 Add certificate remove before add to Wisun tasklet
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: feature branch

#13605 Update Mbed CoAP to v5.1.7
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/source/sn_coap_parser.c
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: feature branch

#13589 CMake: Add background and future plans to README
  cmake/README.md
Labels: needs: review, release-version: feature branch

#13609 CMake: Move modules under tools subdirectory
  CMakeLists.txt
  tools/cmake/README.md
  tools/cmake/core.cmake
  tools/cmake/cores/Cortex-A9.cmake
  tools/cmake/cores/Cortex-M0+.cmake
  tools/cmake/cores/Cortex-M0.cmake
  tools/cmake/cores/Cortex-M1.cmake
  tools/cmake/cores/Cortex-M23-NS.cmake
  tools/cmake/cores/Cortex-M23.cmake
  tools/cmake/cores/Cortex-M3.cmake
  tools/cmake/cores/Cortex-M33-NS.cmake
  tools/cmake/cores/Cortex-M33.cmake
  tools/cmake/cores/Cortex-M33F-NS.cmake
  tools/cmake/cores/Cortex-M33F.cmake
  tools/cmake/cores/Cortex-M33FE-NS.cmake
  tools/cmake/cores/Cortex-M33FE.cmake
  tools/cmake/cores/Cortex-M4.cmake
  tools/cmake/cores/Cortex-M4F.cmake
  tools/cmake/cores/Cortex-M7.cmake
  tools/cmake/cores/Cortex-M7F.cmake
  tools/cmake/cores/Cortex-M7FD.cmake
  tools/cmake/profile.cmake
  tools/cmake/profiles/debug.cmake
  tools/cmake/profiles/develop.cmake
  tools/cmake/profiles/release.cmake
  tools/cmake/toolchain.cmake
  tools/cmake/toolchains/ARM.cmake
  tools/cmake/toolchains/GCC_ARM.cmake
  tools/cmake/util.cmake
Labels: needs: review, release-version: feature branch

#13612 [feature-wisun] Nanostack release v12.5.3
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot/radius_client_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.c
Labels: ready for merge, release-version: feature branch

#13614 CMake design: update to the latest version of feature-cmake branch
  docs/design-documents/tools/cmake.md
Labels: needs: CI, release-version: feature branch

#13406 STM32F1 USBDevice
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103x8/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103x8/system_clock.c
  targets/TARGET_STM/USBPhyHw.h
Labels: ready for merge, release-type: patch

#13432 Enable PDP type IPV6 and IPV4V6 to support more cellular service prov…
  connectivity/drivers/cellular/TELIT/HE910/TELIT_HE910.cpp
Labels: ready for merge, release-type: patch

#13600 Refactor COMPONENT_FPGA_CI_TEST_SHIELD directory structure
  .travis.yml
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/DynamicPinList.h
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/I2CTester.h
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/MbedTester.h
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/SPIMasterTester.h
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/SPISlaveTester.h
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/SPITester.h
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/UARTTester.h
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/fpga_config.h
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/test_utils.h
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/source/DynamicPinList.cpp
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/source/I2CTester.cpp
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/source/MbedTester.cpp
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/source/SPIMasterTester.cpp
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/source/SPISlaveTester.cpp
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/source/SPITester.cpp
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/source/UARTTester.cpp
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/README.md
Labels: ready for merge, release-type: patch

#13602 WEP Security fix for Cypress Target Kits
  connectivity/drivers/emac/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.cpp
Labels: devices: cypress, ready for merge, release-type: patch

#13621 Refactor remaining TESTS related to hal, rtos, and platform dir
  hal/tests/TESTS/mbed_timing_fpga_ci_test_shield/watchdog/main.cpp
  platform/tests/TESTS/mbed_micro/attributes/attributes.c
  platform/tests/TESTS/mbed_micro/attributes/main.cpp
  platform/tests/TESTS/mbed_micro/attributes/weak.c
  platform/tests/TESTS/mbed_micro/call_before_main/main.cpp
  platform/tests/TESTS/mbed_micro/cpp/main.cpp
  platform/tests/TESTS/mbed_micro/div/main.cpp
  platform/tests/TESTS/mbed_micro/static_assert/main.cpp
  platform/tests/TESTS/mbed_micro/static_assert/test_c.c
  platform/tests/TESTS/mbed_micro/static_assert/test_cpp.cpp
  rtos/tests/TESTS/mbed_rtos/MemoryPool/main.cpp
  rtos/tests/TESTS/mbed_rtos/basic/main.cpp
  rtos/tests/TESTS/mbed_rtos/condition_variable/main.cpp
  rtos/tests/TESTS/mbed_rtos/event_flags/main.cpp
  rtos/tests/TESTS/mbed_rtos/heap_and_stack/main.cpp
  rtos/tests/TESTS/mbed_rtos/kernel_tick_count/main.cpp
  rtos/tests/TESTS/mbed_rtos/mail/main.cpp
  rtos/tests/TESTS/mbed_rtos/malloc/main.cpp
  rtos/tests/TESTS/mbed_rtos/mutex/main.cpp
  rtos/tests/TESTS/mbed_rtos/queue/main.cpp
  rtos/tests/TESTS/mbed_rtos/semaphore/main.cpp
  rtos/tests/TESTS/mbed_rtos/signals/main.cpp
  rtos/tests/TESTS/mbed_rtos/systimer/main.cpp
  rtos/tests/TESTS/mbed_rtos/threads/SynchronizedIntegral.h
  rtos/tests/TESTS/mbed_rtos/threads/main.cpp
Labels: ready for merge, release-type: patch

#13586 travis: license check for new files
  .travis.yml
Labels: needs: review, release-type: patch

#13565 Feature stm32g4 can support
  targets/TARGET_STM/TARGET_STM32G4/TARGET_STM32G474xx/TARGET_NUCLEO_G474RE/system_clock.c
  targets/TARGET_STM/TARGET_STM32G4/objects.h
  targets/TARGET_STM/can_api.c
  targets/targets.json
Labels: ready for merge, release-type: patch

#13593 STM32F: skip LittleFileSystem default instance and TDBStore tests
  storage/kvstore/tests/TESTS/kvstore/general_tests_phase_1/main.cpp
  storage/kvstore/tests/TESTS/kvstore/general_tests_phase_2/main.cpp
  storage/platform/source/PlatformStorage.cpp
  targets/targets.json
Labels: ready for merge, release-type: patch

#13620 CMake: Add support for C lib selection
  CMakeLists.txt
  docs/design-documents/tools/cmake.md
  tools/cmake/README.md
  tools/cmake/toolchains/ARM.cmake
  tools/cmake/toolchains/GCC_ARM.cmake
Labels: ready for merge, release-version: feature branch

#13615 CMake: Add support for printf lib selection
  CMakeLists.txt
  docs/design-documents/tools/cmake.md
  tools/cmake/toolchains/ARM.cmake
  tools/cmake/toolchains/GCC_ARM.cmake
Labels: needs: work, release-version: feature branch

#13631 CMake: Fix TFM targets build
  cmsis/CMSIS_5/CMSIS/RTOS2/RTX/CMakeLists.txt
  tools/cmake/toolchains/ARM.cmake
  tools/cmake/toolchains/GCC_ARM.cmake
Labels: needs: CI, release-version: feature branch

#13622 Cordio configure identity address
  connectivity/FEATURE_BLE/include/ble/Gap.h
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/include/dm_api.h
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/dm/dm_sec.c
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/dm/dm_sec.h
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/smp/smp_act.c
  connectivity/FEATURE_BLE/source/Gap.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.h
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
  connectivity/FEATURE_BLE/source/generic/SecurityDb.h
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/pal/PalSecurityManager.h
Labels: needs: work, release-version: feature branch

#13618 nanostack: fix invalid memory access on memcpy
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_lib.c
Labels: ready for merge, release-version: feature branch

#13545 Fix enabling/disabling BLE-Features
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.cpp
Labels: ready for merge, release-type: patch

#13563 Add mutiple push and pop for circular buffer
  platform/include/platform/CircularBuffer.h
  platform/tests/UNITTESTS/CircularBuffer/test_CircularBuffer.cpp
  platform/tests/UNITTESTS/CircularBuffer/unittest.cmake
Labels: ready for merge, release-type: feature

#13630 Resolve advertising reports and connection complete
  connectivity/FEATURE_BLE/include/ble/gap/Events.h
  connectivity/FEATURE_BLE/mbed_lib.json
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.cpp
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.h
  connectivity/FEATURE_BLE/source/pal/PalGap.h
Labels: needs: review, release-version: feature branch

#13649 Make mbed-trace available to bare metal
  TESTS/configs/baremetal.json
  connectivity/libraries/nanostack-libservice/mbed_lib.json
  drivers/source/SFDP.cpp
  platform/bare_metal/mbed_lib.json
  platform/mbed-trace/include/mbed-trace/mbed_trace.h
  platform/mbed-trace/source/mbed_trace.c
Labels: ready for merge, release-type: patch

#13645 Patch STM32F4 HAL to fix F412CG USART3 issue
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_rcc_ex.h
Labels: ready for merge, release-type: patch

#13496 [mbedos-5.15] Updating mbed-mesh-api
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: Release review required, ready for merge

#13653 Use impl namespace in GattServer att_cb registration, not ble
  connectivity/FEATURE_BLE/source/cordio/source/BLEInstanceBaseImpl.cpp
Labels: ready for merge, release-type: patch

#13640 STM32: Fix system clock setup for XTAL and/or internal source on STM32H743
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI2/system_clock.c
Labels: ready for merge, release-type: patch

#13656 Host privacy fixes
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.cpp
Labels: needs: review, release-version: feature branch

#13658 Host privacy: Set Identity address when retrieved
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.h
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/pal/PalSecurityManager.h
Labels: needs: review, release-version: feature branch

#13634 STM32L4: link issue with IAR
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L452xE/device/TOOLCHAIN_IAR/stm32l452xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/TOOLCHAIN_IAR/stm32l475xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/device/TOOLCHAIN_IAR/stm32l476xx.icf
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/device/TOOLCHAIN_IAR/stm32l486xx.icf
Labels: ready for merge, release-type: patch

#13633 STM32WB: FLASH compilation issue with baremetal
  targets/TARGET_STM/TARGET_STM32WB/flash_api.c
Labels: ready for merge, release-type: patch

#13632 fix DAPLINK error for S1SBP6A Target using GNU Toolchain.
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/device/TOOLCHAIN_GCC_ARM/startup_s1sbp6a.S
Labels: ready for merge, release-type: patch

#13660 BLE: Retrieve correct DB entry when RPA used
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
  connectivity/FEATURE_BLE/source/generic/SecurityDb.h
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.cpp
Labels: needs: review, release-version: feature branch

#13670 Host privacy fixes
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
Labels: needs: review, release-version: feature branch

#13662 Host privacy feature configuration
  connectivity/FEATURE_BLE/include/ble/gap/Types.h
  connectivity/FEATURE_BLE/mbed_lib.json
  connectivity/FEATURE_BLE/source/Gap.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalPrivateAddressControllerImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.cpp
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.h
  connectivity/FEATURE_BLE/source/pal/PalPrivateAddressController.h
Labels: needs: work, release-version: feature branch

#13607 Update Mbed CoAP to v5.1.7
  connectivity/libraries/mbed-coap/CHANGELOG.md
  connectivity/libraries/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-type: patch

#13578 Fix for linker issue in AdBun-M066
  targets/TARGET_TOSHIBA/TARGET_TMPM066/device/TOOLCHAIN_ARM_STD/tmpm066fwug.sct
Labels: ready for merge, release-version: 5.15.6

#13674 Samsung: uart fixes
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/PeripheralNames.h
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/PinNames.h
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/device/TOOLCHAIN_ARM_STD/s1sbp6a.sct
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/device/memory_zones.h
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/device/system_s1sbp6a.c
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/serial_api.c
Labels: ready for merge, release-type: patch

#13680 BLE: Add function to signal privacy initialization.
  connectivity/FEATURE_BLE/include/ble/Gap.h
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
Labels: needs: review, release-version: feature branch

#13495 [mbed-os-5.15] Add WiSun network size configs in JSON
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-version: 5.15.6

#13666 [feature-wisun] Mesh interface global up is indicated always on bootstrap ready
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: feature branch

#13686 Copied TDBStore RAM init fix from mbed OS master
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: ready for merge, release-version: feature branch

#13689 Set privacy mode to device mode in LL.
  connectivity/FEATURE_BLE/source/cordio/source/PalPrivateAddressControllerImpl.cpp
Labels: needs: review, release-version: feature branch

#13684 nanostack: fix inclusion of kvstore
  connectivity/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_file_system_api.cpp
Labels: ready for merge, release-type: patch

#13681 Nrf52840 spim3 updates
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/object_owners.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/spi_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/modules/nrfx/drivers/include/nrfx_spim.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/modules/nrfx/drivers/src/nrfx_spim.c
Labels: ready for merge, release-type: feature

#13679 Nuvoton: Fix NuMaker I2C timeout
  targets/TARGET_NUVOTON/TARGET_M2351/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M251/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M261/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M451/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M480/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/i2c_api.c
Labels: ready for merge, release-type: patch

#13611 Edit on Toolchain linker files for stm32L071xx target
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/TOOLCHAIN_GCC_ARM/STM32L071xx.ld
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/TOOLCHAIN_GCC_ARM/startup_stm32l071xx.S
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/stm32l071xx.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_MCU_STM32L071xx/device/stm32l0xx.h
Labels: ready for merge, release-type: patch

#13646 Make STM32F412xG system_clock.c functions weak
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/system_clock.c
Labels: ready for merge, release-type: patch

#13637 CMake: Add support for NUCLEO_F401RE
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TARGET_NUCLEO_F401RE/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TOOLCHAIN_ARM/stm32f401xe.sct
  tools/cmake/README.md
Labels: needs: CI, release-version: feature branch

#13661 K82F, KL82Z: Fix the I2C SDK driver slave transfer
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/drivers/fsl_i2c.c
Labels: ready for merge, release-version: 5.15.6

#12644 Add OSPI driver to support the Octa mode of Macronix octaflash MX25LM51245G
  drivers/include/drivers/OSPI.h
  drivers/include/drivers/internal/SFDP.h
  drivers/mbed_lib.json
  drivers/source/OSPI.cpp
  drivers/source/SFDP.cpp
  hal/include/hal/ospi_api.h
  hal/include/hal/static_pinmap.h
  hal/source/static_pinmap.cpp
  hal/tests/TESTS/mbed_hal/ospi/flash_configs/MX25LM51245G_config.h
  hal/tests/TESTS/mbed_hal/ospi/flash_configs/flash_configs.h
  hal/tests/TESTS/mbed_hal/ospi/main.cpp
  hal/tests/TESTS/mbed_hal/ospi/ospi_test.h
  hal/tests/TESTS/mbed_hal/ospi/ospi_test_utils.cpp
  hal/tests/TESTS/mbed_hal/ospi/ospi_test_utils.h
  storage/blockdevice/COMPONENT_OSPIF/include/QSPIF/MX25LM51245G_config.h
  storage/blockdevice/COMPONENT_OSPIF/include/QSPIF/OSPIFBlockDevice.h
  storage/blockdevice/COMPONENT_OSPIF/mbed_lib.json
  storage/blockdevice/COMPONENT_OSPIF/source/OSPIFBlockDevice.cpp
  storage/blockdevice/tests/TESTS/blockdevice/general_block_device/main.cpp
  storage/kvstore/kv_config/source/kv_config.cpp
  storage/platform/source/PlatformStorage.cpp
  targets/TARGET_STM/PeripheralPins.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/common_objects.h
  targets/TARGET_STM/ospi_api.c
  targets/targets.json
Labels: ready for merge, release-type: feature

#13601 Fix AnalogIn implementation on STM32G4 series
  targets/TARGET_STM/TARGET_STM32G4/TARGET_STM32G474xx/TARGET_NUCLEO_G474RE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32G4/analogin_device.c
  targets/targets.json
Labels: ready for merge, release-type: patch
