Repository ARMmbed/mbed-os, pull requests merged in 2020-01, with the labels that each got.

#12020 Fix issues in setting radio access technology
  features/cellular/framework/API/CellularNetwork.h
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/targets/GENERIC/GENERIC_AT3GPP/GENERIC_AT3GPP.cpp
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/EC2X/QUECTEL_EC2X.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26.cpp
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.cpp
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910.cpp
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910.h
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910_CellularNetwork.cpp
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910_CellularNetwork.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.cpp
  features/cellular/framework/targets/UBLOX/PPP/UBLOX_PPP.cpp
  features/cellular/mbed_lib.json
Labels: release-version: 6.0.0-alpha-1

#12144 NRF52840: Use 2 region memory model for the ARM toolchain
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_ARM_STD/nRF52840.sct
Labels: release-version: 6.0.0-alpha-1

#12169 syntax error corrections - rm unnecessary semicolons
  hal/can_api.h
  hal/can_helper.h
  hal/crc_api.h
  platform/CircularBuffer.h
  platform/mbed_retarget.h
Labels: release-version: 6.0.0-alpha-1

#12173 Change size embedded in the temp_ram_page_data
  components/TARGET_PSA/services/attestation/COMPONENT_PSA_SRV_IMPL/attestation_bootloader_data.c
Labels: release-version: 6.0.0-alpha-1

#12175 Minimal-printf: Fix documentation as floating point is disabled by default
  platform/source/minimal-printf/README.md
Labels: release-version: 6.0.0-alpha-1

#12170 Nuvoton: Support dynamic heap configuration on IAR
  targets/TARGET_NUVOTON/TARGET_M251/device/TOOLCHAIN_IAR/M251.icf
  targets/TARGET_NUVOTON/TARGET_M261/device/TOOLCHAIN_IAR/M261.icf
  targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_IAR/M453.icf
  targets/TARGET_NUVOTON/TARGET_M480/device/TOOLCHAIN_IAR/M487.icf
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_IAR/TARGET_NU_XRAM_SUPPORTED/NUC472_442.icf
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_IAR/TARGET_NU_XRAM_UNSUPPORTED/NUC472_442.icf
Labels: release-version: 6.0.0-alpha-1

#12164 Pr dev/remove hardcoded timeout in cypress bt code
  features/FEATURE_BLE/targets/TARGET_Cypress/COMPONENT_CYW43XXX/CyH4TransportDriver.cpp
  features/FEATURE_BLE/targets/TARGET_Cypress/COMPONENT_CYW43XXX/CyH4TransportDriver.h
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/hal/src/cyhal_uart.c
Labels: devices: cypress, release-version: 6.0.0-alpha-1

#12146 mbed-coap buffer overflow fix
  features/frameworks/mbed-coap/source/sn_coap_parser.c
Labels: Release review required

#12147 mbed-coap uint16 overflow fix
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/source/sn_coap_builder.c
Labels: Release review required, needs: CI

#12178 Fixes for LPC55S69_NS TLS tests
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/device/TOOLCHAIN_IAR/LPC55S69_cm33_core0_flash.icf
Labels: release-version: 6.0.0-alpha-1

#12068 Enabling small C library option and deprecating uARM toolchain
  TESTS/configs/baremetal.json
  TESTS/mbed_drivers/c_strings/main.cpp
  TESTS/mbed_platform/minimal-printf/compliance/main.cpp
  platform/source/mbed_retarget.cpp
  rtos/source/TARGET_CORTEX/TOOLCHAIN_ARM_MICRO/mbed_boot_arm_micro.c
  rtos/source/TARGET_CORTEX/TOOLCHAIN_ARM_STD/mbed_boot_arm_std.c
  targets/TARGET_STM/TARGET_STM32F2/TARGET_NUCLEO_F207ZG/device/TOOLCHAIN_ARM_STD/stm32f207xx.sct
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/device/TOOLCHAIN_ARM_STD/stm32f303xe.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/device/TOOLCHAIN_ARM_STD/stm32f411re.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_ARM_STD/stm32f429xx.sct
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/device/TOOLCHAIN_ARM_STD/stm32l073xz.sct
  targets/targets.json
  tools/build_api.py
  tools/test/config/app_override_libs/targets.json
  tools/test/config/compound_inheritance/targets.json
  tools/test/config/double_define/targets.json
  tools/test/config/feature_compesition/targets.json
  tools/test/config/feature_recursive_add/targets.json
  tools/test/config/feature_recursive_complex/targets.json
  tools/test/config/feature_remove/targets.json
  tools/test/config/lib_requires_missing_lib/targets.json
  tools/test/config/macro_inheritance/targets.json
  tools/test/config/override_labels_libs/targets.json
  tools/test/config/override_labels_libs_more/targets.json
  tools/test/config/override_labels_targets/targets.json
  tools/test/config/override_precidence/targets.json
  tools/test/config/override_undefined/targets.json
  tools/test/config/override_undefined_libs/targets.json
  tools/test/config/override_with_labels/targets.json
  tools/test/config/range_limits/targets.json
  tools/test/config/range_limits_invalid/targets.json
  tools/test/config/range_limits_override_invalid/targets.json
  tools/test/config/requires_exclude_in_include/targets.json
  tools/test/config/requires_from_lib/targets.json
  tools/test/config/requires_include_in_exclude/targets.json
  tools/test/config/requires_omit_lib/targets.json
  tools/test/config/simple_features/targets.json
  tools/test/config/simple_iheritance/targets.json
  tools/test/targets/target_test.py
  tools/test/toolchains/test_toolchains.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
  tools/toolchains/mbed_toolchain.py
Labels: release-version: 6.0.0-alpha-1

#12182 Update watchdog tests to run with bare metal profile
  TESTS/mbed_drivers/watchdog/main.cpp
  TESTS/mbed_drivers/watchdog_reset/main.cpp
  TESTS/mbed_hal/watchdog/main.cpp
  TESTS/mbed_hal/watchdog_reset/main.cpp
Labels: release-version: 6.0.0-alpha-1

#12123 Cellular: Refactor cellular variable visibilities
  UNITTESTS/stubs/CellularDevice_stub.cpp
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/API/CellularSMS.h
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/AT/AT_CellularInformation.h
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/AT/AT_CellularSMS.h
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/AT/AT_ControlPlane_netif.h
  features/cellular/framework/device/CellularDevice.cpp
Labels: release-version: 6.0.0-alpha-1

#12156 Modify PSA target definition strategy
  features/FEATURE_PSA/supporting_psa_in_mbed-os.md
Labels: release-version: feature branch

#12188 Greentea test :Added the print in the exception handler
  tools/test.py
  tools/test/toolchains/test_toolchains.py
Labels: release-version: 6.0.0-alpha-1

#12194 Nanostack Socket event handler fix
  features/nanostack/nanostack-interface/Nanostack.cpp
Labels: release-version: 6.0.0-alpha-1

#12189 Removed hardcoded CY8CPROTO_062_4343W bt baudrate limit.
  features/FEATURE_BLE/targets/TARGET_Cypress/COMPONENT_CYW43XXX/CyH4TransportDriver.h
Labels: devices: cypress, release-version: 6.0.0-alpha-1

#12179 TESTS: Update testing of examples in mbed-os
  tools/test/examples/examples.json
Labels: release-version: 6.0.0-alpha-1

#12155 LPC11U24: Fix baremetal build and runtime error
  targets/targets.json
Labels: release-version: 6.0.0-alpha-1

#12186 STM serial init: Set pin function only if pin is defined (not NC)
  targets/TARGET_STM/serial_api.c
Labels: release-version: 6.0.0-alpha-1

#12109 Replace RawSerial as it has been deprecated
  TESTS/mbed_drivers/flashiap/main.cpp
  TESTS/mbed_hal/trng/main.cpp
  TESTS/psa/entropy_inject/main.cpp
  TESTS/psa/spm_smoke/COMPONENT_NSPE/main.cpp
  TEST_APPS/device/nanostack_mac_tester/main.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/test_utils.h
  drivers/RawSerial.h
  drivers/UnbufferedSerial.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/H4TransportDriver.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/H4TransportDriver.h
  features/frameworks/greentea-client/greentea-client/greentea_serial.h
  features/frameworks/greentea-client/greentea-client/test_env.h
  features/frameworks/greentea-client/source/greentea_serial.cpp
  features/frameworks/greentea-client/source/greentea_test_env.cpp
  features/frameworks/utest/source/unity_handler.cpp
  features/frameworks/utest/source/utest_case.cpp
  features/frameworks/utest/source/utest_default_handlers.cpp
  features/frameworks/utest/source/utest_greentea_handlers.cpp
  features/frameworks/utest/source/utest_harness.cpp
  features/frameworks/utest/source/utest_print.cpp
  features/frameworks/utest/source/utest_stack_trace.cpp
  features/frameworks/utest/utest/utest.h
  features/frameworks/utest/utest/utest_print.h
Labels: release-version: 6.0.0-alpha-1

#12193 Cellular: Move cellular event queue thread ownership to CellularDevice
  UNITTESTS/features/cellular/framework/device/cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellularstatemachine/cellularstatemachinetest.cpp
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/device/CellularStateMachine.h
Labels: release-version: 6.0.0-alpha-1

#11653 Add Getaddrinfo interface for multiple DNS adresses
  TESTS/netsocket/dns/asynchronous_dns_cache.cpp
  TESTS/netsocket/dns/asynchronous_dns_cancel.cpp
  TESTS/netsocket/dns/asynchronous_dns_multi_ip.cpp
  TESTS/netsocket/dns/asynchronous_dns_non_async_and_async.cpp
  TESTS/netsocket/dns/dns_tests.h
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/dns/synchronous_dns_multi_ip.cpp
  UNITTESTS/MODULETESTS/features/netsocket/IfaceDnsSocket/test_IfaceDnsSocket.cpp
  UNITTESTS/features/netsocket/InternetSocket/unittest.cmake
  UNITTESTS/features/netsocket/NetworkStack/test_NetworkStack.cpp
  UNITTESTS/stubs/NetworkInterface_stub.cpp
  UNITTESTS/stubs/NetworkStack_stub.cpp
  UNITTESTS/stubs/NetworkStack_stub.h
  UNITTESTS/stubs/nsapi_dns_stub.cpp
  features/netsocket/DNS.h
  features/netsocket/NetworkInterface.cpp
  features/netsocket/NetworkInterface.h
  features/netsocket/NetworkStack.cpp
  features/netsocket/NetworkStack.h
  features/netsocket/mbed_lib.json
  features/netsocket/nsapi_dns.cpp
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
Labels: BREAKING-CHANGE, release-version: 6.0.0-alpha-1

#12185 BLE: fix pointer not set to null on delete
  features/FEATURE_BLE/source/generic/GenericSecurityManager.tpp
Labels: release-version: 6.0.0-alpha-1

#12196 LWIP: don't pbuf_free(NULL) on socket close
  features/lwipstack/LWIPStack.cpp
Labels: release-version: 6.0.0-alpha-1

#12176 Nuvoton: Support usbd
  TESTS/usb_device/msd/main.cpp
  drivers/source/usb/USBCDC.cpp
  targets/TARGET_NUVOTON/TARGET_M2351/device/StdDriver/m2351_clk.h
  targets/TARGET_NUVOTON/TARGET_NANO100/device/StdDriver/nano100_usbd.h
  targets/TARGET_NUVOTON/TARGET_NANO100/mbed_overrides.c
  targets/TARGET_NUVOTON/USBEndpoints_Nuvoton.cpp
  targets/TARGET_NUVOTON/USBEndpoints_Nuvoton.h
  targets/TARGET_NUVOTON/USBPhyHw.h
  targets/targets.json
Labels: release-version: 6.0.0-alpha-1

#12195 Corrected PPP debug trace flagging
  features/netsocket/ppp/include/ppp_impl.h
  features/netsocket/ppp/source/auth.c
  features/netsocket/ppp/source/chap-new.c
  features/netsocket/ppp/source/fsm.c
  features/netsocket/ppp/source/ipcp.c
  features/netsocket/ppp/source/ipv6cp.c
  features/netsocket/ppp/source/lcp.c
  features/netsocket/ppp/source/utils.c
Labels: release-version: 6.0.0-alpha-1

#12181 Add DTLS in Connectivity's design document
  docs/design-documents/features/connectivity/TLSSocket - Design document.md
Labels: component: docs, release-version: 6.0.0-alpha-1

#12055 cmsis: remove arm math
  cmsis/TARGET_CORTEX_M/arm_math.h
  targets/TARGET_NUVOTON/nu_bitutil.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/drivers/fsl_powerquad_cmsis.c
Labels: BREAKING-CHANGE, release-version: 6.0.0-alpha-1

#12081 Expose target_offset and header_offset parameters in targets.json
  targets/targets.json
Labels: release-version: 6.0.0-alpha-1

#12216 Fix dl_channel tests
  UNITTESTS/features/lorawan/loramaccommand/Test_LoRaMacCommand.cpp
Labels: release-version: 6.0.0-alpha-1

#12151 NRF5x: Fix baremetal linker error
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_11/libraries/util/nrf_assert.c
Labels: release-version: 6.0.0-alpha-1

#12214 Cellular: Move string_to_pdp_type method to CellularContext
  UNITTESTS/features/cellular/framework/common/util/utiltest.cpp
  UNITTESTS/features/cellular/framework/device/cellularcontext/cellularcontexttest.cpp
  UNITTESTS/stubs/CellularContext_stub.cpp
  UNITTESTS/stubs/CellularUtil_stub.cpp
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/common/CellularUtil.cpp
  features/cellular/framework/common/CellularUtil.h
  features/cellular/framework/device/CellularContext.cpp
Labels: release-version: 6.0.0-alpha-1

#12217 Nuvoton: Add DEVICE_USBDEVICE detection in usbd implementation
  targets/TARGET_NUVOTON/USBEndpoints_Nuvoton.cpp
Labels: release-version: 6.0.0-alpha-1

#12202 Increase MSI clock frequency when exiting deep sleep
  targets/TARGET_STM/sleep.c
Labels: release-version: 6.0.0-alpha-1

#12037 SharedPtr: add move operations
  platform/SharedPtr.h
Labels: release-version: 6.0.0-alpha-1

#12143 Blockdevice config changes to make it possible to run littlefs filesystem tests
  components/storage/blockdevice/COMPONENT_DATAFLASH/DataFlashBlockDevice.h
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.h
  components/storage/blockdevice/COMPONENT_RSPIF/SPIFReducedBlockDevice.h
  components/storage/blockdevice/COMPONENT_RSPIF/mbed_lib.json
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.h
  components/storage/blockdevice/COMPONENT_SD/mbed_lib.json
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.h
  features/storage/system_storage/SystemStorage.cpp
  tools/test_configs/QSPIFBlockDeviceAndHeapBlockDevice.json
  tools/test_configs/RSPIFBlockDeviceAndHeapBlockDevice.json
  tools/test_configs/SDBlockDeviceAndHeapBlockDevice.json
  tools/test_configs/SPIFBlockDeviceAndHeapBlockDevice.json
Labels: release-version: 6.0.0-alpha-1

#12122 ATHandler refactoring
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/at_cellulardevicetest.cpp
  UNITTESTS/features/cellular/framework/device/athandler/athandlertest.cpp
  UNITTESTS/features/cellular/framework/device/athandler/unittest.cmake
  UNITTESTS/stubs/ATHandler_stub.cpp
  features/cellular/framework/API/ATHandler.h
  features/cellular/framework/device/ATHandler.cpp
Labels: release-version: 6.0.0-alpha-1

#12215 Cellular: Implementation of virtual get_ip_address funtion in ublox-api
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.h
Labels: release-version: 6.0.0-alpha-1

#12218 tests-mbed_hal-common_tickers: adapt ticker_interrupt_test() test case for high frequency tickers - WIP
  TESTS/mbed_hal/common_tickers/main.cpp
Labels: release-version: 6.0.0-alpha-1

#12200 Minor fixes for peripheral pins on Dragonfly Nano
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/PeripheralPins.c
Labels: release-version: 6.0.0-alpha-1

#11897 MbedCRC: improve init value handling and tests
  TESTS/mbed_drivers/crc/main.cpp
  TESTS/mbed_hal/crc/main.cpp
  drivers/MbedCRC.h
  platform/cxxsupport/mstd_type_traits
Labels: release-version: 6.0.0-alpha-1

#12197 Import TF-M NS APIs into Mbed OS
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_TWINCPU/.gitkeep
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_TWINCPU/inc/ns_ipc_config.h
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_TWINCPU/inc/platform_multicore.h
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_TWINCPU/inc/tfm_mailbox.h
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_TWINCPU/inc/tfm_multi_core_api.h
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_TWINCPU/inc/tfm_ns_mailbox.h
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_TWINCPU/src/platform_multicore.c
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_TWINCPU/src/platform_ns_mailbox.c
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_TWINCPU/src/tfm_multi_core_api.c
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_TWINCPU/src/tfm_multi_core_psa_ns_api.c
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_TWINCPU/src/tfm_ns_mailbox.c
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V8M/.gitkeep
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V8M/src/tfm_ns_interface.c
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V8M/src/tfm_nspm_api.c
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V8M/src/tfm_nspm_svc_handler.c
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V8M/src/tfm_psa_ns_api.c
  features/FEATURE_PSA/TARGET_TFM/include/os_wrapper/.mbedignore
  features/FEATURE_PSA/TARGET_TFM/include/os_wrapper/common.h
  features/FEATURE_PSA/TARGET_TFM/include/os_wrapper/mutex.h
  features/FEATURE_PSA/TARGET_TFM/include/os_wrapper/semaphore.h
  features/FEATURE_PSA/TARGET_TFM/include/os_wrapper/thread.h
  features/FEATURE_PSA/TARGET_TFM/include/psa/client.h
  features/FEATURE_PSA/TARGET_TFM/include/psa/crypto.h
  features/FEATURE_PSA/TARGET_TFM/include/psa/crypto_extra.h
  features/FEATURE_PSA/TARGET_TFM/include/psa/crypto_platform.h
  features/FEATURE_PSA/TARGET_TFM/include/psa/crypto_sizes.h
  features/FEATURE_PSA/TARGET_TFM/include/psa/crypto_struct.h
  features/FEATURE_PSA/TARGET_TFM/include/psa/crypto_types.h
  features/FEATURE_PSA/TARGET_TFM/include/psa/crypto_values.h
  features/FEATURE_PSA/TARGET_TFM/include/psa/error.h
  features/FEATURE_PSA/TARGET_TFM/include/psa/initial_attestation.h
  features/FEATURE_PSA/TARGET_TFM/include/psa/protected_storage.h
  features/FEATURE_PSA/TARGET_TFM/include/psa/service.h
  features/FEATURE_PSA/TARGET_TFM/include/psa_manifest/sid.h
  features/FEATURE_PSA/TARGET_TFM/include/tfm_api.h
  features/FEATURE_PSA/TARGET_TFM/include/tfm_crypto_defs.h
  features/FEATURE_PSA/TARGET_TFM/include/tfm_ns_interface.h
  features/FEATURE_PSA/TARGET_TFM/include/tfm_ns_svc.h
  features/FEATURE_PSA/TARGET_TFM/include/tfm_nspm_api.h
  features/FEATURE_PSA/TARGET_TFM/include/tfm_nspm_svc_handler.h
  features/FEATURE_PSA/TARGET_TFM/include/tfm_sst_defs.h
  features/FEATURE_PSA/TARGET_TFM/include/tfm_veneers.h
  features/FEATURE_PSA/TARGET_TFM/src/os_wrapper_cmsis_rtos_v2.c
  features/FEATURE_PSA/TARGET_TFM/src/tfm_crypto_ipc_api.c
  features/FEATURE_PSA/TARGET_TFM/src/tfm_initial_attestation_ipc_api.c
  features/FEATURE_PSA/TARGET_TFM/src/tfm_sst_ipc_api.c
  targets/targets.json
  tools/psa/build_tfm.py
  tools/psa/tfm_ns_import.json
Labels: release-version: feature branch

#12204 Fix handling of 1.1 MAC commands
  UNITTESTS/features/lorawan/loramaccommand/Test_LoRaMacCommand.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
Labels: release-version: feature branch

#12236 Fix baremetal build failures
  TESTS/netsocket/dns/asynchronous_dns_multi_ip.cpp
  features/storage/TESTS/kvstore/static_tests/main.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-1

#12238 Minimal-printf: Fix wrapping of printf functions for the ARM compiler
  platform/source/minimal-printf/mbed_printf_armlink_overrides.c
  platform/source/minimal-printf/mbed_printf_wrapper.c
Labels: release-version: 6.0.0-alpha-1

#12256 Update psa binaries for 6.0.0-alpha1
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_NS/prebuilt/crypto_access_control.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_NS/prebuilt/spm_client.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_NS/prebuilt/spm_server.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_NS/prebuilt/spm_smoke.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_NS/prebuilt/tfm.bin
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NS/TARGET_NU_PREBUILD_SECURE/crypto_access_control.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NS/TARGET_NU_PREBUILD_SECURE/spm_client.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NS/TARGET_NU_PREBUILD_SECURE/spm_server.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NS/TARGET_NU_PREBUILD_SECURE/spm_smoke.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NS/TARGET_NU_PREBUILD_SECURE/tfm.hex
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/crypto_access_control.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/spm_client.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/spm_server.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/spm_smoke.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/tfm.bin
Labels: ready for merge, release-version: 6.0.0-alpha-1

#11433 FPGA CI shield: Add a watchdog timing test
  TESTS/mbed_timing_fpga_ci_test_shield/watchdog/main.cpp
Labels: release-version: 6.0.0-alpha-2

#12157 ESP8266: Avoid duplicate data sends
  TESTS/netsocket/udp/udp_tests.h
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: release-version: 6.0.0-alpha-2

#12160 nRF52: Properly configure nRF SDK for nRF52-series targets
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_uart.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/objects.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/modules/nrfx/drivers/src/nrfx_twi.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/modules/nrfx/drivers/src/nrfx_twim.c
Labels: release-version: 6.0.0-alpha-2

#12227 Cellular: AT + QICSGP set up APN fix
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularContext.cpp
Labels: release-version: 6.0.0-alpha-2

#12199 Format targets.json
  targets/targets.json
Labels: release-version: 6.0.0-alpha-2

#12234 ESP8266: Add built-in hostname resolution handling (disabled by default)
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
  components/wifi/esp8266-driver/mbed_lib.json
Labels: release-version: 6.0.0-alpha-2

#12237 STM serial free: Set pin function only if pin is defined (not NC)
  targets/TARGET_STM/serial_api.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12239 Fix DNS multiple query hints to perform both IP4 and IP6 tests
  TESTS/netsocket/dns/asynchronous_dns_multi_ip.cpp
  TESTS/netsocket/dns/synchronous_dns_multi_ip.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12243 Add timer shutdown after time stop on deinit
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_bb_ble.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_timer.c
Labels: release-version: 6.0.0-alpha-2

#12249 Cellular: Remove deprecated CellularDevice::stop()
  UNITTESTS/features/cellular/framework/device/cellulardevice/cellulardevicetest.cpp
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/device/CellularDevice.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12254 unittest: fix ATCmdParser test segfault
  UNITTESTS/platform/ATCmdParser/test_ATCmdParser.cpp
Labels: release-version: 6.0.0-alpha-2

#12260 Add KSZ8041 as a supported PHY for the LPC17xx series
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_LPCTarget/lpc_phy_dp83848.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12258 Disable the cell AUX UART by default on EP_AGORA
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_AGORA/ONBOARD_TELIT_ME910.cpp
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_AGORA/mbed_lib.json
Labels: release-version: 6.0.0-alpha-2

#12257 psa: Ensure spaces before partition name comment
  tools/psa/templates/psa_setup.c.tpl
Labels: release-version: 6.0.0-alpha-2

#12263 unittest: fix coverage filtering
  UNITTESTS/unit_test/coverage.py
Labels: release-version: 6.0.0-alpha-2

#12240 Cypress: Initial commit of SoftAP host tests
  targets/TARGET_Cypress/TARGET_PSOC6/TESTS/host_tests/softap_basic.py
  targets/TARGET_Cypress/TARGET_PSOC6/TESTS/host_tests/softap_wpa_supplicant.conf
  targets/TARGET_Cypress/TARGET_PSOC6/TESTS/softap/ap/main.cpp
Labels: devices: cypress, release-version: 6.0.0-alpha-2

#12262 Test: Increase the UART flush delay
  TESTS/mbed_drivers/reset_reason/main.cpp
  TESTS/mbed_drivers/watchdog/main.cpp
  TESTS/mbed_drivers/watchdog_reset/main.cpp
  TESTS/mbed_hal/lp_ticker/main.cpp
  TESTS/mbed_hal/reset_reason/main.cpp
  TESTS/mbed_hal/sleep/sleep_test_utils.h
  TESTS/mbed_hal/watchdog/main.cpp
  TESTS/mbed_hal/watchdog_reset/main.cpp
Labels: release-version: 6.0.0-alpha-2

#12245 NUCLEO_WB55RG - add device name "STM32WB55RGVx"
  targets/targets.json
Labels: release-version: 6.0.0-alpha-2

#12261 Cellular: Fix compilation fail with APN lookup enabled
  features/cellular/framework/AT/AT_CellularContext.cpp
Labels: release-version: 6.0.0-alpha-2

#12241 M2351: Remove LPTICKER to spare memory for non-PSA minimal secure build
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NPSA_NS/TARGET_NU_PREBUILD_SECURE/NuMaker-mbed-TZ-secure-example.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NPSA_NS/TARGET_NU_PREBUILD_SECURE/cmse_lib.o
  targets/targets.json
Labels: release-version: 6.0.0-alpha-2

#12230 TEST: use K64F replace DISCO_L475VG_IOT01A to run some example test
  tools/test/examples/examples.json
Labels: release-version: 6.0.0-alpha-2

#12198 uARM: Fix deprecate warning printing wrongly for GCC_ARM/IAR toolchain build
  tools/build_api.py
  tools/toolchains/arm.py
Labels: release-version: 6.0.0-alpha-2

#12139 HAL: Add a get_capabilities() function to ResetReason API
  TESTS/host_tests/reset_reason.py
  TESTS/mbed_drivers/reset_reason/main.cpp
  TESTS/mbed_hal/reset_reason/main.cpp
  hal/mbed_compat.c
  hal/reset_reason_api.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/reset_reason.c
  targets/TARGET_TOSHIBA/TARGET_TMPM066/reset_reason_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3H6/reset_reason_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM3HQ/reset_reason_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/reset_reason_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/reset_reason_api.c
Labels: release-version: 6.0.0-alpha-2

#12208 ST targets: Replace UARTSerial references with BufferedSerial
  components/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTB_MTS_DRAGONFLY/ONBOARD_TELIT_HE910.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/ONBOARD_TELIT_HE910.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_MTS_DRAGONFLY_F413RH/ONBOARD_TELIT_HE910.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/ONBOARD_UBLOX.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/ONBOARD_QUECTEL_UG96.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_BG96/ONBOARD_QUECTEL_BG96.cpp
  targets/TARGET_STM/TARGET_STM32L4/TARGET_MTS_DRAGONFLY_L471QG/ONBOARD_SARA4_PPP.cpp
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/TARGET_MTB_ADV_WISE_1570/ONBOARD_QUECTEL_BC95.cpp
Labels: release-version: 6.0.0-alpha-2

#12209 NXP target: Replace UARTSerial references with BufferedSerial
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_UBLOX_C027/ONBOARD_UBLOX_PPP.cpp
Labels: release-version: 6.0.0-alpha-2

#12213 ESP8266: Replace UARTSerial references with BufferedSerial
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
Labels: release-version: 6.0.0-alpha-2

#12269 mergify: add fixes to the conditions
  .mergify.yml
Labels: needs: review

#12220 NRF5x targets: Replace UARTSerial references with BufferedSerial
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/TARGET_RIOT_MICRO_MODULE/ONBOARD_RM1000_AT.cpp
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_AGORA/ONBOARD_TELIT_ME910.cpp
Labels: release-version: 6.0.0-alpha-2

#12267 Fix UDP socket test cases
  TESTS/netsocket/udp/main.cpp
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_echotest_burst.cpp
  TESTS/netsocket/udp/udpsocket_open_limit.cpp
  TESTS/netsocket/udp/udpsocket_recv_timeout.cpp
  TESTS/network/multihoming/multihoming_udpsocket_echotest.cpp
  features/cellular/framework/AT/AT_CellularStack.cpp
Labels: release-version: 6.0.0-alpha-2

#12211 Cellular: Replace UARTSerial references with BufferedSerial
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/unittest.cmake
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/device/athandler/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellularcontext/cellularcontexttest.cpp
  UNITTESTS/features/cellular/framework/device/cellularcontext/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellulardevice/unittest.cmake
  UNITTESTS/features/cellular/framework/device/cellularstatemachine/unittest.cmake
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  UNITTESTS/stubs/BufferedSerial_stub.cpp
  UNITTESTS/stubs/UARTSerial_stub.cpp
  UNITTESTS/target_h/myCellularContext.h
  UNITTESTS/target_h/myCellularDevice.h
  features/cellular/framework/API/ATHandler.h
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/device/ATHandler.cpp
  features/cellular/framework/device/CellularContext.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.cpp
  features/cellular/framework/targets/GENERIC/GENERIC_AT3GPP/GENERIC_AT3GPP.cpp
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/EC2X/QUECTEL_EC2X.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26.cpp
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularStack.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.cpp
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/PPP/UBLOX_PPP.cpp
Labels: release-version: 6.0.0-alpha-2

#12265 Refactor unnecessary functions from cellular driver
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/at_cellulardevicetest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellularstack/at_cellularstacktest.cpp
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  UNITTESTS/stubs/AT_CellularDevice_stub.h
  UNITTESTS/target_h/myCellularDevice.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION.h
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.h
  features/cellular/framework/targets/GENERIC/GENERIC_AT3GPP/GENERIC_AT3GPP.cpp
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.h
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.h
  features/cellular/framework/targets/QUECTEL/EC2X/QUECTEL_EC2X.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.h
  features/cellular/framework/targets/QUECTEL/UG96/QUECTEL_UG96.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularStack.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT_CellularStack.h
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.h
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910.cpp
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.h
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularStack.h
  features/cellular/framework/targets/UBLOX/PPP/UBLOX_PPP.cpp
Labels: release-version: 6.0.0-alpha-2

#12253 storage_abstraction: deprecated since Mbed OS 5.5 and now removed
  hal/storage_abstraction/Driver_Common.h
  hal/storage_abstraction/Driver_Storage.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/storage_driver.c
Labels: release-version: 6.0.0-alpha-2

#12273 unittests: disable coverage report filtering
  UNITTESTS/mbed_unittest.py
Labels: release-version: 6.0.0-alpha-2

#12060 Improve reliability of KVStore general tests
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_2/main.cpp
Labels: devices: cypress, release-version: 6.0.0-alpha-2

#12274 mergify: enable for any pull request
  .mergify.yml
Labels: ready for merge, release-version: 6.0.0-alpha-2

#11904 TOOLS: enable build greentea test coverage for HW
  tools/build_api.py
  tools/test.py
  tools/test_api.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
  tools/toolchains/mbed_toolchain.py
Labels: release-version: 6.0.0-alpha-2

#12280 EFM32: add UART and LEUART for EFM32GG11
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG11/PeripheralPins.c
Labels: ready for merge

#12275 Fix call to sorted by providing key to sort on.
  tools/config/__init__.py
Labels: ready for merge

#12035 Preparation for Callback changes
  TESTS/mbed_functional/callback/main.cpp
  TESTS/mbed_functional/callback_big/main.cpp
  TESTS/mbed_functional/callback_small/main.cpp
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  drivers/SerialBase.h
  drivers/internal/PolledQueue.h
  drivers/internal/USBDevice.h
  drivers/source/CAN.cpp
  drivers/source/InterruptIn.cpp
  drivers/source/SPI.cpp
  drivers/source/Serial.cpp
  drivers/source/SerialBase.cpp
  drivers/source/Ticker.cpp
  drivers/source/UARTSerial.cpp
  drivers/source/usb/AsyncOp.cpp
  drivers/source/usb/USBAudio.cpp
  drivers/source/usb/USBCDC.cpp
  drivers/source/usb/USBDevice.cpp
  drivers/source/usb/USBHID.cpp
  drivers/source/usb/USBMIDI.cpp
  drivers/source/usb/USBMSD.cpp
  drivers/source/usb/USBMouse.cpp
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularSMS.cpp
  features/cellular/framework/device/ATHandler.cpp
  features/cellular/framework/device/CellularContext.cpp
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularContext.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX_CellularStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/mac/LoRaMacCrypto.cpp
  features/lorawan/lorastack/phy/LoRaPHYAU915.cpp
  features/lorawan/lorastack/phy/LoRaPHYUS915.cpp
  features/netsocket/nsapi_ppp.h
  features/storage/filesystem/fat/FATFileSystem.cpp
  platform/SharedPtr.h
  platform/cxxsupport/mstd_new
  rtos/source/Thread.cpp
Labels: ready for merge

#12292 Multiple labels need to be in an array of strings
  .mergify.yml
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12225 Fix baremetal heap and stack initialisation
  TESTS/mbedmicro-rtos-mbed/heap_and_stack/main.cpp
  platform/source/TARGET_CORTEX_M/TOOLCHAIN_IAR/cmain.S
  platform/source/mbed_retarget.cpp
  platform/source/mbed_sdk_boot.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12278 Rename "default_lib" to "c_lib".
  TESTS/configs/baremetal.json
  targets/targets.json
  tools/build_api.py
  tools/targets/lint.py
  tools/test/config/app_override_libs/targets.json
  tools/test/config/compound_inheritance/targets.json
  tools/test/config/double_define/targets.json
  tools/test/config/feature_compesition/targets.json
  tools/test/config/feature_recursive_add/targets.json
  tools/test/config/feature_recursive_complex/targets.json
  tools/test/config/feature_remove/targets.json
  tools/test/config/lib_requires_missing_lib/targets.json
  tools/test/config/macro_inheritance/targets.json
  tools/test/config/override_labels_libs/targets.json
  tools/test/config/override_labels_libs_more/targets.json
  tools/test/config/override_labels_targets/targets.json
  tools/test/config/override_precidence/targets.json
  tools/test/config/override_undefined/targets.json
  tools/test/config/override_undefined_libs/targets.json
  tools/test/config/override_with_labels/targets.json
  tools/test/config/range_limits/targets.json
  tools/test/config/range_limits_invalid/targets.json
  tools/test/config/range_limits_override_invalid/targets.json
  tools/test/config/requires_exclude_in_include/targets.json
  tools/test/config/requires_from_lib/targets.json
  tools/test/config/requires_include_in_exclude/targets.json
  tools/test/config/requires_omit_lib/targets.json
  tools/test/config/simple_features/targets.json
  tools/test/config/simple_iheritance/targets.json
  tools/test/targets/target_test.py
  tools/test/toolchains/test_toolchains.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12023 GCC: remove -fno-delete-null-pointer-checks
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge

#12228 Need RAM and ROM size for compilation
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge

#12282 Fix for issue #12268 (SerialBase.cpp: fix initialization list)
  drivers/source/SerialBase.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12291 Minor optimisation to ATCmdParser unit test code
  UNITTESTS/platform/ATCmdParser/test_ATCmdParser.cpp
Labels: ready for merge

#12295 STM32H7 correct PWMOUT instances
  targets/TARGET_STM/TARGET_STM32H7/pwmout_device.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12297 Corrected minimal-printf README
  platform/source/minimal-printf/README.md
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12154 NRF51822: Fix baremetal linker error
  targets/TARGET_NORDIC/TARGET_MCU_NRF51822/us_ticker.c
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12210 Fix for issue #10725: disable lp-ticker for STM targets which uses RTC/LSI for lp-ticker
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12226 target_test - assert if sectors keyword missing
  tools/test/targets/target_test.py
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12303 Fix ARM compiler warning for microlib
  tools/test/toolchains/test_toolchains.py
  tools/toolchains/arm.py
Labels: ready for merge

#12231 Import latest python scripts and MCUBoot image
  requirements.txt
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_NS/prebuilt/README.md
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_NS/prebuilt/mcuboot.bin
  tools/psa/tfm/bin_utils/assemble.py
  tools/psa/tfm/bin_utils/imgtool.py
  tools/psa/tfm/bin_utils/imgtool_lib/boot_record.py
  tools/psa/tfm/bin_utils/imgtool_lib/image.py
  tools/psa/tfm/bin_utils/imgtool_lib/keys.py
  tools/psa/tfm/bin_utils/macro_parser.py
  tools/targets/ARM_MUSCA_A1.py
  tools/targets/musca_a1-root-rsa-2048.pem
  tools/targets/musca_a1-root-rsa-3072.md
  tools/targets/musca_a1-root-rsa-3072.pem
Labels: ready for merge

#12307 Fix the missing retrieve error context function call.
  platform/source/mbed_sdk_boot.c
Labels: ready for merge

#12310 Greentea DNS tests workaround.
  TESTS/netsocket/dns/main.cpp
Labels: ready for merge

#12315 Add check for __APPLE__ & __MACH__ to fix unit tests on macOS
  events/internal/equeue_platform.h
Labels: ready for merge

#12304 QSPIF: Enable QPI mode as a second option, if available
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
Labels: ready for merge

#12324 Fix inconsistency between mbed crc and psoc6 crc implementations.
  targets/TARGET_Cypress/TARGET_PSOC6/cy_crc_api.c
Labels: ready for merge

#12322 minimal-printf: README correction
  platform/source/minimal-printf/README.md
Labels: ready for merge

#12321 Ble driver set random static address
  features/FEATURE_BLE/ble/gap/Gap.h
  features/FEATURE_BLE/ble/generic/GenericGap.h
  features/FEATURE_BLE/source/gap/Gap.tpp
  features/FEATURE_BLE/source/generic/GenericGap.tpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/CordioHCIDriver.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/driver/CordioHCIDriver.h
  features/FEATURE_BLE/targets/TARGET_CORDIO_ODIN_W2/HCIDriver.cpp
  features/FEATURE_BLE/targets/TARGET_Cypress/COMPONENT_CYW43XXX/HCIDriver.cpp
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_CYW4343X/HCIDriver.cpp
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/HCIDriver.cpp
Labels: ready for merge

#12302 Remove _LIBCPP_EXTERN_TEMPLATE ARMCC compilation flag
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge

#12331 STM32: enable QSPI test with MX25LM51245G octo SPI
  TESTS/mbed_hal/qspi/flash_configs/MX25LM51245G_config.h
  components/storage/blockdevice/COMPONENT_QSPIF/mbed_lib.json
  targets/targets.json
Labels: ready for merge

#12308 Tests: add missing mbed_trace.h multihoming header
  TESTS/network/multihoming/multihoming_tests.h
Labels: ready for merge

#12153 Hackathon: Increase coverage of the SPI master FPGA test
  TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/spi/spi_fpga_test.h
  hal/mbed_compat.c
  hal/spi_api.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/spi_api.c
  targets/TARGET_STM/stm_spi_api.c
Labels: ready for merge

#12296 FPGA_CI_TEST_SHIELD : force all peripheral to be tested
  TESTS/mbed_hal_fpga_ci_test_shield/pwm/main.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/test_utils.h
Labels: ready for merge

#12316 Fix general filesystem greentea test
  features/storage/TESTS/filesystem/general_filesystem/main.cpp
Labels: ready for merge

#12326 Correct SysTimer absolute time calculations
  platform/source/SysTimer.cpp
  platform/source/SysTimer.h
Labels: ready for merge

#12327 Doxygen: don't extract static members
  doxyfile_options
Labels: ready for merge

#12335 Remove CPU usage example from CI build
  tools/test/examples/examples.json
Labels: ready for merge

#12330 Fix FAT filesystem `ferror` greentea test(SD Component)
  components/storage/blockdevice/COMPONENT_SD/TESTS/filesystem/fopen/fopen.cpp
Labels: ready for merge

#12336 Disable write buffering on debug builds.
  platform/source/mbed_application.c
  platform/source/mbed_sdk_boot.c
  rtos/source/TARGET_CORTEX/mbed_boot.c
Labels: ready for merge

#12344 Unittests for DNS improvements
  UNITTESTS/moduletests/features/netsocket/IfaceDnsSocket/moduletest.cpp
  UNITTESTS/moduletests/features/netsocket/IfaceDnsSocket/unittest.cmake
Labels: ready for merge

#12299 MIMXRT1050: Add Watchdog support
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/watchdog_api.c
  targets/targets.json
Labels: ready for merge
