Repository ARMmbed/mbed-os, pull requests merged in 2020-12, with the labels that each got.

#13945 Freescale: Remove K20XX files
  targets/TARGET_Freescale/TARGET_K20XX/PeripheralPins.h
  targets/TARGET_Freescale/TARGET_K20XX/PortNames.h
  targets/TARGET_Freescale/TARGET_K20XX/analogin_api.c
  targets/TARGET_Freescale/TARGET_K20XX/analogout_api.c
  targets/TARGET_Freescale/TARGET_K20XX/clk_freqs.h
  targets/TARGET_Freescale/TARGET_K20XX/gpio_api.c
  targets/TARGET_Freescale/TARGET_K20XX/gpio_irq_api.c
  targets/TARGET_Freescale/TARGET_K20XX/gpio_object.h
  targets/TARGET_Freescale/TARGET_K20XX/i2c_api.c
  targets/TARGET_Freescale/TARGET_K20XX/objects.h
  targets/TARGET_Freescale/TARGET_K20XX/pinmap.c
  targets/TARGET_Freescale/TARGET_K20XX/port_api.c
  targets/TARGET_Freescale/TARGET_K20XX/pwmout_api.c
  targets/TARGET_Freescale/TARGET_K20XX/rtc_api.c
  targets/TARGET_Freescale/TARGET_K20XX/serial_api.c
  targets/TARGET_Freescale/TARGET_K20XX/sleep.c
  targets/TARGET_Freescale/TARGET_K20XX/spi_api.c
Labels: ready for merge, release-type: patch

#13929 STM32: LPUART clock source selection up to a serial driver
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/system_clock.c
  targets/TARGET_STM/TARGET_STM32L5/system_clock.c
Labels: ready for merge, release-type: patch

#13963 Fix ThisThread warnings
  rtos/source/ThisThread.cpp
Labels: ready for merge, release-type: patch

#13985 CMake: fix memory map generation
  CMakeLists.txt
  tools/cmake/toolchains/ARM.cmake
  tools/cmake/toolchains/GCC_ARM.cmake
Labels: ready for merge, release-type: patch

#13925 Cypress: Remove CY8CKIT_064S2_4343W files
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/COMPONENT_CM4/device_cfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/tfm_s.axf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/tfm_s.hex
Labels: needs: review, release-type: patch

#13934 CMake: Add support for Cypress targets
  targets/CMakeLists.txt
  targets/TARGET_Cypress/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/common/COMPONENT_WHD/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/rtos/CMakeLists.txt
  targets/targets.json
  tools/cmake/README.md
Labels: ready for merge, release-type: patch

#13978 S5JS100: remove idle hook in favour of Mbed-default idle hook
  targets/TARGET_Samsung/TARGET_SIDK_S5JS100/sleep.c
Labels: ready for merge, release-type: patch

#13970 CMake: Add support for all Maxim Mbed targets
  targets/CMakeLists.txt
  targets/TARGET_Maxim/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32620C/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32620C/device/TOOLCHAIN_ARM_STD/MAX32620.sct
  targets/TARGET_Maxim/TARGET_MAX32625/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32625/device/TOOLCHAIN_ARM_STD/TARGET_MAX32625_BOOT/MAX32625.sct
  targets/TARGET_Maxim/TARGET_MAX32625/device/TOOLCHAIN_ARM_STD/TARGET_MAX32625_NO_BOOT/MAX32625.sct
  targets/TARGET_Maxim/TARGET_MAX32630/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32630/device/TOOLCHAIN_ARM_STD/MAX3263x.sct
  tools/cmake/README.md
Labels: ready for merge, release-type: patch

#14006 [STD-PIN] Updates after review
  hal/include/hal/ArduinoUnoAliases.h
  hal/tests/TESTS/pin_names/arduino_uno/main.cpp
  hal/tests/TESTS/pin_names/generic/main.cpp
Labels: needs: review, release-version: feature branch

#13777 STM32 : full GPIO reset during mbed init
  targets/TARGET_STM/mbed_overrides.c
Labels: ready for merge, release-type: patch

#13936 Network interface MAC address set/get
  UNITTESTS/stubs/NetworkInterface_stub.cpp
  connectivity/nanostack/include/nanostack-interface/Nanostack.h
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackPPPInterface.h
  connectivity/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  connectivity/nanostack/mbed-mesh-api/source/NanostackEMACInterface.cpp
  connectivity/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  connectivity/netsocket/include/netsocket/EMACInterface.h
  connectivity/netsocket/include/netsocket/NetworkInterface.h
  connectivity/netsocket/include/netsocket/OnboardNetworkStack.h
  connectivity/netsocket/source/EMACInterface.cpp
  connectivity/netsocket/source/NetworkInterface.cpp
  connectivity/netsocket/tests/TESTS/network/emac/emac_TestNetworkStack.cpp
  connectivity/netsocket/tests/TESTS/network/emac/emac_TestNetworkStack.h
  connectivity/netsocket/tests/UNITTESTS/netsocket/NetworkInterface/test_NetworkInterface.cpp
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_WIO_EMW3166/libwiced_drivers.ar
Labels: ready for merge, release-type: feature

#13907 Workaround to fix RTC-reset issue on the EFM32GG11_STK3701
  targets/TARGET_Silicon_Labs/TARGET_EFM32/rtcc.c
Labels: ready for merge, release-type: patch

#13992 STM32_gen_PeripheralPins.py v1.19
  targets/TARGET_STM/README.md
  targets/TARGET_STM/tools/STM32_gen_PeripheralPins.py
Labels: ready for merge, release-type: patch

#14003 STM32H7: system power supply configuration
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI2/system_clock.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H745xI/system_clock.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/system_clock.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/system_clock.c
  targets/TARGET_STM/mbed_overrides.c
  targets/targets.json
Labels: ready for merge, release-type: patch

#13996 TDBStore: pad program units when writing record_header_t; ensure work buffer is large enough
  storage/kvstore/include/kvstore/TDBStore.h
  storage/kvstore/source/TDBStore.cpp
  storage/kvstore/tests/UNITTESTS/TDBStore/moduletest.cpp
Labels: ready for merge, release-type: patch

#14000 Add octa RAM calibration feature to GR-MANGO.
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/TARGET_GR_MANGO/device/system_RZ_A2M.c
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/common/r_octabus/inc/r_octabus_drv_sc_cfg.h
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/common/r_octabus/inc/r_octabus_lld_rza2m_api.h
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/common/r_octabus/src/lld/r_octabus_lld_rza2m_api.c
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/common/r_octabus/src/lld/r_octabus_memclk_setup.c
Labels: ready for merge, release-type: patch

#14017 Nuvoton: Remove DISABLE/ENABLE macro definitions in BSP
  targets/TARGET_NUVOTON/TARGET_M2351/device/M2351.h
  targets/TARGET_NUVOTON/TARGET_M251/device/M251.h
  targets/TARGET_NUVOTON/TARGET_M261/device/M261.h
  targets/TARGET_NUVOTON/TARGET_M480/device/M480.h
  targets/TARGET_NUVOTON/TARGET_NANO100/device/Nano100Series.h
  targets/TARGET_NUVOTON/TARGET_NUC472/device/NUC472_442.h
Labels: ready for merge, release-type: patch

#13998 Add crash reporting and autoreboot capability to MTS_DRAGONFLY_L471QG
  platform/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L471xG/TOOLCHAIN_ARM/stm32l471xg.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L471xG/TOOLCHAIN_GCC_ARM/stm32l471xg.ld
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L471xG/TOOLCHAIN_IAR/stm32l471xg.icf
Labels: ready for merge, release-type: patch

#14001 Add missing retry to atomic exchange
  platform/include/platform/internal/mbed_atomic_impl.h
Labels: needs: work, release-type: patch

#13995 CMake: Add support for GigaDevice targets
  targets/CMakeLists.txt
  targets/TARGET_GigaDevice/CMakeLists.txt
  targets/TARGET_GigaDevice/TARGET_GD32F30X/CMakeLists.txt
  targets/TARGET_GigaDevice/TARGET_GD32F30X/TARGET_GD32F307VG/device/TOOLCHAIN_ARM_STD/gd32f307vg.sct
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/CMakeLists.txt
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/device/TOOLCHAIN_ARM_STD/gd32f450zi.sct
  tools/cmake/README.md
Labels: needs: CI, release-type: patch

#14005 Correct/clarify TimerEvent::insert documentation
  drivers/include/drivers/TimerEvent.h
  drivers/source/TimerEvent.cpp
Labels: ready for merge, release-type: patch

#13961 Silabs: Remove EFR32_1 rail files
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/TARGET_EFR32_1/ieee802154_subg_efr32xg1_configurator_out.c
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/TARGET_EFR32_1/ieee802154_subg_efr32xg1_configurator_out.h
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/TARGET_EFR32_1/librail_efr32xg1_release.a
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/efr32-rf-driver/rail/TARGET_EFR32_1/librail_efr32xg1_release.ar
Labels: ready for merge, release-type: patch

#13548 Add width modifier and prepending zeros for hexadecimal output and decimal precision for floating point
  platform/source/minimal-printf/README.md
  platform/source/minimal-printf/mbed_printf_implementation.c
  platform/tests/TESTS/mbed_platform/minimal-printf/compliance/main.cpp
Labels: ready for merge, release-type: feature

#13959 CMake: Add support for all Silicon Labs Mbed targets
  targets/CMakeLists.txt
  targets/TARGET_Silicon_Labs/CMakeLists.txt
  targets/TARGET_Silicon_Labs/TARGET_EFM32/CMakeLists.txt
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG/CMakeLists.txt
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG/device/TARGET_1024K/TOOLCHAIN_ARM_STD/efm32gg.sct
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG11/CMakeLists.txt
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG11/device/TOOLCHAIN_ARM_STD/efm32gg11.sct
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/CMakeLists.txt
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/device/TOOLCHAIN_ARM_STD/efr32mg12p.sct
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/CMakeLists.txt
  tools/cmake/README.md
Labels: ready for merge, release-type: patch

#13957 Replaced new calls with nothrow version of the call on mesh api
  connectivity/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop_mbed.cpp
  connectivity/nanostack/source/Nanostack.cpp
Labels: ready for merge, release-type: patch

#13987 CMake: Set required toolchain and processor flags globally, instead of per-target
  CMakeLists.txt
  tools/cmake/app.cmake
  tools/cmake/core.cmake
  tools/cmake/cores/Cortex-A9.cmake
  tools/cmake/cores/Cortex-M0+.cmake
  tools/cmake/cores/Cortex-M0.cmake
  tools/cmake/cores/Cortex-M1.cmake
  tools/cmake/cores/Cortex-M23-NS.cmake
  tools/cmake/cores/Cortex-M23.cmake
  tools/cmake/cores/Cortex-M3.cmake
  tools/cmake/cores/Cortex-M33-NS.cmake
  tools/cmake/cores/Cortex-M33.cmake
  tools/cmake/cores/Cortex-M33F-NS.cmake
  tools/cmake/cores/Cortex-M33F.cmake
  tools/cmake/cores/Cortex-M33FE-NS.cmake
  tools/cmake/cores/Cortex-M33FE.cmake
  tools/cmake/cores/Cortex-M4.cmake
  tools/cmake/cores/Cortex-M4F.cmake
  tools/cmake/cores/Cortex-M7.cmake
  tools/cmake/cores/Cortex-M7F.cmake
  tools/cmake/cores/Cortex-M7FD.cmake
  tools/cmake/profiles/debug.cmake
  tools/cmake/profiles/develop.cmake
  tools/cmake/profiles/release.cmake
  tools/cmake/toolchain.cmake
  tools/cmake/toolchains/ARM.cmake
  tools/cmake/toolchains/GCC_ARM.cmake
Labels: ready for merge, release-type: patch

#13988 BLE: Fix periodic advertrising sync based on advertiser list
  connectivity/FEATURE_BLE/libraries/TARGET_CORDIO_LL/stack/controller/sources/ble/lctr/lctr_isr_adv_master_ae.c
Labels: ready for merge, release-type: patch

#13924 CMake: Add support for all NXP Mbed targets
  targets/CMakeLists.txt
  targets/TARGET_NXP/CMakeLists.txt
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/CMakeLists.txt
  targets/TARGET_NXP/TARGET_LPC176X/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_S/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/CMakeLists.txt
  tools/cmake/README.md
  tools/cmake/cores/Cortex-M0.cmake
  tools/cmake/cores/Cortex-M3.cmake
  tools/cmake/cores/Cortex-M33-NS.cmake
  tools/cmake/cores/Cortex-M33.cmake
Labels: ready for merge, release-type: patch

#13917 Move SFDP to blockdevice
  drivers/device_key/CMakeLists.txt
  storage/blockdevice/CMakeLists.txt
  storage/blockdevice/COMPONENT_OSPIF/include/QSPIF/OSPIFBlockDevice.h
  storage/blockdevice/COMPONENT_OSPIF/source/OSPIFBlockDevice.cpp
  storage/blockdevice/COMPONENT_QSPIF/include/QSPIF/QSPIFBlockDevice.h
  storage/blockdevice/COMPONENT_QSPIF/source/QSPIFBlockDevice.cpp
  storage/blockdevice/COMPONENT_SPIF/include/SPIF/SPIFBlockDevice.h
  storage/blockdevice/COMPONENT_SPIF/source/SPIFBlockDevice.cpp
  storage/blockdevice/include/blockdevice/internal/SFDP.h
  storage/blockdevice/source/SFDP.cpp
  storage/blockdevice/tests/UNITTESTS/SFDP/test_sfdp.cpp
  storage/blockdevice/tests/UNITTESTS/SFDP/unittest.cmake
Labels: ready for merge, release-type: patch

#14014 Update GattAuthCallbackReply_t enumeration.
  connectivity/FEATURE_BLE/include/ble/gatt/GattCallbackParamTypes.h
Labels: ready for merge, release-type: feature

#14009 ble cyw43xxx: dev/hci driver terminate
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_CYW43XXX/CyH4TransportDriver.cpp
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_CYW43XXX/CyH4TransportDriver.h
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_CYW43XXX/TARGET_PSOC6/cy_bt_cordio_cfg.cpp
Labels: Priority-High, devices: cypress, ready for merge, release-type: patch

#14024 CMake: add Samsungs, Analog devices and WICED targets
  targets/CMakeLists.txt
  targets/TARGET_Analog_Devices/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TOOLCHAIN_ARM_STD/ADuCM3029.sct
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TOOLCHAIN_ARM_STD/ADuCM4050.sct
  targets/TARGET_Samsung/CMakeLists.txt
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/CMakeLists.txt
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/device/TOOLCHAIN_ARM_STD/s1sbp6a.sct
  targets/TARGET_Samsung/TARGET_SIDK_S5JS100/CMakeLists.txt
  targets/TARGET_Samsung/TARGET_SIDK_S5JS100/device/TOOLCHAIN_ARM_STD/sidk_s5js100.sct
  targets/TARGET_Samsung/TARGET_SIDK_S5JS100/device/system_core_s5js100.c
  targets/TARGET_WICED/CMakeLists.txt
  tools/cmake/README.md
Labels: Priority-High, ready for merge, release-type: patch

#13972 CMake: Add support for WICED target
  targets/CMakeLists.txt
  targets/TARGET_WICED/CMakeLists.txt
  tools/cmake/README.md
Labels: needs: work, release-type: patch

#14019 Port analog devices to CMake
  targets/CMakeLists.txt
  targets/TARGET_Analog_Devices/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TOOLCHAIN_ARM_STD/ADuCM3029.sct
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TOOLCHAIN_ARM_STD/ADuCM4050.sct
  tools/cmake/README.md
Labels: needs: CI, release-type: patch

#13908 Restructure KVStore to one library per store type
  TESTS/configs/baremetal.json
  UNITTESTS/CMakeLists.txt
  drivers/device_key/CMakeLists.txt
  drivers/device_key/source/DeviceKey.cpp
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/CMakeLists.txt
  storage/CMakeLists.txt
  storage/filesystem/CMakeLists.txt
  storage/kvstore/CMakeLists.txt
  storage/kvstore/direct_access_devicekey/CMakeLists.txt
  storage/kvstore/direct_access_devicekey/tests/TESTS/direct_access_devicekey/tdb/main.cpp
  storage/kvstore/filesystemstore/CMakeLists.txt
  storage/kvstore/filesystemstore/include/filesystemstore/FileSystemStore.h
  storage/kvstore/filesystemstore/mbed_lib.json
  storage/kvstore/filesystemstore/source/FileSystemStore.cpp
  storage/kvstore/filesystemstore/tests/TESTS/filesystemstore/general/main.cpp
  storage/kvstore/filesystemstore/tests/UNITTESTS/.mbedignore
  storage/kvstore/filesystemstore/tests/UNITTESTS/FileSystemStore/moduletest.cpp
  storage/kvstore/filesystemstore/tests/UNITTESTS/FileSystemStore/unittest.cmake
  storage/kvstore/kv_config/CMakeLists.txt
  storage/kvstore/kv_config/source/kv_config.cpp
  storage/kvstore/kvstore_global_api/CMakeLists.txt
  storage/kvstore/kvstore_global_api/include/kvstore_global_api/KVMap.h
  storage/kvstore/kvstore_global_api/include/kvstore_global_api/kvstore_global_api.h
  storage/kvstore/kvstore_global_api/mbed_lib.json
  storage/kvstore/kvstore_global_api/source/KVMap.cpp
  storage/kvstore/kvstore_global_api/source/kvstore_global_api.cpp
  storage/kvstore/mbed_lib.json
  storage/kvstore/securestore/CMakeLists.txt
  storage/kvstore/securestore/tests/TESTS/securestore/whitebox/main.cpp
  storage/kvstore/tdbstore/CMakeLists.txt
  storage/kvstore/tdbstore/include/tdbstore/TDBStore.h
  storage/kvstore/tdbstore/mbed_lib.json
  storage/kvstore/tdbstore/source/TDBStore.cpp
  storage/kvstore/tdbstore/tests/TESTS/tdbstore/whitebox/main.cpp
  storage/kvstore/tdbstore/tests/UNITTESTS/.mbedignore
  storage/kvstore/tdbstore/tests/UNITTESTS/TDBStore/moduletest.cpp
  storage/kvstore/tdbstore/tests/UNITTESTS/TDBStore/unittest.cmake
  storage/kvstore/tests/TESTS/kvstore/general_tests_phase_1/main.cpp
  storage/kvstore/tests/TESTS/kvstore/general_tests_phase_2/main.cpp
Labels: Priority-High, ready for merge, release-type: feature

#13946 Update to reflect Mbed CLI 2 changes
  docs/design-documents/tools/cmake.md
  tools/cmake/README.md
  tools/test/examples/examples_lib.py
Labels: Priority-High, needs: work, release-type: patch

#14034 FIX: update cryptography version to 2.5 or later
  requirements.txt
Labels: Release review required, ready for merge

#13927 targets:evkbimxrt1050: Adjust the SEMC re-order rules
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/xip/evkbimxrt1050_sdram_ini_dcd.c
Labels: ready for merge, release-version: feature branch

#14033 FIX: update cryptography version to 2.5 or later
  requirements.txt
Labels: ready for merge, release-version: feature branch

#14040 [feature-wisun] Nanostack release v12.7.0
  features/frameworks/nanostack-libservice/mbed-client-libservice/nsdynmemLIB.h
  features/frameworks/nanostack-libservice/mbed_lib.json
  features/frameworks/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c
  features/frameworks/nanostack-libservice/test/libService/unittest/nsdynmem/dynmemtest.cpp
  features/nanostack/sal-stack-nanostack-eventloop/source/event.c
  features/nanostack/sal-stack-nanostack/nanostack/nwk_stats_api.h
  features/nanostack/sal-stack-nanostack/nanostack/platform/arm_hal_phy.h
  features/nanostack/sal-stack-nanostack/nanostack/ws_bbr_api.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps/Generic/protocol_6lowpan.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ND/nd_router_object.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/adaptation_interface.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_config.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_eapol_auth_relay.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_eapol_pdu.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_eapol_relay.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_llc_data_service.c
  features/nanostack/sal-stack-nanostack/source/Common_Protocols/icmpv6.c
  features/nanostack/sal-stack-nanostack/source/Common_Protocols/ipv6.c
  features/nanostack/sal-stack-nanostack/source/Core/include/ns_buffer.h
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mlme.c
  features/nanostack/sal-stack-nanostack/source/MPL/mpl.c
  features/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/Include/protocol.h
  features/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/Include/protocol_stats.h
  features/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/protocol_stats.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_control.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_downward.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_upward.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot/radius_client_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot/tls_sec_prot_lib.c
  features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.c
  features/nanostack/sal-stack-nanostack/source/Service_Libs/random_early_detection/random_early_detection.c
  features/nanostack/sal-stack-nanostack/source/Service_Libs/random_early_detection/random_early_detection.h
  features/nanostack/sal-stack-nanostack/source/Service_Libs/random_early_detection/random_early_detection_api.h
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/dhcp_service_api.c
  features/nanostack/sal-stack-nanostack/sources.mk
Labels: ready for merge, release-version: feature branch

#13937 [feature-wisun] Replaced new calls with nothrow version of the call on mesh api
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop_mbed.cpp
  features/nanostack/nanostack-interface/Nanostack.cpp
Labels: ready for merge, release-version: feature branch

#14018 Corrected Wi-SUN certificate add and remove functions on Wi-SUN interface
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: feature branch

#13902 [feature-wisun] Network interface MAC address set/get
  TESTS/network/emac/emac_TestNetworkStack.cpp
  TESTS/network/emac/emac_TestNetworkStack.h
  UNITTESTS/features/netsocket/NetworkInterface/test_NetworkInterface.cpp
  UNITTESTS/stubs/NetworkInterface_stub.cpp
  features/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEMACInterface.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  features/nanostack/nanostack-interface/Nanostack.h
  features/netsocket/EMACInterface.cpp
  features/netsocket/EMACInterface.h
  features/netsocket/NetworkInterface.cpp
  features/netsocket/NetworkInterface.h
  features/netsocket/OnboardNetworkStack.h
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
Labels: ready for merge, release-version: feature branch

#14054 [feature-wisun] Nanostack 802.15.4 Atmel RF driver update
  components/802.15.4_RF/atmel-rf-driver/source/AT86RF215Reg.h
  components/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAT86RF215.cpp
Labels: ready for merge, release-version: feature branch

#13944 CMake: Add requirements.txt file for required Python modules
  tools/cmake/README.md
  tools/cmake/requirements.txt
Labels: ready for merge, release-type: patch

#13965 Clarify the time units stated in the delay and period function headers for events
  events/include/events/Event.h
Labels: ready for merge, release-type: patch

#14007 Clean-up: TDBStore no longer requires BlockDevice to have flash behaviour
  storage/docs/BlockDevices/get_type_method.md
  storage/docs/TDBStore/TDBStore_design.md
  storage/kvstore/kv_config/source/kv_config.cpp
  storage/kvstore/securestore/tests/TESTS/securestore/whitebox/main.cpp
  storage/kvstore/tdbstore/include/tdbstore/TDBStore.h
  storage/kvstore/tdbstore/tests/TESTS/tdbstore/whitebox/main.cpp
  storage/kvstore/tdbstore/tests/UNITTESTS/TDBStore/moduletest.cpp
  storage/kvstore/tdbstore/tests/UNITTESTS/TDBStore/unittest.cmake
  storage/kvstore/tests/TESTS/kvstore/general_tests_phase_1/main.cpp
  storage/kvstore/tests/TESTS/kvstore/general_tests_phase_2/main.cpp
Labels: ready for merge, release-type: patch

#14021 CMake: Add support for Renesas targets
  connectivity/drivers/emac/TARGET_RENESAS_EMAC/TARGET_RZ_A2XX/CMakelists.txt
  targets/CMakeLists.txt
  targets/TARGET_RENESAS/CMakeLists.txt
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/CMakeLists.txt
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/CMakeLists.txt
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/device/TOOLCHAIN_ARM_STD/MBRZA1LU.sct
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/CMakeLists.txt
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/device/TOOLCHAIN_ARM_STD/MBRZA1H.sct
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/CMakeLists.txt
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/TARGET_GR_MANGO/CMakeLists.txt
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/TARGET_GR_MANGO/device/TOOLCHAIN_ARM_STD/MBRZA1H.sct
  tools/cmake/README.md
Labels: ready for merge, release-type: patch

#14027 CMake: Fix Analog Devices targets support
  targets/CMakeLists.txt
  targets/TARGET_Analog_Devices/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14038 Fix `mbed device-management` command for Python 3.8
  requirements.txt
Labels: ready for merge, release-type: patch

#14055 CMake: Remove TODO note in device_key list input source file
  drivers/device_key/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14050 fix QSPI-API for NRF52
  targets/TARGET_NORDIC/TARGET_NRF5x/qspi_api.c
  targets/targets.json
Labels: ready for merge, release-type: patch

#13976 PSoC 6: rework sleep overrides by Cypress's debug macro
  targets/TARGET_Cypress/TARGET_PSOC6/cy_sleep_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/mbed_overrides.c
Labels: ready for merge, release-type: patch

#14042 CMake: Add support for all Ambiq Micro Mbed targets
  connectivity/drivers/ble/FEATURE_BLE/TARGET_Ambiq_Micro/TARGET_Apollo3/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/TARGET_Ambiq_Micro/hal/apollo3/hci_drv_apollo3.c
  targets/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TOOLCHAIN_ARM_STD/AMA3B1KK.sct
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TOOLCHAIN_GCC_ARM/startup_gcc.c
  tools/cmake/README.md
Labels: ready for merge, release-type: patch

#14035 Remove unsupported Renesas target include files
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/TARGET_MBED_MBRZA1LU/reserved_pins.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/TARGET_MBED_MBRZA1H/reserved_pins.h
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/TARGET_GR_MANGO/TARGET_MBED_MBRZA2M/reserved_pins.h
Labels: ready for merge, release-type: patch

#14064 examples:create build_data after example application build
  tools/test/examples/examples_lib.py
Labels: ready for merge, release-type: patch

#13809 Remove Cellular dependency in netsocket
  connectivity/cellular/README.md
  connectivity/cellular/mbed_lib.json
  connectivity/netsocket/include/netsocket/nsapi.h
  connectivity/netsocket/source/CellularNonIPSocket.cpp
  connectivity/netsocket/source/NetworkInterfaceDefaults.cpp
  connectivity/netsocket/tests/TESTS/netsocket/tcp/tcpsocket_recv_100k.cpp
  connectivity/netsocket/tests/TESTS/netsocket/tls/main.cpp
  connectivity/netsocket/tests/TESTS/netsocket/udp/udpsocket_echotest_burst.cpp
  connectivity/netsocket/tests/UNITTESTS/netsocket/CellularNonIPSocket/unittest.cmake
Labels: ready for merge, release-type: patch

#14029 STM32H7: FDCAN: use PLL1Q frequency for calculations
  targets/TARGET_STM/can_api.c
Labels: ready for merge, release-type: patch

#14041 Add SPDX identifier to files in storage
  storage/blockdevice/include/blockdevice/BufferedBlockDevice.h
  storage/blockdevice/include/blockdevice/ChainingBlockDevice.h
  storage/blockdevice/include/blockdevice/FlashSimBlockDevice.h
  storage/blockdevice/include/blockdevice/HeapBlockDevice.h
  storage/blockdevice/include/blockdevice/MBRBlockDevice.h
  storage/blockdevice/include/blockdevice/ObservingBlockDevice.h
  storage/blockdevice/include/blockdevice/ProfilingBlockDevice.h
  storage/blockdevice/include/blockdevice/ReadOnlyBlockDevice.h
  storage/blockdevice/include/blockdevice/SlicingBlockDevice.h
  storage/blockdevice/source/ObservingBlockDevice.cpp
  storage/blockdevice/source/ReadOnlyBlockDevice.cpp
  storage/blockdevice/tests/TESTS/blockdevice/general_block_device/main.cpp
  storage/filesystem/fat/include/fat/FATFileSystem.h
  storage/filesystem/fat/source/FATFileSystem.cpp
  storage/filesystem/littlefs/tests/TESTS/COMMON/atomic_usage.cpp
  storage/filesystem/littlefs/tests/TESTS/COMMON/atomic_usage.h
  storage/filesystem/littlefsv2/tests/TESTS/COMMON/atomic_usage.cpp
  storage/filesystem/littlefsv2/tests/TESTS/COMMON/atomic_usage.h
Labels: ready for merge, release-type: patch

#14065 CMake: streamline kvstore support
  storage/kvstore/CMakeLists.txt
  storage/kvstore/securestore/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14071 Add `internal` subfolder to USBDriver's CMakelists
  drivers/usb/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14036 Add SD component and Update SD card SPI interface for Maxim's MAX32630FTHR
  storage/blockdevice/COMPONENT_SD/mbed_lib.json
  targets/targets.json
Labels: ready for merge, release-type: patch

#14061 CMake: Create mbed-greentea library
  features/CMakeLists.txt
  features/frameworks/greentea-client/CMakeLists.txt
  features/frameworks/unity/CMakeLists.txt
  features/frameworks/utest/CMakeLists.txt
Labels: ready for merge, release-type: feature

#13897 Remove nanostack-border-router example from list of supported examples
  tools/test/examples/examples.json
Labels: Release review required, ready for merge

#14012 Standard pin name validation
  hal/tests/TESTS/pin_names/PinNames_test.h
  hal/tests/TESTS/pin_names/pinvalidate.py
  hal/tests/TESTS/pin_names/pinvalidate_test.py
Labels: needs: work, release-version: feature branch
