Repository ARMmbed/mbed-os, pull requests merged in 2020-03, with the labels that each got.

#12526 GCC: Fix the toolchain LTO workaround for Python 3
  tools/toolchains/gcc.py
Labels: ready for merge, release-version: 6.0.0-beta-1

#12521 Remove explicit include of mbedtls/config.h
  features/device_key/source/DeviceKey.cpp
  features/lorawan/lorastack/mac/LoRaMacCrypto.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12517 [feature-wisun] Disable sleep on STM32F4 as an workaround for stability issues.
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr.c
Labels: mergify skip, needs: review, release-version: feature branch

#12545 threads: fix timeout (set to 25)
  TESTS/mbedmicro-rtos-mbed/threads/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12533 Remove CriticalSectionLock deprecated APIs
  platform/CriticalSectionLock.h
  platform/source/CriticalSectionLock.cpp
Labels: BREAKING-CHANGE, release-version: 6.0.0-beta-1

#12548 tests-integration-net-single: fix build error
  TESTS/integration/COMMON/download_test.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12460 Allow MISO/MOSI set to NC during SPI initialisation (fix for issue #12435)
  TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/spi_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/spi_api.c
  targets/TARGET_STM/can_api.c
  targets/TARGET_STM/pinmap.c
  targets/TARGET_STM/serial_api.c
  targets/TARGET_STM/stm_spi_api.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12487 C++11-ify virtualisation in netsocket
  UNITTESTS/features/netsocket/CellularNonIPSocket/unittest.cmake
  UNITTESTS/features/netsocket/PPPInterface/test_PPPInterface.cpp
  features/netsocket/CellularInterface.h
  features/netsocket/CellularNonIPSocket.cpp
  features/netsocket/CellularNonIPSocket.h
  features/netsocket/ControlPlane_netif.h
  features/netsocket/DNS.h
  features/netsocket/DTLSSocket.h
  features/netsocket/DTLSSocketWrapper.cpp
  features/netsocket/DTLSSocketWrapper.h
  features/netsocket/EMACInterface.cpp
  features/netsocket/EMACInterface.h
  features/netsocket/EthInterface.h
  features/netsocket/ICMPSocket.cpp
  features/netsocket/ICMPSocket.h
  features/netsocket/InternetDatagramSocket.h
  features/netsocket/InternetSocket.cpp
  features/netsocket/InternetSocket.h
  features/netsocket/L3IPInterface.cpp
  features/netsocket/L3IPInterface.h
  features/netsocket/MeshInterface.h
  features/netsocket/NetStackMemoryManager.h
  features/netsocket/NetworkInterface.h
  features/netsocket/NetworkStack.cpp
  features/netsocket/NetworkStack.h
  features/netsocket/OnboardNetworkStack.h
  features/netsocket/PPP.h
  features/netsocket/PPPInterface.cpp
  features/netsocket/PPPInterface.h
  features/netsocket/Socket.h
  features/netsocket/TCPServer.cpp
  features/netsocket/TCPServer.h
  features/netsocket/TCPSocket.cpp
  features/netsocket/TCPSocket.h
  features/netsocket/TLSSocket.cpp
  features/netsocket/TLSSocket.h
  features/netsocket/TLSSocketWrapper.cpp
  features/netsocket/TLSSocketWrapper.h
  features/netsocket/UDPSocket.h
  features/netsocket/WiFiAccessPoint.cpp
  features/netsocket/WiFiAccessPoint.h
  features/netsocket/WiFiInterface.h
  features/netsocket/ppp/ppp_service.cpp
  features/netsocket/ppp/ppp_service.h
Labels: mergify skip, ready for merge, release-version: 6.0.0-beta-1

#12511 allow reconfiguring a running watchdog
  UNITTESTS/drivers/Watchdog/test_watchdog.cpp
  drivers/Watchdog.h
  drivers/source/Watchdog.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12467 Inline nsapi_create_stack(NetworkStack)
  UNITTESTS/stubs/NetworkStack_stub.cpp
  features/netsocket/NetworkStack.cpp
  features/netsocket/NetworkStack.h
Labels: release-version: 6.0.0-beta-1

#12476 Fix build failure when target's cmsis doesn't exist
  tools/config/__init__.py
Labels: release-version: 6.0.0-beta-1

#12557 M487: Fix crash on WDT reset from power-down
  targets/TARGET_NUVOTON/TARGET_M480/device/startup_M480.c
  targets/TARGET_NUVOTON/TARGET_M480/mbed_overrides.c
Labels: release-version: 6.0.0-beta-1

#12508 Fix minimal-printf stack overflow
  platform/source/minimal-printf/mbed_printf_implementation.c
Labels: release-version: 6.0.0-beta-1

#12553 Remove DirHandle deprecated APIs
  platform/DirHandle.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12534 Remove the deprecated CallChain class and its APIs
  features/FEATURE_BLE/ble/FunctionPointerWithContext.h
  platform/CallChain.h
  platform/source/CallChain.cpp
Labels: BREAKING-CHANGE, release-version: 6.0.0-beta-1

#12529 travis: scancode ret value not cat fix
  .travis.yml
Labels: release-version: 6.0.0-beta-1

#12464 STM32 EMAC : add configuration choice and connection check
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F2/stm32xx_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F4/stm32xx_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32F7/stm32xx_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/stm32xx_emac_config.h
  features/netsocket/emac-drivers/TARGET_STM/mbed_lib.json
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.h
  targets/TARGET_STM/TARGET_STM32F2/device/stm32f2xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32F7/device/stm32f7xx_hal_conf.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12559 DISCO_L4R9I correct LED pins
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/PinNames.h
Labels: release-version: 6.0.0-beta-1

#12506 Fix 2 string based IP address removal regressions
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/netsocket/L3IPInterface.cpp
  features/netsocket/L3IPInterface.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12489 C++11-ify virtualisation in lwIP classes
  features/lwipstack/LWIPMemoryManager.h
  features/lwipstack/LWIPStack.cpp
  features/lwipstack/LWIPStack.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12499 Cellular: For ublox modem, read '@' char first then send data.
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12543 TLSSocket: Remove deprecated connect
  features/netsocket/TLSSocket.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12549 Remove FileHandle deprecated APIs
  platform/FileHandle.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12550 Remove mbed interface deprecated API
  platform/mbed_interface.h
  platform/source/mbed_board.c
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12551 Remove mbed power management deprecated API
  features/FEATURE_BLE/targets/TARGET_Maxim/MaximBLE.cpp
  platform/mbed_power_mgmt.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12554 Remove FileSystemLike deprecated APIs
  platform/FileSystemLike.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12537 Minor optimization to improve readability of code
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode/iphc_decompress.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode/lowpan_context.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode/lowpan_context.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread/thread_router_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/BorderRouter/border_router.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12536 Fixed typo 'thead' in thread_neighbor_class.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread/thread_neighbor_class.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12436 Remove GPIO pin-maps used for FPGA testing
  TESTS/mbed_hal/pinmap/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/uart/main.cpp
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/test_utils.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW24D/TARGET_FRDM/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/TARGET_FRDM/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralPinMaps.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/i2c_api.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12558 Fix issue when TDBStore has varying erase sizes between areas.
  features/storage/kvstore/tdbstore/TDBStore.cpp
  features/storage/kvstore/tdbstore/TDBStore.h
Labels: release-version: 5.15.2

#12531 Add check so that FlashIAP does not allocate memory on flash_init failure
  drivers/source/FlashIAP.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12524 Bugfix: Concurrent SFDP header address init fixed
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.h
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.h
  drivers/internal/SFDP.h
  drivers/source/SFDP.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12560 crypto: Update to Mbed Crypto 3.0.1
  features/mbedtls/mbed-crypto/VERSION.txt
  features/mbedtls/mbed-crypto/importer/Makefile
  features/mbedtls/mbed-crypto/inc/mbedtls/bignum.h
  features/mbedtls/mbed-crypto/inc/mbedtls/ctr_drbg.h
  features/mbedtls/mbed-crypto/src/aes.c
  features/mbedtls/mbed-crypto/src/bignum.c
  features/mbedtls/mbed-crypto/src/ctr_drbg.c
  features/mbedtls/mbed-crypto/src/ecdsa.c
  features/mbedtls/mbed-crypto/src/ecp.c
  features/mbedtls/mbed-crypto/src/gcm.c
Labels: ready for merge

#12507 Cellular: release _semaphore only once
  features/cellular/framework/AT/AT_CellularContext.cpp
Labels: release-version: 6.0.0-beta-1

#12583 STM32F7: baremetal profile support
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_DISCO_F746NG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/device/TOOLCHAIN_ARM_STD/stm32f746xg.sct
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/TARGET_NUCLEO_F756ZG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/device/TOOLCHAIN_ARM_STD/stm32f756xg.sct
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/device/TOOLCHAIN_ARM_STD/stm32f767xi.sct
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/TARGET_DISCO_F769NI/system_clock.c
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/device/TOOLCHAIN_ARM_STD/stm32f769xi.sct
Labels: release-version: 6.0.0-beta-1

#12540 fix for suppress 'unknown object name' messages from memap.py
  tools/memap.py
Labels: release-version: 6.0.0-beta-1

#12590 Importer script: remove apache-2.0.txt
  features/mbedtls/README.md
  features/mbedtls/importer/Makefile
  features/mbedtls/mbed-crypto/importer/Makefile
Labels: ready for merge, release-version: 6.0.0-beta-1

#12596 Remove Mutex deprecated API
  UNITTESTS/stubs/Mutex_stub.cpp
  UNITTESTS/target_h/rtos/Mutex.h
  rtos/Mutex.h
  rtos/source/Mutex.cpp
Labels: BREAKING-CHANGE, release-version: 6.0.0-beta-1

#12567 STM32 EMAC : increase thread size when mbed-trace is enabled
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12595 Fixed typo 'timout'
  TESTS/mbed_hal/watchdog_timing/watchdog_timing_tests.h
Labels: release-version: 6.0.0-beta-1

#12599 Greentea kvstorage tests Cypress targets fix.
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_2/main.cpp
Labels: ready for merge

#12233 Enable minimal-printf by default for all builds
  TESTS/mbed_drivers/c_strings/main.cpp
  TESTS/mbed_drivers/reset_reason/main.cpp
  TESTS/mbed_drivers/watchdog_reset/main.cpp
  TESTS/mbed_hal/reset_reason/main.cpp
  TESTS/mbed_hal/watchdog_reset/main.cpp
  TESTS/mbed_hal/watchdog_timing/main.cpp
  TESTS/mbed_timing_fpga_ci_test_shield/watchdog/main.cpp
  platform/mbed_lib.json
  platform/source/minimal-printf/README.md
  platform/source/minimal-printf/mbed_printf_implementation.c
  targets/targets.json
Labels: BREAKING-CHANGE, needs: review, release-version: 6.0.0-beta-1

#12580 Reverting #12312 as it breaking current WiFI connect()->Disconnect() sequence
  features/lwipstack/LWIPInterface.cpp
  features/lwipstack/LWIPStack.h
  features/netsocket/OnboardNetworkStack.h
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.cpp
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSoftAPInterface.cpp
Labels: devices: cypress, ready for merge, release-version: 6.0.0-beta-1

#12598 Change Mutex lock and unlock APIs return value to void
  rtos/Mutex.h
  rtos/source/Mutex.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_MODULE_UBLOX_ODIN_W2/sdk/ublox-odin-w2-drivers/OdinWiFiInterface.cpp
Labels: ready for merge

#12601 Remove RtosTimer deprecated class
  TESTS/mbedmicro-rtos-mbed/rtostimer/main.cpp
  rtos/LICENSE.md
  rtos/RtosTimer.h
  rtos/rtos.h
  rtos/source/RtosTimer.cpp
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12319 Fix userallocatedevent imp
  TESTS/events/equeue/main.cpp
  TESTS/events/queue/main.cpp
  UNITTESTS/events/equeue/test_equeue.cpp
  events/UserAllocatedEvent.h
  events/source/equeue.c
Labels: mergify skip, needs: CI, release-version: 6.0.0-alpha-3

#12571 C++11-ify NonCopyable
  platform/NonCopyable.h
Labels: ready for merge, release-version: 6.0.0-alpha-3

#12611 STM32F4 UART issue when parity enabled
  targets/TARGET_STM/TARGET_STM32F4/serial_device.c
Labels: ready for merge, release-version: 6.0.0-alpha-3

#12597 Cellular: Add ALT1250 PPP cellular target
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP.cpp
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP.h
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP_CellularContext.cpp
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP_CellularContext.h
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP_CellularNetwork.cpp
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP_CellularNetwork.h
  features/cellular/framework/targets/Altair/ALT1250/PPP/mbed_lib.json
Labels: ready for merge, release-version: 6.0.0-alpha-3, scope: new-target

#12617 Correct doxygen for Mail::get
  rtos/Mail.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12624 Cellular: Support EC2x power control pin support no connect
  features/cellular/framework/targets/QUECTEL/EC2X/QUECTEL_EC2X.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12607 Use toolchain's struct stat if available
  platform/mbed_retarget.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12631 Update psutils to address security issue
  requirements.txt
Labels: ready for merge, release-version: 6.0.0-beta-1

#12633 Cellular: Add offload TLSSocket implementation inside feature flag
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12636 Extend unit tests for TDBStore
  UNITTESTS/moduletests/storage/kvstore/TDBStore/moduletest.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12576 M487: Support custom board
  targets/TARGET_NUVOTON/TARGET_M480/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_M480/PinNamesCommon.h
  targets/TARGET_NUVOTON/TARGET_M480/TARGET_NUMAKER_IOT_M487/PinNames.h
  targets/TARGET_NUVOTON/TARGET_M480/TARGET_NUMAKER_PFM_M487/PinNames.h
  targets/TARGET_NUVOTON/TARGET_M480/device/M480_mem.h
  targets/TARGET_NUVOTON/TARGET_M480/device/M480_mem.icf.h
  targets/TARGET_NUVOTON/TARGET_M480/device/TOOLCHAIN_ARM_MICRO/M487.sct
  targets/TARGET_NUVOTON/TARGET_M480/device/TOOLCHAIN_ARM_STD/M487.sct
  targets/TARGET_NUVOTON/TARGET_M480/device/TOOLCHAIN_GCC_ARM/M487.ld
  targets/TARGET_NUVOTON/TARGET_M480/device/TOOLCHAIN_IAR/M487.icf
  targets/TARGET_NUVOTON/TARGET_M480/device/system_M480.c
  targets/TARGET_NUVOTON/TARGET_M480/flash_api.c
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-beta-1, scope: new-target

#12652 Add moduletests for FileSystemStore
  UNITTESTS/moduletests/storage/kvstore/FileSystemStore/moduletest.cpp
  UNITTESTS/moduletests/storage/kvstore/FileSystemStore/unittest.cmake
  UNITTESTS/stubs/kv_config_stub.cpp
  UNITTESTS/stubs/mbed_retarget_stub.cpp
  UNITTESTS/target_h/platform/mbed_retarget.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12645 Storage: Use internal flash for KVStore always if default config
  docs/design-documents/features/storage/Configuration/CONFIGURATION.md
  features/storage/TESTS/kvstore/direct_access_devicekey_test/main.cpp
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/kvstore/direct_access_devicekey/DirectAccessDevicekey.cpp
Labels: release-version: 6.0.0-beta-1

#12410 Remove the deprecated RawSerial, UARTSerial, Serial
  TESTS/mbed_drivers/dev_null/main.cpp
  drivers/RawSerial.h
  drivers/Serial.h
  drivers/SerialBase.h
  drivers/UARTSerial.h
  drivers/source/RawSerial.cpp
  drivers/source/Serial.cpp
  drivers/source/UARTSerial.cpp
  features/FEATURE_BLE/targets/TARGET_Maxim/MaximBLE.cpp
  mbed.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12648 Nanostack: Add config for Wi-SUN device type
  features/nanostack/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12649 Expose SerialBase IrqType member to UnbufferedSerial class
  drivers/UnbufferedSerial.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12654 Removed all references to __CC_ARM
  features/FEATURE_BLE/ble/Gap.h
  features/FEATURE_BLE/ble/pal/Deprecated.h
  features/FEATURE_BLE/source/LegacyGap.tpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/include/util/print.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/wsf/include/wsf_types.h
  features/FEATURE_BLE/targets/TARGET_CORDIO_LL/stack/thirdparty/uecc/uECC_ll.c
  features/FEATURE_BLE/targets/TARGET_CORDIO_LL/stack/thirdparty/uecc/uECC_ll.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_MCU_NRF51822/sdk/source/ble/common/ble_conn_state.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_MCU_NRF51822/sdk/source/ble/device_manager/device_manager_peripheral.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_MCU_NRF51822/sdk/source/device/compiler_abstraction.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_MCU_NRF51822/sdk/source/device/nrf51.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_MCU_NRF51822/sdk/source/drivers_nrf/delay/nrf_delay.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_MCU_NRF51822/sdk/source/libraries/bootloader_dfu/bootloader_util.c
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_MCU_NRF51822/sdk/source/libraries/experimental_section_vars/section_vars.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_MCU_NRF51822/sdk/source/softdevice/s130/headers/nrf_svc.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_MCU_NRF51822/source/common/binary.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF51/source/common/binary.h
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_SOFTDEVICE/TARGET_NRF52/source/common/binary.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12655 Remove ARMC5 reference from Mbed OS platform
  platform/SingletonPtr.h
  platform/cxxsupport/TOOLCHAIN_ARMC5/_move.h
  platform/cxxsupport/TOOLCHAIN_ARMC5/array
  platform/cxxsupport/TOOLCHAIN_ARMC5/atomic
  platform/cxxsupport/TOOLCHAIN_ARMC5/cinttypes
  platform/cxxsupport/TOOLCHAIN_ARMC5/initializer_list
  platform/cxxsupport/TOOLCHAIN_ARMC5/mutex
  platform/cxxsupport/TOOLCHAIN_ARMC5/tuple
  platform/cxxsupport/TOOLCHAIN_ARMC5/type_traits
  platform/cxxsupport/mstd_algorithm
  platform/cxxsupport/mstd_atomic
  platform/cxxsupport/mstd_cstddef
  platform/cxxsupport/mstd_functional
  platform/cxxsupport/mstd_iterator
  platform/cxxsupport/mstd_memory
  platform/cxxsupport/mstd_mutex
  platform/cxxsupport/mstd_type_traits
  platform/cxxsupport/mstd_utility
  platform/internal/mbed_atomic_impl.h
  platform/mbed_assert.h
  platform/mbed_rtc_time.h
  platform/mbed_semihost_api.h
  platform/mbed_toolchain.h
  platform/source/mbed_application.c
  platform/source/mbed_crash_data_offsets.h
  platform/source/mbed_retarget.cpp
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12659 Rebuild WICED libraries after Mbed update
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
Labels: ready for merge, release-version: 6.0.0-beta-1

#12528 SFDP: consolidation of SFDP parsing [5/5]
  drivers/internal/SFDP.h
  drivers/source/SFDP.cpp
Labels: mergify skip, ready for merge, release-version: 6.0.0-beta-1

#12646 Makefile: fix for overlong command line
  tools/export/makefile/Makefile.tmpl
Labels: mergify skip, ready for merge, release-version: 6.0.0-beta-1

#12661 Adjusted SecurityManager Doxygen ASCII art
  features/FEATURE_BLE/ble/SecurityManager.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12656 [feature-wisun] Nanostack: Add config for Wi-SUN device type
  features/nanostack/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: needs: work, release-version: feature branch

#12658 tests-integration;tests-filesystem: fix code causing compiler warnings and enable more tests
  TESTS/integration/COMMON/download_test.cpp
  TESTS/integration/COMMON/target_extended.json
  TESTS/integration/fs-threaded/main.cpp
  TESTS/integration/net-single/main.cpp
  TESTS/integration/net-threaded/main.cpp
  TESTS/integration/stress-net-fs/main.cpp
  features/storage/TESTS/filesystem/general_filesystem/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12637 Cordio: fix for issue #12625
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack_adaptation/hci_tr.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12666 Makefile: render compatible with some GNU make versions (revert #12646)
  tools/export/makefile/Makefile.tmpl
Labels: ready for merge, release-version: 6.0.0-beta-1

#12667 Add check for return code in DeviceKey to avoid injecting invalid ROT
  features/device_key/source/DeviceKey.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12673 Mergify update
  .mergify.yml
Labels: ready for merge, release-version: 6.0.0-beta-1

#12642 M263: Support custom board
  targets/TARGET_NUVOTON/TARGET_M261/PeripheralNames.h
  targets/TARGET_NUVOTON/TARGET_M261/PinNamesCommon.h
  targets/TARGET_NUVOTON/TARGET_M261/TARGET_NUMAKER_IOT_M263A/PinNames.h
  targets/TARGET_NUVOTON/TARGET_M261/device/M261_mem.h
  targets/TARGET_NUVOTON/TARGET_M261/device/M261_mem.icf.h
  targets/TARGET_NUVOTON/TARGET_M261/device/TOOLCHAIN_ARMC6/M261.sct
  targets/TARGET_NUVOTON/TARGET_M261/device/TOOLCHAIN_GCC_ARM/M261.ld
  targets/TARGET_NUVOTON/TARGET_M261/device/TOOLCHAIN_IAR/M261.icf
  targets/TARGET_NUVOTON/TARGET_M261/flash_api.c
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12651 Cellular: Make Quectel EC2x modem start up timeout configurable
  features/cellular/framework/targets/QUECTEL/EC2X/QUECTEL_EC2X.cpp
  features/cellular/framework/targets/QUECTEL/EC2X/mbed_lib.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12686 STM32 EMAC : remove TIMEOUT issue when cable is not plugged yet
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12685 Remove deprecated netsocket methods
  features/netsocket/InternetSocket.cpp
  features/netsocket/InternetSocket.h
  features/netsocket/TCPSocket.h
  features/netsocket/UDPSocket.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12632 Fix snprintf in minimal-printf library
  TESTS/mbed_platform/minimal-printf/compliance/main.cpp
  platform/source/minimal-printf/mbed_printf_implementation.c
Labels: ready for merge

#12672 Remove deprecated ARMC5 reference from `mbed compile -S` output
  tools/build_api.py
Labels: ready for merge, release-version: 6.0.0-beta-1

#12692 EFM32G11: Add RGB LEDs to PinNames.h
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG11/TARGET_EFM32GG11_STK3701/PinNames.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12640 Remove minimal-printf extension profile
  TESTS/mbed_platform/minimal-printf/compliance/README.md
  tools/profiles/extensions/minimal-printf.json
Labels: BREAKING-CHANGE, release-version: 6.0.0-beta-1

#12629 Add "rtos-api" to bare metal
  .travis.yml
  TESTS/configs/baremetal.json
  platform/bare_metal/mbed_lib.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12300 Add get_time function to ESP8266
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
  components/wifi/esp8266-driver/mbed_lib.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12677 STM32H7: enable QSPI
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12683 SocketAddress rework
  UNITTESTS/stubs/SocketAddress_stub.cpp
  features/netsocket/SocketAddress.cpp
  features/netsocket/SocketAddress.h
  tools/test/travis-ci/doxy-spellchecker/ignore.en.pws
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12693 USBMSD security updates
  drivers/source/usb/USBMSD.cpp
Labels: ready for merge

#12704 LWIP: propagate the apimsg->err out of netconn_apimsg()
  features/lwipstack/lwip/src/api/lwip_api_lib.c
Labels: ready for merge

#12706 Tests: Remove support for ARM Compiler 5
  TESTS/mbed_hal/flash/functional_tests/main.cpp
  TESTS/mbed_hal/spm/main.cpp
  UNITTESTS/target_h/platform/mbed_assert.h
  features/frameworks/unity/unity/unity_internals.h
  features/frameworks/utest/utest/utest_shim.h
Labels: ready for merge

#12036 Callback extension and optimisation
  TESTS/mbed_functional/callback/main.cpp
  TESTS/mbed_platform/Transaction/main.cpp
  TESTS/network/emac/emac_util.h
  UNITTESTS/features/netsocket/NetworkInterface/unittest.cmake
  UNITTESTS/target_h/platform/cxxsupport/mstd_new
  UNITTESTS/target_h/platform/cxxsupport/mstd_type_traits
  features/netsocket/NetworkInterface.cpp
  features/netsocket/NetworkInterface.h
  platform/Callback.h
  platform/mbed_lib.json
  platform/mbed_retarget.h
  platform/mbed_toolchain.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#11726 Disable C++ static destructors in ARMC6 compiler
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: ready for merge

#11629 Refactor TDB internal bounds computation
  UNITTESTS/CMakeLists.txt
  features/storage/TESTS/kvstore/direct_access_devicekey_test/main.cpp
  features/storage/kvstore/conf/filesystem/mbed_lib.json
  features/storage/kvstore/conf/kv_config.cpp
  features/storage/kvstore/conf/kv_config.h
  features/storage/kvstore/conf/tdb_external/mbed_lib.json
  features/storage/kvstore/conf/tdb_internal/mbed_lib.json
  features/storage/kvstore/direct_access_devicekey/DirectAccessDevicekey.cpp
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: devices: cypress, ready for merge, release-version: 6.0.0-beta-1

#12569 Replace with weak mbed_error_hook implementation (deprecate the hook function)
  platform/mbed_error.h
  platform/source/mbed_error.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12670 ESP8266: Fix typo: gateway to netmask
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12662 Add workaround for STM32F4 hardfault in sleep mode
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12472 Add WPA3 support in mbed-os for green tea tests
  TESTS/network/wifi/README.md
  TESTS/network/wifi/get_security.cpp
  TESTS/network/wifi/wifi_set_credential.cpp
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.cpp
  features/netsocket/nsapi_types.h
Labels: devices: cypress, ready for merge, release-version: 6.0.0-beta-1

#12705 mbed-client-cli: Remove support for ARM Compiler 5
  features/frameworks/mbed-client-cli/mbed-client-cli/ns_cmdline.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12690 STM32: solve GCC Unspecified RTOS error
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G030xx/TOOLCHAIN_GCC_ARM/stm32g030xx.ld
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G031xx/TOOLCHAIN_GCC_ARM/stm32g031xx.ld
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G041xx/TOOLCHAIN_GCC_ARM/stm32g041xx.ld
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G070xx/TOOLCHAIN_GCC_ARM/stm32g070xx.ld
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G071xx/TOOLCHAIN_GCC_ARM/stm32g071xx.ld
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G081xx/TOOLCHAIN_GCC_ARM/stm32g081xx.ld
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L552xx/TOOLCHAIN_GCC_ARM/stm32l552xx.ld
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L562xx/TOOLCHAIN_GCC_ARM/stm32l562xx.ld
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB50xx/TOOLCHAIN_GCC_ARM/stm32wb50xx.ld
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xx/TOOLCHAIN_GCC_ARM/stm32wb55xx.ld
Labels: ready for merge, release-version: 6.0.0-beta-1

#12682 MBED TRACE default level is INFO
  features/frameworks/mbed-trace/README.md
  features/frameworks/mbed-trace/mbed-trace/mbed_trace.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12630 mbed test with dual core targets
  tools/test_api.py
Labels: ready for merge, release-version: 6.0.0-beta-1

#12609 Remove Semaphore deprecated APIs
  TESTS/mbed_drivers/timeout/timeout_tests.h
  UNITTESTS/stubs/Semaphore_stub.cpp
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/HCIDriver.cpp
  rtos/Semaphore.h
  rtos/source/Semaphore.cpp
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12708 Remove compatibility for Arm Compiler versions prior to 6.01.0050
  platform/source/mbed_crash_data_offsets.h
  platform/source/mbed_retarget.cpp
  rtos/source/TARGET_CORTEX/TOOLCHAIN_ARM_STD/mbed_boot_arm_std.c
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12612 TEST: add RTOS macro to enable integration test
  TESTS/integration/COMMON/download_test.cpp
  TESTS/integration/COMMON/file_test.cpp
  TESTS/integration/fs-single/main.cpp
  TESTS/integration/fs-threaded/main.cpp
  TESTS/integration/net-single/main.cpp
  TESTS/integration/net-threaded/main.cpp
  TESTS/integration/stress-net-fs/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12570 Improve nsapi_create_stack
  UNITTESTS/features/netsocket/DTLSSocket/test_DTLSSocket.cpp
  UNITTESTS/features/netsocket/DTLSSocketWrapper/test_DTLSSocketWrapper.cpp
  UNITTESTS/features/netsocket/InternetSocket/test_InternetSocket.cpp
  UNITTESTS/features/netsocket/TCPServer/test_TCPServer.cpp
  UNITTESTS/features/netsocket/TCPSocket/test_TCPSocket.cpp
  UNITTESTS/features/netsocket/TLSSocket/test_TLSSocket.cpp
  UNITTESTS/features/netsocket/TLSSocketWrapper/test_TLSSocketWrapper.cpp
  UNITTESTS/features/netsocket/UDPSocket/test_UDPSocket.cpp
  UNITTESTS/stubs/NetworkStack_stub.cpp
  features/netsocket/NetworkInterface.h
  features/netsocket/NetworkStack.h
Labels: mergify skip, ready for merge, release-version: 6.0.0-beta-1
