Repository ARMmbed/mbed-os, pull requests merged in 2020-04, with the labels that each got.

#12604 NANO130: Fix test failures with tickless from lp_ticker
  TESTS/events/queue/main.cpp
  TESTS/mbed_hal/stack_size_unification/main.cpp
  targets/TARGET_NUVOTON/TARGET_NANO100/device/StdDriver/nano100_clk.c
Labels: ready for merge

#12610 Add UBLOX_onboard_modem_api for power up UBLOX_C027.
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_UBLOX_C027/ONBOARD_UBLOX_PPP.cpp
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_UBLOX_C027/ONBOARD_UBLOX_PPP.h
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_UBLOX_C027/UBLOX_onboard_modem_api.c
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_UBLOX_C027/UBLOX_onboard_modem_api.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12681 SPIFBlockDevice doesn't play nice on shared SPI bus #11732.
  components/storage/blockdevice/COMPONENT_DATAFLASH/DataFlashBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_DATAFLASH/DataFlashBlockDevice.h
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SD/SDBlockDevice.h
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12715 RZ_A1H remove usage of ethernet hal API
  features/netsocket/emac-drivers/TARGET_RZ_A1_EMAC/rza1_emac.cpp
  features/netsocket/emac-drivers/TARGET_RZ_A1_EMAC/rza1_eth.c
  features/netsocket/emac-drivers/TARGET_RZ_A1_EMAC/rza1_eth.h
  features/netsocket/emac-drivers/TARGET_RZ_A1_EMAC/rza1_eth_ext.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12719 FPGA CI TEST SHIELD: add test config json file
  TESTS/configs/fpga.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12726 feature-wisun: Add fix for STM32F4 hardfault in sleep mode
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr.c
Labels: release-version: feature branch

#12696 rtos: declare vector table type as in Technical Note 11578
  rtos/source/TARGET_CORTEX/TOOLCHAIN_IAR/mbed_boot_iar.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12712 Fix LTO issue with minimal-printf
  tools/profiles/extensions/lto.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12733 odin targets: remove release version
  targets/targets.json
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12653 Fix issue when TDBStore has varying erase sizes between areas. (Backport)
  features/storage/kvstore/tdbstore/TDBStore.cpp
  features/storage/kvstore/tdbstore/TDBStore.h
Labels: ready for merge, release-version: 5.15.2

#12680 QSPI driver also acquires ownership upon initialization now.
  drivers/source/QSPI.cpp
Labels: devices: cypress, ready for merge

#12743 mergify: Add 5.15 rule
  .mergify.yml
Labels: ready for merge, release-version: 6.0.0-beta-1

#12603 Add target CYSBSYSKIT_01
  TESTS/mbed_hal/qspi/flash_configs/flash_configs.h
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_SCL/interface/SclSTAInterface.cpp
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_SCL/interface/SclSTAInterface.h
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_SCL/interface/default_wifi_interface.cpp
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_SCL/interface/scl_emac.cpp
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_SCL/interface/scl_emac.h
  features/netsocket/ppp/mbed_lib.json
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/generated_mac_address.txt
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/inc/scl_common.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/inc/scl_ipc.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/inc/scl_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/inc/scl_wifi_api.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/src/IPC/scl_ipc.c
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/src/include/scl_buffer_api.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/src/scl_buffer_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/src/scl_wifi_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.timestamp
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_notices.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/qspi_config.cfg
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/design.cycapsense
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/design.cyqspi
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/design.modus
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/cybsp.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/cybsp.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/cybsp_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/TOOLCHAIN_ARM/cy8c6xxa_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/TOOLCHAIN_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/cy8c6xxa_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/TOOLCHAIN_IAR/cy8c6xxa_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/TOOLCHAIN_IAR/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/system_psoc6.h
  targets/targets.json
Labels: Backport Candidate, devices: cypress, mergify skip, ready for merge, release-version: 6.0.0-beta-1, scope: new-target

#12676 Remove deprecated BLE:: APIs and unsupported services
  features/FEATURE_BLE/ble/BLE.h
  features/FEATURE_BLE/ble/services/DFUService.h
  features/FEATURE_BLE/ble/services/DeviceInformationService.h
  features/FEATURE_BLE/ble/services/EddystoneConfigService.h
  features/FEATURE_BLE/ble/services/EddystoneService.h
  features/FEATURE_BLE/ble/services/UARTService.h
  features/FEATURE_BLE/ble/services/URIBeaconConfigService.h
  features/FEATURE_BLE/ble/services/iBeacon.h
  features/FEATURE_BLE/source/BLE.cpp
  features/FEATURE_BLE/source/services/DFUService.cpp
  features/FEATURE_BLE/source/services/UARTService.cpp
  features/FEATURE_BLE/source/services/URIBeaconConfigService.cpp
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12729 Mbedtls fixes
  TESTS/mbedtls/multi/main.cpp
  features/device_key/TESTS/device_key/functionality/main.cpp
  features/lwipstack/lwip/src/apps/altcp_tls/altcp_tls_mbedtls.c
  features/mbedtls/platform/inc/shared_rng.h
  features/mbedtls/platform/src/shared_rng.cpp
  features/nanostack/coap-service/source/coap_security_handler.c
  features/nanostack/coap-service/test/coap-service/unittest/stub/mbedtls_stub.c
  features/nanostack/coap-service/test/coap-service/unittest/stub/mbedtls_stub.h
  features/nanostack/sal-stack-nanostack/nanostack/ns_sha256.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot/tls_sec_prot_lib.c
  features/netsocket/DTLSSocketWrapper.cpp
  features/netsocket/TLSSocketWrapper.cpp
  features/netsocket/TLSSocketWrapper.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12638 Enable storage tests to all targets
  components/storage/blockdevice/COMPONENT_QSPIF/mbed_lib.json
  features/storage/TESTS/kvstore/filesystemstore_tests/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_2/main.cpp
  features/storage/TESTS/kvstore/securestore_whitebox/main.cpp
  features/storage/TESTS/kvstore/tdbstore_whitebox/main.cpp
  features/storage/system_storage/SystemStorage.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12698 Drivers: Remove support for ARM Compiler 5
  drivers/MbedCRC.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12701 Add custom BT Firmware image for CYW9P62S1_43012EVB_01
  features/FEATURE_BLE/targets/TARGET_Cypress/COMPONENT_CYW43XXX/firmware/COMPONENT_43012/w_bt_firmware_controller.c
  features/FEATURE_BLE/targets/TARGET_Cypress/COMPONENT_CYW43XXX/firmware/TARGET_CYW9P62S1_43012EVB_01/w_bt_firmware_controller.c
Labels: Backport Candidate, devices: cypress, ready for merge, release-version: 6.0.0-beta-1

#12728 STM32 EMAC : increase thread-stacksize
  features/netsocket/emac-drivers/TARGET_STM/mbed_lib.json
Labels: mergify skip, ready for merge, release-version: 6.0.0-beta-1

#12744 Change files in TARGET_SDT64B
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/PeripheralPinMaps.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/PinNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_SDT64B/mbed_overrides.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12650 Cellular: ALT1250 PPP cellular driver for mbed-os 5.15
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP.cpp
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP.h
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP_CellularContext.cpp
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP_CellularContext.h
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP_CellularNetwork.cpp
  features/cellular/framework/targets/Altair/ALT1250/PPP/ALT1250_PPP_CellularNetwork.h
  features/cellular/framework/targets/Altair/ALT1250/PPP/mbed_lib.json
Labels: mergify skip, ready for merge, release-version: 5.15.2

#12723 Mbedtls fixes for 5.15.2
  TESTS/mbedtls/multi/main.cpp
  features/device_key/TESTS/device_key/functionality/main.cpp
  features/lwipstack/lwip/src/apps/altcp_tls/altcp_tls_mbedtls.c
  features/mbedtls/platform/inc/shared_rng.h
  features/mbedtls/platform/src/shared_rng.cpp
  features/nanostack/coap-service/source/coap_security_handler.c
  features/nanostack/coap-service/test/coap-service/unittest/stub/mbedtls_stub.c
  features/nanostack/coap-service/test/coap-service/unittest/stub/mbedtls_stub.h
  features/nanostack/sal-stack-nanostack/nanostack/ns_sha256.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot/tls_sec_prot_lib.c
  features/netsocket/DTLSSocketWrapper.cpp
  features/netsocket/TLSSocketWrapper.cpp
  features/netsocket/TLSSocketWrapper.h
Labels: mergify skip, ready for merge, release-version: 5.15.2

#12717 Add fix for STM32F4 hardfault in sleep mode
  targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr.c
Labels: mergify skip, ready for merge, release-version: 5.15.2

#12771 Cypress: Partial backport of #12769
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.cpp
Labels: mergify skip, ready for merge, release-version: 5.15.2

#12776 Update stm32 emac ethernet driver
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
Labels: ready for merge, release-version: 5.15.2

#12668 tests-integration-fs-threaded: makes tests independent from each other
  TESTS/integration/fs-threaded/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12589 Cellular: Add deativation of context associated with profile
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12581 Fully enforce NonCopyable
  UNITTESTS/features/netsocket/TCPServer/test_TCPServer.cpp
  platform/NonCopyable.h
  platform/mbed_lib.json
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12387 Add Objects Extensions Configuration Parameter to HAL
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_AGORA/device.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_NRF52840_DK/device.h
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12572 Remove mbed wait deprecated APIs
  TESTS/lorawan/loraradio/main.cpp
  TESTS/mbed_drivers/reset_reason/main.cpp
  TESTS/mbed_drivers/rtc/main.cpp
  TESTS/mbed_drivers/watchdog/main.cpp
  TESTS/mbed_hal/reset_reason/main.cpp
  TESTS/mbed_hal/rtc/main.cpp
  TESTS/mbed_hal/rtc_time/main.cpp
  TESTS/mbed_hal/watchdog/main.cpp
  TESTS/mbed_hal_fpga_ci_test_shield/pwm/main.cpp
  TESTS/mbedmicro-rtos-mbed/condition_variable/main.cpp
  TESTS/mbedmicro-rtos-mbed/mutex/main.cpp
  TESTS/mbedmicro-rtos-mbed/systimer/main.cpp
  TESTS/usb_device/basic/main.cpp
  TESTS/usb_device/msd/main.cpp
  TESTS/usb_device/serial/main.cpp
  UNITTESTS/stubs/mbed_wait_api_stub.cpp
  UNITTESTS/target_h/platform/mbed_wait_api.h
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/MbedTester.h
  drivers/CAN.h
  drivers/DigitalIn.h
  drivers/DigitalOut.h
  drivers/I2C.h
  drivers/InterruptIn.h
  drivers/PortOut.h
  drivers/PwmOut.h
  drivers/Ticker.h
  drivers/Timeout.h
  drivers/USBKeyboard.h
  drivers/USBMIDI.h
  drivers/USBMouse.h
  drivers/USBMouseKeyboard.h
  drivers/USBSerial.h
  features/FEATURE_BLE/targets/TARGET_CORDIO_ODIN_W2/HCIDriver.cpp
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_CYW4343X/HCIDriver.cpp
  features/netsocket/emac-drivers/TARGET_ARM_SSG/COMPONENT_SMSC9220/smsc9220_emac.cpp
  platform/mbed_rtc_time.h
  platform/mbed_wait_api.h
  platform/source/mbed_wait_api_no_rtos.c
  platform/source/mbed_wait_api_rtos.cpp
  rtos/ConditionVariable.h
  rtos/Thread.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/smsc9220_eth_drv.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/smsc9220_eth_drv.h
  targets/TARGET_ARM_SSG/TARGET_MPS2/SDK/ETH_MPS2.c
  targets/TARGET_NXP/USBHAL_LPC17.cpp
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/trng_api_esp32.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_MTS_DRAGONFLY_F413RH/ONBOARD_TELIT_HE910.cpp
Labels: BREAKING-CHANGE, mergify skip, ready for merge, release-version: 6.0.0-beta-1

#12780 Cypress: Remove CYSBSYSKIT_01 from 5.15
  TESTS/mbed_hal/qspi/flash_configs/flash_configs.h
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_SCL/interface/SclSTAInterface.cpp
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_SCL/interface/SclSTAInterface.h
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_SCL/interface/default_wifi_interface.cpp
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_SCL/interface/scl_emac.cpp
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_SCL/interface/scl_emac.h
  features/netsocket/ppp/mbed_lib.json
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/generated_mac_address.txt
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/inc/scl_common.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/inc/scl_ipc.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/inc/scl_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/inc/scl_wifi_api.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/src/IPC/scl_ipc.c
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/src/include/scl_buffer_api.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/src/scl_buffer_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/src/scl_wifi_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.timestamp
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_notices.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/qspi_config.cfg
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/design.cycapsense
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/design.cyqspi
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/COMPONENT_BSP_DESIGN_MODUS/design.modus
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/cybsp.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/cybsp.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/cybsp_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/TOOLCHAIN_ARM/cy8c6xxa_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/TOOLCHAIN_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/cy8c6xxa_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/TOOLCHAIN_IAR/cy8c6xxa_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/TOOLCHAIN_IAR/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/COMPONENT_CM4/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/device/system_psoc6.h
  targets/targets.json
Labels: ready for merge, release-version: 5.15.2

#12762 Various LoRaWAN 1.1 fixes
  UNITTESTS/features/lorawan/loramaccrypto/Test_LoRaMacCrypto.cpp
  UNITTESTS/stubs/LoRaMacCrypto_stub.cpp
  features/lorawan/LoRaWANStack.cpp
  features/lorawan/lorastack/mac/LoRaMac.cpp
  features/lorawan/lorastack/mac/LoRaMacCommand.cpp
  features/lorawan/lorastack/mac/LoRaMacCrypto.cpp
  features/lorawan/lorastack/mac/LoRaMacCrypto.h
Labels: needs: CI, release-version: feature branch

#12739 FIX: update usb device tests for deprecated API
  TESTS/usb_device/msd/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12161 nRF52 I2CSlave Implementation
  drivers/I2CSlave.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/config/sdk_config.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/i2c_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/objects.h
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12606 Netsocket: Introduce set_ip_address and get_dns_server APIs
  UNITTESTS/stubs/NetworkInterface_stub.cpp
  features/lwipstack/LWIPInterface.cpp
  features/lwipstack/LWIPStack.h
  features/netsocket/NetworkInterface.cpp
  features/netsocket/NetworkInterface.h
  features/netsocket/OnboardNetworkStack.h
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_WIO_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_WIO_EMW3166/libwiced_drivers.a
Labels: ready for merge, release-version: 6.0.0-beta-1

#12785 Cordio: Apply Packetcraft's fix for possible SweynTooth vulnerabilities
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/include/smp_api.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/dm/dm_sec.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp/smp_main.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp/smp_main.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp/smpi_act.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp/smpi_sc_act.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp/smpr_act.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp/smpr_sc_act.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12792 Seeed: Removing unsupported Seeed targets for OS 6
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/TARGET_RO359B/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/TARGET_RO359B/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/TARGET_RO359B/PinNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/TARGET_RO359B/crc.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/TARGET_RO359B/crc.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/TARGET_RO359B/device.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/TARGET_RO359B/fsl_clock_config.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/TARGET_RO359B/fsl_clock_config.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K24F/TARGET_MCU_K24F1M/TARGET_RO359B/mbed_overrides.c
  targets/TARGET_Freescale/mbed_rtx.h
  targets/TARGET_NORDIC/TARGET_MCU_NRF51822/TARGET_ARCH_BLE/PinNames.h
  targets/TARGET_NORDIC/TARGET_MCU_NRF51822/TARGET_ARCH_BLE/device.h
  targets/TARGET_NORDIC/TARGET_MCU_NRF51822/TARGET_SEEED_TINY_BLE/PinNames.h
  targets/TARGET_NORDIC/TARGET_MCU_NRF51822/TARGET_SEEED_TINY_BLE/device.h
  targets/TARGET_NXP/TARGET_LPC11UXX/TARGET_ARCH_GPRS/PeripheralNames.h
  targets/TARGET_NXP/TARGET_LPC11UXX/TARGET_ARCH_GPRS/PeripheralPins.c
  targets/TARGET_NXP/TARGET_LPC11UXX/TARGET_ARCH_GPRS/PinNames.h
  targets/TARGET_NXP/TARGET_LPC11UXX/TARGET_ARCH_GPRS/device.h
  targets/TARGET_NXP/TARGET_LPC11UXX/TARGET_MCU_LPC11U35_501/TARGET_XADOW_M0/PinNames.h
  targets/TARGET_NXP/TARGET_LPC11UXX/TARGET_MCU_LPC11U35_501/TARGET_XADOW_M0/device.h
  targets/targets.json
Labels: BREAKING-CHANGE, ready for merge

#12711 targets:MIMXRT1050: Add QSPI flash support
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/flash_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/device.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/flash_defines.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/xip/evkbimxrt1050_flexspi_nor_config.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_ARM_STD/MIMXRT1052xxxxx.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_GCC_ARM/MIMXRT1052xxxxx.ld
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_IAR/MIMXRT1052xxxxx.icf
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_flexspi.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_flexspi.h
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12769 Fix WIFI-GET-RSSI test case failure and remove extra label from CYW9P62S1_43438EVB_01 in target.json
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.cpp
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12731 Testing: Fix multihoming test compilation issues
  TESTS/network/multihoming/main.cpp
  TESTS/network/multihoming/multihoming_tests.h
  features/netsocket/SocketAddress.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12745 add config option for phy media interface
  features/netsocket/emac-drivers/TARGET_STM/mbed_lib.json
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12752 PSoC 62/63: set correct mbed_ram_start and mbed_ram_size
  targets/targets.json
Labels: devices: cypress, ready for merge, release-version: 6.0.0-beta-1

#12758 Fix: Return the correct std I/O device handle for Microlib in retarget code
  platform/source/mbed_retarget.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12763 Cellular: Fix ATHandler::read_string to handle delimiter inside string
  UNITTESTS/features/cellular/framework/device/athandler/athandlertest.cpp
  features/cellular/framework/device/ATHandler.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12768 ESP8266 Drv support baud-rate switch
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12786 Baremetal: Enable kernel_tick_count greentea test
  TESTS/mbedmicro-rtos-mbed/kernel_tick_count/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12799 TDBStore: Handle odd number of sectors in block
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12802 Nuvoton: Add 'sectors' configuration option into targets.json
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12691 Replace small with std C lib if not supported by a target's toolchain
  tools/build_api.py
  tools/test/toolchains/test_toolchains.py
  tools/toolchains/arm.py
  tools/toolchains/gcc.py
  tools/toolchains/iar.py
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-version: 6.0.0-beta-1

#12702 TFM: Remove ARM Compiler 5 considerations
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_core.c
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12734 NUCLEO_WB55RG : enable IAR export
  tools/export/iar/iar_definitions.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12748 Fix build failure due to C lib selected
  tools/build_api.py
Labels: ready for merge, release-version: 6.0.0-beta-1

#12774 Feature wisun
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/flash_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PeripheralNames.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PeripheralPins.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/device.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/flash_defines.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/xip/evkbimxrt1050_flexspi_nor_config.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_ARM_STD/MIMXRT1052xxxxx.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_GCC_ARM/MIMXRT1052xxxxx.ld
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_IAR/MIMXRT1052xxxxx.icf
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_flexspi.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_flexspi.h
  targets/targets.json
Labels: ready for merge, release-version: feature branch

#12766 Add Wi-SUN statistics interface
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/mbed-mesh-api/source/include/wisun_tasklet.h
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: feature branch

#12779 Baremetal: Enable EventFlags greentea test
  TESTS/mbedmicro-rtos-mbed/event_flags/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12804 Cellular: Check if serial is supported
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/device/ATHandler.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12699 Storage: Remove support for ARM Compiler 5
  features/storage/filesystem/littlefs/littlefs/lfs_util.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12778 Add I2C api to Musca-B1 target
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/PeripheralNames.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/PinNames.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/device/drivers/i2c_ip6510_drv.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/device/drivers/i2c_ip6510_drv.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/i2c_api.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/pinmap_ns.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/prebuilt/crypto_access_control.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/prebuilt/spm_client.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/prebuilt/spm_server.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/prebuilt/spm_smoke.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/prebuilt/tfm.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/device/device_cfg.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/objects.h
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12797 Add custom board option to STM32 pins generation script
  tools/targets/STM32_gen_PeripheralPins.py
Labels: ready for merge, release-version: 6.0.0-beta-1

#12765 Update MTS_MDOT_F411RE target and remove bootloader from tools
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTB_MTS_DRAGONFLY/TOOLCHAIN_ARM_STD/stm32f411re.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTB_MTS_DRAGONFLY/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/TOOLCHAIN_ARM_MICRO/stm32f411re.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/TOOLCHAIN_GCC_ARM/STM32F411XE.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_MDOT_F411RE/TOOLCHAIN_IAR/stm32f411xe.icf
  targets/targets.json
  tools/bootloaders/MTS_MDOT_F411RE/LICENSE.txt
  tools/bootloaders/MTS_MDOT_F411RE/bootloader.bin
  tools/export/uvision/__init__.py
  tools/targets/__init__.py
Labels: ready for merge, release-version: 6.0.0-beta-1

#12791 Fix for IPv6 Dual Stack support
  features/lwipstack/LWIPInterface.cpp
  features/lwipstack/LWIPStack.h
  features/netsocket/OnboardNetworkStack.h
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.cpp
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSoftAPInterface.cpp
Labels: devices: cypress, ready for merge, release-version: 6.0.0-beta-1

#12755 Update astyle filtering rules for Nanostack
  .astyleignore
Labels: ready for merge, release-version: 6.0.0-beta-1

#12815 Cellular: Fix build problem if cellular.debug-at is set as null
  features/cellular/framework/device/ATHandler.cpp
  features/cellular/mbed_lib.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12741 Add Semtech Lora radio drivers
  components/lora/COMPONENT_SX126X/SX126X_LoRaRadio.cpp
  components/lora/COMPONENT_SX126X/SX126X_LoRaRadio.h
  components/lora/COMPONENT_SX126X/SleepMode.txt
  components/lora/COMPONENT_SX126X/mbed_lib.json
  components/lora/COMPONENT_SX126X/sx126x_ds.h
  components/lora/COMPONENT_SX1272/README.md
  components/lora/COMPONENT_SX1272/SX1272_LoRaRadio.cpp
  components/lora/COMPONENT_SX1272/SX1272_LoRaRadio.h
  components/lora/COMPONENT_SX1272/mbed_lib.json
  components/lora/COMPONENT_SX1272/registers/sx1272Regs-Fsk.h
  components/lora/COMPONENT_SX1272/registers/sx1272Regs-LoRa.h
  components/lora/COMPONENT_SX1276/README.md
  components/lora/COMPONENT_SX1276/SX1276_LoRaRadio.cpp
  components/lora/COMPONENT_SX1276/SX1276_LoRaRadio.h
  components/lora/COMPONENT_SX1276/mbed_lib.json
  components/lora/COMPONENT_SX1276/registers/sx1276Regs-Fsk.h
  components/lora/COMPONENT_SX1276/registers/sx1276Regs-LoRa.h
  components/lora/LICENCE-BSD-3-Clause
  components/lora/LICENSE
  components/lora/README.md
Labels: ready for merge, release-version: 6.0.0-beta-1

#12742 BLE: remove deprecated APIs from Gatt and SecurityManager
  features/FEATURE_BLE/ble/GattCharacteristic.h
  features/FEATURE_BLE/ble/GattClient.h
  features/FEATURE_BLE/ble/SecurityManager.h
  features/FEATURE_BLE/ble/pal/PalSecurityManager.h
  features/FEATURE_BLE/source/SecurityManager.tpp
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12736 rtos: Improve CMSIS-RTOSv2 app compatibility
  rtos/source/TARGET_CORTEX/mbed_lib.json
  rtos/source/TARGET_CORTEX/mbed_rtx_conf.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12817 Cellular: Disable AT traces when mbed-trace is disabled
  features/cellular/framework/device/ATHandler.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12819 Cypress: Fix unitialized memory in spi_master_write
  targets/TARGET_Cypress/TARGET_PSOC6/cy_spi_api.c
Labels: devices: cypress, ready for merge, release-version: 6.0.0-beta-1

#12811 Remove deprecated Platform header files
  platform/critical.h
  platform/mbed_sleep.h
  platform/rtc_time.h
  platform/semihost_api.h
  platform/sleep.h
  platform/toolchain.h
  platform/wait_api.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12271 Make cypress psoc64 TFM ready and also add TF-M initialization
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_DUALCPU/src/tfm_mbed_boot.c
  features/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V8M/src/tfm_mbed_boot.c
  rtos/source/TARGET_CORTEX/mbed_boot.c
  rtos/source/TARGET_CORTEX/mbed_boot.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_ARM/cyb06xxa_cm4.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/cyb06xxa_cm4.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/device/COMPONENT_CM4/device_cfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/partition/flash_layout.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_064S2_4343W/partition/region_defs.h
  targets/TARGET_Cypress/TARGET_PSOC6/cy_us_ticker_api.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12671 Netsocket/lwIP Stack: Remove support for ARM Compiler 5
  features/frameworks/nanostack-libservice/mbed-client-libservice/common_functions.h
  features/frameworks/nanostack-libservice/mbed-client-libservice/ns_types.h
  features/lwipstack/lwip-sys/arch/cc.h
  features/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/port/compiler/fnet_comp_config.h
  features/nanostack/sal-stack-nanostack/source/nsconfig.h
  features/netsocket/emac-drivers/TARGET_Freescale_EMAC/kinetis_emac.cpp
  features/netsocket/emac-drivers/TARGET_NXP_EMAC/TARGET_IMX/imx_emac.cpp
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
  features/netsocket/ppp/ppp_service_if.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12830 Cellular: Fix BG96 offloaded DNS query for new API
  TESTS/netsocket/dns/asynchronous_dns_multi_ip.cpp
  TESTS/netsocket/dns/dns_tests.h
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/dns/synchronous_dns_multi_ip.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12816 Baremetal: Enable Semaphore greentea test
  TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12827 enable common tickers & lp_tickers hal tests in baremetal mode
  TESTS/mbed_hal/common_tickers/main.cpp
  TESTS/mbed_hal/common_tickers_freq/main.cpp
  TESTS/mbed_hal/lp_ticker/main.cpp
  TESTS/mbed_hal/stack_size_unification/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12787 Cypress: Add CYESKIT-064B0S2-4343W
  TESTS/mbed_hal/qspi/flash_configs/flash_configs.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/nvram/TARGET_CYESKIT_064B0S2_4343W/wifi_nvram_image.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg.timestamp
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_clocks.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_notices.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_peripherals.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_pins.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_qspi_memslot.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_routing.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/cycfg_system.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/GeneratedSource/qspi_config.cfg
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/cyreservedresources.list
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/design.cycapsense
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/design.cyqspi
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/COMPONENT_BSP_DESIGN_MODUS/design.modus
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/cybsp.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/cybsp.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/cybsp_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_ARM/cyb06xxa_cm0plus.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_ARM/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/cyb06xxa_cm0plus.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_IAR/cyb06xxa_cm0plus.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM0P/TOOLCHAIN_IAR/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM0P/system_psoc6_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_ARM/cyb06xxa_cm4.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/cyb06xxa_cm4.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_IAR/cyb06xxa_cm4.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM4/TOOLCHAIN_IAR/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/COMPONENT_CM4/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYESKIT_064B0S2_4343W/secure_image_parameters.json
  targets/targets.json
Labels: devices: cypress, ready for merge, scope: new-target

#12818 Add the Doxygen note to non-supported RTOS and Driver class.
  drivers/USBCDC_ECM.h
  rtos/ConditionVariable.h
  rtos/Mail.h
  rtos/MemoryPool.h
  rtos/Queue.h
  rtos/Thread.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12840 Musca-B1: Grant Non-Secure access for MHU0 on EXP0
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/prebuilt/crypto_access_control.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/prebuilt/spm_client.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/prebuilt/spm_server.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/prebuilt/spm_smoke.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_NS/prebuilt/tfm.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/TARGET_MUSCA_B1_S/target_cfg.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12663 Migrate NUCLEO_F303K8 to Mbed OS 5 baremetal
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303x8/device/TOOLCHAIN_ARM_STD/stm32f303x8.sct
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303x8/device/TOOLCHAIN_GCC_ARM/STM32F303X8.ld
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12826 [feature-wisun] Fix feature-wisun tests
  TESTS/configs/fpga.json
Labels: needs: CI, release-version: feature branch

#12841 Drops prebuild bootloaders not supported in Mbed OS 6
  tools/bootloaders/MTB_MTS_DRAGONFLY/LICENSE.txt
  tools/bootloaders/MTB_MTS_DRAGONFLY/bootloader.bin
  tools/bootloaders/REALTEK_RTL8195AM/LICENSE
  tools/bootloaders/REALTEK_RTL8195AM/ram_1.bin
Labels: ready for merge, release-version: 6.0.0-beta-1

#12833 Override c_lib to small for all targets
  TESTS/configs/baremetal.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12842 Remove ethernet interface logic for SoftAP and STA
  features/lwipstack/LWIPInterface.cpp
  features/lwipstack/LWIPStack.h
  features/netsocket/OnboardNetworkStack.h
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.cpp
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSoftAPInterface.cpp
Labels: ready for merge, release-version: 5.15.3

#12843 enable storage tests on baremetal
  features/storage/TESTS/kvstore/filesystemstore_tests/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_2/main.cpp
  features/storage/TESTS/kvstore/static_tests/main.cpp
Labels: release-version: 6.0.0-beta-1

#12845 Backport SweynTooth fix for Cordio to 5.15
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/include/smp_api.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/dm/dm_sec.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp/smp_main.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp/smp_main.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp/smpi_act.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp/smpi_sc_act.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp/smpr_act.c
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/smp/smpr_sc_act.c
Labels: ready for merge, release-version: 5.15.3

#12846 Revert "Remove MTB_STM_S2LP target"
  components/802.15.4_RF/stm-s2lp-rf-driver/mbed_lib.json
  components/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver/NanostackRfPhys2lp.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_MTB_STM_S2LP/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_MTB_STM_S2LP/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_MTB_STM_S2LP/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_MTB_STM_S2LP/system_clock.c
  targets/targets.json
  tools/test_configs/Wi-SUNInterface.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12825 Turn on ARM linker --inline
  tools/profiles/develop.json
  tools/profiles/release.json
Labels: release-version: 6.0.0-beta-1

#12852 Update mbed-coap to version 5.1.4
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12854 Implement psa_hash_*() functions
  components/TARGET_PSA/services/crypto/COMPONENT_SPE/psa_crypto_partition.c
Labels: ready for merge, release-version: 5.15.3

#12844 Add invalid data case to tdbstore ram init
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12850 Fix intermittent sync fail in tests-filesystem-general_filesystem
  features/storage/TESTS/filesystem/general_filesystem/main.cpp
Labels: devices: cypress, ready for merge, release-version: 6.0.0-beta-1

#12855 Bare metal: Enable signals greentea test
  TESTS/mbedmicro-rtos-mbed/signals/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12859 Update mbed-coap to version 5.1.4
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.15.3

#12863 STM32 GCC Unspecified RTOS error
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L552xx/TOOLCHAIN_GCC_ARM/stm32l552xx.ld
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L562xx/TOOLCHAIN_GCC_ARM/stm32l562xx.ld
Labels: ready for merge, release-version: 5.15.3

#12730 BLE Gap deprecation cleanup/rework
  features/FEATURE_BLE/ble/BLE.h
  features/FEATURE_BLE/ble/BLEInstanceBase.h
  features/FEATURE_BLE/ble/BLEProtocol.h
  features/FEATURE_BLE/ble/BLETypes.h
  features/FEATURE_BLE/ble/Gap.h
  features/FEATURE_BLE/ble/GapAdvertisingData.h
  features/FEATURE_BLE/ble/GapAdvertisingParams.h
  features/FEATURE_BLE/ble/GapEvents.h
  features/FEATURE_BLE/ble/GapScanningParams.h
  features/FEATURE_BLE/ble/SecurityManager.h
  features/FEATURE_BLE/ble/gap/AdvertisingParameters.h
  features/FEATURE_BLE/ble/gap/Gap.h
  features/FEATURE_BLE/ble/gap/Types.h
  features/FEATURE_BLE/ble/generic/GenericGap.h
  features/FEATURE_BLE/ble/generic/GenericSecurityManager.h
  features/FEATURE_BLE/ble/generic/SecurityDb.h
  features/FEATURE_BLE/ble/pal/ConnectionEventMonitor.h
  features/FEATURE_BLE/ble/pal/GapTypes.h
  features/FEATURE_BLE/ble/pal/GenericAccessService.h
  features/FEATURE_BLE/ble/pal/PalGap.h
  features/FEATURE_BLE/ble/pal/PalSecurityManager.h
  features/FEATURE_BLE/ble/services/LinkLossService.h
  features/FEATURE_BLE/source/BLE.cpp
  features/FEATURE_BLE/source/GapScanningParams.cpp
  features/FEATURE_BLE/source/LegacyGap.tpp
  features/FEATURE_BLE/source/SecurityManager.tpp
  features/FEATURE_BLE/source/gap/Gap.tpp
  features/FEATURE_BLE/source/generic/GenericGap.tpp
  features/FEATURE_BLE/source/generic/GenericSecurityManager.tpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioGattServer.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioPalGap.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/CordioPalGenericAccessService.h
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioImplementations.cpp
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioPalGap.tpp
Labels: BREAKING-CHANGE, needs: CI, release-version: 6.0.0-beta-1

#12867 Update mbed-coap to version v5.1.5 for Mbed OS 5.15
  features/frameworks/mbed-coap/.mbedignore
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.15.3

#12869 LWIP: don't pbuf_free(NULL) on socket close (5.15-branch)
  features/lwipstack/LWIPStack.cpp
Labels: ready for merge, release-version: 5.15.3

#12871 UpdateMbed version and secure binaries
  platform/mbed_version.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_NS/prebuilt/crypto_access_control.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_NS/prebuilt/spm_client.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_NS/prebuilt/spm_server.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_NS/prebuilt/spm_smoke.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_NS/prebuilt/tfm.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/crypto_access_control.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/spm_client.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/spm_server.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/spm_smoke.bin
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/prebuilt/tfm.bin
Labels: ready for merge, release-version: 5.15.3

#12868 Update mbed-coap to version v5.1.5 for feature-wisun
  features/frameworks/mbed-coap/.mbedignore
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: feature branch

#12866 Update mbed-coap to version v5.1.5
  features/frameworks/mbed-coap/.mbedignore
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12522 Add property API to InternetSocket
  UNITTESTS/features/netsocket/InternetSocket/test_InternetSocket.cpp
  features/nanostack/nanostack-interface/Nanostack.cpp
  features/netsocket/InternetSocket.cpp
  features/netsocket/InternetSocket.h
  features/netsocket/nsapi_types.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12874 nRF: use Mbed-default boot-stack-size & fix stack_size_unification test
  TESTS/mbed_hal/stack_size_unification/main.cpp
  rtos/source/TARGET_CORTEX/mbed_lib.json
Labels: ready for merge

#12694 Remove netsocket icetea tests and TCPServer
  TEST_APPS/device/socket_app/cmd_ifconfig.cpp
  TEST_APPS/device/socket_app/cmd_ifconfig.h
  TEST_APPS/device/socket_app/cmd_socket.cpp
  TEST_APPS/device/socket_app/cmd_socket.h
  TEST_APPS/device/socket_app/main.cpp
  TEST_APPS/device/socket_app/mbed_app.json
  TEST_APPS/device/socket_app/strconv.c
  TEST_APPS/device/socket_app/strconv.h
  TEST_APPS/testcases/README.md
  TEST_APPS/testcases/netsocket/README.md
  TEST_APPS/testcases/netsocket/SOCKET_BIND_PORT.py
  TEST_APPS/testcases/netsocket/TCPSERVER_ACCEPT.py
  TEST_APPS/testcases/netsocket/TCPSOCKET_ACCEPT.py
  TEST_APPS/testcases/netsocket/TCPSOCKET_ECHOTEST_BURST_SHORT.py
  TEST_APPS/testcases/netsocket/__init__.py
  TEST_APPS/testcases/netsocket/interface.py
  UNITTESTS/features/netsocket/TCPServer/test_TCPServer.cpp
  UNITTESTS/features/netsocket/TCPServer/unittest.cmake
  UNITTESTS/features/netsocket/TCPSocket/test_TCPSocket.cpp
  features/lwipstack/lwipopts.h
  features/lwipstack/mbed_lib.json
  features/netsocket/NetworkStack.h
  features/netsocket/TCPServer.cpp
  features/netsocket/TCPServer.h
  features/netsocket/TCPSocket.h
  features/netsocket/nsapi.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12884 Update README.md
  README.md
Labels: mergify skip, release-type: major

#12886 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: release-type: feature

#12887 Update LICENSE.md
  LICENSE.md
Labels: release-type: patch

#12878 Added kv store adaptation to Nanostack file interface
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/mbed_lib.json
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_file_system_api.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_file_system_api.h
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_hal_init.c
Labels: ready for merge, release-version: feature branch

#12657 Added new configuration parameters to Wi-SUN network interface and Border Router class
  features/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackPPPInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  features/nanostack/mbed-mesh-api/source/NanostackPPPInterface.cpp
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/mbed-mesh-api/source/include/wisun_tasklet.h
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: feature branch

#12456 COMPONENT_BlueNRG_MS creation : ST Bluetooth Low Energy module
  components/BLE/COMPONENT_BlueNRG_MS/BlueNrgMsHCIDriver.cpp
  components/BLE/COMPONENT_BlueNRG_MS/README.md
  components/BLE/COMPONENT_BlueNRG_MS/mbed_lib.json
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12853 ARCH_PRO: Remove uARM tooolchain support
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_ARM_MICRO/LPC1768.sct
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_ARM_MICRO/startup_LPC17xx.S
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_ARM_STD/LPC1768.sct
  targets/targets.json
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12463 Clean up and optimise socket statistics
  UNITTESTS/stubs/SocketStats_Stub.cpp
  features/netsocket/SocketStats.cpp
  features/netsocket/SocketStats.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12872 Add the Doxygen note to non-supported RTOS kernel APIs.
  rtos/Kernel.h
Labels: ready for merge

#12873 Bare metal profile: USB class device support
  drivers/USBCDC_ECM.h
  drivers/source/usb/USBCDC_ECM.cpp
Labels: ready for merge

#12761 Callback: Trivial default
  platform/mbed_lib.json
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12889 Convert newlines on all terminal (tty) devices by default
  platform/mbed_lib.json
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12839 Nuvoton: netsocket correction of judgment errors
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/TARGET_M480/m480_eth.c
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/TARGET_NUC472/nuc472_eth.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12823 Allow Devicekey::generate_root_of_trust() to define key size.
  features/device_key/source/DeviceKey.cpp
  features/device_key/source/DeviceKey.h
Labels: needs: CI, release-version: 6.0.0-beta-1
