Repository ARMmbed/mbed-os, pull requests merged in 2020-10, with the labels that each got.

#13685 allow host resolved address to be used for connection
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
Labels: needs: review, release-version: feature branch

#13694 adapting to new s3 bucket location in travis.yml
  .travis.yml
Labels: ready for merge

#13696 adapting to new s3 bucket location in travis.yml
  .travis.yml
Labels: Release review required, ready for merge

#13721 TEST: Extend the kvstore test time out to 120s
  features/storage/TESTS/kvstore/filesystemstore_tests/main.cpp
Labels: ready for merge, release-version: feature branch

#13716 [feature-wisun] Nanostack release v12.6.0
  features/nanostack/sal-stack-nanostack/nanostack/ws_bbr_api.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common_defines.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_config.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_llc_data_service.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_management_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_key_storage.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/radius_eap_tls_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_keys.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_keys.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_lib.c
  features/nanostack/sal-stack-nanostack/source/Service_Libs/etx/etx.c
  features/nanostack/sal-stack-nanostack/source/Service_Libs/etx/etx.h
  features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.c
Labels: needs: work, release-version: feature branch

#13695 CMake: Add memap table
  CMakeLists.txt
  tools/cmake/toolchains/ARM.cmake
  tools/cmake/toolchains/GCC_ARM.cmake
Labels: needs: CI, release-version: feature branch

#13549 Make readdir reentrant
  platform/include/platform/mbed_retarget.h
  platform/source/mbed_retarget.cpp
Labels: ready for merge, release-type: patch

#13749 Add missing args to weakly defined PalRtc functions
  connectivity/FEATURE_BLE/source/cordio/stack_adaptation/pal_mbed_os_adaptation.cpp
Labels: ready for merge, release-type: patch

#13744 Use NUCLEO_F429ZI for Azure IoT Hub and Google IoT Core examples testing
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#13742 Add initialization to radius retry values
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
Labels: ready for merge, release-type: patch

#13729 BLE: Enable getting an implicitly-created CCCD through `GattCharacteristic::getDescriptor`
  connectivity/FEATURE_BLE/include/ble/gatt/GattCharacteristic.h
  connectivity/FEATURE_BLE/source/cordio/source/GattServerImpl.cpp
Labels: ready for merge, release-type: patch

#13718 Nanostack release v12.6.0
  connectivity/nanostack/sal-stack-nanostack/nanostack/net_ws_test.h
  connectivity/nanostack/sal-stack-nanostack/nanostack/ws_bbr_api.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common_defines.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_config.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_empty_functions.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_llc_data_service.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_management_api.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_key_storage.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_test_api.c
  connectivity/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mcps_sap.c
  connectivity/nanostack/sal-stack-nanostack/source/RPL/rpl_structures.h
  connectivity/nanostack/sal-stack-nanostack/source/RPL/rpl_upward.c
  connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/radius_eap_tls_sec_prot.c
  connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot/radius_client_sec_prot.c
  connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_keys.c
  connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_keys.h
  connectivity/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_lib.c
  connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/etx/etx.c
  connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/etx/etx.h
  connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.c
  connectivity/nanostack/sal-stack-nanostack/source/libNET/src/net_dns.c
Labels: ready for merge, release-type: patch

#13714 nanostack: mesh interface global up is indicated always on bootstrap
  connectivity/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  connectivity/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-type: patch

#13704 ble: reset transport last and reset the default chars in gatt server
  connectivity/FEATURE_BLE/source/cordio/source/BLEInstanceBaseImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/GattServerImpl.cpp
Labels: ready for merge, release-type: patch

#13643 M2351: Support GCC and IAR
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/device/TOOLCHAIN_ARMC6/M2351.sct
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/device/TOOLCHAIN_GCC_ARM/M2351.ld
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/device/TOOLCHAIN_IAR/M2351.icf
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_S/device/TOOLCHAIN_ARMC6/M2351.sct
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_S/device/TOOLCHAIN_GCC_ARM/M2351.ld
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_S/device/TOOLCHAIN_IAR/M2351.icf
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_ARMC6/M2351.sct
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_GCC_ARM/M2351.ld
  targets/TARGET_NUVOTON/TARGET_M2351/device/TOOLCHAIN_IAR/M2351.icf
  targets/TARGET_NUVOTON/TARGET_M2351/device/cmsis.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/partition_M2351.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/partition_M2351_mem.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/partition_M2351_mem.icf
  targets/TARGET_NUVOTON/TARGET_M2351/device/partition_M2351_mem.icf.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/startup_M2351.c
  targets/TARGET_NUVOTON/TARGET_M2351/flash_api.c
  targets/TARGET_NUVOTON/TARGET_M2351/rtc_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.15.6

#13610 Fix #13490 Cellular disconnect does not deactivate context
  connectivity/cellular/source/framework/AT/AT_CellularContext.cpp
Labels: ready for merge, release-type: patch

#13606 Update Mbed CoAP to v5.1.7
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/source/sn_coap_parser.c
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.15.6

#13525 device_management.py supports application access keys 5.15
  tools/device_management.py
Labels: ready for merge, release-version: 5.15.6

#13512 mbed-os-5.15: Nuvoton: Fixed NUC472 SD buffer alignment
  targets/TARGET_NUVOTON/TARGET_NUC472/device/StdDriver/nuc472_sd.c
Labels: ready for merge, release-version: 5.15.6

#13639 Add SD, USBDEVICE & LPTICKER support for VK_RZ_A1H board.
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/PeripheralPins.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/PeripheralNames.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/PeripheralPins.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_ARM_STD/VKRZA1H.sct
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_ARM_STD/sys.cpp
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_GCC_ARM/VKRZA1H.ld
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_GCC_ARM/startup_VKRZ1AH.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_GCC_ARM/weak_handler.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_IAR/VKRZA1H.icf
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/TOOLCHAIN_IAR/weak_handler.S
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/VKRZA1H.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/inc/VK_RZ_A1H.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/inc/iobitmasks/spibsc_iobitmask.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/inc/iodefine.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/inc/iodefines/sdhi_iodefine.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/inc/reg32_t.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/system_VK_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/mbed_drv_cfg.h
  targets/targets.json
Labels: ready for merge, release-version: 5.15.6

#13739 Nuvoton: Enable fault handler dump message on CM23 targets (5.15)
  targets/targets.json
Labels: ready for merge, release-version: 5.15.6

#13754 CMake: replace usage of the mbed_add_cmake_directory_if_labels()
  CMakeLists.txt
  cmsis/CMSIS_5/CMSIS/CMakeLists.txt
  docs/design-documents/tools/cmake.md
  hal/CMakeLists.txt
  hal/usb/CMakeLists.txt
  targets/CMakeLists.txt
  targets/TARGET_Freescale/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/CMakeLists.txt
  targets/TARGET_NORDIC/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/CMakeLists.txt
  targets/TARGET_STM/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/CMakeLists.txt
  tools/cmake/util.cmake
Labels: needs: CI, release-version: feature branch

#13576 [mbed-os-5.15] Added external RADIUS server configuration to Wi-SUN Border Router
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-version: 5.15.6

#13759 Privacy workaround wb55
  connectivity/FEATURE_BLE/mbed_lib.json
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.h
Labels: needs: review, release-version: feature branch

#13760 Fix conditional compilation for ble
  connectivity/FEATURE_BLE/include/ble/SecurityManager.h
  connectivity/FEATURE_BLE/source/SecurityManager.cpp
  connectivity/FEATURE_BLE/source/cordio/source/BLEInstanceBaseImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.h
  connectivity/FEATURE_BLE/source/cordio/source/PalPrivateAddressControllerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalPrivateAddressControllerImpl.h
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.cpp
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.h
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.h
  connectivity/FEATURE_BLE/source/pal/PalGap.h
  connectivity/FEATURE_BLE/source/pal/PalPrivateAddressController.h
Labels: needs: work, release-version: feature branch

#13725 STM32: update SetSysClock for NUCLEO_L476RG
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/TARGET_NUCLEO_L476RG/system_clock.c
Labels: ready for merge, release-type: patch

#13762 CMake: fix mbed.h components inclusion
  connectivity/netsocket/CMakeLists.txt
  events/CMakeLists.txt
  mbed.h
  rtos/CMakeLists.txt
  storage/CMakeLists.txt
Labels: release-version: feature branch

#13677 psoc64: Update flash layout of CYTFM_064B0S2_4343W
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/cytfm_flash_info.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/cytfm_flash_info.h
  targets/TARGET_Cypress/TARGET_PSOC6/cy_flash_api.c
Labels: ready for merge, release-type: patch

#13707 Fix ESP8266
  connectivity/drivers/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-type: patch

#13737 Add certificate remove before add to wisun tasklet
  connectivity/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-type: patch

#13757 wisun: Add APIs for Device min sense and CCA threshold table.
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  connectivity/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-type: patch

#13738 Nuvoton: Enable fault handler dump message on CM23 targets
  targets/targets.json
Labels: ready for merge, release-type: patch

#13743 Define SD and STORAGE for the MAX32630FTHR and prevent warnings during compilation on Mbed 5.12 and above
  targets/TARGET_Maxim/TARGET_MAX32620C/device/mxc_device.h
  targets/TARGET_Maxim/TARGET_MAX32625/device/mxc_device.h
  targets/TARGET_Maxim/TARGET_MAX32630/device/mxc_device.h
  targets/targets.json
Labels: ready for merge, release-type: patch

#13717 Feature ble host privacy
  connectivity/FEATURE_BLE/include/ble/Gap.h
  connectivity/FEATURE_BLE/include/ble/SecurityManager.h
  connectivity/FEATURE_BLE/include/ble/common/Duration.h
  connectivity/FEATURE_BLE/include/ble/gap/Events.h
  connectivity/FEATURE_BLE/include/ble/gap/Types.h
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/include/dm_api.h
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/dm/dm_sec.c
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/dm/dm_sec.h
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/smp/smp_act.c
  connectivity/FEATURE_BLE/mbed_lib.json
  connectivity/FEATURE_BLE/source/Gap.cpp
  connectivity/FEATURE_BLE/source/SecurityManager.cpp
  connectivity/FEATURE_BLE/source/cordio/source/BLEInstanceBaseImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/BLEInstanceBaseImpl.h
  connectivity/FEATURE_BLE/source/cordio/source/PalEventQueueImpl.h
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.h
  connectivity/FEATURE_BLE/source/cordio/source/PalPrivateAddressControllerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalPrivateAddressControllerImpl.h
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.h
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.cpp
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.h
  connectivity/FEATURE_BLE/source/generic/SecurityDb.h
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.h
  connectivity/FEATURE_BLE/source/pal/GapTypes.h
  connectivity/FEATURE_BLE/source/pal/PalGap.h
  connectivity/FEATURE_BLE/source/pal/PalPrivateAddressController.h
  connectivity/FEATURE_BLE/source/pal/PalSecurityManager.h
Labels: ready for merge, release-type: feature

#13619 Travis: remove status functionality
  .travis.yml
Labels: ready for merge, release-type: patch

#13683 USB STM32: fix header inclusion, removing mbed.h
  targets/TARGET_STM/USBPhyHw.h
Labels: ready for merge, release-type: patch

#13595 Nordic: Support 31250 baud rate
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
Labels: ready for merge, release-type: patch

#13655 STM32_gen_PeripheralPins.py v1.17
  targets/TARGET_STM/README.md
  targets/TARGET_STM/tools/STM32_gen_PeripheralPins.py
Labels: ready for merge, release-type: patch

#13723 Add crash RAM to STM32F412xG
  platform/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TOOLCHAIN_ARM/stm32f411re.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TOOLCHAIN_IAR/stm32f411xe.icf
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TOOLCHAIN_ARM/stm32f412xg.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TOOLCHAIN_GCC_ARM/STM32F412xG.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TOOLCHAIN_IAR/stm32f412xx.icf
Labels: ready for merge, release-type: patch

#13773 CMake: remove alredy included string.h in STM32 usb phy
  targets/TARGET_STM/USBPhyHw.h
Labels: needs: review, release-version: feature branch

#13745 Scancode: Fix false positive reported by scancode output analyser script
  .travis.yml
  tools/test/travis-ci/scancode-evaluate.py
  tools/test/travis-ci/scancode_evaluate_test.py
  tools/test/travis-ci/scancode_test/scancode_test_1.json
  tools/test/travis-ci/scancode_test/scancode_test_2.json
  tools/test/travis-ci/scancode_test/scancode_test_3.json
  tools/test/travis-ci/scancode_test/scancode_test_4.json
Labels: ready for merge, release-type: patch

#13767 CMake: linker preprocess fix for Gcc Arm
  CMakeLists.txt
  tools/cmake/toolchains/GCC_ARM.cmake
Labels: release-version: feature branch

#13654 Remove WEP security Green Tea Test case as the WEP security Key are sequence of Hex Values
  connectivity/netsocket/tests/TESTS/network/wifi/wifi_set_credential.cpp
Labels: ready for merge, release-type: patch

#13733 Enable Nanostack DNS cache usage
  connectivity/nanostack/include/nanostack-interface/Nanostack.h
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  connectivity/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  connectivity/nanostack/source/Nanostack.cpp
Labels: ready for merge, release-type: patch

#13734 BLE: Introduce ChainableEventHandler and subclasses
  connectivity/FEATURE_BLE/include/ble/Gap.h
  connectivity/FEATURE_BLE/include/ble/GattServer.h
  connectivity/FEATURE_BLE/include/ble/common/ChainableEventHandler.h
  connectivity/FEATURE_BLE/include/ble/gap/ChainableGapEventHandler.h
  connectivity/FEATURE_BLE/include/ble/gatt/ChainableGattServerEventHandler.h
  connectivity/FEATURE_BLE/include/ble/gatt/GattCallbackParamTypes.h
  connectivity/FEATURE_BLE/source/GattServer.cpp
  connectivity/FEATURE_BLE/source/cordio/source/GattServerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/GattServerImpl.h
Labels: ready for merge, release-type: feature

#13782 scancode: fix SPDX check - only warning
  tools/test/travis-ci/scancode-evaluate.py
  tools/test/travis-ci/scancode_evaluate_test.py
Labels: ready for merge, release-type: patch

#13771 Separate cloud example configurations to another file
  tools/test/examples/cloud_examples.json
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#13779 BLE: Fix scan state and host resolution of RPAs
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
Labels: ready for merge, release-type: patch

#13787 Update Mbed CoAP to v5.1.8
  connectivity/libraries/mbed-coap/CHANGELOG.md
  connectivity/libraries/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-type: patch

#13785 BLE: Fix access to attcCb.onDeck and attsCb.prepWriteQueue access
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/att/attc_main.c
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/att/attc_proc.c
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/att/attc_sign.c
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/att/atts_main.c
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/att/atts_write.c
Labels: ready for merge, release-type: patch

#13713 STM32H7: add NUCLEO_H7A3ZI_Q new target
  targets/TARGET_STM/TARGET_STM32H7/README.md
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/TARGET_NUCLEO_H7A3ZI_Q/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/TARGET_NUCLEO_H7A3ZI_Q/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/TOOLCHAIN_ARM/startup_stm32h7a3xxq.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/TOOLCHAIN_ARM/stm32h7a3xxq.sct
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/TOOLCHAIN_GCC_ARM/startup_stm32h7a3xxq.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/TOOLCHAIN_GCC_ARM/stm32h7a3xxq.ld
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/TOOLCHAIN_IAR/startup_stm32h7a3xxq.S
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/TOOLCHAIN_IAR/stm32h7a3xxq.icf
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/system_clock.c
  targets/targets.json
Labels: ready for merge, release-type: patch, scope: new-target

#13652 Fix STM32H747 Arduino pinout
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/PinNames.h
Labels: ready for merge, release-version: 5.15.6

#13719 mbed-os-5.15: Nanostack release v12.6.0
  features/nanostack/sal-stack-nanostack/nanostack/net_ws_test.h
  features/nanostack/sal-stack-nanostack/nanostack/ws_bbr_api.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common_defines.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_config.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_empty_functions.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_llc_data_service.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_management_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_key_storage.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_test_api.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mcps_sap.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_structures.h
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_upward.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/radius_eap_tls_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot/radius_client_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_keys.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_keys.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_lib.c
  features/nanostack/sal-stack-nanostack/source/Service_Libs/etx/etx.c
  features/nanostack/sal-stack-nanostack/source/Service_Libs/etx/etx.h
  features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.c
  features/nanostack/sal-stack-nanostack/source/libNET/src/net_dns.c
Labels: ready for merge, release-version: 5.15.6

#13736 mbed-os-5.15: Add certificate remove before add to wisun tasklet
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: Release review required, release-version: 5.15.6

#13798 CMake: remove TODO as it is not valid anymore
  CMakeLists.txt
Labels: ready for merge, release-version: feature branch

#13799 CMake: fix application config
  CMakeLists.txt
  tools/cmake/app.cmake
Labels: release-version: feature branch

#13553 Standard pin-name design documents
  docs/design-documents/hal/0004-pin-names-general-guidelines.md
  docs/design-documents/hal/0005-pin-names-Arduino-Uno-standard.md
  docs/design-documents/hal/img/Arduino_Uno_Mbed.png
Labels: release-version: feature branch

#13810 Remove missing examples from the config
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#13740 feature-wisun: Add initialization to radius retry values
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
Labels: ready for merge, release-version: feature branch

#13808 Remove erroneous character from SPDX identifer
  connectivity/drivers/emac/TARGET_NUVOTON_EMAC/numaker_emac_config.h
  connectivity/drivers/emac/TARGET_NXP_EMAC/TARGET_LPCTarget/lpc17_emac.h
  connectivity/lwipstack/include/lwipstack/LWIPMemoryManager.h
  connectivity/lwipstack/source/LWIPInterface.cpp
  connectivity/lwipstack/source/LWIPMemoryManager.cpp
  connectivity/nanostack/mbed-mesh-api/source/include/NanostackMemoryManager.h
  connectivity/netsocket/include/netsocket/EMACMemoryManager.h
  storage/filesystem/tests/TESTS/filesystem/general_filesystem/main.cpp
Labels: ready for merge, release-type: patch

#13796 Update README.md to remove WEP test case with NULL data
  connectivity/netsocket/tests/TESTS/network/wifi/README.md
Labels: ready for merge, release-type: patch

#13692 Fix I2C slave bugs on Renesas RZ/A series.
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/i2c_api.c
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/i2c_api.c
Labels: ready for merge, release-type: patch

#13747 Renesas: fix timing to wait UART completion in deep sleep function
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/sleep.c
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/TARGET_GR_MANGO/device/os_tick_ostm.c
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/sleep.c
Labels: ready for merge, release-type: patch

#13830 CMake: Replace public to interface CMake keyword
  CMakeLists.txt
  tools/cmake/cores/Cortex-A9.cmake
  tools/cmake/cores/Cortex-M0+.cmake
  tools/cmake/cores/Cortex-M0.cmake
  tools/cmake/cores/Cortex-M1.cmake
  tools/cmake/cores/Cortex-M23-NS.cmake
  tools/cmake/cores/Cortex-M23.cmake
  tools/cmake/cores/Cortex-M3.cmake
  tools/cmake/cores/Cortex-M33-NS.cmake
  tools/cmake/cores/Cortex-M33.cmake
  tools/cmake/cores/Cortex-M33F-NS.cmake
  tools/cmake/cores/Cortex-M33F.cmake
  tools/cmake/cores/Cortex-M33FE-NS.cmake
  tools/cmake/cores/Cortex-M33FE.cmake
  tools/cmake/cores/Cortex-M4.cmake
  tools/cmake/cores/Cortex-M7.cmake
  tools/cmake/cores/Cortex-M7F.cmake
  tools/cmake/cores/Cortex-M7FD.cmake
  tools/cmake/toolchains/ARM.cmake
Labels: release-version: feature branch

#13828 fix ble example names
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#13825 [feature-wisun] Nanostack release v12.6.1
  features/nanostack/sal-stack-nanostack/nanostack/ws_management_api.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread/thread_bbr_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_llc_data_service.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_management_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_neighbor_class.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_key_storage.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_key_storage.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_nvm_data.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_nvm_data.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_nvm_store.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_time.c
  features/nanostack/sal-stack-nanostack/source/Common_Protocols/icmpv6.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mcps_sap.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_pd_sap.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_pd_sap.h
  features/nanostack/sal-stack-nanostack/source/MPL/mpl.c
  features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.c
  features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.h
Labels: ready for merge, release-version: feature branch

#13735 mbed-os-5.15: Enable Nanostack DNS cache usage
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  features/nanostack/nanostack-interface/Nanostack.cpp
  features/nanostack/nanostack-interface/Nanostack.h
Labels: Release review required, ready for merge

#13477 CMake: add CI testing
  .travis.yml
  tools/test/examples/examples.py
  tools/test/examples/examples_cmake.json
  tools/test/examples/examples_lib.py
Labels: ready for merge, release-version: feature branch

#13788 Update Mbed CoAP to v5.1.8
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.15.6

#13758 mbed-os-5.15: Add APIs for Device min sense and CCA threshold table
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-version: 5.15.6

#13774 mbed-os-5.15: Add initialization check to RADIUS ipv6 address
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
Labels: ready for merge, release-version: 5.15.6

#13775 mbed-os-5.15: Add initialization to radius retry values
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
Labels: ready for merge, release-version: 5.15.6

#13827 CMake: ninja reponse files disabled for ARMClang on Windows
  CMakeLists.txt
  tools/cmake/README.md
  tools/cmake/toolchain.cmake
Labels: release-version: feature branch

#13715 mbed-os-5.15: Mesh interface global up is indicated always on bootstrap ready
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: 5.15.6
