Repository ARMmbed/mbed-os, pull requests merged in 2020-02, with the labels that each got.

#12350 implements i2c_free for STM
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/PeripheralPinMaps.h
  targets/TARGET_STM/i2c_api.c
Labels: ready for merge

#12333 UDP echotests fix in case of no memory or device busy.
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  TESTS/netsocket/udp/udpsocket_sendto_repeat.cpp
Labels: ready for merge

#12332 FIX: Disable Analogin D13(PA_5) on some NUCLEO targets
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/TARGET_NUCLEO_F303RE/PeripheralPinMaps.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TARGET_NUCLEO_F411RE/PeripheralPinMaps.h
  targets/TARGET_STM/TARGET_STM32L0/TARGET_NUCLEO_L073RZ/PeripheralPinMaps.h
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12142 Thread: remove methods deprecated in 5.10
  TESTS/mbedmicro-rtos-mbed/signals/main.cpp
  UNITTESTS/stubs/Thread_stub.cpp
  rtos/Thread.h
  rtos/source/Thread.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12353 M2351: Support IAR
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/device/TOOLCHAIN_IAR/M2351.icf
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_S/device/TOOLCHAIN_IAR/M2351.icf
  targets/TARGET_NUVOTON/TARGET_M2351/device/partition_M2351_mem.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/partition_M2351_mem.icf
  targets/TARGET_NUVOTON/TARGET_M2351/device/partition_M2351_mem.icf.h
  targets/TARGET_NUVOTON/TARGET_M2351/device/startup_M2351.c
  targets/TARGET_NUVOTON/TARGET_M2351/rtc_api.c
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12312 Fix to sending IPV6 UPD packet fails IPv6 enabled in SoftAP intf
  features/lwipstack/LWIPInterface.cpp
  features/lwipstack/LWIPStack.h
  features/netsocket/OnboardNetworkStack.h
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.cpp
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSoftAPInterface.cpp
Labels: devices: cypress, ready for merge, release-version: 5.15.1

#12345 USBMSD; NFCEEPROM; mbed_compat: Fix compiler warnings
  drivers/source/usb/USBMSD.cpp
  features/nfc/source/nfc/NFCEEPROM.cpp
  hal/mbed_compat.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12329 AT_CellularStack: crash during TCP test
  features/cellular/framework/AT/AT_CellularStack.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12355 HANI_IOT: add new target board support
  components/storage/blockdevice/COMPONENT_SPIF/mbed_lib.json
  features/storage/kvstore/conf/global/mbed_lib.json
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_HANI_IOT/PeripheralNames.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_HANI_IOT/PeripheralPinMaps.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_HANI_IOT/PeripheralPins.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_HANI_IOT/PinNames.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_HANI_IOT/clock_config.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_HANI_IOT/clock_config.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_HANI_IOT/device.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_HANI_IOT/mbed_overrides.c
  targets/targets.json
Labels: ready for merge, release-version: 5.15.1, scope: new-target

#12356 Fix NRF51, NRF52 gpio_irq_init() function
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF51/gpio_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/gpio_api.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12357 TARGET_STM32F1: don't set ADC common register when ADC doesn't support it
  targets/TARGET_STM/TARGET_STM32F1/analogin_device.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12317 MXRT1050 Flash support
  components/storage/blockdevice/COMPONENT_FLASHIAP/mbed_lib.json
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/flash_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/objects.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/device.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/flash_defines.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_ARM_STD/MIMXRT1052xxxxx.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_GCC_ARM/MIMXRT1052xxxxx.ld
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_IAR/MIMXRT1052xxxxx.icf
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_flexspi.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_flexspi.h
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12363 Mergify: fix release version label
  .mergify.yml
Labels: release-version: 6.0.0-alpha-2

#12362 TARGET_STM: L0 CUBE SPI async mode send next byte after previous one is read
  targets/TARGET_STM/TARGET_STM32L0/device/stm32l0xx_hal_spi.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12369 LPC1768: Fix ARM toolchain baremetal by defining 2 memory region
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_ARM_STD/LPC1768.sct
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12366 M2351: Support GCC
  targets/TARGET_NUVOTON/TARGET_M2351/device/startup_M2351.c
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12334 Update cellular drivers/tests for UBLOX_C030_R412M
  TESTS/netsocket/dns/main.cpp
  TESTS/netsocket/udp/udpsocket_echotest.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/PPP/UBLOX_PPP.cpp
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F437xG/TARGET_UBLOX_C030/ONBOARD_UBLOX.cpp
  tools/test_configs/CellularInterface.json
Labels: release-version: 6.0.0-alpha-2

#12370 OKDO_ODIN_W2: Reenable lp-ticker and BLE
  targets/targets.json
Labels: ready for merge, release-version: 5.15.1

#11874 ARMC6: Add a build profile extension with the link-time optimizer enabled
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/ipc/tfm_spm.c
  components/TARGET_PSA/TARGET_TFM/COMPONENT_SPE/secure_fw/core/tfm_handler.c
  platform/source/mbed_alloc_wrappers.cpp
  platform/source/mbed_retarget.cpp
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TARGET_EV_COG_AD3029LZ/device/startup_ADuCM3029.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TARGET_EV_COG_AD4050LZ/device/startup_ADuCM4050.c
  targets/TARGET_NUVOTON/TARGET_M2351/device/startup_M2351.c
  targets/TARGET_NUVOTON/TARGET_M251/device/startup_M251.c
  targets/TARGET_NUVOTON/TARGET_M261/device/startup_M261.c
  targets/TARGET_NUVOTON/TARGET_M451/device/startup_M451Series.c
  targets/TARGET_NUVOTON/TARGET_M480/device/startup_M480.c
  targets/TARGET_NUVOTON/TARGET_NANO100/device/startup_Nano100Series.c
  targets/TARGET_NUVOTON/TARGET_NUC472/device/startup_NUC472_442.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/xip/evkbimxrt1050_flexspi_nor_config.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_flexspi_nor_boot.c
  targets/TARGET_STM/rtc_api.c
  targets/TARGET_TI/TARGET_CC32XX/TARGET_CC3220SF/TARGET_CC3220SF_LAUNCHXL/CC3220SF_LAUNCHXL.c
  targets/TARGET_TI/TARGET_MSP432/TARGET_MSP432P401R/device/startup_msp432p401r.c
  tools/profiles/extensions/lto.json
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12251 Cellular: Remove friend definitions from cellular state machine
  features/cellular/framework/device/CellularStateMachine.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-alpha-2

#12320 ONME-3433 ESP8266 driver support for UDP get - modified ESP8266 drive…
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12359 MXRT1050: Add bootloader support
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_ARM_STD/MIMXRT1052xxxxx.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_GCC_ARM/MIMXRT1052xxxxx.ld
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_IAR/MIMXRT1052xxxxx.icf
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-alpha-1

#12270 BUGFIX: SFDP Sector Map Table Parameter ID LSB is 0x81
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.h
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.h
  drivers/internal/SFDP.h
  drivers/source/SFDP.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12377 Update psoc6cm0p asset to 1.1.0
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_BLESS/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_BLESS/psoc6_cm0p_bless.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_01_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_02_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_03_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_01_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_02_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_03_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/version.xml
Labels: Release review required, ready for merge

#12293 Cellular: Remove API's empty default implemetations
  UNITTESTS/features/cellular/framework/device/cellularcontext/cellularcontexttest.cpp
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  UNITTESTS/stubs/CellularDevice_stub.cpp
  UNITTESTS/target_h/myCellularContext.h
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/device/CellularDevice.cpp
  features/netsocket/CellularInterface.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-alpha-2

#12364 MIMXRT1050: Update for deep sleep latency
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/lpm.c
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12287 Fix unittests on windows(mingw)
  UNITTESTS/CMakeLists.txt
  UNITTESTS/target_h/rtos/Semaphore.h
  events/internal/equeue_platform.h
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12305 Cellular: Remove support for multiple ATHandlers
  UNITTESTS/features/cellular/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  UNITTESTS/features/cellular/framework/AT/at_cellulardevice/at_cellulardevicetest.cpp
  UNITTESTS/features/cellular/framework/device/athandler/athandlertest.cpp
  UNITTESTS/features/cellular/framework/device/cellularcontext/cellularcontexttest.cpp
  UNITTESTS/stubs/ATHandler_stub.cpp
  UNITTESTS/stubs/ATHandler_stub.h
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  UNITTESTS/stubs/AT_CellularDevice_stub.cpp
  UNITTESTS/stubs/AT_CellularInformation_stub.cpp
  UNITTESTS/stubs/AT_CellularNetwork_stub.cpp
  UNITTESTS/stubs/AT_CellularSMS_stub.cpp
  UNITTESTS/stubs/CellularContext_stub.cpp
  UNITTESTS/stubs/CellularDevice_stub.cpp
  UNITTESTS/target_h/myCellularContext.h
  UNITTESTS/target_h/myCellularDevice.h
  components/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.cpp
  features/cellular/framework/API/ATHandler.h
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularDevice.cpp
  features/cellular/framework/AT/AT_CellularDevice.h
  features/cellular/framework/AT/AT_CellularInformation.cpp
  features/cellular/framework/AT/AT_CellularInformation.h
  features/cellular/framework/AT/AT_CellularNetwork.cpp
  features/cellular/framework/AT/AT_CellularNetwork.h
  features/cellular/framework/AT/AT_CellularSMS.cpp
  features/cellular/framework/AT/AT_CellularSMS.h
  features/cellular/framework/device/ATHandler.cpp
  features/cellular/framework/device/CellularContext.cpp
  features/cellular/framework/device/CellularDevice.cpp
  features/cellular/framework/targets/GEMALTO/CINTERION/GEMALTO_CINTERION_CellularContext.cpp
  features/cellular/framework/targets/QUECTEL/BC95/QUECTEL_BC95.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96.cpp
  features/cellular/framework/targets/QUECTEL/EC2X/QUECTEL_EC2X.cpp
  features/cellular/framework/targets/QUECTEL/M26/QUECTEL_M26.cpp
  features/cellular/framework/targets/RiotMicro/AT/RM1000_AT.cpp
  features/cellular/framework/targets/TELIT/HE910/TELIT_HE910.cpp
  features/cellular/framework/targets/TELIT/ME910/TELIT_ME910.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT.cpp
  features/cellular/framework/targets/UBLOX/N2XX/UBLOX_N2XX.cpp
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_AGORA/ONBOARD_TELIT_ME910.cpp
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-alpha-2

#12397 Testing: Fix buffer overflow in ATHandler_read_bytes UT test
  UNITTESTS/features/cellular/framework/device/athandler/athandlertest.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12382 Fix BufferedSerial visibility of private base class enum enumerators
  drivers/BufferedSerial.h
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12389 Update InterruptIn.h
  drivers/InterruptIn.h
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12152 Updated 113 targets with missing detect_codes
  targets/targets.json
Labels: Priority-High, ready for merge

#12386 TEST: fix a bug in ATCmdParser test
  UNITTESTS/platform/ATCmdParser/test_ATCmdParser.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12383 Fix thread_sleep_for with zero wake_delay
  platform/source/mbed_os_timer.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12341 STM32L4: Fix the UART RX & TX data reg bitmasks
  targets/TARGET_STM/TARGET_STM32F0/serial_device.c
  targets/TARGET_STM/TARGET_STM32F3/serial_device.c
  targets/TARGET_STM/TARGET_STM32F7/serial_device.c
  targets/TARGET_STM/TARGET_STM32G0/serial_device.c
  targets/TARGET_STM/TARGET_STM32H7/serial_device.c
  targets/TARGET_STM/TARGET_STM32L0/serial_device.c
  targets/TARGET_STM/TARGET_STM32L4/serial_device.c
  targets/TARGET_STM/TARGET_STM32WB/serial_device.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12394 Fix SDIO communication issue on Cypress 1M boards and other minor fixes
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.cpp
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/SDIO_HOST/SDIO_HOST.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/SDIO_HOST/SDIO_HOST.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/SDIO_HOST/SDIO_HOST_cfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/SDIO_HOST/SDIO_HOST_cfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/SDIO_HOST/SDIO_HOST.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/SDIO_HOST/SDIO_HOST.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/SDIO_HOST/SDIO_HOST_cfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW943012P6EVB_01/SDIO_HOST/SDIO_HOST_cfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/SDIO_HOST/SDIO_HOST.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/SDIO_HOST/SDIO_HOST.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/SDIO_HOST/SDIO_HOST_cfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/SDIO_HOST/SDIO_HOST_cfg.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/SDIO_HOST/SDIO_HOST.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/SDIO_HOST/SDIO_HOST.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/SDIO_HOST/SDIO_HOST_cfg.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/SDIO_HOST/SDIO_HOST_cfg.h
  targets/targets.json
Labels: devices: cypress, ready for merge, release-version: 6.0.0-alpha-2

#12399 Cellular: Delete created context if activation fails
  features/cellular/framework/AT/AT_CellularContext.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12349 Nanostack: Update Wi-SUN configuration
  features/nanostack/mbed-mesh-api/mbed_lib.json
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12368 Fix NRF52840_DK UART driver and adapt FPGA test
  TESTS/mbed_hal_fpga_ci_test_shield/uart/main.cpp
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/serial_api.c
  targets/targets.json
Labels: ready for merge

#12395 Fix I2CEEBlockdevice
  components/storage/blockdevice/COMPONENT_I2CEE/I2CEEBlockDevice.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12402 Fix dependency (`requires` attribute) issue
  TESTS/configs/baremetal.json
Labels: ready for merge, release-version: feature branch

#12393 Fix Musca-A1 gcc linker
  targets/TARGET_ARM_SSG/TARGET_MUSCA_A1/TARGET_MUSCA_A1_S/device/TOOLCHAIN_GCC_ARM/musca_s.ld
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12379 Add STDIO UART as restricted for FPGA testing for all targets and support for restricting GPIO
  components/testing/COMPONENT_FPGA_CI_TEST_SHIELD/test_utils.h
  hal/mbed_pinmap_default.cpp
  hal/pinmap.h
  targets/TARGET_NUVOTON/TARGET_M2351/pinmap.c
  targets/TARGET_NUVOTON/TARGET_M251/pinmap.c
  targets/TARGET_NUVOTON/TARGET_M261/pinmap.c
  targets/TARGET_NUVOTON/TARGET_M451/pinmap.c
  targets/TARGET_NUVOTON/TARGET_M480/pinmap.c
  targets/TARGET_NUVOTON/TARGET_NANO100/pinmap.c
  targets/TARGET_NUVOTON/TARGET_NUC472/pinmap.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12342 LPC55S69: Fix UART & GPIO HAL to pass FPGA CI test shield tests
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/serial_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_LPCXpresso/PeripheralPins.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12380 DISCO_L475VG_IOT01A: Add a list of restricted GPIO pins for testing
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/TARGET_DISCO_L475VG_IOT01A/PeripheralPins.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12400 Add an exception for ARMC5 toolchain build
  tools/build_api.py
  tools/toolchains/arm.py
Labels: release-version: 6.0.0-alpha-2

#12391 mergify: CI only if PR is without conflicts
  .mergify.yml
Labels: release-version: 6.0.0-alpha-2

#12392 Fix psa_key_management_operations
  components/TARGET_PSA/services/crypto/COMPONENT_SPE/psa_crypto_partition.c
Labels: release-version: 6.0.0-alpha-2

#12401 Remove float symbols from apps that use the NFCController class
  features/nfc/source/nfc/NFCController.cpp
Labels: release-version: 6.0.0-alpha-2

#12378 TEST: Refactor mbedmicro tests to use utest framework
  TESTS/mbedmicro-mbed/call_before_main/main.cpp
  TESTS/mbedmicro-mbed/cpp/main.cpp
  TESTS/mbedmicro-mbed/div/main.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12403 FPGA: Enlarge timeout with mbed_hal_fpga_ci_test_shield-i2c
  TESTS/mbed_hal_fpga_ci_test_shield/i2c/main.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12405 EthernetInterface fix detecting change of connection status on ARCH_MAX
  features/netsocket/emac-drivers/TARGET_STM/mbed_lib.json
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12407 Disable restricted uart peripheral for NRF52840
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/PeripheralPins.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12408 LPC408X: Delete the ethernet_api.c files
  targets/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088/ethernet_api.c
  targets/TARGET_NXP/TARGET_LPC408X/TARGET_LPC4088_DM/ethernet_api.c
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12409 FIX: LPUART clock source selection should be left to serial driver
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/system_clock.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12411 add FLASHIAP in targets.json for KVStore used in PDMC
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12419 Fix #12290: crash_log_parser on py3
  tools/debug_tools/crash_log_parser/crash_log_parser.py
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12339 Cellular : add modem version in mbed trace
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/device/CellularStateMachine.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularInformation.cpp
  features/cellular/framework/targets/QUECTEL/BG96/QUECTEL_BG96_CellularInformation.h
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12424 Nuvoton: Fix GPIO IRQ and RTC
  targets/TARGET_NUVOTON/TARGET_M2351/PeripheralPins.c
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NPSA_NS/TARGET_NU_PREBUILD_SECURE/NuMaker-mbed-TZ-secure-example.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NS/TARGET_NU_PREBUILD_SECURE/crypto_access_control.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NS/TARGET_NU_PREBUILD_SECURE/spm_client.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NS/TARGET_NU_PREBUILD_SECURE/spm_server.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NS/TARGET_NU_PREBUILD_SECURE/spm_smoke.hex
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_NU_PFM_M2351_NS/TARGET_NU_PREBUILD_SECURE/tfm.hex
  targets/TARGET_NUVOTON/TARGET_M2351/crypto/crypto-misc.h
  targets/TARGET_NUVOTON/TARGET_M2351/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M2351/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_M251/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M251/objects.h
  targets/TARGET_NUVOTON/TARGET_M251/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_M261/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M261/objects.h
  targets/TARGET_NUVOTON/TARGET_M261/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_M451/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M451/objects.h
  targets/TARGET_NUVOTON/TARGET_M451/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_M480/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M480/objects.h
  targets/TARGET_NUVOTON/TARGET_M480/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/objects.h
  targets/TARGET_NUVOTON/TARGET_NANO100/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/objects.h
  targets/TARGET_NUVOTON/TARGET_NUC472/rtc_api.c
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12166 NRF52840_DK: Fix baremetal linker error
  TESTS/configs/baremetal.json
  features/cryptocell/FEATURE_CRYPTOCELL310/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/objects.h
Labels: release-version: 6.0.0-alpha-2

#12398 Add BlockDevice unittests and fix issues they revealed
  UNITTESTS/features/storage/blockdevice/BufferedBlockDevice/test_BufferedBlockDevice.cpp
  UNITTESTS/features/storage/blockdevice/BufferedBlockDevice/unittest.cmake
  UNITTESTS/features/storage/blockdevice/ChainingBlockDevice/test_ChainingBlockDevice.cpp
  UNITTESTS/features/storage/blockdevice/ChainingBlockDevice/unittest.cmake
  UNITTESTS/features/storage/blockdevice/ExhaustibleBlockDevice/test_ExhaustibleBlockDevice.cpp
  UNITTESTS/features/storage/blockdevice/ExhaustibleBlockDevice/unittest.cmake
  UNITTESTS/features/storage/blockdevice/FlashSimBlockDevice/test_FlashSimBlockDevice.cpp
  UNITTESTS/features/storage/blockdevice/FlashSimBlockDevice/unittest.cmake
  UNITTESTS/features/storage/blockdevice/MBRBlockDevice/test_MBRBlockDevice.cpp
  UNITTESTS/features/storage/blockdevice/MBRBlockDevice/unittest.cmake
  UNITTESTS/features/storage/blockdevice/ObservingBlockDevice/test_ObservingBlockDevice.cpp
  UNITTESTS/features/storage/blockdevice/ObservingBlockDevice/unittest.cmake
  UNITTESTS/features/storage/blockdevice/ProfilingBlockDevice/test_ProfilingBlockDevice.cpp
  UNITTESTS/features/storage/blockdevice/ProfilingBlockDevice/unittest.cmake
  UNITTESTS/features/storage/blockdevice/ReadOnlyBlockDevice/test_ReadOnlyBlockDevice.cpp
  UNITTESTS/features/storage/blockdevice/ReadOnlyBlockDevice/unittest.cmake
  UNITTESTS/moduletests/storage/blockdevice/BufferedBlockDevice/moduletest.cpp
  UNITTESTS/stubs/BlockDevice_mock.h
  features/storage/blockdevice/BufferedBlockDevice.cpp
  features/storage/blockdevice/ChainingBlockDevice.cpp
  features/storage/blockdevice/ExhaustibleBlockDevice.cpp
  features/storage/blockdevice/ExhaustibleBlockDevice.h
  features/storage/blockdevice/FlashSimBlockDevice.cpp
  features/storage/blockdevice/MBRBlockDevice.cpp
  features/storage/blockdevice/ReadOnlyBlockDevice.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12396 PDP Type needs to be IPV4V6
  features/cellular/framework/targets/MultiTech/DragonflyNano/PPP/SARA4_PPP.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-2

#12338 STM32L5 : add DISCO-L562QE board support
  components/cellular/COMPONENT_STMOD_CELLULAR/README.md
  components/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.cpp
  components/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.h
  components/cellular/COMPONENT_STMOD_CELLULAR/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L562xx/TARGET_DISCO_L562QE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L562xx/TARGET_DISCO_L562QE/PinNames.h
  targets/TARGET_STM/TARGET_STM32L5/objects.h
  targets/TARGET_STM/qspi_api.c
  targets/targets.json
Labels: release-version: 6.0.0-alpha-2, scope: new-target

#11856 GCC: Add a build profile extension with the link-time optimizer enabled
  tools/profiles/debug.json
  tools/profiles/develop.json
  tools/profiles/extensions/lto.json
  tools/profiles/release.json
  tools/toolchains/gcc.py
Labels: ready for merge, release-version: 6.0.0-beta-1

#12415 STM32H7 : add readme file for dual core use
  features/netsocket/emac-drivers/TARGET_STM/TARGET_STM32H7/TARGET_DISCO_H747I/stm32h7_eth_init.c
  targets/TARGET_STM/TARGET_STM32H7/README.md
Labels: ready for merge, release-version: 6.0.0-beta-1

#12427 Minor optimisation to mcr20a-rf-driver code
  components/802.15.4_RF/mcr20a-rf-driver/source/MCR20Drv.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12431 Nordic NRF52 GPIO API: Fix non-deterministic failure to configure interrupt handling
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/gpio_api.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12462 Fix static ram memory statistics for arm compiler
  tools/memap.py
Labels: ready for merge, release-version: 6.0.0-beta-1

#12441 CAN: fix length calculation (fixes #12311)
  drivers/CAN.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12443 Fixed typo: 'lenght' in coap_service_api.h
  features/nanostack/coap-service/coap-service/coap_service_api.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12442 Fixed typo: 'lenght' in minimal-printf
  platform/source/minimal-printf/mbed_printf_implementation.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12447 fix targets device_name with nrf51822 32K SoC
  targets/targets.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12445 Fixed typo: 'lenght' in ip6string.h
  features/frameworks/nanostack-libservice/mbed-client-libservice/ip6string.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12444 Fixed typo: 'lenght' in ns_crc.h
  features/nanostack/sal-stack-nanostack/source/Service_Libs/utils/ns_crc.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12449 Add missing pins def for ARDUINO_NANO33BLE
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_ARDUINO_NANO33BLE/PinNames.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12453 STM32 TRACE_GROUP update
  components/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.cpp
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/HCIDriver.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12454 Nuvoton: Optimize spi_master_write(...) in case of no SPI MISO pin
  targets/TARGET_NUVOTON/TARGET_M2351/spi_api.c
  targets/TARGET_NUVOTON/TARGET_M251/spi_api.c
  targets/TARGET_NUVOTON/TARGET_M261/spi_api.c
  targets/TARGET_NUVOTON/TARGET_M451/spi_api.c
  targets/TARGET_NUVOTON/TARGET_M480/spi_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/spi_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/spi_api.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12318 SFDP: Move Sector Map Parameter Table parsing under SFDP module
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.h
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.h
  drivers/internal/SFDP.h
  drivers/source/SFDP.cpp
  tools/test_configs/SPIFBlockDeviceAndHeapBlockDevice.json
Labels: ready for merge, release-version: 6.0.0-beta-1

#12438 Fix CY8CPROTO_062_4343W baremetal build
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/mbed_lib.json
  targets/TARGET_Cypress/TARGET_PSOC6/common/network/cy_network_buffer.c
  targets/TARGET_Cypress/TARGET_PSOC6/common/network/cy_network_buffer.h
  targets/TARGET_Cypress/TARGET_PSOC6/common/network/cybsp_wifi.c
  targets/TARGET_Cypress/TARGET_PSOC6/common/network/cybsp_wifi.h
  targets/TARGET_Cypress/TARGET_PSOC6/common/network/mbed_lib.json
  targets/TARGET_Cypress/TARGET_PSOC6/mbed_overrides.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/rtos/mbed_lib.json
Labels: release-version: 6.0.0-beta-1

#12473 Fix Freescale MCUXpresso AnalogOut
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/analogout_api.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12206 Kvstore tests
  UNITTESTS/moduletests/storage/kvstore/TDBStore/moduletest.cpp
  UNITTESTS/moduletests/storage/kvstore/TDBStore/unittest.cmake
  UNITTESTS/stubs/EmulatedSD.cpp
  UNITTESTS/stubs/EmulatedSD.h
  features/storage/TESTS/blockdevice/general_block_device/main.cpp
Labels: release-version: 6.0.0-beta-1

#12446 Add Eight-Bit-Addressing mode to I2CEEBlockDevice.
  components/storage/blockdevice/COMPONENT_I2CEE/I2CEEBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_I2CEE/I2CEEBlockDevice.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12384 STM32WB : update BLE part with better support
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_STM32WB/HCIDriver.cpp
  targets/TARGET_STM/README.md
  targets/TARGET_STM/TARGET_STM32WB/README.md
  targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/stm32_lpm_if.c
  targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/stm32_lpm_if.h
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xx/TARGET_NUCLEO_WB55RG/system_clock.c
  targets/TARGET_STM/TARGET_STM32WB/stm32wb_ble_update.jpg
  targets/TARGET_STM/TARGET_STM32WB/wb_sleep.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#11942 IPCore String-based API removal
  UNITTESTS/features/netsocket/PPPInterface/test_PPPInterface.cpp
  UNITTESTS/features/netsocket/PPPInterface/unittest.cmake
  UNITTESTS/stubs/AT_CellularContext_stub.cpp
  UNITTESTS/stubs/AT_CellularStack_stub.cpp
  UNITTESTS/stubs/NetworkInterface_stub.cpp
  UNITTESTS/stubs/NetworkStack_stub.cpp
  UNITTESTS/stubs/NetworkStack_stub.h
  UNITTESTS/stubs/OnboardNetworkStack_mock.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
  components/wifi/esp8266-driver/ESP8266Interface.h
  features/cellular/framework/API/CellularContext.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_CellularStack.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularContext.h
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  features/cellular/framework/targets/UBLOX/AT/UBLOX_AT_CellularStack.h
  features/lwipstack/LWIPInterface.cpp
  features/lwipstack/LWIPStack.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/mbed-mesh-api/source/LoWPANNDInterface.cpp
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/nanostack-interface/Nanostack.cpp
  features/nanostack/nanostack-interface/Nanostack.h
  features/netsocket/CellularInterface.h
  features/netsocket/DTLSSocket.cpp
  features/netsocket/DTLSSocket.h
  features/netsocket/EMACInterface.cpp
  features/netsocket/EMACInterface.h
  features/netsocket/InternetDatagramSocket.cpp
  features/netsocket/InternetDatagramSocket.h
  features/netsocket/InternetSocket.cpp
  features/netsocket/InternetSocket.h
  features/netsocket/L3IPInterface.cpp
  features/netsocket/L3IPInterface.h
  features/netsocket/NetworkInterface.cpp
  features/netsocket/NetworkInterface.h
  features/netsocket/NetworkStack.cpp
  features/netsocket/NetworkStack.h
  features/netsocket/OnboardNetworkStack.h
  features/netsocket/PPPInterface.cpp
  features/netsocket/PPPInterface.h
  features/netsocket/TCPSocket.cpp
  features/netsocket/TCPSocket.h
  features/netsocket/TLSSocket.cpp
  features/netsocket/TLSSocket.h
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/CyDhcpServer.cpp
  features/netsocket/ppp/ppp_nsapi.cpp
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.a
  targets/TARGET_WICED/TOOLCHAIN_IAR/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.a
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12484 TDBStore magic number if endian sensitive fix comment
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12477 HAL: Add a get_capabilities() function to GPIO API
  TESTS/mbed_hal_fpga_ci_test_shield/gpio/gpio_fpga_test.h
  TESTS/mbed_hal_fpga_ci_test_shield/gpio/main.cpp
  hal/gpio_api.h
  hal/mbed_gpio.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralNames.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralPinMaps.h
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PeripheralPins.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/PeripheralPins.h
  targets/TARGET_NUVOTON/TARGET_M451/gpio_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/gpio_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/gpio_api.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12492 Update psoc6cm0p asset to version 1.1.1.
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_BLESS/psoc6_cm0p_bless.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_01_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_02_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_CRYPTO/psoc6_03_cm0p_crypto.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_01_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_02_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/COMPONENT_CM0P_SLEEP/psoc6_03_cm0p_sleep.c
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/README.md
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6cm0p/version.xml
Labels: devices: cypress, ready for merge, release-version: 6.0.0-beta-1

#12496 EFM32: fix mbed_hal-pinmap test
  targets/TARGET_Silicon_Labs/TARGET_EFM32/common/CommonPinNames.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12491 Fixed error of function 'mac_fcf_lenght'
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_header_helper_functions.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12478 M2351: Fix some minor issues
  targets/TARGET_NUVOTON/TARGET_M2351/device/startup_M2351.c
  targets/TARGET_NUVOTON/TARGET_M2351/device/system_M2351.c
  targets/TARGET_NUVOTON/TARGET_M2351/rtc_api.c
Labels: ready for merge, release-version: 6.0.0-beta-1

#12358 FIX: add cbor module in the requirement.txt
  requirements.txt
Labels: release-version: 6.0.0-beta-1

#12490 Fixed error of structure mlme_key_descriptor_t
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_security_mib.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_security_mib.h
Labels: release-version: 6.0.0-beta-1

#12437 travis: add PR license check for missing/not-valid license files
  .travis.yml
  tools/test/travis-ci/scancode-evaluate.py
Labels: ready for merge, release-version: 6.0.0-beta-1

#12421 Cypress Targets Reorganization
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM0P/TOOLCHAIN_ARM/cy8c6xxa_cm0plus.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM0P/TOOLCHAIN_ARM/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/cy8c6xxa_cm0plus.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM0P/TOOLCHAIN_IAR/cy8c6xxa_cm0plus.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM0P/TOOLCHAIN_IAR/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM0P/system_psoc6_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM4/TOOLCHAIN_ARM/cy8c6xxa_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM4/TOOLCHAIN_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/cy8c6xxa_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM4/TOOLCHAIN_IAR/cy8c6xxa_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM4/TOOLCHAIN_IAR/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/COMPONENT_CM4/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/PeripheralNames.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM0P/TOOLCHAIN_ARM/cy8c6xx5_cm0plus.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM0P/TOOLCHAIN_ARM/startup_psoc6_03_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/cy8c6xx5_cm0plus.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/startup_psoc6_03_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM0P/TOOLCHAIN_IAR/cy8c6xx5_cm0plus.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM0P/TOOLCHAIN_IAR/startup_psoc6_03_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM0P/system_psoc6_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM4/TOOLCHAIN_ARM/cy8c6xx5_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM4/TOOLCHAIN_ARM/startup_psoc6_03_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/cy8c6xx5_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/startup_psoc6_03_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM4/TOOLCHAIN_IAR/cy8c6xx5_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM4/TOOLCHAIN_IAR/startup_psoc6_03_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/COMPONENT_CM4/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/device/system_psoc6.h
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/PeripheralPins.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM0P/TOOLCHAIN_ARM/cy8c6xxa_cm0plus.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM0P/TOOLCHAIN_ARM/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/cy8c6xxa_cm0plus.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM0P/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM0P/TOOLCHAIN_IAR/cy8c6xxa_cm0plus.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM0P/TOOLCHAIN_IAR/startup_psoc6_02_cm0plus.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM0P/system_psoc6_cm0plus.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM4/TOOLCHAIN_ARM/cy8c6xxa_cm4_dual.sct
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM4/TOOLCHAIN_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/cy8c6xxa_cm4_dual.ld
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM4/TOOLCHAIN_GCC_ARM/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM4/TOOLCHAIN_IAR/cy8c6xxa_cm4_dual.icf
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM4/TOOLCHAIN_IAR/startup_psoc6_02_cm4.S
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/COMPONENT_CM4/system_psoc6_cm4.c
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/device/system_psoc6.h
  targets/targets.json
Labels: devices: cypress

#12505 travis: ignore grep return value for scancode
  .travis.yml
Labels: needs: CI

#12502 Fixed macro error
  TESTS/network/emac/emac_util.cpp
  TESTS/network/emac/emac_util.h
Labels: release-version: 6.0.0-beta-1

#12426 SFDP: consolidation of SFDP parsing [2/n]
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.h
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.h
  drivers/internal/SFDP.h
  drivers/source/SFDP.cpp
Labels: release-version: 6.0.0-beta-1

#12475 Proposal to remove SPIFReducedBlockDevice
  UNITTESTS/empty_baseline/unittest.cmake
  components/storage/blockdevice/COMPONENT_RSPIF/SPIFReducedBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_RSPIF/SPIFReducedBlockDevice.h
  components/storage/blockdevice/COMPONENT_RSPIF/mbed_lib.json
  docs/design-documents/features/storage/BlockDevices/get_type_method.md
  features/storage/system_storage/SystemStorage.cpp
  tools/test_configs/RSPIFBlockDeviceAndHeapBlockDevice.json
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12440 Implement reset_reason api for cypress targets
  targets/TARGET_Cypress/TARGET_PSOC6/cy_reset_reason_api.c
  targets/targets.json
Labels: devices: cypress, ready for merge, release-version: 6.0.0-beta-1

#12495 C++11-ify virtualisation in FileHandle + Serials
  drivers/BufferedSerial.h
  drivers/SerialWireOutput.h
  drivers/UnbufferedSerial.h
  drivers/source/SerialWireOutput.cpp
  platform/FileHandle.h
Labels: release-version: 6.0.0-beta-1

#12501 Remove the deprecated the InterruptManager APIs
  drivers/InterruptManager.h
  drivers/source/InterruptManager.cpp
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12420 Remove the deprecated CAN APIs.
  drivers/CAN.h
Labels: BREAKING-CHANGE

#12514 mergify: add "mergify skip" label
  .mergify.yml
Labels: release-version: 6.0.0-beta-1

#12385 DeviceKey Root of Trust generation refactored.
  TESTS/psa/its_ps/main.cpp
  features/device_key/TESTS/device_key/functionality/main.cpp
  features/device_key/source/DeviceKey.cpp
  features/device_key/source/DeviceKey.h
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_2/main.cpp
  features/storage/TESTS/kvstore/securestore_whitebox/main.cpp
  features/storage/TESTS/kvstore/static_tests/main.cpp
Labels: ready for merge, release-version: 6.0.0-alpha-1

#12509 EFM32: RTCC bugfix for #12374
  targets/TARGET_Silicon_Labs/TARGET_EFM32/rtcc.c
Labels: release-version: 6.0.0-beta-1

#12500 Remove the deprecated ethernet APIs
  drivers/Ethernet.h
  drivers/source/Ethernet.cpp
  mbed.h
Labels: BREAKING-CHANGE, release-version: 6.0.0-beta-1

#12520 Fix initialization order for I2CEEBlockDevice
  components/storage/blockdevice/COMPONENT_I2CEE/I2CEEBlockDevice.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12519 tests-mbed_hal-sleep_manager: fix counter wraparound handling
  TESTS/mbed_hal/sleep_manager/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12488 C++11-ify virtualisation in Nanostack classes
  features/nanostack/mbed-mesh-api/mbed-mesh-api/LoWPANNDInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEMACInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackPPPInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackRfInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/ThreadInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/LoWPANNDInterface.cpp
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEMACInterface.cpp
  features/nanostack/mbed-mesh-api/source/NanostackPPPInterface.cpp
  features/nanostack/mbed-mesh-api/source/ThreadInterface.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/mbed-mesh-api/source/include/NanostackMemoryManager.h
  features/nanostack/nanostack-interface/Nanostack.h
  features/nanostack/nanostack-interface/NanostackLockGuard.h
  features/nanostack/nanostack-interface/NanostackMACPhy.h
  features/nanostack/nanostack-interface/NanostackPPPPhy.h
  features/nanostack/nanostack-interface/NanostackPhy.h
  features/nanostack/nanostack-interface/NanostackRfPhy.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12498 TEST: update usb tests and guard them with macro
  TESTS/usb_device/README.md
  TESTS/usb_device/basic/USBEndpointTester.cpp
  TESTS/usb_device/basic/USBTester.cpp
  TESTS/usb_device/basic/main.cpp
  TESTS/usb_device/hid/main.cpp
  TESTS/usb_device/msd/main.cpp
  TESTS/usb_device/serial/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12451 STM32 : enable MBED trace for QSPI
  targets/TARGET_STM/qspi_api.c
Labels: release-version: 6.0.0-beta-1

#12518 Remove InterruptIn deprecated APIs
  drivers/InterruptIn.h
Labels: BREAKING-CHANGE, ready for merge, release-version: 6.0.0-beta-1

#12450 SFDP: consolidation of SFDP parsing [3/n]
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_QSPIF/QSPIFBlockDevice.h
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.cpp
  components/storage/blockdevice/COMPONENT_SPIF/SPIFBlockDevice.h
  drivers/internal/SFDP.h
  drivers/source/SFDP.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12457 Update STM32 EMAC driver - limit RX frame length
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
Labels: Release review required, ready for merge

#12466 MBED_STACK_STATS_ENABLED : Add stack_name information in greentea metrics
  features/frameworks/greentea-client/source/greentea_metrics.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12527 Remove the deprecated ATCmdParser APIs.
  platform/ATCmdParser.h
Labels: ready for merge, release-version: 6.0.0-beta-1

#12525 Remove the deprecated Ticker APIs
  drivers/Ticker.h
  features/frameworks/utest/TESTS/unit_tests/case_control_async/main.cpp
Labels: ready for merge, release-version: 6.0.0-beta-1

#12516 [feature-wisun] Update STM32 EMAC driver - limit RX frame length
  features/netsocket/emac-drivers/TARGET_STM/stm32xx_emac.cpp
Labels: needs: work, release-version: feature branch

#12530 Remove reset reason from Future Sequana targets.
  targets/targets.json
Labels: devices: cypress, release-version: 6.0.0-beta-1
