Repository ARMmbed/mbed-os, pull requests merged in 2020-11, with the labels that each got.

#13834 CMake: Activate ccache
  .travis.yml
  tools/cmake/app.cmake
Labels: ready for merge, release-version: feature branch

#13709 mbed-os-5.15: Nuvoton: Fix NuMaker I2C timeout
  targets/TARGET_NUVOTON/TARGET_M2351/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M2354/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M251/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M261/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M451/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_M480/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/i2c_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/i2c_api.c
Labels: release-version: 5.15.6

#13822 BLE fix periodic advertising list function parameter checking
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
Labels: ready for merge, release-type: patch

#13753 Remove Unneeded nordic-bsp Folder from Cordio
  connectivity/FEATURE_BLE/libraries/TARGET_CORDIO_LL/stack/thirdparty/.mbedignore
Labels: ready for merge, release-type: patch

#13817 STM32: define RCC_LSE_BYPASS to allow using PC_15 as gpio
  targets/TARGET_STM/lp_ticker.c
  targets/TARGET_STM/rtc_api.c
Labels: ready for merge, release-type: patch

#13835 CMake: fix targets linker script/drivers inclusion
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F3/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303x8/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303x8/device/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F3/device/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/CMSIS/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/Legacy/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/STM32Cube_FW/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/STM32Cube_FW/STM32L4xx_HAL_Driver/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/STM32Cube_FW/STM32L4xx_HAL_Driver/Legacy/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/CMakeLists.txt
Labels: needs: work, release-version: feature branch

#13843 Fix linking issue #13793 when using -O0 compiler optimization in ARMC…
  connectivity/drivers/cellular/RiotMicro/AT/RM1000_AT_CellularStack.cpp
  connectivity/drivers/cellular/UBLOX/AT/UBLOX_AT_CellularStack.cpp
  connectivity/drivers/cellular/UBLOX/N2XX/UBLOX_N2XX_CellularStack.cpp
Labels: ready for merge, release-type: patch

#13839 cmsis: remove math header file
  cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/Include/arm_math.h
  tools/importer/cmsis_importer.json
Labels: ready for merge, release-type: patch

#13866 CMake: Rename Mbed OS path variable for consistency
  CMakeLists.txt
  docs/design-documents/tools/cmake.md
  tools/cmake/app.cmake
  tools/cmake/core.cmake
  tools/cmake/profile.cmake
Labels: release-version: feature branch

#13853 Samsung: fix baremetal #13851
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/watchdog_api.c
Labels: ready for merge, release-type: patch

#13855 CMake nrf52480: fix startup/linker inclusion
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/CMakeLists.txt
Labels: release-version: feature branch

#13846 STM32 usb: fixing missing header file
  targets/TARGET_STM/USBPhy_STM32.cpp
Labels: ready for merge, release-type: patch

#13862 STM32 SERIAL: free RTS/CTS pins
  targets/TARGET_STM/TARGET_STM32L4/serial_device.c
  targets/TARGET_STM/serial_api.c
Labels: ready for merge, release-type: patch

#13698 Fix SPIF read dummy cycles not being reset
  storage/blockdevice/COMPONENT_SPIF/source/SPIFBlockDevice.cpp
Labels: ready for merge, release-type: patch

#13871 CMake: Fix Microlib selection
  tools/cmake/toolchains/ARM.cmake
Labels: needs: review, release-version: feature branch

#13860 CMake: Remove memap depth level argument
  CMakeLists.txt
Labels: release-version: feature branch

#13811 Ble conditional compilation
  connectivity/FEATURE_BLE/include/ble/SecurityManager.h
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/hci/dual_chip/hci_evt.c
  connectivity/FEATURE_BLE/libraries/cordio_stack/wsf/include/hci_defs.h
  connectivity/FEATURE_BLE/source/SecurityManager.cpp
  connectivity/FEATURE_BLE/source/cordio/source/BLEInstanceBaseImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalAttClientImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalAttClientImpl.h
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.h
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.h
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.h
  connectivity/FEATURE_BLE/source/pal/PalGap.h
  connectivity/FEATURE_BLE/source/pal/PalSecurityManager.h
Labels: ready for merge, release-type: patch

#13885 TEST: update cmake example on ble examples
  tools/test/examples/examples_cmake.json
Labels: ready for merge, release-type: patch

#13883 feature-wisun: Nanostack release v12.6.2
  features/nanostack/sal-stack-nanostack/mbed_lib.json
  features/nanostack/sal-stack-nanostack/nanostack/ws_bbr_api.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api_internal.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_config.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_neighbor_class.c
  features/nanostack/sal-stack-nanostack/source/Core/include/ns_socket.h
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_downward.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_downward.h
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_upward.c
  features/nanostack/sal-stack-nanostack/source/nsconfig.h
Labels: needs: review, release-version: feature branch

#13886 Don't require too old mbed tools
  requirements.txt
Labels: ready for merge, release-type: patch

#13847 Add workaround for files with permissive binary licenses
  tools/test/travis-ci/scancode-evaluate.py
  tools/test/travis-ci/scancode_evaluate_test.py
  tools/test/travis-ci/scancode_test/scancode_test_3.json
Labels: ready for merge, release-type: patch

#13802 STM32F4 FLASH API update
  targets/TARGET_STM/TARGET_STM32F4/flash_api.c
Labels: ready for merge, release-type: patch

#13816 STM32: allow HS USB endpoints and increase USB OTG_HS endpoints number
  drivers/include/drivers/USBCDC.h
  drivers/source/usb/USBCDC.cpp
  targets/TARGET_STM/USBPhy_STM32.cpp
Labels: ready for merge, release-type: patch

#13859 STM32L4: Use HSI for LPUART
  targets/targets.json
Labels: ready for merge, release-type: patch

#13867 SysTimer: Prevent unacknowledged tick overflow when halted for a while
  platform/include/platform/internal/SysTimer.h
  platform/source/SysTimer.cpp
Labels: ready for merge, release-type: patch

#13864 Fix bare metal builds on Cypress targets
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/mbed_lib.json
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/cytfm_flash_info.c
  targets/TARGET_Cypress/TARGET_PSOC6/cy_flash_api.c
Labels: ready for merge, release-type: patch

#13889 Nanostack release v12.6.2
  connectivity/nanostack/sal-stack-nanostack/mbed_lib.json
  connectivity/nanostack/sal-stack-nanostack/nanostack/ws_bbr_api.h
  connectivity/nanostack/sal-stack-nanostack/nanostack/ws_management_api.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread/thread_bbr_api.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api_internal.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_config.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_llc_data_service.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_management_api.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_neighbor_class.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_key_storage.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_key_storage.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_nvm_data.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_nvm_data.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_nvm_store.h
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.c
  connectivity/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_time.c
  connectivity/nanostack/sal-stack-nanostack/source/Common_Protocols/icmpv6.c
  connectivity/nanostack/sal-stack-nanostack/source/Core/include/ns_socket.h
  connectivity/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mcps_sap.c
  connectivity/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_pd_sap.c
  connectivity/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_pd_sap.h
  connectivity/nanostack/sal-stack-nanostack/source/MPL/mpl.c
  connectivity/nanostack/sal-stack-nanostack/source/RPL/rpl_downward.c
  connectivity/nanostack/sal-stack-nanostack/source/RPL/rpl_downward.h
  connectivity/nanostack/sal-stack-nanostack/source/RPL/rpl_upward.c
  connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.c
  connectivity/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.h
  connectivity/nanostack/sal-stack-nanostack/source/nsconfig.h
Labels: ready for merge, release-type: patch

#13893 MIMXRT1050_EVK return bootloader support
  targets/targets.json
Labels: ready for merge, release-type: patch

#13901 [feature-wisun] Make _unacknowledged_ticks uint32_t to prevent overflow
  platform/source/SysTimer.cpp
  platform/source/SysTimer.h
Labels: ready for merge, release-version: feature branch

#13800 OSPI: enable feature in baremetal test configuration
  TESTS/configs/baremetal.json
Labels: ready for merge, release-type: patch

#13849 Add apollo3 sleep
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/sleep.c
  targets/targets.json
Labels: ready for merge, release-type: patch

#13895 CMake: Fix error that prevented re-build
  tools/cmake/app.cmake
Labels: ready for merge, release-type: patch

#13699 Fix sfdp_find_addr_region algorithm
  drivers/include/drivers/internal/SFDP.h
  drivers/source/SFDP.cpp
Labels: ready for merge, release-type: patch

#13833 Add new Gap::EventHandler callbacks to ChainableGapEventHandler class
  connectivity/FEATURE_BLE/include/ble/gap/ChainableGapEventHandler.h
Labels: ready for merge, release-type: patch

#13861 Ambiq apollo3 fix of an SPI related SD bug
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/spi_api.c
Labels: ready for merge, release-type: patch

#13878 Add missing blockdevice mbed_lib.json
  platform/bare_metal/mbed_lib.json
  storage/blockdevice/mbed_lib.json
Labels: ready for merge, release-type: patch

#13880 S1SBP6A fix RTC range
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/device/s1sbp6a_rtc.c
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/device/s1sbp6a_rtc.h
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/rtc_api.c
Labels: ready for merge, release-type: patch

#13891 Remove nanostack border router from examples list
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#13894 Fix compilation warnings
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAT86RF215.cpp
  connectivity/nanostack/coap-service/source/coap_connection_handler.c
Labels: ready for merge, release-type: patch

#13887 CMake: Specify mbedtools in the build instructions
  tools/cmake/README.md
Labels: ready for merge, release-type: patch

#13911 [feature-std-pin-name] Replace STDIO_UART_TX by USBTX
  docs/design-documents/hal/0004-pin-names-general-guidelines.md
  hal/include/hal/static_pinmap.h
  hal/source/mbed_pinmap_default.cpp
  platform/source/mbed_retarget.cpp
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/TARGET_B_L4S5I_IOT01A/PinNames.h
  targets/TARGET_STM/serial_api.c
  targets/targets.json
Labels: needs: CI, release-version: feature branch

#13913 [feature-std-pin-name] New test for generic pin names
  docs/design-documents/hal/0004-pin-names-general-guidelines.md
  hal/tests/TESTS/pin_names/generic/main.cpp
Labels: needs: CI, release-version: feature branch

#13848 Q/OSPIFBlockDevice: fix misconception in minimum program size
  storage/blockdevice/COMPONENT_OSPIF/mbed_lib.json
  storage/blockdevice/COMPONENT_QSPIF/mbed_lib.json
  storage/blockdevice/tests/TESTS/blockdevice/general_block_device/main.cpp
  storage/kvstore/tests/TESTS/kvstore/general_tests_phase_2/main.cpp
Labels: ready for merge, release-type: patch

#13832 Fix GCC_ARM non-contiguous FW for `K64F` and `K66F`
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/TOOLCHAIN_ARM_STD/MK66FN2M0xxx18.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/device/TOOLCHAIN_GCC_ARM/MK66FN2M0xxx18.ld
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_ARM_STD/MK64FN1M0xxx12.sct
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_GCC_ARM/MK64FN1M0xxx12.ld
Labels: ready for merge, release-type: patch

#13671 Add an socket option to set type of service to set specific precedence for QoS
  connectivity/lwipstack/source/LWIPStack.cpp
  connectivity/netsocket/include/netsocket/nsapi_types.h
Labels: ready for merge, release-type: patch

#13904 CMake STM32L475xG: fix linker/startup inclusion
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/CMakeLists.txt
Labels: ready for merge, release-type: patch

#13768 COMPONENT_FPGA_CI_TEST_SHIELD: better debug print
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/test_utils.h
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/source/MbedTester.cpp
Labels: ready for merge, release-type: patch

#13910 Update NRF ble configuration options
  connectivity/FEATURE_BLE/libraries/TARGET_CORDIO_LL/mbed_lib.json
  connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_MCU_NRF52840/mbed_lib.json
  connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/NRFCordioHCIDriver.cpp
  connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/mbed_lib.json
Labels: ready for merge, release-type: feature

#13870 CMake: Address review comment from PR#13566
  CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/TARGET_Ambiq_Micro/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/TARGET_Ambiq_Micro/TARGET_Apollo3/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_MCU_NRF52840/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/CMakeLists.txt
  connectivity/drivers/mbedtls/FEATURE_CRYPTOCELL310/CMakeLists.txt
  connectivity/drivers/mbedtls/FEATURE_CRYPTOCELL310/TARGET_MCU_NRF52840/CMakeLists.txt
  connectivity/drivers/mbedtls/FEATURE_CRYPTOCELL310/binaries/CMakeLists.txt
  connectivity/netsocket/CMakeLists.txt
  tools/cmake/toolchain.cmake
Labels: ready for merge, release-type: patch

#13797 STM32: add setting for LSE drive load level
  targets/TARGET_STM/TARGET_STM32L5/system_clock.c
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xx/TARGET_NUCLEO_WB55RG/system_clock.c
  targets/TARGET_STM/mbed_overrides.c
  targets/targets.json
Labels: ready for merge, release-type: patch

#13905 STM32L4: ADC compilation issue with L422
  targets/TARGET_STM/TARGET_STM32L4/analogin_device.c
Labels: ready for merge, release-type: patch

#13912 [feature-std-pin-name] LED and BUTTON definition
  docs/design-documents/hal/0004-pin-names-general-guidelines.md
  hal/tests/TESTS/mbed_hal/gpio/main.cpp
  platform/source/mbed_board.c
  platform/tests/TESTS/mbed_platform/stats_cpu/main.cpp
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/TARGET_B_L4S5I_IOT01A/PinNames.h
Labels: needs: review, release-version: feature branch

#13085 Change MBED_STATIC_ASSERTs version for built-in
  connectivity/FEATURE_BLE/include/ble/common/Duration.h
  connectivity/netsocket/source/NetworkStack.cpp
  drivers/source/MbedCRC.cpp
  events/source/equeue_mbed.cpp
  features/frameworks/utest/utest/utest_specification.h
  hal/source/mbed_pinmap_default.cpp
  hal/source/mpu/mbed_mpu_v7m.c
  hal/source/mpu/mbed_mpu_v8m.c
  platform/cxxsupport/mstd_atomic
  platform/include/platform/CircularBuffer.h
  platform/include/platform/Span.h
  platform/include/platform/mbed_assert.h
  platform/include/platform/mbed_version.h
  platform/source/CThunkBase.cpp
  platform/source/SysTimer.cpp
  platform/source/mbed_atomic_impl.c
  platform/source/mbed_retarget.cpp
  platform/tests/TESTS/mbed_micro/static_assert/test_c.c
  platform/tests/TESTS/mbed_micro/static_assert/test_cpp.cpp
  rtos/include/rtos/MemoryPool.h
  rtos/source/Thread.cpp
  storage/blockdevice/COMPONENT_SD/source/SDBlockDevice.cpp
  targets/TARGET_NUVOTON/TARGET_M2351/device/system_M2351.c
  targets/TARGET_NUVOTON/TARGET_M2351/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M251/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M261/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M451/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M480/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/gpio_irq_api.c
Labels: ready for merge, release-type: patch

#13755 Fix MBED_ERROR call in init_os_timer
  platform/source/mbed_os_timer.cpp
Labels: ready for merge, release-type: patch

#13896 STM32 OSPI support
  hal/tests/TESTS/mbed_hal/ospi/ospi_test_utils.cpp
  storage/blockdevice/COMPONENT_OSPIF/source/OSPIFBlockDevice.cpp
  targets/TARGET_STM/TARGET_STM32F4/common_objects.h
  targets/TARGET_STM/TARGET_STM32F7/objects.h
  targets/TARGET_STM/TARGET_STM32H7/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/TARGET_NUCLEO_H7A3ZI_Q/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/TARGET_DISCO_L4R9I/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/TARGET_B_L4S5I_IOT01A/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/TARGET_B_L4S5I_IOT01A/PinNames.h
  targets/TARGET_STM/TARGET_STM32L5/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L552xE/TARGET_NUCLEO_L552ZE_Q/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L552xE/TARGET_NUCLEO_L552ZE_Q/PinNames.h
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L562xE/TARGET_DISCO_L562QE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L562xE/TARGET_DISCO_L562QE/PinNames.h
  targets/TARGET_STM/TARGET_STM32L5/objects.h
  targets/TARGET_STM/ospi_api.c
  targets/targets.json
Labels: ready for merge, release-type: patch

#13914 STM32 FLASH API : add critical sections
  targets/TARGET_STM/TARGET_STM32F0/flash_api.c
  targets/TARGET_STM/TARGET_STM32F1/flash_api.c
  targets/TARGET_STM/TARGET_STM32F2/flash_api.c
  targets/TARGET_STM/TARGET_STM32F3/flash_api.c
  targets/TARGET_STM/TARGET_STM32F4/flash_api.c
  targets/TARGET_STM/TARGET_STM32F7/flash_api.c
  targets/TARGET_STM/TARGET_STM32G0/flash_api.c
  targets/TARGET_STM/TARGET_STM32G4/flash_api.c
  targets/TARGET_STM/TARGET_STM32H7/flash_api.c
  targets/TARGET_STM/TARGET_STM32L0/flash_api.c
  targets/TARGET_STM/TARGET_STM32L1/flash_api.c
  targets/TARGET_STM/TARGET_STM32L4/flash_api.c
  targets/TARGET_STM/TARGET_STM32L5/flash_api.c
Labels: ready for merge, release-type: patch

#13918 TARGET_NXP: Remove support for LPC11U6X
  targets/TARGET_NXP/TARGET_LPC11U6X/PeripheralNames.h
  targets/TARGET_NXP/TARGET_LPC11U6X/PinNames.h
  targets/TARGET_NXP/TARGET_LPC11U6X/PortNames.h
  targets/TARGET_NXP/TARGET_LPC11U6X/analogin_api.c
  targets/TARGET_NXP/TARGET_LPC11U6X/device.h
  targets/TARGET_NXP/TARGET_LPC11U6X/device/LPC11U6x.h
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_ARM_MICRO/TARGET_LPC11U68/LPC11U68.sct
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_ARM_MICRO/TARGET_LPC11U68/startup_LPC11U6x.S
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_ARM_STD/TARGET_LPC11U68/LPC11U68.sct
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_ARM_STD/TARGET_LPC11U68/startup_LPC11U6x.S
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U68/LPC11U68.ld
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_GCC_ARM/TARGET_LPC11U68/startup_LPC11U68.cpp
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_IAR/TARGET_LPC11U68/LPC11U68.icf
  targets/TARGET_NXP/TARGET_LPC11U6X/device/TOOLCHAIN_IAR/TARGET_LPC11U68/startup_LPC11U6X.S
  targets/TARGET_NXP/TARGET_LPC11U6X/device/cmsis.h
  targets/TARGET_NXP/TARGET_LPC11U6X/device/cmsis_nvic.h
  targets/TARGET_NXP/TARGET_LPC11U6X/device/system_LPC11U6x.c
  targets/TARGET_NXP/TARGET_LPC11U6X/device/system_LPC11U6x.h
  targets/TARGET_NXP/TARGET_LPC11U6X/gpio_api.c
  targets/TARGET_NXP/TARGET_LPC11U6X/gpio_irq_api.c
  targets/TARGET_NXP/TARGET_LPC11U6X/gpio_object.h
  targets/TARGET_NXP/TARGET_LPC11U6X/i2c_api.c
  targets/TARGET_NXP/TARGET_LPC11U6X/objects.h
  targets/TARGET_NXP/TARGET_LPC11U6X/pinmap.c
  targets/TARGET_NXP/TARGET_LPC11U6X/pwmout_api.c
  targets/TARGET_NXP/TARGET_LPC11U6X/rtc_api.c
  targets/TARGET_NXP/TARGET_LPC11U6X/serial_api.c
  targets/TARGET_NXP/TARGET_LPC11U6X/sleep.c
  targets/TARGET_NXP/TARGET_LPC11U6X/spi_api.c
  targets/TARGET_NXP/TARGET_LPC11U6X/us_ticker.c
Labels: ready for merge, release-type: patch

#13928 Clean remnant of experiment with ARM toolchain
  tools/cmake/toolchains/ARM.cmake
Labels: ready for merge, release-type: patch

#13930 CMake: pass macros to ARM toolchain linker
  CMakeLists.txt
  tools/cmake/toolchain.cmake
  tools/cmake/toolchains/GCC_ARM.cmake
Labels: ready for merge, release-type: patch

#13931 STM32 I2C: use correct HAL API
  targets/TARGET_STM/TARGET_STM32F0/common_objects.h
  targets/TARGET_STM/TARGET_STM32F1/STM32Cube_FW/STM32F1xx_HAL_Driver/stm32f1xx_hal_def.h
  targets/TARGET_STM/TARGET_STM32F2/objects.h
  targets/TARGET_STM/TARGET_STM32L1/common_objects.h
  targets/TARGET_STM/i2c_api.c
Labels: ready for merge, release-type: patch

#13932 Reduce ST QSPI/OSPI trace verbosity to debug
  targets/TARGET_STM/ospi_api.c
  targets/TARGET_STM/qspi_api.c
Labels: ready for merge

#13939 STM32: LSE DRIVE feature update
  targets/TARGET_STM/TARGET_STM32F0/common_objects.h
  targets/TARGET_STM/TARGET_STM32F3/objects.h
  targets/TARGET_STM/TARGET_STM32F4/common_objects.h
  targets/TARGET_STM/TARGET_STM32F7/objects.h
  targets/TARGET_STM/TARGET_STM32G4/objects.h
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/TARGET_STM/TARGET_STM32L0/objects.h
  targets/TARGET_STM/TARGET_STM32L4/objects.h
  targets/TARGET_STM/TARGET_STM32L5/objects.h
  targets/TARGET_STM/mbed_overrides.c
  targets/targets.json
Labels: ready for merge, release-type: patch

#13935 Dragonfly Nano(MTQN): power on/off so soft_power_on() fix
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L471xG/TARGET_MTS_DRAGONFLY_L471QG/ONBOARD_SARA4_PPP.cpp
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L471xG/TARGET_MTS_DRAGONFLY_L471QG/ONBOARD_SARA4_PPP.h
Labels: ready for merge, release-type: patch

#13909 [feature-wisun] Add nanostack dynamic memory tracker and hooks to dynmem library
  features/frameworks/nanostack-libservice/Makefile
  features/frameworks/nanostack-libservice/mbed-client-libservice/nsdynmemLIB.h
  features/frameworks/nanostack-libservice/mbed-client-libservice/nsdynmem_tracker.h
  features/frameworks/nanostack-libservice/mbed-client-libservice/nsdynmem_tracker_lib.h
  features/frameworks/nanostack-libservice/mbed_lib.json
  features/frameworks/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c
  features/frameworks/nanostack-libservice/source/nsdynmemtracker/nsdynmem_tracker_lib.c
Labels: ready for merge, release-version: feature branch

#13953 Add nanostack dependency lib
  connectivity/nanostack/CMakeLists.txt
Labels: ready for merge, release-type: patch

#13919 [feature-std-pin-name] ARDUINO_UNO standard
  TESTS/integration/COMMON/target_extended.json
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_MS/mbed_lib.json
  docs/design-documents/hal/0005-pin-names-Arduino-Uno-standard.md
  hal/include/hal/ArduinoUnoAliases.h
  hal/include/hal/pinmap.h
  hal/source/mbed_gpio.c
  hal/source/mbed_pinmap_default.cpp
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/analogin/main.cpp
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/gpio/main.cpp
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/gpio_irq/main.cpp
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/i2c/main.cpp
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/pwm/main.cpp
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/uart/main.cpp
  hal/tests/TESTS/mbed_timing_fpga_ci_test_shield/watchdog/main.cpp
  hal/tests/TESTS/pin_names/arduino_uno/main.cpp
  platform/include/platform/platform.h
  storage/blockdevice/COMPONENT_SD/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/TARGET_B_L4S5I_IOT01A/PinNames.h
  targets/targets.json
Labels: needs: work, release-version: feature branch

#13958 Fix a typo in STM32F3's CMakeList.txt
  targets/TARGET_STM/TARGET_STM32F3/CMakeLists.txt
Labels: ready for merge, release-type: patch

#13948 CMake: Simplify BLE library inclusion
  connectivity/FEATURE_BLE/source/CMakeLists.txt
Labels: ready for merge, release-type: patch

#13949 Fix mbed::Dir type handling in fat_filesystem
  storage/filesystem/fat/tests/TESTS/fat/fat_filesystem/main.cpp
Labels: ready for merge, release-type: patch

#13942 ble: Fix persistence in SecurityDB
  connectivity/FEATURE_BLE/source/generic/KVStoreSecurityDb.cpp
  connectivity/FEATURE_BLE/source/generic/KVStoreSecurityDb.h
  connectivity/FEATURE_BLE/source/generic/SecurityDb.h
Labels: ready for merge, release-type: patch

#13780 STM32 H7: fix USB in sleep mode
  targets/TARGET_STM/USBPhy_STM32.cpp
Labels: ready for merge, release-type: patch

#13947 Fix erase type determination for [Q/O/]BlockDevice::erase()
  drivers/include/drivers/internal/SFDP.h
  drivers/source/SFDP.cpp
  drivers/tests/UNITTESTS/SFDP/test_sfdp.cpp
  drivers/tests/UNITTESTS/SFDP/unittest.cmake
  storage/blockdevice/COMPONENT_OSPIF/source/OSPIFBlockDevice.cpp
  storage/blockdevice/COMPONENT_QSPIF/source/QSPIFBlockDevice.cpp
  storage/blockdevice/COMPONENT_SPIF/source/SPIFBlockDevice.cpp
Labels: ready for merge, release-type: patch

#13960 Add const keyword to get_erase_size declaration
  storage/blockdevice/COMPONENT_QSPIF/include/QSPIF/QSPIFBlockDevice.h
  storage/blockdevice/COMPONENT_QSPIF/source/QSPIFBlockDevice.cpp
Labels: ready for merge, release-type: patch

#13951 MCU_NRF52832 (NRF52_DK, SDT52832B): use two-region memory model to support MicroLib
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_ARM_STD/nRF52832.sct
Labels: ready for merge, release-type: patch

#13964 CMake: Add support for all ARM FM Mbed targets
  targets/CMakeLists.txt
  targets/TARGET_ARM_FM/CMakeLists.txt
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/CMakeLists.txt
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/TOOLCHAIN_ARM_STD/MPS2.sct
  tools/cmake/README.md
Labels: ready for merge, release-type: patch

#13973 stm32: delete objects.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/objects.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/objects.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F769xI/objects.h
Labels: ready for merge, release-type: patch

#13922 CMake: add nuvoton targets
  targets/CMakeLists.txt
  targets/TARGET_NUVOTON/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_TFM/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/device/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/device/TARGET_TFM/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/device/TOOLCHAIN_ARMC6/M2351.sct
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_S/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_S/TARGET_TFM/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_NU_PFM_M2351/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M251/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M251/TARGET_NUMAKER_IOT_M252/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M251/device/TOOLCHAIN_ARMC6/M251.sct
  targets/TARGET_NUVOTON/TARGET_M261/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M261/TARGET_NUMAKER_IOT_M263A/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M261/device/TOOLCHAIN_ARMC6/M261.sct
  targets/TARGET_NUVOTON/TARGET_M451/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M451/device/TOOLCHAIN_ARM/M453.sct
  targets/TARGET_NUVOTON/TARGET_M480/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M480/TARGET_NUMAKER_IOT_M487/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M480/TARGET_NUMAKER_PFM_M487/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M480/device/TOOLCHAIN_ARM_STD/M487.sct
  targets/TARGET_NUVOTON/TARGET_NANO100/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_NUC472/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_ARM_STD/TARGET_NU_XRAM_SUPPORTED/NUC472.sct
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_ARM_STD/TARGET_NU_XRAM_UNSUPPORTED/NUC472.sct
Labels: ready for merge, release-type: patch

#13906 STM32G070: generic target creation
  targets/TARGET_STM/TARGET_STM32G0/objects.h
  targets/TARGET_STM/TARGET_STM32G0/serial_device.c
  targets/TARGET_STM/TARGET_STM32G0/us_ticker_data.h
  targets/targets.json
Labels: ready for merge, release-type: patch

#12897 Optimise mbed_ticker_api.c
  hal/include/hal/lp_ticker_api.h
  hal/include/hal/ticker_api.h
  hal/include/hal/us_ticker_api.h
  hal/source/mbed_ticker_api.c
  hal/tests/TESTS/mbed_hal/lp_ticker/main.cpp
  hal/tests/TESTS/mbed_hal/ticker/main.cpp
  targets/targets.json
Labels: needs: review, release-type: feature
