Repository ARMmbed/mbed-os, pull requests merged in 2020-07, with the labels that each got.

#13172 Cypress: Fix internal JIRA. Add check if cybsp_init() is successful
  targets/TARGET_Cypress/TARGET_PSOC6/mbed_overrides.c
Labels: ready for merge, release-type: patch

#13152 Add Wi-SUN Interface APIs
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-type: feature

#13173 STM32L4: I2C init parameters for L4+ MCU
  targets/TARGET_STM/TARGET_STM32L4/i2c_device.h
Labels: ready for merge, release-type: patch

#13180 Update mbed-coap to version 5.1.6
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/source/sn_coap_parser.c
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-type: patch

#13182 [feature-wisun] Correct network name and PAN ID change on auth start
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.h
Labels: ready for merge, release-version: feature branch

#13174 tests-mbed_timing_fpga_ci_test_shield-watchdog update with clock accuracy
  TESTS/mbed_timing_fpga_ci_test_shield/watchdog/main.cpp
Labels: ready for merge, release-type: patch

#13188 TEST: Add spif-driver support for baremetal test build
  TESTS/configs/baremetal.json
Labels: ready for merge, release-type: patch

#13191 Fix ordering in adjust config.sh
  features/mbedtls/importer/adjust-config.sh
Labels: ready for merge, release-type: patch

#13198 Cypress: Update WHD to version 1.91.2
  features/netsocket/emac-drivers/TARGET_Cypress/COMPONENT_WHD/interface/WhdSTAInterface.cpp
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/generated_mac_address.txt
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/inc/whd_types.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/inc/whd_version.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/inc/whd_wifi_api.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/firmware/COMPONENT_43012/43012A0.bin
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/firmware/COMPONENT_43012/43012B0.bin
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/nvram/TARGET_CYESKIT_064B0S2_4343W/wifi_nvram_image.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/resources/nvram/TARGET_CYW943012P6EVB_01/wifi_nvram_image.h
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/src/whd_cdc_bdc.c
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/src/whd_wifi_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/version.txt
Labels: devices: cypress, ready for merge

#13199 TEST: Update kvstore tests with shorter timeout
  features/storage/TESTS/kvstore/general_tests_phase_1/main.cpp
  features/storage/TESTS/kvstore/general_tests_phase_2/main.cpp
Labels: ready for merge

#13205 LWIPStack: set sockets non-blocking
  features/lwipstack/LWIPStack.cpp
  features/lwipstack/lwipopts.h
Labels: ready for merge, release-type: patch

#13206 Usb device init: wait_us fix
  targets/TARGET_NXP/USBHAL_LPC17.cpp
Labels: ready for merge, release-type: patch

#13134 Add WiSun network size configs in JSON
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: needs: CI, release-version: feature branch

#13171 Re-enable AWS example, limit targets
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#13207 TEST: update NRF52840_DK with correct FPAG configuration
  TESTS/configs/fpga.json
Labels: ready for merge, release-type: patch

#13210 Fix hal-sleep/sleep_manager Tests on Cypress Targets
  TESTS/mbed_hal/sleep/main.cpp
  features/frameworks/greentea-client/source/greentea_test_env.cpp
Labels: ready for merge, release-type: patch

#13219 STM32WB RNG: enable use from both M4 and M0+ cores
  targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/hw_conf.h
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xx/TARGET_NUCLEO_WB55RG/system_clock.c
  targets/TARGET_STM/TARGET_STM32WB/wb_sleep.c
  targets/TARGET_STM/trng_api.c
Labels: ready for merge, release-type: patch

#13221 STM32 ANALOGOUT and DEEPSLEEP
  targets/TARGET_STM/TARGET_STM32L4/analogout_device.c
Labels: ready for merge, release-type: patch

#13222 STM32 PWM : avoid glitch after duty cycle change
  targets/TARGET_STM/pwmout_api.c
Labels: ready for merge, release-type: patch

#13227 Revert "Fix kv parsing bug in greentea client."
  features/frameworks/greentea-client/source/greentea_test_env.cpp
Labels: ready for merge, release-type: patch

#13228 create a random static address using random data
  features/FEATURE_BLE/targets/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/NRFCordioHCIDriver.cpp
Labels: ready for merge, release-version: feature branch

#13147 Ws management API missing lib
  features/nanostack/sal-stack-nanostack/nanostack/ws_management_api.h
Labels: ready for merge, release-version: 5.15.5

#13224 ADV_WISE TLS config duplication
  features/mbedtls/targets/TARGET_STM/TARGET_STM32L4/TARGET_ADV_WISE_1510/mbedtls_device.h
  features/mbedtls/targets/TARGET_STM/TARGET_STM32L4/TARGET_ADV_WISE_1570/mbedtls_device.h
Labels: ready for merge, release-type: patch

#13213 Reduce LED use in automatic CI tests
  TESTS/integration/fs-single/main.cpp
  TESTS/integration/fs-threaded/main.cpp
  TESTS/integration/net-single/main.cpp
  TESTS/integration/net-threaded/main.cpp
  TESTS/integration/stress-net-fs/main.cpp
  TESTS/mbed_drivers/ticker/main.cpp
Labels: ready for merge, release-type: patch

#13235 CMake: armclang fixes
  cmake/app.cmake
  cmake/arm.cmake
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/TOOLCHAIN_ARM_STD/MK64FN1M0xxx12.sct
Labels: needs: review, release-version: feature branch

#13223 PSoC Targets: Increase greentea sync timeout
  targets/targets.json
Labels: ready for merge, release-type: patch

#13230 Fix duplication of KW41Z Nanostack driver
  features/nanostack/nanostack-interface/targets/TARGET_Freescale/TARGET_KW41Z/NanostackRfPhyKw41z.cpp
  features/nanostack/nanostack-interface/targets/TARGET_Freescale/TARGET_KW41Z/NanostackRfPhyKw41z.h
  features/nanostack/targets/TARGET_Freescale/TARGET_KW41Z/NanostackRfPhyKw41z.cpp
  features/nanostack/targets/TARGET_Freescale/TARGET_KW41Z/NanostackRfPhyKw41z.h
Labels: ready for merge, release-type: patch

#13038 BLE: Add KVStore Security DB
  features/FEATURE_BLE/ble/generic/FileSecurityDb.h
  features/FEATURE_BLE/ble/generic/GenericGap.h
  features/FEATURE_BLE/ble/generic/GenericGattClient.h
  features/FEATURE_BLE/ble/generic/GenericSecurityManager.h
  features/FEATURE_BLE/ble/generic/KVStoreSecurityDb.h
  features/FEATURE_BLE/ble/generic/MemorySecurityDb.h
  features/FEATURE_BLE/ble/generic/SecurityDb.h
  features/FEATURE_BLE/mbed_lib.json
  features/FEATURE_BLE/source/generic/FileSecurityDb.cpp
  features/FEATURE_BLE/source/generic/GenericGap.tpp
  features/FEATURE_BLE/source/generic/GenericGattClient.tpp
  features/FEATURE_BLE/source/generic/GenericSecurityManager.tpp
  features/FEATURE_BLE/source/generic/KVStoreSecurityDb.cpp
Labels: ready for merge, release-type: feature

#13225 BLE remove unused CYW4343X file
  features/FEATURE_BLE/targets/TARGET_STM/TARGET_CYW4343X/HCIDriver.cpp
Labels: ready for merge, release-type: patch

#13247 GreenTea: Fix inconsistency of Greentea KV message
  features/frameworks/greentea-client/source/greentea_test_env.cpp
Labels: ready for merge, release-type: patch

#13257 Remove invalid unicode characters from mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/mbed_lib.json
Labels: ready for merge, release-type: patch

#13251 CMake: Complete support for mbedtls
  features/mbedtls/CMakeLists.txt
  features/mbedtls/targets/TARGET_Cypress/CMakeLists.txt
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/CMakeLists.txt
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/TARGET_MXCRYPTO_01/CMakeLists.txt
  features/mbedtls/targets/TARGET_Cypress/TARGET_MXCRYPTO/TARGET_MXCRYPTO_02/CMakeLists.txt
  features/mbedtls/targets/TARGET_NUVOTON/CMakeLists.txt
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_M480/CMakeLists.txt
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/CMakeLists.txt
  features/mbedtls/targets/TARGET_NUVOTON/TARGET_NUC472/TARGET_NUMAKER_PFM_NUC472/CMakeLists.txt
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F437xG/CMakeLists.txt
  features/mbedtls/targets/TARGET_STM/TARGET_STM32F756xG/CMakeLists.txt
  features/mbedtls/targets/TARGET_STM/TARGET_STM32L443xC/CMakeLists.txt
  features/mbedtls/targets/TARGET_STM/TARGET_STM32L486xG/CMakeLists.txt
  features/mbedtls/targets/TARGET_STM/TARGET_STM32L562xx/CMakeLists.txt
  features/mbedtls/targets/TARGET_STM/TARGET_STM32WB55xx/CMakeLists.txt
  features/mbedtls/targets/TARGET_Samsung/CMakeLists.txt
  features/mbedtls/targets/TARGET_Silicon_Labs/CMakeLists.txt
Labels: ready for merge, release-version: feature branch

#13249 CMake: Add support for mbed-client-cli
  features/CMakeLists.txt
  features/frameworks/mbed-client-cli/CMakeLists.txt
Labels: ready for merge, release-version: feature branch

#13250 CMake: Add support for mbed-coap
  features/CMakeLists.txt
  features/frameworks/mbed-coap/CMakeLists.txt
Labels: ready for merge, release-version: feature branch

#13258 Fix deprecated warning messages in Cypress code
  features/FEATURE_BLE/targets/TARGET_Cypress/COMPONENT_CYW43XXX/CyH4TransportDriver.cpp
  features/FEATURE_BLE/targets/TARGET_Cypress/COMPONENT_CYW43XXX/HCIDriver.cpp
Labels: ready for merge, release-type: patch

#13252 Implements iterators for the Span class to be compatible with std::span
  platform/Span.h
Labels: ready for merge, release-type: feature

#13011 Always build both .hex and .bin files
  tools/toolchains/mbed_toolchain.py
Labels: ready for merge, release-type: feature

#13263 psa: Update TF-M for ARM_MUSCA_B1
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/VERSION.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/include/psa/crypto.h
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/include/psa/crypto_client_struct.h
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/include/psa/crypto_extra.h
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/include/psa/crypto_struct.h
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/include/psa/crypto_types.h
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/include/psa/crypto_values.h
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/include/psa_manifest/sid.h
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/include/tfm_crypto_defs.h
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/include/tfm_veneers.h
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/src/tfm_ps_ipc_api.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/mcuboot.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/tfm_s.axf
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/tfm_s.bin
  tools/psa/tfm/bin_utils/imgtool.py
Labels: ready for merge, release-type: feature

#13269 Add profile cmake files
  cmake/profiles/common.cmake
  cmake/profiles/debug.cmake
  cmake/profiles/develop.cmake
  cmake/profiles/release.cmake
Labels: ready for merge, release-version: feature branch

#13270 cmake: fix armclang6 errors
  features/storage/CMakeLists.txt
  features/storage/filesystem/littlefs/CMakeLists.txt
  features/storage/filesystem/littlefsv2/CMakeLists.txt
Labels: needs: review, release-version: feature branch

#13266 CMake: remove arm toolchain and rename fix components
  CMakeLists.txt
  cmake/arm.cmake
  cmake/env.cmake
  cmake/toolchain.cmake
Labels: ready for merge, release-version: feature branch

#13278 CMake: use `MBED_` prefix in CMake files
  CMakeLists.txt
  cmake/app.cmake
  cmake/env.cmake
  cmake/target.cmake
  cmake/toolchain.cmake
Labels: ready for merge, release-version: feature branch

#13272 Add per-core cmake files
  cmake/cores/Cortex-A9.cmake
  cmake/cores/Cortex-M0+.cmake
  cmake/cores/Cortex-M0.cmake
  cmake/cores/Cortex-M1.cmake
  cmake/cores/Cortex-M23-NS.cmake
  cmake/cores/Cortex-M23.cmake
  cmake/cores/Cortex-M3.cmake
  cmake/cores/Cortex-M33-NS.cmake
  cmake/cores/Cortex-M33.cmake
  cmake/cores/Cortex-M33F-NS.cmake
  cmake/cores/Cortex-M33F.cmake
  cmake/cores/Cortex-M33FE-NS.cmake
  cmake/cores/Cortex-M33FE.cmake
  cmake/cores/Cortex-M4.cmake
  cmake/cores/Cortex-M4F.cmake
  cmake/cores/Cortex-M7.cmake
  cmake/cores/Cortex-M7F.cmake
  cmake/cores/Cortex-M7FD.cmake
Labels: ready for merge, release-version: feature branch

#13277 move elements generated by the tools to gen_config and remove the need for mbed_config.h
  cmake/app.cmake
  cmake/target.cmake
  cmake/toolchain.cmake
Labels: ready for merge, release-version: feature branch

#13282 CMake: add travis job to build blinky
  .travis.yml
Labels: ready for merge, release-version: feature branch

#13287 CMake: Correct property names (must be MBED_* instead of MBED_OS_*)
  rtos/source/TARGET_CORTEX/rtx5/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/device/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/device/CMakeLists.txt
Labels: ready for merge, release-version: feature branch

#13288 CMake: Correct how scatter file is passed
  cmake/app.cmake
Labels: ready for merge, release-version: feature branch

#13285 Use a different key to sign Non-secure image for ARM_MUSCA_B1 target
  tools/targets/ARM_MUSCA_B1.py
  tools/targets/musca_b1-root-rsa-3072.md
  tools/targets/musca_b1-root-rsa-3072_1.pem
Labels: ready for merge, release-type: patch

#13291 Update TF-M for ARM_MUSCA_B1
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/VERSION.txt
  features/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/include/psa/crypto_client_struct.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/tfm_s.axf
Labels: ready for merge, release-type: patch

#13253 Allow unit tests defined anywhere in mbed-os
  UNITTESTS/CMakeLists.txt
Labels: ready for merge

#13229 STM32 custom target: create MCU_STM32xx for each family
  .travis.yml
  targets/targets.json
Labels: ready for merge, release-type: patch

#13283 BLE: Cordio bugfix fixed size writes under size must be allowed
  features/FEATURE_BLE/targets/TARGET_CORDIO/stack/ble-host/sources/stack/att/atts_write.c
Labels: ready for merge

#13234 Move drivers from components to connectivity
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/LICENSE
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/README.md
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/apache-2.0.txt
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/atmel-rf-driver/NanostackRfPhyAtmel.h
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/mbed_lib.json
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/source/AT86RF215Reg.h
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/source/AT86RFReg.h
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAT86RF215.cpp
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/source/NanostackRfPhyAtmel.cpp
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/source/at24mac.cpp
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/source/at24mac.h
  connectivity/drivers/802.15.4_RF/atmel-rf-driver/source/rfbits.h
  connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/LICENSE
  connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/README.md
  connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/apache-2.0.txt
  connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/mbed_lib.json
  connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/mcr20a-rf-driver/NanostackRfPhyMcr20a.h
  connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/source/MCR20Drv.c
  connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/source/MCR20Drv.h
  connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/source/MCR20Overwrites.h
  connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/source/MCR20Reg.h
  connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/source/NanostackRfPhyMcr20a.cpp
  connectivity/drivers/802.15.4_RF/mcr20a-rf-driver/source/XcvrSpi.h
  connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/README.md
  connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/mbed_lib.json
  connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/source/NanostackRfPhys2lp.cpp
  connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/source/at24mac_s2lp.cpp
  connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/source/at24mac_s2lp.h
  connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.c
  connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/source/rf_configuration.h
  connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/source/s2lpReg.h
  connectivity/drivers/802.15.4_RF/stm-s2lp-rf-driver/stm-s2lp-rf-driver/NanostackRfPhys2lp.h
  connectivity/drivers/cellular/COMPONENT_STMOD_CELLULAR/README.md
  connectivity/drivers/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.cpp
  connectivity/drivers/cellular/COMPONENT_STMOD_CELLULAR/STModCellular.h
  connectivity/drivers/cellular/COMPONENT_STMOD_CELLULAR/mbed_lib.json
  connectivity/drivers/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  connectivity/drivers/wifi/esp8266-driver/ESP8266/ESP8266.h
  connectivity/drivers/wifi/esp8266-driver/ESP8266Interface.cpp
  connectivity/drivers/wifi/esp8266-driver/ESP8266Interface.h
  connectivity/drivers/wifi/esp8266-driver/README.md
  connectivity/drivers/wifi/esp8266-driver/mbed_lib.json
  connectivity/drivers/wifi/esp8266-driver/nucleo_esp8266_hw_fc1.jpg
  connectivity/drivers/wifi/esp8266-driver/nucleo_esp8266_hw_fc2.jpg
Labels: ready for merge

#13255 Move mbed-coap to connectivity/libraries
  .astyleignore
  connectivity/libraries/mbed-coap/.gitattributes
  connectivity/libraries/mbed-coap/.gitignore
  connectivity/libraries/mbed-coap/.mbedignore
  connectivity/libraries/mbed-coap/.settings/language.settings.xml
  connectivity/libraries/mbed-coap/.settings/org.eclipse.cdt.core.prefs
  connectivity/libraries/mbed-coap/CHANGELOG.md
  connectivity/libraries/mbed-coap/LICENSE
  connectivity/libraries/mbed-coap/Makefile
  connectivity/libraries/mbed-coap/Makefile.test
  connectivity/libraries/mbed-coap/README.md
  connectivity/libraries/mbed-coap/README.txt
  connectivity/libraries/mbed-coap/apache-2.0.txt
  connectivity/libraries/mbed-coap/doxygen/libcoap_doxy
  connectivity/libraries/mbed-coap/junit_xsl.xslt
  connectivity/libraries/mbed-coap/mbed-coap/sn_coap_header.h
  connectivity/libraries/mbed-coap/mbed-coap/sn_coap_protocol.h
  connectivity/libraries/mbed-coap/mbed-coap/sn_config.h
  connectivity/libraries/mbed-coap/mbed_lib.json
  connectivity/libraries/mbed-coap/run_unit_tests.sh
  connectivity/libraries/mbed-coap/run_unit_tests_with_valgrind.sh
  connectivity/libraries/mbed-coap/source/include/sn_coap_header_internal.h
  connectivity/libraries/mbed-coap/source/include/sn_coap_protocol_internal.h
  connectivity/libraries/mbed-coap/source/sn_coap_builder.c
  connectivity/libraries/mbed-coap/source/sn_coap_header_check.c
  connectivity/libraries/mbed-coap/source/sn_coap_parser.c
  connectivity/libraries/mbed-coap/source/sn_coap_protocol.c
  connectivity/libraries/mbed-coap/xsl_script.sh
Labels: ready for merge

#13293 BLE Fix read and write callbacks for descriptors not firing if characteristic is not readable or writable
  features/FEATURE_BLE/targets/TARGET_CORDIO/source/CordioGattServer.cpp
Labels: ready for merge, release-type: patch

#13276 MASTER - LICENSE.md - clarify filesystem licensing
  LICENSE.md
Labels: ready for merge, release-type: patch

#13264 Moving around a few items within \rtos
  UNITTESTS/CMakeLists.txt
  UNITTESTS/stubs/AT_ControlPlane_netif_stub.cpp
  UNITTESTS/stubs/Kernel_stub.cpp
  UNITTESTS/stubs/Semaphore_stub.cpp
  UNITTESTS/stubs/Thread_stub.h
  UNITTESTS/target_h/rtos/Mutex.h
  UNITTESTS/target_h/rtos/Semaphore.h
  UNITTESTS/target_h/rtos/Thread.h
  UNITTESTS/target_h/rtos/include/rtos/internal/mbed_rtos1_types.h
  UNITTESTS/target_h/rtos/include/rtos/internal/mbed_rtos_storage.h
  features/cellular/framework/API/ATHandler.h
  features/cellular/framework/API/CellularDevice.h
  features/cellular/framework/AT/AT_CellularContext.cpp
  features/cellular/framework/AT/AT_CellularContext.h
  features/cellular/framework/AT/AT_CellularSMS.cpp
  features/cellular/framework/AT/AT_CellularStack.cpp
  features/cellular/framework/AT/AT_ControlPlane_netif.cpp
  features/cellular/framework/device/ATHandler.cpp
  features/cellular/framework/device/CellularContext.cpp
  features/netsocket/TLSSocketWrapper.cpp
  features/netsocket/nsapi_dns.cpp
  rtos/include/rtos/ConditionVariable.h
  rtos/include/rtos/EventFlags.h
  rtos/include/rtos/Kernel.h
  rtos/include/rtos/Mail.h
  rtos/include/rtos/MemoryPool.h
  rtos/include/rtos/Mutex.h
  rtos/include/rtos/Queue.h
  rtos/include/rtos/Semaphore.h
  rtos/include/rtos/ThisThread.h
  rtos/include/rtos/Thread.h
  rtos/include/rtos/internal/mbed_rtos1_types.h
  rtos/include/rtos/internal/mbed_rtos_storage.h
  rtos/include/rtos/mbed_rtos_types.h
  rtos/include/rtos/rtos.h
  rtos/tests/TESTS/mbedmicro-rtos-mbed/MemoryPool/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/basic/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/condition_variable/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/event_flags/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/heap_and_stack/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/kernel_tick_count/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/mail/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/malloc/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/mutex/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/queue/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/semaphore/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/signals/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/systimer/main.cpp
  rtos/tests/TESTS/mbedmicro-rtos-mbed/threads/SynchronizedIntegral.h
  rtos/tests/TESTS/mbedmicro-rtos-mbed/threads/main.cpp
Labels: ready for merge, release-type: patch

#13311 CMake: Fix travis using tools
  .travis.yml
Labels: needs: work, release-version: feature branch

#13323 Travis: fix scandcode failure
  .travis.yml
Labels: ready for merge, release-type: patch

#13301 Remove MTS_DRAGONFLY_F411RE post binary hook that adds the bootloader
  targets/targets.json
Labels: ready for merge, release-type: patch

#13317 Fixed doxygen for Kernel::Clock::time_point argument
  rtos/include/rtos/Mutex.h
  rtos/include/rtos/Semaphore.h
Labels: ready for merge, release-type: patch

#13325 Nuvoton: Revise the pin name of M263A button
  targets/TARGET_NUVOTON/TARGET_M261/TARGET_NUMAKER_IOT_M263A/PinNames.h
Labels: ready for merge, release-type: patch

#13326 Adding NUCLEO_F429ZI to AWS example
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#13330 Remove doubly defined symbol from mbed_lib.json
  storage/kvstore/securestore/mbed_lib.json
Labels: ready for merge, release-type: patch

#13316 CMake: remove version number from ARM toolchain
  cmake/app.cmake
  cmake/cores/Cortex-A9.cmake
  cmake/cores/Cortex-M0+.cmake
  cmake/cores/Cortex-M0.cmake
  cmake/cores/Cortex-M1.cmake
  cmake/cores/Cortex-M23-NS.cmake
  cmake/cores/Cortex-M23.cmake
  cmake/cores/Cortex-M3.cmake
  cmake/cores/Cortex-M33-NS.cmake
  cmake/cores/Cortex-M33.cmake
  cmake/cores/Cortex-M33F-NS.cmake
  cmake/cores/Cortex-M33F.cmake
  cmake/cores/Cortex-M33FE-NS.cmake
  cmake/cores/Cortex-M33FE.cmake
  cmake/cores/Cortex-M4.cmake
  cmake/cores/Cortex-M4F.cmake
  cmake/cores/Cortex-M7.cmake
  cmake/cores/Cortex-M7F.cmake
  cmake/cores/Cortex-M7FD.cmake
  cmake/profiles/debug.cmake
  cmake/profiles/develop.cmake
  cmake/profiles/release.cmake
  cmake/toolchains/ARM.cmake
  cmake/toolchains/ARMC6.cmake
Labels: ready for merge, release-version: feature branch

#13337 Fix Mbed TLS + TF-M integration issues
  features/mbedtls/inc/mbedtls/psa_util.h
  features/mbedtls/src/pk.c
Labels: ready for merge, release-type: patch

#13341 CMake: Fix ARMClang compiler issues
  cmake/app.cmake
  cmake/cores/Cortex-M4F.cmake
  cmake/profiles/develop.cmake
  cmake/toolchain.cmake
  cmake/toolchains/ARM.cmake
Labels: ready for merge, release-version: feature branch

#13332 Nuvoton: Update M252 target name
  targets/targets.json
Labels: ready for merge, release-type: patch

#13314 Storage `system_storage` directory restructure
  UNITTESTS/empty_baseline/unittest.cmake
  storage/blockdevice/tests/TESTS/blockdevice/general_block_device/README.md
  storage/platform/mbed_lib.json
  storage/platform/source/PlatformStorage.cpp
Labels: ready for merge, release-type: patch

#13347 cmake: Armclang - Fix assembler and linker flags
  cmake/cores/Cortex-A9.cmake
  cmake/cores/Cortex-M0+.cmake
  cmake/cores/Cortex-M0.cmake
  cmake/cores/Cortex-M1.cmake
  cmake/cores/Cortex-M23-NS.cmake
  cmake/cores/Cortex-M23.cmake
  cmake/cores/Cortex-M3.cmake
  cmake/cores/Cortex-M33-NS.cmake
  cmake/cores/Cortex-M33.cmake
  cmake/cores/Cortex-M33F-NS.cmake
  cmake/cores/Cortex-M33F.cmake
  cmake/cores/Cortex-M33FE-NS.cmake
  cmake/cores/Cortex-M33FE.cmake
  cmake/cores/Cortex-M4.cmake
  cmake/cores/Cortex-M7.cmake
  cmake/cores/Cortex-M7F.cmake
  cmake/cores/Cortex-M7FD.cmake
Labels: ready for merge, release-version: feature branch

#13114 Fix issue #13023, CAN constructor ignores passed speed.
  targets/TARGET_STM/can_api.c
Labels: Release review required, ready for merge

#13150 Nuvoton: Support EMAC bus reset as while bus err (5.15)
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/TARGET_M480/m480_eth.c
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/TARGET_NUC472/nuc472_eth.c
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/numaker_emac.cpp
  features/netsocket/emac-drivers/TARGET_NUVOTON_EMAC/numaker_emac.h
Labels: release-version: 5.15.5

#13151 [mbed-os-5.15] Added Wi-SUN Interface APIs
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: release-version: 5.15.5

#13164 ESP8266: Avoid duplicate data sends (5.15)
  TESTS/netsocket/udp/udp_tests.h
  components/wifi/esp8266-driver/ESP8266/ESP8266.cpp
  components/wifi/esp8266-driver/ESP8266/ESP8266.h
  components/wifi/esp8266-driver/ESP8266Interface.cpp
Labels: Release review required, ready for merge

#13184 Nordic NRF52 GPIO API: Fix failure to clear the field 'skip_gpio_setup' in a local
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/gpio_api.c
Labels: Release review required, ready for merge

#13318 Call HAL free functions from C++ destructors
  drivers/AnalogIn.h
  drivers/QSPI.h
  drivers/source/SerialBase.cpp
Labels: ready for merge, release-type: patch

#13320 Updating targets.json file for SDP-K1 board.
  targets/targets.json
Labels: Release review required, ready for merge

#13362 TESTS: update tests and fixing time drifting tests in rtos folder
  TESTS/mbed_hal/common_tickers_freq/main.cpp
  rtos/tests/TESTS/host_tests/timing_drift_auto.py
  rtos/tests/TESTS/mbedmicro-rtos-mbed/basic/main.cpp
Labels: ready for merge, release-type: patch

#13333 Events directory restructuring
  .astyleignore
  .travis.yml
  TESTS/usb_device/basic/USBEndpointTester.cpp
  TESTS/usb_device/basic/USBEndpointTester.h
  TESTS/usb_device/basic/USBTester.cpp
  TESTS/usb_device/basic/USBTester.h
  UNITTESTS/CMakeLists.txt
  UNITTESTS/events/equeue/unittest.cmake
  UNITTESTS/stubs/equeue_stub.c
  connectivity/cellular/source/framework/device/CellularDevice.cpp
  connectivity/drivers/emac/TARGET_ARM_FM/COMPONENT_LAN91C111/fvp_emac.cpp
  connectivity/drivers/emac/TARGET_ARM_SSG/COMPONENT_SMSC9220/smsc9220_emac.cpp
  connectivity/drivers/emac/TARGET_Cypress/COMPONENT_SCL/interface/scl_emac.cpp
  connectivity/drivers/emac/TARGET_Cypress/COMPONENT_WHD/interface/whd_emac.cpp
  connectivity/drivers/emac/TARGET_Freescale_EMAC/kinetis_emac.cpp
  connectivity/drivers/emac/TARGET_GD_EMAC/gd32xx_emac.cpp
  connectivity/drivers/emac/TARGET_NUVOTON_EMAC/numaker_emac.cpp
  connectivity/drivers/emac/TARGET_NXP_EMAC/TARGET_IMX/imx_emac.cpp
  connectivity/drivers/emac/TARGET_NXP_EMAC/TARGET_MCU_LPC546XX/lpc546xx_emac.cpp
  connectivity/drivers/emac/TARGET_RDA_EMAC/rda5981x_emac.cpp
  connectivity/drivers/emac/TARGET_RZ_A1_EMAC/rza1_emac.cpp
  connectivity/drivers/emac/TARGET_STM/stm32xx_emac.cpp
  connectivity/libraries/ppp/source/ppp_service.cpp
  connectivity/libraries/ppp/source/ppp_service_if.cpp
  connectivity/netsocket/source/NetworkStack.cpp
  connectivity/netsocket/source/nsapi_dns.cpp
  connectivity/netsocket/tests/UNITTESTS/netsocket/IfaceDnsSocket/moduletest.cpp
  drivers/USBCDC_ECM.h
  events/include/events/Event.h
  events/include/events/EventQueue.h
  events/include/events/UserAllocatedEvent.h
  events/include/events/equeue.h
  events/include/events/internal/equeue_platform.h
  events/include/events/mbed_events.h
  events/include/events/mbed_shared_queues.h
  events/source/.mbedignore
  events/source/tests/tests.c
  events/tests/.mbedignore
  events/tests/TESTS/events/equeue/main.cpp
  events/tests/TESTS/events/queue/main.cpp
  events/tests/TESTS/events/timing/main.cpp
  events/tests/UNITTESTS/equeue/test_equeue.cpp
  events/tests/UNITTESTS/equeue/unittest.cmake
  events/tests/UNITTESTS/stubs/EqueuePosix_stub.c
  events/tests/UNITTESTS/target_h/equeue/equeue_platform.h
  events/tests/UNITTESTS/target_h/mbed_events.h
  events/tests/unit/Makefile
  events/tests/unit/prof.c
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_fhss_timer.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop_mbed.cpp
Labels: ready for merge, release-type: patch

#13377 Move nanostack rf driver from features to connectivity
  connectivity/drivers/802.15.4_RF/TARGET_Freescale/TARGET_KW41Z/NanostackRfPhyKw41z.cpp
  connectivity/drivers/802.15.4_RF/TARGET_Freescale/TARGET_KW41Z/NanostackRfPhyKw41z.h
  connectivity/drivers/802.15.4_RF/TARGET_Freescale/TARGET_KW41Z/mbed_lib.json
  connectivity/drivers/802.15.4_RF/TARGET_Silicon_Labs/TARGET_SL_RAIL/NanostackRfPhyEfr32.cpp
  connectivity/drivers/802.15.4_RF/TARGET_Silicon_Labs/TARGET_SL_RAIL/NanostackRfPhyEfr32.h
  connectivity/drivers/802.15.4_RF/TARGET_Silicon_Labs/TARGET_SL_RAIL/mbed_lib.json
Labels: ready for merge, release-type: patch

#13351 Fix MTS_DRAGONFLY_F413RH drag and drop failure
  targets/targets.json
Labels: ready for merge, release-type: patch

#13279 TESTS: removed mbed OS 6 unsupported target in examples test
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#13379 Fix baremetal nightly test build issue
  connectivity/drivers/emac/TARGET_ARM_FM/COMPONENT_LAN91C111/mbed_lib.json
  connectivity/drivers/emac/TARGET_Cypress/mbed_lib.json
  connectivity/drivers/emac/TARGET_GD_EMAC/mbed_lib.json
  connectivity/drivers/emac/TARGET_NUVOTON_EMAC/mbed_lib.json
  connectivity/drivers/emac/TARGET_NXP_EMAC/TARGET_LPCTarget/mbed_lib.json
  connectivity/drivers/emac/TARGET_NXP_EMAC/TARGET_MCU_LPC546XX/mbed_lib.json
  connectivity/drivers/emac/TARGET_RDA_EMAC/mbed_lib.json
  connectivity/drivers/emac/TARGET_RZ_A1_EMAC/mbed_lib.json
Labels: ready for merge, release-type: patch

#13370 CMake: fix optimizations set
  cmake/profiles/debug.cmake
  cmake/profiles/develop.cmake
  cmake/profiles/release.cmake
  cmake/toolchains/ARM.cmake
  cmake/toolchains/GCC_ARM.cmake
Labels: ready for merge, release-version: feature branch

#13378 CMake: Remove app.cmake module
  CMakeLists.txt
  cmake/app.cmake
  cmake/toolchain.cmake
  cmake/toolchains/ARM.cmake
  cmake/toolchains/GCC_ARM.cmake
Labels: ready for merge, release-version: feature branch
