Repository ARMmbed/mbed-os, pull requests merged in 2021-10, with the labels that each got.

#15116 STM32F3 - enable USB_DEVICE for NUCLEO_F303ZE
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/TARGET_NUCLEO_F303ZE/PinNames.h
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/system_clock.c
  targets/TARGET_STM/USBPhyHw.h
  targets/TARGET_STM/USBPhy_STM32.cpp
  targets/targets.json
Labels: devices: st, ready for merge, release-type: patch

#15124 pin_names-arduino_uno test : UART test case update
  hal/tests/TESTS/pin_names/arduino_uno/main.cpp
Labels: ready for merge, component: hal, release-type: patch

#15123 STM32: introduce new wifi driver for B-U585I-IOT02A
  .codecheckignore
  connectivity/drivers/wifi/CMakeLists.txt
  connectivity/drivers/wifi/TARGET_STM/CMakeLists.txt
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/CMakeLists.txt
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/EMW3080BInterface.cpp
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/EMW3080BInterface.h
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/EMW3080B_EMAC.cpp
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/EMW3080B_EMAC.h
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/EMW3080B_SPI.cpp
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/EMW3080B_SPI.h
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/EMW3080B_UART.cpp
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/EMW3080B_UART.h
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/README.md
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mbed_lib.json
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/LICENSE.md
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/core/checksumutils.c
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/core/checksumutils.h
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/core/mx_rtos_abs.h
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/core/mx_wifi_hci.c
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/core/mx_wifi_hci.h
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/core/mx_wifi_ipc.c
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/core/mx_wifi_ipc.h
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/core/mx_wifi_slip.c
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/core/mx_wifi_slip.h
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/mx_wifi.c
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/mx_wifi.h
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi/mx_wifi_conf_template.h
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi_conf.h
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi_mbed_os.cpp
  connectivity/drivers/wifi/TARGET_STM/COMPONENT_EMW3080B/mx_wifi_mbed_os.h
  connectivity/netsocket/CMakeLists.txt
  targets/targets.json
Labels: ready for merge, component: connectivity, release-type: patch

#15127 mergify: fix issue with labels when PR is closed
  .mergify.yml
Labels: ready for merge, release-type: patch

#15132 STM32: fix USB_reenumerate() for STM32F3
  targets/TARGET_STM/USBPhy_STM32.cpp
Labels: devices: st, ready for merge, release-type: patch

#15140 M2354: Enable post-build for custom board partially with Mbed CLI
  tools/targets/NU_M2354.py
Labels: ready for merge, release-type: patch

#15141 mergify: fix needs work labels if CI fails
  .mergify.yml
Labels: ready for merge, release-type: patch
