Repository ARMmbed/mbed-os, pull requests merged in 2021-03, with the labels that each got.

#14355 CMake - Configure memory map per target to allow multiple add_executable
  CMakeLists.txt
  tools/cmake/toolchains/ARM.cmake
  tools/cmake/toolchains/GCC_ARM.cmake
Labels: component: tools, ready for merge, release-type: patch

#14334 CMake: Remove references of APP_TARGET
  targets/TARGET_Cypress/scripts/PSOC6.py
  targets/TARGET_Cypress/scripts/mbed_set_post_build_cypress.cmake
  targets/TARGET_NXP/scripts/LPC.py
  targets/TARGET_NXP/scripts/mbed_set_post_build_nxp.cmake
Labels: devices: cypress, devices: nxp, ready for merge, release-type: patch

#14340 STM32L5: enable USBDEVICE
  targets/TARGET_STM/TARGET_STM32L5/system_clock.c
  targets/TARGET_STM/USBPhyHw.h
  targets/targets.json
Labels: devices: st, ready for merge, release-type: patch

#14271 Add .editorconfig file
  .editorconfig
Labels: ready for merge, release-type: patch, stale

#14291 Add bare metal support to freescale targets
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_ARM_MICRO/MKL25Z4.sct
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_ARM_MICRO/startup_MKL25Z4.S
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_ARM_STD/MKL25Z4.sct
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL46Z/device/TOOLCHAIN_ARM_STD/MKL46Z4.sct
  targets/targets.json
Labels: devices: nxp, ready for merge, release-type: patch, stale

#14324 PSOC6: Catch possible error in post build script
  targets/TARGET_Cypress/scripts/PSOC6.py
Labels: devices: cypress, ready for merge, stale

#14325 EP Atlas Target Updates
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_ATLAS/atlas_init.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_ATLAS/mbed_lib.json
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_ATLAS/usb_stdio.cpp
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/reloc_vector_table.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/subtarget_init.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/subtarget_init.h
Labels: devices: nordic, ready for merge, release-type: patch, stale

#14349 Add bare metal support to Nordic targets
  targets/targets.json
Labels: ready for merge, release-type: patch

#14345 Add bare metal support to Toshiba targets
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/device/TOOLCHAIN_ARM_STD/tmpm46bf10fg.sct
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/device/TOOLCHAIN_ARM_STD/tmpm4g9f15.sct
  targets/targets.json
Labels: ready for merge, release-type: patch

#14321 Mergify: remove stale label when PR is merged
  .mergify.yml
Labels: ready for merge, release-type: patch

#14363 Add bare metal support to Silicon Labs targets
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG/device/TARGET_1024K/TOOLCHAIN_ARM_MICRO/efm32gg.sct
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG/device/TARGET_1024K/TOOLCHAIN_ARM_MICRO/startup_efm32gg.S
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG/device/TARGET_1024K/TOOLCHAIN_ARM_STD/efm32gg.sct
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG11/device/TOOLCHAIN_ARM_STD/efm32gg11.sct
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/device/TOOLCHAIN_ARM_STD/efr32mg12p.sct
  targets/targets.json
Labels: devices: silicon labs, ready for merge, release-type: patch

#14338 STM32: update readme with clock information
  targets/TARGET_STM/README.md
Labels: devices: st, ready for merge, release-type: patch, stale

#14348 Add bare metal support to ARM FM targets
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/targets.json
Labels: component: test, ready for merge, release-type: patch

#14375 CMake: Update readme for greentea test build procedure
  tools/cmake/README.md
Labels: component: tools, ready for merge, release-type: patch

#14380 CMake: Refactor target MCU_STM32F103xE library name
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103xE/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14376 CMake: Add mbed-cmsis-cortex-m into Nuvoton target
  targets/TARGET_NUVOTON/CMakeLists.txt
Labels: devices: nuvoton, ready for merge, release-type: patch

#14368 Fix CMake include path for the minimal-printf test
  platform/tests/TESTS/mbed_platform/minimal-printf/compliance/CMakeLists.txt
Labels: component: core, ready for merge, release-type: patch

#14378 CMake: Pass application/test name to post build operation
  CMakeLists.txt
  targets/TARGET_Cypress/scripts/PSOC6.py
  targets/TARGET_Cypress/scripts/mbed_set_post_build_cypress.cmake
  targets/TARGET_NXP/scripts/LPC.py
  targets/TARGET_NXP/scripts/mbed_set_post_build_nxp.cmake
Labels: devices: cypress, devices: nxp, ready for merge, release-type: patch

#14386 Freescale: Remove IAR from list of supported toolchains
  targets/targets.json
Labels: ready for merge

#14351 STM32 - Add if !defined check for USE_HAL_XXX_REGISTER_CALLBACKS
  targets/TARGET_STM/TARGET_STM32F0/STM32Cube_FW/stm32f0xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32F1/STM32Cube_FW/stm32f1xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32F2/STM32Cube_FW/stm32f2xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32F3/STM32Cube_FW/stm32f3xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/stm32f4xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32F7/STM32Cube_FW/stm32f7xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32G0/STM32Cube_FW/stm32g0xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32G4/STM32Cube_FW/stm32g4xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32H7/STM32Cube_FW/stm32h7xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32L0/STM32Cube_FW/stm32l0xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32L4/STM32Cube_FW/stm32l4xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32L5/STM32Cube_FW/stm32l5xx_hal_conf.h
  targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/stm32wbxx_hal_conf.h
Labels: devices: st, ready for merge, release-type: patch, stale

#14361 CMake: support signing TF-M targets with post binary hooks
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/scripts/generate_mbed_image.py
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/scripts/mbed_set_post_build_tfm.cmake
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/musca_b1-root-rsa-3072.md
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/musca_b1-root-rsa-3072.pem
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/musca_b1-root-rsa-3072_1.pem
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/musca_s1-root-rsa-3072.md
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/musca_s1-root-rsa-3072.pem
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/musca_s1-root-rsa-3072_1.pem
Labels: ready for merge, release-type: feature

#14374 targets: Remove target. prefix from ARM-CM3DS-MPS2 override
  targets/targets.json
Labels: ready for merge, release-type: patch, stale

#14373 Add bare metal support to Nuvoton targets
  targets/TARGET_NUVOTON/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M480/device/TOOLCHAIN_ARM_MICRO/M487.sct
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_ARM_MICRO/TARGET_NU_XRAM_SUPPORTED/NUC472.sct
  targets/TARGET_NUVOTON/TARGET_NUC472/device/TOOLCHAIN_ARM_MICRO/TARGET_NU_XRAM_UNSUPPORTED/NUC472.sct
  targets/targets.json
Labels: devices: nuvoton, ready for merge, release-type: patch

#14323 Bring in MIMXRT1050_EVK changes from feature-wisun branch
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/flash_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/spi_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PeripheralNames.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PeripheralPins.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/flash_defines.h
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/fsl_clock_config.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/specific.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/xip/evkbimxrt1050_sdram_ini_dcd.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/drivers/fsl_lpspi.c
Labels: devices: nxp, ready for merge, release-type: patch

#14377 feature-cmake-object-libraries: BLE as OBJECT library
  connectivity/CMakeLists.txt
  connectivity/FEATURE_BLE/CMakeLists.txt
  connectivity/FEATURE_BLE/libraries/CMakeLists.txt
  connectivity/FEATURE_BLE/libraries/TARGET_CORDIO_LL/CMakeLists.txt
  connectivity/FEATURE_BLE/source/CMakeLists.txt
  connectivity/FEATURE_BLE/source/gap/CMakeLists.txt
  connectivity/FEATURE_BLE/source/gatt/CMakeLists.txt
  connectivity/FEATURE_BLE/source/generic/CMakeLists.txt
  connectivity/FEATURE_BLE/source/pal/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_2/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_MS/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_CYW43XXX/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_CYW43XXX/TARGET_PSOC6/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_CYW43XXX/firmware/COMPONENT_43012/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_CYW43XXX/firmware/COMPONENT_43438/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_CYW43XXX/firmware/COMPONENT_4343W/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_CYW43XXX/firmware/TARGET_CYW9P62S1_43012EVB_01/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/TARGET_Ambiq_Micro/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/TARGET_Ambiq_Micro/TARGET_Apollo3/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/TARGET_CY8C63XX/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/TARGET_STM32WB/CMakeLists.txt
Labels: needs: work, release-version: feature branch

#14390 Add extern "C" around am_hal_secure_ota.h functions
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/sdk/mcu/apollo3/hal/am_hal_secure_ota.h
Labels: ready for merge, release-type: patch

#14319 CMake: Refactor storage unittest cmake
  CMakeLists.txt
  UNITTESTS/mbed_unittest.py
  UNITTESTS/stubs/hal/CMakeLists.txt
  UNITTESTS/stubs/platform/CMakeLists.txt
  UNITTESTS/unit_test/test.py
  storage/blockdevice/tests/UNITTESTS/CMakeLists.txt
  storage/blockdevice/tests/UNITTESTS/SFDP/CMakeLists.txt
  storage/blockdevice/tests/UNITTESTS/blockdevice/BufferedBlockDevice/CMakeLists.txt
  storage/blockdevice/tests/UNITTESTS/blockdevice/BufferedBlockDevice/test_BufferedBlockDevice.cpp
  storage/blockdevice/tests/UNITTESTS/blockdevice/CMakeLists.txt
  storage/blockdevice/tests/UNITTESTS/blockdevice/ChainingBlockDevice/CMakeLists.txt
  storage/blockdevice/tests/UNITTESTS/blockdevice/ChainingBlockDevice/test_ChainingBlockDevice.cpp
  storage/blockdevice/tests/UNITTESTS/blockdevice/ExhaustibleBlockDevice/CMakeLists.txt
  storage/blockdevice/tests/UNITTESTS/blockdevice/ExhaustibleBlockDevice/test_ExhaustibleBlockDevice.cpp
  storage/blockdevice/tests/UNITTESTS/blockdevice/FlashSimBlockDevice/CMakeLists.txt
  storage/blockdevice/tests/UNITTESTS/blockdevice/FlashSimBlockDevice/test_FlashSimBlockDevice.cpp
  storage/blockdevice/tests/UNITTESTS/blockdevice/HeapBlockDevice/CMakeLists.txt
  storage/blockdevice/tests/UNITTESTS/blockdevice/MBRBlockDevice/CMakeLists.txt
  storage/blockdevice/tests/UNITTESTS/blockdevice/MBRBlockDevice/test_MBRBlockDevice.cpp
  storage/blockdevice/tests/UNITTESTS/blockdevice/ObservingBlockDevice/CMakeLists.txt
  storage/blockdevice/tests/UNITTESTS/blockdevice/ObservingBlockDevice/test_ObservingBlockDevice.cpp
  storage/blockdevice/tests/UNITTESTS/blockdevice/ProfilingBlockDevice/CMakeLists.txt
  storage/blockdevice/tests/UNITTESTS/blockdevice/ProfilingBlockDevice/test_ProfilingBlockDevice.cpp
  storage/blockdevice/tests/UNITTESTS/blockdevice/ReadOnlyBlockDevice/CMakeLists.txt
  storage/blockdevice/tests/UNITTESTS/blockdevice/ReadOnlyBlockDevice/test_ReadOnlyBlockDevice.cpp
  storage/blockdevice/tests/UNITTESTS/blockdevice/SlicingBlockDevice/CMakeLists.txt
Labels: ready for merge, release-version: feature branch

#14391 Update secure binaries with platform init fix for ARM_MUSCA_S1
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/VERSION.txt
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/tfm_s.axf
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/tfm_s.bin
Labels: devices: arm, ready for merge, release-type: patch

#14367 fix typo: replace underscore by hyphen in lwipstack/mbed_lib.json
  connectivity/lwipstack/mbed_lib.json
Labels: component: connectivity, ready for merge, release-type: patch, stale

#14294 CMake: Refactor Mbed OS Platform UNITTESTS
  CMakeLists.txt
  UNITTESTS/stubs/platform/CMakeLists.txt
  UNITTESTS/stubs/platform/FileHandle_stub.cpp
  UNITTESTS/stubs/storage/CMakeLists.txt
  platform/tests/UNITTESTS/ATCmdParser/CMakeLists.txt
  platform/tests/UNITTESTS/CMakeLists.txt
  platform/tests/UNITTESTS/CircularBuffer/CMakeLists.txt
Labels: ready for merge, release-version: feature branch

#14331 CMake: Refactor storage filesystemstore unittest cmake
  CMakeLists.txt
  storage/kvstore/filesystemstore/tests/UNITTESTS/CMakeLists.txt
  storage/kvstore/filesystemstore/tests/UNITTESTS/FileSystemStore/CMakeLists.txt
Labels: ready for merge, release-version: feature branch

#14392 STM32WB: enable QSPI for custom boards
  targets/TARGET_STM/TARGET_STM32WB/objects.h
  targets/TARGET_STM/qspi_api.c
Labels: devices: st, ready for merge, release-type: patch

#14387 Update serial_api.c - Issue #14353 - Setting BufferedSerial pin to NC throws runtime assertion
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/serial_api.c
Labels: devices: nxp, ready for merge, release-type: patch

#14301 Add bare metal support to Renesas targets
  targets/targets.json
Labels: ready for merge, release-type: patch, stale

#14327 [feature-wisun] Update Nanostack
  features/nanostack/sal-stack-nanostack/nanostack/ws_bbr_api.h
  features/nanostack/sal-stack-nanostack/nanostack/ws_management_api.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps/Generic/protocol_6lowpan_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/Thread/thread_management_if.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api_internal.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common_defines.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_config.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_empty_functions.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_management_api.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_lib.c
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_lib.h
  features/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.c
  features/nanostack/sal-stack-nanostack/source/Common_Protocols/ipv6.c
  features/nanostack/sal-stack-nanostack/source/Common_Protocols/ipv6.h
  features/nanostack/sal-stack-nanostack/source/Core/include/ns_monitor.h
  features/nanostack/sal-stack-nanostack/source/Core/include/ns_socket.h
  features/nanostack/sal-stack-nanostack/source/Core/ns_monitor.c
  features/nanostack/sal-stack-nanostack/source/Core/ns_socket.c
  features/nanostack/sal-stack-nanostack/source/DHCPv6_Server/DHCPv6_Server_service.c
  features/nanostack/sal-stack-nanostack/source/DHCPv6_Server/DHCPv6_server_service.h
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_data_buffer.h
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_defines.h
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mcps_sap.c
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_mcps_sap.h
  features/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_pd_sap.c
  features/nanostack/sal-stack-nanostack/source/MPL/mpl.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_control.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_control.h
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_data.c
  features/nanostack/sal-stack-nanostack/source/RPL/rpl_upward.c
  features/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_api.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/key_sec_prot/key_sec_prot.c
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot.h
  features/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_cfg.h
  features/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/fhss_ws.c
  features/nanostack/sal-stack-nanostack/source/Service_Libs/utils/ns_conf.c
  features/nanostack/sal-stack-nanostack/source/ipv6_stack/ipv6_routing_table.c
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6_server.c
  features/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6_server.h
Labels: ready for merge, release-version: feature branch, stale

#14393 Doc update: post build now supported on TF-M targets
  tools/cmake/README.md
Labels: component: tools, ready for merge, release-type: patch

#14347 Add bare metal support to Ambiq targets
  targets/targets.json
Labels: ready for merge, release-type: patch, stale

#14293 STM32L4 : align CMakeLists.txt with all STM32
  targets/TARGET_STM/TARGET_STM32L4/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/STM32Cube_FW/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/STM32Cube_FW/STM32L4xx_HAL_Driver/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/STM32Cube_FW/STM32L4xx_HAL_Driver/Legacy/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14407 Add integer overflow check to the malloc wrappers
  platform/source/mbed_alloc_wrappers.cpp
Labels: component: core, ready for merge, release-type: patch

#14372 S1SBP6A: Add bare metal support
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/device/TOOLCHAIN_ARM_STD/s1sbp6a.sct
  targets/targets.json
Labels: devices: samsung, ready for merge, release-type: patch

#14401 Workaround for Cortex-M33 Arm toochain linking
  tools/cmake/cores/Cortex-M33-NS.cmake
  tools/cmake/cores/Cortex-M33.cmake
Labels: component: tools, ready for merge, release-type: patch

#14402 Fix sys/stat.h issue for unit tests on macOS
  UNITTESTS/target_h/platform/mbed_retarget.h
Labels: component: test, ready for merge, release-type: patch

#14352 CMake: Refactor event unittest cmake
  CMakeLists.txt
  UNITTESTS/stubs/CMakeLists.txt
  UNITTESTS/stubs/events/CMakeLists.txt
  events/tests/UNITTESTS/CMakeLists.txt
  events/tests/UNITTESTS/equeue/CMakeLists.txt
Labels: ready for merge, release-version: feature branch, stale

#14362 Fix imgtool import for CYTFM_064B0S2_4343W signing
  tools/targets/ARM_MUSCA.py
  tools/targets/__init__.py
Labels: ready for merge, release-type: patch

#14410 CMake: Fix Renesas build error on Linux
  connectivity/drivers/emac/TARGET_RENESAS_EMAC/CMakeLists.txt
  connectivity/drivers/emac/TARGET_RENESAS_EMAC/TARGET_RZ_A1XX/CMakeLists.txt
  connectivity/drivers/emac/TARGET_RENESAS_EMAC/TARGET_RZ_A2XX/CMakeLists.txt
Labels: ready for merge

#14405 Update event queue generation process
  events/include/events/equeue.h
  events/source/equeue.c
Labels: component: core, ready for merge

#14346 Add bare metal support to Analog Device targets
  targets/targets.json
Labels: ready for merge, release-type: patch

#14379 Nuvoton: Enlarge NuMaker PWM duty cycle range
  targets/TARGET_NUVOTON/TARGET_M251/device/StdDriver/inc/m251_pwm.h
  targets/TARGET_NUVOTON/TARGET_M251/device/StdDriver/src/m251_pwm.c
  targets/TARGET_NUVOTON/TARGET_M251/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_M261/device/StdDriver/m261_epwm.c
  targets/TARGET_NUVOTON/TARGET_M261/device/StdDriver/m261_epwm.h
  targets/TARGET_NUVOTON/TARGET_M261/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_M451/device/StdDriver/m451_pwm.c
  targets/TARGET_NUVOTON/TARGET_M451/device/StdDriver/m451_pwm.h
  targets/TARGET_NUVOTON/TARGET_M451/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_M480/device/StdDriver/inc/m480_epwm.h
  targets/TARGET_NUVOTON/TARGET_M480/device/StdDriver/src/m480_epwm.c
  targets/TARGET_NUVOTON/TARGET_M480/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/device/StdDriver/nano100_pwm.c
  targets/TARGET_NUVOTON/TARGET_NANO100/device/StdDriver/nano100_pwm.h
  targets/TARGET_NUVOTON/TARGET_NANO100/pwmout_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/device/StdDriver/nuc472_pwm.c
  targets/TARGET_NUVOTON/TARGET_NUC472/device/StdDriver/nuc472_pwm.h
  targets/TARGET_NUVOTON/TARGET_NUC472/pwmout_api.c
Labels: devices: nuvoton, ready for merge, release-type: patch

#14342 use calloc for new_interface_server
  connectivity/lwipstack/lwip/src/core/lwip_dns.c
  connectivity/lwipstack/lwip/src/include/lwip/dns.h
Labels: component: connectivity, ready for merge, release-type: patch

#14419 STM32: remove mbed.h include in connectivity
  connectivity/drivers/ble/FEATURE_BLE/TARGET_STM32WB/HCIDriver.cpp
  connectivity/drivers/emac/TARGET_STM/stm32xx_emac.cpp
Labels: component: connectivity, devices: st, ready for merge, release-type: patch

#14423 STM32: AnalogOut: do not call HAL_DAC_Start in dac_write
  targets/TARGET_STM/TARGET_STM32F0/analogout_device.c
  targets/TARGET_STM/TARGET_STM32F1/analogout_device.c
  targets/TARGET_STM/TARGET_STM32F2/analogout_device.c
  targets/TARGET_STM/TARGET_STM32F3/analogout_device.c
  targets/TARGET_STM/TARGET_STM32F4/analogout_device.c
  targets/TARGET_STM/TARGET_STM32F7/analogout_device.c
  targets/TARGET_STM/TARGET_STM32G0/analogout_device.c
  targets/TARGET_STM/TARGET_STM32G4/analogout_device.c
  targets/TARGET_STM/TARGET_STM32H7/analogout_device.c
  targets/TARGET_STM/TARGET_STM32L0/analogout_device.c
  targets/TARGET_STM/TARGET_STM32L1/analogout_device.c
  targets/TARGET_STM/TARGET_STM32L4/analogout_device.c
  targets/TARGET_STM/TARGET_STM32L5/analogout_device.c
  targets/TARGET_STM/TARGET_STM32WL/analogout_device.c
  targets/TARGET_STM/analogout_api.c
Labels: devices: st, ready for merge, release-type: patch

#14422 Fix Lora timer cancellation
  UNITTESTS/stubs/LoRaWANTimer_stub.cpp
  connectivity/lorawan/lorastack/mac/LoRaMac.cpp
  connectivity/lorawan/system/LoRaWANTimer.cpp
  connectivity/lorawan/system/LoRaWANTimer.h
Labels: component: connectivity, ready for merge, release-type: feature

#14416 CMake: Fix FF1705_L151CC build
  targets/TARGET_STM/TARGET_STM32L1/TARGET_STM32L151xC/TARGET_XDOT_L151CC/CMakeLists.txt
Labels: devices: st, ready for merge, release-type: patch

#14403 update baud rate of CY8CKIT064B0S2_4343W to 115200
  platform/mbed_lib.json
Labels: devices: cypress, ready for merge, release-type: patch

#14411 CMake: Fix Cortex-A9 flags for GCC_ARM toolchain
  tools/cmake/cores/Cortex-A9.cmake
Labels: component: tools, ready for merge, release-type: patch

#14418 EP_ATLAS: Fix mbedtools build errors
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_ATLAS/ONBOARD_TELIT_ME310.cpp
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_EP_ATLAS/usb_stdio.cpp
Labels: component: connectivity, devices: nordic, ready for merge, release-type: patch

#14427 CMake: Convert mbed-lorawan CMake library target to OBJECT
  connectivity/CMakeLists.txt
  connectivity/drivers/lora/COMPONENT_SX126X/CMakeLists.txt
  connectivity/drivers/lora/COMPONENT_SX1272/CMakeLists.txt
  connectivity/drivers/lora/COMPONENT_SX1276/CMakeLists.txt
  connectivity/drivers/lora/TARGET_STM32WL/CMakeLists.txt
  connectivity/lorawan/CMakeLists.txt
  connectivity/lorawan/lorastack/CMakeLists.txt
  connectivity/lorawan/system/CMakeLists.txt
Labels: needs: CI, release-version: feature branch

#14430 Unittest ble addition
  UNITTESTS/CMakeLists.txt
  UNITTESTS/fakes/CMakeLists.txt
  UNITTESTS/fakes/ble/BLE.cpp
  UNITTESTS/fakes/ble/CMakeLists.txt
  UNITTESTS/fakes/ble/GapImpl_mock.h
  UNITTESTS/fakes/ble/GattClientImpl_mock.h
  UNITTESTS/fakes/ble/GattServerImpl_mock.h
  UNITTESTS/fakes/ble/SecurityManagerImpl_mock.h
  UNITTESTS/fakes/ble/ble_mocks.h
  UNITTESTS/fakes/ble/source/GattServerImpl.h
  UNITTESTS/fakes/ble/source/GattServerImpl_mock.cpp
  UNITTESTS/fakes/ble/source/generic/GapImpl.h
  UNITTESTS/fakes/ble/source/generic/GattClientImpl.h
  UNITTESTS/fakes/ble/source/generic/SecurityManagerImpl.h
  UNITTESTS/fakes/events/CMakeLists.txt
  UNITTESTS/fakes/events/events/EventQueue.cpp
  UNITTESTS/fakes/events/events/EventQueue.h
  UNITTESTS/target_h/platform/cxxsupport/mstd_tuple
  connectivity/FEATURE_BLE/include/ble/common/BLERoles.h
Labels: needs: review, release-version: feature branch

#14262 [feature-wisun] Added missing const qualifier to mesh ethernet mac addr get
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
Labels: ready for merge, release-version: feature branch

#14429 CMake: Fix STM target build failures
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/TOOLCHAIN_ARM/startup_stm32f407xx.S
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TOOLCHAIN_GCC_ARM/stm32f411xe.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TOOLCHAIN_GCC_ARM/stm32f412xg.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TOOLCHAIN_GCC_ARM/stm32f413xh.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TOOLCHAIN_GCC_ARM/stm32f429xi.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TOOLCHAIN_GCC_ARM/stm32f446xe.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TOOLCHAIN_GCC_ARM/stm32f469xi.ld
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_STM32H747xI_CM4/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_STM32H747xI_CM4/TOOLCHAIN_GCC_ARM/stm32h747xI_CM4.ld
Labels: devices: st, ready for merge, release-type: patch

#14428 CMake targets: remove labels usage, not required anymore
  targets/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K66F/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_K82F/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KL43Z/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_KW41Z/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K22F/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14421 SDP-K1: enable IAR compilation
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_SDP_K1/PeripheralPins.c
Labels: ready for merge, release-type: patch

#14243 STM32: Add HSE support to RTC
  targets/TARGET_STM/mbed_overrides.c
  targets/TARGET_STM/rtc_api.c
  targets/TARGET_STM/rtc_api_hal.h
  targets/targets.json
Labels: ready for merge, release-type: patch

#14251 Mesh API: Get and validate functions for PHY mode and channel plan IDs
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-version: feature branch

#14198 Feature bluetooth traces
  .github/issue_template.md
  connectivity/FEATURE_BLE/libraries/cordio_stack/wsf/include/wsf_trace.h
  connectivity/FEATURE_BLE/mbed_lib.json
  connectivity/FEATURE_BLE/source/CMakeLists.txt
  connectivity/FEATURE_BLE/source/common/ble_trace_helpers.cpp
  connectivity/FEATURE_BLE/source/common/ble_trace_helpers.h
  connectivity/FEATURE_BLE/source/cordio/CMakeLists.txt
  connectivity/FEATURE_BLE/source/cordio/driver/CordioHCIDriver.cpp
  connectivity/FEATURE_BLE/source/cordio/driver/CordioHCITransportDriver.cpp
  connectivity/FEATURE_BLE/source/cordio/mbed_lib.json
  connectivity/FEATURE_BLE/source/cordio/source/BLEInstanceBaseImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/GattServerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalAttClientImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalPrivateAddressControllerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/stack_adaptation/mbed_wsf_trace.c
  connectivity/FEATURE_BLE/source/cordio/stack_adaptation/mbed_wsf_trace.h
  connectivity/FEATURE_BLE/source/generic/CMakeLists.txt
  connectivity/FEATURE_BLE/source/generic/FileSecurityDb.cpp
  connectivity/FEATURE_BLE/source/generic/FileSecurityDb.h
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
  connectivity/FEATURE_BLE/source/generic/GattClientImpl.cpp
  connectivity/FEATURE_BLE/source/generic/KVStoreSecurityDb.cpp
  connectivity/FEATURE_BLE/source/generic/KVStoreSecurityDb.h
  connectivity/FEATURE_BLE/source/generic/MemorySecurityDb.cpp
  connectivity/FEATURE_BLE/source/generic/MemorySecurityDb.h
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.cpp
  connectivity/FEATURE_BLE/source/generic/SecurityDb.cpp
  connectivity/FEATURE_BLE/source/generic/SecurityDb.h
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.cpp
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_2/BlueNrg2HCIDriver.cpp
  connectivity/drivers/ble/FEATURE_BLE/TARGET_STM32WB/HCIDriver.cpp
Labels: ready for merge, release-type: patch

#13209 Implement polymorphism for DigitalIn/Out/InOut
  drivers/include/drivers/DigitalIn.h
  drivers/include/drivers/DigitalInOut.h
  drivers/include/drivers/DigitalOut.h
  drivers/include/drivers/interfaces/InterfaceDigitalIn.h
  drivers/include/drivers/interfaces/InterfaceDigitalInOut.h
  drivers/include/drivers/interfaces/InterfaceDigitalOut.h
Labels: ready for merge, release-type: feature

#14396 TF-M: Switch to vanilla TF-M's OS wrapper
  drivers/usb/include/usb/USBCDC_ECM.h
  drivers/usb/include/usb/USBMIDI.h
  drivers/usb/include/usb/USBMSD.h
  drivers/usb/include/usb/internal/AsyncOp.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/TARGET_TFM_V8M/src/tfm_ns_interface.c
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/VERSION.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/os_wrapper/common.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/os_wrapper/mutex.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/os_wrapper/semaphore.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/os_wrapper/thread.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/os_wrapper/tick.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/src/os_wrapper_cmsis_rtos_v2.c
Labels: component: core, component: hal, component: security, ready for merge, release-type: patch

#14263 [mbed-os-5.15] Added missing const qualifier to mesh ethernet mac addr get
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
Labels: ready for merge, release-version: 5.15.7

#14147 [mbed-os-5.15] Corrected nanostack coverity warnings
  features/nanostack/mbed-mesh-api/source/NanostackEMACInterface.cpp
  features/nanostack/mbed-mesh-api/source/NanostackPPPInterface.cpp
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_random.c
Labels: ready for merge, release-version: 5.15.7

#14443 [mbed-os-5.15] Improve WisunInterface set_network_size docs
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/mbed_lib.json
Labels: ready for merge, release-version: 5.15.7

#14408 Add integer overflow check to the malloc wrappers
  platform/source/mbed_alloc_wrappers.cpp
Labels: Release review required, needs: work, release-version: 5.15.7

#14473 Update cmake supported example list
  tools/test/examples/cloud_examples_cmake.json
  tools/test/examples/examples_cmake.json
Labels: component: tools, needs: review, needs: work, release-type: patch

#14431 [feature-wisun] Improve WisunInterface set_network_size docs
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/mbed_lib.json
Labels: ready for merge, release-version: feature branch

#14438 Update Event Queue Documentation
  events/README.md
  events/include/events/Event.h
  events/include/events/EventQueue.h
  events/include/events/UserAllocatedEvent.h
  events/include/events/equeue.h
Labels: component: core, ready for merge, release-type: patch

#14447 Remove paths to fetched TF-M repos from .gitignore
  .gitignore
Labels: ready for merge, release-type: patch

#14450 FPGA SPI : decrease test frequency for ASYNC test cases
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/spi/main.cpp
Labels: component: hal, ready for merge, release-type: patch

#14437 Remove ownership/acquire in QSPI/OSPI driver
  drivers/include/drivers/OSPI.h
  drivers/include/drivers/QSPI.h
  drivers/source/OSPI.cpp
  drivers/source/QSPI.cpp
Labels: component: core, component: hal, needs: work, release-type: feature

#14455 Fix RTOS & OS wrapper header conflicts for Mbed CLI 1
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/os_wrapper/.mbedignore
Labels: component: core, component: security, ready for merge, release-type: patch

#14456 Fix define MBED_EXCLUSIVE_ACCESS for Apple M1 (__aarch64__) computers
  platform/include/platform/mbed_atomic.h
Labels: ready for merge

#14466 GigaDevice: Add bare metal support for targets
  targets/TARGET_GigaDevice/TARGET_GD32F30X/TARGET_GD32F307VG/device/TOOLCHAIN_ARM_MICRO/gd32f307vg.sct
  targets/TARGET_GigaDevice/TARGET_GD32F30X/TARGET_GD32F307VG/device/TOOLCHAIN_ARM_MICRO/startup_gd32f30x_cl.S
  targets/TARGET_GigaDevice/TARGET_GD32F30X/TARGET_GD32F307VG/device/TOOLCHAIN_ARM_STD/gd32f307vg.sct
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/device/TOOLCHAIN_ARM_MICRO/gd32f450zi.sct
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/device/TOOLCHAIN_ARM_MICRO/startup_gd32f450.S
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/device/TOOLCHAIN_ARM_STD/gd32f450zi.sct
  targets/targets.json
Labels: devices: gigadevice, ready for merge, release-type: patch

#14434 STM32 I2C : correct deinit
  targets/TARGET_STM/i2c_api.c
Labels: ready for merge

#14442 Improve WisunInterface set_network_size docs
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  connectivity/nanostack/mbed-mesh-api/mbed_lib.json
Labels: component: mesh, ready for merge, release-type: patch

#14444 STM32: reset GPIO value is analog mode
  targets/TARGET_STM/TARGET_STM32F0/analogout_device.c
  targets/TARGET_STM/TARGET_STM32F1/analogout_device.c
  targets/TARGET_STM/TARGET_STM32F2/analogout_device.c
  targets/TARGET_STM/TARGET_STM32F3/analogout_device.c
  targets/TARGET_STM/TARGET_STM32G0/analogout_device.c
  targets/TARGET_STM/TARGET_STM32G4/analogout_device.c
  targets/TARGET_STM/TARGET_STM32L0/analogout_device.c
  targets/TARGET_STM/TARGET_STM32L1/analogout_device.c
  targets/TARGET_STM/TARGET_STM32L4/analogout_device.c
  targets/TARGET_STM/TARGET_STM32L5/analogout_device.c
  targets/TARGET_STM/TARGET_STM32WL/analogout_device.c
  targets/TARGET_STM/ospi_api.c
  targets/TARGET_STM/pwmout_api.c
  targets/TARGET_STM/qspi_api.c
  targets/TARGET_STM/serial_api.c
  targets/TARGET_STM/stm_spi_api.c
Labels: devices: st, ready for merge, release-type: patch

#14445 STM32WB/STM32WL: watchdog LSI frequency
  targets/TARGET_STM/watchdog_api.c
Labels: devices: st, ready for merge, release-type: patch

#14472 CMake: support `OUTPUT_EXT` from `targets.json`
  CMakeLists.txt
  targets/targets.json
Labels: ready for merge, release-type: patch

#14460 Ambiq: Fix baremetal build profile when using CLI 1
  connectivity/drivers/ble/FEATURE_BLE/TARGET_Ambiq_Micro/mbed_lib.json
Labels: component: connectivity, ready for merge, release-type: patch
