Repository ARMmbed/mbed-os, pull requests merged in 2021-02, with the labels that each got.

#14092 NFC: Add support for M24SR driver
  connectivity/drivers/nfc/CMakeLists.txt
  connectivity/drivers/nfc/TARGET_M24SR/CMakeLists.txt
  connectivity/drivers/nfc/TARGET_M24SR/include/nfc/m24sr_driver.h
  connectivity/drivers/nfc/TARGET_M24SR/mbed_lib.json
  connectivity/drivers/nfc/TARGET_M24SR/source/m24sr_driver.cpp
Labels: ready for merge, release-type: patch

#14197 Upgrade gtest to 1.10
  UNITTESTS/README.md
  UNITTESTS/googletest-CMakeLists.txt.in
  connectivity/netsocket/tests/UNITTESTS/netsocket/EthernetInterface/test_EthernetInterface.cpp
  connectivity/netsocket/tests/UNITTESTS/netsocket/PPPInterface/test_PPPInterface.cpp
Labels: ready for merge, release-type: patch

#14225 add tracing to scan state
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
Labels: needs: review, release-version: feature branch

#14201 Update maximum version of intelhex to 2.3.0
  requirements.txt
Labels: ready for merge, release-type: patch, stale

#14057 [mbed-os-5.15] Fix `mbed device-management` command for Python 3.8
  requirements.txt
Labels: ready for merge, release-version: 5.15.7

#14181 CMake: Add support for Mbed TLS Greentea tests
  connectivity/mbedtls/tests/TESTS/mbedtls/multi/CMakeLists.txt
  connectivity/mbedtls/tests/TESTS/mbedtls/sanity/CMakeLists.txt
  connectivity/mbedtls/tests/TESTS/mbedtls/selftest/CMakeLists.txt
  tools/cmake/README.md
Labels: ready for merge, release-type: patch, stale

#14196 CMake cores: fix cpu/fpu flags
  tools/cmake/cores/Cortex-A9.cmake
  tools/cmake/cores/Cortex-M1.cmake
  tools/cmake/cores/Cortex-M23-NS.cmake
  tools/cmake/cores/Cortex-M23.cmake
  tools/cmake/cores/Cortex-M33-NS.cmake
  tools/cmake/cores/Cortex-M33.cmake
  tools/cmake/cores/Cortex-M33F-NS.cmake
  tools/cmake/cores/Cortex-M33F.cmake
  tools/cmake/cores/Cortex-M33FE-NS.cmake
  tools/cmake/cores/Cortex-M33FE.cmake
  tools/cmake/cores/Cortex-M7F.cmake
  tools/cmake/cores/Cortex-M7FD.cmake
Labels: ready for merge, release-type: patch, stale

#14178 Fix CI in feature-std-pin-name
  .travis.yml
  hal/source/mbed_pinmap_default.cpp
  hal/tests/TESTS/mbed_hal/gpio/CMakeLists.txt
  hal/tests/TESTS/pin_names/arduino_uno/main.cpp
  storage/blockdevice/COMPONENT_SD/mbed_lib.json
Labels: needs: work, release-version: feature branch

#14212 Expose the public Stream API
  mbed.h
Labels: ready for merge, release-type: patch, stale

#14202 BLE: return OK when stopping advertising set that is not active
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
Labels: ready for merge, release-type: patch, stale

#14195 LoraRadio test update for baremetal support
  TESTS/configs/baremetal.json
  connectivity/drivers/lora/COMPONENT_SX126X/mbed_lib.json
  connectivity/drivers/lora/COMPONENT_SX1272/mbed_lib.json
  connectivity/drivers/lora/COMPONENT_SX1276/mbed_lib.json
  connectivity/lorawan/mbed_lib.json
  connectivity/lorawan/tests/TESTS/lorawan/loraradio/main.cpp
Labels: ready for merge, release-type: patch, stale

#13979 Support for ST STM32 NUCLEO-G431KB Development Board
  targets/TARGET_STM/TARGET_STM32G4/TARGET_STM32G431xB/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32G4/TARGET_STM32G431xB/TARGET_NUCLEO_G431KB/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32G4/TARGET_STM32G431xB/TARGET_NUCLEO_G431KB/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32G4/TARGET_STM32G431xB/TARGET_NUCLEO_G431KB/PinNames.h
  targets/TARGET_STM/TARGET_STM32G4/TARGET_STM32G431xB/TOOLCHAIN_GCC_ARM/stm32g431xb.ld
  targets/TARGET_STM/TARGET_STM32G4/TARGET_STM32G431xB/system_clock.c
  targets/TARGET_STM/USBPhyHw.h
  targets/targets.json
Labels: ready for merge, release-type: patch, scope: new-target, stale

#14213 Add cortex-m55 to CMake support
  cmsis/CMSIS_5/CMSIS/RTOS2/RTX/CMakeLists.txt
  tools/cmake/cores/Cortex-M55.cmake
  tools/cmake/toolchain.cmake
Labels: ready for merge, release-type: patch

#14190 CMake cores: fix NS cores
  tools/cmake/cores/Cortex-M23-NS.cmake
  tools/cmake/cores/Cortex-M23.cmake
  tools/cmake/cores/Cortex-M33-NS.cmake
  tools/cmake/cores/Cortex-M33.cmake
  tools/cmake/cores/Cortex-M33F-NS.cmake
  tools/cmake/cores/Cortex-M33F.cmake
Labels: ready for merge, release-type: patch, stale

#14141 Pin names: Make improvements to code
  hal/tests/TESTS/pin_names/pinvalidate.py
  hal/tests/TESTS/pin_names/pinvalidate_test.py
Labels: needs: work, release-version: feature branch

#14204 Set executable suffix in CMake
  CMakeLists.txt
  tools/cmake/app.cmake
Labels: ready for merge, release-type: patch

#14203 Adding USB HS Support to the SDP-K1
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_SDP_K1/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_SDP_K1/PeripheralPins.c
  targets/targets.json
Labels: ready for merge, release-type: patch

#14215 STM: Fix Hal_GetTick wrap around errors
  targets/TARGET_STM/hal_tick_overrides.c
Labels: ready for merge, release-type: patch

#14233 Musca S1: include missing `cmsis_nvic.h`
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/device/cmsis.h
Labels: release-version: feature branch

#14031 BlockDevices: specify mbed namespace where needed
  drivers/usb/include/usb/USBMSD.h
  drivers/usb/source/PolledQueue.cpp
  drivers/usb/source/TaskBase.cpp
  drivers/usb/source/USBMSD.cpp
  storage/blockdevice/COMPONENT_DATAFLASH/include/DataFlash/DataFlashBlockDevice.h
  storage/blockdevice/COMPONENT_FLASHIAP/include/FlashIAP/FlashIAPBlockDevice.h
  storage/blockdevice/COMPONENT_I2CEE/include/I2CEE/I2CEEBlockDevice.h
  storage/blockdevice/COMPONENT_OSPIF/include/OSPIF/OSPIFBlockDevice.h
  storage/blockdevice/COMPONENT_QSPIF/include/QSPIF/QSPIFBlockDevice.h
  storage/blockdevice/COMPONENT_SPIF/include/SPIF/SPIFBlockDevice.h
  storage/kvstore/kv_config/source/kv_config.cpp
Labels: ready for merge, release-type: patch

#14179 Fix minimal-printf floating point decimal output error
  platform/source/minimal-printf/mbed_printf_implementation.c
Labels: ready for merge, release-type: patch, stale

#14232 CMake: Fix Cypress MCU_PSOC6_M4 build
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/rtos/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14230 nRF52: clean pwm structures on deinit
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/pinmap_ex.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/pinmap_ex.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/pwmout_api.c
Labels: ready for merge, release-type: patch

#14205 CMake: better detection of memap dependencies
  CMakeLists.txt
  tools/cmake/CheckPythonPackage.cmake
  tools/cmake/app.cmake
  tools/cmake/requirements.txt
Labels: ready for merge, release-type: patch

#13975 Update EventQueue API to use chrono times
  events/include/events/EventQueue.h
  events/source/EventQueue.cpp
  events/tests/TESTS/events/queue/main.cpp
Labels: ready for merge, release-type: feature

#14238 Update list of licenses in LICENSE.md
  LICENSE.md
Labels: ready for merge, release-type: patch

#14250 example-psa - add MUSCA_S1 and update baudrate
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#14229 add stubs as libs
  UNITTESTS/fakes/CMakeLists.txt
  UNITTESTS/fakes/ble/BLE.cpp
  UNITTESTS/fakes/ble/CMakeLists.txt
  UNITTESTS/fakes/ble/GapImpl_mock.h
  UNITTESTS/fakes/ble/GattClientImpl_mock.h
  UNITTESTS/fakes/ble/GattServerImpl_mock.h
  UNITTESTS/fakes/ble/SecurityManagerImpl_mock.h
  UNITTESTS/fakes/ble/ble_mocks.h
  UNITTESTS/fakes/ble/source/GattServerImpl.h
  UNITTESTS/fakes/ble/source/generic/GapImpl.h
  UNITTESTS/fakes/ble/source/generic/GattClientImpl.h
  UNITTESTS/fakes/ble/source/generic/SecurityManagerImpl.h
  UNITTESTS/fakes/events/EventQueue.cpp
  UNITTESTS/fakes/events/EventQueue.h
  UNITTESTS/stubs/CMakeLists.txt
  UNITTESTS/target_h/platform/cxxsupport/mstd_tuple
Labels: needs: work, release-version: feature branch

#14241 Deprecate PSA key enrollment algorithms
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/inc/psa/crypto_extra.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/psa/crypto_client_struct.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/psa/crypto_extra.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/tfm_crypto_defs.h
Labels: needs: work, release-version: feature branch

#14254 Add implementation of MockGattServer::addService
  UNITTESTS/fakes/ble/CMakeLists.txt
  UNITTESTS/fakes/ble/GattServerImpl_mock.h
  UNITTESTS/fakes/ble/source/GattServerImpl_mock.cpp
  UNITTESTS/fakes/events/EventQueue.cpp
  UNITTESTS/target_h/platform/mbed_retarget.h
  connectivity/FEATURE_BLE/include/ble/common/ChainableEventHandler.h
  connectivity/FEATURE_BLE/include/ble/gatt/GattCharacteristic.h
Labels: needs: CI, release-version: feature branch

#14261 Add missing const qualifier to mesh ethernet mac addr get
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  connectivity/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
Labels: ready for merge, release-type: patch

#14257 BLE: Add APIs to get characteristic authorization callbacks.
  connectivity/FEATURE_BLE/include/ble/gatt/GattCharacteristic.h
Labels: ready for merge, release-type: feature

#14256 BLE: Add API to test the presence of an event handler in a chain.
  connectivity/FEATURE_BLE/include/ble/common/ChainableEventHandler.h
Labels: ready for merge, release-type: feature

#14248 MAX32625MBED: Gate ticker (timer0) clock on deepsleep
  targets/TARGET_Maxim/TARGET_MAX32625/sleep.c
Labels: ready for merge, release-type: patch

#14239 BLE: fix passkey for display being returned reversed
  connectivity/FEATURE_BLE/include/ble/SecurityManager.h
  connectivity/FEATURE_BLE/include/ble/common/BLETypes.h
  connectivity/FEATURE_BLE/mbed_lib.json
Labels: ready for merge, release-type: patch

#14268 CMake: Refactor NXP targets
  targets/TARGET_NXP/CMakeLists.txt
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/CMakeLists.txt
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/TARGET_LPC11XX/CMakeLists.txt
  targets/TARGET_NXP/TARGET_LPC176X/CMakeLists.txt
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_ARCH_PRO/CMakeLists.txt
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_MBED_LPC1768/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/TARGET_LPCXpresso/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/TARGET_FF_LPC546XX/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/TARGET_LPCXpresso/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/middleware/TARGET_USB/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14265 CMake: remove need for APP_TARGET
  CMakeLists.txt
  tools/cmake/set_linker_script.cmake
Labels: ready for merge, release-type: patch

#14266 Fix up some ST CMake targets
  targets/TARGET_STM/TARGET_STM32G4/TARGET_STM32G431xB/TARGET_NUCLEO_G431KB/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_PORTENTA_H7/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L073xZ/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R5xI/TARGET_NUCLEO_L4R5ZI/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14253 CMake: refactor Renesas targets
  targets/TARGET_RENESAS/CMakeLists.txt
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/CMakeLists.txt
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_GR_LYCHEE/CMakeLists.txt
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_RZ_A1H/CMakeLists.txt
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/CMakeLists.txt
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/TARGET_GR_MANGO/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14267 CMake: Refactor Nordic targets to be CMake buildsystem targets
  targets/TARGET_NORDIC/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/TARGET_SOFTDEVICE_NONE/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/components/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/integration/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/modules/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14269 CMake: Refactor Toshiba targets
  targets/TARGET_TOSHIBA/CMakeLists.txt
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/CMakeLists.txt
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14242 Ambiq Micro: refactor CMake targets
  targets/TARGET_Ambiq_Micro/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/COMPONENT_hm01b0/hm01b0/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/COMPONENT_lis2dh12/lis2dh12/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TARGET_SFE_ARTEMIS/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TARGET_SFE_ARTEMIS_ATP/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TARGET_SFE_ARTEMIS_DK/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TARGET_SFE_ARTEMIS_MODULE/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TARGET_SFE_ARTEMIS_NANO/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TARGET_SFE_ARTEMIS_THING_PLUS/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TARGET_SFE_EDGE/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TARGET_SFE_EDGE2/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14264 BLE: fix termination of periodic advertising sync
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.h
Labels: ready for merge, release-type: patch

#14279 CMake: Refactor Silicon Laboratories targets
  targets/TARGET_Silicon_Labs/CMakeLists.txt
  targets/TARGET_Silicon_Labs/TARGET_EFM32/CMakeLists.txt
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG/CMakeLists.txt
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG11/CMakeLists.txt
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFR32MG12/CMakeLists.txt
  targets/TARGET_Silicon_Labs/TARGET_SL_RAIL/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14235 CMake: Add post build operation support
  CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/CMakeLists.txt
  targets/TARGET_Cypress/scripts/PSOC6.py
  targets/TARGET_Cypress/scripts/mbed_set_post_build_cypress.cmake
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/TARGET_LPC11XX/CMakeLists.txt
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_ARCH_PRO/CMakeLists.txt
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_MBED_LPC1768/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/CMakeLists.txt
  targets/TARGET_NXP/scripts/LPC.py
  targets/TARGET_NXP/scripts/mbed_set_post_build_nxp.cmake
  tools/cmake/README.md
  tools/cmake/mbed_set_post_build.cmake
Labels: ready for merge, release-type: patch

#14272 Change CMAKE_BINARY_DIR to CMAKE_CURRENT_BINARY_DIR
  CMakeLists.txt
  tools/cmake/set_linker_script.cmake
  tools/cmake/toolchain.cmake
Labels: ready for merge, release-type: patch

#14276 CMake: refactor Samsung targets
  targets/TARGET_Samsung/CMakeLists.txt
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/CMakeLists.txt
  targets/TARGET_Samsung/TARGET_SIDK_S5JS100/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14277 Apollo3: Fix run time error due to memory mapping
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TOOLCHAIN_ARM_STD/AMA3B1KK.sct
Labels: ready for merge, release-type: patch

#14282 CMake: Refactor Nuvoton targets
  targets/TARGET_NUVOTON/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/TARGET_TFM/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/device/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_NS/device/TARGET_TFM/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_S/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_M23_S/TARGET_TFM/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2351/TARGET_NU_PFM_M2351/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M251/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M251/TARGET_NUMAKER_IOT_M252/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M261/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M261/TARGET_NUMAKER_IOT_M263A/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M451/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M480/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_NANO100/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_NANO100/device/TOOLCHAIN_ARM/NANO130.sct
  targets/TARGET_NUVOTON/TARGET_NUC472/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14245 STM32WL: I2C and ADC full support
  targets/TARGET_STM/TARGET_STM32WL/TARGET_STM32WL55xC/TARGET_NUCLEO_WL55JC/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32WL/analogin_device.c
  targets/TARGET_STM/TARGET_STM32WL/analogout_device.c
  targets/TARGET_STM/TARGET_STM32WL/i2c_device.h
  targets/TARGET_STM/i2c_api.c
Labels: ready for merge, release-type: patch

#14281 CMake: refactor GigaDevice targets
  targets/TARGET_GigaDevice/CMakeLists.txt
  targets/TARGET_GigaDevice/TARGET_GD32F30X/CMakeLists.txt
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14280 CMake: Refactor WIO_EMW3166 support
  connectivity/drivers/wifi/CMakeLists.txt
  connectivity/drivers/wifi/TARGET_WICED/CMakeLists.txt
  connectivity/drivers/wifi/TARGET_WICED/LICENSE-permissive-binary-license-1.0.txt
  connectivity/drivers/wifi/TARGET_WICED/README.md
  connectivity/drivers/wifi/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_WIO_EMW3166/libwiced_drivers.ar
  connectivity/drivers/wifi/TARGET_WICED/TOOLCHAIN_GCC_ARM/TARGET_WIO_EMW3166/libwiced_drivers.a
  connectivity/drivers/wifi/TARGET_WICED/TOOLCHAIN_IAR/TARGET_WIO_EMW3166/libwiced_drivers.a
  connectivity/drivers/wifi/TARGET_WICED/wiced_interface/WicedInterface.h
  connectivity/drivers/wifi/TARGET_WICED/wiced_interface/default_wifi_interface.cpp
  connectivity/drivers/wifi/TARGET_WICED/wiced_interface/wiced_emac.h
  targets/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_WIO_EMW3166/CMakeLists.txt
  targets/TARGET_WICED/CMakeLists.txt
  tools/cmake/README.md
Labels: ready for merge, release-type: patch

#14247 CMake: Refactor Greentea test CMakeLists.txt
  tools/cmake/README.md
  tools/cmake/mbed_greentea.cmake
Labels: ready for merge, release-type: patch, stale

#14244 Analog Devices: refactor CMake targets
  targets/TARGET_Analog_Devices/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TARGET_EV_COG_AD3029LZ/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TARGET_EV_COG_AD4050LZ/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14246 ARM FM: refactor CMake targets
  targets/TARGET_ARM_FM/CMakeLists.txt
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/CMakeLists.txt
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0/CMakeLists.txt
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M0P/CMakeLists.txt
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M3/CMakeLists.txt
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M4/CMakeLists.txt
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/TARGET_FVP_MPS2_M7/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14249 STM32WL : add LoRa support
  connectivity/drivers/lora/CMakeLists.txt
  connectivity/drivers/lora/TARGET_STM32WL/CMakeLists.txt
  connectivity/drivers/lora/TARGET_STM32WL/STM32WL_LoRaRadio.cpp
  connectivity/drivers/lora/TARGET_STM32WL/STM32WL_LoRaRadio.h
  connectivity/drivers/lora/TARGET_STM32WL/STM32WL_radio_driver.h
  connectivity/drivers/lora/TARGET_STM32WL/mbed_lib.json
  connectivity/lorawan/mbed_lib.json
  connectivity/lorawan/tests/TESTS/lorawan/loraradio/main.cpp
  targets/TARGET_STM/README.md
  targets/TARGET_STM/TARGET_STM32WL/README.md
  targets/TARGET_STM/TARGET_STM32WL/STM32Cube_FW/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14270 CMake Maxim: fix targets naming
  targets/TARGET_Maxim/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32620C/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32620C/TARGET_MAX32620FTHR/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32620C/TARGET_SDT32620B/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32625/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32625/TARGET_MAX32625MBED/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32625/TARGET_MAX32625PICO/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32625/TARGET_SDT32625B/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32625/device/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32630/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32630/TARGET_MAX32630FTHR/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14275 Fix ST targets naming and linker script issues
  CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F072xB/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103xB/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32G0/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI2/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L1/TARGET_XDOT_L151CC/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_NUCLEO_L496ZG/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4R9xI/CMakeLists.txt
  tools/cmake/toolchain.cmake
Labels: ready for merge, release-type: patch

#14030 STM32H7: Compute I2C timing according current I2C clock source
  targets/TARGET_STM/TARGET_STM32H7/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32H7/STM32Cube_FW/STM32H7xx_HAL_Driver/stm32h7xx_hal_rcc_ex.h
  targets/TARGET_STM/TARGET_STM32H7/i2c_device.c
  targets/TARGET_STM/TARGET_STM32H7/i2c_device.h
  targets/TARGET_STM/i2c_api.c
Labels: ready for merge, release-type: patch

#14284 CMake Arm SSG: refactor CMake targets
  targets/TARGET_ARM_SSG/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MPS2/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0P/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M3/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M4/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M7/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14289 CMake: Refactor Cypress targets
  CMakeLists.txt
  connectivity/drivers/emac/TARGET_Cypress/COMPONENT_SCL/CMakeLists.txt
  targets/TARGET_Cypress/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_SCL/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/COMPONENT_WHD/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT064B0S2_4343W/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062S2_43012/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_BLE/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CKIT_062_WIFI_BT/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062S3_4343W/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CY8CPROTO_062_4343W/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYSBSYSKIT_01/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYTFM_064B0S2_4343W/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43012EVB_01/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/TARGET_CYW9P62S1_43438EVB_01/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/common/COMPONENT_WHD/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/psoc6csp/abstraction/rtos/CMakeLists.txt
  targets/TARGET_Cypress/scripts/mbed_set_post_build_cypress.cmake
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/TARGET_LPC11XX/CMakeLists.txt
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_ARCH_PRO/CMakeLists.txt
  targets/TARGET_NXP/TARGET_LPC176X/TARGET_MBED_LPC1768/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/CMakeLists.txt
  targets/TARGET_NXP/scripts/mbed_set_post_build_nxp.cmake
  tools/cmake/mbed_set_post_build.cmake
Labels: component: connectivity, component: tools, devices: cypress, devices: nxp, ready for merge, release-type: patch

#14286 CMake: remove workaround for targets prior refactor
  CMakeLists.txt
Labels: ready for merge, release-type: patch

#14287 Musca B1/S1: remove _NS aliases
  targets/targets.json
  tools/cmake/README.md
Labels: needs: CI, release-version: feature branch, stale

#14278 Add mbedtls_ecp_write_key() to Cypress Mbed TLS driver
  connectivity/drivers/mbedtls/TARGET_Cypress/TARGET_MXCRYPTO/ecp_alt.c
Labels: needs: CI, release-version: feature branch

#14307 CMake: Fix some NUVOTON build
  targets/TARGET_NUVOTON/TARGET_M251/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M261/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M480/TARGET_NUMAKER_IOT_M487/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M480/TARGET_NUMAKER_PFM_M487/CMakeLists.txt
Labels: devices: nuvoton, ready for merge, release-type: patch, stale

#14308 Create FLASH CMSIS ALGO target to remove dependency on MBED_TARGET_LABELS
  hal/CMakeLists.txt
  hal/TARGET_FLASH_CMSIS_ALGO/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/qspi/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/TARGET_EV_COG_AD3029LZ/CMakeLists.txt
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/TARGET_EV_COG_AD4050LZ/CMakeLists.txt
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL46Z/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M251/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M261/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M451/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M480/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_NUC472/CMakeLists.txt
Labels: component: hal, devices: analog devices, devices: nuvoton, devices: nxp, ready for merge, release-type: patch

#14309 CMake: Fix STM32F091XC Mbed targets GCC_ARM build
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/CMakeLists.txt
Labels: devices: st, ready for merge, release-type: patch

#14316 MAX32625: Fix CMake build
  targets/TARGET_Maxim/TARGET_MAX32625/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32625/TARGET_SDT32625B/CMakeLists.txt
  targets/TARGET_Maxim/TARGET_MAX32625/device/CMakeLists.txt
Labels: devices: maxim, ready for merge, release-type: patch

#14311 CMake: Fix Cortex-A9 builds with GCC_ARM
  tools/cmake/cores/Cortex-A9.cmake
Labels: component: tools, ready for merge, release-type: patch

#14315 NUVOTON: Remove CMake listing of M261 include directory that do not exist
  targets/TARGET_NUVOTON/TARGET_M261/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14300 Add bare metal support to ARM_MPS2_Target family of targets
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0P/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M3/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M4/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M7/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M7/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/targets.json
Labels: devices: arm, ready for merge, release-type: patch, stale

#14295 CMake remove IAR references in the tree
  cmsis/CMSIS_5/CMSIS/RTOS2/RTX/CMakeLists.txt
  cmsis/device/rtos/CMakeLists.txt
  connectivity/drivers/emac/TARGET_RDA_EMAC/lwip-wifi/arch/TARGET_RDA/TARGET_UNO_91H/lib/CMakeLists.txt
  connectivity/drivers/mbedtls/FEATURE_CRYPTOCELL310/TARGET_MCU_NRF52840/CMakeLists.txt
  connectivity/drivers/mbedtls/FEATURE_CRYPTOCELL310/binaries/CMakeLists.txt
  platform/source/CMakeLists.txt
  platform/source/TARGET_CORTEX_A/CMakeLists.txt
  platform/source/TARGET_CORTEX_M/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L475xG/CMakeLists.txt
Labels: component: connectivity, component: core, component: security, devices: st, ready for merge, release-type: patch, stale

#14298 CMake: remove debug print
  CMakeLists.txt
Labels: ready for merge, release-type: patch

#14306 CMake: Create CMSIS library targets to remove dependency on MBED_TARGET_LABELS
  cmsis/CMSIS_5/CMSIS/CMakeLists.txt
  cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_A/CMakeLists.txt
  cmsis/CMSIS_5/CMSIS/TARGET_CORTEX_M/CMakeLists.txt
  targets/TARGET_ARM_FM/CMakeLists.txt
  targets/TARGET_ARM_SSG/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/CMakeLists.txt
  targets/TARGET_Analog_Devices/CMakeLists.txt
  targets/TARGET_Cypress/TARGET_PSOC6/CMakeLists.txt
  targets/TARGET_Freescale/CMakeLists.txt
  targets/TARGET_GigaDevice/CMakeLists.txt
  targets/TARGET_Maxim/CMakeLists.txt
  targets/TARGET_NORDIC/CMakeLists.txt
  targets/TARGET_NXP/CMakeLists.txt
  targets/TARGET_RENESAS/CMakeLists.txt
  targets/TARGET_STM/CMakeLists.txt
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/CMakeLists.txt
  targets/TARGET_Samsung/TARGET_SIDK_S5JS100/CMakeLists.txt
  targets/TARGET_Silicon_Labs/CMakeLists.txt
  targets/TARGET_TOSHIBA/CMakeLists.txt
Labels: component: core, component: test, devices: analog devices, devices: arm, devices: cypress, devices: gigadevice, devices: maxim, devices: nordic, devices: nxp, devices: renesas, devices: samsung, devices: silicon labs, devices: sparkfun, devices: st, devices: toshiba, ready for merge, release-type: patch

#14314 CMake: Fix ARM MUSCA NS targets build
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/CMakeLists.txt
Labels: devices: arm, ready for merge, release-type: patch

#14313 CMake: Fix Cortex-M33 GCC build
  tools/cmake/cores/Cortex-M33-NS.cmake
  tools/cmake/cores/Cortex-M33.cmake
Labels: component: tools, ready for merge, release-type: patch

#14305 BLE: fix indexing of array in Cordio host stack
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/att/atts_csf.c
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/att/atts_eatt.c
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/att/atts_main.c
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/att/atts_main.h
Labels: component: connectivity, ready for merge, release-type: patch

#14328 CMake: Fix Greentea tests
  tools/cmake/README.md
  tools/cmake/mbed_greentea.cmake
Labels: ready for merge, release-type: patch

#14304 CMake: Refactor post-build hook to remove APP_TARGET references
  CMakeLists.txt
  tools/cmake/mbed_set_post_build.cmake
Labels: component: tools, ready for merge, release-type: patch

#14350 ARM_MPS2_Target: Fix conflicts in IAR configuration
  targets/targets.json
Labels: ready for merge, release-type: patch

#14332 CMake: Tdbstore unittest refactor cmake
  CMakeLists.txt
  storage/kvstore/tdbstore/tests/UNITTESTS/CMakeLists.txt
  storage/kvstore/tdbstore/tests/UNITTESTS/TDBStore/CMakeLists.txt
Labels: needs: CI, release-version: feature branch

#14343 Add lw ip opttion for rdnss
  connectivity/lwipstack/include/lwipstack/lwipopts.h
  connectivity/lwipstack/mbed_lib.json
Labels: component: connectivity, ready for merge, release-type: feature

#14344 CMake: Fix PSOC6 post build script
  targets/TARGET_Cypress/scripts/PSOC6.py
Labels: devices: cypress, ready for merge, release-type: patch

#14299 CMake: Refactor mapfile generation
  CMakeLists.txt
  tools/cmake/toolchains/ARM.cmake
  tools/cmake/toolchains/GCC_ARM.cmake
Labels: component: tools, ready for merge, release-type: patch

#14341 Update stm32xx_emac driver traces
  connectivity/drivers/emac/TARGET_STM/stm32xx_emac.cpp
Labels: component: connectivity, devices: st, ready for merge

#14333 TARGET_TFM_V1_0: compatibility with Mbed TLS 2.24.0
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_0/include/psa/crypto_extra.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_0/include/psa/crypto_types.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_0/include/psa/crypto_values.h
Labels: needs: CI, release-version: feature branch
