Repository ARMmbed/mbed-os, pull requests merged in 2021-05, with the labels that each got.

#14603 Avoid init class definition for compatibility
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
Labels: component: connectivity, ready for merge, release-type: patch

#14602 Deprecate indications event onConfirmationReceived
  connectivity/FEATURE_BLE/include/ble/GattServer.h
  connectivity/FEATURE_BLE/source/cordio/source/GattServerImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GattServerEvents.h
Labels: component: connectivity, ready for merge, release-type: patch

#14594 STM32_gen_PeripheralPins.py : TargetName correction
  targets/TARGET_STM/tools/STM32_gen_PeripheralPins.py
Labels: devices: st, ready for merge, release-type: patch

#14567 M487: Resolve WDT reset H/W limit
  targets/TARGET_NUVOTON/TARGET_M480/device/startup_M480.c
  targets/TARGET_NUVOTON/TARGET_M480/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_M480/reset_reason.c
Labels: devices: nuvoton, needs: CI, release-type: patch

#14586 [feature-wisun]: Added API to get Wi-SUN Neighbor Table
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: feature branch

#14569 remove cmake specific example list
  tools/test/examples/cloud_examples_cmake.json
  tools/test/examples/examples_cmake.json
Labels: ready for merge, release-type: patch

#14578 STM32 : new DISCO_WB5MMG target
  connectivity/drivers/mbedtls/TARGET_STM/CMakeLists.txt
  connectivity/drivers/mbedtls/TARGET_STM/TARGET_STM32WB/CMakeLists.txt
  connectivity/drivers/mbedtls/TARGET_STM/TARGET_STM32WB/mbedtls_device.h
  targets/TARGET_STM/TARGET_STM32WB/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32WB/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32WB/STM32Cube_FW/CMSIS/stm32wb5mxx.h
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5Mxx/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5Mxx/TARGET_DISCO_WB5MMG/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5Mxx/TARGET_DISCO_WB5MMG/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5Mxx/TARGET_DISCO_WB5MMG/PinNames.h
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5Mxx/TOOLCHAIN_ARM/startup_stm32wb5mxx.S
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5Mxx/TOOLCHAIN_ARM/stm32wb5mxx.sct
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5Mxx/TOOLCHAIN_GCC_ARM/startup_stm32wb5mxx.S
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5Mxx/TOOLCHAIN_GCC_ARM/stm32wb5mxx.ld
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5Mxx/TOOLCHAIN_IAR/startup_stm32wb5mxx.S
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5Mxx/TOOLCHAIN_IAR/stm32wb5mxx.icf
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5Mxx/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5Mxx/system_clock.c
  targets/targets.json
Labels: component: connectivity, component: security, devices: st, ready for merge, release-type: patch, scope: new-target

#14627 Dispatch Gap::stopPeriodicAdvertising to the right function.
  connectivity/FEATURE_BLE/source/Gap.cpp
Labels: component: connectivity, ready for merge, release-type: patch

#14628 ARDUINO_UNO form factor and new PinNames for MIMXRT1050 target
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/TARGET_EVK/PinNames.h
  targets/targets.json
Labels: devices: nxp, ready for merge, release-type: patch

#14625 BLE: Fix overwriting attribute data from read auth callback
  connectivity/FEATURE_BLE/include/ble/gatt/GattCharacteristic.h
  connectivity/FEATURE_BLE/source/cordio/source/GattServerImpl.cpp
Labels: component: connectivity, ready for merge, release-type: patch

#14631 driver/I2C: STm32: Updated HAL_I2C_ErrorCallback function to store information about error reason in obj_s->event
  targets/TARGET_STM/i2c_api.c
Labels: devices: st, ready for merge

#14588 Add v8.1-M architecture awareness
  drivers/include/drivers/MbedCRC.h
  hal/source/mpu/mbed_mpu_v8m.c
  hal/tests/TESTS/mbed_hal/mpu/main.cpp
  platform/include/platform/mbed_atomic.h
  tools/cmake/cores/Cortex-M55.cmake
Labels: component: core, component: hal, ready for merge, release-type: patch

#14653 requirements: Relax Click version requirement
  requirements.txt
Labels: ready for merge, release-type: patch

#14548 STM32F4 update drivers version to CUBE V1.26.1
  targets/TARGET_STM/README.md
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal.c
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/STM32F4xx_HAL_Driver/stm32f4xx_hal_usart.c
  targets/TARGET_STM/TARGET_STM32F4/STM32Cube_FW/system_stm32f4xx.c
Labels: devices: st, needs: CI, release-type: patch

#14624 error: use __INITIAL_SP from cmsis instead of RTX one
  platform/source/mbed_error.c
Labels: component: core, ready for merge, release-type: patch

#14538 Cmake: Add MBED_TEST_MODE macro
  .travis.yml
  CMakeLists.txt
  tools/cmake/mbed_greentea.cmake
  tools/cmake/tests/mbed_test_mode/CMakeLists.txt
  tools/cmake/tests/mbed_test_mode/main.cpp
Labels: ready for merge, release-type: patch

#14497 Check for duplicate status callbacks before adding to the list
  connectivity/netsocket/source/NetworkInterface.cpp
Labels: component: connectivity, ready for merge, release-type: patch

#14655 mbedtls_stub: Add missing include
  connectivity/nanostack/coap-service/test/coap-service/unittest/stub/mbedtls_stub.c
Labels: component: mesh, ready for merge, release-type: patch

#14336 Implement polymorphism for CAN driver
  drivers/include/drivers/CAN.h
  drivers/include/drivers/interfaces/InterfaceCAN.h
  drivers/source/CAN.cpp
  hal/include/hal/can_helper.h
Labels: component: core, component: hal, ready for merge, release-type: feature

#14576 Trace: Change tr_debug color from gray to bright blue
  platform/mbed-trace/mbed_lib.json
  platform/mbed-trace/source/mbed_trace.c
Labels: component: core, ready for merge, release-type: patch

#13791 mbedtls: Don't attempt to use default_random_seed
  connectivity/mbedtls/platform/inc/platform_mbed.h
Labels: ready for merge, release-type: patch

#14619 Add API to get Wi-SUN Neighbor Table
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h
  connectivity/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  connectivity/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: component: mesh, ready for merge, release-type: feature

#14656 CMake: Only force Ninja response files on Windows
  CMakeLists.txt
Labels: ready for merge, release-type: patch

#14657 Deprecate broken TDB_EXTERNAL_NO_RBP and FILESYSTEM_NO_RBP in kv_config
  storage/docs/Configuration/CONFIGURATION.md
  storage/kvstore/kv_config/filesystem_no_rbp/mbed_lib.json
  storage/kvstore/kv_config/global/mbed_lib.json
  storage/kvstore/kv_config/source/kv_config.cpp
  storage/kvstore/kv_config/tdb_external_no_rbp/mbed_lib.json
Labels: component: core, component: docs, ready for merge, release-type: patch, stale

#14661 Delete STM32F401XE.ld
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F401xE/TOOLCHAIN_GCC_ARM/STM32F401XE.ld
Labels: devices: st, ready for merge, release-type: patch

#14556 Nuvoton: Fix hal_watchdog_kick() with WDT stopped (5.15)
  targets/TARGET_NUVOTON/TARGET_M451/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_M480/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/watchdog_api.c
Labels: Release review required, ready for merge, release-version: 5.15.8

#14502 M487: Fix crash on WDT reset from power-down (5.15)
  targets/TARGET_NUVOTON/TARGET_M480/device/startup_M480.c
  targets/TARGET_NUVOTON/TARGET_M480/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_M480/reset_reason.c
Labels: ready for merge, release-version: 5.15.8

#14536 STM32: Add LP_TICKER and US_TICKER optimisation macro
  targets/TARGET_STM/device.h
  targets/TARGET_STM/lp_ticker_defines.h
Labels: component: hal, devices: st, ready for merge, release-type: patch

#14664 Enable FlashIAP for MCU_NRF52832
  targets/targets.json
Labels: ready for merge, release-type: patch

#14668 Driver: I2C: STM32F2/STM32F4/STM32L1: Fix alternate i2c read.
  targets/TARGET_STM/TARGET_STM32F2/objects.h
  targets/TARGET_STM/TARGET_STM32F4/objects.h
  targets/TARGET_STM/i2c_api.c
Labels: ready for merge, release-type: patch

#14671 enable aws example test in CI
  tools/test/examples/cloud_examples.json
Labels: component: tools, ready for merge, release-type: patch

#14674 Update mbed-coap to version v5.1.10
  connectivity/libraries/mbed-coap/CHANGELOG.md
  connectivity/libraries/mbed-coap/Makefile.test
  connectivity/libraries/mbed-coap/mbed-coap/sn_coap_header.h
  connectivity/libraries/mbed-coap/mbed-coap/sn_config.h
  connectivity/libraries/mbed-coap/run_unit_tests.sh
  connectivity/libraries/mbed-coap/run_unit_tests_with_valgrind.sh
  connectivity/libraries/mbed-coap/source/include/sn_coap_header_internal.h
  connectivity/libraries/mbed-coap/source/include/sn_coap_protocol_internal.h
  connectivity/libraries/mbed-coap/source/sn_coap_builder.c
  connectivity/libraries/mbed-coap/source/sn_coap_parser.c
  connectivity/libraries/mbed-coap/source/sn_coap_protocol.c
Labels: component: mesh, ready for merge, release-type: patch

#14678 Serial: remove shadowing member variables
  drivers/include/drivers/BufferedSerial.h
  drivers/source/BufferedSerial.cpp
Labels: component: core, component: hal, ready for merge, release-type: patch

#14683 Baremetal tests: enable BLE tests with NUCLEO_WB55RG
  TESTS/configs/baremetal.json
  connectivity/drivers/ble/FEATURE_BLE/TARGET_STM32WB/mbed_lib.json
Labels: component: connectivity, component: test, ready for merge, release-type: patch

#14684 Fix missing `as_entry` method in KVStoreSecurityDb
  connectivity/FEATURE_BLE/source/generic/KVStoreSecurityDb.cpp
  connectivity/FEATURE_BLE/source/generic/KVStoreSecurityDb.h
Labels: component: connectivity, ready for merge, release-type: patch

#14665 Travis: Move frozen tools check to the end
  .travis.yml
Labels: ready for merge, release-type: patch

#14574 Fix string buffer length in UUID trace helper
  connectivity/FEATURE_BLE/source/common/ble_trace_helpers.cpp
Labels: component: connectivity, needs: preceding PR, needs: review, release-type: patch

#14629 Mesh api: Added PHY mode, channel plan IDs and configuration functions
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  connectivity/nanostack/mbed-mesh-api/mbed_lib.json
  connectivity/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: component: mesh, ready for merge, release-type: feature

#14662 Add CANMessage deep comparison operators
  drivers/include/drivers/interfaces/InterfaceCAN.h
Labels: component: core, component: hal, ready for merge, release-type: patch, stale

#14689 Information on Asynchronous SPI limitation on High Speeds
  targets/TARGET_STM/README.md
  targets/TARGET_STM/stm_spi_api.c
Labels: devices: st, ready for merge, release-type: patch

#14691 Add GitHub action for issue triaging script
  .github/workflows/main.yml
Labels: needs: review, release-type: patch

#14667 Update GCC except.S to support ARMC6 and use GCC assembly with ARM toolchain in CMake
  cmsis/CMSIS_5/CMSIS/RTOS2/RTX/CMakeLists.txt
  cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/TOOLCHAIN_GCC/TARGET_M0/irq_cm0.S
  cmsis/CMSIS_5/CMSIS/RTOS2/RTX/Source/TOOLCHAIN_GCC/TARGET_M0P/irq_cm0.S
  platform/source/TARGET_CORTEX_M/CMakeLists.txt
  platform/source/TARGET_CORTEX_M/TOOLCHAIN_GCC/except.S
  tools/cmake/cores/Cortex-M55.cmake
Labels: component: core, component: tools, ready for merge, release-type: patch

#14709 CMake: Remove forgotten debug message
  CMakeLists.txt
Labels: ready for merge, release-type: patch

#14705 Fix frozen tools check never failing
  .travis.yml
Labels: component: tools, ready for merge, release-type: patch

#14697 TESTS: rename variable interface to fix broken tests
  TESTS/integration/net-single/main.cpp
  TESTS/integration/stress-net-fs/main.cpp
Labels: component: test, ready for merge, release-type: patch

#14708 test: Fix function does not return a value warnings
  UNITTESTS/stubs/FileHandle_stub.h
  UNITTESTS/stubs/connectivity/AT_CellularDevice_stub.cpp
  UNITTESTS/stubs/connectivity/LoRaMac_stub.cpp
  UNITTESTS/stubs/drivers/BufferedSerial_stub.cpp
  UNITTESTS/stubs/events/equeue_stub.c
  UNITTESTS/stubs/storage/EmulatedSD.cpp
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularcontext/at_cellularcontexttest.cpp
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/loramac/Test_LoRaMac.cpp
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/loraphy/Test_LoRaPHY.cpp
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/loraphyas923/Test_LoRaPHYAS923.cpp
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/loraphyau915/Test_LoRaPHYAU915.cpp
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/loraphycn470/Test_LoRaPHYCN470.cpp
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/loraphykr920/Test_LoRaPHYKR920.cpp
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/loraphyus915/Test_LoRaPHYUS915.cpp
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/lorawaninterface/Test_LoRaWANInterface.cpp
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/lorawanstack/Test_LoRaWANStack.cpp
Labels: component: connectivity, component: test, ready for merge, release-type: patch

#14702 Silence expansion-to-defined for nrfx
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/CMakeLists.txt
Labels: devices: nordic, ready for merge, release-type: patch

#14698 STM32: Fixed I2C Bug
  targets/TARGET_STM/i2c_api.c
Labels: devices: st, ready for merge, release-type: patch
