Repository ARMmbed/mbed-os, pull requests merged in 2021-09, with the labels that each got.

#15043 FIX: update click version to fix scancode
  .github/workflows/basic_checks.yml
Labels: ready for merge, release-type: patch

#15032 CMake: Fix escaping of quotes in response file
  tools/cmake/mbed_toolchain.cmake
Labels: ready for merge, component: tools, release-type: patch

#15041 CMake: Set TARGET_NAME macro
  CMakeLists.txt
Labels: ready for merge, release-type: patch

#15034 add RTC using HSE to target STM32F1
  targets/TARGET_STM/mbed_overrides.c
  targets/TARGET_STM/rtc_api.c
  targets/TARGET_STM/rtc_api_hal.h
Labels: devices: st, ready for merge, release-type: patch

#15019 Refactor platform greentea cmake
  platform/CMakeLists.txt
  platform/tests/TESTS/CMakeLists.txt
  platform/tests/TESTS/mbed_functional/callback/CMakeLists.txt
  platform/tests/TESTS/mbed_functional/callback_big/CMakeLists.txt
  platform/tests/TESTS/mbed_functional/callback_small/CMakeLists.txt
  platform/tests/TESTS/mbed_micro/attributes/CMakeLists.txt
  platform/tests/TESTS/mbed_micro/call_before_main/CMakeLists.txt
  platform/tests/TESTS/mbed_micro/cpp/CMakeLists.txt
  platform/tests/TESTS/mbed_micro/div/CMakeLists.txt
  platform/tests/TESTS/mbed_micro/static_assert/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/CircularBuffer/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/FileHandle/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/SharedPtr/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/SingletonPtr/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/Stream/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/Transaction/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/atomic/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/crash_reporting/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/critical_section/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/error_handling/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/minimal-printf/compliance/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/stats_cpu/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/stats_heap/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/stats_sys/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/stats_thread/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/system_reset/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/wait_ns/CMakeLists.txt
Labels: ready for merge, component: core, release-type: patch

#14981 Fix STM32 SPI 3-wire (synchronous API)
  targets/TARGET_STM/stm_spi_api.c
Labels: devices: st, ready for merge, release-type: patch

#15030 M2354: Fix LCDCP missing in TF-M CLK pass list
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/tfm_s.bin
Labels: ready for merge, devices: nuvoton, release-type: patch

#14951 CMake: Refactor rtos greentea cmake
  rtos/CMakeLists.txt
  rtos/tests/TESTS/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/MemoryPool/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/basic/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/condition_variable/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/event_flags/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/heap_and_stack/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/kernel_tick_count/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/mail/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/malloc/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/mutex/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/queue/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/semaphore/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/signals/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/systimer/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/threads/CMakeLists.txt
Labels: ready for merge, component: connectivity, component: hal, component: tools, component: core, release-type: patch

#15045 Workaround for a bug in malloc() from newlib-nano 4.1.0 (in GCC 10.3)
  .codecheckignore
  platform/source/CMakeLists.txt
  platform/source/newlib_nano_malloc_workaround.c
  rtos/tests/TESTS/mbed_rtos/malloc/main.cpp
Labels: ready for merge, component: core

#15052 Fix mbed-os-env docker digest retrieval
  .github/workflows/ci_scripts/ghcr_utils.py
  .github/workflows/docker_management.branch.yml
  .github/workflows/docker_management.release.yml
Labels: ready for merge, release-type: patch

#15007 docker: Upgrade GCC to 10.3-2021.07
  docker_images/mbed-os-env/Dockerfile
Labels: ready for merge, release-type: patch, story: september release

#15028 STM32 SPI: Update and improvement
  targets/TARGET_STM/TARGET_STM32H7/spi_device.h
  targets/TARGET_STM/stm_spi_api.c
Labels: devices: st, ready for merge, release-type: patch

#15027 M2354: Generate unique MCUboot image version
  targets/TARGET_NUVOTON/scripts/NUVOTON.py
  tools/targets/NU_M2354.py
Labels: ready for merge, devices: nuvoton, component: tools, release-type: patch

#15059 Fix Thread::start() and general_block_device test's thread allocation/deallocation
  rtos/include/rtos/Thread.h
  rtos/source/Thread.cpp
  storage/blockdevice/tests/TESTS/blockdevice/general_block_device/main.cpp
Labels: ready for merge, component: core, release-type: patch

#15060 set locale in mbed-os-env Docker image
  docker_images/mbed-os-env/Dockerfile
Labels: ready for merge, release-type: patch

#15026 [mbed-os-5.15] Nuvoton M480/M451 CAN API support mask feature
  targets/TARGET_NUVOTON/TARGET_M451/can_api.c
  targets/TARGET_NUVOTON/TARGET_M480/can_api.c
Labels: ready for merge, release-version: 5.15.8

#15029 M2354: Fix incorrectly resolved peripheral base with security
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/partition/partition_M2354_im.h
  targets/TARGET_NUVOTON/TARGET_M2354/device/nu_tfm_import_define.h
  targets/TARGET_NUVOTON/TARGET_M2354/device/nu_tfm_import_undefine.h
  targets/TARGET_NUVOTON/TARGET_M2354/device/partition_M2354.h
  targets/TARGET_NUVOTON/TARGET_M2354/device/partition_M2354_mem.h
Labels: ready for merge, devices: nuvoton, release-type: patch

#15010 Reduce spam on trace because of calling read/write while handshaking
  connectivity/netsocket/source/TLSSocketWrapper.cpp
Labels: ready for merge, component: connectivity, release-type: patch

#15040 New feature: send/recv message implementation added to network stack
  connectivity/cellular/include/cellular/framework/AT/AT_CellularStack.h
  connectivity/lwipstack/include/lwipstack/LWIPStack.h
  connectivity/lwipstack/include/lwipstack/lwipopts.h
  connectivity/lwipstack/lwip/test/unit/lwipopts.h
  connectivity/lwipstack/source/LWIPInterface.cpp
  connectivity/lwipstack/source/LWIPStack.cpp
  connectivity/nanostack/include/nanostack-interface/Nanostack.h
  connectivity/nanostack/mbed-mesh-api/source/NanostackEMACInterface.cpp
  connectivity/netsocket/include/netsocket/CellularNonIPSocket.h
  connectivity/netsocket/include/netsocket/InternetDatagramSocket.h
  connectivity/netsocket/include/netsocket/MsgHeader.h
  connectivity/netsocket/include/netsocket/NetworkStack.h
  connectivity/netsocket/include/netsocket/OnboardNetworkStack.h
  connectivity/netsocket/include/netsocket/Socket.h
  connectivity/netsocket/include/netsocket/TCPSocket.h
  connectivity/netsocket/include/netsocket/TLSSocketWrapper.h
  connectivity/netsocket/include/netsocket/nsapi_types.h
  connectivity/netsocket/source/CellularNonIPSocket.cpp
  connectivity/netsocket/source/EMACInterface.cpp
  connectivity/netsocket/source/InternetDatagramSocket.cpp
  connectivity/netsocket/source/NetworkStack.cpp
  connectivity/netsocket/source/TCPSocket.cpp
  connectivity/netsocket/source/TLSSocketWrapper.cpp
  connectivity/netsocket/tests/TESTS/network/emac/emac_TestNetworkStack.cpp
  connectivity/netsocket/tests/TESTS/network/emac/emac_TestNetworkStack.h
  connectivity/netsocket/tests/UNITTESTS/doubles/NetworkStack_stub.h
  connectivity/netsocket/tests/UNITTESTS/doubles/OnboardNetworkStack_mock.h
  connectivity/netsocket/tests/UNITTESTS/netsocket/EthernetInterface/test_EthernetInterface.cpp
  connectivity/netsocket/tests/UNITTESTS/netsocket/InternetSocket/test_InternetSocket.cpp
  connectivity/netsocket/tests/UNITTESTS/netsocket/NetworkStack/CMakeLists.txt
  connectivity/netsocket/tests/UNITTESTS/netsocket/NetworkStack/test_MsgHeaderIterator.cpp
Labels: ready for merge, component: connectivity, release-type: feature, component: mesh

#15031 connectivity-netsocket-tests-tests-network-wifi test suite configuration simplification
  connectivity/netsocket/tests/TESTS/network/wifi/get_interface.cpp
  connectivity/netsocket/tests/TESTS/network/wifi/get_security.cpp
  connectivity/netsocket/tests/TESTS/network/wifi/main.cpp
  connectivity/netsocket/tests/TESTS/network/wifi/template_mbed_app.txt
  connectivity/netsocket/tests/TESTS/network/wifi/wifi_connect_disconnect_repeat.cpp
  connectivity/netsocket/tests/TESTS/network/wifi/wifi_connect_secure_fail.cpp
  connectivity/netsocket/tests/TESTS/network/wifi/wifi_scan.cpp
  connectivity/netsocket/tests/TESTS/network/wifi/wifi_tests.h
Labels: ready for merge, component: connectivity, release-type: patch

#15051 Allow to use all STM32 targets prescaler for LPTIM
  targets/TARGET_STM/lp_ticker.c
  targets/targets.json
Labels: devices: st, ready for merge, release-type: patch

#14989 SFDP: Add support for multiple configurations and sector maps
  drivers/CMakeLists.txt
  drivers/include/drivers/QSPI.h
  drivers/source/QSPI.cpp
  storage/blockdevice/CMakeLists.txt
  storage/blockdevice/COMPONENT_OSPIF/include/OSPIF/OSPIFBlockDevice.h
  storage/blockdevice/COMPONENT_OSPIF/source/OSPIFBlockDevice.cpp
  storage/blockdevice/COMPONENT_QSPIF/CMakeLists.txt
  storage/blockdevice/COMPONENT_QSPIF/UNITTESTS/.mbedignore
  storage/blockdevice/COMPONENT_QSPIF/UNITTESTS/CMakeLists.txt
  storage/blockdevice/COMPONENT_QSPIF/UNITTESTS/test_QSPIFBlockDevice.cpp
  storage/blockdevice/COMPONENT_QSPIF/include/QSPIF/QSPIFBlockDevice.h
  storage/blockdevice/COMPONENT_QSPIF/source/QSPIFBlockDevice.cpp
  storage/blockdevice/COMPONENT_SPIF/include/SPIF/SPIFBlockDevice.h
  storage/blockdevice/COMPONENT_SPIF/source/SPIFBlockDevice.cpp
  storage/blockdevice/include/blockdevice/internal/SFDP.h
  storage/blockdevice/source/SFDP.cpp
  storage/blockdevice/tests/UNITTESTS/SFDP/test_sfdp.cpp
  targets/targets.json
Labels: ready for merge, component: core, release-type: feature

#15067 Greentea: Fix flash overflown issue in callback_big test
  platform/tests/TESTS/mbed_functional/callback/main.cpp
Labels: ready for merge, component: core, release-type: patch

#15050 Update to TF-M v1.4.0
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/TARGET_TFM_V8M/src/tfm_psa_ns_api.c
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/VERSION.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/psa/client.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/psa/crypto.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/psa/crypto_client_struct.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/psa/crypto_compat.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/psa/crypto_sizes.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/psa/crypto_types.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/psa/crypto_values.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/psa/initial_attestation.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/psa/update.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/psa_manifest/sid.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/tfm_api.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/tfm_crypto_defs.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/tfm_ns_interface.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/include/tfm_psa_call_param.h
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/src/tfm_crypto_ipc_api.c
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/src/tfm_firmware_update_ipc_api.c
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/src/tfm_initial_attestation_ipc_api.c
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/src/tfm_its_ipc_api.c
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_LATEST/src/tfm_ps_ipc_api.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/bl2.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/device/TOOLCHAIN_ARMC6/musca_ns.sct
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/partition/flash_layout.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/partition/region_defs.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/s_veneers.o
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/tfm_ns_interface.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/tfm_s.axf
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/tfm_s.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/bl2.bin
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/device/TOOLCHAIN_ARMC6/musca_ns.sct
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/partition/flash_layout.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/partition/region_defs.h
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/tfm_ns_interface.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/tfm_s.axf
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/tfm_s.bin
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/bl2.bin
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/tfm_s.axf
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/tfm_s.bin
  targets/targets.json
  tools/psa/tfm/bin_utils/imgtool/__init__.py
  tools/psa/tfm/bin_utils/imgtool/image.py
  tools/psa/tfm/bin_utils/imgtool/keys/general.py
  tools/psa/tfm/bin_utils/imgtool/main.py
  tools/psa/tfm/bin_utils/macro_parser.py
  tools/psa/tfm/bin_utils/wrapper.py
Labels: ready for merge, devices: arm, devices: nuvoton, component: tools, component: security, component: core, release-type: patch

#15073 CMake: QSPIFBlockDevice: Guard unit test directory
  storage/blockdevice/COMPONENT_QSPIF/CMakeLists.txt
Labels: ready for merge, component: core, release-type: patch

#15061 Fix replacement of event queue background.
  events/source/EventQueue.cpp
Labels: ready for merge, component: core, release-type: patch

#15078 M2354: Fix TF-M 1.4
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/README.md
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/bl2.bin
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/tfm_s.axf
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/tfm_s.bin
  targets/TARGET_NUVOTON/scripts/NUVOTON.py
  tools/targets/NU_M2354.py
Labels: needs: review, devices: nuvoton, component: tools, release-type: patch

#15098 STM32F303xC: cmakelist issue
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xC/CMakeLists.txt
Labels: devices: st, ready for merge, release-type: patch, stale

#15062 Lora drivers: explicit lib requirement
  connectivity/drivers/lora/COMPONENT_SX126X/mbed_lib.json
  connectivity/drivers/lora/COMPONENT_SX1272/mbed_lib.json
  connectivity/drivers/lora/COMPONENT_SX1276/mbed_lib.json
  connectivity/drivers/lora/TARGET_STM32WL/mbed_lib.json
  connectivity/lorawan/mbed_lib.json
  targets/TARGET_STM/TARGET_STM32WL/README.md
Labels: devices: st, ready for merge, component: connectivity, release-type: patch

#15095 CMake: greentea: Migrate the NFC EEPROM test to CTest
  connectivity/CMakeLists.txt
  connectivity/FEATURE_BLE/CMakeLists.txt
  connectivity/libraries/CMakeLists.txt
  connectivity/mbedtls/CMakeLists.txt
  connectivity/nfc/CMakeLists.txt
  connectivity/nfc/tests/TESTS/CMakeLists.txt
  connectivity/nfc/tests/TESTS/nfc/eeprom/CMakeLists.txt
  targets/targets.json
  tools/memap.py
Labels: ready for merge, component: connectivity, component: tools, component: security, release-type: patch

#15080 STM32F4: CAN issue with F407 target
  targets/TARGET_STM/TARGET_STM32F4/PeripheralNames.h
  targets/targets.json
Labels: devices: st, ready for merge, release-type: patch

#15114 Fix ARM toolchain #L6803W Relocation warnings
  targets/TARGET_Maxim/TARGET_MAX32625/device/TOOLCHAIN_ARM_STD/startup_MAX32625.S
  targets/TARGET_Maxim/TARGET_MAX32630/device/TOOLCHAIN_ARM_STD/startup_MAX3263x.S
Labels: ready for merge, devices: maxim

#15065 STM32L5/STM32U5 : CAN support
  targets/TARGET_STM/TARGET_STM32L5/objects.h
  targets/TARGET_STM/TARGET_STM32U5/objects.h
  targets/TARGET_STM/can_api.c
  targets/targets.json
Labels: devices: st, ready for merge, release-type: patch

#15077 CAN: Use uintptr_t for can_irq_ids
  drivers/include/drivers/CAN.h
  drivers/source/CAN.cpp
  hal/include/hal/can_api.h
  targets/TARGET_GigaDevice/TARGET_GD32F30X/can_api.c
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/can_api.c
  targets/TARGET_NUVOTON/TARGET_M451/can_api.c
  targets/TARGET_NUVOTON/TARGET_M480/can_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/can_api.c
  targets/TARGET_NXP/TARGET_LPC176X/can_api.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/can_api.c
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/can_api.c
  targets/TARGET_STM/can_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/can_api.c
Labels: devices: st, devices: nxp, ready for merge, devices: nuvoton, devices: silicon labs, component: hal, devices: renesas, component: core, release-type: patch, devices: gigadevice

#15081 STM32: STM32_gen_PeripheralPins.py v1.20.4
  targets/TARGET_STM/tools/STM32_gen_PeripheralPins.py
Labels: devices: st, ready for merge, release-type: patch

#15107 LWIP: Provide inline replacements for htons() and htonl()
  connectivity/lwipstack/lwip-sys/arch/cc.h
Labels: ready for merge, component: connectivity, release-type: patch

#15074 STM32 : default SPI and I2C for targets with ARDUINO-NANO
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303x8/TARGET_NUCLEO_F303K8/PinNames.h
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G031x8/TARGET_NUCLEO_G031K8/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/TARGET_NUCLEO_L432KC/PinNames.h
Labels: ready for merge, release-type: patch

#15082 STM32F1: add more alternate functions
  targets/TARGET_STM/PeripheralPins.h
  targets/TARGET_STM/TARGET_STM32F1/pin_device.h
Labels: devices: st, ready for merge, release-type: patch
