Repository ARMmbed/mbed-os, pull requests merged in 2021-01, with the labels that each got.

#14045 CMake: add support for Nordic targets
  targets/TARGET_NORDIC/TARGET_NRF5x/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52832/device/TOOLCHAIN_ARM_STD/nRF52832.sct
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_NRF52840_DK/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/TARGET_SOFTDEVICE_NONE/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/components/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/integration/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_SDK_15_0/modules/CMakeLists.txt
  tools/cmake/README.md
Labels: ready for merge, release-type: patch

#14079 CMake: Add Blockdevice dependency to KVstore library
  storage/kvstore/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14108 travis: set attrs to 19.1.0, fixes python 3.5 issue
  .travis.yml
Labels: ready for merge, release-type: patch

#14112 ARM linking issue: compile out trace when not available
  connectivity/nanostack/sal-stack-nanostack/source/Common_Protocols/tcp.c
Labels: ready for merge, release-type: patch

#14074 CMake: Add cmake support for Toshiba targets
  targets/CMakeLists.txt
  targets/TARGET_TOSHIBA/CMakeLists.txt
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/CMakeLists.txt
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/device/TOOLCHAIN_ARM_STD/tmpm46bf10fg.sct
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/CMakeLists.txt
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/device/TOOLCHAIN_ARM_STD/tmpm4g9f15.sct
  tools/cmake/README.md
Labels: ready for merge, release-type: patch

#14084 BLE: Fix GattServer callbacks not being copied to GattServer instance of the service
  connectivity/FEATURE_BLE/include/ble/GattServer.h
  connectivity/FEATURE_BLE/source/cordio/source/GattServerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/GattServerImpl.h
Labels: needs: CI, release-type: patch

#14078 CMake: Add support for OSPIF blockdevice
  storage/CMakeLists.txt
  storage/blockdevice/CMakeLists.txt
  storage/blockdevice/COMPONENT_OSPIF/CMakeLists.txt
  storage/blockdevice/COMPONENT_OSPIF/include/OSPIF/MX25LM51245G_config.h
  storage/blockdevice/COMPONENT_OSPIF/include/OSPIF/OSPIFBlockDevice.h
Labels: ready for merge, release-type: patch

#14111 BLE: fix scanning/advertising when extended features are available but disabled on host
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.cpp
  connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/NRFCordioHCIDriver.cpp
Labels: ready for merge, release-type: patch

#14068 Enabled USBDevice in targets.json for H743ZI2
  targets/targets.json
Labels: ready for merge, release-type: patch

#14100 CMake: Fix path to Ambiq BLE source file
  connectivity/drivers/ble/FEATURE_BLE/TARGET_Ambiq_Micro/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14072 CMake: Add CMake to platform greentea test
  platform/tests/TESTS/mbed_functional/callback/CMakeLists.txt
  platform/tests/TESTS/mbed_functional/callback_big/CMakeLists.txt
  platform/tests/TESTS/mbed_functional/callback_small/CMakeLists.txt
  platform/tests/TESTS/mbed_micro/attributes/CMakeLists.txt
  platform/tests/TESTS/mbed_micro/call_before_main/CMakeLists.txt
  platform/tests/TESTS/mbed_micro/cpp/CMakeLists.txt
  platform/tests/TESTS/mbed_micro/div/CMakeLists.txt
  platform/tests/TESTS/mbed_micro/static_assert/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/CircularBuffer/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/FileHandle/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/SharedPtr/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/SingletonPtr/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/Stream/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/Transaction/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/atomic/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/crash_reporting/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/critical_section/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/error_handling/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/minimal-printf/compliance/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/stats_cpu/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/stats_heap/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/stats_sys/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/stats_thread/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/system_reset/CMakeLists.txt
  platform/tests/TESTS/mbed_platform/wait_ns/CMakeLists.txt
  tools/cmake/README.md
  tools/cmake/mbed_greentea.cmake
Labels: ready for merge, release-type: feature

#14127 BLE: Add privacy trace
  connectivity/FEATURE_BLE/source/common/ble_trace_helpers.h
  connectivity/FEATURE_BLE/source/cordio/source/PalPrivateAddressControllerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.cpp
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.cpp
Labels: component: ble, needs: preceding PR, release-version: feature branch

#14115 Deploy pinvalidate standard pin names check to Travis
  .travis.yml
Labels: release-version: feature branch

#14048 nanostack: correct Wi-SUN certificate add and remove functions on Wi-SUN interface
  connectivity/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  connectivity/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-type: patch

#14060 CMake: Add CMake to drivers greentea test
  drivers/tests/TESTS/mbed_drivers/buffered_serial/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/c_strings/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/crc/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/dev_null/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/echo/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/flashiap/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/generic_tests/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/lp_ticker/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/lp_timeout/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/lp_timer/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/mem_trace/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/race_test/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/reset_reason/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/rtc/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/sleep_lock/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/stl_features/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/ticker/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/timeout/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/timer/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/timerevent/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/unbuffered_serial/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/watchdog/CMakeLists.txt
  drivers/tests/TESTS/mbed_drivers/watchdog_reset/CMakeLists.txt
Labels: ready for merge, release-type: feature

#14135 NXP: Fix heap size formula in scatter files
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/device/TOOLCHAIN_ARM_MICRO/MKL25Z4.sct
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/TOOLCHAIN_ARM_STD/TARGET_LPC11XX/LPC1114.sct
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_ARM_STD/LPC1768.sct
Labels: ready for merge, release-type: patch

#14129 EFM32GG: Fix heap size formula in scatter files
  targets/TARGET_Silicon_Labs/TARGET_EFM32/TARGET_EFM32GG/device/TARGET_1024K/TOOLCHAIN_ARM_MICRO/efm32gg.sct
Labels: ready for merge, release-type: patch

#14088 CMake: Add support for KVstore Greentea tests
  storage/kvstore/tests/TESTS/kvstore/general_tests_phase_1/CMakeLists.txt
  storage/kvstore/tests/TESTS/kvstore/general_tests_phase_2/CMakeLists.txt
  storage/kvstore/tests/TESTS/kvstore/static_tests/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14083 Add SLEEP/DEEPSLEEP support for MAX32630FTHR
  targets/targets.json
Labels: ready for merge, release-type: patch

#14134 GigaDevice: Fix heap size formula in scatter files
  targets/TARGET_GigaDevice/TARGET_GD32F30X/TARGET_GD32F307VG/device/TOOLCHAIN_ARM_MICRO/gd32f307vg.sct
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/device/TOOLCHAIN_ARM_MICRO/gd32f450zi.sct
Labels: ready for merge, release-type: patch

#14094 CMake: Add CMake support for rtos greentea test
  rtos/tests/TESTS/mbed_rtos/MemoryPool/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/basic/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/condition_variable/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/event_flags/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/heap_and_stack/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/kernel_tick_count/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/mail/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/malloc/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/mutex/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/queue/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/semaphore/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/signals/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/systimer/CMakeLists.txt
  rtos/tests/TESTS/mbed_rtos/threads/CMakeLists.txt
Labels: ready for merge, release-type: feature

#14093 CMake: Add Support for hal greentea test
  hal/tests/TESTS/mbed_hal/common_tickers/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/common_tickers_freq/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/crc/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/critical_section/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/flash/functional_tests/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/gpio/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/lp_ticker/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/minimum_requirements/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/mpu/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/ospi/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/pinmap/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/qspi/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/reset_reason/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/rtc/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/rtc_reset/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/rtc_time/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/rtc_time_conv/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/sleep/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/sleep_manager/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/sleep_manager_racecondition/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/stack_size_unification/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/ticker/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/trng/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/us_ticker/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/watchdog/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/watchdog_reset/CMakeLists.txt
  hal/tests/TESTS/mbed_hal/watchdog_timing/CMakeLists.txt
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/CMakeLists.txt
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/analogin/CMakeLists.txt
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/gpio/CMakeLists.txt
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/gpio_irq/CMakeLists.txt
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/i2c/CMakeLists.txt
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/pwm/CMakeLists.txt
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/spi/CMakeLists.txt
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/uart/CMakeLists.txt
  hal/tests/TESTS/mbed_timing_fpga_ci_test_shield/watchdog/CMakeLists.txt
Labels: ready for merge, release-type: feature

#14095 CMake: Add CMake support for events greentea test
  events/tests/TESTS/events/equeue/CMakeLists.txt
  events/tests/TESTS/events/queue/CMakeLists.txt
  events/tests/TESTS/events/timing/CMakeLists.txt
Labels: ready for merge, release-type: feature

#14133 STM: Fix heap size formula in scatter files
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F411xE/TOOLCHAIN_ARM/stm32f411re.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TOOLCHAIN_ARM/stm32f412xg.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TOOLCHAIN_ARM/stm32f429xx.sct
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TOOLCHAIN_ARM/stm32f439xx.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L443xC/TOOLCHAIN_ARM/stm32l443xc.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L452xE/TOOLCHAIN_ARM/stm32l452xe.sct
Labels: ready for merge, release-type: patch

#14131 MUSCA_B1: Fix heap size formula in scatter files
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/device/TOOLCHAIN_ARMC6/musca_ns.sct
Labels: ready for merge, release-type: patch

#14125 BLE: Fix Security Manager key generation
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.cpp
Labels: ready for merge, release-type: patch

#14101 CMake: Add CMake support for netsocket greentea test
  connectivity/netsocket/tests/TESTS/netsocket/dns/CMakeLists.txt
  connectivity/netsocket/tests/TESTS/netsocket/nidd/CMakeLists.txt
  connectivity/netsocket/tests/TESTS/netsocket/tcp/CMakeLists.txt
  connectivity/netsocket/tests/TESTS/netsocket/tls/CMakeLists.txt
  connectivity/netsocket/tests/TESTS/netsocket/udp/CMakeLists.txt
Labels: ready for merge, release-type: feature

#14130 NRF52840: Fix heap size formula in scatter files
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/device/TOOLCHAIN_ARM_STD/nRF52840.sct
Labels: ready for merge, release-type: patch

#14090 CMake: Add support for Blockdevice Greentea tests
  storage/blockdevice/tests/TESTS/blockdevice/buffered_block_device/CMakeLists.txt
  storage/blockdevice/tests/TESTS/blockdevice/flashsim_block_device/CMakeLists.txt
  storage/blockdevice/tests/TESTS/blockdevice/general_block_device/CMakeLists.txt
  storage/blockdevice/tests/TESTS/blockdevice/heap_block_device/CMakeLists.txt
  storage/blockdevice/tests/TESTS/blockdevice/mbr_block_device/CMakeLists.txt
  storage/blockdevice/tests/TESTS/blockdevice/util_block_device/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14120 STM32F439 : correct cmake compilation
  connectivity/drivers/emac/TARGET_STM/TARGET_STM32F4/TARGET_NUCLEO_F439ZI/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_3G/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_WIO_BG96/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14103 CMake: Add support for netsocket/network Greentea tests
  connectivity/netsocket/tests/TESTS/network/emac/CMakeLists.txt
  connectivity/netsocket/tests/TESTS/network/interface/CMakeLists.txt
  connectivity/netsocket/tests/TESTS/network/l3ip/CMakeLists.txt
  connectivity/netsocket/tests/TESTS/network/multihoming/CMakeLists.txt
  connectivity/netsocket/tests/TESTS/network/wifi/CMakeLists.txt
Labels: ready for merge

#14008 Add proper power save mode command format for MTS_DRAGONFLY_L471
  connectivity/drivers/cellular/MultiTech/DragonflyNano/PPP/SARA4_PPP.cpp
  connectivity/drivers/cellular/MultiTech/DragonflyNano/PPP/SARA4_PPP.h
Labels: ready for merge, release-type: patch

#14089 CMake: Add support for Filesystem Greentea tests
  storage/filesystem/tests/TESTS/filesystem/general_filesystem/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14109 Remove deprecated connectivity examples
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#14049 DISCO_L072CZ_LRWAN1: enable LORA by default
  connectivity/drivers/lora/COMPONENT_SX126X/mbed_lib.json
  connectivity/drivers/lora/COMPONENT_SX1272/SX1272_LoRaRadio.h
  connectivity/drivers/lora/COMPONENT_SX1272/mbed_lib.json
  connectivity/drivers/lora/COMPONENT_SX1276/SX1276_LoRaRadio.h
  connectivity/drivers/lora/COMPONENT_SX1276/mbed_lib.json
  connectivity/lorawan/mbed_lib.json
  connectivity/lorawan/tests/TESTS/lorawan/loraradio/README.md
  connectivity/lorawan/tests/TESTS/lorawan/loraradio/main.cpp
  connectivity/lorawan/tests/TESTS/lorawan/loraradio/template_mbed_app.txt
  targets/targets.json
Labels: ready for merge, release-type: patch

#14104 CMake: Fix the listing of system_clock.c for STM32F413xH
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_MTS_DRAGONFLY_F413RH/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_NUCLEO_F413ZH/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14020 Add SPI bitwidths to ST targets where supported
  drivers/include/drivers/SPI.h
  targets/TARGET_STM/TARGET_STM32F0/spi_device.h
  targets/TARGET_STM/TARGET_STM32F1/spi_device.h
  targets/TARGET_STM/TARGET_STM32F2/spi_device.h
  targets/TARGET_STM/TARGET_STM32F3/spi_device.h
  targets/TARGET_STM/TARGET_STM32F4/spi_device.h
  targets/TARGET_STM/TARGET_STM32F7/spi_device.h
  targets/TARGET_STM/TARGET_STM32G0/spi_device.h
  targets/TARGET_STM/TARGET_STM32G4/spi_device.h
  targets/TARGET_STM/TARGET_STM32H7/spi_device.h
  targets/TARGET_STM/TARGET_STM32L0/spi_device.h
  targets/TARGET_STM/TARGET_STM32L1/spi_device.h
  targets/TARGET_STM/TARGET_STM32L4/spi_device.h
  targets/TARGET_STM/TARGET_STM32L5/spi_device.h
  targets/TARGET_STM/TARGET_STM32WB/spi_device.h
  targets/TARGET_STM/stm_spi_api.c
Labels: ready for merge, release-type: patch

#14138 Add traces to HCI, BLE instance, Security DB and WSF cordio traces
  connectivity/FEATURE_BLE/libraries/cordio_stack/wsf/include/wsf_trace.h
  connectivity/FEATURE_BLE/mbed_lib.json
  connectivity/FEATURE_BLE/source/common/ble_trace_helpers.cpp
  connectivity/FEATURE_BLE/source/common/ble_trace_helpers.h
  connectivity/FEATURE_BLE/source/cordio/CMakeLists.txt
  connectivity/FEATURE_BLE/source/cordio/driver/CordioHCIDriver.cpp
  connectivity/FEATURE_BLE/source/cordio/driver/CordioHCITransportDriver.cpp
  connectivity/FEATURE_BLE/source/cordio/mbed_lib.json
  connectivity/FEATURE_BLE/source/cordio/source/BLEInstanceBaseImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalPrivateAddressControllerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/PalSecurityManagerImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/stack_adaptation/mbed_wsf_trace.c
  connectivity/FEATURE_BLE/source/cordio/stack_adaptation/mbed_wsf_trace.h
  connectivity/FEATURE_BLE/source/generic/FileSecurityDb.cpp
  connectivity/FEATURE_BLE/source/generic/FileSecurityDb.h
  connectivity/FEATURE_BLE/source/generic/KVStoreSecurityDb.cpp
  connectivity/FEATURE_BLE/source/generic/KVStoreSecurityDb.h
  connectivity/FEATURE_BLE/source/generic/MemorySecurityDb.h
  connectivity/FEATURE_BLE/source/generic/SecurityDb.h
  connectivity/FEATURE_BLE/source/generic/SecurityManagerImpl.cpp
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_2/BlueNrg2HCIDriver.cpp
  connectivity/drivers/ble/FEATURE_BLE/TARGET_STM32WB/HCIDriver.cpp
Labels: needs: CI, release-version: feature branch

#14032 STM32: RESET GPIO during init is configurable
  targets/TARGET_STM/mbed_overrides.c
  targets/targets.json
Labels: ready for merge, release-type: patch

#14145 STM32H7: disable uSD transceiver
  targets/TARGET_STM/TARGET_STM32H7/STM32Cube_FW/stm32h7xx_hal_conf.h
Labels: ready for merge, release-type: feature

#14143 Travis: Remove make.py test for events and littlefs
  .travis.yml
Labels: ready for merge, release-type: patch

#14087 Update events period method to check for invalid values
  events/include/events/Event.h
  events/tests/TESTS/events/queue/main.cpp
Labels: ready for merge

#14149 STM32G4: enable TRNG and correct dual bank flash detection
  targets/TARGET_STM/TARGET_STM32G4/TARGET_STM32G474xE/system_clock.c
  targets/TARGET_STM/TARGET_STM32G4/flash_api.c
  targets/TARGET_STM/trng_api.c
  targets/targets.json
Labels: ready for merge, release-type: patch

#14166 ARDUINO_NANO33BLE: don't define Arduino pins if compiling in Arduino core
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/TARGET_MCU_NRF52840/TARGET_ARDUINO_NANO33BLE/PinNames.h
Labels: ready for merge, release-type: patch

#14154 STM32: correct cmake compilation issues
  connectivity/drivers/mbedtls/TARGET_STM/TARGET_STM32F437xG/CMakeLists.txt
  connectivity/drivers/mbedtls/TARGET_STM/TARGET_STM32F756xG/CMakeLists.txt
  connectivity/drivers/mbedtls/TARGET_STM/TARGET_STM32L443xC/CMakeLists.txt
  connectivity/drivers/mbedtls/TARGET_STM/TARGET_STM32L486xG/CMakeLists.txt
  connectivity/drivers/mbedtls/TARGET_STM/TARGET_STM32L4S5xI/CMakeLists.txt
  connectivity/drivers/mbedtls/TARGET_STM/TARGET_STM32L562xx/CMakeLists.txt
  connectivity/drivers/mbedtls/TARGET_STM/TARGET_STM32WB55xx/CMakeLists.txt
  targets/TARGET_STM/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103xB/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_MTS_DRAGONFLY_F411RE/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F407xE/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L072xZ/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L073xZ/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L1/TARGET_MOTE_L152RC/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L1/TARGET_NUCLEO_L152RE/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L432xC/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L433xC/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L443xC/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L476xG/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L486xG/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L496xG/TARGET_DISCO_L496AG/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L5/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L552xE/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32WB/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14091 CMake: Add support for NFC Greentea test
  connectivity/nfc/tests/TESTS/nfc/eeprom/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14076 Replace macros in MbedTester to avoid conflicts
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/include/fpga_ci_test_shield/MbedTester.h
  features/frameworks/COMPONENT_FPGA_CI_TEST_SHIELD/source/MbedTester.cpp
Labels: ready for merge, release-type: patch

#14075 Maxim targets; Add USB stack implementation
  targets/TARGET_Maxim/CMakeLists.txt
  targets/TARGET_Maxim/USBEndpoints_Maxim.h
  targets/TARGET_Maxim/USBPhyHw.h
  targets/TARGET_Maxim/USBPhy_Maxim.cpp
  targets/targets.json
Labels: needs: CI, release-type: patch

#13881 Add std::span implementation for cxxsupport
  platform/cxxsupport/mstd_iterator
  platform/cxxsupport/mstd_span
Labels: ready for merge, release-type: feature

#14167 [feature-wisun] travis: fix 3.5 test bug in attrs
  .travis.yml
Labels: ready for merge, release-version: feature branch

#14173 Update cert for testing server
  connectivity/netsocket/tests/TESTS/netsocket/tls/cert.h
Labels: needs: work, release-type: patch

#13968 CMake: Add support for all ARM SSG Mbed targets
  CMakeLists.txt
  platform/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/services/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/services/attestation/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_MBED_PSA_SRV/services/storage/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_0/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_0/TARGET_TFM_DUALCPU/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_0/TARGET_TFM_V8M/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_1/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_1/TARGET_TFM_DUALCPU/CMakeLists.txt
  platform/FEATURE_EXPERIMENTAL_API/FEATURE_PSA/TARGET_TFM/TARGET_TFM_V1_1/TARGET_TFM_V8M/CMakeLists.txt
  targets/CMakeLists.txt
  targets/TARGET_ARM_SSG/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M0P/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M3/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M4/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MPS2/TARGET_MPS2_M7/device/TOOLCHAIN_ARM_STD/MPS2.sct
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/CMakeLists.txt
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/CMakeLists.txt
  tools/cmake/README.md
  tools/cmake/cores/Cortex-M33-NS.cmake
  tools/cmake/cores/Cortex-M33.cmake
Labels: ready for merge, release-type: patch

#14155 CMAKE / M33 : DOMAIN_NS issue
  tools/cmake/cores/Cortex-M33FE-NS.cmake
  tools/cmake/cores/Cortex-M33FE.cmake
Labels: ready for merge, release-type: patch

#14148 Corrected nanostack coverity warnings
  connectivity/nanostack/mbed-mesh-api/source/NanostackEMACInterface.cpp
  connectivity/nanostack/mbed-mesh-api/source/NanostackPPPInterface.cpp
  connectivity/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_random.c
Labels: ready for merge, release-type: patch

#14080 Add bare-metal support for MAXIM targets
  targets/targets.json
Labels: ready for merge, release-type: patch

#14023 Adding QSPI support to SDP-K1 board support package.
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_SDP_K1/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F469xI/TARGET_SDP_K1/PinNames.h
  targets/targets.json
Labels: ready for merge, release-type: patch, stale

#14098 CMake: Add support for LoRaWAN Greentea tests
  connectivity/lorawan/CMakeLists.txt
  connectivity/lorawan/tests/TESTS/lorawan/loraradio/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14144 Update for Arduino Pinnames
  targets/TARGET_STM/TARGET_STM32F2/TARGET_STM32F207xG/TARGET_NUCLEO_F207ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F3/TARGET_STM32F303xE/TARGET_NUCLEO_F303ZE/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/TARGET_NUCLEO_F412ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_NUCLEO_F413ZH/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F446xE/TARGET_NUCLEO_F446ZE/PinNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F746xG/TARGET_NUCLEO_F746ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F756xG/TARGET_NUCLEO_F756ZG/PinNames.h
  targets/TARGET_STM/TARGET_STM32F7/TARGET_STM32F767xI/TARGET_NUCLEO_F767ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI2/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/TARGET_NUCLEO_H7A3ZI_Q/PinNames.h
Labels: ready for merge, release-type: patch

#14132 Apollo3: Fix heap size formula and stack start address in scatter file
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/TOOLCHAIN_ARM_STD/AMA3B1KK.sct
Labels: release-type: patch

#14126 tests: Limit PSA crypto tests to Arm-v7M targets
  connectivity/mbedtls/tests/TESTS/mbedtls/sanity/main.cpp
Labels: ready for merge, release-type: patch

#14159 CMAKE : correct "Cortex-M7F" link parameter
  tools/cmake/cores/Cortex-M7F.cmake
Labels: ready for merge, release-type: patch

#14137 Storage: Fix FATFileSystem unmount issue
  storage/filesystem/fat/source/FATFileSystem.cpp
Labels: ready for merge, release-type: patch

#14142 STM32L4: Correct heap size formula
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L443xC/TOOLCHAIN_ARM/stm32l443xc.sct
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L452xE/TOOLCHAIN_ARM/stm32l452xe.sct
Labels: ready for merge, release-type: patch

#14099 CMake: Add support for CORDIO Greentea tests
  connectivity/FEATURE_BLE/source/cordio/TESTS/cordio_hci/driver/CMakeLists.txt
  connectivity/FEATURE_BLE/source/cordio/TESTS/cordio_hci/transport/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14168 [mbed-os-5.15] travis: fix 3.5 test bug in attrs
  .travis.yml
Labels: Release review required, ready for merge, release-version: 5.15.7

#14165 BLE: add traces to gatt client
  connectivity/FEATURE_BLE/source/CMakeLists.txt
  connectivity/FEATURE_BLE/source/common/ble_trace_helpers.cpp
  connectivity/FEATURE_BLE/source/common/ble_trace_helpers.h
  connectivity/FEATURE_BLE/source/cordio/source/PalAttClientImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GattClientImpl.cpp
Labels: needs: work, release-version: feature branch

#14056 [feature-wisun] Fix `mbed device-management` command for Python 3.8
  requirements.txt
Labels: ready for merge, release-version: feature branch

#13954 [mbed-os-5.15] Replaced new calls with nothrow version of the call on mesh api
  features/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop_mbed.cpp
  features/nanostack/nanostack-interface/Nanostack.cpp
Labels: ready for merge, release-version: 5.15.7

#13879 mbed-os-5.15: Add FLASH, FLASHIAP & bootloader support for VK_RZ_A1H board
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/device/mmu_VK_RZ_A1H.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/TARGET_VK_RZ_A1H/mbed_drv_cfg.h
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/flash_api.c
  targets/targets.json
Labels: ready for merge, release-version: 5.15.7

#14185 CMake: Correct ARM toolchain MCU core flags
  tools/cmake/cores/Cortex-A9.cmake
  tools/cmake/cores/Cortex-M0+.cmake
  tools/cmake/cores/Cortex-M0.cmake
  tools/cmake/cores/Cortex-M1.cmake
  tools/cmake/cores/Cortex-M23-NS.cmake
  tools/cmake/cores/Cortex-M23.cmake
  tools/cmake/cores/Cortex-M3.cmake
  tools/cmake/cores/Cortex-M33F-NS.cmake
  tools/cmake/cores/Cortex-M33F.cmake
  tools/cmake/cores/Cortex-M33FE-NS.cmake
  tools/cmake/cores/Cortex-M33FE.cmake
  tools/cmake/cores/Cortex-M4.cmake
  tools/cmake/cores/Cortex-M4F.cmake
  tools/cmake/cores/Cortex-M7.cmake
  tools/cmake/cores/Cortex-M7FD.cmake
Labels: ready for merge, release-type: patch

#14186 NXP: Fix CMake support and clean up
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/device/TOOLCHAIN_ARM_STD/TARGET_LPC11XX/LPC1114.sct
  targets/TARGET_NXP/TARGET_LPC176X/device/TOOLCHAIN_ARM_STD/LPC1768.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC54114/device/TARGET_LPC54114_M4/TOOLCHAIN_ARM_STD/LPC54114J256_cm4.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_NS/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC55S69/TARGET_M33_S/CMakeLists.txt
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MCU_LPC546XX/device/TOOLCHAIN_ARM_STD/LPC54628J512.sct
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_ARM_STD/MIMXRT1052xxxxx.sct
Labels: ready for merge, release-type: patch

#14175 Add declaration to expose enable_* functions from SerialBase
  drivers/include/drivers/UnbufferedSerial.h
  drivers/source/UnbufferedSerial.cpp
Labels: ready for merge, release-type: patch

#14046 [mbed-os-5.15] Corrected Wi-SUN certificate add and remove functions on Wi-SUN interface
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: 5.15.7

#13920 [mbed-os-5.15] Network interface MAC address set/get
  TESTS/network/emac/emac_TestNetworkStack.cpp
  TESTS/network/emac/emac_TestNetworkStack.h
  UNITTESTS/features/netsocket/NetworkInterface/test_NetworkInterface.cpp
  UNITTESTS/stubs/NetworkInterface_stub.cpp
  features/nanostack/mbed-mesh-api/mbed-mesh-api/MeshInterfaceNanostack.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/NanostackEthernetInterface.h
  features/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEMACInterface.cpp
  features/nanostack/mbed-mesh-api/source/NanostackEthernetInterface.cpp
  features/nanostack/nanostack-interface/Nanostack.h
  features/netsocket/EMACInterface.cpp
  features/netsocket/EMACInterface.h
  features/netsocket/NetworkInterface.cpp
  features/netsocket/NetworkInterface.h
  features/netsocket/OnboardNetworkStack.h
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_ADV_WISE_1530/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_MXCHIP_EMW3166/libwiced_drivers.ar
  targets/TARGET_WICED/TOOLCHAIN_ARMC6/TARGET_MTB_USI_WM_BN_BM_22/libwiced_drivers.ar
Labels: ready for merge, release-version: 5.15.7

#14117 Add tracing to BLE GAP
  connectivity/FEATURE_BLE/source/common/ble_trace_helpers.h
  connectivity/FEATURE_BLE/source/cordio/mbed_lib.json
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
Labels: component: ble, needs: CI, release-version: feature branch

#14180 Cypress: Fix CYTFM_064B0S2_4343W CMake build
  targets/TARGET_Cypress/TARGET_PSOC6/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14191 base for ble unittests - BLE instance and mocked clasess
  UNITTESTS/stubs/BLE.cpp
  UNITTESTS/stubs/GapImpl_mock.h
  UNITTESTS/stubs/GattClientImpl_mock.h
  UNITTESTS/stubs/GattServerImpl_mock.h
  UNITTESTS/stubs/SecurityManagerImpl_mock.h
  UNITTESTS/stubs/ble_mocks.h
  UNITTESTS/stubs/source/GattServerImpl.h
  UNITTESTS/stubs/source/generic/GapImpl.h
  UNITTESTS/stubs/source/generic/GattClientImpl.h
  UNITTESTS/stubs/source/generic/SecurityManagerImpl.h
  connectivity/FEATURE_BLE/include/ble/common/BLERoles.h
  connectivity/FEATURE_BLE/tests/UNITTESTS/README.md
  connectivity/FEATURE_BLE/tests/UNITTESTS/ble_template/ble_template.cpp
  connectivity/FEATURE_BLE/tests/UNITTESTS/ble_template/unittest.cmake
Labels: needs: review, release-version: feature branch

#14200 Add Bluetooth user facing mocks
  UNITTESTS/googletest-CMakeLists.txt.in
  UNITTESTS/stubs/GapImpl_mock.h
  UNITTESTS/stubs/GattClientImpl_mock.h
  UNITTESTS/stubs/GattServerImpl_mock.h
  UNITTESTS/stubs/SecurityManagerImpl_mock.h
  connectivity/FEATURE_BLE/tests/UNITTESTS/ble_template/unittest.cmake
  connectivity/netsocket/tests/UNITTESTS/netsocket/EthernetInterface/test_EthernetInterface.cpp
  connectivity/netsocket/tests/UNITTESTS/netsocket/PPPInterface/test_PPPInterface.cpp
Labels: needs: CI, release-version: feature branch

#14161 Mesh api: Added PHY mode and channel plan IDs
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-version: feature branch

#14211 Fix gmocks
  UNITTESTS/stubs/GapImpl_mock.h
  UNITTESTS/stubs/GattClientImpl_mock.h
  UNITTESTS/stubs/GattServerImpl_mock.h
  UNITTESTS/stubs/SecurityManagerImpl_mock.h
Labels: needs: review, release-version: feature branch
