Repository ARMmbed/mbed-os, pull requests merged in 2021-06, with the labels that each got.

#14699 STM32 astyle format
  connectivity/drivers/emac/TARGET_STM/TARGET_STM32H7/TARGET_PORTENTA_H7/stm32h7_eth_init.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F070xB/system_clock.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F072xB/system_clock.c
  targets/TARGET_STM/TARGET_STM32F0/TARGET_STM32F091xC/system_clock.c
  targets/TARGET_STM/TARGET_STM32F0/cmsis_nvic.c
  targets/TARGET_STM/TARGET_STM32F0/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32F3/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F412xG/system_clock.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F413xH/TARGET_DISCO_F413ZH/TargetInit.c
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_NUCLEO_F429ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F439xI/TARGET_NUCLEO_F439ZI/PinNames.h
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G030xx/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G041xx/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G071xx/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32G4/TARGET_STM32G474xE/TARGET_NUCLEO_G474RE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_PORTENTA_H7/portenta_power.cpp
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_PORTENTA_H7/system_clock_override.c
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L073xZ/system_clock.c
  targets/TARGET_STM/TARGET_STM32L0/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_STM32L151xB/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_STM32L151xC/TARGET_XDOT_L151CC/system_clock.c
  targets/TARGET_STM/TARGET_STM32L1/TARGET_STM32L152xB/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_STM32L152xC/TARGET_MOTE_L152RC/system_clock.c
  targets/TARGET_STM/TARGET_STM32L1/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L452xE/TARGET_NUCLEO_L452RE_P/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L4/TARGET_STM32L4S5xI/TARGET_B_L4S5I_IOT01A/PinNames.h
  targets/TARGET_STM/TARGET_STM32L4/us_ticker_data.h
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L562xE/TARGET_DISCO_L562QE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5MxG/TARGET_DISCO_WB5MMG/PinNames.h
  targets/TARGET_STM/TARGET_STM32WL/TARGET_STM32WL55xC/TARGET_NUCLEO_WL55JC/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32WL/TARGET_STM32WL55xC/TARGET_NUCLEO_WL55JC/system_clock.c
  targets/TARGET_STM/TARGET_STM32WL/serial_device.c
  targets/TARGET_STM/USBPhy_STM32.cpp
  targets/TARGET_STM/can_api.c
  targets/TARGET_STM/hal_tick_overrides.c
  targets/TARGET_STM/lp_ticker.c
  targets/TARGET_STM/mbed_overrides.c
  targets/TARGET_STM/ospi_api.c
  targets/TARGET_STM/serial_api.c
  targets/TARGET_STM/sleep.c
  targets/TARGET_STM/stm_spi_api.c
Labels: component: connectivity, devices: st, ready for merge, release-type: patch, stale

#14710 BLE: support non-low power devices
  connectivity/FEATURE_BLE/source/cordio/source/BLEInstanceBaseImpl.cpp
  connectivity/FEATURE_BLE/source/cordio/source/BLEInstanceBaseImpl.h
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
  connectivity/FEATURE_BLE/source/generic/PrivateAddressController.h
Labels: component: connectivity, ready for merge, release-type: patch

#14724 STM32G0: correct voltage scaling control
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G031xx/TARGET_NUCLEO_G031K8/system_clock.c
  targets/TARGET_STM/TARGET_STM32G0/TARGET_STM32G071xx/TARGET_NUCLEO_G071RB/system_clock.c
Labels: devices: st, ready for merge, release-type: patch

#14686 STM32: correct __cplusplus brackets
  targets/TARGET_STM/TARGET_STM32F0/can_device.h
  targets/TARGET_STM/TARGET_STM32F0/i2c_device.h
  targets/TARGET_STM/TARGET_STM32F1/can_device.h
  targets/TARGET_STM/TARGET_STM32F1/i2c_device.h
  targets/TARGET_STM/TARGET_STM32F2/can_device.h
  targets/TARGET_STM/TARGET_STM32F2/i2c_device.h
  targets/TARGET_STM/TARGET_STM32F3/can_device.h
  targets/TARGET_STM/TARGET_STM32F3/i2c_device.h
  targets/TARGET_STM/TARGET_STM32F4/can_device.h
  targets/TARGET_STM/TARGET_STM32F4/i2c_device.h
  targets/TARGET_STM/TARGET_STM32F7/can_device.h
  targets/TARGET_STM/TARGET_STM32F7/i2c_device.h
  targets/TARGET_STM/TARGET_STM32G0/i2c_device.h
  targets/TARGET_STM/TARGET_STM32G4/i2c_device.h
  targets/TARGET_STM/TARGET_STM32H7/i2c_device.h
  targets/TARGET_STM/TARGET_STM32L0/i2c_device.h
  targets/TARGET_STM/TARGET_STM32L1/i2c_device.h
  targets/TARGET_STM/TARGET_STM32L4/can_device.h
  targets/TARGET_STM/TARGET_STM32L4/i2c_device.h
  targets/TARGET_STM/TARGET_STM32L5/can_device.h
  targets/TARGET_STM/TARGET_STM32L5/i2c_device.h
  targets/TARGET_STM/TARGET_STM32WB/i2c_device.h
  targets/TARGET_STM/TARGET_STM32WL/i2c_device.h
Labels: devices: st, ready for merge, release-type: patch

#14073 Feature nrf52 low power ble
  connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/CMakeLists.txt
  connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/NRFCordioHCIDriver.cpp
  connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_bb_ble.c
  connectivity/drivers/ble/FEATURE_BLE/TARGET_NORDIC/TARGET_NORDIC_CORDIO/TARGET_NRF5x/stack/sources/pal_rtc.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/CMakeLists.txt
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/common_rtc.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/common_rtc.h
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/sleep.c
Labels: do not merge, needs: work, release-version: feature branch, stale

#14701 Add Travis test to make sure text files are UTF-8 encoded
  .travis.yml
  connectivity/drivers/ble/FEATURE_BLE/TARGET_STM32WB/STM32Cube_FW/shci.h
Labels: ready for merge, release-type: patch

#14720 STM32L5: corrected voltage scaling when using MSI
  targets/TARGET_STM/TARGET_STM32L5/system_clock.c
Labels: devices: st, ready for merge, release-type: patch

#14669 STM32L152: Added ADC Bank_B functionality
  targets/TARGET_STM/PinNamesTypes.h
  targets/TARGET_STM/TARGET_STM32L1/TARGET_STM32L152xE/TARGET_NUCLEO_L152RE/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32L1/analogin_device.c
Labels: devices: st, ready for merge

#14221 Enable the RWW function of Macronix Flash MX25LW51245G in OSPI block device driver
  storage/blockdevice/COMPONENT_OSPIF/include/OSPIF/MX25LM51245G_config.h
  storage/blockdevice/COMPONENT_OSPIF/include/OSPIF/MX25LW51245G_config.h
  storage/blockdevice/COMPONENT_OSPIF/include/OSPIF/OSPIFBlockDevice.h
  storage/blockdevice/COMPONENT_OSPIF/source/OSPIFBlockDevice.cpp
  storage/blockdevice/tests/TESTS/blockdevice/general_block_device/main.cpp
  targets/TARGET_STM/ospi_api.c
Labels: ready for merge, release-type: feature

#14722 STM32 TRNG: update init to match all configs
  targets/TARGET_STM/TARGET_STM32L5/STM32Cube_FW/STM32L5xx_HAL_Driver/stm32l5xx_hal_rng.c
  targets/TARGET_STM/trng_api.c
Labels: devices: st, ready for merge, release-type: patch

#14692 STM32WB: improve FLASH size
  connectivity/drivers/ble/FEATURE_BLE/TARGET_STM32WB/HCIDriver.cpp
  targets/TARGET_STM/TARGET_STM32WB/README.md
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xG/TOOLCHAIN_ARM/stm32wb55xg.sct
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xG/TOOLCHAIN_GCC_ARM/stm32wb55xg.ld
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xG/TOOLCHAIN_IAR/stm32wb55xg.icf
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB55xG/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5MxG/TOOLCHAIN_ARM/stm32wb5mxg.sct
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5MxG/TOOLCHAIN_GCC_ARM/stm32wb5mxg.ld
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5MxG/TOOLCHAIN_IAR/stm32wb5mxg.icf
  targets/TARGET_STM/TARGET_STM32WB/TARGET_STM32WB5MxG/cmsis_nvic.h
  targets/TARGET_STM/TARGET_STM32WB/flash_api.c
  targets/TARGET_STM/TARGET_STM32WB/flash_data.h
  targets/TARGET_STM/TARGET_STM32WB/stm32wb_ble_update.jpg
  targets/targets.json
Labels: devices: st, ready for merge, release-type: patch

#14738 Gate ticker (timer0) clock on deepsleep for MAX32620FTHR
  targets/TARGET_Maxim/TARGET_MAX32620C/sleep.c
Labels: devices: maxim, ready for merge, release-type: patch

#14670 STM32: add information in README for SLEEP feature
  targets/TARGET_STM/README.md
Labels: devices: st, ready for merge, release-type: patch, stale

#14739 M2354: Substitute HIRC for HXT to clock PLL
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/README.md
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/bl2.bin
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/tfm_s.bin
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/platform_extra_secure.c
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/platform_extra_secure.h
  targets/targets.json
Labels: devices: nuvoton, ready for merge, release-type: patch

#14736 STM32 USB: update init
  targets/TARGET_STM/USBPhy_STM32.cpp
Labels: devices: st, ready for merge, release-type: patch

#14675 i2c: `start()` should aquire the bus
  drivers/source/I2C.cpp
Labels: component: core, component: hal, ready for merge, release-type: patch

#14721 Nuvoton: Enable no HXT/LXT configurability
  targets/TARGET_NUVOTON/TARGET_M251/device/system_M251.h
  targets/TARGET_NUVOTON/TARGET_M251/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M251/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_M251/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_M261/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M261/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_M261/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_M261/trng_api.cpp
  targets/TARGET_NUVOTON/TARGET_M451/device/startup_M451Series.c
  targets/TARGET_NUVOTON/TARGET_M451/device/system_M451Series.c
  targets/TARGET_NUVOTON/TARGET_M451/device/system_M451Series.h
  targets/TARGET_NUVOTON/TARGET_M451/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M451/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_M451/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_M451/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_M451/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_M480/device/system_M480.c
  targets/TARGET_NUVOTON/TARGET_M480/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_M480/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_M480/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_M480/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_NANO100/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_NANO100/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_NANO100/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/lp_ticker.c
  targets/TARGET_NUVOTON/TARGET_NUC472/mbed_overrides.c
  targets/TARGET_NUVOTON/TARGET_NUC472/rtc_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/us_ticker.c
  targets/TARGET_NUVOTON/TARGET_NUC472/watchdog_api.c
  targets/targets.json
Labels: devices: nuvoton, ready for merge, release-type: patch, stale

#14733 STM32H7 ADC : dual pad feature update
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI2/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H743xI/TARGET_NUCLEO_H743ZI2/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_DISCO_H747I/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H747xI/TARGET_PORTENTA_H7/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/TARGET_NUCLEO_H7A3ZI_Q/PeripheralPins.c
  targets/TARGET_STM/TARGET_STM32H7/TARGET_STM32H7A3xIQ/TARGET_NUCLEO_H7A3ZI_Q/PinNames.h
  targets/TARGET_STM/TARGET_STM32H7/analogin_device.c
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/TARGET_STM/gpio_api.c
  targets/TARGET_STM/pinmap.c
  targets/TARGET_STM/tools/STM32_gen_PeripheralPins.py
Labels: devices: st, ready for merge, release-type: patch

#14729 tools/STM32 Modified Python script generates Peripheral Pins
  targets/TARGET_STM/tools/STM32_gen_PeripheralPins.py
Labels: devices: st, ready for merge, release-type: patch, stale

#14672 BLE: Fix advertising start and stop
  connectivity/FEATURE_BLE/include/ble/Gap.h
  connectivity/FEATURE_BLE/include/ble/gap/Events.h
  connectivity/FEATURE_BLE/mbed_lib.json
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.h
  connectivity/FEATURE_BLE/source/pal/PalEventQueue.h
Labels: component: connectivity, ready for merge, release-type: patch

#14744 test examples: remove tls socket, it was deprecated some time ago
  tools/test/examples/examples.json
Labels: ready for merge, release-version: 5.15.8

#14745 mbed-os-5.15: remove python 2.7 tests from travis
  .travis.yml
Labels: Release review required, ready for merge

#14753 Add mbed prefix into atomic
  platform/cxxsupport/mstd_atomic
Labels: component: core, ready for merge, release-type: patch

#14617 Add legacy I2C/SPI pin aliases
  hal/include/hal/PinNameAliases.h
Labels: component: hal, ready for merge, release-type: patch

#14498 UARTSerial writes even if tx is disabled
  drivers/UARTSerial.h
  drivers/source/UARTSerial.cpp
Labels: ready for merge, release-version: 5.15.8

#14693 Fix compilation errors with kvstore - TDB_INTERNAL option to store BLE bonding info
  connectivity/FEATURE_BLE/source/generic/CMakeLists.txt
Labels: component: connectivity, ready for merge, release-type: patch

#14704 Pin name tests update
  hal/tests/TESTS/pin_names/arduino_uno/main.cpp
  hal/tests/TESTS/pin_names/generic/main.cpp
Labels: component: hal, ready for merge, release-type: patch

#14740 Fix 'netsocket: several dynamic allocation results not checked' (#14210)
  connectivity/netsocket/include/netsocket/NetworkInterface.h
  connectivity/netsocket/mbed_lib.json
  connectivity/netsocket/source/NetworkInterface.cpp
  connectivity/netsocket/source/TCPSocket.cpp
  connectivity/netsocket/source/TLSSocketWrapper.cpp
  connectivity/netsocket/source/nsapi_dns.cpp
  tools/test/travis-ci/doxy-spellchecker/ignore.en.pws
Labels: component: connectivity, component: tools, ready for merge, release-type: feature

#14713 lgtm: Add initial LGTM configuration file
  .lgtm.yml
Labels: needs: review, release-type: patch

#14756 mbedtls: Add an alt implementation of timing
  connectivity/mbedtls/CMakeLists.txt
  connectivity/mbedtls/include/mbedtls/check_config.h
  connectivity/mbedtls/platform/inc/timing_alt.h
  connectivity/mbedtls/platform/src/timing.cpp
Labels: component: security, ready for merge, release-type: patch

#14659 STM32: make i2c_salve_read return the number of bytes read
  targets/TARGET_STM/TARGET_STM32F0/objects.h
  targets/TARGET_STM/TARGET_STM32F1/objects.h
  targets/TARGET_STM/TARGET_STM32F2/objects.h
  targets/TARGET_STM/TARGET_STM32F3/objects.h
  targets/TARGET_STM/TARGET_STM32F4/objects.h
  targets/TARGET_STM/TARGET_STM32F7/objects.h
  targets/TARGET_STM/TARGET_STM32G0/objects.h
  targets/TARGET_STM/TARGET_STM32G4/objects.h
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/TARGET_STM/TARGET_STM32L0/objects.h
  targets/TARGET_STM/TARGET_STM32L1/objects.h
  targets/TARGET_STM/TARGET_STM32L4/objects.h
  targets/TARGET_STM/TARGET_STM32L5/objects.h
  targets/TARGET_STM/TARGET_STM32WB/objects.h
  targets/TARGET_STM/TARGET_STM32WL/objects.h
  targets/TARGET_STM/i2c_api.c
Labels: devices: st, ready for merge, release-type: patch

#14682 [mbed-os-5.15] Update mbed-coap to version v5.1.10
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/Makefile.test
  features/frameworks/mbed-coap/mbed-coap/sn_coap_header.h
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/run_unit_tests.sh
  features/frameworks/mbed-coap/run_unit_tests_with_valgrind.sh
  features/frameworks/mbed-coap/source/include/sn_coap_header_internal.h
  features/frameworks/mbed-coap/source/include/sn_coap_protocol_internal.h
  features/frameworks/mbed-coap/source/sn_coap_builder.c
  features/frameworks/mbed-coap/source/sn_coap_parser.c
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.15.8

#14737 BLE: Add cmake unittest fakes for BLE and events
  UNITTESTS/CMakeLists.txt
  UNITTESTS/fakes/CMakeLists.txt
  UNITTESTS/fakes/ble/BLE.cpp
  UNITTESTS/fakes/ble/CMakeLists.txt
  UNITTESTS/fakes/ble/GapImpl_mock.h
  UNITTESTS/fakes/ble/GattClientImpl_mock.h
  UNITTESTS/fakes/ble/GattServerImpl_mock.h
  UNITTESTS/fakes/ble/SecurityManagerImpl_mock.h
  UNITTESTS/fakes/ble/ble_mocks.h
  UNITTESTS/fakes/ble/source/GattServerImpl.h
  UNITTESTS/fakes/ble/source/GattServerImpl_mock.cpp
  UNITTESTS/fakes/ble/source/generic/GapImpl.h
  UNITTESTS/fakes/ble/source/generic/GattClientImpl.h
  UNITTESTS/fakes/ble/source/generic/SecurityManagerImpl.h
  UNITTESTS/fakes/events/CMakeLists.txt
  UNITTESTS/fakes/events/events/EventQueue.cpp
  UNITTESTS/fakes/events/events/EventQueue.h
  UNITTESTS/target_h/platform/cxxsupport/mstd_tuple
  connectivity/FEATURE_BLE/include/ble/common/BLERoles.h
Labels: component: connectivity, component: test, ready for merge, release-type: patch

#14760 mbedtls: Rename Mbed timing implementation
  connectivity/mbedtls/CMakeLists.txt
  connectivity/mbedtls/platform/src/timing_mbed.cpp
Labels: component: security, ready for merge, release-type: patch

#14734 STM32WL LORA: HW specific out of STM32WL_LoRaRadio class
  connectivity/drivers/lora/TARGET_STM32WL/STM32WL_LoRaRadio.cpp
  connectivity/drivers/lora/TARGET_STM32WL/STM32WL_LoRaRadio.h
  connectivity/drivers/lora/TARGET_STM32WL/STM32WL_radio_driver.cpp
Labels: component: connectivity, ready for merge, release-type: patch

#14743 Nuvoton: Support watchdog on M251/M261 series
  targets/TARGET_NUVOTON/TARGET_M251/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M251/watchdog_api.c
  targets/TARGET_NUVOTON/TARGET_M261/CMakeLists.txt
  targets/TARGET_NUVOTON/TARGET_M261/watchdog_api.c
  targets/targets.json
Labels: devices: nuvoton, ready for merge, release-type: patch

#14765 Fix unittest check
  CMakeLists.txt
  UNITTESTS/CMakeLists.txt
  UNITTESTS/stubs/CMakeLists.txt
  connectivity/cellular/CMakeLists.txt
  connectivity/lorawan/CMakeLists.txt
  connectivity/netsocket/CMakeLists.txt
  drivers/CMakeLists.txt
  events/CMakeLists.txt
  platform/CMakeLists.txt
  platform/tests/UNITTESTS/ATCmdParser/CMakeLists.txt
  storage/blockdevice/CMakeLists.txt
  storage/kvstore/filesystemstore/CMakeLists.txt
  storage/kvstore/tdbstore/CMakeLists.txt
Labels: component: connectivity, component: core, component: hal, component: test, ready for merge, release-type: patch

#14750 Increase SPI stack size to 2048 for BlueNrg driver
  connectivity/drivers/ble/FEATURE_BLE/COMPONENT_BlueNRG_2/BlueNrg2HCIDriver.cpp
Labels: component: connectivity, ready for merge, release-type: patch

#14741 MbedTLS: Add definition checks for TRNG
  connectivity/mbedtls/platform/inc/platform_mbed.h
Labels: component: security, ready for merge, release-type: patch

#14767 connectivity tests: early skip fix
  connectivity/lorawan/tests/TESTS/lorawan/loraradio/main.cpp
  connectivity/nfc/tests/TESTS/nfc/eeprom/main.cpp
Labels: component: connectivity, ready for merge, release-type: patch

#14768 Update mbed-coap to version v5.1.11
  connectivity/libraries/mbed-coap/CHANGELOG.md
  connectivity/libraries/mbed-coap/source/sn_coap_protocol.c
Labels: component: mesh, ready for merge, release-type: patch

#14771 connectivity tests: Early test skip
  TESTS/lorawan/loraradio/main.cpp
  TESTS/nfc/eeprom/main.cpp
Labels: ready for merge, release-version: 5.15.8

#14597 LPC15xx extended CAN fix (5.15)
  targets/TARGET_NXP/TARGET_LPC15XX/can_api.c
Labels: ready for merge, release-version: 5.15.8

#14772 Improve implementation of Mbed TLS timing
  TESTS/configs/mbedtls.json
  connectivity/mbedtls/include/mbedtls/config-no-entropy.h
  connectivity/mbedtls/include/mbedtls/config.h
  connectivity/mbedtls/platform/inc/timing_alt.h
  connectivity/mbedtls/platform/src/timing_mbed.cpp
  connectivity/mbedtls/tests/TESTS/mbedtls/selftest/main.cpp
  connectivity/mbedtls/tools/importer/adjust-config.sh
  connectivity/mbedtls/tools/importer/adjust-no-entropy-config.sh
Labels: component: security, ready for merge, release-type: patch

#14752 LWIP Broadcast socket option added
  connectivity/lwipstack/source/LWIPStack.cpp
  connectivity/netsocket/include/netsocket/nsapi_types.h
Labels: component: connectivity, ready for merge, release-type: feature

#14747 BLE: fix advertising set termination event
  connectivity/FEATURE_BLE/include/ble/common/blecommon.h
  connectivity/FEATURE_BLE/include/ble/gap/Events.h
  connectivity/FEATURE_BLE/libraries/cordio_stack/ble-host/sources/stack/dm/dm_adv_ae.c
  connectivity/FEATURE_BLE/source/cordio/source/PalGapImpl.cpp
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
  connectivity/FEATURE_BLE/source/pal/PalGap.h
Labels: component: connectivity, ready for merge, release-type: patch

#14749 Fcntl setting improvement,
  platform/source/mbed_retarget.cpp
Labels: ready for merge, release-type: patch

#14797 run example-tls on faster K64F board (than K66F)
  tools/test/examples/examples.json
Labels: ready for merge, release-type: patch

#14801 BKE: fix statements outside correct feature guard blocks
  connectivity/FEATURE_BLE/source/generic/GapImpl.cpp
Labels: ready for merge, release-type: patch

#14618 mbed-os-5.15: Add API to get Wi-SUN Neighbor Table
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/mbed-mesh-api/mesh_interface_types.h
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: 5.15.8

#14770 mbed-os-5.15: Update mbed-coap to version 5.1.11
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: 5.15.8

#14464 mbed-os-5.15: Added new start methods to Wi-SUN BR with WisunInterface parameter and deprecated the old ones
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunBorderRouter.h
  features/nanostack/mbed-mesh-api/source/WisunBorderRouter.cpp
Labels: ready for merge, release-version: 5.15.8

#14806 [feature-wisun] test examples: remove tls socket, it was deprecated some time ago
  tools/test/examples/examples.json
Labels: ready for merge, release-version: feature branch

#14552 mbed-os-5.15: Add API to reset MAC statistics and Wi-SUN statistics
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
  features/nanostack/mbed-mesh-api/source/include/wisun_tasklet.h
  features/nanostack/mbed-mesh-api/source/wisun_tasklet.c
Labels: ready for merge, release-version: 5.15.8

#14566 mbed-os-5.15: Mesh api: Added PHY mode, channel plan IDs and configuration functions
  features/nanostack/mbed-mesh-api/mbed-mesh-api/WisunInterface.h
  features/nanostack/mbed-mesh-api/mbed_lib.json
  features/nanostack/mbed-mesh-api/source/WisunInterface.cpp
Labels: ready for merge, release-version: 5.15.8

#14769 [FEATURE-WISUN] Update mbed-coap to version 5.1.11
  features/frameworks/mbed-coap/CHANGELOG.md
  features/frameworks/mbed-coap/Makefile.test
  features/frameworks/mbed-coap/mbed-coap/sn_coap_header.h
  features/frameworks/mbed-coap/mbed-coap/sn_config.h
  features/frameworks/mbed-coap/source/include/sn_coap_header_internal.h
  features/frameworks/mbed-coap/source/include/sn_coap_protocol_internal.h
  features/frameworks/mbed-coap/source/sn_coap_builder.c
  features/frameworks/mbed-coap/source/sn_coap_parser.c
  features/frameworks/mbed-coap/source/sn_coap_protocol.c
Labels: ready for merge, release-version: feature branch

#14813 CMake: unit-tests: Make drivers unittests only depend on headers it uses
  drivers/tests/UNITTESTS/PwmOut/CMakeLists.txt
  drivers/tests/UNITTESTS/Watchdog/CMakeLists.txt
Labels: component: core, component: hal, ready for merge, release-type: patch

#14786 Move mbed-stubs-drivers to the drivers directory
  UNITTESTS/stubs/CMakeLists.txt
  drivers/tests/UNITTESTS/CMakeLists.txt
  drivers/tests/UNITTESTS/doubles/BufferedSerial_stub.cpp
  drivers/tests/UNITTESTS/doubles/CMakeLists.txt
  drivers/tests/UNITTESTS/doubles/SerialBase_stub.cpp
Labels: component: core, component: hal, component: test, ready for merge, release-type: patch

#14778 CAN TxIRq callback never called -STM32G474
  targets/TARGET_STM/can_api.c
Labels: devices: st, ready for merge, release-type: patch

#14814 BG96: Add correct get_ip_address implementation
  connectivity/drivers/cellular/QUECTEL/BG96/QUECTEL_BG96_CellularStack.cpp
  connectivity/drivers/cellular/QUECTEL/BG96/QUECTEL_BG96_CellularStack.h
Labels: component: connectivity, ready for merge, release-type: patch

#14822 STM32H7: correction for FLASH API for CM4
  targets/TARGET_STM/TARGET_STM32H7/STM32Cube_FW/CMSIS/stm32h747xx.h
  targets/TARGET_STM/TARGET_STM32H7/flash_api.c
Labels: devices: st, ready for merge, release-type: patch

#14826 CMake: unit-tests: Make events UNITTESTS only depend on headers it uses
  events/tests/UNITTESTS/equeue/CMakeLists.txt
Labels: component: core, ready for merge, release-type: patch

#14677 Changes required in STM CAN read API
  targets/TARGET_STM/can_api.c
Labels: ready for merge, release-type: patch

#14751 Fix for fcntl() flags definition
  platform/include/platform/mbed_retarget.h
  platform/source/mbed_retarget.cpp
Labels: component: core, ready for merge, release-type: patch

#14716 Cellular: Add AT handler buffer size to configuration
  UNITTESTS/stubs/connectivity/CMakeLists.txt
  connectivity/cellular/include/cellular/framework/API/ATHandler.h
  connectivity/cellular/mbed_lib.json
  connectivity/cellular/source/framework/device/ATHandler.cpp
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularcontext/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellulardevice/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularinformation/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularnetwork/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularsms/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularstack/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/device/athandler/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/device/cellularcontext/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/device/cellulardevice/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/device/cellularstatemachine/CMakeLists.txt
  connectivity/netsocket/tests/UNITTESTS/netsocket/CellularNonIPSocket/CMakeLists.txt
Labels: ready for merge, release-type: patch

#14776 driver/i2c: STM32: I2C memory usage and time delay in read-write solved.
  targets/TARGET_STM/TARGET_STM32F0/i2c_device.c
  targets/TARGET_STM/TARGET_STM32F0/i2c_device.h
  targets/TARGET_STM/TARGET_STM32F3/i2c_device.c
  targets/TARGET_STM/TARGET_STM32F3/i2c_device.h
  targets/TARGET_STM/TARGET_STM32F7/i2c_device.c
  targets/TARGET_STM/TARGET_STM32F7/i2c_device.h
  targets/TARGET_STM/TARGET_STM32G0/i2c_device.c
  targets/TARGET_STM/TARGET_STM32G0/i2c_device.h
  targets/TARGET_STM/TARGET_STM32G4/i2c_device.c
  targets/TARGET_STM/TARGET_STM32G4/i2c_device.h
  targets/TARGET_STM/TARGET_STM32H7/i2c_device.c
  targets/TARGET_STM/TARGET_STM32H7/i2c_device.h
  targets/TARGET_STM/TARGET_STM32L0/i2c_device.c
  targets/TARGET_STM/TARGET_STM32L0/i2c_device.h
  targets/TARGET_STM/TARGET_STM32L4/i2c_device.c
  targets/TARGET_STM/TARGET_STM32L4/i2c_device.h
  targets/TARGET_STM/TARGET_STM32L5/i2c_device.c
  targets/TARGET_STM/TARGET_STM32L5/i2c_device.h
  targets/TARGET_STM/TARGET_STM32WB/i2c_device.c
  targets/TARGET_STM/TARGET_STM32WB/i2c_device.h
  targets/TARGET_STM/TARGET_STM32WL/i2c_device.c
  targets/TARGET_STM/TARGET_STM32WL/i2c_device.h
  targets/TARGET_STM/i2c_api.c
  targets/targets.json
Labels: devices: st, ready for merge, release-type: patch

#14837 K64F: Fix pin names and migrate to Arduino Uno form factor
  hal/tests/pinvalidate/pinvalidate.py
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/TARGET_MCU_K64F/TARGET_FRDM/PinNames.h
  targets/targets.json
Labels: component: hal, devices: nxp, ready for merge, release-type: patch

#14819 Move rtos stubs to the rtos directory
  UNITTESTS/stubs/CMakeLists.txt
  UNITTESTS/stubs/connectivity/CMakeLists.txt
  UNITTESTS/stubs/rtos/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularcontext/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellulardevice/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularstack/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/device/cellularstatemachine/CMakeLists.txt
  rtos/CMakeLists.txt
  rtos/tests/.mbedignore
  rtos/tests/UNITTESTS/CMakeLists.txt
  rtos/tests/UNITTESTS/doubles/CMakeLists.txt
  rtos/tests/UNITTESTS/doubles/ConditionVariable_stub.cpp
  rtos/tests/UNITTESTS/doubles/ConditionVariable_stub.h
  rtos/tests/UNITTESTS/doubles/Kernel_stub.cpp
  rtos/tests/UNITTESTS/doubles/Mutex_stub.cpp
  rtos/tests/UNITTESTS/doubles/Semaphore_stub.cpp
  rtos/tests/UNITTESTS/doubles/Semaphore_stub.h
  rtos/tests/UNITTESTS/doubles/ThisThread_stub.cpp
  rtos/tests/UNITTESTS/doubles/Thread_stub.cpp
  rtos/tests/UNITTESTS/doubles/Thread_stub.h
  rtos/tests/UNITTESTS/doubles/mbed_rtos_rtx_stub.c
  rtos/tests/UNITTESTS/doubles/rtx_mutex_stub.c
Labels: component: connectivity, component: core, component: test, ready for merge, release-type: patch

#14815 Enable PSA tests on K64F/K66F and fix missing PSA Crypto init in TLSSocketWrapper
  connectivity/mbedtls/platform/inc/platform_mbed.h
  connectivity/netsocket/source/TLSSocketWrapper.cpp
  tools/test_configs/HeapBlockDeviceAndEthernetAndExperimental.json
  tools/test_configs/config_paths.json
  tools/test_configs/experimental.json
  tools/test_configs/target_configs.json
Labels: component: tools, ready for merge, release-type: patch

#14780 Update python requirements
  .travis.yml
  requirements.txt
  tools/cmake/requirements.txt
Labels: component: tools, devices: arm, ready for merge, release-type: patch

#14834 Move connectivity cellular stubs
  UNITTESTS/stubs/CMakeLists.txt
  UNITTESTS/stubs/connectivity/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/doubles/ATHandler_stub.cpp
  connectivity/cellular/tests/UNITTESTS/doubles/AT_CellularContext_stub.cpp
  connectivity/cellular/tests/UNITTESTS/doubles/AT_CellularDevice_stub.cpp
  connectivity/cellular/tests/UNITTESTS/doubles/AT_CellularInformation_stub.cpp
  connectivity/cellular/tests/UNITTESTS/doubles/AT_CellularNetwork_stub.cpp
  connectivity/cellular/tests/UNITTESTS/doubles/AT_CellularSMS_stub.cpp
  connectivity/cellular/tests/UNITTESTS/doubles/AT_CellularStack_stub.cpp
  connectivity/cellular/tests/UNITTESTS/doubles/AT_ControlPlane_netif_stub.cpp
  connectivity/cellular/tests/UNITTESTS/doubles/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/doubles/CellularContext_stub.cpp
  connectivity/cellular/tests/UNITTESTS/doubles/CellularDevice_stub.cpp
  connectivity/cellular/tests/UNITTESTS/doubles/CellularStateMachine_stub.cpp
  connectivity/cellular/tests/UNITTESTS/doubles/CellularUtil_stub.cpp
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularcontext/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellulardevice/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularinformation/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularnetwork/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularsms/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/AT/at_cellularstack/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/common/list/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/common/util/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/device/athandler/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/device/cellularcontext/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/device/cellulardevice/CMakeLists.txt
  connectivity/cellular/tests/UNITTESTS/framework/device/cellularstatemachine/CMakeLists.txt
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/loraphyeu433/CMakeLists.txt
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/loraphykr920/CMakeLists.txt
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/loraphyus915/CMakeLists.txt
  connectivity/lorawan/tests/UNITTESTS/features/lorawan/lorawaninterface/CMakeLists.txt
  connectivity/netsocket/tests/UNITTESTS/netsocket/CellularNonIPSocket/CMakeLists.txt
Labels: component: connectivity, component: test, ready for merge, release-type: patch
