Repository ARMmbed/mbed-os, pull requests merged in 2021-11, with the labels that each got.

#15155 Add invalid data case to tdbstore ram init
  features/storage/kvstore/tdbstore/TDBStore.cpp
Labels: ready for merge, release-version: 5.15.9

#15161 M2354: Adjust TF-M configuration to fit AWS IoT application
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/tfm_s.axf
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/tfm_s.bin
Labels: ready for merge, devices: nuvoton, release-type: patch

#15152 Fix rounding bug when formatting floats with minimal_printf
  platform/source/minimal-printf/mbed_printf_implementation.c
  platform/tests/UNITTESTS/CMakeLists.txt
  platform/tests/UNITTESTS/minimal-printf/CMakeLists.txt
  platform/tests/UNITTESTS/minimal-printf/test_minimal-printf-implementation.cpp
Labels: ready for merge, component: core, release-type: patch

#14610 Power management stat : add verbosity level for MBED_SLEEP_TRACING_ENABLED
  platform/mbed_lib.json
  platform/source/mbed_power_mgmt.c
  targets/TARGET_STM/README.md
Labels: devices: st, ready for merge, component: core, release-type: patch

#15166 Change google test git tag to main
  UNITTESTS/CMakeLists.txt
Labels: ready for merge, release-type: patch

#15111 DTLSSocket - destruction while handshaking lead to error
  connectivity/netsocket/include/netsocket/DTLSSocketWrapper.h
  connectivity/netsocket/source/DTLSSocketWrapper.cpp
Labels: ready for merge, component: connectivity, release-type: patch

#15169 B_U585I_IOT02A supports OSPI
  targets/TARGET_STM/TARGET_STM32U5/TARGET_STM32U585xI/TARGET_B_U585I_IOT02A/PinNames.h
  targets/TARGET_STM/ospi_api.c
  targets/targets.json
Labels: devices: st, ready for merge, release-type: patch

#15174 M2354: Fix potential issues in TF-M
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/bl2.bin
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/partition/flash_layout.h
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/tfm_s.axf
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/tfm_s.bin
Labels: ready for merge, devices: nuvoton, release-type: patch

#15178 Add netbuf-recvinfo-enabled config to LWIP settings
  connectivity/lwipstack/mbed_lib.json
Labels: ready for merge, release-type: patch

#15177 Fix overflow at extremely low RSSI
  connectivity/lorawan/include/lorawan/LoRaRadio.h
Labels: ready for merge, component: connectivity, release-type: patch
