Repository ARMmbed/mbed-os, pull requests merged in 2022-05, with the labels that each got.

#15277 STM32L0: add MCU_STM32L071xB support
  targets/TARGET_STM/TARGET_STM32L0/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L071xB/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L071xB/TOOLCHAIN_ARM/startup_stm32l071xx.S
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L071xB/TOOLCHAIN_ARM/stm32l071xb.sct
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L071xB/TOOLCHAIN_GCC_ARM/startup_stm32l071xx.S
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L071xB/TOOLCHAIN_GCC_ARM/stm32l071xb.ld
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L071xB/TOOLCHAIN_IAR/startup_stm32l071xx.S
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L071xB/TOOLCHAIN_IAR/stm32l071xb.icf
  targets/TARGET_STM/TARGET_STM32L0/TARGET_STM32L071xB/cmsis_nvic.h
  targets/targets.json
Labels: devices: st, ready for merge, release-type: patch

#15281 Bluetooth: Inform privacy risk of using signed writes.
  connectivity/FEATURE_BLE/README.md
Labels: ready for merge, component: connectivity, release-type: patch

#15280 Support ITM tracing for Ambiq Apollo3 targets
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/CMakeLists.txt
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/itm_api.c
  targets/targets.json
Labels: ready for merge, release-type: patch, devices: sparkfun

#15282 Bluetooth: Inform privacy risk of using signed writes.
  features/FEATURE_BLE/README.md
Labels: ready for merge, release-version: 5.15.9

#15284 Fix MPS2 CM3DS ethernet driver
  connectivity/drivers/emac/TARGET_ARM_SSG/COMPONENT_SMSC9220/smsc9220_emac.cpp
  connectivity/drivers/emac/TARGET_ARM_SSG/COMPONENT_SMSC9220/smsc9220_emac_config.h
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/smsc9220_eth_drv.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/device/drivers/smsc9220_eth_drv.h
Labels: ready for merge, release-type: patch

#15286 STM32G4: Fix serial port at low speed baud
  targets/TARGET_STM/serial_api.c
Labels: devices: st, ready for merge, release-type: patch

#15289 M487: Fix crypto h/w port
  connectivity/drivers/mbedtls/TARGET_NUVOTON/TARGET_M480/des/des_alt.c
  connectivity/drivers/mbedtls/TARGET_NUVOTON/TARGET_M480/ecp/ecp_internal_alt.c
Labels: ready for merge, component: connectivity, component: security, release-type: patch
