Repository ARMmbed/mbed-os, pull requests merged in 2022-01, with the labels that each got.

#15200 M487: Fix UART 6/7 base address encoding
  targets/TARGET_NUVOTON/TARGET_M480/PeripheralNames.h
Labels: ready for merge, devices: nuvoton, release-type: patch

#15204 STM32G0 FLASH : support MCU with dual bank
  targets/TARGET_STM/TARGET_STM32G0/flash_api.c
Labels: devices: st, ready for merge, release-type: patch

#15205 Add USBDEVICE to NUCLEO_F722ZE target
  targets/targets.json
Labels: ready for merge, release-type: patch

#15206 STM32: fix SPI 16 bit mode
  targets/TARGET_STM/stm_spi_api.c
Labels: devices: st, ready for merge, release-type: patch

#15210 ST: correct LED pins for DISCO_L562QE
  targets/TARGET_STM/TARGET_STM32L5/TARGET_STM32L562xE/TARGET_DISCO_L562QE/PinNames.h
Labels: devices: st, ready for merge, release-type: patch

#15207 Add Nuvoton NuMaker-IoT-M263A CAN bus support
  targets/TARGET_NUVOTON/TARGET_M261/can_api.c
  targets/TARGET_NUVOTON/TARGET_M261/objects.h
  targets/targets.json
Labels: ready for merge, devices: nuvoton, release-type: patch

#15214 Allow unit tests to be compiled with -fno-exception
  platform/tests/UNITTESTS/doubles/mbed_assert_stub.cpp
Labels: ready for merge, component: core

#15190 Make gpio irq api portable
  drivers/include/drivers/InterruptIn.h
  drivers/source/InterruptIn.cpp
  hal/include/hal/gpio_irq_api.h
  hal/tests/TESTS/mbed_hal_fpga_ci_test_shield/gpio_irq/main.cpp
  targets/TARGET_ARM_FM/TARGET_FVP_MPS2/gpio_irq_api.c
  targets/TARGET_ARM_SSG/TARGET_CM3DS_MPS2/gpio_irq_api.c
  targets/TARGET_ARM_SSG/TARGET_MPS2/gpio_irq_api.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_B1/gpio_irq_api.c
  targets/TARGET_ARM_SSG/TARGET_MUSCA_S1/gpio_irq_api.c
  targets/TARGET_Ambiq_Micro/TARGET_Apollo3/device/gpio_irq_api.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM302X/TARGET_ADUCM3029/api/gpio_irq_api.c
  targets/TARGET_Analog_Devices/TARGET_ADUCM4X50/TARGET_ADUCM4050/api/gpio_irq_api.c
  targets/TARGET_Cypress/TARGET_PSOC6/cy_gpio_irq_api.c
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL25Z/gpio_irq_api.c
  targets/TARGET_Freescale/TARGET_KLXX/TARGET_KL46Z/gpio_irq_api.c
  targets/TARGET_Freescale/TARGET_MCUXpresso_MCUS/api/gpio_irq_api.c
  targets/TARGET_GigaDevice/TARGET_GD32F30X/gpio_irq_api.c
  targets/TARGET_GigaDevice/TARGET_GD32F4XX/gpio_irq_api.c
  targets/TARGET_Maxim/TARGET_MAX32620C/gpio_irq_api.c
  targets/TARGET_Maxim/TARGET_MAX32625/gpio_irq_api.c
  targets/TARGET_Maxim/TARGET_MAX32630/gpio_irq_api.c
  targets/TARGET_Maxim/TARGET_MAX32660/gpio_irq_api.c
  targets/TARGET_NORDIC/TARGET_NRF5x/TARGET_NRF52/gpio_api.c
  targets/TARGET_NUVOTON/TARGET_M2354/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M251/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M261/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M451/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_M480/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_NANO100/gpio_irq_api.c
  targets/TARGET_NUVOTON/TARGET_NUC472/gpio_irq_api.c
  targets/TARGET_NXP/TARGET_LPC11XX_11CXX/gpio_irq_api.c
  targets/TARGET_NXP/TARGET_LPC176X/gpio_irq_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_IMX/gpio_irq_api.c
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_LPC/gpio_irq_api.c
  targets/TARGET_RENESAS/TARGET_RZ_A1XX/gpio_irq_api.c
  targets/TARGET_RENESAS/TARGET_RZ_A2XX/gpio_irq_api.c
  targets/TARGET_STM/gpio_irq_api.c
  targets/TARGET_Samsung/TARGET_SIDK_S1SBP6A/gpio_irq_api.c
  targets/TARGET_Samsung/TARGET_SIDK_S5JS100/gpio_irq_api.c
  targets/TARGET_Silicon_Labs/TARGET_EFM32/gpio_irq_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM46B/gpio_irq_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4G9/gpio_irq_api.c
  targets/TARGET_TOSHIBA/TARGET_TMPM4KN/gpio_irq_api.c
Labels: devices: st, devices: nxp, devices: nordic, ready for merge, devices: arm, devices: nuvoton, devices: silicon labs, component: hal, devices: renesas, devices: maxim, devices: analog devices, component: core, devices: toshiba, devices: cypress, release-type: patch, devices: samsung, devices: gigadevice, devices: sparkfun, component: test
