Repository ARMmbed/mbed-os, pull requests merged in 2022-02, with the labels that each got.

#15212 STM32H7: increase i2c slave rx limit.
  targets/TARGET_STM/TARGET_STM32F0/objects.h
  targets/TARGET_STM/TARGET_STM32F1/objects.h
  targets/TARGET_STM/TARGET_STM32F2/objects.h
  targets/TARGET_STM/TARGET_STM32F3/objects.h
  targets/TARGET_STM/TARGET_STM32F4/objects.h
  targets/TARGET_STM/TARGET_STM32F7/objects.h
  targets/TARGET_STM/TARGET_STM32G0/objects.h
  targets/TARGET_STM/TARGET_STM32G4/objects.h
  targets/TARGET_STM/TARGET_STM32H7/objects.h
  targets/TARGET_STM/TARGET_STM32L0/objects.h
  targets/TARGET_STM/TARGET_STM32L1/objects.h
  targets/TARGET_STM/TARGET_STM32L4/objects.h
  targets/TARGET_STM/TARGET_STM32L5/objects.h
  targets/TARGET_STM/TARGET_STM32U5/objects.h
  targets/TARGET_STM/TARGET_STM32WB/objects.h
  targets/TARGET_STM/TARGET_STM32WL/objects.h
Labels: devices: st, ready for merge, release-type: patch

#15219 Use MBED_FILENAME instead of __FILE__ in MBED_ASSERT
  platform/include/platform/mbed_assert.h
Labels: ready for merge, component: core, release-type: patch

#15217 Fix STM32 radio driver when bandwidth is 0
  connectivity/drivers/lora/TARGET_STM32WL/STM32WL_LoRaRadio.cpp
Labels: ready for merge, component: connectivity, release-type: patch

#15222 Fix strrchr() not declared for IAR
  platform/include/platform/mbed_toolchain.h
Labels: ready for merge, component: core, release-type: patch

#15223 CMake: Fix command line too long with Ninja/ARMClang on Windows
  CMakeLists.txt
Labels: ready for merge, release-type: patch

#15225 Fixed issue in unconfirmed_retransmission behavior
  connectivity/lorawan/source/LoRaWANStack.cpp
  connectivity/lorawan/system/lorawan_data_structures.h
Labels: ready for merge, release-type: patch

#15229 STM32H7 : fix I2C5 build error
  targets/TARGET_STM/TARGET_STM32H7/i2c_device.c
Labels: devices: st, ready for merge, release-type: patch

#15231 STM32L1: build error with STM32L151xB MCU
  targets/TARGET_STM/rtc_api.c
Labels: devices: st, ready for merge, release-type: patch

#15227 lorawan: Fix Join Request retransmission timing (Interop test)
  connectivity/lorawan/source/LoRaWANStack.cpp
Labels: ready for merge, component: connectivity, release-type: patch

#15221 Add ability to use multiple UARTs on STM32L0, STM32G0 when IRQ is shared
  targets/TARGET_STM/TARGET_STM32G0/serial_device.c
  targets/TARGET_STM/TARGET_STM32L0/serial_device.c
Labels: devices: st, ready for merge, release-type: patch
