Repository ARMmbed/mbed-os, pull requests merged in 2022-04, with the labels that each got.

#15256 STM32F1: add MCU_STM32F103xC support
  targets/TARGET_STM/TARGET_STM32F1/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103xC/CMakeLists.txt
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103xC/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103xC/TOOLCHAIN_ARM/startup_stm32f103xe.S
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103xC/TOOLCHAIN_ARM/stm32f103xc.sct
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103xC/TOOLCHAIN_GCC_ARM/startup_stm32f103xe.S
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103xC/TOOLCHAIN_GCC_ARM/stm32f103xc.ld
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103xC/TOOLCHAIN_IAR/startup_stm32f103xe.S
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103xC/TOOLCHAIN_IAR/stm32f103xc.icf
  targets/TARGET_STM/TARGET_STM32F1/TARGET_STM32F103xC/cmsis_nvic.h
  targets/targets.json
Labels: ready for merge, release-type: patch

#15258 STM32F0: Fix target codes for number of UARTs
  targets/TARGET_STM/TARGET_STM32F0/serial_device.c
Labels: devices: st, ready for merge, release-type: patch

#15261 Mbed TLS: Fix compile error with ECP alternative
  connectivity/mbedtls/source/ecp.c
Labels: ready for merge, component: security, release-type: patch

#15270 Github actions: use safe.directory for actions invoking git
  .github/workflows/basic_checks.yml
  .github/workflows/docker_management.branch.yml
  .github/workflows/docker_management.prune.yml
  .github/workflows/docker_management.release.yml
  .github/workflows/docker_management.test-PR.yml
  .github/workflows/greentea_cmake.yml
  .github/workflows/main.yml
  .github/workflows/run_conditional_ble_feature_compilation.yml
  .github/workflows/test_building_multiple_executables.yml
Labels: ready for merge, release-type: patch

#15275 GitHub actions: Update checkout version and use safe.directory
  .github/workflows/basic_checks.yml
  .github/workflows/docker_management.publish.yml
  .github/workflows/docker_management.test.yml
Labels: ready for merge, release-version: 5.15.9

#15268 STM32L0 : I2C2 was missing
  targets/TARGET_STM/TARGET_STM32L0/i2c_device.c
Labels: devices: st, ready for merge, release-type: patch

#15274 tcp_out: fix tcp_output_fill_options() arguments
  connectivity/lwipstack/lwip/src/core/lwip_tcp_out.c
Labels: ready for merge, component: connectivity, release-type: patch

#15269 STM32G4 : enable UART ASYNC
  targets/TARGET_STM/TARGET_STM32G4/PeripheralNames.h
  targets/TARGET_STM/TARGET_STM32G4/serial_device.c
  targets/targets.json
Labels: devices: st, ready for merge, release-type: patch

#15271 semihosting: Fix typo in semihost_rename
  platform/source/mbed_semihost_api.c
Labels: ready for merge, component: core, release-type: patch
