Repository ARMmbed/mbed-os, pull requests merged in 2023-06, with the labels that each got.

#15430 scancode: version >31.2.4 contains fix for reindexing
  .github/workflows/basic_checks.yml
Labels: needs: CI, release-type: patch

#15427 M2354: Fix debug failure in Mbed Studio
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/README.md
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/partition/flash_layout.h
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/partition/region_defs.h
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/s_veneers.o
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/tfm_s.axf
  targets/TARGET_NUVOTON/TARGET_M2354/TARGET_TFM/TARGET_NU_M2354/COMPONENT_TFM_S_FW/tfm_s.bin
  targets/TARGET_NUVOTON/scripts/NUVOTON.py
  tools/targets/NU_M2354.py
Labels: needs: review, release-type: patch

#15426 Fix bug uart
  targets/TARGET_Maxim/TARGET_MAX32660/serial_api.c
  targets/TARGET_Maxim/TARGET_MAX32670/serial_api.c
Labels: ready for merge, release-type: patch

#15432 doc: Update README to include production usage warning
  README.md
Labels: ready for merge, release-type: patch
