Repository ARMmbed/mbed-os, pull requests merged in 2023-01, with the labels that each got.

#15363 scancode: Fix license index failure
  .github/workflows/basic_checks.yml
Labels: ready for merge, release-type: patch

#15368 fix STM32L1 FLASH_SIZE for cat.3 devices with DEV_ID 0x436
  targets/TARGET_STM/TARGET_STM32L1/STM32Cube_FW/STM32L1xx_HAL_Driver/stm32l1xx_hal_flash.h
Labels: ready for merge

#15367 Fix mesh connect semaphore not releasing causing blockage
  connectivity/nanostack/mbed-mesh-api/source/MeshInterfaceNanostack.cpp
Labels: ready for merge, release-type: patch

#15366 Add support of NSAPI_ICMP sockets in Nanostack
  connectivity/nanostack/include/nanostack-interface/Nanostack.h
  connectivity/nanostack/source/Nanostack.cpp
Labels: ready for merge, release-type: patch

#15369 test: Disable failing tests due to echo server
  connectivity/netsocket/tests/TESTS/netsocket/tls/main.cpp
Labels: ready for merge, release-type: patch

#15373 Check CAN DLC length value
  targets/TARGET_STM/can_api.c
Labels: ready for merge, release-type: patch

#15370 Fix socket default interface ID only being used partially
  connectivity/nanostack/sal-stack-nanostack/source/Core/ns_socket.c
Labels: ready for merge, release-type: patch

#15355 Targets: NXP: IMXRT: Fixed GCC_ARM lds syntax.
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1050/device/TOOLCHAIN_GCC_ARM/MIMXRT1052xxxxx.ld
  targets/TARGET_NXP/TARGET_MCUXpresso_MCUS/TARGET_MIMXRT1170/device/TOOLCHAIN_GCC_ARM/MIMXRT1170xxxxx.ld
Labels: needs: CI, release-type: patch

#15374 CAN: read can do only up to 8 bytes, error if more is reported
  drivers/source/CAN.cpp
Labels: ready for merge, release-type: patch
